section "m01_m1_000"{
    int var0 = Parameter_GetPl1Param(12);
    switch (var0){
        case 0:
        Background_Bg_GS2("BG_HO200_?_1", 1, #1, 0);
        break ;
        case 1:
        Background_Bg_GS2("BG_HO210_?_1", 1, #1, 0);
        break ;
        case 2:
        Background_Bg_GS2("BG_HO220_?_1", 1, #1, 0);
        break ;
        case 3:
        Background_Bg_GS2("BG_HO230_?_1", 1, #1, 0);
        break ;
        }
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Argh～, I'm bored...\nI'm bored of just sleeping...)");
    SoundEffect_PlayStream(2, "SS_T_00_058_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes～...");
    SoundEffect_PlayStream(2, "SS_T_00_056_M00");
    System_Wait(90);
    SoundEffect_PlayStream(2, "SS_DSE_037_000");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 4);
    Character_Chara_GS2(1, "M1_13F", 0);
    Music_PlayBGM(0, "MN_C_01_000_D02", 127, 40);
    Voice_PlayVoice("M0101000_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Huh?\nYou look better than I thought you\nwould.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝!");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("M0101000_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ehh... So this is your room?");
    Message_Who(0);
    Message_MsgDisp("主人公", "H-Hey, anyway... What's up?");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(1, 2, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("M0101000_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "That's my line.... What's with you?\nYou took so many days off school.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, I wasn't feeling very well...\nAnyway, I'm okay now!");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(1, 3, (#1));
    Voice_PlayVoice("M0101000_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I see... Alright.\nAh, I made some sherbet and gave it\nto your parents.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wow, thanks! Huh? Your clothes...\nare you working, perhaps?");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(1, 0, (#1));
    Voice_PlayVoice("M0101000_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Yeah, I went to go buy some\nstuff....\nI feel out of place being in this\nroom.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, maybe you are. Sorry.\nYou're busy yet...");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("M0101000_A00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Hey, it might not sound very good\ncoming from me.");
    Character_BlinkStart(1, 3, (#1));
    Voice_PlayVoice("M0101000_A00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "But don't push yourself. I...\nI'm troubled when you're not there.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yeah, I won't push myself.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("M0101000_A00700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Yeah.... Promise me, okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sorry for making you worry.");
    Character_BlinkStart(1, 2, (#1));
    Voice_PlayVoice("M0101000_A00800", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It's fine....\nI kinda feel like I've gained\nsomething today.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Gained something?");
    Character_ChFace(0, 4, 1);
    Character_BlinkStart(1, 0, (#1));
    Voice_PlayVoice("M0101000_A00900", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "...\nYou sleep in those clothes, don't\nyou?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh!? ... Don't look at me.");
    Character_BlinkStart(1, 3, (#1));
    Voice_PlayVoice("M0101000_A01000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Okay. I've already seen enough....\nI'll be heading back to Sangosho\nnow.");
    Character_BlinkStart(1, 0, (#1));
    Character_ChFace(0, 4, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah. Thanks, ｛Saeki＊＊｝.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(1, "NON");
    SoundEffect_PlayStream(2, "SS_T_00_056_M00");
    System_Wait(90);
    SoundEffect_PlayStream(2, "SS_DSE_037_000");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Saeki＊＊｝ came here to\nvisit me...\nI have to get better soon!)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    }
