section "m01_m7_000"{
    int var0 = Parameter_GetPl1Param(12);
    switch (var0){
        case 0:
        Background_Bg_GS2("BG_HO200_?_1", 1, #1, 0);
        break ;
        case 1:
        Background_Bg_GS2("BG_HO210_?_1", 1, #1, 0);
        break ;
        case 2:
        Background_Bg_GS2("BG_HO220_?_1", 1, #1, 0);
        break ;
        case 3:
        Background_Bg_GS2("BG_HO230_?_1", 1, #1, 0);
        break ;
        }
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Argh～, I'm bored...\nI'm bored of just sleeping...)");
    SoundEffect_PlayStream(2, "SS_T_00_058_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes, what is it～? I'm awake.");
    SoundEffect_PlayStream(2, "SS_T_00_056_M00");
    System_Wait(90);
    Music_PlayBGM(0, "MN_C_07_002_D00", 127, 40);
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 3, 0);
    Character_Chara_GS2(7, "M7_17F", 0);
    SoundEffect_PlayStream(2, "SS_DSE_037_000");
    Voice_PlayVoice("M0107000_G00000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Are you okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝!?\nU-Umm, why--");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(7, 2, (#1));
    Voice_PlayVoice("M0107000_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Your parents let me in.\nAh, just stay where you are.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yes.");
    Character_BlinkStart(7, 0, (#1));
    Voice_PlayVoice("M0107000_G00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I came to visit.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Okay.");
    Character_ChFace(0, 4, 1);
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("M0107000_G00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "*Sigh*...\nI am a little nervous for some\nreason.\nThis is actually my first time\ninside of a girl's room.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, please do not look around my\nroom...");
    Character_ChFace(0, 2, 4);
    Voice_PlayVoice("M0107000_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Ah, sorry.... How are you feeling?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes. I am fine.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(7, 2, (#1));
    Voice_PlayVoice("M0107000_G00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "That's good.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sorry for making you come all the\nway to my house...");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("M0107000_G00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I am the one who should be\napologizing.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_BlinkStart(7, 0, (#1));
    Voice_PlayVoice("M0107000_G00700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Even though I saw you every day, I\ncould not see that you were pushing\nyourself.");
    Message_Who(0);
    Message_MsgDisp("主人公", "That's not true!\nIt isn't your fault,\n｛Wakaouji＊＊｝!");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(7, 2, (#1));
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("M0107000_G00800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Thank you.\nBut I get the feeling that I was\nforcing you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...\nPlease cheer up.");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(7, 0, (#1));
    Voice_PlayVoice("M0107000_G00900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Okay... Huh?\nAren't I the one visiting you?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, you're right!");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(7, 2, (#1));
    Voice_PlayVoice("M0107000_G01000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Haha. I see...");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("M0107000_G01100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Perhaps it was for my sake that I\ncame to visit you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Voice_PlayVoice("M0107000_G01200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Human thoughts are complex.\nYou do not know if it is for their\nsake, or for your sake.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(7, 0, (#1));
    Voice_PlayVoice("M0107000_G01300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "So let us promise each other that we\nwill both be honest.\nAnd to not force ourselves, for the\nsake of the other person.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("M0107000_G01400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Yes, that is fine.\nLet us meet again at school.\nI will be waiting.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I made ｛Wakaouji＊＊｝ worry\nquite a bit...\nI have to get better soon.)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 86, 1);
    }
