section "m01_m3_000"{
    int var0 = Parameter_GetPl1Param(12);
    switch (var0){
        case 0:
        Background_Bg_GS2("BG_HO200_?_1", 1, #1, 0);
        break ;
        case 1:
        Background_Bg_GS2("BG_HO210_?_1", 1, #1, 0);
        break ;
        case 2:
        Background_Bg_GS2("BG_HO220_?_1", 1, #1, 0);
        break ;
        case 3:
        Background_Bg_GS2("BG_HO230_?_1", 1, #1, 0);
        break ;
        }
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Argh～, I'm bored...\nI'm bored of just sleeping...)");
    SoundEffect_PlayStream(2, "SS_T_00_058_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes～...");
    SoundEffect_PlayStream(2, "SS_T_00_056_M00");
    System_Wait(90);
    SoundEffect_PlayStream(2, "SS_DSE_037_000");
    Character_ChFace(0, 0, 10);
    Character_Chara_GS2(3, "M3_??F", 0);
    Music_PlayBGM(0, "MN_C_03_004_D00", 127, 40);
    Voice_PlayVoice("M0103000_C00000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Oh.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah, ｛Hikami＊＊｝!");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("M0103000_C00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "...\nI had no intention of surprising\nyou.\nI came here to visit.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay.");
    Character_ChFace(0, 0, 6);
    Voice_PlayVoice("M0103000_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "So this is your place.......\nIt is fitting of you, in many ways.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh, what do you mean by that!?\nI'm curious.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("M0103000_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... I will not answer.\nI'm glad that you are better than I\nthought.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes, thanks to you....\nThanks for worrying about me.");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(3, 3, (#1));
    Voice_PlayVoice("M0103000_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "What are you saying?\nIs it not a given that I would come\nand visit you?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 4, 1);
    Character_BlinkStart(3, 0, (#1));
    Voice_PlayVoice("M0103000_C00500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Ah, no, umm......\nThe school is quiet when you are not\naround.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(3, 3, (#1));
    Character_ChFace(0, 3, 2);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("M0103000_C00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Ah, I am not saying that you are\nnoisy....\nI am lonely when you are not there.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hikami＊＊｝...");
    Character_ChFace(0, 4, 0);
    Character_BlinkStart(3, 0, (#1));
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("M0103000_C00700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Is what everyone says.\nThat is why I came here on their\nbehalf.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... I see, on their behalf...");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(3, 2, (#1));
    Voice_PlayVoice("M0103000_C00800", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I...It is not as if I do not think\nof this duty as a good duty,\nthough...");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("M0103000_C00900", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... Ah, right!\nI brought some notes over that were\nhanded out today.");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("M0103000_C01000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "You would want to look over them\nbefore you come back to school,\nright?\nA copy of the notes are also\nattached.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wow, such neat notes.");
    Character_ChFace(0, 4, 0);
    Character_BlinkStart(3, 2, (#1));
    Voice_PlayVoice("M0103000_C01100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "It would be nice if you did not\nworry about school and took your\ntime to rest.\nI will take my leave.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks, ｛Hikami＊＊｝.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(3, "NON");
    SoundEffect_PlayStream(2, "SS_T_00_056_M00");
    System_Wait(90);
    SoundEffect_PlayStream(2, "SS_DSE_037_000");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Thanks to ｛Hikami＊＊｝, I\nfeel better....\nI want to go to school already!)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(3, 86, 1);
    }
