section "m01_m5_000"{
    int var0 = Parameter_GetPl1Param(12);
    switch (var0){
        case 0:
        Background_Bg_GS2("BG_HO200_?_1", 1, #1, 0);
        break ;
        case 1:
        Background_Bg_GS2("BG_HO210_?_1", 1, #1, 0);
        break ;
        case 2:
        Background_Bg_GS2("BG_HO220_?_1", 1, #1, 0);
        break ;
        case 3:
        Background_Bg_GS2("BG_HO230_?_1", 1, #1, 0);
        break ;
        }
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Hmm～...\nIt's boring just sleeping all the\ntime...)");
    SoundEffect_PlayStream(2, "SS_T_00_058_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes...");
    Voice_PlayVoice("", 5, "M0105000_E00000");
    Message_Who(5);
    Message_MsgDisp("Chris", "｛主人公｝.\nHow are you feeling?");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝!?");
    Voice_PlayVoice("M0105000_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "If you are not feeling that well, I\nwill take my leave.");
    Message_Who(0);
    Message_MsgDisp("主人公", "N-No, it's fine!\nThe door is open, so come in.");
    Voice_PlayVoice("M0105000_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I won't refuse, then...");
    SoundEffect_PlayStream(2, "SS_T_00_056_M00");
    System_Wait(90);
    SoundEffect_PlayStream(2, "SS_DSE_037_000");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Character_Chara_GS2(5, "M5_01F", 0);
    Music_PlayBGM(0, "MN_C_05_002_D01", 127, 40);
    Voice_PlayVoice("M0105000_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Sorry for coming over without\ncalling...");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's fine. What's up?");
    Voice_PlayVoice("M0105000_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It doesn't matter....\nAre you really okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah.\nI'm resting today just to be sure.\nI've pretty much recovered.");
    Character_BlinkStart(5, 3, (#1));
    Voice_PlayVoice("M0105000_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I see..........");
    Message_Who(0);
    Message_MsgDisp("主人公", "... ｛Chris＊＊｝?");
    Character_BlinkStart(5, 0, (#1));
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("M0105000_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nYou know it's not a good thing to\npush yourself to the point where you\nfaint, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "......... Yeah.");
    Voice_PlayVoice("M0105000_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It's important to do your best, but\nyou gotta balance it with rest.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... That's right... Sorry.");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(5, 2, (#1));
    Voice_PlayVoice("M0105000_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I didn't want you to apologize.\nPromise me that you won't push\nyourself, okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay. I promise.");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("M0105000_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah. I feel relieved hearing that.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("M0105000_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah, right. This is a present.");
    Message_Who(0);
    Message_MsgDisp("主人公", "M-Melons!?\nAnd you brought three along...\nIt was expensive, right...?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("M0105000_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It doesn't matter if they were cheap\nor expensive～.");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(5, 3, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("M0105000_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "What's important is if you think\nit's yummy or not.");
    Character_BlinkStart(5, 0, (#1));
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("M0105000_E01300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "So, which is it?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uhh... It looks yummy.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(5, 3, (#1));
    Voice_PlayVoice("M0105000_E01400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Thank gosh.");
    SoundEffect_PlaySE(339);
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(5, 2, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("M0105000_E01500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah, my time's up. Sorry, I gotta go.");
    SoundEffect_StopSE(339, 0);
    SoundEffect_PlaySE(20);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, okay.\nThanks for coming all the way here.\nAnd for bringing melons.");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(5, 3, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("M0105000_E01600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "You're welcome.\nThese melons are so yummy.");
    Character_BlinkStart(5, 0, (#1));
    Voice_PlayVoice("M0105000_E01700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I really wanna eat them, so hurry\nand get well so you can give me your\nthanks at school.");
    Character_BlinkStart(5, 2, (#1));
    Voice_PlayVoice("M0105000_E01800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I'll be leaving then.\nI've intruded on you～.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(5, "NON");
    SoundEffect_PlayStream(2, "SS_T_00_056_M00");
    System_Wait(90);
    SoundEffect_PlayStream(2, "SS_DSE_037_000");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Thanks to ｛Chris＊＊｝, I\nfeel better...\nThanks, ｛Chris＊＊｝.)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    }
