section "b03_m7_090"{
    if ((Date_ChkDateOpen(25) == 1) || (Date_ChkDateOpen(26) == 1)){
        Character_Chara_GS2(7, "M7_17F", 0, 1, 1);
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 5);
        Background_Bg_GS2("BG_FP400_CO_0", #1, #1, 0);
        Screen_WipeIn(2);
        Message_PauseSkinship();
        Voice_PlayVoice("B0307090_G00000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Sensei is not a museum curator, so\nhe does not know this place very\nwell.");
        Voice_PlayVoice("B0307090_W00100", #1, "");
        Message_Who(0);
        Message_MsgDisp("Students", "Huh?!");
        Character_ChFace(1, 0, 11);
        Voice_PlayVoice("B0307090_G00200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "So, Sensei needs to look for someone\nwho would make a more appropriate\nteacher....\nOh.");
        Message_Who(0);
        Message_MsgDisp("主人公", "?");
        Character_ChFace(1, 2, 5);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("", 7, "B0307090_G00301");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "... ｛主人公｝.\nGive a round of applause to the\nselected teacher for today!");
        Voice_PlayVoice("B0307090_W00400", #1, "");
        Message_Who(0);
        Message_MsgDisp("Students", "Oh!");
        SoundEffect_PlayStream(2, "SS_T_00_153_S00");
        Message_ResumeSkinship();
        Message_SkinshipSet(1);
        Message_Who(0);
        Message_MsgDisp("主人公", "H-Huh!! Me?!");
        Message_SkinshipSet(0);
        SoundEffect_StopStream(2, 40);
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_Call_GS2("B04", "M7", 91);
        }
    else if (Date_ChkDateOpen(27) == 1){
        Character_Chara_GS2(7, "M7_17F", 0, 1, 1);
        Background_Bg_GS2("BG_FP400_CO_0", #1, #1, 0);
        Screen_WipeIn(2);
        Message_PauseSkinship();
        Voice_PlayVoice("B0307090_G00500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "There are notes on an important\nstory today.");
        Message_Who(0);
        Message_MsgDisp("主人公", "?");
        Voice_PlayVoice("B0307090_G00600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "The dinosaur and fossil exhibition\nis popular amongst children.\nMany are coming here today.");
        Voice_PlayVoice("B0307090_G00700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Therefore, someone has to take care\nof the small children.\nIs that okay?");
        Voice_PlayVoice("B0307090_W00800", #1, "");
        Message_Who(0);
        Message_MsgDisp("Students", "Yes!");
        Character_ChFace(1, 0, 10);
        Message_ResumeSkinship();
        Voice_PlayVoice("B0307090_G00900", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Good answer. So, let's go!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_Call_GS2("B04", "M7", 93);
        }
    else if (Date_ChkDateOpen(28) == 1){
        Character_Chara_GS2(7, "M7_17F", 0, 1, 1);
        Background_Bg_GS2("BG_FP400_CO_0", #1, #1, 0);
        Screen_WipeIn(2);
        Message_PauseSkinship();
        Voice_PlayVoice("B0307090_G01000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "The Gagi exhibition is today.\nThough he is a world-famous artist,\nhe was never recorded in textbooks.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so...?");
        Character_ChFace(1, 2, 5);
        Character_BlinkStart(7, 2, (#1), 2);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("B0307090_G01100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Yes. So, please feel it freely.");
        Character_ChFace(1, 2, 5);
        Character_BlinkStart(7, 2, (#1), 2);
        Character_ChFace(1, 3, 3);
        Message_ResumeSkinship();
        Voice_PlayVoice("B0307090_G01200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "It really helps a person to think by\nthemselves....\nOkay, let's go.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_Call_GS2("B04", "M7", 94);
        }
    else if (Date_ChkDateOpen(29) == 1){
        Character_Chara_GS2(7, "M7_17F", 0, 1, 1);
        Background_Bg_GS2("BG_FP400_CO_0", #1, #1, 0);
        Screen_WipeIn(2);
        Message_PauseSkinship();
        Voice_PlayVoice("B0307090_G01300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Today's artist is from this town.\nHe's not that far apart in age from\nall of you either.");
        Voice_PlayVoice("B0307090_W01400", #1, "");
        Message_Who(0);
        Message_MsgDisp("Students", "... Really?");
        Character_ChFace(1, 2, 5);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("B0307090_G01500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Incidentally, there is a person who\ntook care of the alma mater of this\nartist.\nI get the impression they were\nclose.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so...?");
        Character_ChFace(1, 2, 0);
        Character_ChFace(1, 3, 5);
        Message_ResumeSkinship();
        Voice_PlayVoice("B0307090_G01600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "But it is the first time I have seen\nthis picture.\nNow, shall we go? Line up, everyone.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_Call_GS2("B04", "M7", 95);
        }
    }
