section "b04_m1_053"{
    int var0 = Date_GetDateOption(2, 14);
    if (var0 == 0){
        System_GlobalWork(1, 0, 0);
        Character_ChFace(0, 0, 11);
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("B0401053_A00100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Even if you throw a hissy-fit, I'm\nnot going to buy you anything, okay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "You're like a father,\n｛Saeki＊＊｝...");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(1, "M1_D?F", 0, 1, 1, 33);
        Character_ChFace(1, 0, 0);
        Background_Bg_GS2("BG_WF500_LI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Character_ChFace(1, 2, 4);
        Character_BlinkStart(1, 2, (#1), 2);
        Character_ChFace(1, 3, 2);
        Voice_PlayVoice("B0401053_A00200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Ah, it's almost time. Let's go.");
        }
    else if (var0 == 1){
        System_GlobalWork(1, 0, 1);
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("B0401053_A00300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Ah, toffee apples.\nMaybe I should buy one...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Haha, you're like a little kid,\n｛Saeki＊＊｝.");
        Character_ChFace(0, 0, 8);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("B0401053_A00400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "So what?\nThere's nothing wrong with that...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, it's fine.\nThere's nothing wrong with that.");
        Voice_PlayVoice("B0401053_A00500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "...\nI'm just saying, it's the latest\ntrend, you know?\nThe toffee apple diet.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Really!?");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0401053_A00600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "As if something like that exists.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Geez!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(1, "M1_D?F", 0, 1, 1, 33);
        Character_ChFace(1, 0, 0);
        Background_Bg_GS2("BG_WF500_LI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Character_ChFace(1, 4, 0);
        Character_ChFace(1, 2, 4);
        Character_BlinkStart(1, 2, (#1), 2);
        Character_ChFace(1, 3, 0);
        Voice_PlayVoice("B0401053_A00700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Oh, the fireworks are about to\nstart.");
        }
    else if (var0 == 2){
        System_GlobalWork(1, 0, 2);
        Character_ChFace(0, 0, 11);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, goldfish scooping!\nDo you want to try?");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("B0401053_A00800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I'll pass. I can't do it.\nIt reminds of a nasty memory.");
        Message_Who(0);
        Message_MsgDisp("主人公", "A nasty memory?");
        Voice_PlayVoice("B0401053_A00900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "When I was in kindergarten...\nI put the goldfish I caught in a\nbowl full of sea water.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... They died, didn't they?");
        Character_BlinkStart(1, 3, (#1));
        Voice_PlayVoice("B0401053_A01000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It was horrible.\nThose guys were small, red, and\ncute.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I see...\nBut the goldfish are surely happy\nknowing that you remember them.");
        Character_BlinkStart(1, 0, (#1));
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(1, 2, (#1));
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("B0401053_A01100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Yeah...\nIt would be nice if they were.\nThanks.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(1, "M1_D?F", 0, 1, 1, 33);
        Character_ChFace(1, 0, 0);
        Background_Bg_GS2("BG_WF500_LI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Character_ChFace(1, 0, 3);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("B0401053_A01200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It's about to start, right?\nLet's go!");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    System_Call_GS2("B90", "PL", 0);
    }
