section "b04_m8_080"{
    int var0 = Date_GetDateOption(2, 24);
    if (var0 == 0){
        Character_Chara_GS2(8, "M8_??F", 0, 1, 0);
        Background_Bg_GS2("BG_FP310_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Music_PlayBGM(0, "MN_B_FP_310_000", 127, 40);
        Voice_PlayVoice("B0408080_H00000", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "That fruit over there looks yummy.");
        Message_MsgSel("It looks like you can sample them there.", "Can we eat it?", "｛Masaki＊＊｝, you're such a...");
        switch (Message_TextSelect()){
            case 0:
            Date_InData_Date(124, 3);
            Date_InData_Date(321, 1);
            Character_Chara_GS2(8, "M8_??F", 0, 1, 1);
            Character_ChFace(1, 0, 10);
            Message_PauseSkinship();
            Voice_PlayVoice("B0408080_H00100", #1, "");
            Message_Who(8);
            Message_MsgDisp("Masaki", "Let's do it!\nIt's got a good ring to it,\n\"sample\"...\nAlright, let's eat～!");
            Message_ResumeSkinship();
            Message_SkinshipSet(1);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Yeah! I made a good impression.)");
            Message_SkinshipSet(0);
            Message_SkinshipSet(0);
            break ;
            case 1:
            Date_InData_Date(124, 2);
            Date_InData_Date(321, 2);
            Character_Chara_GS2(8, "M8_??F", 0, 1, 1);
            Character_ChFace(1, 2, 5);
            Character_ChFace(1, 3, 1);
            Message_PauseSkinship();
            Voice_PlayVoice("B0408080_H00200", #1, "");
            Message_Who(8);
            Message_MsgDisp("Masaki", "... I think so. Ah, I'm hungry now.\nLet's hurry and leave so we can go\neat somewhere.");
            Message_ResumeSkinship();
            Message_SkinshipSet(1);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Uhh, I made an okay impression.)");
            Message_SkinshipSet(0);
            Message_SkinshipSet(0);
            break ;
            case 2:
            Date_InData_Date(124, 1);
            Date_InData_Date(321, 3);
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("B0408080_H00300", #1, "");
            Message_Who(8);
            Message_MsgDisp("Masaki", "It's not like I'm s-seriously gonna\neat it....\nSo look somewhere else.");
            Character_Chara_GS2(8, "M8_??F", 0, 1, 1);
            Message_SkinshipSet(1);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ugh... I made a bad impression.)");
            Message_SkinshipSet(0);
            break ;
            }
        }
    else if (var0 == 1){
        Character_Chara_GS2(8, "M8_??F", 0, 1, 0);
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 4);
        Background_Bg_GS2("BG_FP310_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Music_PlayBGM(0, "MN_B_FP_310_000", 127, 40);
        Voice_PlayVoice("B0408080_H00400", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "This tree is oddly big...");
        Message_MsgSel("I wanna climb it and sit on a branch.", "I want to move it outside.", "Honestly, it's just in the way!");
        switch (Message_TextSelect()){
            case 0:
            Date_InData_Date(124, 3);
            Date_InData_Date(321, 1);
            Character_Chara_GS2(8, "M8_??F", 0, 1, 1);
            Character_ChFace(1, 0, 10);
            Message_PauseSkinship();
            Voice_PlayVoice("B0408080_H00500", #1, "");
            Message_Who(8);
            Message_MsgDisp("Masaki", "Yeah, I wanted to do that too when I\nwas a kid!\nI also wanted to make a treehouse.");
            Message_ResumeSkinship();
            Message_SkinshipSet(1);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Yeah! I made a good impression.)");
            Message_SkinshipSet(0);
            Message_SkinshipSet(0);
            break ;
            case 1:
            Date_InData_Date(124, 2);
            Date_InData_Date(321, 2);
            Character_Chara_GS2(8, "M8_??F", 0, 1, 1);
            Character_ChFace(1, 0, 3);
            Message_PauseSkinship();
            Voice_PlayVoice("B0408080_H00600", #1, "");
            Message_Who(8);
            Message_MsgDisp("Masaki", "Right....\nThis place might be a little too\nnarrow for this one.");
            Message_ResumeSkinship();
            Message_SkinshipSet(1);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Uhh, I made an okay impression.)");
            Message_SkinshipSet(0);
            Message_SkinshipSet(0);
            break ;
            case 2:
            Date_InData_Date(124, 1);
            Date_InData_Date(321, 3);
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("B0408080_H00700", #1, "");
            Message_Who(8);
            Message_MsgDisp("Masaki", "Calm down.\nThere's no point in getting that\nannoyed, right?");
            Character_Chara_GS2(8, "M8_??F", 0, 1, 1);
            Message_SkinshipSet(1);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ugh... I made a bad impression.)");
            Message_SkinshipSet(0);
            break ;
            }
        }
    else if (var0 == 2){
        Character_Chara_GS2(8, "M8_??F", 0, 1, 0);
        Background_Bg_GS2("BG_FP310_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Music_PlayBGM(0, "MN_B_FP_310_000", 127, 40);
        Voice_PlayVoice("B0408080_H00800", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Surprisingly, I actually remember\nflower names.");
        Message_MsgSel("Then what is that?", "Of course, you work at Anneri.", "You're still not as good as Arisawa.");
        switch (Message_TextSelect()){
            case 0:
            Date_InData_Date(124, 3);
            Date_InData_Date(321, 1);
            Character_Chara_GS2(8, "M8_??F", 0, 1, 1);
            Character_ChFace(1, 0, 10);
            Message_PauseSkinship();
            Voice_PlayVoice("B0408080_H00900", #1, "");
            Message_Who(8);
            Message_MsgDisp("Masaki", "Asystasia!\nI remember it because I just\nrecently brought some to Hanegasaki\nAcademy.\nYou surprised?");
            Message_ResumeSkinship();
            Message_SkinshipSet(1);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Yeah! I made a good impression.)");
            Message_SkinshipSet(0);
            Message_SkinshipSet(0);
            break ;
            case 1:
            if (Parameter_GetCh1Param(8, 130) <= 3){
                Date_InData_Date(124, 1);
                Date_InData_Date(321, 3);
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(8, 2, (#1), 1);
                Character_ChFace(0, 3, 2);
                Voice_PlayVoice("B0408080_H01000", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "Say that when you yourself, remember\nall the names.\nOn the last order sheet you wrote\nthe names down wrong.");
                Character_Chara_GS2(8, "M8_??F", 0, 1, 1);
                Message_SkinshipSet(1);
                Message_Who(0);
                Message_MsgDisp("主人公", "(Ugh... I made a bad impression.)");
                Message_SkinshipSet(0);
                }
            else {
                Date_InData_Date(124, 5);
                Date_InData_Date(321, 1);
                Character_BlinkStart(8, 2, (#1));
                Character_ChFace(0, 3, 3);
                Voice_PlayVoice("B0408080_H01100", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "Right...\nI've been working there for so long.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Really?");
                Character_BlinkStart(8, 0, (#1));
                Voice_PlayVoice("B0408080_H01200", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "Yeah.\nAt first I was only hired for two\nweeks.");
                Character_ChFace(0, 2, 2);
                Voice_PlayVoice("B0408080_H01300", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "I thought that it would be nothing,\nbut it was really tough from day\none...");
                Character_BlinkStart(8, 3, (#1));
                Voice_PlayVoice("B0408080_H01400", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "I thought about quitting right away,\nbut that would be a bad thing to do,\nso I stayed.");
                Character_ChFace(0, 0, 10);
                Voice_PlayVoice("B0408080_H01500", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "I'm glad I stayed.\nI did good back then.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Haha. Why did you stay?");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(8, 2, (#1));
                Voice_PlayVoice("B0408080_H01600", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "Well, simply because I liked the\njob.");
                Character_ChFace(0, 0, 3);
                Voice_PlayVoice("B0408080_H01700", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "It looks easy, but you actually need\nstrength and good senses, right?\nFor displaying and arranging.");
                Voice_PlayVoice("B0408080_H01800", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "I thought those things made it quite\nan interesting job.");
                Character_ChFace(0, 2, 5);
                Character_ChFace(0, 3, 3);
                Voice_PlayVoice("B0408080_H01900", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "Anyway, I thought it'd help me out\nsomehow, but it actually ended up\nbeing a pretty fun job.");
                Character_ChFace(0, 2, 4);
                Character_BlinkStart(8, 2, (#1));
                Voice_PlayVoice("B0408080_H02000", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "Well, I still don't know what's\ngonna happen.");
                Message_Who(0);
                Message_MsgDisp("主人公", "It would be nice if things went\nwell.");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(8, 3, (#1));
                Voice_PlayVoice("B0408080_H02100", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "Yeah...\nWell, there is something else good\nabout it, apart from the work.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Eh? What is it?");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(8, 2, (#1));
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("B0408080_H02200", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "... Meetings.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Ah, the manager and Arisawa-san.\nI think that meeting people is a\ngood part of the job, too!");
                Character_ChFace(0, 2, 1);
                Voice_PlayVoice("B0408080_H02300", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "... There's also someone else.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Someone else... Ah!");
                Character_BlinkStart(8, 0, (#1));
                Character_ChFace(0, 2, 4);
                Character_ChFace(0, 3, 3);
                Voice_PlayVoice("B0408080_H02400", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "Who is it?");
                Message_Who(0);
                Message_MsgDisp("主人公", "The customers!");
                Character_ChFace(0, 4, 0);
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(8, 2, (#1));
                Character_ChFace(0, 3, 5);
                Voice_PlayVoice("B0408080_H02500", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "...\nYeah, I get to meet different\ncustomers...\nHahaha...");
                Message_Who(0);
                Message_MsgDisp("主人公", "Ah, I'm glad I met you too,\n｛Masaki＊＊｝!");
                Character_BlinkStart(8, 0, (#1));
                Character_ChFace(0, 3, 3);
                Voice_PlayVoice("B0408080_H02600", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "... Thanks.\nEven if you speak of me like I'm\nsome kinda bonus thing, I'm glad.\nYeah.");
                Character_ChFace(0, 0, 9);
                Character_BlinkStart(8, 3, (#1));
                Voice_PlayVoice("B0408080_H02700", #1, "");
                Message_Who(8);
                Message_MsgDisp("Masaki", "... So I was named last, huh.\nHmph...");
                Message_Who(0);
                Message_MsgDisp("主人公", "(｛Masaki＊＊｝...\nIs he really pouting?)");
                }
            break ;
            case 2:
            Date_InData_Date(124, 2);
            Date_InData_Date(321, 2);
            Character_Chara_GS2(8, "M8_??F", 0, 1, 1);
            Character_ChFace(1, 2, 4);
            Character_BlinkStart(8, 2, (#1), 2);
            Character_ChFace(1, 3, 2);
            Message_PauseSkinship();
            Voice_PlayVoice("B0408080_H02800", #1, "");
            Message_Who(8);
            Message_MsgDisp("Masaki", "I got no plans on trying to beat\nher.\nShe knows everything...\nRight, let's try to find her weak\npoint next time.");
            Message_ResumeSkinship();
            Message_SkinshipSet(1);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Uhh, I made an okay impression.)");
            Message_SkinshipSet(0);
            Message_SkinshipSet(0);
            break ;
            }
        }
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
