section "b04_m4_053"{
    int var0 = Date_GetDateOption(2, 14);
    if (var0 == 0){
        System_GlobalWork(1, 0, 0);
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("B0404053_D00000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Woah, like the good old days!\nI do love stuff like this.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You're having too much fun,\n｛Hariya＊＊｝.");
        Voice_PlayVoice("B0404053_D00100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Hey, I'm going to toss the ring,\ntoss the ring!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Haha, just like a kid.)");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(4, "M4_D?F", 0, 1, 1, 33);
        Character_ChFace(1, 0, 0);
        Background_Bg_GS2("BG_WF500_LI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Character_ChFace(1, 4, 0);
        Voice_PlayVoice("B0404053_D00200", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Oh, looks like the fireworks are\nabout to start!");
        }
    else if (var0 == 1){
        System_GlobalWork(1, 0, 1);
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("B0404053_D00300", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "We came on the day of the festival.\nI guess that means you're　going to\neat a lot.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, you're right.\nCotton candy, apricot candy, shaved\nice, yakisoba, and then...");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("B0404053_D00400", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Hey, hey, hey, you'd 　still want to\neat after that!?\n... Eating that much isn't normal.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Really?\nWell, maybe a cotton candy first.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("B0404053_D00500", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Okay, let's aim at eating\neverything.\nLet's go!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(4, "M4_D?F", 0, 1, 1, 33);
        Character_ChFace(1, 0, 0);
        Background_Bg_GS2("BG_WF500_LI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Character_ChFace(1, 4, 1);
        Voice_PlayVoice("B0404053_D00600", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Well, it's the fireworks turn!\nI'm getting excited!");
        }
    else if (var0 == 2){
        System_GlobalWork(1, 0, 2);
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("B0404053_D00700", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Let's do more target practice.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, let's try that!");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0404053_D00800", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "I feel sorry for the guy at the\nshop.\nI've trained myself at darts and aim\nto get everything!");
        Message_Who(0);
        Message_MsgDisp("主人公", "... It got hit, but it won't fall...");
        Character_Chara_GS2(4, "M4_D?F", 0, 0, 0);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("B0404053_D00900", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Damn～...... You should try it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay.");
        Character_ChFace(0, 0, 3);
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, I got it! Great!");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("B0404053_D01000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Seriously!? I'm not convinced, yet～!");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(4, 2, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("B0404053_D01100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "...\nRather than just aiming, a better\noption would be to try doing it\nwithout thinking...");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(4, "M4_D?F", 0, 1, 1, 33);
        Character_ChFace(1, 0, 0);
        Background_Bg_GS2("BG_WF500_LI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Character_ChFace(1, 0, 10);
        Voice_PlayVoice("B0404053_D01200", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "It's almost time!\nFinally, it's showtime!");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    System_Call_GS2("B90", "PL", 0);
    }
