section "b04_m2_053"{
    int var0 = Date_GetDateOption(2, 14);
    if (var0 == 0){
        System_GlobalWork(1, 0, 0);
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("B0402053_B00000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Don't leave my side.\nIf you get lost here, we won't be\nable to see each other again.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay, got it.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(2, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0402053_B00100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Since we're here, do you wanna eat\nsomething?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah! I want to eat a toffee apple!");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(2, 0, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0402053_B00200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Alright.\nLet's go to that store, then.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nAre the toffee apples at that store\nnice?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("B0402053_B00300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Of all the stores that sell toffee\napples, it's the most crowded, so of\ncourse it's nice.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(2, "M2_D?F", 0, 1, 1, 33);
        Character_ChFace(1, 0, 0);
        Background_Bg_GS2("BG_WF500_LI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Character_ChFace(1, 3, 4);
        Voice_PlayVoice("B0402053_B00400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Hmm...\nIt looks like the fireworks will be\nstarting soon.");
        }
    else if (var0 == 1){
        System_GlobalWork(1, 0, 1);
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("B0402053_B00500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Hm? ... Hey, that thing.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh? Ah, ring toss.\nDo you want to try,\n｛Shiba＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(2, 2, (#1));
        Voice_PlayVoice("B0402053_B00600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "No.\nI was pointing to the trophy that\nyou can win.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Wow, amazing.\nIt's about as large as a real\ntrophy.");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("B0402053_B00700", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "I wonder if you can get a ring\naround it...");
        Message_Who(0);
        Message_MsgDisp("主人公", "R-Right...\nI wonder if it's just decoration.");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("B0402053_B00800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "I wonder.... But.");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(2, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("B0402053_B00900", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "You need to get a real trophy with\nyour own strength...");
        Message_Who(0);
        Message_MsgDisp("主人公", "?");
        Character_BlinkStart(2, 0, (#1));
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0402053_B01000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Let's go around to other places.");
        Message_Who(0);
        Message_MsgDisp("主人公", "O-Okay.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(2, "M2_D?F", 0, 1, 1, 33);
        Character_ChFace(1, 0, 0);
        Background_Bg_GS2("BG_WF500_LI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Character_ChFace(1, 0, 3);
        Voice_PlayVoice("B0402053_B01100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "The fireworks are starting soon.\nLet's go.");
        }
    else if (var0 == 2){
        System_GlobalWork(1, 0, 2);
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("B0402053_B01200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "There are a lot of people...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-Yeah...\nIt really is just full of people...\nAh!");
        SoundEffect_PlayStream(3, "SS_T_00_007_M00");
        Screen_StartShakePlane(0, 32, 32, 0, 16);
        System_Wait(92);
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("B0402053_B01300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "!");
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("B0402053_B01400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Hey, are you okay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ouch...\nSomeone's shoulder bumped into me as\nthey were walking past.");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 0);
        Character_ChFace(0, 7, 0);
        Voice_PlayVoice("B0402053_B01500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "That guy...!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Shiba＊＊｝!\nI wasn't watching where I was going,\nso...");
        Message_Who(0);
        Message_MsgDisp("主人公", "And it's also crowded, so it can't\nbe helped, right?");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(2, 3, (#1));
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("B0402053_B01600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", ".........");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(2, 2, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("B0402053_B01700", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... No injuries?");
        Message_Who(0);
        Message_MsgDisp("主人公", "No, I'm fine.\nThanks for looking out for me,\n｛Shiba＊＊｝.");
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("B0402053_B01800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Yeah.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(2, "M2_D?F", 0, 1, 1, 33);
        Character_ChFace(1, 0, 0);
        Background_Bg_GS2("BG_WF500_LI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Character_ChFace(1, 2, 5);
        Character_BlinkStart(2, 0, (#1), 2);
        Character_ChFace(1, 3, 3);
        Character_ChFace(1, 4, 0);
        Voice_PlayVoice("B0402053_B01900", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "We should go, soon.\nWe have to get a good spot this\nyear, as well.");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    System_Call_GS2("B90", "PL", 0);
    }
