section "b04_m3_053"{
    int var0 = Date_GetDateOption(2, 14);
    if (var0 == 0){
        System_GlobalWork(1, 0, 0);
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("B0403053_C00000", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "... What a nice smell.\nThere is some soy sauce burning\nnearby.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, it's a grilled corn stall! ...\nMmm～. My stomach is rumbling.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0403053_C00100", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Although I want to say that we\nshould buy it, it seems like we do\nnot have the time to.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0403053_C00200", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "We must hurry up and find a good\nspot to view the fireworks from....\nCome on, let us move.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(3, "M3_D?F", 0, 1, 1, 33);
        Character_ChFace(1, 0, 0);
        Background_Bg_GS2("BG_WF500_LI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Character_ChFace(1, 0, 3);
        Voice_PlayVoice("B0403053_C00300", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "It is about to start.");
        }
    else if (var0 == 1){
        System_GlobalWork(1, 0, 1);
        Character_ChFace(0, 0, 11);
        Character_BlinkStart(3, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0403053_C00400", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "... The stalls are also bustling.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Hikami＊＊｝, there's a\ngoldfish scooping store!");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("B0403053_C00500", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "...\nDo you also want to give it a go?\nBut you do not really have anything\nthat you could keep the goldfish in,\nright?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm, that's true...");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(3, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("B0403053_C00600", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Then won't it be better to give up\non the idea so you do not regret it?");
        Character_BlinkStart(3, 0, (#1));
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("B0403053_C00700", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Also, if we want a good spot to view\nthe fireworks from, stopping is a\nwaste of time.\nSorry, but can we go?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay, I understand.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(3, "M3_D?F", 0, 1, 1, 33);
        Character_ChFace(1, 0, 0);
        Background_Bg_GS2("BG_WF500_LI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Character_ChFace(1, 2, 0);
        Character_BlinkStart(3, 2, (#1), 2);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("B0403053_C00800", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "So, the fireworks are starting.");
        }
    else if (var0 == 2){
        System_GlobalWork(1, 0, 2);
        Character_ChFace(0, 0, 11);
        Character_BlinkStart(3, 2, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("B0403053_C00900", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Are there not more stalls than\nusual, this year?\n...\nThat stall was not here last year.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, which one?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(3, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0403053_C01000", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Look, that one... Target practice.\nIt seems quite fun.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.\nWhy don't we go check it out,\n｛Hikami＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(3, 3, (#1));
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("B0403053_C01100", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "...\nNo, it seems like there is not much\ntime left until the fireworks start.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(3, 2, (#1));
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("B0403053_C01200", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Although I am reluctant, it is more\nimportant to get a good spot....\nLet us hurry.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(3, "M3_D?F", 0, 1, 1, 33);
        Character_ChFace(1, 0, 0);
        Background_Bg_GS2("BG_WF500_LI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Character_ChFace(1, 0, 10);
        Voice_PlayVoice("B0403053_C01300", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "It seems like we can see the\nfireworks well from here...\nIt is about to start.");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    System_Call_GS2("B90", "PL", 0);
    }
