section "b05_m1_002"{
    Background_Bg_GS2("BG_WF100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ack, I got lost while looking for a\ntoilet...\nWill ｛Saeki＊＊｝ be\nangry?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Umm～ ｛Saeki＊＊｝...\nis over there! Hm?)");
    Still_Event("EV_01_29", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_01_003_D02", 127, 40);
    Still_Approach(1, 3, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, he's fixing his hair!)");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ehh...\nHis hair is usually quite simple,\nbut he's quite fussy about it...)");
    Voice_PlayVoice("B0501002_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "!?");
    Character_Chara_GS2(1, "M1_??F", 0);
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Still_Event("");
    Voice_PlayVoice("B0501002_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "O-Oh! You took your time.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sorry to keep you waiting!\nYour hair is like that again today?");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(1, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("B0501002_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "... What are you saying?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, you're feigning ignorance.\nWeren't you just looking in the\nwindow and fixing your hair?\nMessing around with it.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("B0501002_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "... I wasn't.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Liar! I saw you!");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(1, 3, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("B0501002_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I said I wasn't, so I wasn't.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? The back is still sticking up.");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(1, 2, (#1));
    Character_BlinkStart(1, 0, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("B0501002_A00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Seriously? Where?");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, I was lying.");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("B0501002_A00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "H-Hey...\nYour eyes are kind of scary.");
    Voice_PlayVoice("B0501002_A00700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I'm going to mess your hair up so\nmuch that it won't be able to be\nfixed.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah! S-Sorry!");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(1, 61, 6);
    Parameter_AddCh1Param(1, 60, 3);
    Parameter_AddCh1Param(1, 62, #5);
    if (Parameter_GetCh1Param(1, 130) <= 3){
        }
    else {
        System_GlobalWork(5, 0, 1);
        }
    Date_DateEvent(1);
    }
