section "b05_m4_000"{
    Character_Chara_GS2(4, "M4_??F", 0);
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(4, 2, (#1));
    Background_Bg_GS2("BG_NE320_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("B0504000_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Ehh～...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("", 4, "B0504000_D00100");
    Message_Who(4);
    Message_MsgDisp("Hariya", "｛主人公｝, you've gotten\nmuch better.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Really?");
    Character_ChFace(0, 2, 1);
    Voice_PlayVoice("B0504000_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah.\nWell, you're still average, compared\nto me!");
    Character_ChFace(0, 2, 5);
    Voice_PlayVoice("B0504000_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "To improve, you need form. Watch me.");
    Character_Chara_GS2(4, "NON");
    Still_Event("EV_04_02", #1, 0, 60);
    System_Wait(10);
    SoundEffect_PlayStream(3, "SE_DARTS");
    System_Wait(50);
    Music_PlayBGM(0, "MN_C_04_003_D02", 127, 40);
    Voice_PlayVoice("B0504000_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "See? I got a bull's eye!\nI'm in perfect form!");
    Still_Approach(4, 91, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "Amazing!");
    Still_ApproachEnd();
    Background_Bg_GS2("BG_NE320_?_0", 1, #1, 0);
    Character_Chara_GS2(4, "M4_??F", 0);
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("主人公", "You really are good,\n｛Hariya＊＊｝.");
    Voice_PlayVoice("B0504000_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I often come here to play after\nlives.\nThis is nothing!");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see.\nI also want to be able to have the\ndart land where I'm aiming for.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("B0504000_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "You'll be able to do it if you\npractice.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Really?");
    Character_BlinkStart(4, 3, (#1));
    Voice_PlayVoice("B0504000_D00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah, really.");
    Character_BlinkStart(4, 0, (#1));
    Character_ChFace(0, 2, 5);
    Voice_PlayVoice("B0504000_D00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Until then, I'll be responsible for\nyou and teach you.");
    Character_ChFace(0, 2, 1);
    Voice_PlayVoice("B0504000_D00900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "My training is tough, you know?\nBe ready for it!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay!");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(4, 61, 6);
    Parameter_AddCh1Param(4, 60, 3);
    Parameter_AddCh1Param(4, 62, #5);
    System_GlobalWork(5, 0, 2);
    Date_DateEvent(1);
    }
