section "b05_m4_001"{
    Still_Event("EV_04_03", #1, 0, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_04_003_D00", 127, 40);
    Environment_PlayME(1, "SN_BGE_027_014", 127, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Which band is going out next?");
    Still_StillFace(0, 7, 1);
    Voice_PlayVoice("B0504001_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "......");
    Still_StillFace(0, 7, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝?");
    Voice_PlayVoice("B0504001_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nThis kind of live event is held\nevery summer.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("B0504001_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "There are events that are so awesome\nthat this one can't even compare.");
    Voice_PlayVoice("B0504001_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It has big home-grown artists and\nforeign artists, and there are tens\nof thousands of people in the\naudience...");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("B0504001_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "People are normally fired up, but\nthat event makes you feel even more\nfired up...\nIt feels really good.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("B0504001_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I'm a part of the audience right\nnow, but I want to stand on that\nstage one day...");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's not that you want to stand on\nstage.\nYou will stand on stage.\nRight, ｛Hariya＊＊｝?");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("B0504001_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Of course!");
    Voice_PlayVoice("B0504001_D00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I'll fire you up when I'm standing\nthere on stage....\nSo look forward to it!");
    Still_Approach(4, 92, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay!");
    Still_ApproachEnd();
    Message_CloseMsg();
    Environment_StopME(1, 40);
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Still_Event("");
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(4, 61, 6);
    Parameter_AddCh1Param(4, 60, 3);
    Parameter_AddCh1Param(4, 62, #5);
    Character_Chara_GS2(4, "M4_??F", 0, 1, 1, 5);
    Background_Bg_GS2("BG_WF400_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    System_GlobalWork(3, 0, 1);
    System_GlobalWork(5, 0, 1);
    Date_DateEvent(1);
    }
