section "b05_m7_002"{
    Background_Bg_GS2("待ち合わせ場所背景", #1, #1, 0, 0, Date_Date_Data(2));
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(I'm late!\n｛Wakaouji＊＊｝, did he\nwait...?\nOh, he's already here!)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝! Oh...");
    Voice_PlayVoice("B0507002_W00000", #1, "");
    Message_Who(7);
    Message_MsgDisp("？？？", "Dr. Wakaouji.");
    Still_Event("EV_07_03", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_07_001_D00", 127, 40);
    Voice_PlayVoice("B0507002_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "You...");
    Voice_PlayVoice("B0507002_W00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Men in Suits", "It's been a long time, Doctor.\nAt last, I've found you.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("B0507002_G00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Hello. It has been a long time.\nYour Japanese has gotten better.\nWhere did you learn it?");
    Voice_PlayVoice("B0507002_W00400", #1, "");
    Message_Who(0);
    Message_MsgDisp("Men in Suits", "When I came to Japan to look for\nyou.\nIt took three years.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Who is this? Is it a friend...?)");
    Voice_PlayVoice("B0507002_W00500", #1, "");
    Message_Who(0);
    Message_MsgDisp("Men in Suits", "You have no time for us to\nassociate.\nWill you return with me?");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("B0507002_G00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It is not association.\nI do not intend to return.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, ｛Wakaouji＊＊｝...");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("", 7, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝.");
    Voice_PlayVoice("B0507002_W00700", #1, "");
    Message_Who(0);
    Message_MsgDisp("Men in Suits", "This woman?");
    Still_StillFace(0, 0, 0);
    Still_Approach(7, 182, 0, 0, 1, 1);
    Voice_PlayVoice("B0507002_G00800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "She has nothing to do with this.\nShe is my student.\nI work as a high school teacher now.\nTherefore, I am not returning.");
    Still_ApproachEnd();
    Voice_PlayVoice("B0507002_W00900", #1, "");
    Message_Who(0);
    Message_MsgDisp("Men in Suits", "A high school teacher.\nWith your IQ of 200?\nThat's absurd and ridiculous...");
    Voice_PlayVoice("B0507002_W01000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Men in Suits", "Do you not think that it's a waste\nof talent?\nA doctor, with that great amount of\nintelligence...");
    Still_StillFace(0, 6, 2);
    Still_Approach(7, 182, 0, 0, 1, 5);
    Voice_PlayVoice("B0507002_G01100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "...\nStop the dull talk in front of a\nstudent.");
    Still_ApproachEnd();
    Still_Approach(7, 182, 0, 0, 1, 9);
    Voice_PlayVoice("B0507002_W01200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Men in Suits", "Okay, I understand.");
    Still_ApproachEnd();
    Voice_PlayVoice("B0507002_W01300", #1, "");
    Message_Who(0);
    Message_MsgDisp("Men in Suits", "I'll wait and see what happens.\nSo long, Doctor.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("B0507002_G01400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I said never. Forget me.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Character_Chara_GS2(7, "M7_06F", 0);
    Character_ChFace(0, 0, 10);
    Music_StopBGM(0, 40);
    Screen_WipeIn(2);
    Voice_PlayVoice("B0507002_G01500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Now, the bad fellow's disappeared.\nLet's go!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 61, 6);
    Parameter_AddCh1Param(7, 60, 3);
    System_GlobalWork(5, 0, 1);
    Date_DateEvent(1);
    }
