section "b05_m5_003"{
    Character_Chara_GS2(5, "M5_??F", 0);
    Background_Bg_GS2("BG_TR300_WI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("B0505003_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Hey. Can I make a request today?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sure. What should we go and see?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0505003_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I want to ride the horses.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Can you ride a horse,\n｛Chris＊＊｝?");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(5, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0505003_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It's fun watching. Let's go.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(5, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    if (Parameter_GetCh1Param(5, 571) == 7){
        Still_Event("EV_05_05", #1, 0, 60);
        }
    else if (Parameter_GetCh1Param(5, 571) == 5){
        Still_Event("EV_05_21", #1, 0, 60);
        }
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_05_003_D00", 127, 40);
    Voice_PlayVoice("B0505003_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "That was fun～.\nAs expected, horseback riding feels\ngood.");
    Message_Who(0);
    Message_MsgDisp("主人公", "The horse you rode was neighing a\nlot, ｛Chris＊＊｝.");
    Voice_PlayVoice("B0505003_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah, it was a smart one.\nI think it's also because I'm used\nto riding horses.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so?");
    Still_Approach(5, 124, 0, 0, 1, 1);
    Voice_PlayVoice("B0505003_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah.");
    Still_ApproachEnd();
    Voice_PlayVoice("B0505003_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I also joined a horse riding club,\nand during classes we would be\nplaying polo and stuff.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh～.");
    Voice_PlayVoice("B0505003_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "The funnest thing is riding long\ndistances.");
    Voice_PlayVoice("B0505003_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "When I was in England, I would often\nwake up early and go riding with my\ndad.");
    Voice_PlayVoice("B0505003_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It was really good.\nI also wanna show you, the place\nwhere the town gets dyed by the\nmorning glow...");
    Message_Who(0);
    Message_MsgDisp("主人公", "It would surely be pretty.");
    Voice_PlayVoice("B0505003_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It's extremely pretty, and fun, you\nknow?\nAh, right.");
    Voice_PlayVoice("B0505003_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "When we go to England one day, let's\ngo on a long ride.\nI'll introduce you to my Kapporegou.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... \"Kapporegou\"?");
    Voice_PlayVoice("B0505003_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "That's my horse's name.\nIsn't it a cute name?\nNot just the name, my horse is cute,\ntoo.");
    Voice_PlayVoice("B0505003_E01300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I made it like my dad's horse's\nname, \"Awaodorigou\".");
    Message_Who(0);
    Message_MsgDisp("主人公", "\"Awaodori\"...");
    Voice_PlayVoice("B0505003_E01400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah, it's gotten a little colder.\nLet's go somewhere and get something\nwarm to drink.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(\"Kappore\" and \"Awaodori\"...\nI wonder who gave them those\nnames...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Music_StopBGM(0, 40);
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(5, 61, 6);
    Parameter_AddCh1Param(5, 60, 3);
    Parameter_AddCh1Param(5, 62, #5);
    System_GlobalWork(5, 0, 1);
    Date_DateEvent(1);
    }
