section "b05_m4_002"{
    Character_Chara_GS2(4, "M4_04F", 0);
    Background_Bg_GS2("BG_NE210_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "How was the live today,\n｛Hariya＊＊｝?");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(4, 3, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("B0504002_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Actually, there was nothing that\nI'll remember for long.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see...\nI liked the second song, the one\nwith a cheerful feeling.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("B0504002_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "The second song? Ah, that.");
    Character_BlinkStart(4, 2, (#1));
    Voice_PlayVoice("B0504002_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "That song...\nI got a feeling that it'll be a\npopular song if I changed the chords\na little bit.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Chords?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0504002_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I guess it can't be helped, you\nwouldn't understand even if I told\nyou.\nI'll show you.");
    Voice_PlayVoice("B0504002_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Wait a sec.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Character_Chara_GS2(4, "NON");
    Voice_PlayVoice("B0504002_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Sorry.\nCan I borrow a guitar for a bit?");
    Voice_PlayVoice("B0504002_W00600", #1, "");
    Message_Who(0);
    Message_MsgDisp("Clerk", "You can use the one over there.");
    Voice_PlayVoice("B0504002_D00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Thanks.");
    Still_Event("EV_04_04", #1, 0, 60);
    Voice_PlayVoice("B0504002_D00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Alright.\nThis is the main chord we use for\nthat song.");
    SoundEffect_PlayStream(3, "SS_T_00_236_M00");
    System_Wait(#60);
    Still_Approach(4, 93, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Still_ApproachEnd();
    Voice_PlayVoice("B0504002_D00900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "This is the 7th chord.");
    SoundEffect_PlayStream(3, "SS_T_00_237_M00");
    System_Wait(#60);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, it's completely different...");
    Still_Approach(4, 93, 0, 0, 1, 5);
    Voice_PlayVoice("B0504002_D01000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Isn't it?");
    Background_Bg_GS2("BG_NE210_?_0", 1, #1, 0);
    Still_Event("");
    Voice_PlayVoice("B0504002_D01100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Thanks!");
    Voice_PlayVoice("B0504002_W01200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Clerk", "You're welcome.");
    Character_Chara_GS2(4, "M4_??F", 0);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("B0504002_D01300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Well, this is how the entire song\ncan change.\nYou got it?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, thanks.\nDo you do such things with the songs\nyou write, ｛Hariya＊＊｝?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("B0504002_D01400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Huh? Why you asking?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Like change the chords and stuff...");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(4, 2, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("B0504002_D01500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "... ｛Hariya＊＊｝?\nWhat's wrong?");
    Character_ChFace(0, 4, 1);
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("B0504002_D01600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Oi, let's go!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh?");
    Character_ChFace(0, 4, 0);
    Character_BlinkStart(4, 0, (#1));
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("B0504002_D01700", 4, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I got an idea...!\nThanks, ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehhh? What is it?");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(4, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0504002_D01800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I think it's gonna be a famous\nsong...!");
    Character_Chara_GS2(4, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(You're too impulsive,\n｛Hariya＊＊｝～!)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(4, 61, 6);
    Parameter_AddCh1Param(4, 60, 3);
    Parameter_AddCh1Param(4, 62, #5);
    System_GlobalWork(5, 0, 1);
    Date_DateEvent(1);
    }
