section "b05_m3_000"{
    Character_Chara_GS2(3, "M3_??F", 0);
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Background_Bg_GS2("BG_TR550_?_0", 1, #1, 0);
    Music_PlayBGM(0, "MN_BGC_024_000", 127, 40);
    Screen_WipeIn(2);
    Voice_PlayVoice("", 3, "B0503000_C00000");
    Message_Who(3);
    Message_MsgDisp("Hikami", "｛主人公｝.\nI have a cousin who is much older\nthan me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Pardon?");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(3, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0503000_C00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "He's smart, and the way he moves is\nrefined.\nI aspire to be like him....\nHe is good at driving.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay...");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(3, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0503000_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "In Spring of my 2nd year in middle\nschool, he let me sit in the\npassenger seat.\nIt was so cool.\nIt was like my body was numb.");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0503000_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "...\nThat's why I am thinking about\nimitating the way he drives.");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(3, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0503000_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "You are like the me of that time.\nPlease ride in the passenger seat!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, okay.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(3, "NON");
    Environment_PlayME(1, "SN_P_00_017_000", 127, 0);
    Still_Event("EV_03_01", #1, 0, 60);
    Screen_WipeIn(2);
    Still_Approach(3, 60, 0, 0, 1, 1);
    Voice_PlayVoice("B0503000_C00500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Right, that's how it felt that time!\n...\nSmooth cornering and steady\ndriving!!");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "Were you able to imitate it,\n｛Hikami＊＊｝?");
    Voice_PlayVoice("B0503000_C00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Yes, it was generally the same!");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Was the speed also the same?");
    SoundEffect_PlayStream(3, "SS_T_00_198_M00");
    Voice_PlayVoice("B0503000_C00700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... Eh?");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("B0503000_C00800", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Ugh, I was beaten by an elementary\nschool kid...!?\n...\nDamn, the \"safety first\" rule\nbackfired on me!");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yeah, I thought that was it...");
    Voice_PlayVoice("B0503000_C00900", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Right, what I couldn't imitate was\nthe \"speed\" I need to achieve in\norder for no one to overtake me...");
    Message_Who(0);
    Message_MsgDisp("主人公", "As I thought...");
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("B0503000_C01000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Now I feel extremely mortified.\nWhile we were still driving, all I\ndid was talk about such things...");
    Voice_PlayVoice("B0503000_C01100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Next time, I will be aware of the\nspeed!\nRather, I will not let anyone\novertake me!");
    Voice_PlayVoice("B0503000_C01200", 3, "B0503000_C01201");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... ｛主人公｝.\nPlease ride with me again!!");
    Environment_StopME(1, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(3, 61, 6);
    Parameter_AddCh1Param(3, 60, 3);
    Parameter_AddCh1Param(3, 62, #5);
    System_GlobalWork(5, 0, 1);
    Date_DateEvent(1);
    }
