section "b05_m5_000"{
    Character_Chara_GS2(5, "M5_??F", 0);
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Background_Bg_GS2("BG_TR400_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("B0505000_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Hey. What kind of store is this?");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's a costume lending store.\nIt seems like they lend you clothes,\nand also photograph you.");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(5, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0505000_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Wah, I want to try it!\nSince we're here, do you wanna give\nit a go?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, okay.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0505000_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yay.\nA military commander from the\nSengoku Period, a playboy, a ninja!\nWah, I don't know which one to\nchoose～");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0505000_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Hmm, I've decided!\nI'm going to get changed～.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Character_Chara_GS2(5, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I wonder which one\n｛Chris＊＊｝ chose...)");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Voice_PlayVoice("B0505000_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Sorry to keep you waiting▼");
    Message_Who(0);
    Message_MsgDisp("主人公", "Welcome back,\n｛Chris＊＊｝...\nAh!");
    Environment_StopME(0, 40);
    Still_Event("EV_05_02", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_05_002_D01", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah!\nIt suits you, ｛Chris＊＊｝!\nBut why a court dancer...?");
    Voice_PlayVoice("B0505000_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Shizuka-chan.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Shizuka-chan?");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("B0505000_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah.\nThey're a really wholehearted\nperson.");
    Still_Approach(5, 121, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "Shizuka-chan...\nis a wholehearted person?");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("B0505000_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I also had them prepare a\nYoshitsune-kun costume for you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah! Lady Shizuka! ... Eh?\nA Yoshitsune costume?");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("B0505000_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Because it's lonely if I'm dressed\nup by myself, right?\nHurry up and change so we can take a\nphoto.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh～!");
    Voice_PlayVoice("B0505000_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Come on, come on, hurry!\nI'm reaaaally looking forward to it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay. I'll go get changed, then.");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("B0505000_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nIt was a sad love story between the\ntwo actual people, but let's take a\nhappy photo, okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Still_StillFace(0, 0, 0);
    Still_Approach(5, 121, 0, 0, 1, 5);
    Voice_PlayVoice("B0505000_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Hurry up and change.\nYour rendition of Yoshitsune-kun.");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Chris＊＊｝ looked sad\nfor a moment, but perhaps it was my\nimagination...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Music_StopBGM(0, 40);
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(5, 61, 6);
    Parameter_AddCh1Param(5, 60, 3);
    Parameter_AddCh1Param(5, 62, #5);
    System_GlobalWork(5, 0, 1);
    Date_DateEvent(1);
    }
