section "b05_m6_001"{
    Character_Chara_GS2(6, "M6_09F", 0);
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Background_Bg_GS2("BG_WF530_SU_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_B_WF_530_000", 127, 40);
    Voice_PlayVoice("B0506001_F00000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Senpai!\nI will buy some baked corn and\nshaved ice!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay, take care.");
    Character_Chara_GS2(6, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I wonder if ｛Amachi＊＊｝\nwill be okay if he keeps eating at\nthis rate...)");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_Chara_GS2(6, "M6_09F", 0);
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(6, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0506001_F00100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Hah, I'm full!\nThanks for the food.");
    Message_Who(0);
    Message_MsgDisp("主人公", "You ate quite a lot.");
    Character_ChFace(0, 0, 3);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("B0506001_F00200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Sorry, I usually eat by myself.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("B0506001_F00300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "It's so tasty that I can't stop.\nIt's really difficult...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Well, it definitely would be\ndifficult if you eat three bowls of\nshaved ice...)");
    Character_Chara_GS2(6, "NON");
    SoundEffect_PlayStream(3, "SS_T_00_224_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Amachi＊＊｝!?\nAre you o-okay!?");
    Voice_PlayVoice("B0506001_F00400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Sorry, Senpai...\nPlease let me rest a little.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Music_StopBGM(0, 40);
    Still_Event("EV_06_03", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_06_004_D01", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Amachi＊＊｝?");
    Voice_PlayVoice("B0506001_F00500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He fell asleep...\nHe falls asleep fast.)");
    Voice_PlayVoice("B0506001_F00600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Mmm...... Senpai......");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Voice_PlayVoice("B0506001_F00700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "(... Is he sleep talking?)");
    Voice_PlayVoice("B0506001_F00800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Senpai is...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(... I am?)");
    Voice_PlayVoice("B0506001_F00900", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Senpai is an idiot....\nOr an ignorant person?");
    Message_Who(0);
    Message_MsgDisp("主人公", "What!?");
    Still_StillFace(0, 3, 1);
    Voice_PlayVoice("B0506001_F01000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Both are... Hahaha.");
    Still_Approach(6, 152, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(.........\nWhat exactly was that about...)");
    Still_ApproachEnd();
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_Chara_GS2(6, "M6_09F", 0);
    Background_Bg_GS2("BG_WF530_SU_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_B_WF_530_000", 127, 40);
    Voice_PlayVoice("B0506001_F01100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Ah, I feel refreshed...\nSorry, I went to sleep.");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's fine.\nDo you always suddenly fall asleep\nlike that?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0506001_F01200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "No, that's not it.\nI usually just lie down.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0506001_F01300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "But because I was with you Senpai, I\njust felt at ease...");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 2);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("B0506001_F01400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "This is bad... It's so embarrassing!");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("B0506001_F01500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "We still have time, should we go for\na swim?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, let's do that.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(6, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0506001_F01600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Okay.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(...\nIf we do, I'll stop thinking about\nwhat he said.)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(6, 61, 6);
    Parameter_AddCh1Param(6, 60, 3);
    Parameter_AddCh1Param(6, 62, #5);
    System_GlobalWork(5, 0, 2);
    Date_DateEvent(1);
    }
