section "b05_m5_001"{
    Character_Chara_GS2(5, "M5_??F", 0);
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(5, 2, (#1));
    Character_ChFace(0, 3, 4);
    Background_Bg_GS2("BG_FP220_SU_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("B0505001_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "............");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝, are you okay?\nYou don't look so good.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(5, 3, (#1));
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("B0505001_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Hmm～...");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(5, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("", 5, "B0505001_E00200");
    Message_Who(5);
    Message_MsgDisp("Chris", "｛主人公｝.\nCan I be a bit selfish?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(5, 3, (#1));
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("B0505001_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I actually can't handle it\nanymore...\nPlease let me...\nrest at the bench in the shade over\nthere～.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-oh no!\nI will buy some water for you!");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(5, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sorry to keep you waiting!\nHere's some water!");
    Still_Event("EV_05_03", #1, 0, 60);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_05_002_D01", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Are you okay?");
    Still_Approach(5, 122, 0, 0, 1, 1);
    Voice_PlayVoice("B0505001_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah. Thanks.");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "Were you perhaps already not feeling\nwell before you came?");
    Voice_PlayVoice("B0505001_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nI couldn't shake the feeling no\nmatter what...\nI stayed up all night.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so.\nI forced you out with me...");
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("B0505001_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah～ Don't sound so sad!");
    Voice_PlayVoice("B0505001_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Staying up late is nothing to me!\nIt's this sunlight that's bad!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Geez, ｛Chris＊＊｝.\nYou really don't have to force\nyourself, okay?");
    Voice_PlayVoice("B0505001_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Haha, you saw through it, huh.\nI'm kinda... defeated now.\nYou look like you're going to cry.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝...");
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("B0505001_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Is it okay if I rest here a little\nlonger?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, sure.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("B0505001_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Thanks.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Music_StopBGM(0, 40);
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(5, 61, 6);
    Parameter_AddCh1Param(5, 60, 3);
    Parameter_AddCh1Param(5, 62, #5);
    System_GlobalWork(5, 0, 1);
    Date_DateEvent(1);
    }
