section "b05_m1_001"{
    Character_Chara_GS2(1, "M1_09F", 0);
    Character_ChFace(0, 0, 10);
    Background_Bg_GS2("BG_WF530_SU_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_B_WF_530_000", 127, 40);
    Voice_PlayVoice("B0501001_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Hey, we've walked all the way here,\nbut do you want to go to the cove's\nrocky area?\nIt's underwater, but there's a good\nspot.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay! Let's go!");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(1, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Music_StopBGM(0, 40);
    Still_Event("EV_01_25", #1, 0, 60);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_01_003_D02", 127, 40);
    Environment_PlayME(1, "SN_B_EX_110_480", 127, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝!");
    SoundEffect_PlayStream(3, "SS_DSE_157_000");
    Still_Event("EV_01_03", #1, 1, 90);
    System_Wait(60);
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("B0501001_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "*pant* *pant* What is it?\nAren't you swimming anymore?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, the water has gotten a little\ncold.\nWhy don't you get out as well,\n｛Saeki＊＊｝?");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("B0501001_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Just a little while longer, okay?\nIt's been a while since I've been\nhere.");
    Voice_PlayVoice("B0501001_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I used to dive here with my grandpa\nwhen I was in elementary school!\nYou can catch turban shells and ear\nshells!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh... Ah!\nBut you can't just take the ocean's\nthings as you please, right?");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("B0501001_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Right!\nThe people of the association caught\nus and were very angry at the both\nof us!\nAhaha!");
    Message_Who(0);
    Message_MsgDisp("主人公", "You're laughing about it?\nThe both of you were wrong!");
    Still_StillFace(0, 6, 3);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("B0501001_A00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Even though my grandpa looks like\nthat, he used to be quite wild, you\nknow?\nYou didn't know that at all...");
    Message_Who(0);
    Message_MsgDisp("主人公", "But the sun is setting.\nIf you don't get out now, you'll\ncatch a cold.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("B0501001_A00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Please! Just one more dive! Okay?\n... Okay!?");
    Still_Event("EV_01_25", #1, 0, 60);
    SoundEffect_PlayStream(3, "SS_DSE_157_000");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝!?\nHe dove in again...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(*sigh*...\nWhen ｛Saeki＊＊｝ is in the\nocean, he's like a child.)");
    Still_Approach(1, 2, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    System_Wait(5);
    if (System_GlobalWork(10, 1) == 0){
        Still_ApproachEnd();
        Message_Who(0);
        Message_MsgDisp("主人公", "(It's been quite long...)");
        }
    Still_Approach(1, 2, 0, 0, 1, 5);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    System_Wait(5);
    if (System_GlobalWork(10, 1) == 0){
        Still_ApproachEnd();
        Message_Who(0);
        Message_MsgDisp("主人公", "(Maybe even too long... Ah!\nDid he perhaps..!?\nWhat should I do...)");
        }
    SoundEffect_PlayStream(3, "SS_DSE_157_000");
    Voice_PlayVoice("B0501001_A00700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ahh!!");
    Still_Event("EV_01_03", #1, 1, 60);
    Still_StillFace(0, 6, 1);
    Still_Approach(1, 2, 0, 0, 1, 9);
    Voice_PlayVoice("B0501001_A00800", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "*pant* *pant* ...");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝!! Geez!\nI thought you drowned!");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("B0501001_A00900", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "*pant* *pant* Sorry!\nI brought you a present! Here!");
    SoundEffect_PlayStream(3, "SS_DSE_157_000");
    Message_CloseMsg();
    Screen_WipeOut(8);
    Screen_WipeIn(2);
    SoundEffect_PlayStream(2, "SS_DSE_169_000");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah! ... W-What is it?");
    Still_StillFace(0, 6, 3);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("B0501001_A01000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "An octopus!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Kyaa!!");
    Voice_PlayVoice("B0501001_A01100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ahaha!!");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Environment_StopME(1, 40);
    Screen_WipeOut(2);
    Still_Event("");
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(1, 61, 6);
    Parameter_AddCh1Param(1, 60, 3);
    Parameter_AddCh1Param(1, 62, #5);
    System_GlobalWork(5, 0, 1);
    Date_DateEvent(1);
    }
