section "b05_m7_001"{
    Background_Bg_GS2("BG_WF000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝...\nOh, he's here already!)");
    Character_Chara_GS2(7, "M7_06F", 0);
    Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, it's hot!");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0507001_G00000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It is hot.\nSuch a day like this should be at a\nbeach.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.\nIt was slightly unexpected of you to\ninvite me to come swimming.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(7, 2, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("B0507001_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I can't go swimming.\nSensei doesn't know how to swim.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Then where?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0507001_G00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It's a cruiser.");
    Message_Who(0);
    Message_MsgDisp("主人公", "A cruiser...!?");
    Environment_StopME(0, 40);
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_EX180_SU_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ooh, it really is a cruiser...\nIs it Sensei's?");
    Voice_PlayVoice("B0507001_G00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Of course not.\nIt's the ship of a person who Sensei\nis indebted to in various ways.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see...\nBut don't you need a driver's\nlicense or something for this...?");
    Voice_PlayVoice("B0507001_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I think so.");
    Message_Who(0);
    Message_MsgDisp("主人公", "...?");
    Music_PlayBGM(0, "MN_C_07_003_D00", 127, 40);
    Environment_PlayME(1, "SN_BGF_036_000", 85, 40);
    Character_Chara_GS2(7, "NON");
    SoundEffect_PlayStream(2, "SE_HOSE");
    Still_Event("EV_07_02", #1, 0, 60);
    Message_Who(0);
    Message_MsgDisp("主人公", "So we were just going to clean the\ncruiser's deck...\n｛Wakaouji＊＊｝, you liar!");
    Still_Approach(7, 181, 0, 0, 1, 1);
    Voice_PlayVoice("B0507001_G00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Hahaha! It's not a lie.\nHey, you can board the cruiser\nperfectly fine!");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", ".........");
    Voice_PlayVoice("B0507001_G00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Well, because this gorgeous ship was\ntaken care of with great effort,\nlet's enjoy it!");
    Still_Event("EV_07_18", #1, 1, 60);
    Environment_FadeME(1, 127, 30);
    SoundEffect_PlaySE(2254, 127);
    Voice_PlayVoice("B0507001_G00700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Take this!!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah!!");
    Still_Approach(7, 181, 0, 0, 1, 5);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Well...\nWhen it comes to something like\nthis, enjoy it!)");
    Still_ApproachEnd();
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Music_StopBGM(0, 40);
    SoundEffect_StopStream(2, 20);
    Environment_StopME(1, 40);
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(7, 61, 6);
    Parameter_AddCh1Param(7, 60, 3);
    System_GlobalWork(5, 0, 1);
    Date_DateEvent(1);
    }
