section "b05_m2_001"{
    Background_Bg_GS2("BG_WF530_SU_0", #1, #1, 0);
    Music_PlayBGM(0, "MN_B_WF_530_000", 127, 40);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? Wasn't it around this area...\nOr was it over there?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_WF530_SU_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Seems like it's a different\nspot......\nAm I perhaps lost?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Shiba＊＊｝ might be\nworried...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ahh, what should I do!)");
    Voice_PlayVoice("", 2, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "｛主人公｝!");
    Message_Who(0);
    Message_MsgDisp("主人公", "!!!");
    Still_Event("EV_02_02", #1, 0, 60);
    Voice_PlayVoice("B0502001_B00000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "*Pant* *Pant*");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝...\nYou came running?");
    Still_Approach(2, 31, 0, 0, 1, 1);
    Voice_PlayVoice("B0502001_B00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Kinda...\nYou didn't come back, so I thought\nsomething happened...!");
    Still_ApproachEnd();
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("B0502001_B00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Don't go making me worry.");
    Message_Who(0);
    Message_MsgDisp("主人公", "S-Sorry... I got lost...");
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("B0502001_B00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nOur spot was right in front of the\nshops, so how the hell did you get\nlost?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uh...");
    Background_Bg_GS2("BG_WF530_SU_0", #1, #1, 0);
    Character_Chara_GS2(2, "M2_09F", 0);
    Still_Event("");
    Voice_PlayVoice("B0502001_B00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Anyway, it's a relief you're...");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0502001_B00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "............ Haha.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝?");
    Character_ChFace(0, 2, 3);
    Voice_PlayVoice("B0502001_B00600", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Seriously, what's with your sense of\ndirection...");
    Message_Who(0);
    Message_MsgDisp("主人公", "You don't have to laugh...");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(2, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0502001_B00700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Haha... Sorry...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Geez...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(But seeing ｛Shiba＊＊｝\nlaugh like this might be a rare\nthing...?)");
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 61, 6);
    Parameter_AddCh1Param(2, 60, 3);
    Parameter_AddCh1Param(2, 62, #5);
    System_GlobalWork(5, 0, 1);
    Date_DateEvent(1);
    }
