section "b05_m7_003"{
    Character_Chara_GS2(7, "M7_06F", 0);
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(7, 2, (#1));
    Background_Bg_GS2("BG_WF540_WI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("B0507003_G00000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Sigh～～! It's pleasant....\nAre you cold?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm all right.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("B0507003_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "The sea is very calm today...\nLet's go down to the beach.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah.");
    Music_PlayBGM(0, "MN_C_07_002_D00", 127, 40);
    Character_Chara_GS2(7, "NON");
    Still_Event("EV_07_04", #1, 0, 60);
    Still_Approach(7, 183, 0, 0, 1, 1);
    Voice_PlayVoice("B0507003_G00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "The beach in Winter is good.\nIt's wide and refreshing.");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes, it is refreshing.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("B0507003_G00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Can you believe it?\nWhen you go straight ahead through\nthis sea, you'll be in the United\nStates.");
    Message_Who(0);
    Message_MsgDisp("主人公", "The United States...?");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("B0507003_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It's the country where Sensei spent\nhis youth.\nHowever, he left it a long time ago\nfor research facilities.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Why is that...?");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("B0507003_G00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "There, people devote their time with\npatent competitions and money-making\nfrom morning to night...");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("B0507003_G00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Research should be able to make many\npeople happy, but it's monopolized\nfor worthless honor and money.");
    Voice_PlayVoice("B0507003_G00700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "That was just a few years ago.\nThose affairs are on the other side\nof this sea.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is it like that...?");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("B0507003_G00800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "However, this conversation may seem\nstrange to you, like a story from\nanother world.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("B0507003_G00900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "You tie me to this world.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("B0507003_G01000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "The wind has appeared...");
    Still_StillFace(0, 0, 1);
    Still_Approach(7, 183, 0, 0, 1, 5);
    Voice_PlayVoice("B0507003_G01100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Now, let's go to drink some hot\ncoffee.");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Music_StopBGM(0, 40);
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(7, 61, 6);
    Parameter_AddCh1Param(7, 60, 3);
    System_GlobalWork(5, 0, 1);
    Date_DateEvent(1);
    }
