section "b07_m4_000"{
    int var0;
    Character_Chara_GS2(4, "M4_??F", 0);
    Background_Bg_GS2("BG_EX150_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    if ((Parameter_GetCh1Param(4, 536) == 1) && (Parameter_GetCh1Param(4, 538) == 0)){
        var0 = 1;
        }
    if (4 == System_GlobalWork(23, 1)){
        var0 = 0;
        }
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    if (var0 == 0){
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nBy the way, ｛Hariya＊＊｝.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("B0704000_D00000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Huh?");
        Message_Sele_Kitaku_Kaiwa();
        int var1 = Parameter_Kitaku_Kaiwa(0);
        switch (var1){
            case 0:
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of TV shows do you\nnormally watch,\n｛Hariya＊＊｝?");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("B0704000_D00100", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "TV? I often watch music shows.");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("B0704000_D00200", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Also, I quite like checking fashion.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... \"Ofumi's Fashion Check\"?");
            Character_ChFace(0, 0, 8);
            Voice_PlayVoice("B0704000_D00300", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "No! Why would I watch that?\nI watch the one that's for showbiz.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Like do you check to see if there\nare things that you can wear at live\nshows?");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D00400", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Oh, sharp! How rare.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D00500", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "In order to become a great musician,\nyou need to be steady and to put in\nthe effort.");
            Character_BlinkStart(4, 0, (#1));
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D00600", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Ah, I'm a diligent person!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad.)");
            Parameter_InCh1Param(4, 530, 35);
            break ;
            case 1:
            Message_Who(0);
            Message_MsgDisp("主人公", "What are foods that you like,\n｛Hariya＊＊｝?");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D00700", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Hamburg Steak!\nThere has to be a sunny-side fried\negg on top.");
            Message_Who(0);
            Message_MsgDisp("主人公", "There has to be?");
            Character_ChFace(0, 2, 1);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("B0704000_D00800", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "There definitely has to be.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Why?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("B0704000_D00900", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "If it doesn't have a sunny-side\nfried egg on top, then a Hamburg\nSteak isn't a Hamburg Steak!");
            Message_Who(0);
            Message_MsgDisp("主人公", "I-Is that so... Anything else?");
            Character_BlinkStart(4, 0, (#1));
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D01000", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Curry rice. Ramen.\nSushi without wasabi!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I see...)");
            Parameter_InCh1Param(4, 531, 36);
            break ;
            case 2:
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you have any favorite sports,\n｛Hariya＊＊｝?");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("B0704000_D01100", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Hmm... I have sports that I hate...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh, what?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("B0704000_D01200", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "... I won't tell you.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Then, give me a hint!");
            Voice_PlayVoice("B0704000_D01300", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", ".........");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("B0704000_D01400", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", ".........\nI nearly drowned in the ocean\nbefore, ages ago.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Swimming!)");
            Parameter_InCh1Param(4, 532, 37);
            break ;
            case 3:
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of music do you like,\n｛Hariya＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("B0704000_D01500", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Generally, I listen to things from\nJ-Pop to classical music.");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D01600", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "But I listen to rock music the most.\nI like rock music!");
            Message_Who(0);
            Message_MsgDisp("主人公", "I thought so.");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("B0704000_D01700", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Yeah!\nI generally listen to bands that\nhave gone major.");
            Voice_PlayVoice("B0704000_D01800", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "I also listen to Western bands from\nthe 80s like John Bobby, W2, and Mr.\nPick.");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D01900", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "For the 90s, you can't leave out the\nJ-Rock band ZEX.\nThey're still mind- blowing!");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D02000", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "So to return to your original\nquestion, I listen to rock music and\nmany other genres.");
            Voice_PlayVoice("B0704000_D02100", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Mellowcore, alternative, grunge...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(... He was fired up...)");
            Parameter_InCh1Param(4, 533, 38);
            break ;
            case 4:
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you have any hobbies,\n｛Hariya＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("B0704000_D02200", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Right now it's song composition.\nI mess around with the guitar when I\nhave time.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Can you finish the songs right away?");
            Voice_PlayVoice("B0704000_D02300", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "There are times when I can, and\ntimes when I can't.");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D02400", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Sometimes, no matter where I am, a\ngood phrase just comes to me.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh...\nIt seems tough if it were to come to\nyou while you were out.");
            Character_ChFace(0, 2, 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D02500", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Indeed.\nIt's fine with lyrics, but it's a\ncontest the moment you think of a\nmelody!");
            Message_Who(0);
            Message_MsgDisp("主人公", "Contest?");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D02600", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Yeah.\nI keep repeating it over and over in\nmy head so I don't forget it.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D02700", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "So I quickly go home and play it on\nthe guitar!\nIt's a contest with yourself.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I feel like it would be better if\nhe could write a memo about it...)");
            Parameter_InCh1Param(4, 529, 34);
            break ;
            case 5:
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of kid were you in middle\nschool, ｛Hariya＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("B0704000_D02800", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "I wasn't that different than how I\nam now.\nBut I was a bit naughty back then.");
            Message_Who(0);
            Message_MsgDisp("主人公", "How much is a bit?");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("B0704000_D02900", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "I was made to stand out in the\nhallway a number of times.\nI've also had many things\nconfiscated.");
            Message_Who(0);
            Message_MsgDisp("主人公", "......");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D03000", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Well, it's not something for you to\nworry about.\nDon't mind, don't mind.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I feel like he wasn't just \"a bit\"\nnaughty...)");
            Parameter_InCh1Param(4, 534, 39);
            break ;
            case 6:
            Message_Who(0);
            Message_MsgDisp("主人公", "What is your future dream,\n｛Hariya＊＊｝?");
            Character_ChFace(0, 2, 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D03100", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "To become a musician recognized\nthroughout the world!");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0704000_D03200", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "And another thing!\nIt's not a dream, it's a target.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I see.");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("B0704000_D03300", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "...\nWell, before that, there are things\nthat I have to overcome.");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("B0704000_D03400", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "*Sigh*...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I wonder what he has to\novercome...)");
            Parameter_InCh1Param(4, 528, 33);
            break ;
            case 7:
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of girl do you like,\n｛Hariya＊＊｝?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("B0704000_D03500", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "... Why are you asking me that!?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Should I not have asked?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("B0704000_D03600", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "That's... not it, but...");
            Message_Who(0);
            Message_MsgDisp("主人公", "So then what type?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("B0704000_D03700", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Uh............\nSomeone that can't help being thick-\nheaded and idiotic.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("B0704000_D03800", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Someone who will seriously listen to\nwhat I say without making fun.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("B0704000_D03900", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Also, a kind of eccentric person who\nwill use any excuse to meddle with\nme.");
            Message_Who(0);
            Message_MsgDisp("主人公", "You're not an eccentric person,\n｛Hariya＊＊｝.");
            Character_ChFace(0, 2, 1);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("B0704000_D04000", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "I wasn't talking about myself just\nnow!");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("B0704000_D04100", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "... I guess that's how you are.\nYour senses are bad...");
            Parameter_InCh1Param(4, 535, 40);
            break ;
            case 8:
            Message_Who(0);
            Message_MsgDisp("主人公", "What is love to you,\n｛Hariya＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("B0704000_D04200", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "...\nAn emotion that I don't know much\nabout.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("B0704000_D04300", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Maybe it's different from not\nknowing...\nHow would you say it?\nI can't keep up with these\nemotions...");
            Voice_PlayVoice("B0704000_D04400", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "...\nEven at times when I'm extremely\ninterested in someone, and I can't\nkeep my eyes off them.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("B0704000_D04500", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "There are also times when I think,\n\"What's with this person?\", and want\nto chase after them...\nI've been soppy lately.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Lately?");
            Character_ChFace(0, 0, 11);
            Character_BlinkStart(4, 2, (#1));
            Voice_PlayVoice("B0704000_D04600", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "... Huh?");
            Message_Who(0);
            Message_MsgDisp("主人公", "So you've been feeling that way\nlately?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("B0704000_D04700", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "W-What are you talking about!?\nYou're wrong.\nI was just talking about what people\nfeel in general!");
            Message_Who(0);
            Message_MsgDisp("主人公", "I-I see.");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("B0704000_D04800", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "... This. *Sigh*...\nIt's really tiring...");
            Parameter_InCh1Param(4, 536, 41);
            break ;
            case 9:
            if (Parameter_GetPl1Param(312) != 4){
                Message_Who(0);
                Message_MsgDisp("主人公", "What kind of kiss is your ideal\nkiss, ｛Hariya＊＊｝?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 2, (#1));
                Character_ChFace(0, 3, 4);
                Voice_PlayVoice("B0704000_D04900", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "............ Huh?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Uh... I'll change the question then.\nWhat comes to mind when you hear the\nword \"kiss\"?");
                Character_BlinkStart(4, 3, (#1));
                Character_ChFace(0, 3, 2);
                Voice_PlayVoice("B0704000_D05000", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "......... Nothing comes to mind.");
                Message_Who(0);
                Message_MsgDisp("主人公", ".........");
                Character_BlinkStart(4, 0, (#1));
                Character_ChFace(0, 2, 1);
                Voice_PlayVoice("B0704000_D05100", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... It can't be helped, right?\nI haven't even thought about such\nthings.\nGenerally...");
                Character_ChFace(0, 0, 11);
                Voice_PlayVoice("B0704000_D05200", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Wah!");
                Message_Who(0);
                Message_MsgDisp("主人公", "Huh!? W-What?");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(4, 2, (#1));
                Character_ChFace(0, 3, 1);
                Voice_PlayVoice("B0704000_D05300", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "I just narrowly avoided falling into\na trap...!");
                Message_Who(0);
                Message_MsgDisp("主人公", "A trap?");
                Character_ChFace(0, 2, 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("B0704000_D05400", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "It's nothing!\nThis conversation is over!");
                Message_Who(0);
                Message_MsgDisp("主人公", "(Hmm...\nWhat was he about to say...?)");
                Parameter_InCh1Param(4, 537, 42);
                }
            else {
                Message_Who(0);
                Message_MsgDisp("主人公", "What do you think about kisses,\n｛Hariya＊＊｝?");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(4, 2, (#1));
                Character_ChFace(0, 3, 2);
                Voice_PlayVoice("B0704000_D05500", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nI was just kind of joking at that\ntime, when I said that you could\nbrag about it in the future,\nthough...");
                Character_ChFace(0, 2, 5);
                Character_ChFace(0, 3, 2);
                Voice_PlayVoice("B0704000_D05600", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nActually, the one who can brag about\nit is me...");
                Message_Who(0);
                Message_MsgDisp("主人公", "Eh? \"Brag\"...?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 2, (#1));
                Character_ChFace(0, 3, 2);
                Voice_PlayVoice("B0704000_D05700", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nIt seems like you don't know what\nI'm talking about...");
                Message_Who(0);
                Message_MsgDisp("主人公", "U-Uhh...");
                Character_ChFace(0, 2, 1);
                Character_ChFace(0, 3, 2);
                Voice_PlayVoice("B0704000_D05800", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "I was really freaking worried about\nit.\nNow I'm the one who looks like an\nidiot!");
                Message_Who(0);
                Message_MsgDisp("主人公", "Wah!");
                Character_ChFace(0, 0, 8);
                Character_BlinkStart(4, 3, (#1));
                Voice_PlayVoice("B0704000_D05900", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nIt's fine, just let it escape your\nmemory!");
                Message_Who(0);
                Message_MsgDisp("主人公", "(He's angry...)");
                Parameter_InCh1Param(4, 537, 42);
                }
            break ;
            }
        }
    else {
        Character_ChFace(0, 4, 1);
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("B0704000_D06000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Hey.... What do you think love is?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh...\nWhy are you asking all of a sudden?");
        Character_ChFace(0, 2, 1);
        Voice_PlayVoice("B0704000_D06100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "...\nDidn't you ask me outta nowhere last\ntime?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, yeah. I did.");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 4, 1);
        Character_BlinkStart(4, 3, (#1));
        Voice_PlayVoice("B0704000_D06200", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "...\n*Sigh* Is it some kind of disease?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh?");
        Character_BlinkStart(4, 2, (#1));
        Voice_PlayVoice("B0704000_D06300", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "The feelings wash over me tons of\ntimes in a day, it's very tiring...\nEven when I sleep, I just dream\nabout it.");
        Character_BlinkStart(4, 3, (#1));
        Voice_PlayVoice("B0704000_D06400", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "This...\nI wonder if I would feel more\nrelaxed if I just spilled it all\nout...");
        Character_BlinkStart(4, 0, (#1));
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("B0704000_D06500", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "............");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Hariya＊＊｝?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(4, 2, (#1));
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("B0704000_D06600", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "... I'll stop.");
        Character_BlinkStart(4, 0, (#1));
        Voice_PlayVoice("B0704000_D06700", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "I got a feeling that this isn't the\nright time...");
        Character_BlinkStart(4, 3, (#1));
        Voice_PlayVoice("B0704000_D06800", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Also, if I did...\nspill it all out, I probably won't\nfeel any better.");
        Character_ChFace(0, 0, 6);
        Voice_PlayVoice("B0704000_D06900", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "............ Let's go home.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Hariya＊＊｝...)");
        Parameter_InCh1Param(4, 538, 43);
        }
    if (var0 == 0){
        if (Parameter_GetCh1Param(4, 558) != 1){
            switch (var1){
                case 10:
                Message_Who(0);
                Message_MsgDisp("主人公", "I want to know more about men.");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_070_00000", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nWhat are you gonna do once you know?");
                Message_Who(0);
                Message_MsgDisp("主人公", "If I know, wouldn't I be able to\ncome up with some sort of plan?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_070_00100", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Gee, a \"plan\"...\nDon't think about shifty things like\nthat!\nCompete with your body!");
                Message_Who(0);
                Message_MsgDisp("主人公", "My body, huh?");
                Character_ChFace(0, 2, 4);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_04_070_00200", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Ah! Don't misunderstand, okay!?\nI don't mean your actual body...!");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_04_070_00300", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Ack! Look at what you made me say!");
                Message_Who(0);
                Message_MsgDisp("主人公", "(Why is he flustered?\n｛Hariya＊＊｝ is acting\nstrange.)");
                break ;
                case 11:
                Message_Who(0);
                Message_MsgDisp("主人公", "What kind of girls do guys like?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_080_00000", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "That all depends on their tastes.");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_080_00100", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Well, it wouldn't hurt to improve\nyourself, right?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_080_00200", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Rather than personality, it might be\neasier to change your appearance....\nHmm? What?");
                Message_Who(0);
                Message_MsgDisp("主人公", "...\nSo are you implying that I don't\nhave a good personality?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 4);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_080_00300", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "N...No!\nHow and where did you pull that idea\nfrom!?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 1);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_080_00400", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "What's with this kind of idiocy!?");
                Message_Who(0);
                Message_MsgDisp("主人公", "(Ugh, he's mad at me...)");
                break ;
                case 12:
                Message_Who(0);
                Message_MsgDisp("主人公", "At what time does a guy's heart beat\nfaster because of something a girl\ndoes?");
                Character_ChFace(0, 2, 4);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_090_00000", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Heart throbbing? What the hell?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Doesn't your heart beat faster\nbecause of a female fan or\nsomething?");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(4, 3, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_090_00100", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "No.");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_090_00200", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nJust standing on the stage is enough\nto make my heart throb, so I don't\nreally pay attention to that.");
                Message_Who(0);
                Message_MsgDisp("主人公", "I-I see..........");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_04_090_00300", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... Sorry for being useless!");
                break ;
                case 13:
                Message_Who(0);
                Message_MsgDisp("主人公", "I wonder how femininity shows.");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_100_00000", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Doesn't it show through gestures or\netiquette?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_100_00100", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "My mother used to do Japanese\ndancing.");
                Voice_PlayVoice("FD_04_100_00200", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Usually, she's kind of boyish or\nmaybe kind of rough, but when she\nwears a kimono, she's different.");
                Voice_PlayVoice("FD_04_100_00300", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Even just seeing her move her\nfingertips, she's completely\ndifferent.\nShe would be delicate or elegant.");
                Voice_PlayVoice("FD_04_100_00400", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "It might be different to the kind of\nfemininity you're talking about,");
                Voice_PlayVoice("FD_04_100_00500", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "but I think that it wouldn't hurt if\nyou learned about those kinda\nthings, too.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(I see...)");
                break ;
                case 14:
                Message_Who(0);
                Message_MsgDisp("主人公", "Unrequited love is so relentless...");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_110_00000", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "At times like that, I write song\nlyrics.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Song lyrics?");
                Voice_PlayVoice("FD_04_110_00100", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Even just one phrase is fine, so I\nwrite down my painful feelings in a\nnotebook.");
                Voice_PlayVoice("FD_04_110_00200", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "You know they become quite good song\nlyrics?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Eh...\nHas it always been that way,\n｛Hariya＊＊｝?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 4);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_04_110_00300", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "It's just my normal emotions... not!\nWe're talking about you here!");
                Message_Who(0);
                Message_MsgDisp("主人公", "(Ugh, even though there was no\nreason for him to get angry, he got\nangry...)");
                break ;
                case 16:
                Character_ChFace(0, 2, 4);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_120_00000", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "What is that? Food?");
                Message_Who(0);
                Message_MsgDisp("主人公", "No!");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 4);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_04_120_00100", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "You're so loud! Okay, I get it!");
                Message_Who(0);
                Message_MsgDisp("主人公", "S-Sorry.\nAre you in love,\n｛Hariya＊＊｝?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 3, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_04_120_00200", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... As if I could be.\nMy hands are full with helping you\nout.");
                Message_Who(0);
                Message_MsgDisp("主人公", "I see... Sorry.");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_04_120_00300", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "S...Shut up, I don't have a right to\nbe apologized to by you!\nIt's uncool! Idiot!");
                Message_Who(0);
                Message_MsgDisp("主人公", "(Ugh...\nHe didn't have to get that angry...)");
                break ;
                case 17:
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_130_00000", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... Hey.\nDon't tell the guy you like that we\ndid that thing, okay?");
                Message_Who(0);
                Message_MsgDisp("主人公", "I-I won't.\nI definitely won't say it, promise!");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_130_00100", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nThat in itself kind of pisses me\noff.");
                Message_Who(0);
                Message_MsgDisp("主人公", "What?! Then what should I...");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_130_00200", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "As if I know!\nSpread rumors around if you want,\njust do whatever you want!\n.........");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_130_00300", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "As expected, you can't say it.\nIf he found out and got angry at\nyou, it'd be bad.\nThat much is certain.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(Ah, what a surprise...)");
                break ;
                case 18:
                Message_Who(0);
                Message_MsgDisp("主人公", "Are you good at skinship,\n｛Hariya＊＊｝?");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_140_00000", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "I'm not good or bad at it.\nWhy are you asking this question?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_140_00100", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "*Sigh*...\nSo you're thinking about touching\nthe guy you like.");
                Message_Who(0);
                Message_MsgDisp("主人公", "T-That's not it...\nHey, ｛Hariya＊＊｝, what's\n\"TAOC\"?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_140_00200", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "You don't know?\nIt's an abbreviation for \"taking\nadvantage of the confusion\".\nYou know, the first thing you'd do.");
                Voice_PlayVoice("FD_04_140_00300", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Well, that should do.\nHarry-sama will give you some good\nadvice.");
                Voice_PlayVoice("FD_04_140_00400", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "If you're going to touch, then touch\nwith confidence!\nThat's all!");
                Message_Who(0);
                Message_MsgDisp("主人公", "(Why did the conversation end up\nbeing under the assumption that I'd\ntouch...?)");
                break ;
                case 19:
                Message_Who(0);
                Message_MsgDisp("主人公", "Isn't it difficult for men and women\nto have a workable friendship?");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_150_00000", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "You...\nAren't you being overly\nself-conscious?\nAre you all right?");
                Message_Who(0);
                Message_MsgDisp("主人公", "I-I didn't mean it like that!\nI was just a little worried.");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_150_00100", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Well, I don't really think so.\nThose kind of things aren't\ndifficult.");
                Voice_PlayVoice("FD_04_150_00200", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Generally, wouldn't you be cut if\nthey said they're MILWE?");
                Message_Who(0);
                Message_MsgDisp("主人公", "... MILWE?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_150_00300", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "\"Madly in love with everyone\"!\nAh, geez, do I gotta spell these\nthings our for you!?");
                Message_Who(0);
                Message_MsgDisp("主人公", "(I don't understand,\n｛Hariya＊＊｝...)");
                break ;
                }
            }
        else {
            switch (var1){
                case 10:
                Message_Who(0);
                Message_MsgDisp("主人公", "What do you think I should do in\norder to know more about guys?");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_070_00400", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nNot guys, but the person you like,\nright?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Yeah... maybe.");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_070_00500", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "\"Maybe\"? ...\nThen are you fine with knowing more\nabout me?\nBecause I'm a guy?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Y-Yes. That's right...");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_070_00600", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nDo you think absolutely nothing of\nme?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 3, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_070_00700", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "What the hell am I saying... Damn...");
                Message_Who(0);
                Message_MsgDisp("主人公", "(｛Hariya＊＊｝?)");
                break ;
                case 11:
                Message_Who(0);
                Message_MsgDisp("主人公", "I wonder what I can do to understand\nguys' preferences.");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_080_00500", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "You'd have no choice but to ask the\nactual person, right?");
                Message_Who(0);
                Message_MsgDisp("主人公", "That's right...");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_080_00600", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... I'll go ask him. Wait.");
                SoundEffect_PlayStream(3, "SS_DSE_060_000");
                Character_Chara_GS2(4, "NON");
                Message_Who(0);
                Message_MsgDisp("主人公", "Eh! ｛Hariya＊＊｝, wait...");
                Character_Chara_GS2(4, "M4_??F", 0);
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_080_00700", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... Idiot.\nIt's obvious I was kidding.");
                Message_Who(0);
                Message_MsgDisp("主人公", "You scared me...\nCome on, don't scare me like that...");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(4, 3, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_080_00800", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Who the hell would do that?\nThere's no way they would...\nThere's no way they could do it...");
                break ;
                case 12:
                Message_Who(0);
                Message_MsgDisp("主人公", "At what times does your heart beat\nfaster, ｛Hariya＊＊｝?");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_090_00400", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nLike when my name is called or when\nthey approach me while making hand\ngestures...");
                Voice_PlayVoice("FD_04_090_00500", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Well, it's not really \"what time\".\nIt's all the time.");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_090_00600", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... Even with you just being there.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Eh... me?");
                Character_ChFace(0, 2, 4);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_090_00700", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "!! ... H-How was it, those lyrics?\nYour heart beat faster, right?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Y-Yeah. For a new song?");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_090_00800", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Yeah, I'm using it as a reference.\nI think all the guys in the world\nhave that kind of feeling....\nProbably.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(｛Hariya＊＊｝?)");
                break ;
                case 13:
                Message_Who(0);
                Message_MsgDisp("主人公", "Should I be more feminine all the\ntime?");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(4, 3, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_100_00600", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "I wonder...\nActually, no one is expecting that\nof you.");
                Message_Who(0);
                Message_MsgDisp("主人公", "\"Of me\"....");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_100_00700", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nI'm saying that you'll be happy when\nyou discover something about you\nthat's feminine.");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_100_00800", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "It's the opposite of what you're\nsaying!\nSo don't look at me with those\nwatery eyes!");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_04_100_00900", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... It makes my heart beat faster.\nNow that you know, look over there\ninstead!");
                Message_Who(0);
                Message_MsgDisp("主人公", "(｛Hariya＊＊｝...)");
                break ;
                case 14:
                Message_Who(0);
                Message_MsgDisp("主人公", "Do you think that there is an\nenjoyable kind of unrequited love?");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_110_00400", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Isn't there?");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(4, 3, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_110_00500", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... I also find it to be good.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Are you experiencing an unrequited\nlove situation too,\n｛Hariya＊＊｝?");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Message_Who(4);
                Message_MsgDisp("Hariya", "......");
                Message_Who(0);
                Message_MsgDisp("主人公", "... Eh, what?\nDid I say something weird?");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_110_00700", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... You didn't.\nThe one who did was me.");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(4, 3, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_110_00800", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "When did things end up like this...?\n*Sigh*");
                break ;
                case 16:
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_120_00400", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nIf I did, I wonder what it'd be\nlike.");
                Message_Who(0);
                Message_MsgDisp("主人公", "I kind of want some reference.");
                Voice_PlayVoice("FD_04_120_00500", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nAs if it could be of any reference.\nI would want you to tell me instead.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Me? Tell you, ｛Hariya＊＊｝?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 3, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_120_00600", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... As expected, I'll just drop it.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Eh, why?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_120_00700", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nI'm curious as to what kind of\nstories other people have about\nlove.");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(4, 3, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_120_00800", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Ah, I won't ask. Yeah...");
                break ;
                case 17:
                Message_Who(0);
                Message_MsgDisp("主人公", "What do you think about kisses,\n｛Hariya＊＊｝?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_130_00400", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "And what about you?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Eh, me?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_130_00500", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "...\nEven if I wanted to forget, I could\nnever forget it.");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_130_00600", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Don't even think about it\noptimistically, like it never\nhappened or something, okay?");
                Message_Who(0);
                Message_MsgDisp("主人公", "... ｛Hariya＊＊｝?");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(4, 3, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_130_00700", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... That's how it is. Remember it.");
                Message_Who(0);
                Message_MsgDisp("主人公", "O-Okay, I got it...");
                break ;
                case 18:
                Message_Who(0);
                Message_MsgDisp("主人公", "Are there any techniques to do\nskinship well?");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_140_00500", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Wouldn't a technique be to be\nunaware about it?");
                Voice_PlayVoice("FD_04_140_00600", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "When you become aware of weird\nthings, how should I put it...");
                Message_Who(0);
                Message_MsgDisp("主人公", "... Yes?");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_140_00700", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "It's like you'll become scared of\ndoing things you usually do, and\nwon't be able to do anything.");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_140_00800", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... Anyway!\nIt's fine if you do things how you\nusually do them.");
                Voice_PlayVoice("FD_04_140_00900", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "There's no need for techniques or\nanything.\nHave self- confidence.\nI guarantee that's the best way.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(... ｛Hariya＊＊｝?)");
                break ;
                case 19:
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(4, 0, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_150_00400", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... Hey.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Hmm? What?");
                Voice_PlayVoice("FD_04_150_00500", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "I wonder who decided up to what\npoint it's friendship, and at what\npoint love starts.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Eh?");
                Voice_PlayVoice("FD_04_150_00600", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "Where is the line between friends\nand lovers?");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(4, 2, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_150_00700", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "... What are we?");
                Message_Who(0);
                Message_MsgDisp("主人公", "... ｛Hariya＊＊｝?");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(4, 3, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_04_150_00800", #1, "");
                Message_Who(4);
                Message_MsgDisp("Hariya", "It seems like I won't be able to get\nany sleep tonight, either.\n*Sigh*...");
                break ;
                }
            }
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
