section "b10_m1_000"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(*sigh*... Why did I say that?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ugh, I hate myself...)");
    SoundEffect_PlaySE(19, 127);
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? Who's calling me?");
    SoundEffect_StopSE(19, 0);
    SoundEffect_PlaySE(20, 127);
    Message_Who(0);
    Message_MsgDisp("主人公", "Hello.");
    Voice_PlayVoice("B1001000_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It's me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝?");
    Voice_PlayVoice("B1001000_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I can't keep my anger down, so I had\nto call you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Um, about earlier--");
    Voice_PlayVoice("B1001000_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "--Is what I had planned...\nBut after hearing your voice, I've\nchanged my mind.");
    Voice_PlayVoice("B1001000_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "... Sorry. That's all.\nI'm hanging up.");
    SoundEffect_PlaySE(23, 127);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Saeki＊＊｝, did he call\nto just check up on me...?)");
    SoundEffect_StopSE(23, 0);
    SoundEffect_PlaySE(20, 127);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
