section "b10_m5_000"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(*Sigh* Why did I say that?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ugh, I hate myself...)");
    SoundEffect_PlaySE(19, 127);
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? Who's calling me?");
    SoundEffect_StopSE(19, 0);
    SoundEffect_PlaySE(20, 127);
    Message_Who(0);
    Message_MsgDisp("主人公", "Hello.");
    Voice_PlayVoice("B1005000_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah.... It's me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝? What's wrong?");
    Voice_PlayVoice("B1005000_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah... Sorry about today.\nYou know, about that thing.");
    Voice_PlayVoice("B1005000_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I'd be glad if we could learn from\nthis bad experience and hang out\ntogether, again.");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's fine, I wasn't worried about it\nat all!");
    Voice_PlayVoice("B1005000_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Thanks.\nNow then, be careful on your way\nhome, okay?\nGood night.");
    SoundEffect_PlaySE(23, 127);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Chris＊＊｝ called to\ncheck up on me.\nThank you...)");
    SoundEffect_StopSE(23, 0);
    SoundEffect_PlaySE(20, 127);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
