section "b11_m8_000"{
    if ((Date_Date_Data(7) == 0) || (Date_Date_Data(7) == 1)){
        Character_Chara_GS2(20, "N1_17F", 0);
        Voice_PlayVoice("B1108000_T00000", #1, "");
        Message_Who(20);
        Message_Who(20);
        Message_MsgDisp("Man", "Heey, girl! What's the matter?\nSeems like you were stood up.");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's nothing like that.");
        Voice_PlayVoice("B1108000_T00100", #1, "");
        Message_Who(20);
        Message_Who(20);
        Message_MsgDisp("Man", "It's alright, it's alright, no need\nto pretend.\nHey, let's go over there for some\ntea♪");
        Message_Who(0);
        Message_MsgDisp("主人公", "Well, this is really\nembarrassing...!");
        Voice_PlayVoice("B1108000_H00200", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Oi, bro.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah... ｛Masaki＊＊｝!)");
        Character_Chara_GS2(8, "M8_D?F", 0, 1, 1, 36);
        Character_ChFace(1, 2, 1);
        Character_ChFace(1, 3, 2);
        Music_PlayBGM(0, "MN_C_08_000_D03", 127, 40);
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("B1108000_T00300", #1, "");
        Message_Who(20);
        Message_Who(20);
        Message_MsgDisp("Man", "Huuh!? Who are you!");
        Character_ChFace(1, 3, 0);
        Voice_PlayVoice("B1108000_H00400", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "... I'll teach you something useful.\nJust for today, okay?");
        Voice_PlayVoice("B1108000_H00500", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "I've got the special ability to see\nwhen something bad is going down.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("B1108000_T00600", #1, "");
        Message_Who(20);
        Message_Who(20);
        Message_MsgDisp("Man", "... Huh?");
        Character_ChFace(1, 2, 5);
        Character_ChFace(1, 3, 2);
        Voice_PlayVoice("B1108000_H00700", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "I've been watching you forever～...\nThere's been a black shadow\nfollowing you everywhere...");
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 1);
        Voice_PlayVoice("B1108000_H00800", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "It's slowly taking over...\nAnd when it has completely taken\nover, your body...!!!");
        Voice_PlayVoice("B1108000_T00900", #1, "");
        Message_Who(20);
        Message_Who(20);
        Message_MsgDisp("Man", "Kyaa! I hate those kind of stories!");
        Character_Chara_GS2(20, "NON");
        Character_Chara_GS2(8, "M8_D?F", 0);
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("B1108000_H01000", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "*Sigh*... What an idiot.\nEveryone will have a shadow when the\nsun shines on them.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Sorry about that,\n｛Masaki＊＊｝...");
        Character_ChFace(0, 2, 2);
        Voice_PlayVoice("B1108000_H01100", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "You're welcome....\nSorry for being late.\nI'll make sure it doesn't happen,\nagain.\nFor real.");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("B1108000_H01200", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Let's forget this whole thing and\ngo.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I'm glad ｛Masaki＊＊｝\ncame...)");
        }
    else if ((Date_Date_Data(7) == 2) || (Date_Date_Data(7) == 3)){
        Character_Chara_GS2(21, "N2_17F", 0);
        Voice_PlayVoice("B1108000_U01300", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "I've finally found you～!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh? M-Me?");
        Voice_PlayVoice("B1108000_U01400", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "Yeah!\nI've brought you a pamphlet that has\nthe things you want in it!");
        Message_Who(0);
        Message_MsgDisp("主人公", "I never said anything like that...");
        Voice_PlayVoice("B1108000_U01500", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "It's fine～, you'll want this pillow\nwhen you see it!\nSo let's go to that cafe over\nthere...");
        Voice_PlayVoice("", 8, "B1108000_H01600");
        Message_Who(8);
        Message_MsgDisp("Masaki", "｛主人公｝.\nSorry for making you wait!");
        Character_Chara_GS2(8, "M8_??F", 0, 1, 1, 38);
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 1);
        Music_PlayBGM(0, "MN_C_08_000_D03", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Masaki＊＊｝!");
        Character_ChFace(1, 2, 3);
        Character_ChFace(1, 3, 2);
        Voice_PlayVoice("B1108000_H01700", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Who's this? Huh...\nwhere have I seen you before...");
        Character_ChFace(1, 2, 4);
        Character_ChFace(1, 3, 1);
        Voice_PlayVoice("B1108000_H01800", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Ah!\nAren't you Saitou-kun's older\nbrother!");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("B1108000_U01900", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "N-No! You're mistaken.");
        Character_ChFace(1, 2, 1);
        Character_ChFace(1, 3, 0);
        Voice_PlayVoice("B1108000_H02000", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "No, you are Saitou-kun's older\nbrother.\nThere's no way a customer service\npro like me would be wrong.");
        Voice_PlayVoice("B1108000_H02100", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "You know your younger bro was\ncrying～?\nHe said that his big bro couldn't\nquit from the shady sales business.");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("B1108000_U02200", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "Ugh...");
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 0);
        Voice_PlayVoice("B1108000_H02300", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Don't make him cry.\nHe's real worried about you.");
        Voice_PlayVoice("B1108000_U02400", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "Do you know that much about me...\nForgive me for being such a bad\nolder brother～!");
        Character_Chara_GS2(21, "NON");
        SoundEffect_PlayStream(3, "SS_DSE_060_000");
        Character_Chara_GS2(8, "M8_??F", 0);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "... Was that all for real?");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("B1108000_H02500", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "...\nIt's true that his younger brother\nwas my classmate.\nThe worrying part was a lie.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Will it be okay?\nSaying that kind of thing...");
        Character_BlinkStart(8, 3, (#1));
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("B1108000_H02600", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "I don't mind lying if it means that\nit will protect you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_BlinkStart(8, 0, (#1));
        Voice_PlayVoice("B1108000_H02700", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Anyway.\nIf that kinda person talks to you\nagain, just ignore them, okay?");
        Voice_PlayVoice("B1108000_H02800", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "I'll be careful not to come late,\nbut you also gotta watch out....\nOkay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes... I understand.");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("B1108000_H02900", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Let's go then.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I'm glad ｛Masaki＊＊｝\ncame...)");
        }
    }
