section "b11_m1_000"{
    int var0;
    int var1;
    if ((Date_Date_Data(7) == 0) || (Date_Date_Data(7) == 1)){
        var0 = Date_Get_Date_Place2();
        if (var0 == 6){
            if (Date_ChkDateOpen(15) == 1){
                var1 = 1;
                }
            }
        if (var1 == 0){
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh, it seems like\n｛Saeki＊＊｝ hasn't come\nyet.");
            Message_Who(0);
            Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Saeki＊＊｝ is late...");
            Character_Chara_GS2(20, "N1_17F", 0);
            Voice_PlayVoice("B1101000_T00000", #1, "");
            Message_Who(20);
            Message_Who(20);
            Message_MsgDisp("Man", "Hey there girl, are you waiting in\nvain?\nIf you are, come and have some tea\nwith me instead.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh!? No, I'm fine.");
            Voice_PlayVoice("B1101000_T00100", #1, "");
            Message_Who(20);
            Message_Who(20);
            Message_MsgDisp("Man", "It's fine, it's fine.\nCome on, let's go.");
            Message_Who(0);
            Message_MsgDisp("主人公", "W-Wait...");
            Character_Chara_GS2(1, "M1_D?F", 0, 1, 1, 36);
            Character_ChFace(1, 2, 2);
            Character_ChFace(1, 3, 3);
            Music_PlayBGM(0, "MN_C_01_000_D03", 127, 40);
            Message_PauseSkinship();
            Voice_PlayVoice("B1101000_A00200", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "If you're looking for someone to hit\non, go look somewhere else.\nYou're just embarrassing yourself.");
            Character_ChFace(0, 0, 8);
            Voice_PlayVoice("B1101000_T00300", #1, "");
            Message_Who(20);
            Message_Who(20);
            Message_MsgDisp("Man", "Who the hell are you?\nIn a few seconds, I was gonna--\nWhoa, you're cool...");
            Character_ChFace(1, 2, 1);
            Character_BlinkStart(1, 2, (#1), 2);
            Character_ChFace(1, 3, 2);
            Voice_PlayVoice("B1101000_A00400", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Gonna what? Go ahead and say it.");
            Character_ChFace(0, 0, 4);
            Voice_PlayVoice("B1101000_T00500", #1, "");
            Message_Who(20);
            Message_Who(20);
            Message_MsgDisp("Man", "Uhh～...\nI was gonna ask for directions.");
            Voice_PlayVoice("B1101000_A00600", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Don't go around acting all cool\nhere, you're an eyesore.\nAnd--");
            Character_ChFace(1, 0, 8);
            Voice_PlayVoice("B1101000_A00700", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Don't go hitting on other people's\ngirls.\nIt pisses me off.");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("B1101000_T00800", #1, "");
            Message_Who(20);
            Message_Who(20);
            Message_MsgDisp("Man", "Yes! E-Excuse me!");
            Character_Chara_GS2(20, "NON");
            Character_ChFace(0, 0, 3);
            Message_ResumeSkinship();
            Voice_PlayVoice("B1101000_A00900", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Pfft, he's no match for me.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Um, thank you,\n｛Saeki＊＊｝.");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("B1101000_A01000", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "It's fine, It's because I was\nlate...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah, but you still saved me.");
            Character_ChFace(0, 0, 3);
            Character_BlinkStart(1, 2, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("B1101000_A01100", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Ah, anyway! ...\nAbout that \"people's girls\" thing, I\njust said it in the heat of the\nmoment...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Saeki＊＊｝...\nIs he embarrassed?)");
            }
        else {
            Background_Bg_GS2("BG_WF530_SU_0", #1, #1, 0);
            Screen_WipeIn(2);
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh, it seems like\n｛Saeki＊＊｝ hasn't come\nyet.");
            Message_Who(0);
            Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Saeki＊＊｝ is late...");
            Character_Chara_GS2(22, "N3_09F", 0);
            Voice_PlayVoice("B1101000_V01200", #1, "");
            Message_Who(22);
            Message_Who(22);
            Message_MsgDisp("Man", "Hey! That girl over there!\nAre you alone?");
            Message_Who(0);
            Message_MsgDisp("主人公", "No, I'm not.");
            Voice_PlayVoice("B1101000_V01300", #1, "");
            Message_Who(22);
            Message_Who(22);
            Message_MsgDisp("Man", "Come now～!\nShould we go take-off somewhere?\nAh, \"take-off\" is surfer lingo.");
            Message_Who(0);
            Message_MsgDisp("主人公", "No, I am fine, so please...");
            Voice_PlayVoice("B1101000_V01400", #1, "");
            Message_Who(22);
            Message_Who(22);
            Message_MsgDisp("Man", "Aren't the waves awesome today?\nYou know, both offshore and\nonshore--");
            Character_Chara_GS2(1, "M1_09F", 0, 1, 1, 37);
            Music_PlayBGM(0, "MN_C_01_000_D03", 127, 40);
            Message_PauseSkinship();
            Voice_PlayVoice("B1101000_A01500", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Hi.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Saeki＊＊｝!\nThank goodness!");
            Character_ChFace(0, 0, 4);
            Voice_PlayVoice("B1101000_V01600", #1, "");
            Message_Who(22);
            Message_Who(22);
            Message_MsgDisp("Man", "Wah! S-Saeki-kun!?");
            Character_ChFace(1, 2, 1);
            Character_BlinkStart(1, 2, (#1), 2);
            Character_ChFace(1, 3, 0);
            Voice_PlayVoice("B1101000_A01700", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Yo. What are the waves like today?");
            Character_ChFace(0, 0, 9);
            Voice_PlayVoice("B1101000_V01800", #1, "");
            Message_Who(22);
            Message_Who(22);
            Message_MsgDisp("Man", "U-Uh～, right...\nAh, I've got stuff to do! Later!");
            Character_Chara_GS2(22, "NON");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(1, 2, (#1));
            Character_ChFace(0, 3, 1);
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you know that person?");
            Voice_PlayVoice("B1101000_A01900", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Kinda.\nHe's a famous surfer around here.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ehh, is that so...");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 1);
            Message_ResumeSkinship();
            Voice_PlayVoice("B1101000_A02000", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Hey, you shouldn't be saying \"is\nthat so\", you...");
            Voice_PlayVoice("B1101000_A02100", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Standing around the beach in your\nswimming costume, aren't you asking\nfor people to hit on you?");
            Message_Who(0);
            Message_MsgDisp("主人公", "It's because you were late,\n｛Saeki＊＊｝...");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B1101000_A02200", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Well, that's true... Sorry.\nLet's go!");
            Message_CloseMsg();
            Screen_WipeOut(2);
            Screen_ClearScreen();
            }
        }
    else if ((Date_Date_Data(7) == 2) || (Date_Date_Data(7) == 3)){
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh, it seems like\n｛Saeki＊＊｝ hasn't come\nyet.");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝ is late...");
        Character_Chara_GS2(21, "N2_17F", 0);
        Voice_PlayVoice("B1101000_U02300", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "You got a minute?\nAh, such pretty hair.\nWhat kind of shampoo do you use?");
        Message_Who(0);
        Message_MsgDisp("主人公", "U-Umm...\nI'm busy waiting for someone.");
        Voice_PlayVoice("B1101000_U02400", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "Come on!\nLet's talk while you wait for them!\nWe'll just talk about your nice\nhair, okay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "No thank you. Really, I am fine!");
        Character_Chara_GS2(1, "M1_??F", 0, 1, 1, 38);
        Character_ChFace(1, 2, 1);
        Character_ChFace(1, 3, 2);
        Music_PlayBGM(0, "MN_C_01_000_D03", 127, 40);
        Message_PauseSkinship();
        Voice_PlayVoice("B1101000_A02500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Hey.");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("B1101000_U02600", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "Wah!");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝...\nThank gosh...");
        Message_ResumeSkinship();
        Voice_PlayVoice("B1101000_A02700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "What are you talking about?\nWhy are you fawning over being\npraised by some shady guy?");
        Message_PauseSkinship();
        Message_Who(0);
        Message_MsgDisp("主人公", "Me!? I'm not fawning.");
        Character_ChFace(1, 2, 1);
        Character_BlinkStart(1, 2, (#1), 2);
        Character_ChFace(1, 3, 2);
        Voice_PlayVoice("B1101000_A02800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "You were.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I said I wasn't!");
        Voice_PlayVoice("B1101000_A02900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "You were! You were, weren't you?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I wasn't.");
        Character_ChFace(0, 0, 4);
        Voice_PlayVoice("B1101000_U03000", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "A-Are you guys ignoring me!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "If you're going to get jealous,\ndon't come late.");
        Character_ChFace(1, 2, 4);
        Character_BlinkStart(1, 2, (#1), 2);
        Character_ChFace(1, 3, 1);
        Message_ResumeSkinship();
        Voice_PlayVoice("B1101000_A03100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Jealous? Hah! Jealous of who?");
        Message_PauseSkinship();
        Voice_PlayVoice("B1101000_U03200", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "Come now.\nSince you guys are on a date, you\nguys should enjoy and have fun,\nright?");
        Character_ChFace(1, 2, 1);
        Character_BlinkStart(1, 2, (#1), 2);
        Character_ChFace(1, 3, 0);
        Voice_PlayVoice("B1101000_A03300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Shut up.");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's got nothing to do with you!");
        Character_ChFace(0, 0, 2);
        Voice_PlayVoice("B1101000_U03400", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "What should I...");
        Character_ChFace(1, 2, 1);
        Character_ChFace(1, 3, 0);
        Message_ResumeSkinship();
        Voice_PlayVoice("B1101000_A03500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Let's go.\nIf we stay here any longer, someone\nelse might pull your leg.");
        Message_PauseSkinship();
        Music_StopBGM(0, 40);
        Character_Chara_GS2(1, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, wait!\nNo one's going to pull my leg!");
        Character_ChFace(0, 0, 4);
        Voice_PlayVoice("B1101000_U03600", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "What a weird couple...");
        }
    }
