section "b11_m4_000"{
    int var0;
    int var1;
    if ((Date_Date_Data(7) == 0) || (Date_Date_Data(7) == 1)){
        var0 = Date_Get_Date_Place2();
        if (var0 == 6){
            if (Date_ChkDateOpen(15) == 1){
                var1 = 1;
                }
            }
        if (var1 == 0){
            Character_Chara_GS2(20, "N1_17F", 0);
            Voice_PlayVoice("B1104000_T00000", #1, "");
            Message_Who(20);
            Message_Who(20);
            Message_MsgDisp("Man", "Hey, miss, are you alone?\nWanna have some tea with me?");
            Message_Who(0);
            Message_MsgDisp("主人公", "No, I am waiting for someone...");
            Voice_PlayVoice("B1104000_T00100", #1, "");
            Message_Who(20);
            Message_Who(20);
            Message_MsgDisp("Man", "But I've been watching you forever,\nno one's coming～.\nCome on, let's go～.");
            Voice_PlayVoice("B1104000_D00200", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Hey, you.");
            Character_Chara_GS2(4, "M4_D?F", 0, 1, 1, 36);
            Character_ChFace(1, 0, 8);
            Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
            Voice_PlayVoice("B1104000_D00300", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Isn't it about time you get lost\nwith that ugly face of yours?");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Hariya＊＊｝!");
            Character_ChFace(0, 0, 8);
            Voice_PlayVoice("B1104000_T00400", #1, "");
            Message_Who(20);
            Message_Who(20);
            Message_MsgDisp("Man", "Huh...? What ugly face!?\nDon't screw with me!");
            Character_BlinkStart(4, 3, (#1), 2);
            Voice_PlayVoice("B1104000_D00500", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Geez, this guy doesn't know when to\nquit!\nListen, from here on......");
            Voice_PlayVoice("B1104000_T00600", #1, "");
            Message_Who(20);
            Message_Who(20);
            Message_MsgDisp("Man", "F...From here on what? I wanna know!");
            Character_BlinkStart(4, 0, (#1), 2);
            Character_ChFace(1, 3, 5);
            Voice_PlayVoice("B1104000_D00700", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Alright, gimme your ear.");
            Character_ChFace(1, 0, 8);
            Voice_PlayVoice("B1104000_D00800", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "... Just go get lost!");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("B1104000_T00900", #1, "");
            Message_Who(20);
            Message_Who(20);
            Message_MsgDisp("Man", "Waaaah! My e-eaaaaar!\nYou better r-remember thiiis!");
            Character_Chara_GS2(20, "NON");
            Character_Chara_GS2(4, "M4_D?F", 0);
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("B1104000_D01000", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "...\nDon't make light of how loud a\nvocalist's voice can get.");
            Character_ChFace(0, 2, 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B1104000_D01100", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "That guy's got no hope of\nrecovering.\nServes him right.");
            Character_ChFace(0, 0, 9);
            Voice_PlayVoice("B1104000_D01200", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Oi, you okay?\nSorry for always being late...");
            Message_Who(0);
            Message_MsgDisp("主人公", "I'm fine.\nThanks, ｛Hariya＊＊｝.");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("B1104000_D01300", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Yeah. Let's go!");
            Message_Who(0);
            Message_MsgDisp("主人公", "Okay.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I'm glad ｛Hariya＊＊｝\ncame...)");
            }
        else {
            Character_Chara_GS2(22, "N3_09F", 0);
            Background_Bg_GS2("BG_WF530_SU_0", #1, #1, 0);
            Screen_WipeIn(2);
            Voice_PlayVoice("B1104000_V01400", #1, "");
            Message_Who(22);
            Message_Who(22);
            Message_MsgDisp("Man", "Hey girl, you're cute▼ Come surfing\nwith me, Habataki's swimming king!");
            Message_Who(0);
            Message_MsgDisp("主人公", "I will decline.");
            Voice_PlayVoice("B1104000_V01500", #1, "");
            Message_Who(22);
            Message_Who(22);
            Message_MsgDisp("Man", "Are you worried about the storm\nwarnings?\nThen let's go eat something sweet at\nthe beach house...");
            Voice_PlayVoice("B1104000_D01600", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Since you're the swimming king, it\nmeans you're good at swimming,\nright?");
            Voice_PlayVoice("B1104000_V01700", #1, "");
            Message_Who(22);
            Message_Who(22);
            Message_MsgDisp("Man", "Of course I am～.... Eh?");
            Character_Chara_GS2(4, "M4_09F", 0, 1, 1, 37);
            Character_ChFace(1, 0, 10);
            Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
            Voice_PlayVoice("B1104000_D01800", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Then teach me the crawl and\nbreaststroke.");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("B1104000_V01900", #1, "");
            Message_Who(22);
            Message_Who(22);
            Message_MsgDisp("Man", "...\nUmm, big bro is a little busy right\nnow.\nYou can see that can't you, kid?");
            Character_ChFace(1, 2, 2);
            Character_ChFace(1, 3, 1);
            Voice_PlayVoice("B1104000_D02000", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "... I can't! That's so unfair, bro!\nWhy won't you teach me!?");
            Character_ChFace(0, 0, 9);
            Voice_PlayVoice("B1104000_V02100", #1, "");
            Message_Who(22);
            Message_Who(22);
            Message_MsgDisp("Man", "Wh... What!?");
            Character_ChFace(1, 4, 1);
            Character_BlinkStart(4, 2, (#1), 2);
            Voice_PlayVoice("B1104000_D02200", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "I wanted to learn how to swim,\ntoo...\nYou're so mean, swimming king!!");
            Character_ChFace(0, 0, 9);
            Voice_PlayVoice("B1104000_V02300", #1, "");
            Message_Who(22);
            Message_Who(22);
            Message_MsgDisp("Man", "O-Oi, cut it out! You're too loud.\nIt's embarrassing!");
            Character_Chara_GS2(22, "NON");
            Character_Chara_GS2(4, "M4_09F", 0);
            Character_ChFace(0, 4, 0);
            Character_BlinkStart(4, 0, (#1));
            Character_ChFace(0, 2, 3);
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("B1104000_D02400", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "What was with that closing line...?");
            Character_ChFace(0, 0, 9);
            Voice_PlayVoice("B1104000_D02500", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Oi, are you okay?");
            Message_Who(0);
            Message_MsgDisp("主人公", "T-Thanks, ｛Hariya＊＊｝.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(4, 3, (#1));
            Voice_PlayVoice("B1104000_D02600", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "That guy...\nWhat a waste, even though he can\nswim, too.\nWhy did he come here?");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Hariya＊＊｝...?");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("B1104000_D02700", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Nothing! Let's go.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Okay.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I'm glad that ｛Hariya＊＊｝\ncame...)");
            Message_CloseMsg();
            Screen_WipeOut(2);
            Screen_ClearScreen();
            }
        }
    else if ((Date_Date_Data(7) == 2) || (Date_Date_Data(7) == 3)){
        Character_Chara_GS2(21, "N2_17F", 0);
        Voice_PlayVoice("B1104000_U02800", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "Mega cute girls! Giga cool guys!\nDon't you want to know the magic you\nneed to turn into that?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!? No, I...\ndon't really want to know.");
        Voice_PlayVoice("B1104000_U02900", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "I'll tell you about special super\nhigh quality goods!\nJust give me your number!");
        Voice_PlayVoice("B1104000_D03000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "I'll give you mine!");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("B1104000_U03100", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "Huh? Who are you!?");
        Character_Chara_GS2(4, "M4_??F", 0, 1, 1, 38);
        Character_ChFace(1, 2, 1);
        Character_ChFace(1, 3, 3);
        Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
        Voice_PlayVoice("B1104000_D03200", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "I'm Harry...\nI'm the future superstar that\neveryone will know.");
        Character_BlinkStart(4, 3, (#1), 2);
        Voice_PlayVoice("B1104000_D03300", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Why do you want my number?\nI'm cool enough already.\nYou thought that, right? Didn't you?");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("B1104000_U03400", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "Y...Yes...");
        Character_BlinkStart(4, 0, (#1), 2);
        Voice_PlayVoice("B1104000_D03500", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "It's because I'm amazing!\nI'm not happy with myself right now,\nnot me, Hariya Kounoshin!");
        Voice_PlayVoice("B1104000_U03600", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "... Kounoshin?");
        Character_BlinkStart(4, 2, (#1), 2);
        Character_ChFace(1, 3, 2);
        Voice_PlayVoice("B1104000_D03700", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "... You bastard...\nHow did you learn of that name...");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("B1104000_U03800", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "Eh? J-Just then, you yourself...");
        Character_ChFace(1, 0, 8);
        Voice_PlayVoice("B1104000_D03900", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Don't screw around with me.\nWhy the hell would I do that!?\nAnyway, I'll give you mine!");
        Voice_PlayVoice("B1104000_U04000", #1, "");
        Message_Who(21);
        Message_Who(21);
        Message_MsgDisp("Man", "I... I'll get it off you next time!");
        Character_Chara_GS2(21, "NON");
        Character_Chara_GS2(4, "M4_??F", 0);
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("B1104000_D04100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Pfft, how boring.\nI was gonna give it to him.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Hariya＊＊｝, you were\nlate!");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("B1104000_D04200", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Ah, I'm very sorry.\nI'll make sure I'm not late next\ntime...\nLet's forget this whole thing and\ngo.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I'm glad ｛Hariya＊＊｝\ncame...)");
        }
    }
