section "b15_m5_005"{
    Background_Bg_GS2("BG_EX101_?_2", 1, #1, 0);
    Character_Chara_GS2(5, "M5_D?F", 0, 1);
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 1);
    Screen_WipeIn(3);
    Voice_PlayVoice("XD_05_00_E03900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Humans are really greedy.");
    Voice_PlayVoice("XD_05_00_E04000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Even though I get along with you so\nwell, I want more and more.");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("XD_05_00_E04100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I want to be by your side more.\nI want to touch you more.\nI always want more.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yeah.");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("XD_05_00_E04200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "But...");
    Message_Who(0);
    Message_MsgDisp("主人公", "But?");
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 6, 2);
    Voice_PlayVoice("XD_05_00_E04300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I can't take a step forward.\nOnce I go forward, I definitely\nwon't be able to stop.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("XD_05_00_E04400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... But I'm incapable of doing it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝, you're not\nincapable...");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("XD_05_00_E04500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "As expected, we gotta be cautious.\nBoth me and you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Chris＊＊｝...)");
    }
