section "b15_m7_001"{
    Character_ChFace(0, 0, 9);
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Character_Chara_GS2(7, "M7_06F", 0, 1);
    Screen_WipeIn(3);
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("", 7, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes?");
    Voice_PlayVoice("", 7, "XD_07_00_G00900");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Look at me, ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay.");
    Voice_PlayVoice("XD_07_00_G01000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Why do you want to touch Sensei in\nthat way?\nHuh?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, I'm sorry...");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_07_00_G01100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I am not angry. I just want to know.");
    Voice_PlayVoice("XD_07_00_G01200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "You are like a baby that wants to\ntouch something interesting.\nYou touch the cheek and got used to\nit.\nThis time, the body.");
    Message_Who(0);
    Message_MsgDisp("主人公", "That's not it...");
    Voice_PlayVoice("XD_07_00_G01300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Yes.\nWell then, what do you think will be\nnext?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_07_00_G01400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "B-Buzz. Time's up.\nThe correct answer is, you would\nwant to kiss my lips.\nTherefore...");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yes.");
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("", 7, "XD_07_00_G01500");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝, please do not\neat Sensei.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay!");
    }
