section "b15_m5_001"{
    Background_Bg_GS2("BG_EX101_?_2", 1, #1, 0);
    Character_Chara_GS2(5, "M5_D?F", 0, 1);
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 1);
    Screen_WipeIn(3);
    Voice_PlayVoice("XD_05_00_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Do you love skinship?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uh... Can I not like it?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("XD_05_00_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Hmm.\nI'm not saying that you can't.\nRather, I'm glad.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("XD_05_00_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "But it's common sense for my body.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Common sense?\nAh, do you mean that the body is\nmore frank?");
    Character_BlinkStart(5, 0, (#1), 1);
    Character_ChFace(0, 4, 0);
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_05_00_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah, that.");
    Voice_PlayVoice("XD_05_00_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "A boy's body is unexpectedly\ndelicate.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("XD_05_00_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "So I'm not saying doing this is bad,\nbut to be cautious.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("XD_05_00_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... And that I'm also a boy.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Chris＊＊｝...)");
    }
