section "b15_m2_004"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(2, "M2_??F", 0, 1);
    Voice_PlayVoice("", 2, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hm? What?");
    Voice_PlayVoice("XD_02_00_B03300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "I've always been curious about\nthis-- Why do you touch me a lot?");
    Message_Who(0);
    Message_MsgDisp("主人公", "B-Because...");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 6, 2);
    Voice_PlayVoice("XD_02_00_B03400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nI have intentions of wanting to\ntouch you.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("XD_02_00_B03500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "-- Because there are intentions, I'm\nscared of being touched by you.\nIt seems like something will happen.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("XD_02_00_B03600", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "So...\nIf you're perhaps touching me with\nno particular reason, you'd better\nstop.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("XD_02_00_B03700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "But if you're touching me with the\nsame intentions that I have, then\ndon't stop.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Shiba＊＊｝.)");
    }
