section "b15_m2_003"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(2, "M2_??F", 0, 1);
    Voice_PlayVoice("XD_02_00_B02300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "I'm glad that you're that size.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? Are you talking about my height?");
    Voice_PlayVoice("XD_02_00_B02400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Yeah.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Why?");
    Voice_PlayVoice("XD_02_00_B02500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Isn't it convenient?\nFor various situations.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Various situations?");
    Voice_PlayVoice("XD_02_00_B02600", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Like changing light bulbs.\nAnd people could be a windbreaker\nfor you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, you'd even do that for me?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("XD_02_00_B02700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... There are other things, too.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh... Other things?");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 6, 2);
    Voice_PlayVoice("XD_02_00_B02800", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "What do you think?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm. I wonder...");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("XD_02_00_B02900", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "For example...");
    Voice_PlayVoice("XD_02_00_B03000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("XD_02_00_B03100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Well, look forward to it.");
    }
