section "b15_m2_002"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(2, "M2_??F", 0, 1);
    Voice_PlayVoice("XD_02_00_B01500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Hm? Is there something on my face?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? Ah, yeah! I think it's lint.\nIt's fine, I've removed it already.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("XD_02_00_B01600", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Thanks....\nThere's also something in the corner\nof your eye.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh, really?");
    Voice_PlayVoice("XD_02_00_B01700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "I'll get it. Don't move.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("XD_02_00_B01800", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "......");
    Message_Who(0);
    Message_MsgDisp("主人公", "... ｛Shiba＊＊｝? Umm...\nYour hand...");
    Voice_PlayVoice("XD_02_00_B01900", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Your cheeks are soft.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... R-Really?");
    Voice_PlayVoice("XD_02_00_B02000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Yeah.... Your lips, too.");
    Message_Who(0);
    Message_MsgDisp("主人公", "U-Uhh...");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("XD_02_00_B02100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... You're way too defenseless.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 6, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("XD_02_00_B02200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "But it's fine if you're like this\nwith just me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Shiba＊＊｝...)");
    }
