section "b15_m1_000"{
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(1, "M1_??F", 0, 1);
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("XD_01_00_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Argh, damn!");
    Message_Who(0);
    Message_MsgDisp("主人公", "What!? ... What's wrong?");
    Voice_PlayVoice("XD_01_00_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "You know what's wrong!\nYou've been touching and feeling.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sorry. I'll stop...");
    Voice_PlayVoice("XD_01_00_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Don't stop! Ah, no...");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("XD_01_00_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It's fine.\nBut you know, I'm a guy after all...");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("XD_01_00_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "What should I do?");
    Message_Who(0);
    Message_MsgDisp("主人公", "What should you do? What's wrong?");
    Character_ChFace(0, 0, 9);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_01_00_A00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_01_00_A00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I'm leaving.");
    SoundEffect_PlayStream(3, "SS_DSE_060_000");
    Character_Chara_GS2(1, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Saeki＊＊｝!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He left...)");
    }
