section "b15_m7_003"{
    Character_ChFace(0, 0, 10);
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Character_Chara_GS2(7, "M7_06F", 0, 1);
    Screen_WipeIn(3);
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_07_00_G02400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Stop.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, umm...\nIs something wrong?");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_07_00_G02500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Well... Something may be wrong.\nYou touch me too much.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm sorry.... I'll be careful.");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_07_00_G02600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Good. You see, I have a question.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝?");
    Voice_PlayVoice("XD_07_00_G02700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "So, it's necessary to decide what\nI'll do about it.\nI am more than just some adult...\nI am a teacher.");
    Voice_PlayVoice("XD_07_00_G02800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Therefore, in all honesty, there are\nno other options.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, that--");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_07_00_G02900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "The same thing.\nI have to make a good appearance.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes...");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_07_00_G03000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It's all right.\nI am a teacher and you are a\nstudent....\nGoodbye.");
    SoundEffect_PlayStream(3, "SS_DSE_069_000");
    Character_Chara_GS2(7, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He's gone.)");
    }
