section "b15_m3_001"{
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 4, 1);
    Character_Chara_GS2(3, "M3_??F", 0, 1);
    Voice_PlayVoice("XD_03_00_C00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Stop. Stop!");
    Message_Who(0);
    Message_MsgDisp("主人公", "!?");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_03_00_C00700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "*Sigh*... Let's calm down.\nI'm already calm. What about you?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah. I'm fine.");
    Character_ChFace(0, 0, 9);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_03_00_C00800", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Okay. This is normal.\nI'm a straight-laced person.");
    Message_Who(0);
    Message_MsgDisp("主人公", "That's not--");
    Voice_PlayVoice("XD_03_00_C00900", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "It's fine.\nOn that point, I want to mature.");
    Voice_PlayVoice("XD_03_00_C01000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "However, I want you to understand\nthat...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ok, I understand.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("XD_03_00_C01100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Experiencing things and dealing with\nthings in a flexible way.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, it sounds like you're talking\nabout studying,\n｛Hikami＊＊｝.");
    Character_ChFace(0, 0, 9);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_03_00_C01200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "R-Right.\nNow that you've said it, it really\ndoes seem so...");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's becoming of you,\n｛Hikami＊＊｝.");
    Character_ChFace(0, 0, 9);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_03_00_C01300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "That is the problem.\nMy complex mental state...\nI will excuse myself today.");
    SoundEffect_PlayStream(3, "SS_DSE_060_000");
    Character_Chara_GS2(3, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(It seems like ｛Hikami＊＊｝\nis worried over something...)");
    }
