section "b15_m6_002"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Character_Chara_GS2(6, "M6_D?F", 0, 1);
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 2);
    Screen_WipeIn(3);
    Voice_PlayVoice("", 6, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "......");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("XD_06_00_F01400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Seeeemppaaaaii, what's wrong?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh... Aah, I'm sorry!\nI was thinking about something for a\nmoment.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("XD_06_00_F01500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Hmm...\nWere you thinking deeply while you\nwere unconsciously touching me?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ugh... I-I'm sorry.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("XD_06_00_F01600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "It's okay, it's nothing.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("XD_06_00_F01700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Now, try thinking about something\nbesides me.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("XD_06_00_F01800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Senpai, you're cute.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh... ｛Amachi＊＊｝?\nWait a minute...");
    Voice_PlayVoice("XD_06_00_F01900", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Why are you trying to run away from\nme?\nI want you to come closer.");
    Message_Who(0);
    Message_MsgDisp("主人公", "But, hey, you're in the middle of\nthe road!\nHey!");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("XD_06_00_F02000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "From now on, thinking at a time like\nthis is prohibited.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What...");
    Voice_PlayVoice("XD_06_00_F02100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Do you understand? Gonna reply?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yes.");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("XD_06_00_F02200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Well then, you're forgiven!\nBe careful after this, Senpai.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Amachi＊＊｝...)");
    }
