section "b15_m2_000"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 0);
    Character_Chara_GS2(2, "M2_??F", 0, 1);
    Voice_PlayVoice("XD_02_00_B00000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Hey.... Having fun?\nLooking and touching.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah... Ah, sorry!\nDo you hate it,\n｛Shiba＊＊｝?");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("XD_02_00_B00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... That's not it.");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("XD_02_00_B00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "I was just thinking what'd happen if\nI did the same thing.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What would happen?");
    Voice_PlayVoice("XD_02_00_B00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Your hair, face... And also...");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("XD_02_00_B00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...... Enough.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("XD_02_00_B00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nSomething might happen just thinking\nabout it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Shiba＊＊｝?)");
    }
