section "b15_m5_004"{
    Background_Bg_GS2("BG_EX101_?_2", 1, #1, 0);
    Character_Chara_GS2(5, "M5_D?F", 0, 1);
    Character_ChFace(0, 0, 0);
    Screen_WipeIn(3);
    Voice_PlayVoice("XD_05_00_E02200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I have something I wanna try.\nCan I do it?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm? Sure.");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 6, 1);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("XD_05_00_E02300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "......");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("XD_05_00_E02400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... I want to get closer to you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Eh...?)");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("XD_05_00_E02500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "So close that when I hold you, I can\nfeel you breathe.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, ｛Chris＊＊｝! S-Stop!");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("XD_05_00_E02600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... What's wrong?");
    Message_Who(0);
    Message_MsgDisp("主人公", "W-What's wrong...");
    Voice_PlayVoice("XD_05_00_E02700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Aren't we doing the same thing?");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("XD_05_00_E02800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "A nice hug....\nBut why are you so flustered?");
    Message_Who(0);
    Message_MsgDisp("主人公", "...\nI don't think that it's the same...");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("XD_05_00_E02900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I'm happy that I saw that face.\nThank you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Chris＊＊｝...)");
    }
