section "b15_m6_000"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Character_Chara_GS2(6, "M6_D?F", 0, 1);
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 2);
    Screen_WipeIn(3);
    Voice_PlayVoice("XD_06_00_F00000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Senpai, are you actually a person\nwho gets lonely easily?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh, why do you ask?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("XD_06_00_F00100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Because you touch me when you get\nthe chance....\nEven though we're together, are you\nthat lonely?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I don't touch you for that reason...");
    Voice_PlayVoice("XD_06_00_F00200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Then why do you do it?");
    Message_Who(0);
    Message_MsgDisp("主人公", "B-Because, well...");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("XD_06_00_F00300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Hmph.\nMaking that face means that you do\nthink that way, generally.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("XD_06_00_F00400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I won't really refuse, so it might\nbe like female bonding, or have the\nfeeling of us being friends...");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 6, 1);
    Voice_PlayVoice("XD_06_00_F00500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Thank gosh!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Amachi＊＊｝...)");
    }
