section "b15_m2_005"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 2);
    Character_Chara_GS2(2, "M2_??F", 0, 1);
    Voice_PlayVoice("XD_02_00_B03800", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "I feel like it's going to turn bad\nsoon.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What is?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("XD_02_00_B03900", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Being alone with you, like this.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Why do you think that?");
    Voice_PlayVoice("XD_02_00_B04000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Because it seems like things won't\nend on a light-hearted note.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝, you mean...");
    Voice_PlayVoice("XD_02_00_B04100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "If something hit the right nerve,\nI'd crumble right away....\nReally.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("XD_02_00_B04200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "If things got that way, I wouldn't\nbe able to hold back anymore....\nI don't feel like holding back.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("XD_02_00_B04300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "There's no way to escape now.\nWhat will you do?");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝... I...");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 6, 2);
    Voice_PlayVoice("XD_02_00_B04400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "I'm still fine. But...");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("XD_02_00_B04500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "All I want you to remember is that\nit doesn't seem like I can wait that\nlong.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Shiba＊＊｝...)");
    }
