section "b15_m6_004"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Character_Chara_GS2(6, "M6_D?F", 0, 1);
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 2);
    Screen_WipeIn(3);
    Voice_PlayVoice("XD_06_00_F03100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "...\nIt's kind of gotten to the point\nwhere anything is fine.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? What has?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("XD_06_00_F03200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "If you're doing it with that\nintention, then I don't think I have\nto restrain myself.");
    Message_Who(0);
    Message_MsgDisp("主人公", "\"That intention\"?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_06_00_F03300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "\"That intention\" is \"that\nintention\".");
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_06_00_F03400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Hey, Senpai.");
    Voice_PlayVoice("XD_06_00_F03500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "You might be used to doing skinship.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("XD_06_00_F03600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "But what about having it done to\nyou?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...");
    Voice_PlayVoice("XD_06_00_F03700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Think about it a little....\nThen you'll be able to understand my\nfeelings a little, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "S-Sorry!\nI was probably a little insensitive!");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("XD_06_00_F03800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Haha, I'm kidding.\nI also like that face you do,\nSenpai～.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ugh, ｛Amachi＊＊｝ is\nmean...)");
    }
