section "b15_m4_003"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 2);
    Character_Chara_GS2(4, "M4_??F", 0, 1);
    Voice_PlayVoice("XD_04_00_D02500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... That's unfair, as expected.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What is?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("XD_04_00_D02600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Looking up at me!");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 2);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_04_00_D02700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "When I get home I'll start thinking\nabout weird things, so don't look at\nme with those eyes.");
    Message_Who(0);
    Message_MsgDisp("主人公", "But even if you tell me to...");
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 2);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_04_00_D02800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Ack! I told you to cut it out!");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("XD_04_00_D02900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... I get it. Lift your chin.\nAnd then...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Like this?");
    Message_CloseMsg();
    Screen_WipeOut(6);
    Character_Chara_GS2(4, "NON");
    Voice_PlayVoice("XD_04_00_D03000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", ".........");
    Character_Chara_GS2(4, "M4_??F", 0, 1);
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 1);
    Screen_WipeIn(6);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝?");
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_04_00_D03200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Why the hell did you close your\neyes?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, sorry. It wasn't on purpose.");
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_04_00_D03300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nIf you do that again, I don't know\nwhat's gonna happen.");
    Message_Who(0);
    Message_MsgDisp("主人公", "\"What's going to happen\"...?");
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_04_00_D03400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "--Don't go stirring things up!\nI really have no idea.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hariya＊＊｝?)");
    }
