section "b15_m1_003"{
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 0, 9);
    Character_Chara_GS2(1, "M1_??F", 0, 1);
    Voice_PlayVoice("", 1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What?");
    Voice_PlayVoice("", 1, "XD_01_00_A02300");
    Message_Who(1);
    Message_MsgDisp("Saeki", "｛主人公｝.\nHey, I'm going to say something\nserious.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Voice_PlayVoice("XD_01_00_A02400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Even though you probably don't have\nthat intention, when you stick close\nto me...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah... yes?");
    Voice_PlayVoice("XD_01_00_A02500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I...\nsometimes think that I may do\nsomething foolish.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sorry, I might have been a little\nreckless...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("XD_01_00_A02600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "No, it's fine.\nBut you see, I'm an adolescent, even\nthough that might sound strange.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, sorry.");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_01_00_A02700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Well, it's not like I really think\nthat.\nPerhaps you wanna, you know, do that\nkinda thing...");
    Message_Who(0);
    Message_MsgDisp("主人公", "That kinda thing?");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_01_00_A02800", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "No, it's nothing.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay.");
    Voice_PlayVoice("XD_01_00_A02900", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I'm leaving now.");
    SoundEffect_PlayStream(3, "SS_DSE_060_000");
    Character_Chara_GS2(1, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(\"That kinda thing\"...)");
    }
