section "b15_m3_003"{
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 0, 9);
    Character_ChFace(0, 4, 1);
    Character_Chara_GS2(3, "M3_??F", 0, 1);
    Voice_PlayVoice("XD_03_00_C02100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Wait!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah, what?");
    Character_ChFace(0, 0, 9);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_03_00_C02200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I'm fine... I've got a solution.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hey, what is this \"solution\"?");
    Voice_PlayVoice("XD_03_00_C02300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "The solution to this skinship\nthing....\nIs it strange to have one?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uhh... A little.");
    Voice_PlayVoice("XD_03_00_C02400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I see...\nHowever, I have to have a logical\nunderstanding of it, or else.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Or else?");
    Voice_PlayVoice("XD_03_00_C02500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "In other words... No, forget it.\nI'm fine now.");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("XD_03_00_C02600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "So, skinship, right?\nDo it without hesitation!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Voice_PlayVoice("XD_03_00_C02700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "What's wrong? I've found a solution.\nGo ahead!");
    Message_Who(0);
    Message_MsgDisp("主人公", "But it's kind of embarrassing,\nsaying that to me...");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_03_00_C02800", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I see... Okay.\nWe'll save it for another time.\nI'll see you later.");
    SoundEffect_PlayStream(3, "SS_DSE_060_000");
    Character_Chara_GS2(3, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hikami＊＊｝ is\nextreme...)");
    }
