section "b15_m6_001"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Character_Chara_GS2(6, "M6_D?F", 0, 1);
    Character_ChFace(0, 0, 10);
    Screen_WipeIn(3);
    Voice_PlayVoice("XD_06_00_F00600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "It's nice that your voice is close.");
    Message_Who(0);
    Message_MsgDisp("主人公", "My voice is close?");
    Voice_PlayVoice("XD_06_00_F00700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Yeah.\nIt means that we've narrowed the\ndistance between us, right?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("XD_06_00_F00800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I didn't think that I'd be able to\nbe have a conversation with Senpai,\nbeing so close to you and all.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("XD_06_00_F00900", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "...\nI actually want to be closer,\nthough.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("XD_06_00_F01000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "So close that it's like your gaze\nonly fixes on me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Amachi＊＊｝...");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("XD_06_00_F01100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Hey, if we did that, I wonder if the\nsound of your voice would be\ndifferent, again?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 6, 1);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("XD_06_00_F01200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... I look forward to it, Senpai.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Amachi＊＊｝...)");
    }
