section "b15_m3_002"{
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 4, 1);
    Character_Chara_GS2(3, "M3_??F", 0, 1);
    Voice_PlayVoice("XD_03_00_C01400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "No more!");
    Message_Who(0);
    Message_MsgDisp("主人公", "!?");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_03_00_C01500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Sorry for saying it so loudly.\nThere is something I want to verify.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay.");
    Voice_PlayVoice("XD_03_00_C01600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "It seems like you quite like\nskinship...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Do you hate it,\n｛Hikami＊＊｝?");
    Voice_PlayVoice("XD_03_00_C01700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "That is not it.\nMy family does this more to people\nwithin the family.\nSo doing this with someone outside\nthe family...");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("XD_03_00_C01800", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Do you do this to anyone?\nSkinship, I mean.");
    Message_Who(0);
    Message_MsgDisp("主人公", "As if.\nI only do it to you,\n｛Hikami＊＊｝.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("XD_03_00_C01900", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Really... really. Haha... Yes!");
    Voice_PlayVoice("XD_03_00_C02000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I've found a solution.\nI will be fine next time.\nI'll see you later!");
    SoundEffect_PlayStream(3, "SS_DSE_060_000");
    Character_Chara_GS2(3, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(What kind of solution...)");
    }
