section "b15_m6_005"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Character_Chara_GS2(6, "M6_D?F", 0, 1);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Screen_WipeIn(3);
    Voice_PlayVoice("XD_06_00_F03900", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Senpai.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes?");
    Message_CloseMsg();
    Screen_WipeOut(6);
    Character_Chara_GS2(6, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "W-What's wrong with you,\n｛Amachi＊＊｝?\nYou suddenly covered your eyes...");
    Voice_PlayVoice("XD_06_00_F04000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "......\nI want it to stay like this for a\nwhile.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yeah.");
    Voice_PlayVoice("XD_06_00_F04100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Senpai, you touch me irresponsibly a\nlot.");
    Voice_PlayVoice("XD_06_00_F04200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "It may not be a big deal to Senpai.");
    Voice_PlayVoice("XD_06_00_F04300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "But it's very true....\nBe more self-controlled.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm sorry, I...");
    Voice_PlayVoice("XD_06_00_F04400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "......");
    Character_Chara_GS2(6, "M6_D?F", 0, 1);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 5);
    Screen_WipeIn(6);
    Voice_PlayVoice("XD_06_00_F04500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I'm just telling you....\nI don't mean that it's unpleasant.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("XD_06_00_F04600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "But...\nSenpai is a woman and I'm not just\nany man.");
    Voice_PlayVoice("XD_06_00_F04700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... I will always be your junior.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("XD_06_00_F04800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Don't forget that. Do you undestand?");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Amachi＊＊｝...)");
    }
