section "b15_m4_002"{
    Background_Bg_GS2("BG_EX100_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(4, "M4_??F", 0, 1);
    Voice_PlayVoice("XD_04_00_D01700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I tried giving my guitar a name.\nYour name.");
    Message_Who(0);
    Message_MsgDisp("主人公", "My name? Why?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("XD_04_00_D01800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I'm seeing if it will change the\nsounds and stuff.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh, is that so? So...?\nHas it changed...?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("XD_04_00_D01900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... You know.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("XD_04_00_D02000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It seems like if I hold it gently,\nthe sounds will be gentle.\nAnd if I am rough with it, the\nsounds will be rough.");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("XD_04_00_D02100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It seems like you understand this is\nbad.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh... What is?");
    Voice_PlayVoice("XD_04_00_D02200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I was thinking too much about it.");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 2);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_04_00_D02300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "When I hold it like this, I get like\nthat...");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(4, 3, (#1));
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("XD_04_00_D02400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It was a big mistake to give it a\nname.\n*Sigh*...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hariya＊＊｝?)");
    }
