section "b15_m1_001"{
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(3);
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 1);
    Character_Chara_GS2(1, "M1_??F", 0, 1);
    Voice_PlayVoice("", 1, "XD_01_00_A00700");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Hey, ｛主人公｝...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hm?");
    Voice_PlayVoice("XD_01_00_A00800", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Hey...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yeah?");
    Voice_PlayVoice("XD_01_00_A00900", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Umm, you always touch me, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sorry. Do you hate it?");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("XD_01_00_A01000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I don't hate it, but...\nIt seems like I might misunderstand.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Misunderstand?");
    Character_ChFace(0, 4, 1);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_01_00_A01100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Things like, \"Can I do that, too?\"");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh, meaning...");
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_01_00_A01200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I'm lying! It was a joke! Haha!\nYou're such an idiot!");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("XD_01_00_A01300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ah～ Yes!\nNow then, I'll see you later!");
    SoundEffect_PlayStream(3, "SS_DSE_060_000");
    Character_Chara_GS2(1, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(What the...)");
    }
