section "b30_m7_000"{
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(7, 2, (#1));
    Character_ChFace(0, 3, 2);
    Character_Chara_GS2(7, "M7_06F", 0);
    Background_Bg_GS2("BG_EX150_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("B3007000_G00000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "...\nIndeed, that is a way of thinking,\nas well.\nThen, for example-- Oops!");
    Character_Chara_GS2(7, "NON");
    SoundEffect_PlayStream(3, "SS_T_00_224_M00");
    Screen_StartShakePlane(0, 32, 32, 0, 32);
    System_Wait(124);
    Message_Who(0);
    Message_MsgDisp("主人公", "Watch out!\nAre you all right,\n｛Wakaouji＊＊｝?");
    Character_Chara_GS2(7, "M7_06F", 0);
    Character_BlinkStart(7, 2, (#1));
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("B3007000_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Thank you. I tripped.\nFor some reason, my feet are dubious\nwhen I walk while speaking.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha.\nAre you fairly careless,\n｛Wakaouji＊＊｝?");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(7, 2, (#1));
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("B3007000_G00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Oh, even you are like that.");
    Message_Who(0);
    Message_MsgDisp("主人公", "How?");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(7, 2, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("B3007000_G00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Hey, in the chemistry room the other\nday...\nOh.");
    Message_Who(0);
    Message_MsgDisp("主人公", "!! Oh, umm...");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(7, 2, (#1));
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("B3007000_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Hmm～...\nWell then, we are two careless\npeople.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yes...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddPl1Param(316, 1);
    }
