section "b30_m3_000"{
    Character_Chara_GS2(3, "M3_??F", 0);
    Character_ChFace(0, 0, 3);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Background_Bg_GS2("BG_EX150_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("B3003000_C00000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "...\nThis may sound strange, but you are\na mysterious person.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(3, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B3003000_C00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Your atmosphere and personality...\nIs it something you've always had\nsince you were born?");
    Message_Who(0);
    Message_MsgDisp("主人公", "...\nHmm, I've never thought about it.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(3, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B3003000_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I see.\nThat answer is very becoming of you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What's wrong, ｛Hikami＊＊｝?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("B3003000_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I sometimes think that perhaps the\nreason why we can have a\nconversation like this is because of\nguilty feelings.");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(3, 2, (#1));
    Voice_PlayVoice("B3003000_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I mean...\nbecause of the incident at the\nstairs.\nBut I've noticed something recently.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("B3003000_C00500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "That incident was no more than an\nopportunity.\nAn opportunity to get to know you\nbetter.");
    Message_Who(0);
    Message_MsgDisp("主人公", ".........");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(3, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B3003000_C00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "...\nI am sorry, I was talking to myself.\nWhat I talked about was strange,\nwasn't it?");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, not at all...");
    Character_ChFace(0, 0, 3);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B3003000_C00700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "...\nAnyway, I am glad that I met you.\nThat is all I have to say.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hikami＊＊｝...?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddPl1Param(316, 1);
    }
