section "b30_m8_000"{
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 4);
    Character_Chara_GS2(8, "M8_??F", 0);
    Background_Bg_GS2("BG_EX150_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("B3008000_H00000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "......");
    Message_Who(0);
    Message_MsgDisp("主人公", "How pretty...");
    Message_Who(8);
    Message_MsgDisp("Masaki", "......");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, a fish just jumped!\nDid you see it?");
    Message_Who(8);
    Message_MsgDisp("Masaki", "......");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? Are you not listening?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, ｛Masaki＊＊｝?");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("B3008000_H00300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... Whoa!");
    Character_Chara_GS2(8, "NON");
    SoundEffect_PlayStream(3, "SS_T_00_224_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Masaki＊＊｝!");
    Voice_PlayVoice("B3008000_H00400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Ou...ch～...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Are you okay?");
    Character_Chara_GS2(8, "M8_??F", 0);
    Character_ChFace(0, 7, 0);
    Character_ChFace(0, 2, 2);
    Voice_PlayVoice("B3008000_H00500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah... I am.");
    Character_ChFace(0, 4, 1);
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("B3008000_H00600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "... What's the matter?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("B3008000_H00700", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Ah～... I just...\nthought it was pretty and\nfascinating...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Right!\nThe reflection of the setting sun on\nthe calm sea is glistening...");
    Character_ChFace(0, 0, 6);
    Character_BlinkStart(8, 2, (#1));
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("B3008000_H00800", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... I was talking about your lips...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Voice_PlayVoice("B3008000_H00900", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I wonder what would happen if things\nwere reversed.\nMine hitting yours...");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(8, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("B3008000_H01000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "...\nCrap, it doesn't seem like I'll be\nable to stop thinking about it if I\nthink any more.\nStop, stop.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Masaki＊＊｝...?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddPl1Param(316, 1);
    }
