section "b30_m6_000"{
    Character_Chara_GS2(6, "M6_??F", 0);
    Background_Bg_GS2("BG_EX150_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("", 6, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("B3006000_F00000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... It's nothing.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Really?");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("", 6, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "............ ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... What?");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("B3006000_F00200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "??? What's wrong?");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 5);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("B3006000_F00300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Wah! Umm...\nCan you not come near me?");
    Message_Who(0);
    Message_MsgDisp("主人公", "What...");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("B3006000_F00400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I remember that thing at the\nbeginning.");
    Message_Who(0);
    Message_MsgDisp("主人公", "The thing... at the beginning?");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(6, 3, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("B3006000_F00500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "The sensation and the closeness of\nyour face......\nWait a second.");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("B3006000_F00600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Senpai... Do you not know...?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yeah.\nWhat are you talking about?");
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("B3006000_F00700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "*Sigh*...\nIt seems you really don't\nunderstand...\nDo you want me to remind you...?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh, I'll decline...");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 4);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("B3006000_F00800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Okay.\nBut in the end, I'll try not to talk\nabout it.");
    Voice_PlayVoice("B3006000_F00900", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Remember that, Senpai!");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Is ｛Amachi＊＊｝ angry?\nHmm, I wonder if I did something bad\nto him.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddPl1Param(316, 1);
    }
