section "b50_m7_010"{
    Background_Bg_GS2("BG_EX150_CO_1", #1, #1, 0);
    Character_Chara_GS2(7, "M7_06F", 0);
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, I...");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 6, 1);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("", 7, "FD_07_010_00000");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝ is in love\nnow.\nCorrect?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm... Yes.");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("FD_07_010_00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "That kind of face.\nIt's not necessary to be concerned\nwith Sensei.");
    Voice_PlayVoice("FD_07_010_00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Sensei has not fallen in love.\nI feel awkward at my mature age.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("FD_07_010_00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Therefore, you are the teacher, the\nSenpai of love.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm ｛Wakaouji＊＊｝'s Senpai?");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 6, 1);
    Voice_PlayVoice("FD_07_010_00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It looks that way.\nA wonderful future surely awaits\nyou.\nOf course, it is hard on me.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("FD_07_010_00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Please, teach Sensei such a thing,\nsometimes.\nIt may be possible to be worried at\nthe same time.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.");
    Voice_PlayVoice("FD_07_010_00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Okay... Now, let's go home.\nThe wind has risen.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝...\nThank you.)");
    }
