section "b50_m1_010"{
    Background_Bg_GS2("BG_EX150_CO_1", #1, #1, 0);
    Character_Chara_GS2(1, "M1_??F", 0);
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝, I--");
    Voice_PlayVoice("FD_01_010_00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Stop, I get it...\nYou've found someone you like.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yes.");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 6, 1);
    Voice_PlayVoice("FD_01_010_00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I see.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("FD_01_010_00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "That was easy.\nYou were trying to make me feel\nbetter by inviting me here, right?\nI'm confused, too.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sorry...");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("FD_01_010_00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Don't apologize. I should.\nI've been thinking about nothing but\nSangosho, so I didn't realize these\nthings.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 6, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("FD_01_010_00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Let's stop this. It's not like us.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Right.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("FD_01_010_00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It's so you can be a good girl.\nIf you've got any problems,\nHanegasaki's prince will counsel\nyou...\nokay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Thank you,\n｛Saeki＊＊｝...)");
    }
