section "b50_m5_010"{
    Background_Bg_GS2("BG_EX150_CO_1", #1, #1, 0);
    Character_Chara_GS2(5, "M5_??F", 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝. I actually...");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("FD_05_010_00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Hmm, got it.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("FD_05_010_00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "You don't have to worry.\nSo your eyes are looking at someone\nelse.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("FD_05_010_00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It's nothing to worry about.\nAnyway...");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("FD_05_010_00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "If you have something you're worried\nabout, tell me right away, okay?");
    Voice_PlayVoice("FD_05_010_00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I might be able to give you some\nadvice.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("FD_05_010_00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah, right. Let's make a contract.\nI'll counsel you about love.\nIt's for free, of course.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝...");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("FD_05_010_00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Do your best, okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Okay.\nThank you, ｛Chris＊＊｝.");
    }
