section "b60_m8_000"{
    Message_Who(0);
    Message_MsgDisp("主人公", "Thank you for inviting me.");
    Character_ChFace(1, 0, 0);
    Voice_PlayVoice("FD_08_200_00000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I owed you. I'll drive you home.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_Chara_GS2(8, "M8_D?F", 0);
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Well then, Masaki-senpai.");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("", 8, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes?");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("FD_08_200_00200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... I apologize for earlier.\nI'm sorry.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? What for?");
    Voice_PlayVoice("FD_08_200_00300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "That maybe you and I...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Masaki-senpai?");
    Character_ChFace(0, 0, 6);
    Voice_PlayVoice("FD_08_200_00400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... I'll contact you, again. Cya.");
    Character_Chara_GS2(8, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I wonder what Masaki-senpai was\ngoing to say...)");
    Parameter_InCh1Param(8, 558, 1);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
