section "b60_m2_000"{
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks for coming along with me\ntoday.");
    Character_ChFace(1, 0, 0);
    Voice_PlayVoice("FD_02_200_00000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Yeah. I'll walk you home.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_Chara_GS2(2, "M2_D?F", 0);
    Character_ChFace(0, 0, 0);
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks for walking me home.");
    Message_Who(2);
    Message_MsgDisp("Shiba", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "What's the matter,\n｛Shiba＊＊｝?");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 6, 2);
    Voice_PlayVoice("FD_02_200_00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Can this go on forever?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("FD_02_200_00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Just seeing you worry all the time\nis enough to...");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("FD_02_200_00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... My bad.\nI wonder what's wrong with me.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 6, 2);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("FD_02_200_00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Later.");
    Character_Chara_GS2(2, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Shiba＊＊｝...?)");
    Parameter_InCh1Param(2, 558, 1);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
