section "b60_m7_000"{
    Message_Who(0);
    Message_MsgDisp("主人公", "Thank you for today.");
    Character_ChFace(1, 0, 10);
    Character_ChFace(1, 6, 1);
    Voice_PlayVoice("FD_07_200_00000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "You are welcome. Now, let's return.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_Chara_GS2(7, "M7_06F", 0);
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Thank you for walking me home.");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("FD_07_200_00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Yeah...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, is something wrong?");
    Voice_PlayVoice("", 7, "FD_07_200_00200");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Is it good to stay as we are,\n｛主人公｝?");
    Message_Who(0);
    Message_MsgDisp("主人公", "As we are...");
    Voice_PlayVoice("FD_07_200_00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Maybe Wakaouji-sensei is a mean\nperson in reality.\nDo you think so?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Nothing like that!\n｛Wakaouji＊＊｝ isn't mean!");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 6, 1);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("FD_07_200_00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "... Thank you. I'm going home.");
    Character_Chara_GS2(7, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I wonder what's wrong with\n｛Wakaouji＊＊｝?)");
    Parameter_InCh1Param(7, 558, 1);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
