section "b60_m1_000"{
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks for coming along with me\ntoday.");
    Character_ChFace(1, 0, 6);
    Character_ChFace(1, 4, 0);
    Voice_PlayVoice("FD_01_200_00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "You're welcome. So, let's go.\nI'll walk you home.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_Chara_GS2(1, "M1_D?F", 0);
    Character_ChFace(0, 0, 11);
    Character_ChFace(1, 4, 0);
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝, are you okay?\nYou've been quiet the entire time...");
    Voice_PlayVoice("FD_01_200_00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ah, yeah... It's nothing.\nSo we're already at your place, huh.\nLater.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah. Thank you.\nI'll see you later...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("FD_01_200_00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Hey!\nIf there's another place that you\nwanna go to, just tell me, okay?\nLater.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks. And yeah, I will.\nI'll see you later...");
    Voice_PlayVoice("FD_01_200_00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "By the way, I can't go anywhere on\nWednesdays and Fridays.\nYou know why, right...? Later.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝...\nAre you really okay?");
    Character_ChFace(0, 0, 9);
    Character_ChFace(1, 4, 1);
    Voice_PlayVoice("FD_01_200_00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I'm fine. Probably...\nAnyway, I'll see you later.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Saeki＊＊｝...)");
    Parameter_InCh1Param(1, 558, 1);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
