section "a01_pl_001"{
    Music_PlayBGM(0, "MN_X_03_A00_D00", 127, 40);
    Background_Bg_GS2("BG_PR000_LI_1", #1, #1, 0);
    Screen_WipeIn(3);
    Voice_PlayVoice("A0100100_A00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Little Boy", "Why are you crying?");
    Message_Who(0);
    Message_MsgDisp("Little Girl", "......");
    Voice_PlayVoice("A0100100_A00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Little Boy", "Why aren't you saying anything?");
    Message_Who(0);
    Message_MsgDisp("Little Girl", "......");
    Voice_PlayVoice("A0100100_A00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Little Boy", "Hey, are you a mermaid?");
    Message_Who(0);
    Message_MsgDisp("Little Girl", "A mermaid?");
    Voice_PlayVoice("A0100100_A00300", #1, "");
    Message_Who(0);
    Message_MsgDisp("Little Boy", "So you can talk. What's wrong?");
    Message_Who(0);
    Message_MsgDisp("Little Girl", "I can't find my mom or dad...");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_CloseMsg();
    Environment_StopME(1, 40);
    Background_Bg_GS2("BG_PR010_LI_1", #1, #1, 1);
    Screen_WipeIn(2);
    Voice_PlayVoice("A0100100_P00400", #1, "");
    Message_Who(0);
    Message_MsgDisp("Grandfather", "And so, the young man and the\nbeautiful young girl, who had met at\nthe shore, fell in love.");
    Voice_PlayVoice("A0100100_P00500", #1, "");
    Message_Who(0);
    Message_MsgDisp("Grandfather", "Although the young girl couldn't\nspeak, the young man didn't mind.");
    Voice_PlayVoice("A0100100_P00600", #1, "");
    Message_Who(0);
    Message_MsgDisp("Grandfather", "Her eyes, which were like the calm\nocean, spoke more than words.");
    Message_Who(0);
    Message_MsgDisp("Little Girl", "Why couldn't she talk?");
    Voice_PlayVoice("A0100100_A00700", #1, "");
    Message_Who(0);
    Message_MsgDisp("Little Boy", "The young girl is a mermaid.\nWhen she's in her human form, she\ncan't talk.");
    Voice_PlayVoice("A0100100_P00800", #1, "");
    Message_Who(0);
    Message_MsgDisp("Grandfather", "Hey, don't give away the story.");
    Voice_PlayVoice("A0100100_A00900", #1, "");
    Message_Who(0);
    Message_MsgDisp("Little Boy", "Sorry.");
    Message_CloseMsg();
    Background_Check_BGScroll();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_PR020_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("A0100100_P01000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Grandfather", "The heartless villagers had learned\nof this, so the mermaid had to\nreturn to the ocean.");
    Voice_PlayVoice("A0100100_P01100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Grandfather", "Instead of saying good bye, the two\nkissed.\nThey believed that they would meet\nat the shore again, one day.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_PR030_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("A0100100_P01200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Grandfather", "Ever since parting with the mermaid,\nthe young man spent every day gazing\nout at the ocean.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_PR040_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("A0100100_P01300", #1, "");
    Message_Who(0);
    Message_MsgDisp("Grandfather", "Then at last, on a moonlit night,\nthe young man sailed out into the\nocean, full of determination.");
    Voice_PlayVoice("A0100100_P01400", #1, "");
    Message_Who(0);
    Message_MsgDisp("Grandfather", "The young man never returned.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_PR050_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("A0100100_P01500", #1, "");
    Message_Who(0);
    Message_MsgDisp("Grandfather", "The villagers pitied the two, and\nbuilt a lighthouse, so that it would\nshine over the two on dark nights.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Environment_StopME(1, 40);
    System_Wait(60);
    Background_Bg_GS2("BG_ED000_SP_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("Little Girl", "They could meet again though, right?");
    Voice_PlayVoice("A0100100_A01600", #1, "");
    Message_Who(0);
    Message_MsgDisp("Little Boy", "I don't know.");
    Message_Who(0);
    Message_MsgDisp("Little Girl", "That's a shame.");
    Voice_PlayVoice("A0100100_A01700", #1, "");
    Message_Who(0);
    Message_MsgDisp("Little Boy", "That's the kind of story it is.");
    Message_Who(0);
    Message_MsgDisp("Little Girl", "......");
    Voice_PlayVoice("A0100100_A01800", #1, "");
    Message_Who(0);
    Message_MsgDisp("Little Boy", "But I would surely find her.");
    Message_Who(0);
    Message_MsgDisp("Little Girl", "Really?");
    Voice_PlayVoice("A0100100_A01900", #1, "");
    Message_Who(0);
    Message_MsgDisp("Little Boy", "Yeah. So lift your head up.");
    Message_Who(0);
    Message_MsgDisp("Little Girl", "?");
    Message_CloseMsg();
    Screen_WipeOut(3);
    System_Wait(120);
    SoundEffect_PlayStream(3, "SS_T_00_042_M00");
    Still_Event("EV_01_30", #1, 0, 0);
    Screen_WipeIn(3);
    Still_Event("EV_01_24", #1, 1, 180);
    Message_Who(1);
    Voice_PlayVoice("A0100100_A02000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Little Boy", "It's a kiss.\nIt's so that we can meet at this\nbeach, again.");
    Message_CloseMsg();
    Environment_FadeME(0, 127, 127);
    Screen_WipeOut(3);
    Music_StopBGM(0, 40);
    Environment_StopME(0, 40);
    }
