section "a02_m1_001"{
    Effect_OpenParticle(0);
    Background_Bg_GS2("BG_SC110_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(This is the school I'll be\nattending, \"Hanegasaki Academy\".)");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Huh?");
    Message_Who(0);
    Message_MsgDisp("主人公", "(That person...\nIs that the same person from this\nmorning...?)");
    Character_ChFace(0, 0, 11);
    Character_Chara_GS2(1, "M1_01F", 0);
    Environment_PauseME(0);
    Music_PlayBGM(0, "MN_C_01_000_D01", 127, 40);
    Voice_PlayVoice("A0201001_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("？？？", "Ack......");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah!! It is you!\nSo you're a high school student...");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("A0201001_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("？？？", "Come here for a second!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh!?");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(1, "NON");
    Effect_CloseParticle();
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 0, 2);
    Character_Chara_GS2(1, "M1_01F", 0);
    Background_Bg_GS2("BG_SC400_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("A0201001_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("？？？", "So you're a first year student,\nhuh...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah. I'm ｛主人公姓名｝.\nNice to meet you!");
    Character_BlinkStart(1, 3, (#1));
    Voice_PlayVoice("A0201001_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("？？？", "I'm Saeki Teru. First year.\nDon't let my name give you the wrong\nimpression.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay.\nUmm, thanks for helping me this\nmorning.\nI just moved here, so--");
    Character_BlinkStart(1, 0, (#1));
    Voice_PlayVoice("A0201001_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Anyway... about this morning.\nDon't talk about it at school, okay?\nDo I make myself clear?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... This morning?");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("A0201001_A00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "You know...\nThe fact that I work at a store.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay. I won't tell anyone, but...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("A0201001_A00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Good. That's all. Later.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(1, "NON");
    Environment_ResumeME(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Saeki＊＊｝, huh...\nSo he's in the same grade as me...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Even though he's in the same grade,\nwhy does he act so self-important?)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    }
