section "a02_m7_000"{
    Environment_PlayME(1, "SN_P_00_026_000", 127, 0);
    Background_Bg_GS2("BG_SC301_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Speaking of which, I wonder what\nkind of person my homeroom teacher\nis?)");
    SoundEffect_PlayStream(2, "SS_T_00_093_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, they're here!!)");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(7, "M7_01F", 0);
    Music_PlayBGM(0, "MN_C_07_000_D01", 127, 40);
    Voice_PlayVoice("A0207000_G00000", #1, "");
    Message_Who(7);
    Message_MsgDisp("？？？", "Nice to meet you.\nI am your homeroom teacher, Wakaouji\nTakafumi.");
    Voice_PlayVoice("A0207000_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I teach Chemistry.\nI look forward to this year\ntogether.");
    Environment_ResumeME(0);
    Voice_PlayVoice("A0207000_W00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Hey, isn't he kinda cool?");
    Voice_PlayVoice("A0207000_W00300", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student B", "People call him \"Waka-sama\"!\nIt's rumored that he's a genius\nscientist!");
    Voice_PlayVoice("A0207000_W00400", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "No way!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(...\nHe'll probably be an amazing\nteacher.)");
    Environment_PauseME(0);
    Voice_PlayVoice("A0207000_G00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Everyone, please be quiet.\nNow then... Are there any questions?");
    Voice_PlayVoice("A0207000_W00600", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Yes, I do! Are you seeing anyone?");
    SoundEffect_PlayStream(2, "SE_NS_AL_910_003000");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("A0207000_G00700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Seeing...\nDo you mean if I am dating a woman?");
    Voice_PlayVoice("A0207000_W00800", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Yes!");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("A0207000_G00900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "A woman that I am dating... Hmm...\nThis is a tough question.");
    Voice_PlayVoice("A0207000_W01000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Huh?");
    Character_BlinkStart(7, 2, (#1));
    Voice_PlayVoice("A0207000_G01100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "There was a time when I was often\nasked out by a woman, so we often\nwent out together.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("A0207000_G01200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Then she stopped calling.\nIt will be three years since then\nthis Spring.\nDoes that answer your question?");
    Voice_PlayVoice("A0207000_W01300", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Ahh, u-uhh...");
    SoundEffect_StopStream(2, 40);
    SoundEffect_PlayStream(2, "SE_NS_AL_910_003000");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Is he a s-serious teacher...?)");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Voice_PlayVoice("A0207000_G01400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Now then, I will return to the\nstaffroom.");
    Voice_PlayVoice("A0207000_G01500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Please fill out the\nself-introduction sheet.\nI will take my leave now.");
    Music_StopBGM(0, 40);
    SoundEffect_StopStream(2, 40);
    Character_Chara_GS2(7, "NON");
    Environment_ResumeME(0);
    SoundEffect_PlayStream(2, "SS_T_00_093_M00");
    Environment_ResumeME(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(... Huh?\nA self-introduction sheet...?)");
    SoundEffect_PlayStream(2, "SS_T_00_093_M00");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 5);
    Character_Chara_GS2(7, "M7_01F", 0);
    Voice_PlayVoice("A0207000_G01600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I forgot to hand out the sheets.");
    SoundEffect_PlayStream(2, "SE_NS_AL_910_003000");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Will things be okay with this\nteacher...?)");
    Message_CloseMsg();
    SoundEffect_StopStream(2, 40);
    Environment_StopME(1, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_InCh1Param(7, 514, 1);
    Parameter_AddCh1Param(7, 86, 1);
    }
