section "a02_g1_400"{
    Background_Bg_GS2("BG_SC212_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(*Sigh*... That was long...\nI'm going to yawn.)");
    Voice_PlayVoice("A0210001_J00000", #1, "");
    Message_Who(10);
    Message_MsgDisp("？？？", "Hah. What a good yawn.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh!");
    Environment_PauseME(0);
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(10, "G1_01F", 0);
    Music_PlayBGM(0, "MN_C_10_000_D01", 127, 40);
    Voice_PlayVoice("A0210001_J00100", #1, "");
    Message_Who(10);
    Message_MsgDisp("？？？", "You don't have to open your mouth\nthat widely.");
    Voice_PlayVoice("A0210001_J00200", #1, "");
    Message_Who(10);
    Message_MsgDisp("？？？", "I'm Toudou Tatsuko. And you?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah... I'm ｛主人公姓名｝.\nNice to meet you.");
    Character_BlinkStart(10, 3, (#1));
    Voice_PlayVoice("A0210001_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Nice to meet you too.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hey, ｛Toudou＊＊｝.\nDo you perhaps know\n｛Saeki＊＊｝?");
    Character_BlinkStart(10, 0, (#1));
    Voice_PlayVoice("A0210001_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Yeah, I do.");
    Character_BlinkStart(10, 2, (#1));
    Voice_PlayVoice("A0210001_J00500", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Accomplished, gifted in both\nintelligence and looks...\nHe stands out.");
    Character_BlinkStart(10, 3, (#1));
    Voice_PlayVoice("A0210001_J00600", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "While we're talking about him...\nThere's a rumor going around that he\nsneaks around at night, in black\nclothes.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh? Really?");
    Character_BlinkStart(10, 0, (#1));
    Voice_PlayVoice("A0210001_J00700", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... It's just a rumor.\nIt's up to you whether you believe\nit or not.");
    Voice_PlayVoice("A0210001_J00800", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I don't believe in anything I don't\nsee, though.");
    Message_Who(0);
    Message_MsgDisp("主人公", "......");
    Voice_PlayVoice("A0210001_J00900", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... Now, then. I should go...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Where?");
    Voice_PlayVoice("A0210001_J01000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Anywhere except the classroom.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(10, 2, (#1));
    Voice_PlayVoice("A0210001_J01100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I mean, we had to listen to that\nlong, incomprehensible and pointless\nspeech, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "E... Ehh!? You think so?");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(10, 0, (#1));
    Voice_PlayVoice("A0210001_J01200", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Didn't you do that massive yawn\nbecause you were bored, too?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ugh...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("A0210001_J01300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... Hah, I'm kidding.\nYou'd better listen to what they're\nsaying.");
    Character_BlinkStart(10, 3, (#1));
    Voice_PlayVoice("A0210001_J01400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Later.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(10, "NON");
    Environment_ResumeME(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(She left... What a cool person...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_InCh1Param(10, 514, 1);
    Parameter_AddCh1Param(10, 86, 1);
    }
