section "a02_m4_300"{
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's finally my first day at\nwork...\nUgh, I'm nervous...)");
    Environment_PauseME(0);
    Character_ChFace(0, 0, 8);
    Character_Chara_GS2(4, "M4_13F", 0);
    Music_PlayBGM(0, "MN_C_04_000_D01", 127, 40);
    Voice_PlayVoice("A0204300_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "Hey, you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Voice_PlayVoice("A0204300_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "So you're the newbie?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yes! I'm ｛主人公姓名｝.\nI look forward to working with you!");
    Character_BlinkStart(4, 2, (#1));
    Voice_PlayVoice("A0204300_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "...\nAre you working here because you\nknow a lot about instruments?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uhh... Umm...");
    Character_BlinkStart(4, 3, (#1));
    Voice_PlayVoice("A0204300_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "... *Sigh*...\nSo you're an amateur...\nI can tell that this is gonna be\nhell...");
    Message_Who(0);
    Message_MsgDisp("主人公", "I-I'm still an amateur, but I will\ndo my best!\nPlease treat me well, Senpai!");
    Character_BlinkStart(4, 2, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("A0204300_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "... What did you just say?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Pardon?");
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("A0204300_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "...\nYou called me \"Senpai\", didn't you?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yes...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("A0204300_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "Awesome!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh!");
    Character_BlinkStart(4, 3, (#1));
    Voice_PlayVoice("A0204300_D00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "I'll learn to depend on you!\nI'll teach you well!");
    Character_BlinkStart(4, 0, (#1));
    Voice_PlayVoice("A0204300_D00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "Call me Harry!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Harry...?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("A0204300_D00900", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "I'm the future star from Hanegasaki\nAcademy, Hariya!\n... Kounoshin.");
    Character_BlinkStart(4, 3, (#1));
    Voice_PlayVoice("A0204300_D01000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "So call me Harry! You got it?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yes!");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(4, 0, (#1));
    Voice_PlayVoice("A0204300_D01100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Alright!\nI'll teach you the basics of\nguitars.\nFollow me!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(4, "NON");
    Environment_ResumeME(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(So ｛Hariya＊＊｝ goes to\nthe same school as me...\nBut he said \"Harry\"...)");
    Voice_PlayVoice("A0204300_D01200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "You're slow!!\nWhat are you waiting for?");
    Message_Who(0);
    Message_MsgDisp("主人公", "C-Coming～!");
    Parameter_InCh1Param(4, 514, 1);
    Parameter_AddCh1Param(4, 86, 1);
    }
