section "a02_m8_300"{
    if (Parameter_GetPl1Param(312) != 8){
        Message_Who(0);
        Message_MsgDisp("主人公", "(My first day at work is unnerving.)");
        Voice_PlayVoice("A0208300_H00000", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Welcome. What are you looking for?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Environment_PauseME(0);
        Still_Event("");
        Screen_WipeIn(2);
        Still_Event("EV_08_01", #1, 0, 60);
        Music_PlayBGM(0, "MN_C_08_000_D01", 127, 40);
        Voice_PlayVoice("A0208300_H00100", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "If you were to tell me your budget,\nI'd be able to make a bouquet to fit\nthat budget.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, umm...");
        Still_Approach(8, 210, 0, 0, 1, 1);
        Voice_PlayVoice("A0208300_H00200", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "If it seems like your budget isn't\nenough, we'll give you a discount.");
        Still_ApproachEnd();
        Message_Who(0);
        Message_MsgDisp("主人公", "T-Thank you very much...\nNo, wait, you're wrong!");
        Still_StillFace(0, 0, 1);
        Voice_PlayVoice("A0208300_H00300", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Eh? I'm... wrong?");
        Voice_PlayVoice("A0208300_Q00400", #1, "");
        Message_Who(17);
        Message_Who(17);
        Message_MsgDisp("？？？", "Masaki-kun.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Still_Event("");
        Character_ChFace(0, 0, 11);
        Character_Chara_GS2(8, "M8_01F", 0);
        Character_ChFace(1, 0, 0);
        Character_Chara_GS2(17, "G5_01F", 0, 0, 1);
        Background_Bg_GS2("BG_AR500_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("A0208300_H00500", #1, "");
        Message_WindowPosition(0);
        Message_Who(8);
        Message_MsgDisp("Masaki", "Arisawa. What is it?");
        Character_ChFace(1, 0, 8);
        Voice_PlayVoice("A0208300_Q00600", #1, "");
        Message_WindowPosition(1);
        Message_Who(17);
        Message_MsgDisp("Arisawa", "Were you even listening to what the\nmanager was saying earlier?\nShe isn't a customer, she's the\nnew...");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("A0208300_H00700", #1, "");
        Message_WindowPosition(0);
        Message_Who(8);
        Message_MsgDisp("Masaki", "... Ah, ah, ah!\nThey said that there was a new\nperson coming in today!");
        Character_ChFace(1, 2, 2);
        Character_BlinkStart(8, 2, (#1));
        Voice_PlayVoice("A0208300_Q00800", #1, "");
        Message_WindowPosition(1);
        Message_Who(17);
        Message_MsgDisp("Arisawa", "Geez, what a helpless person.\nI'm sorry, he wasn't attentive\nenough to that message.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, it's not that big of a deal...\nAh, I'm ｛主人公姓名｝.");
        Character_ChFace(1, 0, 10);
        Voice_PlayVoice("A0208300_Q00900", #1, "");
        Message_Who(17);
        Message_MsgDisp("Arisawa", "I am Arisawa Shiho.\nI look forward to working with you\nfrom now on.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes, I look forward to working with\nyou!");
        Voice_PlayVoice("A0208300_Q01000", #1, "");
        Message_Who(17);
        Message_MsgDisp("Arisawa", "In a moment Masaki-kun will tell you\nabout the job, even though I think\nhe's a bit undependable.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("A0208300_H01100", #1, "");
        Message_WindowPosition(0);
        Message_Who(8);
        Message_MsgDisp("Masaki", "Is that way of introducing someone\neven allowed?");
        Character_ChFace(1, 0, 0);
        Voice_PlayVoice("A0208300_Q01200", #1, "");
        Message_WindowPosition(1);
        Message_Who(17);
        Message_MsgDisp("Arisawa", "Ah, a customer.\nWell then, I will see you later.");
        Character_Chara_GS2(17, "NON");
        System_Wait(30);
        Character_ChFace(0, 0, 0);
        Character_BlinkStart(8, 2, (#1));
        Voice_PlayVoice("A0208300_H01300", #1, "");
        Message_WindowPosition(0);
        Message_Who(8);
        Message_MsgDisp("Masaki", "...\nI am in charge of taking care of\nyou, Masaki Motoharu...");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Umm... Is there something...?");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("A0208300_H01400", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Ah, sorry.\nYour uniform brings back memories.\nI am a graduate from Hanegasaki\nAcademy.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so!?");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("A0208300_H01500", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "We just missed each other.\nAh, well I'll leave that story for\nanother day.");
        Voice_PlayVoice("A0208300_H01600", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Working at a flower shop isn't easy,\njust remember that.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay!\nI look forward to working with you!");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("A0208300_H01700", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Oh, that's a good response.\nI expect for you to work well, so do\nyour best.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(8, "NON");
        Environment_ResumeME(0);
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Masaki＊＊｝...\nHe seems like a dependable person.)");
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "(My first day at work is unnerving.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It can't be helped that my heart\nwas pounding at the entrance...\nOkay, here I go!)");
        SoundEffect_PlayStream(3, "SS_T_00_007_M00");
        Screen_StartShakePlane(0, 32, 32, 0, 16);
        System_Wait(92);
        Voice_PlayVoice("A0208300_H01800", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Whoa!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Kyaa!");
        Still_Event("");
        Screen_WipeIn(2);
        Still_Event("EV_08_02", #1, 0, 60);
        Music_PlayBGM(0, "MN_C_08_000_D01", 127, 40);
        Voice_PlayVoice("A0208300_H01900", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Ouch...\nI didn't expect for someone to be\nthere...");
        Message_Who(0);
        Message_MsgDisp("主人公", "I-I'm sorry!\nIt's my fault, I was just standing\nhere...");
        Voice_PlayVoice("A0208300_H02000", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Ah, no. Same goes for me.\nAre you okay, no injuries or\nanything?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I am fine.");
        Still_Approach(8, 211, 0, 0, 1, 1);
        Voice_PlayVoice("A0208300_H02100", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "That's a relief then....\nAh crap, if I don't hurry and pick\nthese up and Arisawa sees me...");
        Still_ApproachEnd();
        Message_CloseMsg();
        Background_Bg_GS2("BG_AR500_?_0", 1, #1, 0);
        Still_Event("");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(8, "M8_01F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, I will help you pick the flowers\nup!");
        Voice_PlayVoice("A0208300_H02200", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Really? That would help...... Huh?");
        Message_Who(0);
        Message_MsgDisp("主人公", "W-What is it...");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(8, 2, (#1));
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("A0208300_H02300", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Ah, no....\nI'm just thinking that I've met you\nsomewhere before...");
        Voice_PlayVoice("A0208300_H02400", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Umm.........");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("A0208300_Q02500", #1, "");
        Message_Who(17);
        Message_Who(17);
        Message_MsgDisp("？？？", "Masaki-kun.");
        Character_ChFace(1, 0, 8);
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(8, 2, (#1));
        Character_Chara_GS2(17, "G5_01F", 0, 0, 1);
        Voice_PlayVoice("A0208300_H02600", #1, "");
        Message_WindowPosition(0);
        Message_Who(8);
        Message_MsgDisp("Masaki", "Ack!!! Arisawa!!");
        Character_BlinkStart(8, 2, (#1));
        Voice_PlayVoice("A0208300_Q02700", #1, "");
        Message_WindowPosition(1);
        Message_Who(17);
        Message_MsgDisp("Arisawa", "...\nThe way you say that is terrible.\nWhat happened?\nI mean this disastrous scene.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("A0208300_H02800", #1, "");
        Message_WindowPosition(0);
        Message_Who(8);
        Message_MsgDisp("Masaki", "... Ah, umm... I kind of fell...");
        Message_WindowPosition(1);
        Message_Who(0);
        Message_MsgDisp("主人公", "E-Excuse me! It was my fault!");
        Character_ChFace(1, 2, 0);
        Character_ChFace(1, 3, 4);
        Voice_PlayVoice("A0208300_Q02900", #1, "");
        Message_Who(17);
        Message_MsgDisp("Arisawa", "... Oh? You...\nare you by any chance the new worker\nthat was scheduled to start today?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, yes. I am ｛主人公姓名｝.");
        Character_ChFace(1, 0, 10);
        Voice_PlayVoice("A0208300_Q00900", #1, "");
        Message_Who(17);
        Message_MsgDisp("Arisawa", "I am Arisawa Shiho.\nI look forward to working with you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Me too, I look forward to working\nwith you!");
        Character_ChFace(1, 2, 1);
        Voice_PlayVoice("A0208300_Q03100", #1, "");
        Message_Who(17);
        Message_MsgDisp("Arisawa", "It's an unimaginable first day.\nFor the moment, could I ask you to\nhelp pick up the flowers?");
        Message_Who(0);
        Message_MsgDisp("主人公", "O-Okay!");
        Character_ChFace(1, 0, 10);
        Voice_PlayVoice("A0208300_Q03200", #1, "");
        Message_Who(17);
        Message_MsgDisp("Arisawa", "Now then, I will see you later.");
        Character_Chara_GS2(17, "NON");
        System_Wait(30);
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(8, 3, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("A0208300_H03300", #1, "");
        Message_WindowPosition(0);
        Message_Who(8);
        Message_MsgDisp("Masaki", "*Phew* I was saved... Thanks...");
        Character_ChFace(0, 0, 11);
        Character_BlinkStart(8, 0, (#1));
        Voice_PlayVoice("A0208300_H03400", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "... Ah!!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!?");
        Voice_PlayVoice("A0208300_H03500", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "You're the girl I bumped into\nearlier.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah...");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("A0208300_H03600", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "It was the opposite of today's.\nLast time it was quite a fall.\nWere you okay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-Yes.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(8, 3, (#1));
        Voice_PlayVoice("A0208300_H03700", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "I see, good.\nI was worried, but I didn't know who\nyou were or where you were from.");
        Character_BlinkStart(8, 0, (#1));
        Voice_PlayVoice("A0208300_H03800", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "But I'm shocked that you're my\njunior.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh.\nDoes that mean that you are a\ngraduate from Hanegasaki Academy?");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("A0208300_H03900", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Yeah.\nWell, we'll get to that conversation\ngradually.");
        Voice_PlayVoice("A0208300_H04000", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "I'm Masaki Motoharu.\nI look forward to working with you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes!\nI look forward to working with you!");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("A0208300_H04100", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Oh, that's a good reply.\nI expect for you to work well, so do\nyour best.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("A0208300_H04200", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "...\nNow, if I'm slow, I'm going to be\nyelled at by Arisawa, again...\nLet's work quickly.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(So the person I bumped into then\nwas ｛Masaki＊＊｝...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He's probably a person that you\njust can't hate.)");
        }
    Music_StopBGM(0, 40);
    Parameter_InCh1Param(8, 514, 1);
    Parameter_AddCh1Param(8, 86, 1);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
