section "a02_m2_200"{
    Background_Bg_GS2("BG_SC420_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(I'm really late.\nIf I don't hurry, club activities\nwill start without me!)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh?\nWho is that standing over there...?\nAre they an aspiring club member?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm...\nAre you perhaps an aspiring club\nmember?");
    Character_BlinkStart(2, 2, (#1), 1);
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(2, "M2_01F", 0);
    Environment_PauseME(0);
    Music_PlayBGM(0, "MN_C_02_000_D01", 127, 40);
    Voice_PlayVoice("A0202200_B00000", #1, "");
    Message_Who(2);
    Message_MsgDisp("？？？", "...... No.");
    Message_Who(0);
    Message_MsgDisp("主人公", "But you were really focused on\nwatching them practice...");
    Character_BlinkStart(2, 3, (#1));
    Voice_PlayVoice("A0202200_B00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("？？？", "............");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's fine by us if you have doubts.\nEven if you're a beginner, we...");
    Character_BlinkStart(2, 0, (#1));
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("A0202200_B00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("？？？", "I said I'm not.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay.\nAh, I'm ｛主人公姓名｝.\nAnd you are?");
    Character_BlinkStart(2, 3, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("A0202200_B00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("？？？", "...... Shiba Katsumi.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm, so you're\n｛Shiba＊＊｝...\nAh!");
    Character_Chara_GS2(2, "NON");
    Music_StopBGM(0, 40);
    Environment_ResumeME(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(... He left.\nI wonder if he wanted to join the\nclub...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_InCh1Param(2, 514, 1);
    Parameter_AddCh1Param(2, 86, 1);
    }
