section "a02_g1_100"{
    Background_Bg_GS2("BG_NE000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah! I've worked hard today, too...)");
    Voice_PlayVoice("A0210002_W00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Man", "Scram!");
    Message_Who(0);
    Message_MsgDisp("主人公", "What... Kyaa!");
    SoundEffect_PlayStream(2, "SS_T_00_008_M00");
    Screen_StartShakePlane(0, 32, 32, 0, 16);
    System_Wait(92);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ouch... What in the world...");
    Voice_PlayVoice("A0210002_W00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Woman", "Someone!!!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh!?");
    Voice_PlayVoice("A0210002_W00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Woman", "Someone catch that person!\nThey stole my purse!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(A t-thief!? W-What should I do～!)");
    Message_CloseMsg();
    SoundEffect_StopStream(2, 40);
    SoundEffect_PlayStream(2, "SS_T_00_028_M00");
    Environment_PauseME(0);
    System_Wait(80);
    Character_ChFace(0, 0, 8);
    Character_Chara_GS2(10, "G1_01F", 0);
    Music_PlayBGM(0, "MN_C_10_000_D01", 127, 40);
    Voice_PlayVoice("A0210002_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("？？？", "Which way did they go?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uhh... They went t-that way...!");
    Character_BlinkStart(10, 2, (#1));
    Voice_PlayVoice("A0210002_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("？？？", "... Him, huh. Got it.");
    SoundEffect_PlayStream(2, "SS_T_00_010_M00");
    Character_Chara_GS2(10, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Whoa... she's fast!\nIt looks like she's caught up to\nhim...)");
    Voice_PlayVoice("A0210002_J00500", #1, "");
    Message_Who(10);
    Message_MsgDisp("？？？", "...\nDon't go around doing dirty things!");
    Voice_PlayVoice("A0210002_W00600", #1, "");
    Message_Who(0);
    Message_MsgDisp("Man", "S-Sorry! Forgive m--!");
    SoundEffect_PlayStream(2, "SS_T_00_011_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Whoa! That looked like it hurt...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(10, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(10, "G1_01F", 0);
    Background_Bg_GS2("BG_NE000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("A0210002_J00700", #1, "");
    Message_Who(10);
    Message_MsgDisp("？？？", "Are you okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yes... Thank you very much.\nUmm...");
    Voice_PlayVoice("A0210002_J00800", #1, "");
    Message_Who(10);
    Message_MsgDisp("？？？", "Toudou Tatsuko.\nI'm in the same grade as you, so\ndon't be so polite to me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh! Is that true?\nI am ｛主人公姓名｝.");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(10, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("A0210002_J00900", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I just told you to not use polite\nspeech with me...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, I'm very sorry! ...\nI mean, sorry!");
    Character_BlinkStart(10, 0, (#1));
    Voice_PlayVoice("A0210002_J01000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Hah. You're a funny one.");
    Message_Who(0);
    Message_MsgDisp("主人公", "R-Really...?");
    Character_ChFace(0, 0, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Anyway, I accepted a thank you note\nfrom the lady on your behalf,\n｛Toudou＊＊｝!");
    Message_Who(0);
    Message_MsgDisp("主人公", "You should take it,\n｛Toudou＊＊｝.\nThat lady said that you should take\nit, too.");
    Character_BlinkStart(10, 3, (#1));
    Voice_PlayVoice("A0210002_J01200", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I don't swing that way.");
    Message_Who(0);
    Message_MsgDisp("主人公", "But I didn't do a thing...");
    Character_BlinkStart(10, 0, (#1));
    Voice_PlayVoice("A0210002_J01300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "You helped out as well, right?\nIf you don't need it, then throw it\naway.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I can't just throw it away...");
    Voice_PlayVoice("A0210002_J01400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Take care of it. Later.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Toudou＊＊｝!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(10, "NON");
    Environment_ResumeME(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Toudou＊＊｝, huh...\nShe's a brave and cool person.)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_InCh1Param(10, 514, 1);
    Parameter_AddCh1Param(10, 86, 1);
    }
