section "a02_g4_400"{
    Background_Bg_GS2("BG_SC212_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(*sigh* That was long.\nNow then, my classroom is...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh?\nUhh, that's East, and that's West,\nso...)");
    Voice_PlayVoice("A0213001_M00000", #1, "");
    Message_Who(13);
    Message_MsgDisp("？？？", "Hey, are you looking for your\nclassroom?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Environment_StopME(0, 40);
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(13, "G4_01F", 0);
    Music_PlayBGM(0, "MN_C_13_000_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yes. I don't know where it is.\nI'm in Grade 1, Class B...");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(13, 2, (#1));
    Voice_PlayVoice("A0213001_M00100", #1, "");
    Message_Who(13);
    Message_MsgDisp("？？？", "Haha, Class B is right over there.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, you're right!\nThank you very much, Senpai!");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(13, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("A0213001_M00200", #1, "");
    Message_Who(13);
    Message_MsgDisp("？？？", "Oh no, do I look older?\nWe're in the same grade, though...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? Then...");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(13, 0, (#1));
    Voice_PlayVoice("A0213001_M00300", #1, "");
    Message_Who(13);
    Message_MsgDisp("？？？", "Yeah, I'm in my first year, too.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so. Sorry.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("A0213001_M00400", #1, "");
    Message_Who(13);
    Message_MsgDisp("？？？", "It's fine. I'm Mizushima Hisoka.\nYou write my name like the word for\n\"secret\".\nNice to meet you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm ｛主人公姓名｝.\nNice to meet you, too!");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("A0213001_M00500", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "How mysterious...\nMy horoscope today is: \"You will\nmeet someone new, when you are asked\nfor directions\".");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh, is that so...");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("A0213001_M00600", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Do you think that we'll become\nfriends?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Of course!");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("A0213001_M00700", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Then my horoscope was right!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, that's amazing!");
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("A0213001_M00800", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Haha, it'd be nice if our days in\nhigh school are fun.");
    SoundEffect_PlayStream(2, "SS_T_00_079_S00");
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 3, 0);
    Character_BlinkStart(13, 0, (#1));
    Voice_PlayVoice("A0213001_M00900", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Oh dear!\nI have to get back to my own\nclassroom!\nI will see you later.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'll see you later!");
    Character_Chara_GS2(13, "NON");
    Music_StopBGM(0, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Mizushima＊＊｝, huh.\nShe's a beautiful and mature\nperson...)");
    Message_CloseMsg();
    SoundEffect_StopStream(2, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_InCh1Param(13, 514, 1);
    Parameter_AddCh1Param(13, 86, 1);
    }
