section "a02_m3_100"{
    Background_Bg_GS2("BG_SC102_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    SoundEffect_PlayStream(1, "SS_DSE_060_000", 127, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Whoa, I'm late!\nI'll just try and get there on time,\nsomehow...)");
    SoundEffect_PlayStream(1, "SS_DSE_113_000", 127, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Yay, I'm somewhat safe!!");
    Voice_PlayVoice("A0203100_C00000", #1, "");
    Message_Who(3);
    Message_MsgDisp("？？？", "Out!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh!?");
    Character_ChFace(0, 0, 8);
    Character_Chara_GS2(3, "M3_01F", 0);
    Environment_PauseME(0);
    Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
    Voice_PlayVoice("A0203100_C00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("？？？", "You heard the bell ring too, right?\nIt is currently 8:25 and 15 seconds.");
    Voice_PlayVoice("A0203100_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("？？？", "According to Chapter 3, Section 4 of\nthe school rules: Students must be\nin their seats and ready for class\nwhen the bell rings.");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(3, 3, (#1));
    Voice_PlayVoice("A0203100_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("？？？", "Strictly speaking, you are already\nlate.");
    Message_Who(0);
    Message_MsgDisp("主人公", "B-But if I ran, I might've made it\nto class!");
    Character_BlinkStart(3, 1, (#1));
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("A0203100_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("？？？", "That is a different story.\nFurthermore, Chapter 3, Section 7\nstates that running on school\ngrounds is prohibited.");
    Message_Who(0);
    Message_MsgDisp("主人公", "No way... Ah!\nBut you're not in class, either...");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("A0203100_C00500", #1, "");
    Message_Who(3);
    Message_MsgDisp("？？？", "Look at my armband.\nI am a prefect of the Student\nCouncil, Hikami Itaru.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh, a prefect!?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("A0203100_C00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Now that you know, tell me your\ngrade, class, and your full name.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ugh... But it was only 15 seconds!");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("A0203100_C00700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "That is still classed as being late.\nGrade, class, and full name now.");
    Character_ChFace(0, 0, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "*Sigh*......\nI'm ｛主人公姓名｝ of Grade\n｛学年｝, Class B.");
    Voice_PlayVoice("A0203100_C00800", 3, "A0203100_C00801");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Okay, ｛主人公｝.\nAfter school, bring your Student ID\nto the Educational Affairs Office...\nAh!");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(3, 2, (#1));
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("A0203100_C00900", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Another latecomer! Excuse me!");
    SoundEffect_PlayStream(2, "SS_T_00_020_M00");
    Character_Chara_GS2(3, "NON");
    Music_StopBGM(0, 40);
    Environment_ResumeME(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hikami＊＊｝, huh...\nHe's one of those straight-laced\npeople.\nThe ones that you see in manga...)");
    Voice_PlayVoice("A0203100_C01000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Hurry! Class is starting!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yes!!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hikami＊＊｝ really is a\nserious person...)");
    Message_CloseMsg();
    Environment_StopME(1, 40);
    SoundEffect_StopStream(2, 40);
    Environment_StopME(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_InCh1Param(3, 514, 1);
    Parameter_AddCh1Param(3, 86, 1);
    }
