section "a02_g2_400"{
    Background_Bg_GS2("BG_SC212_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    SoundEffect_PlayStream(2, "SS_T_00_012_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "(...\nHuh, it looks like I forgot my\nhandkerchief.\nHow troubling.)");
    Voice_PlayVoice("A0211003_K00000", #1, "");
    Message_Who(11);
    Message_MsgDisp("？？？", "Are you looking for something?");
    Environment_PauseME(0);
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(11, "G2_01F", 0);
    Music_PlayBGM(0, "MN_C_11_000_D01", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yeah.\nI've actually forgotten to bring my\nhandkerchief...");
    Voice_PlayVoice("A0211003_K00100", #1, "");
    Message_Who(11);
    Message_MsgDisp("？？？", "Is that so?\nIf it is alright with you, please\nuse this.\nIt's my handkerchief.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Wow, what a cute handkerchief.\nThere's a bear embroidered on it.)");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(11, 2, (#1));
    Voice_PlayVoice("A0211003_K00200", #1, "");
    Message_Who(11);
    Message_MsgDisp("？？？", "... What's the matter?\nEven if you stare at it, your hands\nwon't get dry.");
    Message_Who(0);
    Message_MsgDisp("主人公", "That's true...\nBut is it okay for me to use this?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("A0211003_K00300", #1, "");
    Message_Who(11);
    Message_MsgDisp("？？？", "Don't worry about me.\nI always carry around a spare\nhandkerchief with me.");
    Voice_PlayVoice("A0211003_K00400", #1, "");
    Message_Who(11);
    Message_MsgDisp("？？？", "I have a habit of inspecting the\ncontents of my bag before I leave\nthe house.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Really, amazing.\nI should do that, too.\nUmm, you are...");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("A0211003_K00500", #1, "");
    Message_Who(11);
    Message_MsgDisp("？？？", "I am Onoda Chiyomi. And you are?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm ｛主人公姓名｝.\nUmm, I'll return this handkerchief\nto you after I wash it.");
    Voice_PlayVoice("A0211003_K00600", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "You don't have to worry about it.\nRather, please make sure that you\ndon't forget anything.");
    Voice_PlayVoice("A0211003_K00700", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Now then, please excuse me.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(11, "NON");
    Environment_ResumeME(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Onoda＊＊｝, huh.\nShe seems very serious...\nBut she's tiny and cute.)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_InCh1Param(11, 514, 1);
    Parameter_AddCh1Param(11, 86, 1);
    }
