section "a02_g1_300"{
    Message_Who(0);
    Message_MsgDisp("主人公", "Thank you very much～...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Argh, we're busy... I'm tired...)");
    Voice_PlayVoice("A0210003_J00000", #1, "");
    Message_Who(10);
    Message_MsgDisp("？？？", "I can't hear you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Eh?)");
    Environment_PauseME(0);
    Character_ChFace(0, 0, 8);
    Character_Chara_GS2(10, "G1_13F", 0);
    Music_PlayBGM(0, "MN_C_10_000_D01", 127, 40);
    Voice_PlayVoice("A0210003_J00100", #1, "");
    Message_Who(10);
    Message_MsgDisp("？？？", "I get that you're tired, since it's\nyour first day working, but you\ncan't let the customers see that.\nShow me some spirit.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yes! I'm very sorry... Uhh...");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("A0210003_J00200", #1, "");
    Message_Who(10);
    Message_MsgDisp("？？？", "... Ah. I'm Toudou Tatsuko.\nI go to the same school as you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm ｛主人公姓名｝.\nI look forward to working with you!");
    Voice_PlayVoice("A0210003_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Yeah. Ah, also..");
    Voice_PlayVoice("A0210003_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I'm in the same grade as you, so you\ndon't need to use polite speech with\nme.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh!");
    Character_BlinkStart(10, 2, (#1));
    Voice_PlayVoice("A0210003_J00500", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... Is it that strange?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, no... Not at all...");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(10, 2, (#1));
    Voice_PlayVoice("A0210003_J00600", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... How honest. What a funny one.");
    Character_BlinkStart(10, 0, (#1));
    Voice_PlayVoice("A0210003_J00700", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "If there's something you don't know,\nask me....\nAh, a customer.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("A0210003_J00800", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Welcome!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(10, "NON");
    Environment_ResumeME(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Toudou＊＊｝, huh...\nShe seems like a dependable person.)");
    Parameter_InCh1Param(10, 514, 1);
    Parameter_AddCh1Param(10, 86, 1);
    }
