section "a02_g2_200"{
    Background_Bg_GS2("BG_SCA80_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(11);
    Message_MsgDisp("？？？", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes!");
    Environment_StopME(0, 40);
    Character_ChFace(0, 0, 10);
    Character_Chara_GS2(11, "G2_01F", 0);
    Music_PlayBGM(0, "MN_C_11_000_D01", 127, 40);
    Voice_PlayVoice("A0211002_K00000", #1, "");
    Message_Who(11);
    Message_MsgDisp("？？？", "Welcome to the Student Council.\nI am Onoda Chiyomi.\nI am in the same grade as you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so.\nI look forward to working with you,\n｛Onoda＊＊｝!");
    Voice_PlayVoice("A0211002_K00100", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Me too.\nIt's a bit soon, but have you read\nover the minutes from last year's\nmeetings?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uhh... not yet.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("A0211002_K00200", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Then please read them before our\nnext meeting.\nYou have to know of the activities\nthat took place last year.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay, I understand.\nBut reading it all seems tough.");
    Voice_PlayVoice("A0211002_K00300", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "It's not that long.\nTwo days was enough for me to\nmemorize it all.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh? To memorize all of that!?\nT-That's definitely impossible...");
    Character_BlinkStart(11, 3, (#1));
    Voice_PlayVoice("A0211002_K00400", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "It's a question of enthusiasm.\nYou should put the effort into doing\nit, before you give up.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Okay. I'll try my best.");
    Character_BlinkStart(11, 0, (#1));
    Voice_PlayVoice("A0211002_K00500", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "That is fine.\nOf course, that's not the only thing\nyou need to do...");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(11, 3, (#1));
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("A0211002_K00600", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "You need to be ready to demonstrate\nyour intellect, strength and\nability!");
    Character_BlinkStart(11, 0, (#1));
    Voice_PlayVoice("A0211002_K00700", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "The Student Council is the\ncornerstone for the school!\nWe have a great responsibility.\nLet's do our best!");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yes...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Onoda＊＊｝, huh.\nWhat a spirited person...\nBut she's tiny and cute.)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_InCh1Param(11, 514, 1);
    Parameter_AddCh1Param(11, 86, 1);
    }
