section "a02_m6_300"{
    System_Call_GS2("Z71", "M7", 0);
    Background_Bg_GS2("BG_SC211_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetPl1Param(312) != 6){
        Message_Who(0);
        Message_MsgDisp("主人公", "I should probably go home.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Ah, it's raining.\nThank goodness I brought my\numbrella.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Background_Bg_GS2("BG_SC201_CO_0", #1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "... Hm?");
        Environment_PauseME(0);
        Character_ChFace(0, 0, 9);
        Character_Chara_GS2(6, "M6_01F", 0);
        Music_PlayBGM(0, "MN_C_06_000_D01", 127, 40);
        Voice_PlayVoice("A0206000_F00000", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "Won't it stop raining?...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Maybe he didn't bring an umbrella?\n... Alright!)");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hello.");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("A0206000_F00100", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "... Eh? Ah, hello...");
        Message_Who(0);
        Message_MsgDisp("主人公", "If you're okay with going to the\nstation, we can share an umbrella.");
        Character_ChFace(0, 0, 0);
        Character_BlinkStart(6, 3, (#1));
        Voice_PlayVoice("A0206000_F00200", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "Is that alright!?\nThank you very much!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(6, "NON");
        SoundEffect_PlayStream(2, "SS_T_00_082_M00");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Still_Event("EV_06_01", #1, 0, 60);
        Screen_WipeIn(2);
        Environment_PlayME(1, "SN_P_00_001_000", 127, 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's a bit of a shame that it's\nraining on the day of your entrance\nceremony.");
        Voice_PlayVoice("A0206000_F00300", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "Yes...\nBut I think that it's a good thing.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Why?");
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("A0206000_F00400", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "If it weren't raining, I don't think\nthat I'd be able to talk to you like\nthis.");
        Still_StillFace(0, 6, 2);
        Voice_PlayVoice("A0206000_F00500", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "I'm glad I enrolled in Hanegasaki\nAcademy.\nI was able to meet a really nice\nsenior.");
        Still_Approach(6, 150, 0, 0, 1, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ahaha. You're exaggerating.");
        Still_ApproachEnd();
        Message_CloseMsg();
        Screen_WipeOut(2);
        Environment_StopME(1, 40);
        Still_Event("");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Character_ChFace(0, 0, 10);
        Character_Chara_GS2(6, "M6_01F", 0);
        Background_Bg_GS2("BG_NE001_SP_0", #1, #1, 0);
        Effect_OpenParticle(2);
        Screen_WipeIn(2);
        Voice_PlayVoice("A0206000_F00600", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "I will take my leave now. Uhh...");
        Message_Who(0);
        Message_MsgDisp("主人公", "I'm ｛主人公姓名｝.\nAnd you are?");
        Voice_PlayVoice("A0206000_F00700", 6, "A0206000_F00701");
        Message_Who(6);
        Message_MsgDisp("？？？", "I am Amachi Shota.\nThank you very much,\n｛主人公｝.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(6, 0, (#1));
        Voice_PlayVoice("A0206000_F00800", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Don't hesitate to talk to me if you\nsee me at school!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Sure.");
        Character_ChFace(0, 0, 3);
        Character_BlinkStart(6, 3, (#1));
        Voice_PlayVoice("A0206000_F00900", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Now then, excuse me.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(6, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Amachi＊＊｝, huh...\nWhat a good, well-mannered kid.)");
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "I should probably go home.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Ah, it's raining.\nThank goodness I brought my\numbrella.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Background_Bg_GS2("BG_SC201_CO_0", #1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "... Huh?");
        Environment_PauseME(0);
        Character_ChFace(0, 0, 11);
        Character_ChFace(0, 4, 1);
        Character_Chara_GS2(6, "M6_01F", 0);
        Music_PlayBGM(0, "MN_C_06_000_D01", 127, 40);
        Voice_PlayVoice("A0206000_F01000", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "Ah! You're from that time...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Right.\nYou're that kid I bumped into in\nfront of the station!");
        Voice_PlayVoice("A0206000_F01300", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "You're going home now, right?\nPlease go on home.\nI'm waiting for the rain to die\ndown.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Did you forget to bring an umbrella?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(6, 0, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("A0206000_F01400", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "Yes.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Then do you want to share my\numbrella?\nI can only walk you to the station,\nthough.");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("A0206000_F01500", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "Is that okay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Of course it is.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("A0206000_F01600", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "... But aren't you worried?\nIf we get too close, we'll...");
        Message_Who(0);
        Message_MsgDisp("主人公", "If we get close?");
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("A0206000_F01700", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "... No, it is nothing.\nMay I ask you to do this for me?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Sure. Let's go.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(6, "NON");
        SoundEffect_PlayStream(2, "SS_T_00_082_M00");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Still_Event("EV_06_01", #1, 0, 60);
        Screen_WipeIn(2);
        Environment_PlayME(1, "SN_P_00_001_000", 127, 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's a bit of a shame that it's\nraining on the day of your entrance\nceremony.");
        Voice_PlayVoice("A0206000_F01800", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "Yes...\nBut I think that it's a good thing.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Why?");
        Still_StillFace(0, 6, 2);
        Voice_PlayVoice("A0206000_F01900", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "If it weren't raining, I don't think\nthat I'd be able to talk to you like\nthis.");
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("A0206000_F00500", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "I'm glad I enrolled in Hanegasaki\nAcademy.\nI was able to meet a really nice\nsenior.");
        Still_Approach(6, 150, 0, 0, 1, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ahaha. You're exaggerating.");
        Still_ApproachEnd();
        Message_CloseMsg();
        Screen_WipeOut(2);
        Environment_StopME(1, 40);
        Still_Event("");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(6, "M6_01F", 0);
        Background_Bg_GS2("BG_NE001_SP_0", #1, #1, 0);
        Effect_OpenParticle(2);
        Screen_WipeIn(2);
        Voice_PlayVoice("A0206000_F02100", #1, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "I will take my leave now. Uhh...");
        Message_Who(0);
        Message_MsgDisp("主人公", "I'm ｛主人公姓名｝.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("A0206000_F02200", 6, "A0206000_F02201");
        Message_Who(6);
        Message_MsgDisp("？？？", "I am Amachi Shota.\nThank you very much,\n｛主人公｝.");
        Voice_PlayVoice("A0206000_F02300", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "I'm glad that I could introduce\nmyself.\nDon't hesitate to talk to me if you\nsee me at school!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Sure.");
        Character_ChFace(0, 0, 3);
        Character_BlinkStart(6, 3, (#1));
        Voice_PlayVoice("A0206000_F02400", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Thank you very much for today....\nNow then, excuse me.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(6, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Amachi＊＊｝, huh...\nWhat a good, well-mannered kid.)");
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Effect_CloseParticle();
    Parameter_InCh1Param(6, 514, 1);
    Parameter_AddCh1Param(6, 86, 1);
    }
