section "i55_m5_000"{
    if (Parameter_GetCh1Param(5, 130) <= 2){
        Background_Bg_GS2("BG_AR500_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Welcome. Ah, ｛Chris＊＊｝.");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(5, "M5_??F", 0);
        Voice_PlayVoice("I5505000_E00000", 5, "I5505000_E00001");
        Message_Who(5);
        Message_MsgDisp("Chris", "Huh, ｛主人公｝.\nSo you work here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah. Uhh...\nDid you come here to buy flowers?");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(5, 2, (#1));
        Voice_PlayVoice("I5505000_E00100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Right, it's a florist.\nI'll buy this, then.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Thank you very much!");
        }
    else if (Parameter_GetCh1Param(5, 130) == 3){
        Background_Bg_GS2("BG_AR500_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Welcome, ｛Chris＊＊｝!");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(5, "M5_??F", 0);
        Voice_PlayVoice("I5505000_E00200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hello.\nBeing surrounded by flowers is a\nnice job.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.\nYou actually need to be quite\nstrong, though.");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("I5505000_E00300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ehh, that's unexpected.\nSounds tough.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Haha. What are you doing today?");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("I5505000_E00400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I wanted to come here for some\nreason.\nSince I'm here, I'll buy something.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Really?\nPlease take your time looking\naround.");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("I5505000_E00500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah, I will～.");
        }
    else {
        Background_Bg_GS2("BG_AR500_?_0", 1, #1, 0);
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(5, "M5_??F", 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("", 5, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝! Welcome.\nAre you out shopping today?");
        Voice_PlayVoice("I5505000_E00600", 5, "I5505000_E00601");
        Message_Who(5);
        Message_MsgDisp("Chris", "No. Hey, ｛主人公｝.\nWhat kind of flowers do you like?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, me?");
        Voice_PlayVoice("I5505000_E00700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Uhh... Things like this...");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("I5505000_E00800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Good.\nLook forward to it the next time I\nsee you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_BlinkStart(5, 2, (#1));
        Voice_PlayVoice("I5505000_E00900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I'll see you later.");
        Character_Chara_GS2(5, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(What did ｛Chris＊＊｝ come\nhere to do...)");
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    }
