section "i65_m5_000"{
    if (Parameter_GetCh1Param(5, 130) <= 2){
        Background_Bg_GS2("BG_AR600_?_0", 1, #1, 0);
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(5, "M5_??F", 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("", 5, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝!\nWhat's up?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("I6505000_E00000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I'm going to meet a cute girl for\ntea.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(5, 2, (#1));
        Voice_PlayVoice("I6505000_E00100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "And I came because I saw you.\nAre you working here?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.");
        Character_BlinkStart(5, 3, (#1));
        Voice_PlayVoice("I6505000_E00200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I see～. Work hard. Good bye.");
        Character_Chara_GS2(5, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Alright, I'll work hard!)");
        }
    else if (Parameter_GetCh1Param(5, 130) == 3){
        Background_Bg_GS2("BG_AR600_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Thank you very much!\n*Phew* Things have calmed down...");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(5, "M5_17F", 0);
        Voice_PlayVoice("I6505000_E00300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hello.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝. Hello.\nWhat's up?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("I6505000_E00400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I'm going to a business meeting.\nThey will be coming over here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("I6505000_E00500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "This job looks very hard.\nYou have to stand.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm, it's not so tough when you get\nused to it.");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("I6505000_E00600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Really? But don't push yourself.\nAh, they're here.");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("I6505000_E00700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I'll see you later. Good bye.");
        Character_Chara_GS2(5, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Alright, I have to do my best,\ntoo!)");
        }
    else {
        Background_Bg_GS2("BG_AR600_?_0", 1, #1, 0);
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(5, "M5_17F", 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("", 5, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝!\nWhat's up?");
        Character_BlinkStart(5, 3, (#1));
        Voice_PlayVoice("I6505000_E00800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hmm, somehow.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Somehow?");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("I6505000_E00900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah. Somehow...");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Somehow...?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 3, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("I6505000_E01000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I somehow thought that it would go\nwell if I saw your face.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(5, 2, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("I6505000_E01100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I'm going to do something important\nfor work.\nMaybe you would call it\nsuperstition?");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("I6505000_E01200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ah, they're here.\nSorry for bothering you at work.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("I6505000_E01300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ah.\nIf it goes well, I'll fill up here\non the way home～.\nI'll pray so that we can see each\nother again.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(5, 3, (#1));
        Voice_PlayVoice("I6505000_E01400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I will see you later.");
        Character_Chara_GS2(5, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Chris＊＊｝ is doing his\nbest.\nI also have to do my best!)");
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    }
