section "p13_s1_000"{
    Background_Bg_GS2("BG_SC910_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_B_SC_910_000", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm sorry I kept you waiting!\nHere's your hot coffee, tea and iced\ncocoa...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(*Sigh*... It's busy.)");
    Voice_PlayVoice("P0314000_N00000", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Sis.");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(14, "S1_04F", 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Yuu-kun! You came.");
    Character_BlinkStart(14, 3, (#1));
    Voice_PlayVoice("P0314000_N00100", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "I was a little worried you'd be\nsurprisingly careless, Sis...");
    Message_Who(0);
    Message_MsgDisp("主人公", "What is that supposed to mean?");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("P0314000_N00200", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "N-Nothing.\nI was just saying, what a delicious\ncake, Sis.");
    Message_Who(0);
    Message_MsgDisp("主人公", "So be a customer.\nWhat would you like to order?");
    Character_ChFace(0, 4, 0);
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("P0314000_N00300", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Hmm～...\nWell, a black tea and cake set!");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    System_Call_GS2("P14", "S1", 0);
    }
