section "p13_m7_000"{
    Background_Bg_GS2("BG_SC910_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_B_SC_910_000", 127, 40);
    if (Parameter_GetCh1Param(7, 130) == 3){
        Message_Who(0);
        Message_MsgDisp("主人公", "Coffee and sandwiches!\nThank you for waiting.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Sigh* It's busy and I feel\nfaint...)");
        Voice_PlayVoice("P0307000_G00000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Two customers～!");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(7, "M7_17F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, ｛Wakaouji＊＊｝!\nDid you bring a customer?");
        Voice_PlayVoice("P0307000_G00100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Today, Sensei is the sandwich man.\nThough, he is not carrying a sign\nsaying sandwich man.\nDo you understand?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Uhh～... Anyway!\nThank you for the customers.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("P0307000_G00200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "It's nothing.\nIt's the least Sensei is able to do.\nNow, I'll leave it to all of you.");
        Character_ChFace(0, 0, 11);
        Character_BlinkStart(7, 2, (#1));
        Voice_PlayVoice("P0307000_W00300", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Sensei Waka-sama! Eat a sandwich～!");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P0307000_G00400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Sensei has to rope in the\ncustomers...");
        Voice_PlayVoice("P0307000_W00500", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student B", "That's mean～, will you promise me\nthat you will?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(7, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P0307000_G00600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That's right. Well, a little bit.");
        Voice_PlayVoice("P0307000_W00700", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Yaaay!!");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P0307000_G00800", 7, "P0307000_G00801");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Thus, I will do it.\n｛主人公｝, coffee and a\nsandwich, please.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Certainly.... We have an order!");
        }
    else if (Parameter_GetCh1Param(7, 130) >= 4){
        Message_Who(0);
        Message_MsgDisp("主人公", "Coffee and sandwiches!\nThank you for waiting.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Sigh* It's busy and I feel\nfaint...)");
        Voice_PlayVoice("P0307000_G00900", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Two customers!");
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 3);
        Character_Chara_GS2(7, "M7_17F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, ｛Wakaouji＊＊｝!\nDid you bring a customer?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P0307000_G01000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Yes.\nSensei is a batter that does well\n30% of the time.\nHe do not miss the ones he aims for.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nYou let 70% of the people get\naway...\nHowever, thank you. I'm saved!");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 3, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P0307000_G01100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Don't mention it.\nSensei is a man who will do things\nwhen they need to be done.\nYou do your best, too.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes!");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("P0307000_W01200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Sensei Waka-sama! Eat a sandwich～!");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P0307000_G01300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Sensei's a little busy...");
        Voice_PlayVoice("P0307000_W01400", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student B", "That's mean～, you promised!");
        Voice_PlayVoice("P0307000_G01500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I did... Then, in a little bit.");
        Voice_PlayVoice("P0307000_W01600", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Yaaay!");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P0307000_G01700", 7, "P0307000_G01701");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Excuse me.\n｛主人公｝, coffee and a\nsandwich, please.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes, understood....\nWe have an order!");
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    System_Call_GS2("P14", "M7", 0);
    }
