section "p13_m8_000"{
    Background_Bg_GS2("BG_SC910_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_B_SC_910_000", 127, 40);
    if (Parameter_GetCh1Param(8, 130) == 3){
        Message_Who(0);
        Message_MsgDisp("主人公", "Sorry to keep you waiting, here is\nyour coffee and sandwich.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Sigh* It's so busy that I feel\nfaint...)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(8, "M8_??F", 0);
        Voice_PlayVoice("P0308000_H00000", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Yo.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, ｛Masaki＊＊｝...?\nWhy are you here?");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P0308000_H00100", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Isn't it obvious I came here to see\nmy cute protegee working?\nI'm here checking up on you!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ahaha... Thank you very much...");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("P0308000_H00200", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "What the-- What's with that deflated\nresponse～?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("P0308000_H00300", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Whatever.\nAnyway, is there anything that'll\nfill me up here?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, yes.\nWe have spaghetti and curry.");
        Character_BlinkStart(8, 2, (#1));
        Voice_PlayVoice("P0308000_H00400", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Oh, sounds nice.\nPlease get me some spaghetti.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay. I understand!");
        }
    else if (Parameter_GetCh1Param(8, 130) >= 4){
        Message_Who(0);
        Message_MsgDisp("主人公", "Sorry to keep you waiting, here is\nyour coffee and sandwich.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Sigh* It's so busy that I feel\nfaint...)");
        Character_ChFace(0, 3, 3);
        Character_Chara_GS2(8, "M8_??F", 0);
        Voice_PlayVoice("P0308000_H00500", 8, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Yo, ｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Masaki＊＊｝!\nWhy are you here?");
        Character_ChFace(0, 4, 0);
        Character_ChFace(0, 2, 1);
        Voice_PlayVoice("P0308000_H00600", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "I came here to see if any weird bugs\nwere buzzing around you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Bugs... you say?");
        Character_BlinkStart(8, 3, (#1));
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("P0308000_H00700", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Seems like there aren't any here.\nAlright.");
        Message_Who(0);
        Message_MsgDisp("主人公", "???");
        Character_BlinkStart(8, 0, (#1));
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("P0308000_H00800", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Ah～... Can I order something?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes! What will you have?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("P0308000_H00900", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Is there stuff that's easy to eat?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I would recommend spaghetti or\ncurry, in that case.");
        Character_BlinkStart(8, 2, (#1));
        Voice_PlayVoice("P0308000_H01000", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Then I'll have spaghetti.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay. I understand!");
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    System_Call_GS2("P14", "M8", 0);
    }
