section "p23_m1_000"{
    Background_Bg_GS2("BG_SC920_LI_0", #1, #1, 0);
    Music_PlayBGM(0, "MN_B_SC_920_000", 127, 40);
    Screen_WipeIn(2);
    if (Parameter_GetCh1Param(1, 130) == 3){
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝ seems\npopular.\nHe's gathering customers pretty\nfast...)");
        Voice_PlayVoice("", 1, "P1301000_A00000");
        Message_Who(1);
        Message_MsgDisp("Saeki", "｛主人公｝. Hey.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, yeah!\nWelcome to the disco, \"Young\nPrince\"!");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 4);
        Character_Chara_GS2(1, "M1_01F", 0);
        Voice_PlayVoice("P1301000_A00100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Welcome... What is all of this for?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, ｛Saeki＊＊｝.\nDid you come to watch?\nOur class is a disco!");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(1, 3, (#1));
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("P1301000_A00200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "A disco... I'm going home.\nThis has nothing to do with me...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Come on!\nDon't you think it's best to enter\nsince you went through all the\ntrouble?");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(1, 2, (#1));
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("P1301000_A00300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "No.");
        Message_Who(0);
        Message_MsgDisp("主人公", "One person, coming through!");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(1, 3, (#1));
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("P1301000_A00400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I said no!");
        }
    else if (Parameter_GetCh1Param(1, 130) >= 4){
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝ seems\npopular.\nHe's gathering customers pretty\nfast...)");
        Voice_PlayVoice("", 1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, yeah!\nWelcome to the disco, \"Young\nPrince\"!");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 4);
        Character_Chara_GS2(1, "M1_01F", 0);
        Voice_PlayVoice("P1301000_A00500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "A disco...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, ｛Saeki＊＊｝! Welcome!\nDid you come to watch?");
        Voice_PlayVoice("P1301000_A00600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Yeah, I had nothing else to do.\nWhat in the world are you doing...\nAside from that, why a disc--");
        Message_Who(0);
        Message_MsgDisp("主人公", "Come on!\nDon't you think it's best to enter\nsince you went through all the\ntrouble?");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(1, 2, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("P1301000_A00700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "No.");
        Message_Who(0);
        Message_MsgDisp("主人公", "One person, coming through!");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(1, 3, (#1));
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("P1301000_A00800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I said no!");
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    System_Call_GS2("P24", "M1", 0);
    }
