section "p23_m8_000"{
    Background_Bg_GS2("BG_SC920_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_B_SC_920_000", 127, 40);
    if (Parameter_GetCh1Param(8, 130) == 3){
        Message_Who(0);
        Message_MsgDisp("主人公", "Welcome to the disco \"Young Prince\"!");
        Message_Who(0);
        Message_MsgDisp("主人公", "（Gosh, surprisingly, people are\nshowing up.\nIt's getting so hectic that I'm\nfeeling faint...)");
        Voice_PlayVoice("P1308000_H00000", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Hey.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Huh, that voice...)");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(8, 2, (#1));
        Character_ChFace(0, 3, 3);
        Character_Chara_GS2(8, "M8_??F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Masaki＊＊｝!");
        Voice_PlayVoice("P1308000_H00100", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "That familiar voice and face leads\nto an accomplished mission.\nAre you surprised?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I am!\nI never thought that you would come\nand visit, ｛Masaki＊＊｝...");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("P1308000_H00200", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Never thought you'd be so surprised.\nIt's not odd to visit, since it's\nalso where I came from, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, yeah... Of course.");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("P1308000_H00300", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "I see that you're doing something\nfun.\nThis \"disco\" term is a good sign,\ntoo.");
        Message_Who(0);
        Message_MsgDisp("主人公", "*Giggles* Well then, let me lead the\nway!");
        }
    else if (Parameter_GetCh1Param(8, 130) >= 4){
        Message_Who(0);
        Message_MsgDisp("主人公", "Welcome to the disco \"Young Prince\"!");
        Message_Who(0);
        Message_MsgDisp("主人公", "（Gosh, surprisingly, people are\nshowing up.\nIt's getting so hectic that I'm\nfeeling faint...)");
        Character_ChFace(0, 0, 10);
        Character_Chara_GS2(8, "M8_??F", 0);
        Voice_PlayVoice("P1308000_H00400", 8, "P1308000_H00401");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Hey, ｛主人公｝.\nMaking some profits?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm... ｛Masaki＊＊｝!\nDid you come to visit?");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(8, 3, (#1));
        Voice_PlayVoice("P1308000_H00500", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Yeah.\nI had a hard time reaching this\nplace.\nI've walked miles for it...");
        Character_BlinkStart(8, 0, (#1));
        Voice_PlayVoice("P1308000_H00600", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Good thing I listened closely to\nyour class section.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You don't have to strain yourself\nthat much...");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(8, 2, (#1));
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("P1308000_H00700", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "... It's fine.\nI had the urge to see you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh?");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P1308000_H00800", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Umm, nothing, nothing!\nLook, lead the way, quick.\nIt's crowding behind me.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, yeah!\nWell then, let me lead the way!");
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    System_Call_GS2("P24", "M8", 0);
    }
