section "p23_m2_000"{
    Background_Bg_GS2("BG_SC920_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_B_SC_920_000", 127, 40);
    if (Parameter_GetCh1Param(2, 130) == 3){
        Message_Who(0);
        Message_MsgDisp("主人公", "Welcome to the disco, \"Young\nPrince\"!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Gosh, surprisingly, people are\nshowing up.\nIt's getting so hectic that I'm\nfeeling faint...)");
        Voice_PlayVoice("", 2, "");
        Message_Who(2);
        Message_MsgDisp("？？？", "｛主人公｝.");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(2, "M2_01F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, ｛Shiba＊＊｝. Welcome!");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("P1302000_B00000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... A disco?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yep. Are you going to dance?");
        Voice_PlayVoice("P1302000_B00100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Bye.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh!?\nUmm, you could just watch since you\nwent through all that trouble....");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(2, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("P1302000_B00200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... I'll just watch.");
        Message_Who(0);
        Message_MsgDisp("主人公", "O-Okay.\nThen allow me to guide you in!");
        }
    else if (Parameter_GetCh1Param(2, 130) >= 4){
        Message_Who(0);
        Message_MsgDisp("主人公", "Welcome to the disco, \"Young\nPrince\"!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Gosh, surprisingly, people are\nshowing up.\nIt's getting so hectic that I'm\nfeeling faint...)");
        Voice_PlayVoice("", 2, "");
        Message_Who(2);
        Message_MsgDisp("？？？", "｛主人公｝.");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(2, "M2_01F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, ｛Shiba＊＊｝.\nDid you come to watch?");
        Voice_PlayVoice("P1302000_B00300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Yeah. Just making sure.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Making sure?");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("P1302000_B00400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Discos are places that reek of\nseemingly bad public order.\nIt's dangerous, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's okay, it's for the school.\nYou didn't have any trouble coming\nhere, did you?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(2, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("P1302000_B00500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... You don't understand.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_BlinkStart(2, 0, (#1));
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("P1302000_B00600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... I'm going in.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, okay.\nWell then, please let me guide you\nin!");
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    System_Call_GS2("P24", "M2", 0);
    }
