section "p33_m3_000"{
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_bunka_jyu(0) == 1){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ugh～ I'm nervous...\nWhat will I do if I make a mistake.)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(3, "M3_16F", 0);
        Voice_PlayVoice("", 3, "P2303000_C00000");
        Message_Who(3);
        Message_MsgDisp("Hikami", "｛主人公｝, at last....\nPerhaps you're getting nervous.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Hikami＊＊｝...");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("P2303000_C00100", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "... Okay, hold out your hand.\nIt's a special good luck charm.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("P2303000_C00200", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Potato, potato, potato.\nWrite it three times on the palm of\nyour hand and gulp down.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh!?");
        Character_BlinkStart(3, 2, (#1));
        Voice_PlayVoice("P2303000_C00300", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Now, swallow quickly.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\n*Giggles* ｛Hikami＊＊｝,\nthat's incorrect.");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(3, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P2303000_C00400", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "...\nOkay, then you can go back to doing\nthe usual.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah...");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("P2303000_C00500", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "The superstition and the suggestion\nare a combined technique.\nIsn't thinking of the idea\nexceptionally effective?");
        Voice_PlayVoice("P2301000_W00200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Broadcaster", "Hanegasaki Academy's school play\nwill now begin.");
        SoundEffect_PlayStream(3, "SS_T_00_041_M00");
        Character_ChFace(0, 4, 0);
        Character_BlinkStart(3, 2, (#1));
        Voice_PlayVoice("P2303000_C00700", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "... Now, let's go.\nLet's show the results of\npracticing.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_Call_GS2("P34", "M3", 0);
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Phew* I'm worn out.)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(3, "M3_08F", 0);
        Voice_PlayVoice("", 3, "P2303000_C00800");
        Message_Who(3);
        Message_MsgDisp("Hikami", "｛主人公｝, it seems like\nyou are on time for the staging.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes.\nGood job, ｛Hikami＊＊｝.");
        Character_ChFace(0, 4, 0);
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(3, 3, (#1));
        Voice_PlayVoice("P2303000_C00900", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Yes, I thought it would only be for\na moment.\nCertainly the heroine's dress would\nhave somehow become caught and torn?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Honestly, I was surprised.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(3, 2, (#1));
        Voice_PlayVoice("P2303000_C01000", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "However, thanks to you, it was\ntemporarily repaired wonderfully.\nHaha, you really are a person...");
        Message_Who(0);
        Message_MsgDisp("主人公", "...?");
        Character_ChFace(0, 0, 11);
        Character_BlinkStart(3, 2, (#1));
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("P2303000_C01100", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Ah, no, umm... it's nothing....\nThank you is what I meant.");
        Voice_PlayVoice("P2301000_W00800", #1, "");
        Message_Who(0);
        Message_MsgDisp("Broadcaster", "Hanegasaki Academy's school play\nwill now begin.");
        SoundEffect_PlayStream(3, "SS_T_00_041_M00");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("P2303000_C01300", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Well, at last.\nLet's pray an incident won't occur.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, I hear that.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_Call_GS2("P34", "M3", 10);
        }
    }
