section "p33_m7_000"{
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_bunka_jyu(0) == 1){
        Message_Who(0);
        Message_MsgDisp("主人公", "(There are a lot of visitors...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It's not easy to move in this\nswallow costume.\nWhat will I do if I fall down...\nI'm so nervous...)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(7, "M7_16F", 0);
        Voice_PlayVoice("", 7, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝!\nThe prince costume appears to suit\nyou!");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("P2307000_G00000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Thank you. You were umm...\nacting quite well as a swallow.");
        Message_Who(0);
        Message_MsgDisp("主人公", ".........");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("P2307000_G00100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Hmm? You look pale, are you ill?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I'm nervous.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("P2307000_G00200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Nervous... I see.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Are you not nervous,\n｛Wakaouji＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P2307000_G00300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Because this is my first time in a\nplay, Sensei's excited.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Excited...?");
        Voice_PlayVoice("P2307000_G00400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "When things don't go well, you\nshould take your time to reflect.\nNow, let's enjoy the anticipation.");
        Voice_PlayVoice("P2301000_W00200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Broadcaster", "Hanegasaki Academy's school play\nwill now begin.");
        SoundEffect_PlayStream(3, "SS_T_00_041_M00");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("", 7, "P2307000_G00600");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "｛主人公｝. Come now.\nIt's our turn!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_Call_GS2("P34", "M7", 0);
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "(There was a time where I wondered\nhow the stage construction would\nturn out, but we somehow made it...)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(7, "M7_17F", 0);
        Voice_PlayVoice("", 7, "P2307000_G00700");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "｛主人公｝. Good job.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, ｛Wakaouji＊＊｝!\nGood, you're in time for the stage\nconstruction!");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("P2307000_G00800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I'm sorry, Sensei stumbled and\nknocked down the set earlier...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, no, I didn't mean that...");
        Voice_PlayVoice("P2301000_W00800", #1, "");
        Message_Who(0);
        Message_MsgDisp("Broadcaster", "Hanegasaki Academy's school play\nwill now begin.");
        SoundEffect_PlayStream(3, "SS_T_00_041_M00");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Message_Who(0);
        Message_MsgDisp("主人公", "Hey! The play's about to begin!");
        Voice_PlayVoice("P2307000_G01000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Yes. Sensei loves this story.\nI look forward to it.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_Call_GS2("P34", "M7", 10);
        }
    }
