section "p33_m1_000"{
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_bunka_jyu(0) == 1){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ugh～, I'm nervous...)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(1, "M1_16F", 0);
        Voice_PlayVoice("", 1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝...");
        Character_ChFace(0, 0, 11);
        Character_BlinkStart(1, 2, (#1));
        Voice_PlayVoice("P2301000_A00000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Your face is ghastly pale, you know?\nAre you nervous?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-Yes...\nAre you alright,\n｛Saeki＊＊｝?");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(1, 3, (#1));
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("P2301000_A00100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "As a matter of fact, I wasn't a\nlittle while ago.\nBut now that I see your face, I'm\nfeeling a little relieved.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝...");
        Voice_PlayVoice("P2301000_W00200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Broadcaster", "Hanegasaki Academy's school play\nwill now begin.");
        SoundEffect_PlayStream(3, "SS_T_00_041_M00");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(1, 2, (#1));
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("P2301000_A00300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Okay, I'm alright!\nI'm not a confused guy! Let's go!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Let's go!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_Call_GS2("P34", "M1", 0);
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Phew* I'm tired.)");
        Voice_PlayVoice("", 1, "P2301000_A00400");
        Message_Who(1);
        Message_MsgDisp("Saeki", "｛主人公｝.\nYou look tired.");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(1, "M1_08F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝. Good job.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(1, 3, (#1));
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("P2301000_A00500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Yeah, I'm tired, too.\nCulture Festivals are tiresome.");
        Character_BlinkStart(1, 0, (#1));
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("P2301000_A00600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I was thinking about just\nwatching...\nThis is the third year I've joined\nin the Culture Festival like this.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.\nNow that you mention it, you're\nright.");
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 3);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("P2301000_A00700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "This festive feeling...\nor should I say, this is what it\nmeans to be a y-youth...");
        Voice_PlayVoice("P2301000_W00800", #1, "");
        Message_Who(0);
        Message_MsgDisp("Broadcaster", "Hanegasaki Academy's school play\nwill now begin.");
        SoundEffect_PlayStream(3, "SS_T_00_041_M00");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(1, 2, (#1));
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("P2301000_A00900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Be careful.\nDon't blurt out anything strange...\nLook, the stagehand is waiting for\nus to finish talking.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_Call_GS2("P34", "M1", 10);
        }
    }
