section "p33_m8_000"{
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("P2301000_W00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Broadcaster", "Hanegasaki Academy's school play\nwill now begin.");
    SoundEffect_PlayStream(3, "SS_T_00_041_M00");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    SoundEffect_PlayStream(2, "SS_T_00_244_S00");
    Voice_PlayVoice("P2308000_W00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Broadcaster", "Hanegasaki Academy's school play is\nover.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(*Phew* I'm glad that it finished\nwithout any problems...)");
    SoundEffect_StopStream(2, 60);
    Voice_PlayVoice("P2308000_H00200", 8, "");
    Message_Who(8);
    Message_MsgDisp("？？？", "Yo, ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh... Ah, ｛Masaki＊＊｝!\nWhy are you here!?\nDid you watch the play?");
    Character_ChFace(0, 0, 10);
    Character_Chara_GS2(8, "M8_??F", 0);
    Voice_PlayVoice("P2308000_H00300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah, I watched it.\nIt was interesting, your passionate\nacting.");
    Message_Who(0);
    Message_MsgDisp("主人公", "That is a compliment, right...?");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(8, 2, (#1));
    Voice_PlayVoice("P2308000_H00400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Haha, yeah. Anyway, you got time?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.\nI have nothing else planned for\ntoday.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("P2308000_H00500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I see.\nWanna go around the school then?");
    Character_BlinkStart(8, 3, (#1));
    Voice_PlayVoice("P2308000_H00600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I'm hungry...\nAnd if it's something cheap, I'll\ntreat you to it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha. Then shall we go?");
    Character_BlinkStart(8, 0, (#1));
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("P2308000_H00700", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "You were pulled in by the food,\nweren't you?\nYou really do love your food.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("P2308000_H00800", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Whatever, let's go!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(8, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(8, 2, (#1));
    Character_ChFace(0, 3, 2);
    Character_Chara_GS2(8, "M8_??F", 0);
    Background_Bg_GS2("BG_SC230_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("P2308000_W00900", #1, "");
    Message_Who(0);
    Message_MsgDisp("Male Student A", "Hey, that's...");
    Voice_PlayVoice("P2308000_W01000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Male Student B", "Who's that guy...");
    Character_BlinkStart(8, 3, (#1));
    Voice_PlayVoice("P2308000_H01100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "...\nI've got the feeling that people are\nstaring at me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah... I wonder why.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(8, 2, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("P2308000_H01200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... Well, I do stand out.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? How so?");
    Character_BlinkStart(8, 3, (#1));
    Voice_PlayVoice("P2308000_H01300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I'm a plain-clothed guy walking\naround, right?\nWith you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... And what of it...?");
    Character_BlinkStart(8, 0, (#1));
    Voice_PlayVoice("P2308000_H01400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Anyway, let's think of a way so that\nI don't stand out...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("P2308000_H01500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... Oh! Wait a sec.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Masaki＊＊｝!?");
    SoundEffect_PlayStream(2, "SS_DSE_060_000");
    Character_Chara_GS2(8, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He left...)");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He hasn't come back...\nI wonder what ｛Masaki＊＊｝\nis doing...)");
    Voice_PlayVoice("", 8, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Masaki＊＊｝, you took your\ntime...\nAh!");
    Music_PlayBGM(0, "MN_C_08_001_D00", 127, 40);
    Still_Event("EV_08_13", #1, 0, 60);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Masaki＊＊｝... Uniform...!");
    Voice_PlayVoice("P2308000_H01600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah, how is it?\nI still look good in it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Why do you have t-that?");
    Voice_PlayVoice("P2308000_H01700", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "It was on exhibit at a classroom\nnear the end.\nThe title, of course is...!");
    Voice_PlayVoice("P2308000_H01800", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "\"I'm borrowing the age and uniform\nfrom the time I was a dreamer!\nYou will also feel like a student\nwith this!\"");
    Message_Who(0);
    Message_MsgDisp("主人公", "Was there ever such an exhibit...\nHuh?\nIf you look closely, it seems a\nlittle different...");
    Still_Approach(8, 221, 0, 0, 1, 1);
    Voice_PlayVoice("P2308000_H01900", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Even if it's a festival, I can't\nborrow the real thing.\nIt'd be bad.");
    Still_ApproachEnd();
    Voice_PlayVoice("P2308000_H02000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "If I generally looked like a\nHanegasaki student, it's okay!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, that's right.");
    Voice_PlayVoice("P2308000_H02100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "...\nWell, I wonder if by wearing this,\npeople would stop saying, \"Who the\nhell is that guy?\".");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Voice_PlayVoice("P2308000_H02200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Alright, let's go!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, okay.");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(8, 86, 1);
    Parameter_AddCh1Param(8, 61, 6);
    Parameter_AddCh1Param(8, 60, 3);
    Parameter_AddCh1Param(8, 62, #5);
    }
