section "p33_m5_000"{
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_bunka_jyu(0) == 1){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ugh～! I'm nervous...\nWhat should I do if I make a\nmistake?)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(5, "M5_16F", 0);
        Voice_PlayVoice("", 5, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝...\nYou've worked hard.");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("P2305000_E00000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Wow. What a stiff smile.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... You noticed?\nIt's stiffer than stiff.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("P2305000_E00100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "...\nIt's more of a smoothly stiff smile.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ahaha, what is that?");
        Voice_PlayVoice("P2305000_E00200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah, cute.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 3, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P2305000_E00300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Let's go with your natural smile.\nThat's your best one.");
        Voice_PlayVoice("P2301000_W00200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Broadcaster", "Hanegasaki Academy's school play\nwill now begin.");
        SoundEffect_PlayStream(3, "SS_T_00_041_M00");
        Character_BlinkStart(5, 0, (#1));
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("P2305000_E00500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Come on, let's go.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_Call_GS2("P34", "M5", 0);
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "(Thank gosh, I somehow made it\nthrough...)");
        Voice_PlayVoice("", 5, "P2305000_E00600");
        Message_Who(5);
        Message_MsgDisp("Chris", "｛主人公｝. Are you okay?");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(5, "M5_08F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, yeah.\nWhat about you,\n｛Chris＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P2305000_E00700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Perfect.");
        Voice_PlayVoice("P2305000_E00800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Although it was tough to get to this\npoint, it was fun.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 3, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P2305000_E00900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "This...\nalso seems like it'll become a good\nmemory....\nSince I'm with you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Chris＊＊｝...");
        Voice_PlayVoice("P2301000_W00800", #1, "");
        Message_Who(0);
        Message_MsgDisp("Broadcaster", "Hanegasaki Academy's school play\nwill now begin.");
        SoundEffect_PlayStream(3, "SS_T_00_041_M00");
        Character_BlinkStart(5, 0, (#1));
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("P2305000_E01100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ah, it's starting.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, yeah.\nLet's do our best until the very\nend.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_Call_GS2("P34", "M5", 10);
        }
    }
