section "p34_m1_010"{
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Music_PlayBGM(0, "MN_E_SC_931_D00", 127, 40);
    Screen_WipeIn(2);
    Voice_PlayVoice("P2401010_W00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Prince", "Your eyes are like the night sea.\nIt appears as though I am drawn in.\nWill you dance with me?");
    Voice_PlayVoice("P2401010_W00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Prince", "Why do you not answer?\nDo you dislike waltz? Or is it, I?");
    Voice_PlayVoice("P2401010_W00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Prince", "If not, then please!\nPlease let me escort you!");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Character_Chara_GS2(1, "M1_08F", 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Saeki＊＊｝!\nThe dance is starting now!");
    Voice_PlayVoice("P2401010_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Argh....");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He looks serious...\nDuring practice he acted like a\nstupid child, and made it a habit to\nharshly look down on me.)");
    Character_BlinkStart(1, 2, (#1));
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("P2401010_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It's cruel.\nNot being able to listen to the\nmermaid princess speak...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yeah... You're right.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(What's wrong with him?\n｛Saeki＊＊｝ isn't acting\nlike his usual self...)");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(1, 0, (#1));
    Voice_PlayVoice("P2401010_A00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Hey... This mermaid story.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_BlinkStart(1, 3, (#1));
    Voice_PlayVoice("P2401010_A00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Why is it only a sad tale?\nThere is one person who could be a\nhappy mermaid, if she wished.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so...?");
    Voice_PlayVoice("P2401010_A00700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "If you are the mermaid for the\nmoment...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Mermaid for the moment?");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(1, 0, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("P2401010_A00800", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Eh? Oh, it's nothing....");
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("P2401010_A00900", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "If you are the mermaid princess, the\nworld is quieter and saved.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Just as usual,\n｛Saeki＊＊｝...)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    }
