section "p34_m2_000"{
    Screen_WipeIn(2);
    Still_Event("EV_02_14", #1, 0, 60);
    Music_PlayBGM(0, "MN_E_SC_932_D00", 127, 40);
    Voice_PlayVoice("P2402000_B00000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Please don't give up, Princess!");
    Message_Who(0);
    Message_MsgDisp("主人公", "I cannot go on anymore.\nEven with just you...!");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("P2402000_B00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nNo matter how many times you ask, I\nwill not listen to those words.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Be that as it may...!");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("P2402000_B00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Princess.");
    Message_Who(2);
    Message_MsgDisp("Shiba", ".........");
    Still_Approach(2, 42, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(... Huh? Was there a pause here?)");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("P2402000_B00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "............ Princess.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yes!");
    Voice_PlayVoice("P2402000_B00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "You are worried about me, even\nthough I am under suspicion of\nplotting to seize power and refuse\nto run away.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("P2402000_B00600", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "You are the one that has reached out\nto me as I was hiding my lineage...\nAnd living a miserable life as a\nwandering samurai.");
    Voice_PlayVoice("P2402000_B00700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "I've been waiting......\nTo serve as a samurai, again.");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("P2402000_B00800", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Do you not know of just how much\nyour words have saved me?");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("P2402000_B00900", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nIt freed me from the darkness when I\nhad given up...\nI am grateful...\nfrom the bottom of my heart...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Eh? What line is that?\nAnd he directly referred to\nhimself...)");
    Voice_PlayVoice("P2402000_B01000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "!");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 2, 2);
    Voice_PlayVoice("P2402000_B01100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nI will protect you, Princess, even\nif it costs me my life.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("P2402000_B01200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Let us escape from here....\nTogether.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Okay.\nI will not give up, either.\nAs long as you are here...!");
    SoundEffect_PlayStream(2, "SS_T_00_156_S00");
    Still_Event("");
    Message_CloseMsg();
    Screen_WipeOut(2);
    System_Wait(30);
    Music_StopBGM(0, 60);
    SoundEffect_StopStream(2, 60);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Shiba＊＊｝ was more\nserious than when we were\npracticing...\nI was a little surprised.)");
    Message_CloseMsg();
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 86, 1);
    Parameter_AddCh1Param(2, 61, 6);
    Parameter_AddCh1Param(2, 60, 3);
    Parameter_AddCh1Param(2, 62, #5);
    }
