section "p34_m1_000"{
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Character_Chara_GS2(1, "M1_16F", 0);
    Background_Bg_GS2("BG_SC931_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_E_SC_931_D00", 127, 40);
    Voice_PlayVoice("P2401000_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Your eyes are like the night sea.\nIt appears as if I am drawn in.\nWill you dance with me?");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Wah...\nThat costume suits\n｛Saeki＊＊｝ very well.\nHe's like a real actor.)");
    Character_BlinkStart(1, 2, (#1));
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("P2401000_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Why do you not answer?\nDo you dislike waltz? Or is it, I?");
    Message_Who(0);
    Message_MsgDisp("主人公", "(\"No\".\nMy neck seems to hurt when I shake\nmy head...)");
    Character_BlinkStart(1, 2, (#1));
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("P2401000_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "If not, then please!\nPlease let me escort you!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's hard not to say anything...\nThe mermaid princess can't speak.\nIt surely is heartwrenching...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("EV_01_14", #1, 0, 20);
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 2);
    Still_StillFace(0, 7, 1);
    Screen_WipeIn(2);
    Voice_PlayVoice("P2401000_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", ".........");
    Still_Approach(1, 12, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh?\nWhat's wrong with\n｛Saeki＊＊｝?\nHe seems nervous all of a sudden.)");
    Still_ApproachEnd();
    Still_StillFace(0, 7, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Hey, are you nervous?");
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("P2401000_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "W-Well...");
    Message_Who(0);
    Message_MsgDisp("主人公", "That's rare... Ouch!\nYou stepped on my foot,\n｛Saeki＊＊｝.");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("P2401000_A00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It can't be helped.\nEven though it says waltz, I will\nsimply never be able to do it.");
    Still_Approach(1, 12, 0, 0, 1, 5);
    Message_Who(0);
    Message_MsgDisp("主人公", "Nevertheless, you're a prince for\nthe mome-- Ouch!\nDid you step on my foot, again?");
    Still_ApproachEnd();
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("P2401000_A00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It's wrong for the mermaid to not be\nable to get around.\nNo, return to the sea, quickly!");
    Message_Who(0);
    Message_MsgDisp("主人公", "How awful...");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("P2401000_A00700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "... I'm sorry.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("P2401000_A00800", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ever since I was a child I've had no\nsense of rhythm...\nFolk dancing is my limit.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("P2401000_A00900", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Therefore, I wanted to decline the\nrole of the prince because I knew\nI'd have to dance, but...");
    Message_Who(0);
    Message_MsgDisp("主人公", "...?");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("P2401000_A01000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It can't be helped.\nYou were chosen to be the mermaid\nprincess.");
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("P2401000_A01100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I get angry when I think of you\ndancing with other guys...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Saeki＊＊｝...)");
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("P2401000_A01200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I'm sorry... I'll fix my mood.");
    Message_Who(0);
    Message_MsgDisp("主人公", "*Giggles*");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("P2401000_A01300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "... What is it?");
    Message_Who(0);
    Message_MsgDisp("主人公", "You are quite jealous, aren't you,\n｛Saeki＊＊｝?");
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("P2401000_A01400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "What do you mean!\nI'm not like--");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ouch! Stepped on my foot, again!");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("P2401000_A01500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "That time it was on purpose.");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    Parameter_AddCh1Param(1, 61, 6);
    Parameter_AddCh1Param(1, 60, 3);
    Parameter_AddCh1Param(1, 62, #5);
    }
