section "p34_m6_010"{
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_B_SC_930_600", 127, 40);
    Voice_PlayVoice("P2406010_W00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Hikaru Genji", "Lady Fujitsubo...\nPlease, please come with me!");
    Voice_PlayVoice("P2406010_W00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Bushitsubo", "... No. That cannot be done.");
    Voice_PlayVoice("P2406010_W00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Hikaru Genji", "Why!?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Character_Chara_GS2(6, "M6_08F", 0);
    Voice_PlayVoice("P2406010_F00300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "You are free, lady consort.\nWhat will you do? Tell me...");
    Message_Who(0);
    Message_MsgDisp("主人公", "I cannot tell you.");
    Voice_PlayVoice("P2406010_F00400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I should run as a canditate against\nGenji.\nI would absolutely make a better\nperformance.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("P2406010_F00500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Because of that, Senpai's the court\nlady, Fujitsubo.\nYes, the role is perfect.");
    Voice_PlayVoice("P2406010_F00600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Do you remember the next lines?\n\"You ought to have known some time\nago, our thoughts work as one...\"");
    Voice_PlayVoice("P2406010_F00700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "\"Would this be a lie?\"");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh, I do remember.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(6, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("P2406010_F00800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I practiced, but it shows terribly.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Well then, that goes for me, as\nwell.\n\"No, that isn't a lie by any means.\"");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("P2406010_F00900", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Yes, that's correct.\nI'm surprised you remembered,\nSenpai.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Too many words!\nCan you remember the next lines?\n\"Genji...\nYou--\"");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("P2406010_F01000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Stop!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?");
    Message_Who(0);
    Message_MsgDisp("主人公", "W-What's wrong?\nYou suddenly yelled...");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("P2406010_F01100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "............");
    Voice_PlayVoice("P2406010_W01200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Bushitsubo", "Genji... You are young.\nThe world is more different than\nthat, you'll still be young when I\ngrow old.");
    Voice_PlayVoice("P2406010_F01300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "...\nIt seems like you're saying that\nmore personally...");
    Message_Who(0);
    Message_MsgDisp("主人公", "... ｛Amachi＊＊｝?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("P2406010_F01400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Nothing!\nAnyway, it's time to prepare for the\nnext act.\nHey, let's go!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh, okay...");
    Character_Chara_GS2(6, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(What's wrong with you,\n｛Amachi＊＊｝?)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(6, 86, 1);
    }
