section "p34_m5_000"{
    Screen_WipeOut(2);
    Still_Event("EV_05_14", #1, 0, 20);
    Still_StillFace(0, 0, 1);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_E_SC_935_D00", 127, 40);
    Voice_PlayVoice("P2405000_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "If you enter that door, in front of\nyou will be your village.");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("P2405000_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "And the moment the door closes...\nWe will be separated for eternity.");
    Message_Who(0);
    Message_MsgDisp("主人公", "For eternity? ... That's...");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("P2405000_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Hearing that it will be for\neternity, you don't want to leave\nnow?");
    Message_Who(0);
    Message_MsgDisp("主人公", ".........");
    Voice_PlayVoice("P2405000_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Even if you think that for a moment,\nit is just a brief feeling of\n\"sympathy\".");
    Voice_PlayVoice("P2405000_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "If you stay and become a vampire,\nyou will surely regret it.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("P2405000_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Using humans to prolong your own\nlife, can you handle that truth?");
    Message_Who(0);
    Message_MsgDisp("主人公", "T-That's...");
    Still_StillFace(0, 6, 0);
    Still_Approach(5, 132, 0, 0, 1, 1);
    Voice_PlayVoice("P2405000_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "You are too kind to live as a part\nof my family.");
    Still_ApproachEnd();
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("P2405000_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nIf bestowing my family name on you\nwould make you lose your shine, then\nwe don't need that kinda thing.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh...)");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("P2405000_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "If you couldn't be the way you are\nnow, then there's no meaning to\nit...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Chris＊＊｝, the lines\nare wrong...!)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Background_Bg_GS2("BG_SC935_LI_0", #1, #1, 0);
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(5, 2, (#1));
    Character_Chara_GS2(5, "M5_16F", 0);
    Screen_WipeIn(2);
    System_Wait(20);
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(5, 0, (#1));
    Voice_PlayVoice("P2405000_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "But you know?\nEven if we got separated, you'll\nstay in my memories.");
    Character_BlinkStart(5, 2, (#1));
    Voice_PlayVoice("P2405000_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "So...\neven though we might not be able to\nsee each other again, I don't want\nyou to forget.");
    Character_BlinkStart(5, 3, (#1));
    Voice_PlayVoice("P2405000_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "The fact that I came here....\nThat you, who I was looking at...");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay, I won't forget. Never...\nNo, even if my flesh rots away, I\nwon't forget.");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("P2405000_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... So, let's go.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Goodbye... Goodbye, Count...!");
    SoundEffect_PlayStream(2, "SS_T_00_156_S00");
    System_Wait(30);
    Music_StopBGM(0, 60);
    SoundEffect_StopStream(2, 60);
    Message_CloseMsg();
    Screen_WipeOut(2);
    System_Wait(80);
    Character_Chara_GS2(5, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(The lines were different, but the\nstory was still basically the same,\nso it's okay...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(But ｛Chris＊＊｝ really\nlooked sad...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    Parameter_AddCh1Param(5, 61, 6);
    Parameter_AddCh1Param(5, 60, 3);
    Parameter_AddCh1Param(5, 62, #5);
    }
