section "p53_m3_000"{
    int var0 = 0;
    if (Parameter_GetPl1Param(322) == 0){
        Background_Bg_GS2("BG_SC950_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(3, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(There is only a bit of work to go\nbefore the display!\nMy heart is racing.)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝. You came.");
            Voice_PlayVoice("P5303000_C00000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Yes, I'm making rounds for patrol\nduty.\nIt's the job as a student council\nexecutive since we are in charge the\nCulture Festival.");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("P5303000_C00100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Few people here, my check will be\neasy....\nThe Art Club's display is in exhibit\nformat.\nI heard it was a portrait, correct?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, the oil painting was modeled by\nHimeko-senpai.\nShe herself will display it, after\nthis!");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(3, 2, (#1));
            Voice_PlayVoice("P5303000_C00200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Is that so?\nHanatsubaki-san will be coming.\nThat being the case, the display\nshould advance without delay.\nLet's go look.");
            }
        else if (Parameter_GetCh1Param(3, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(There is only a bit of work to go\nbefore the display!\nMy heart is racing.)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝. You came.");
            Voice_PlayVoice("P5303000_C00300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I'm making my rounds on patrol duty.\nIt's the job as a student council\nexecutive since we are in charge the\nCulture Festival.");
            Character_BlinkStart(3, 3, (#1));
            Voice_PlayVoice("P5303000_C00400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "However, thanks to that, even if I\nam here, people won't be suspicious\nof me...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            Character_ChFace(0, 0, 11);
            Character_BlinkStart(3, 2, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P5303000_C00500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Well, umm...\nI'm talking to myself....\nI hear that you have work here.\nI would like to go see it.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, it will begin after this.\nHimeko-senpai, the model herself,\nwill display the oil painting.");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(3, 2, (#1));
            Voice_PlayVoice("P5303000_C00600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Is that so? I'm a little nervous....\nI will watch from here.");
            }
        Character_Chara_GS2(3, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Screen_WipeIn(2);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        var0 = 54 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(34, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else if (Parameter_GetPl1Param(322) == 1){
        Background_Bg_GS2("BG_SC950_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(3, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(I want various people to see the\nwork everyone made.)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝. You came.");
            Voice_PlayVoice("P5303000_C00700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Yes, I saw you guiding a guest to\nthis floor.\nI took the opportunity to drop by.");
            Character_ChFace(0, 2, 3);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("P5303000_C00800", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It seems fairly crowded....\nI hear that the Art Club made a\npiece of artwork.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, we created a plaster figured\nmermaid together.\nIt will be displayed, after this!");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(3, 2, (#1));
            Voice_PlayVoice("P5303000_C00900", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "A mermaid...\nI wonder what kind, let us go take a\nlook.");
            }
        else if (Parameter_GetCh1Param(3, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(I want various people to see the\nwork everyone made.)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝. You came.");
            Voice_PlayVoice("P5303000_C01000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "...\nYes, guiding guests here is the job\nof the executive.\nThe last hall is a shortcut to the\nmain office.");
            Character_ChFace(0, 4, 0);
            Character_BlinkStart(3, 3, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5303000_C01100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I got to see you in time. Good...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            Character_ChFace(0, 0, 11);
            Character_BlinkStart(3, 2, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P5303000_C01200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Well, umm... I'm talking to myself.\nI hear that a plaster figure of a\nmermaid was created.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, it will be displayed, after\nthis!");
            Character_ChFace(0, 4, 0);
            Character_ChFace(0, 2, 5);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5303000_C01300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "You worked on it, as well?\nIn that case, I will go have a look.");
            }
        Character_Chara_GS2(3, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Screen_WipeIn(2);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        var0 = 54 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(35, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else {
        Background_Bg_GS2("BG_SC950_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(3, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow, I'm amazed.\nA lot of guests coming.)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝. You came.");
            Voice_PlayVoice("P5303000_C01400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I'm astonished.\nSo many people gathered here.\nHow did this come about?");
            Message_Who(0);
            Message_MsgDisp("主人公", "There is an epic mural this year.\nA masterpiece by all of the members.");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(3, 2, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P5303000_C01500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Is that so...");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("P5303000_C01600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "As an executive, I will make my\nrounds to check and make sure people\nare gathered to take a look at the\ndisplay.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I'm in the middle of work,\n｛Hikami＊＊｝.");
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5303000_C01700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Alright.\nHowever, I am interested in the part\nthat you painted.\nI'm looking forward to the display.");
            }
        else if (Parameter_GetCh1Param(3, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow, I'm amazed.\nA lot of guests coming.)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Hikami＊＊｝. You came.");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(3, 2, (#1));
            Voice_PlayVoice("P5303000_C01800", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Yes, you too...\nWell, I heard the Art Club worked\nhard to prepare for this.");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P5303000_C01900", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Since I am making my rounds on\npatrol duty, I had a little time to\nvisit.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Thank you.\nJust a little more before the\ndisplay of the \"Hanegasaki Legend\".");
            Character_ChFace(0, 4, 0);
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(3, 2, (#1));
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("P5303000_C02000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Is that the title of the mural...?\nThe name holds much expectation.\nLet us go have a look while I'm in\ncharge.");
            Message_Who(0);
            Message_MsgDisp("主人公", "...\nOh, the presentation is starting!\nYou can see it from here,\n｛Hikami＊＊｝.");
            }
        Character_Chara_GS2(3, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Screen_WipeIn(2);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        var0 = 54 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(36, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    System_Call_GS2("P54", "M3", 0);
    }
