section "p53_s1_000"{
    int var0 = 0;
    Background_Bg_GS2("BG_SC950_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetPl1Param(322) == 0){
        Message_Who(0);
        Message_MsgDisp("主人公", "(There is only a bit of work to go\nbefore the display!\nMy heart is racing.)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(14, "S1_04F", 0);
        Music_PlayBGM(0, "MN_C_14_000_D00", 127, 40);
        Voice_PlayVoice("P5314000_N00000", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "Sis.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, Yuu-kun!");
        Voice_PlayVoice("P5314000_N00100", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "I came to look at Sis's painting.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Thank you!\nBut do you understand artwork,\nYuu-kun?");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("P5314000_N00200", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "Yes, but don't make fun of me\nbecause I'm a child.\nI have quite good taste.");
        Message_Who(0);
        Message_MsgDisp("主人公", "*Giggles* I'm sorry, I'm sorry.\nThe display will be starting soon.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("P5314000_N00300", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "Well then, do your best!\nI'm looking forward to it.");
        Character_Chara_GS2(14, "NON");
        Message_CloseMsg();
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        var0 = 54 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(34, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else if (Parameter_GetPl1Param(322) == 1){
        Message_Who(0);
        Message_MsgDisp("主人公", "(I want various people to see the\nwork everyone made.)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(14, "S1_04F", 0);
        Music_PlayBGM(0, "MN_C_14_000_D00", 127, 40);
        Voice_PlayVoice("P5314000_N00400", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "Sis.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, Yuu-kun!");
        Voice_PlayVoice("P5314000_N00500", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "I came to look at Sis's display.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Thank you!\nThis year's a collaboration.");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("P5314000_N00600", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "What a disaster...\nWell, I don't know where to look for\nwhat you made.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("P5314000_N00700", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "... Ah! Sis, you're being called.\nIt'll start soon!");
        Character_Chara_GS2(14, "NON");
        Message_CloseMsg();
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        var0 = 54 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(35, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "(Wow, I'm amazed.\nA lot of guests are coming.)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(14, "S1_04F", 0);
        Music_PlayBGM(0, "MN_C_14_000_D00", 127, 40);
        Voice_PlayVoice("P5314000_N00800", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "Yo! I came to look, Sis.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, Yuu-kun!");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(14, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P5314000_N00900", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "Is this year a mural or anything?\nI should yell out how amazing it is.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Thank you!\nThere are quite a few people here,\nso be careful.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("P5314000_N01000", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "I'll be safe... I'm not a child.\nAh, it seems like it's starting\nsoon!");
        Character_Chara_GS2(14, "NON");
        Message_CloseMsg();
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        var0 = 54 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(36, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    System_Call_GS2("P54", "S1", 0);
    }
