section "p53_m7_000"{
    int var0 = 0;
    if (Parameter_GetPl1Param(322) == 0){
        Background_Bg_GS2("BG_SC950_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(7, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(There is only a bit of work to go\nbefore the display!\nMy heart is racing.)");
            Voice_PlayVoice("", 7, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(7, "M7_17F", 0);
            Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝.\nAre you here on inspection?");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5307000_G00000", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "I'm not, actually.\nI will be a salesman today.\nWould you also like to become one of\nmy customers?");
            Message_Who(0);
            Message_MsgDisp("主人公", "... I can't yet.\nIt's almost time for the\npresentation.");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P5307000_G00100", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Is that so...");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(7, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5307000_G00200", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Then how about this proposition.\nI will go and watch your\npresentation, but you have to come\nto the classroom afterwards.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Mmm... I see. Then please watch it!");
            }
        else if (Parameter_GetCh1Param(7, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(There is only a bit of work to go\nbefore the display!\nMy heart is racing.)");
            Voice_PlayVoice("", 7, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝.");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(7, 2, (#1));
            Character_ChFace(0, 4, 1);
            Character_Chara_GS2(7, "M7_17F", 0);
            Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝! You came.");
            Voice_PlayVoice("P5307000_G00300", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Yeah, I wanted to see what kind of\npainting you painted.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ooh, thank you!\nThe presentation is very soon.");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P5307000_G00400", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "It's very good that I came.\nI'm looking forward to it.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Haha, please relax!");
            }
        Character_Chara_GS2(7, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Screen_WipeIn(2);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        var0 = 54 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(34, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else if (Parameter_GetPl1Param(322) == 1){
        Background_Bg_GS2("BG_SC950_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(7, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(I want various people to see the\nwork everyone made.)");
            Voice_PlayVoice("", 7, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(7, "M7_17F", 0);
            Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝.\nAre you here on inspection?");
            Voice_PlayVoice("P5307000_G00500", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "What do I have to do?");
            Message_Who(0);
            Message_MsgDisp("主人公", "What... Are you puzzled?");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5307000_G00600", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Sensei is in charge of collecting\nthe visitors.\nThough, he wants a young woman like\nyou to come.");
            Message_Who(0);
            Message_MsgDisp("主人公", "...\nThen, I'll go if you watch the Art\nClub's presentation.");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5307000_G00700", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Alright. End of the negotiations.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, the end....\nWell, please take your seat.\nThe presentation will start soon.");
            }
        else if (Parameter_GetCh1Param(7, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(I want various people to see the\nwork everyone made.)");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 4, 1);
            Character_Chara_GS2(7, "M7_17F", 0);
            Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
            Voice_PlayVoice("", 7, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝. You came.");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P5307000_G00800", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Yeah, I heard the Art Club created\nsome amazing things.\nDid you also make something?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes!\nI cooperated with everyone and\ncreated the legendary mermaid.");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5307000_G00900", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "...\nExcellent, \"cooperated with\neveryone\".\nSounds like it became fun.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, the presentation starts soon!\nCome now, please get to your seat.");
            }
        Character_Chara_GS2(7, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Screen_WipeIn(2);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        var0 = 54 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(35, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else {
        Background_Bg_GS2("BG_SC950_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(7, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow, I'm surprised.\nA lot of visitors came.)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(7, "M7_17F", 0);
            Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
            Voice_PlayVoice("", 7, "P5307000_G01000");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝.\nThe Art Club did very well.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝.\nAre you here on inspection?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(7, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5307000_G01100", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Buzzzz, wrong.\nI went to go get visitors for the\npresentation.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Not good～!\nIt's the 3rd year and I barely\ngathered the little I saw...");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(7, 3, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5307000_G01200", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "You had a hard time, too.");
            Message_Who(0);
            Message_MsgDisp("主人公", "That's right.\nWill Sensei also watch the\npresentation soon?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(7, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5307000_G01300", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "... I see, very well.\nOn the other hand, I have to finish\ngetting visitors.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I'll leave it to you. Now, please!");
            Character_Chara_GS2(7, "NON");
            }
        else if (Parameter_GetCh1Param(7, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Good! A lot of visitors came!)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(7, "M7_17F", 0);
            Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
            Voice_PlayVoice("", 7, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝! You came.");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(7, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5307000_G01400", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Yeah, I heard the Art Club made a\nlegend this year.\nIs it the legend of fast eating?\nThe legend of detention?");
            Message_Who(0);
            Message_MsgDisp("主人公", "It wasn't that kind of legend.\nIt was a mural made about\nHanegasaki's mermaid legend.");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5307000_G01500", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Ooh, that legend!\nI didn't think it was that.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Though, I don't think...)");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(7, 2, (#1));
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P5307000_G01600", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "...\nI certainly considered coming to\nwatch the presentation.\nI'll look forward to waiting in my\nseat.");
            Character_Chara_GS2(7, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh?\nI wonder why ｛Wakaouji＊＊｝\nhad to consider...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ah, the presentation is about to\nbegin!)");
            }
        if ((Parameter_GetCh1Param(7, 130) < 4) && (Parameter_GetPl1Param(322) != 2)){
            Character_Chara_GS2(7, "NON");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Screen_WipeIn(2);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        var0 = 54 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(36, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    System_Call_GS2("P54", "M7", 0);
    }
