section "p53_m4_000"{
    int var0 = 0;
    if (Parameter_GetPl1Param(322) == 0){
        Background_Bg_GS2("BG_SC950_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(4, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(There's only a little while left\nuntil we unveil our work!\nMy heart is racing!)");
            Voice_PlayVoice("P5304000_D00000", #1, "");
            Message_Who(4);
            Message_MsgDisp("？？？", "Yo.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(4, "M4_17F", 0);
            Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Hariya＊＊｝!\nSo you came.");
            Voice_PlayVoice("P5304000_D00100", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Yeah.\nJust as I thought, you don't look\nbusy.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5304000_D00200", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "If I didn't come, you wouldn't have\nanything to do, would you?");
            Message_Who(0);
            Message_MsgDisp("主人公", "T-That's not true!\nActually, I am about to unveil my\nwork!");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P5304000_D00300", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Your work?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah. Go look at it!");
            }
        else if (Parameter_GetCh1Param(4, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(There's only a little while left\nuntil we unveil our work!\nMy heart is racing!)");
            Voice_PlayVoice("P5304000_D00400", #1, "");
            Message_Who(4);
            Message_MsgDisp("？？？", "Yo.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(4, "M4_17F", 0);
            Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Hariya＊＊｝!\nSo you came.");
            Character_ChFace(0, 2, 3);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("P5304000_D00500", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "I came here because I heard\nsomething was going on.");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P5304000_D00600", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "But it's empty. Just as I thought.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah...\nThere aren't that many people coming\nin here...");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P5304000_D00700", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Well, isn't this perfect for being\nable to talk about art?");
            Character_ChFace(0, 0, 6);
            Voice_PlayVoice("P5304000_D00800", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "...\nI can also have a nice chat with\nyou.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            Character_ChFace(0, 0, 11);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P5304000_D00900", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Ah, hey, someone's coming in.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, you're right. I'll go for a bit.");
            }
        Character_Chara_GS2(4, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Screen_WipeIn(2);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        var0 = 54 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(34, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else if (Parameter_GetPl1Param(322) == 1){
        Background_Bg_GS2("BG_SC950_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(4, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(I want many people to see the work\nthat we created together.)");
            Voice_PlayVoice("", 4, "");
            Message_Who(4);
            Message_MsgDisp("？？？", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(4, "M4_01F", 0);
            Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Hariya＊＊｝! So you came.");
            Voice_PlayVoice("P5304000_D01000", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Don't take a break!\nThere are quite a few people in\nhere.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder if it's because I'm about\nto unveil my artwork.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P5304000_D01100", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "So the Art Club runs such playful\nevents.\nHow sly～.");
            Message_Who(0);
            Message_MsgDisp("主人公", "We're not being sly!");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(4, 3, (#1));
            Voice_PlayVoice("P5304000_D01200", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Hahaha!");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P5304000_D01300", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Ah, hey. They're calling you.");
            Message_Who(0);
            Message_MsgDisp("主人公", "You're right, it's probably about\ntime.\nI'll go!");
            }
        else if (Parameter_GetCh1Param(4, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(I want many people to see the work\nthat we created together.)");
            Voice_PlayVoice("", 4, "");
            Message_Who(4);
            Message_MsgDisp("？？？", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(4, "M4_01F", 0);
            Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Hariya＊＊｝! So you came.");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P5304000_D01400", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Huh...\nThere are tons of people\nhere.........");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah.\nI'm glad, because I'm about to\nunveil my artwork.");
            Character_ChFace(0, 0, 9);
            Character_BlinkStart(4, 3, (#1));
            Voice_PlayVoice("P5304000_D01500", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "............");
            Message_Who(0);
            Message_MsgDisp("主人公", "What's wrong, ｛Hariya＊＊｝?");
            Character_ChFace(0, 0, 0);
            Character_BlinkStart(4, 2, (#1));
            Voice_PlayVoice("P5304000_D01600", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Nothing.\nI just didn't think it'd be like\nthis...\nThat's all.");
            Message_Who(0);
            Message_MsgDisp("主人公", "You didn't...?\nAh, sorry, I have to go for a bit.");
            }
        Character_Chara_GS2(4, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Screen_WipeIn(2);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        var0 = 54 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(35, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else {
        Background_Bg_GS2("BG_SC950_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(4, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow, how surprising.\nA lot of guests came.)");
            Voice_PlayVoice("P5304000_D01700", #1, "");
            Message_Who(4);
            Message_MsgDisp("？？？", "Yo.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(4, "M4_01F", 0);
            Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Hariya＊＊｝!");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P5304000_D01800", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Ack, what's this?\nThe Art Club have gotten more many\npeople here than the live.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("P5304000_D01900", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "I'm saying that I'll force people\nhere by saying \"Please come and look\nat the murals\".");
            Character_ChFace(0, 0, 3);
            Character_BlinkStart(4, 2, (#1));
            Voice_PlayVoice("P5304000_D02000", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "I mean they're always on display,\nright?\nI'll get more people here, so just\nwait.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, wait, ｛Hariya＊＊｝!\nI'm just about to unveil my artwork!");
            Character_ChFace(0, 0, 11);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P5304000_D02100", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "For real? ...\nI'll tell them to hurry.");
            }
        else if (Parameter_GetCh1Param(4, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow, how surprising.\nA lot of guests came.)");
            Voice_PlayVoice("P5304000_D02200", #1, "");
            Message_Who(4);
            Message_MsgDisp("？？？", "Yo.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(4, "M4_01F", 0);
            Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Hariya＊＊｝!");
            Character_ChFace(0, 0, 9);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P5304000_D02300", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "This crowd...\nDid I come before the unveiling of\nthe mural?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah, it's about to start.");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("P5304000_D02400", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "I got the timing wrong...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?\nYou came at just the right time,\nthough.");
            Character_ChFace(0, 0, 8);
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P5304000_D02500", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "............");
            Message_Who(0);
            Message_MsgDisp("主人公", "W-What?");
            Character_ChFace(0, 0, 8);
            Character_BlinkStart(4, 2, (#1));
            Voice_PlayVoice("P5304000_D02600", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Nothing.\nIt looks like you're being called,\nwhy don't you go?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh? Ah, you're right. I'm going!");
            }
        Character_Chara_GS2(4, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Screen_WipeIn(2);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        var0 = 54 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(36, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    System_Call_GS2("P54", "M4", 0);
    }
