section "p63_m5_000"{
    int var0 = 0;
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetPl1Param(322) == 0){
        if (Parameter_GetCh1Param(5, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow, there are a lot of visitors!)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(5, "M5_01F", 0);
            Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
            Voice_PlayVoice("P6305000_E00000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Hello.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝.\nDid you come to here listen?");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P6305000_E00100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah. You look real happy.");
            Voice_PlayVoice("P6305000_E00200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "It's a face that only people who\nworked hard practicing could make.\nI'm expecting great things.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Okay!");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P6305000_E00300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Now then, good luck～.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Thanks, ｛Chris＊＊｝.");
            Character_Chara_GS2(5, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Chris＊＊｝ is watching,\nas well.\nAlright, I must do my best!)");
            }
        else if (Parameter_GetCh1Param(5, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow, there are a lot of visitors!)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(5, "M5_01F", 0);
            Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
            Voice_PlayVoice("P6305000_E00400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Hello.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝.\nDid you come to here listen?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P6305000_E00500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Of course!\nIf I don't watch this, I'll regeret\nit for the rest of my life.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Haha, you're exaggerating,\n｛Chris＊＊｝.");
            Character_BlinkStart(5, 3, (#1));
            Voice_PlayVoice("P6305000_E00600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "It's not something to exaggerate....\nI'm very glad to be able to see\nthis.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Chris＊＊｝...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_BlinkStart(5, 0, (#1));
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P6305000_E00700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I'll be watching from the audience\nseat, so show me something cool～.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Okay, I'll do my best!");
            Character_Chara_GS2(5, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Chris＊＊｝ also came to\ncheer me on.\nI have to do my best!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(37, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else if (Parameter_GetPl1Param(322) == 1){
        if (Parameter_GetCh1Param(5, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wah～, what should I do?\nI'm so nervous...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(5, "M5_01F", 0);
            Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
            Voice_PlayVoice("P6305000_E00800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "If you're that nervous you won't be\nable to do the things you can do.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝!");
            Voice_PlayVoice("P6305000_E00900", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Seeing you so nervous is precious.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... A joke?");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P6305000_E01000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah. Don't you think it was good?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Hmm, I wonder.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P6305000_E01100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "So it's still lacking.\nI'll work on it.\nNow then, good luck.");
            Character_Chara_GS2(5, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Haha, my nerves have calmed.\nAlright, I'll do my best!)");
            }
        else if (Parameter_GetCh1Param(5, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wah～, what should I do?\nI'm so nervous...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(5, "M5_01F", 0);
            Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
            Voice_PlayVoice("P6305000_E01200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Huh. You're nervous?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah, extremely...\nAh, ｛Chris＊＊｝!");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P6305000_E01300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "That's important.\nWhat would happen if you weren't\nnervous?");
            Voice_PlayVoice("P6305000_E01400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Don't they say to do that thing 3\ntimes?\nHmm, what was it...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Write the word \"person\" 3 times on\nyour hand.");
            Voice_PlayVoice("P6305000_E01500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah, that.\nHey, does that really get rid of\nyour nervousness?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Haha.\nYou were the one who told me to do\nit, ｛Chris＊＊｝.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 2, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P6305000_E01600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "You laughed.\nAs expected, I had to see it.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            Voice_PlayVoice("P6305000_E01700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Well, I'll see you again after.");
            Character_Chara_GS2(5, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(... Alright!\n｛Chris＊＊｝ is also\nwatching.\nI have to do my best!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(38, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else {
        if (Parameter_GetCh1Param(5, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wah～, what should I do?\nI'm so nervous...)");
            SoundEffect_PlayStream(3, "SS_T_00_281_M00");
            Message_Who(0);
            Message_MsgDisp("主人公", "Wah! Ah, ｛Chris＊＊｝!");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(5, "M5_01F", 0);
            Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
            Voice_PlayVoice("P6305000_E01800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "The neko damashi move!\nIt's a technique that sumo wrestlers\nuse.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Is that so...\nIt shocked me so much that my arms\nwent weak...");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P6305000_E01900", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Success～.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_BlinkStart(5, 0, (#1));
            Voice_PlayVoice("P6305000_E02000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Now then, I will be in the audience\nseat.\nGet into it, into it!");
            Message_Who(0);
            Message_MsgDisp("主人公", "Okay, thanks.");
            Character_Chara_GS2(5, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I feel more relaxed...\nProbably thanks to\n｛Chris＊＊｝.\nAlright, I'll do my best!)");
            }
        else if (Parameter_GetCh1Param(5, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "Wah～, what should I do!?\nI'm so nervous...");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 2, (#1));
            Character_ChFace(0, 3, 0);
            Character_Chara_GS2(5, "M5_01F", 0);
            Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
            Voice_PlayVoice("P6305000_E02100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... When you are, think of my face.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh? Ah, ｛Chris＊＊｝!");
            Voice_PlayVoice("P6305000_E02200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Seeing my face, you'll feel\ndejected.");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("P6305000_E02300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Ah, that might have the opposite\neffect.\nIt'd make your heart race, and\nexcessively nervous, right?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Geez, ｛Chris＊＊｝.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P6305000_E02400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Now then, I will be in the audience\nseat.\nGood luck～.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Okay! Thanks!");
            Character_Chara_GS2(5, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Alright, I'll do my best!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(39, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Character_Chara_GS2(5, "NON");
    System_Call_GS2("P64", "M5", 0);
    }
