section "p63_m3_000"{
    int var0 = 0;
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetPl1Param(322) == 0){
        if (Parameter_GetCh1Param(3, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～ What should I do!\nI'm so nervous...)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Voice_PlayVoice("P6303000_C00000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I dropped in on administration\nbusiness.\nThere is a public performance\nsoon....\nAre you nervous?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, a little...");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("P6303000_C00100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Real ability will be in the results.\nThe pressure on you will vanish as\nyou show your abilities.\nYou practiced well?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, thank you...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(3, 2, (#1));
            Voice_PlayVoice("P6303000_C00200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I will listen from here.\nNow, it is your turn.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Okay, I will do my best!)");
            Character_Chara_GS2(3, "NON");
            }
        else if (Parameter_GetCh1Param(3, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～! What should I do!\nI'm so nervous...)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝.");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P6303000_C00300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Aren't you leaving soon?\nAnyhow, I made it in time. Hmm? ...\nYou seem nervous.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, a little...");
            Character_ChFace(0, 4, 0);
            Character_ChFace(0, 2, 5);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P6303000_C00400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "You'll be fine, it will go smoothly.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh...?");
            Character_ChFace(0, 0, 6);
            Character_BlinkStart(3, 3, (#1));
            Voice_PlayVoice("P6303000_C00500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It isn't flattery. Well...\nI know you have been doing a lot of\npracticing, that was what I meant.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... Thank you.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P6303000_C00600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I will go to the seats in the\naudience....\nYou have my support.");
            Character_Chara_GS2(3, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(...\nThe weight on my shoulders seems to\nhave left.\nOkay, I will do my best!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(37, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else if (Parameter_GetPl1Param(322) == 1){
        if (Parameter_GetCh1Param(3, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ah～! What should I do!?\nMy heart is racing...)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Hikami＊＊｝.");
            Voice_PlayVoice("P6303000_C00700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I came to look from the stage wing\nas I guided a guest....\nWhat, are you nervous?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, a little...");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("P6303000_C00800", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "There is no person here who does not\nfeel nervous during this crucial\nmoment.\nDo not worry.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, thank you...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P6303000_C00900", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I will listen from here.\nNow, it is your turn.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Okay, I will do my best!)");
            Character_Chara_GS2(3, "NON");
            }
        else if (Parameter_GetCh1Param(3, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ah～! What should I do!?\nMy heart is pounding...)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 11);
            Character_BlinkStart(3, 2, (#1));
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝. You came.");
            Voice_PlayVoice("P6303000_C01000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Yes, it is the work of the\nexecutives.\nY-You will do fine on stage....\nYour complexion is a little strange.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, a little...");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(3, 2, (#1));
            Voice_PlayVoice("P6303000_C01100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "...\nYou did very much practicing, yes?\nThe performance will start in an\ninstant.\nYou should perform as you always do.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Okay, thank you...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_BlinkStart(3, 0, (#1));
            Voice_PlayVoice("P6303000_C01200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I will go to the seats with the\naudience.\nI believe this will be an enjoyable\nperformance.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes!\nThank you, ｛Hikami＊＊｝.");
            Character_Chara_GS2(3, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(The pounding has settled...\nOkay, I will do my best!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(38, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else {
        if (Parameter_GetCh1Param(3, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ah～, this isn't good!\nI'm getting nervous...!)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝.");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("P6303000_C01300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I came to return the parts the\nexecutives borrowed.\nI took the opportunity to drop in\nand take a look...\nYou look pale.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes...");
            Character_BlinkStart(3, 2, (#1));
            Voice_PlayVoice("P6303000_C01400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "The seatings are pitch black,\nanyway.\nYou will not be able to see anyone,\nso do not worry.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, you're right...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P6303000_C01500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I will listen from here.\nNow, it is your turn.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Okay, I will do my best!)");
            Character_Chara_GS2(3, "NON");
            }
        else if (Parameter_GetCh1Param(3, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ah～, this isn't good!\nI'm getting nervous...!)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝. You came.");
            Voice_PlayVoice("P6303000_C01600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Yes, you are performing...\nThe Culture Festival cannot come to\nan end until I hear the band\nperform.");
            Character_ChFace(0, 4, 0);
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(3, 2, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P6303000_C01700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "... What, are you nervous?\nYour complexion is a pale blue.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Y-Yes...");
            Character_BlinkStart(3, 0, (#1));
            Character_ChFace(0, 2, 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P6303000_C01800", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "...\nAt times when I make a mistake, I\nsing and play it off.\nGive it a try.\nAt a crucial moment in a confident\nloud voice.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?\n...*Giggles* It's okay to do things\nlike that.");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(3, 2, (#1));
            Voice_PlayVoice("P6303000_C01900", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "... Good, now back to my usual face.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 2, 5);
            Voice_PlayVoice("P6303000_C02000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I will go to my seat in the\naudience....\nI am expecting a nice musical\nperformance.");
            Character_Chara_GS2(3, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I feel a lot better thanks to\n｛Hikami＊＊｝...\nOkay, I will do my best!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(39, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Character_Chara_GS2(3, "NON");
    System_Call_GS2("P64", "M3", 0);
    }
