section "p64_s1_000"{
    if (Parameter_GetPl1Param(322) == 0){
        if (Parameter_bunka_jyu(0) == 1){
            System_Wait(60);
            Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
            Screen_WipeIn(2);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Good thing that went well!)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(14, "S1_04F", 0);
            Voice_PlayVoice("P6414000_N00000", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Sis, good job～.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yuu-kun!?\nWhat, you barged in here, again...");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P6414000_N00100", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "I know, I'm heading home soon.\nBut I wanted to say that it was\ngood.\nWell then, later～!");
            SoundEffect_PlayStream(3, "SS_T_00_095_M00");
            Character_Chara_GS2(14, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Really...\nWell, good thing it turned out\nwell.)");
            }
        else {
            System_Wait(60);
            Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
            Screen_WipeIn(2);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ah, massive failure...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(14, "S1_04F", 0);
            Voice_PlayVoice("P6414000_N00200", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Sis.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yuu-kun...\nDon't just come barging in here.");
            Voice_PlayVoice("P6414000_W00300", #1, "");
            Message_Who(0);
            Message_MsgDisp("Club President", "...\nMay I have a word with you for a\nminute?");
            Character_ChFace(0, 2, 3);
            Character_ChFace(0, 3, 2);
            Message_Who(0);
            Message_MsgDisp("主人公", "Ye-Yes...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(The club leader is really\nfurious...)");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("P6414000_N00400", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Woah～. Looks like you're busy....\nOh, Sis, fight.");
            SoundEffect_PlayStream(3, "SS_T_00_095_M00");
            Character_Chara_GS2(14, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(*Sigh*... What a huge mistake.)");
            }
        }
    else if (Parameter_GetPl1Param(322) == 1){
        if (Parameter_bunka_jyu(0) == 1){
            System_Wait(60);
            Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
            Screen_WipeIn(2);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Good thing that went well!)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(14, "S1_04F", 0);
            Voice_PlayVoice("P6414000_N00500", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Sis, good job～.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Woah, Yuu-kun!\nYou came barging in here, again?");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(14, 2, (#1));
            Voice_PlayVoice("P6414000_N00600", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Ehehe, I'll be quick.\nBut just a few words.");
            Character_BlinkStart(14, 0, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P6414000_N00700", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Sis, the performance was quite good.\nI got carried away!");
            Message_Who(0);
            Message_MsgDisp("主人公", "Thank you.\nBut everyone will be coming back\nsoon, okay?");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("P6414000_N00800", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Yeeeesss. Well then, later!");
            SoundEffect_PlayStream(3, "SS_T_00_095_M00");
            Character_Chara_GS2(14, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(*Sigh* I got nervous...\nBut that went well.)");
            }
        else {
            System_Wait(60);
            Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
            Screen_WipeIn(2);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Aah, what a huge mistake.)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(14, "S1_04F", 0);
            Voice_PlayVoice("P6414000_N00900", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Sis.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Woah, Yuu-kun!\nYou came in barging, again?");
            Voice_PlayVoice("P6414000_W01000", #1, "");
            Message_Who(0);
            Message_MsgDisp("Club President", "...\nMay I have a word with you in a\nminute?");
            Character_ChFace(0, 2, 3);
            Character_ChFace(0, 3, 2);
            Message_Who(0);
            Message_MsgDisp("主人公", "S-Sure...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(The club leader's so furious...)");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("P6414000_N01100", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Woah～, looks like you're busy....\nGood luck, Sis.");
            SoundEffect_PlayStream(3, "SS_T_00_095_M00");
            Character_Chara_GS2(14, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(*Sigh*... I should try harder...)");
            }
        }
    else {
        if (Parameter_bunka_jyu(0) == 1){
            System_Wait(60);
            Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
            Screen_WipeIn(2);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Good thing that went well!)");
            Character_ChFace(0, 0, 0);
            Character_ChFace(0, 4, 1);
            Character_Chara_GS2(14, "S1_04F", 0);
            Voice_PlayVoice("P6414000_N01200", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Amazing, the best! Sis is the best!");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yuu-kun!?\nReally, I told you not to come\nbarging in...");
            Character_ChFace(0, 0, 0);
            Character_BlinkStart(14, 3, (#1));
            Voice_PlayVoice("P6414000_N01300", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "I know, I know. Just a few words!");
            Character_ChFace(0, 0, 3);
            Character_BlinkStart(14, 2, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P6414000_N01400", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "I was so great! I fancied it, again!");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, thank you.");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("P6414000_N01500", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Oh, someone's coming!\nWell then, later!");
            SoundEffect_PlayStream(3, "SS_T_00_095_M00");
            Character_Chara_GS2(14, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(*Giggles* I wonder if all of those\nhard practices were worth it?)");
            }
        else {
            System_Wait(60);
            Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
            Screen_WipeIn(2);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Aah, what a huge mistake...)");
            Voice_PlayVoice("P6414000_W01600", #1, "");
            Message_Who(0);
            Message_MsgDisp("Club President", "...\nMay I have a word with you for a\nminute?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Y-Yes...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(The club leader's so furious...)");
            Message_Who(0);
            Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
            Message_Who(0);
            Message_MsgDisp("主人公", "I really am sorry...");
            Voice_PlayVoice("P6414000_W01700", #1, "");
            Message_Who(0);
            Message_MsgDisp("Club President", "...\nIf you understand, then it's fine.\nWell then.");
            Character_ChFace(0, 0, 9);
            Character_Chara_GS2(14, "S1_04F", 0);
            Voice_PlayVoice("P6414000_N01800", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", ".........");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yuu-kun...\nHonestly, I told you not to barge\nin...");
            Character_BlinkStart(14, 3, (#1));
            Voice_PlayVoice("P6414000_N01900", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "... Yeah.");
            Message_Who(0);
            Message_MsgDisp("主人公", "What's wrong?");
            Character_ChFace(0, 0, 8);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P6414000_N02000", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Nothing!");
            Message_Who(0);
            Message_MsgDisp("主人公", "But...");
            Character_BlinkStart(14, 2, (#1));
            Voice_PlayVoice("P6414000_N02100", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "I'm just a bit sad.\nBecause Sis got scolded even if you\ndid worked hard...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yuu-kun...");
            Character_ChFace(0, 0, 9);
            Character_BlinkStart(14, 3, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P6414000_N02200", #1, "");
            Message_Who(14);
            Message_MsgDisp("Yuu", "Well then, I have to go.");
            SoundEffect_PlayStream(3, "SS_T_00_095_M00");
            Character_Chara_GS2(14, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(*Sigh*...\nYuu-kun felt sympathetic for me...)");
            }
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(14, 86, 1);
    }
