section "p73_m2_000"{
    int var0 = 0;
    if (Parameter_GetPl1Param(322) == 0){
        Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(2, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ugh, I'm so nervous.)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(2, "M2_01F", 0);
            Music_PlayBGM(0, "MN_C_02_000_D03", 127, 40);
            Voice_PlayVoice("", 2, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Shiba＊＊｝...");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("P8302000_B00000", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "...\nYou shouldn't worry, no one will be\npaying attention to you.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ugh...");
            Voice_PlayVoice("P8302000_B00100", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "I came to take a look at all of the\nclothes....\nI think that should ease your mind.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... I see. I'm a little calmer...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P8302000_B00200", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "Bye.");
            Character_Chara_GS2(2, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Was ｛Shiba＊＊｝ worried\nabout me, by any chance?\nTime to do my best!)");
            }
        else if (Parameter_GetCh1Param(2, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(It's almost my turn...\nAaaah, my heart is throbbing...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(2, "M2_01F", 0);
            Music_PlayBGM(0, "MN_C_02_000_D03", 127, 40);
            Voice_PlayVoice("", 2, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Shiba＊＊｝...");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("P8302000_B00300", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "...\nYou shouldn't worry, no one will be\npaying attention to you.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ugh...");
            Voice_PlayVoice("P8302000_B00400", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "I came to take a look at all of the\nclothes....\nI think that should ease your mind.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... I see.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(2, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8302000_B00500", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... I'll be watching you.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(2, 2, (#1));
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("P8302000_B00600", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "Bye.");
            Character_Chara_GS2(2, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Okay, I will do my best!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(40, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else if (Parameter_GetPl1Param(322) == 1){
        if (Parameter_GetCh1Param(2, 130) == 3){
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(2, "M2_01F", 0);
            Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
            Screen_WipeIn(2);
            Music_PlayBGM(0, "MN_C_02_000_D03", 127, 40);
            Voice_PlayVoice("P8302000_B00700", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... That's an amazing appearance.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Shiba＊＊｝.\nDo I look strange?");
            Voice_PlayVoice("P8302000_B00800", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... Did I say you look strange...");
            Message_Who(0);
            Message_MsgDisp("主人公", "... As expected...");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(2, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8302000_B00900", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "...\nYou're not used to feeling\nuncomfortable, it will seem\nstrange....\nI guess.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(2, 3, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8302000_B01000", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "Don't fall if you step on the hem of\nyour skirt.\nBye.");
            Character_Chara_GS2(2, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Was ｛Shiba＊＊｝ worried\nabout me, by any chance?\nTime to do my best!)");
            }
        else if (Parameter_GetCh1Param(2, 130) >= 4){
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(2, "M2_01F", 0);
            Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
            Screen_WipeIn(2);
            Music_PlayBGM(0, "MN_C_02_000_D03", 127, 40);
            Voice_PlayVoice("P8302000_B01100", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... That's an amazing dress.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Shiba＊＊｝.\nDo I look strange?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(2, 3, (#1));
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("P8302000_B01200", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... Strange.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh!?");
            Voice_PlayVoice("P8302000_B01300", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... Not.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... Which one is it?");
            Character_BlinkStart(2, 2, (#1));
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8302000_B01400", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "........ Come on. It suits you.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P8302000_B01500", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "I'll be watching from my seat.\nLater.");
            Character_Chara_GS2(2, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I'm nervous...\nBut, I will do my best!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(41, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else {
        Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(2, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(It's full of guests...\nI'm a little embarrassed...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(2, "M2_01F", 0);
            Music_PlayBGM(0, "MN_C_02_000_D03", 127, 40);
            Voice_PlayVoice("", 2, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Shiba＊＊｝.");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(2, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8302000_B01600", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... Wow.");
            Message_Who(0);
            Message_MsgDisp("主人公", "W-What?");
            Voice_PlayVoice("P8302000_B01700", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "The dress you're wearing is\nbeautiful, I didn't think it was\npossible.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ugh...");
            Character_ChFace(0, 2, 5);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8302000_B01800", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... However, it suits you.\nMaybe having some confidence would\nbe nice?");
            Message_Who(0);
            Message_MsgDisp("主人公", "... Really?");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8302000_B01900", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "...You don't trust me.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P8302000_B02000", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "Look into my eyes to know if whether\nor not what I said is true.");
            Voice_PlayVoice("P8302000_B02100", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "I will be watching from my seat....\nBe careful not to fall down.");
            Character_Chara_GS2(2, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Was ｛Shiba＊＊｝ worried\nabout me, by any chance?\nTime to do my best!)");
            }
        else if (Parameter_GetCh1Param(2, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(It's full of guests...\nI'm a little embarrassed...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(2, "M2_01F", 0);
            Music_PlayBGM(0, "MN_C_02_000_D03", 127, 40);
            Voice_PlayVoice("", 2, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Shiba＊＊｝.");
            Voice_PlayVoice("P8302000_B02200", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "........");
            Message_Who(0);
            Message_MsgDisp("主人公", "W-What?\nDo you find something strange?");
            Voice_PlayVoice("P8302000_B02300", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", ".... No.");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(2, 3, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P8302000_B02400", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... Would it be better if I stopped?");
            Message_Who(0);
            Message_MsgDisp("主人公", "What?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(2, 2, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P8302000_B02500", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "That... dress....\nYou would be showing it to other\nguys...");
            Character_ChFace(0, 0, 9);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8302000_B02600", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... Nevermind.");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P8302000_B02700", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "It's not strange.\nInstead, it's beautiful.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Shiba＊＊｝...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P8302000_B02800", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "...\nIt's going all blank inside my head.\nI think it's best if I go ahead.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah.\nThank you, ｛Shiba＊＊｝.");
            Character_Chara_GS2(2, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I will try to do my best for my\nlast high school play!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(42, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    Screen_WipeOut(1);
    System_Call_GS2("P74", "M2", 0);
    }
