section "p73_m5_000"{
    int var0 = 0;
    if (Parameter_GetPl1Param(322) == 0){
        Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(5, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(I'm kind of nervous...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(5, "M5_01F", 0);
            Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
            Voice_PlayVoice("", 5, "P8305000_E00000");
            Message_Who(5);
            Message_MsgDisp("Chris", "｛主人公｝.\nYou've worked hard.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝.\nYou've worked hard...");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P8305000_E00100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Those clothes are cute.\nYou facial expressions, too.\nRelax, relax!");
            Message_Who(0);
            Message_MsgDisp("主人公", "O-Okay...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P8305000_E00200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I'll be in the audience. Good luck.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Chris＊＊｝ is also\nwatching.\nAlright, I have to do my best!)");
            }
        else if (Parameter_GetCh1Param(5, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(I'm kind of nervous...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(5, "M5_01F", 0);
            Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
            Voice_PlayVoice("", 5, "P8305000_E00300");
            Message_Who(5);
            Message_MsgDisp("Chris", "｛主人公｝.\nYou've worked hard.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Chris＊＊｝.\nDid you come to watch?");
            Voice_PlayVoice("P8305000_E00400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah.\nSo you're wearing hand made clothes,\nhuh...\nIt's cute.");
            Message_Who(0);
            Message_MsgDisp("主人公", "R-Really.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 3, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8305000_E00500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah, it's perfect.\nThe owner would completely be\nupstaged by you.");
            Character_BlinkStart(5, 2, (#1));
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8305000_E00600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "What will you do, if we can't see\nyou or your amazing clothes?\nCome on, look straight up.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Chris＊＊｝...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P8305000_E00700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I'll be watching from the audience\nseats.\nI'll see you later!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Chris＊＊｝ is also\ncheering me on.\nI have to do my best!)");
            }
        Character_Chara_GS2(5, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(40, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else if (Parameter_GetPl1Param(322) == 1){
        Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(5, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(It'd be embarrassing if I fell over\nin this dress...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(5, "M5_01F", 0);
            Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
            Voice_PlayVoice("", 5, "P8305000_E00800");
            Message_Who(5);
            Message_MsgDisp("Chris", "｛主人公｝.\nYou've worked hard.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝.\nYou've worked hard.");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P8305000_E00900", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Wow... Is that dress handmade?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah, basically.");
            Voice_PlayVoice("P8305000_E01000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "There's no need to add \"basically\".\nIt's such an amazing dress.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Thank you, ｛Chris＊＊｝.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8305000_E01100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Now then, I'll be going to the\naudience seats.\nDo a nice turn, okay?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Haha, if I can.");
            Character_Chara_GS2(5, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Chris＊＊｝ is also\nwatching, Alright, I have to do my\nbest!)");
            }
        else if (Parameter_GetCh1Param(5, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(It'd be embarrassing if I fell over\nin this dress...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(5, "M5_01F", 0);
            Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
            Voice_PlayVoice("", 5, "P8305000_E01200");
            Message_Who(5);
            Message_MsgDisp("Chris", "｛主人公｝.\nYou've worked hard.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝.\nYou've worked hard.\nHow is this dress?");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8305000_E01300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... Like a princess.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Really?");
            Character_BlinkStart(5, 3, (#1));
            Voice_PlayVoice("P8305000_E01400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah.\nIt's so pretty that it makes me want\nto wear a prince costume and stand\nbeside you.");
            Character_BlinkStart(5, 2, (#1));
            Voice_PlayVoice("P8305000_E01500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Then I'd be able to escort you from\nstart to finish...");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Chris＊＊｝...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8305000_E01600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Now then, I will see you later.\nDo your best, until the very end.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah!");
            Character_Chara_GS2(5, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Alright, I have to do my best!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(41, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else {
        if (Parameter_GetCh1Param(5, 130) == 3){
            Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
            Screen_WipeIn(2);
            Message_Who(0);
            Message_MsgDisp("主人公", "(Hmm～, is this dress weird...)");
            Character_ChFace(0, 2, 3);
            Character_ChFace(0, 3, 0);
            Character_Chara_GS2(5, "M5_01F", 0);
            Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
            Voice_PlayVoice("P8305000_E01700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Wow... A wedding dress.\nHow pretty...");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Chris＊＊｝.\nSo you came to watch.\nHey, isn't this dress weird?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 3, (#1));
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("P8305000_E01800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "You look absolutely fine...\nBut I feel weird.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            Character_ChFace(0, 0, 9);
            Voice_PlayVoice("P8305000_E01900", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I feel like a dad who is letting his\ndaughter become a wife...");
            Voice_PlayVoice("P8305000_E02000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Even if you fall over, no crying,\nokay?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Geez, ｛Chris＊＊｝.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P8305000_E02100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Ah, you yelled.\nAnyway, I will see you later, okay?");
            Character_Chara_GS2(5, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Chris＊＊｝ is also\nwatching.\nAlright, I have to do my best!)");
            }
        else if (Parameter_GetCh1Param(5, 130) >= 4){
            Character_ChFace(0, 0, 11);
            Character_Chara_GS2(5, "M5_01F", 0);
            Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
            Screen_WipeIn(2);
            Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
            Voice_PlayVoice("P8305000_E02200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... Ah.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝.\nYou came to watch.");
            Voice_PlayVoice("P8305000_E02300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "A wife...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Right, I'm wearing a wedding dress.\nHow is it?");
            Voice_PlayVoice("P8305000_E02400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", ".........");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Chris＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8305000_E02500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Ah! S-Sorry!");
            Character_BlinkStart(5, 2, (#1));
            Voice_PlayVoice("P8305000_E02600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I was just... kinda...\nthinking about the future....");
            Message_Who(0);
            Message_MsgDisp("主人公", "The future?");
            Character_BlinkStart(5, 3, (#1));
            Voice_PlayVoice("P8305000_E02700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah...\nMe standing next to you, holding\nyour hand...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_BlinkStart(5, 0, (#1));
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8305000_E02800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... Wah, just in the nick of time!\nI'm just safe! Anyway, good luck!");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝!");
            Character_Chara_GS2(5, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(He left.\nWhat's with ｛Chris＊＊｝)");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Anyway, I have to do my best on\nstage!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(42, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    Screen_WipeOut(1);
    System_Call_GS2("P74", "M5", 0);
    }
