section "p73_m3_000"{
    int var0 = 0;
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetPl1Param(322) == 0){
        if (Parameter_GetCh1Param(3, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, what should I do!?\nI'm so nervous...)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝.");
            Voice_PlayVoice("P8303000_C00000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I dropped by on business of the\nCulture Festival administration.\nThe play is very soon....\nAre you nervous?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, a little...");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("P8303000_C00100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It is not you that everyone will be\nlooking at, it's the clothes.\nYou don't need to mind me.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah... I get what you're saying.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P8303000_C00200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I will be watching from here.\nNow, it is your turn.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Okay, I'll try hard!)");
            }
        else if (Parameter_GetCh1Param(3, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, what should I do!\nI'm so nervous...)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Hikami＊＊｝.\nYou came to watch.");
            Voice_PlayVoice("P8303000_C00300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Ah, I managed to be in time for it.\nThose clothes seem like they took a\nlong time to make...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, what do you think?");
            Character_BlinkStart(3, 3, (#1));
            Voice_PlayVoice("P8303000_C00400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "........ I-It suits you. Very much.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Really?");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(3, 2, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8303000_C00500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Showing it to everyone though is a\nlittle...\ntoo much for their own good.\nHowever, I must say, you will look\nfine on stage.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(...\nI was encouraged very much by\n｛Hikami＊＊｝!\nOkay, I will do my best.)");
            }
        Character_Chara_GS2(3, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(40, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else if (Parameter_GetPl1Param(322) == 1){
        if (Parameter_GetCh1Param(3, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, what should I do!\nI'm so nervous...)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝!");
            Voice_PlayVoice("P8303000_C00600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I came to see you from the side of\nthe stage when the guests were\nguided in....\nAre you nervous?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, a little...");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("P8303000_C00700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Do not worry.\nAt best, the seats are pitch black,\nyou will not be able to see\nanything.");
            Message_Who(0);
            Message_MsgDisp("主人公", "O-Okay...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P8303000_C00800", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I will watch from here.\nNow, it's starting.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Okay, I will try hard!)");
            }
        else if (Parameter_GetCh1Param(3, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, what should I do!\nI'm so nervous...)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 11);
            Character_BlinkStart(3, 2, (#1));
            Character_ChFace(0, 4, 1);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Hikami＊＊｝!\nYou came to watch.");
            Voice_PlayVoice("P8303000_C00900", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Yes, it is the job of an executive.\nY...You will look fine on stage.\nYou took a long time to make those\nclothes.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, what do you think?");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(3, 2, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8303000_C01000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It is very... amazing...\nBeautiful...\nYou appear to be a different person.");
            Character_ChFace(0, 0, 11);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8303000_C01100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "... N-No!\nYour usual self, is umm, nice, too!\nBut this... It is wonderful.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Thank you, ｛Hikami＊＊｝.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P8303000_C01200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It is your turn.\nI will go to my seat.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(My nerves seemed to have calmed\ndown a little.\nOkay, I will do my best!)");
            }
        Character_Chara_GS2(3, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(41, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else {
        if (Parameter_GetCh1Param(3, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, what should I do!\nI'm so nervous...)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝.");
            Voice_PlayVoice("P8303000_C01300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I came to return the machinery the\nexecutives borrowed.\nIncidentally, when I dropped in...\nIt was full of brides.");
            Message_Who(0);
            Message_MsgDisp("主人公", "*Giggles* Wedding dresses are the\ntheme this year.");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("P8303000_C01400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Is that so? ...\nHowever, the scene of so many women\nwas a little bizarre.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeeeeah, sure....");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P8303000_C01500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Since this is special, I will watch\nfrom here.\nNow, it's your turn.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I feel a little at ease!\nOkay, I will do my best!)");
            }
        else if (Parameter_GetCh1Param(3, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, what should I do!\nI'm so nervous...)");
            Voice_PlayVoice("", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(3, "M3_01F", 0);
            Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Hikami＊＊｝!\nYou came to watch.");
            Voice_PlayVoice("P8303000_C01600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I heard it would make a suitable\nmasterpiece for the final Culture\nFestival.\nIt is my job as an executive.");
            Character_ChFace(0, 0, 11);
            Character_BlinkStart(3, 2, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8303000_C01700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "But, you, that...\nSurely, that's what a bride\nwears...?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, it's a wedding dress!\nIt's this year's theme.");
            Character_ChFace(0, 2, 3);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("P8303000_C01800", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "... It...It's lovely.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh?");
            Character_ChFace(0, 0, 11);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8303000_C01900", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Oh, no, that, the dress! ...\nI did not mean you! Ugh...\nUmm, what...");
            Message_Who(0);
            Message_MsgDisp("主人公", "... ｛Hikami＊＊｝?");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(3, 2, (#1));
            Voice_PlayVoice("P8303000_C02000", 3, "P8303000_C02001");
            Message_Who(3);
            Message_MsgDisp("Hikami", "... Nothing. I am going to my seat.\nIt's your turn,\n｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Hikami＊＊｝ will be\nwatching.\nYes, I will do my best!)");
            }
        Character_Chara_GS2(3, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(42, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    Screen_WipeOut(1);
    System_Call_GS2("P74", "M3", 0);
    }
