section "p73_m1_000"{
    int var0 = 0;
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetPl1Param(322) == 0){
        if (Parameter_GetCh1Param(1, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, what should I do!\nI'm so nervous...)");
            Voice_PlayVoice("", 1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(1, "M1_01F", 0);
            Music_PlayBGM(0, "MN_C_01_000_D02", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Saeki＊＊｝.");
            Voice_PlayVoice("P8301000_A00000", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Hey! Are you nervous?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ye-Yeah... A bit.");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(1, 3, (#1));
            Voice_PlayVoice("P8301000_A00100", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Heh... I see you're wearing that.\nIt seems like you're more likely to\nfall.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Really! Such a bully!");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(1, 0, (#1));
            Voice_PlayVoice("P8301000_A00200", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Ahaha! Fall, fall!");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 6);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("P8301000_A00300", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Well then, I'll be watching you from\nmy seat.\nI'm keeping my hopes high!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I will not fall down!)");
            }
        else if (Parameter_GetCh1Param(1, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, what should I do!\nI'm so nervous...)");
            Voice_PlayVoice("", 1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "｛主人公｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(1, "M1_01F", 0);
            Music_PlayBGM(0, "MN_C_01_000_D02", 127, 40);
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Saeki＊＊｝.");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(1, 2, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P8301000_A00400", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "I came for a quick look before the\ndebut....\nAre you wearing that for the show?");
            Message_Who(0);
            Message_MsgDisp("主人公", "W-What do you think about this\noutfit?");
            Character_ChFace(0, 0, 0);
            Character_BlinkStart(1, 2, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8301000_A00500", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Yeah... Well, yeah.\nIt's like that...");
            Message_Who(0);
            Message_MsgDisp("主人公", "What do you mean by that?");
            Character_ChFace(0, 0, 0);
            Character_BlinkStart(1, 3, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8301000_A00600", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "... Nice... Very amazing.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 6);
            Character_BlinkStart(1, 2, (#1));
            Voice_PlayVoice("P8301000_A00700", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Well, I'm off to my seat. Good luck.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Okay! I'll do my best!)");
            }
        Character_Chara_GS2(1, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(40, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else if (Parameter_GetPl1Param(322) == 1){
        if (Parameter_GetCh1Param(1, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(This year's a dress...\nI have to do much better than last\nyear, so I must make it\nsuccessful...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(1, "M1_01F", 0);
            Music_PlayBGM(0, "MN_C_01_000_D02", 127, 40);
            Voice_PlayVoice("", 1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Saeki＊＊｝!");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("P8301000_A00800", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Ooh...\nAmazing, you look really adult-like.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Really? Thank you.");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8301000_A00900", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "And also, about falling...\nLooks like the guys are going to be\nhappy about it, right?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Really! Don't say such things!");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(1, 3, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8301000_A01000", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "That was just a joke, okay? Hey.\nSeriously. Don't trip.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I will not fall down!)");
            }
        else if (Parameter_GetCh1Param(1, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(This year's a dress...\nI have to do much better than last\nyear, so I must make it\nsuccessful...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(1, "M1_01F", 0);
            Music_PlayBGM(0, "MN_C_01_000_D02", 127, 40);
            Voice_PlayVoice("", 1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Saeki＊＊｝.");
            Character_ChFace(0, 0, 0);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8301000_A01100", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", ".........");
            Message_Who(0);
            Message_MsgDisp("主人公", "Hey, what do you think about this\ndress?");
            Character_ChFace(0, 0, 9);
            Character_BlinkStart(1, 2, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8301000_A01200", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "... Ye-Yeah.\nI think it's nice, but...");
            Message_Who(0);
            Message_MsgDisp("主人公", "But?");
            Character_ChFace(0, 0, 0);
            Character_BlinkStart(1, 2, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8301000_A01300", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Isn't that a bit too revealing?\nUmm...\nespecially around the chest....");
            Message_Who(0);
            Message_MsgDisp("主人公", "But, it's a cocktail dress...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 0, 8);
            Character_BlinkStart(1, 2, (#1));
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8301000_A01400", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Don't try to slouch too much, okay?");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Saeki＊＊｝...\nwas jealous? Okay! I'll do my best!)");
            }
        Character_Chara_GS2(1, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(41, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else {
        if (Parameter_GetCh1Param(1, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wedding dresses are for the 3rd\nyear...\nI have to do much better than last\nyear, so I must make it\nsuccessful...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(1, "M1_01F", 0);
            Music_PlayBGM(0, "MN_C_01_000_D02", 127, 40);
            Voice_PlayVoice("", 1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Saeki＊＊｝!");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8301000_A01500", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "I see, a wedding dress...\nYou made it so... Amazing.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah, even though it was really\ntough.\nThank you.");
            Character_ChFace(0, 2, 3);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P8301000_A01600", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Good luck, okay?\nI'll be watching you closely.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh? ...\nYou're nice this year, are you?");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 2, 3);
            Voice_PlayVoice("P8301000_A01700", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Well, just for this year.\nI'd still praise you even if you do\ntrip, so go on.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I'm not going to trip! Okay!\nI'll do my best!)");
            }
        else if (Parameter_GetCh1Param(1, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wedding dresses are for the 3rd\nyear...\nI have to do much better than last\nyear, so I must make it\nsuccessful...)");
            Character_ChFace(0, 0, 8);
            Character_Chara_GS2(1, "M1_01F", 0);
            Music_PlayBGM(0, "MN_C_01_000_D02", 127, 40);
            Voice_PlayVoice("", 1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Saeki＊＊｝!");
            Voice_PlayVoice("P8301000_A01800", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", ".........");
            Message_Who(0);
            Message_MsgDisp("主人公", "Hey, what do you think?\nI did my best making it...");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(1, 2, (#1));
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P8301000_A01900", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "... I feel at a loss.");
            Message_Who(0);
            Message_MsgDisp("主人公", "A loss? Why?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(1, 2, (#1));
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8301000_A02000", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Nothing much, it's better not to\nknow...");
            Message_Who(0);
            Message_MsgDisp("主人公", "......?");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("P8301000_A02100", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Hey, umm...\nAre you going to change right after\nyou're done?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah, that's what I intended on\ndoing.");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8301000_A02200", #1, "");
            Message_Who(1);
            Message_MsgDisp("Saeki", "Well, forget it... Okay, good luck!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Okay! I'll do my best!)");
            }
        Character_Chara_GS2(1, "NON");
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(42, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    Screen_WipeOut(1);
    System_Call_GS2("P74", "M1", 0);
    }
