section "p73_m7_000"{
    int var0 = 0;
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetPl1Param(322) == 0){
        if (Parameter_GetCh1Param(7, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, what do I do!\nI'm so nervous...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(7, "M7_17F", 0);
            Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
            Voice_PlayVoice("", 7, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝!");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8307000_G00000", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "The model is a little complete.\nYou look a bit pale.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, I'm nervous...");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8307000_G00100", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Well then, let's try to warm up your\nfingertips.\nYour nervousness will go away once\nyou're warm.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh, really!?\nI'll look after my breathing for a\nmoment....\nI-I'm warm.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(7, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8307000_G00200", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "I made your blood flow from the tips\nand stimulated your endocrine\nsystem.\nIt's the magic of science.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P8307000_G00300", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Yes, you're all right now.\nSensei will see himself to his seat.");
            Character_Chara_GS2(7, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(My nervousness went away a little,\nokay, I will try my best!)");
            }
        else if (Parameter_GetCh1Param(7, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, what do I do!\nI'm so nervous...)");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Character_Chara_GS2(7, "M7_17F", 0);
            Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
            Voice_PlayVoice("P8307000_G00400", 7, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Hello, ｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝!\nYou came to watch.");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8307000_G00500", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Yes.\nYou appear to be quite the model.\nYou look nice.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Thank you! I made this.");
            Character_ChFace(0, 0, 10);
            Character_BlinkStart(7, 2, (#1));
            Voice_PlayVoice("P8307000_G00600", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Oh, that smile.\nAs expected, you have to do what you\nhave to do.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            Voice_PlayVoice("P8307000_G00700", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "However, don't forget to have that\nmood on stage, it's alright.\nIt will certainly go well.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P8307000_G00800", 7, "P8307000_G00801");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Sensei isn't going anywhere.\nHe'll cheer you on from his seat,\n｛主人公｝.");
            Character_Chara_GS2(7, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I'm relaxed now that\n｛Wakaouji＊＊｝ came...\nOkay, I will do my best!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(40, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else if (Parameter_GetPl1Param(322) == 1){
        if (Parameter_GetCh1Param(7, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, what do I do!\nI'm so nervous...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(7, "M7_17F", 0);
            Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
            Voice_PlayVoice("P8307000_G00900", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Mademoiselle.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Wakaouji＊＊｝!");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8307000_G01000", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "You turned around, didn't you?\nYou thought I was talking about you.\nAm I right?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ugh... Right.");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8307000_G01100", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "So, you are the mademoiselle who is\nwearing the dress.\nThe stage wasn't that frightening.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P8307000_G01200", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Relax. See you.");
            Character_Chara_GS2(7, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(My nervousness went away a little.\nOkay, I will try my best!)");
            }
        else if (Parameter_GetCh1Param(7, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, what do I do!\nI'm so nervous...)");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Character_Chara_GS2(7, "M7_17F", 0);
            Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
            Voice_PlayVoice("P8307000_G01300", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Mademoiselle.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝!\nYou came to watch.");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8307000_G01400", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "You turned around, didn't you?\nYou thought I was talking about you.\nAm I right?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ugh... Right.");
            Character_ChFace(0, 2, 3);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("P8307000_G01500", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "You don't need to feel shy.\nUntil yesterday, you were a designer\nand a seamstress.\nToday, you are a beauty on stage.");
            Voice_PlayVoice("P8307000_G01600", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "It suits you very well.\nYou're going to debut,\nmagnificently.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P8307000_G01700", 7, "P8307000_G01701");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Sensei can't stay any longer.\nI'll support you from my seat,\n｛主人公｝.");
            Character_Chara_GS2(7, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝ will be\nwatching...\nOkay, I will try my best!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(41, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    else {
        if (Parameter_GetCh1Param(7, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, it's full of guests!\nMy heart's throbbing...)");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(7, "M7_17F", 0);
            Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
            Voice_PlayVoice("", 7, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Oh, ｛Wakaouji＊＊｝.");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8307000_G01800", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "It's packed to the capacity.\nThe guests' expectations are at\ntheir climax.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ugh...");
            Voice_PlayVoice("P8307000_G01900", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "...\nYour nervousness is at its climax,\ntoo.\nRight?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, right...");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(7, 3, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8307000_G02000", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Well then, a beauty should not be\nnervous any further.\nYou will be able to relax on stage.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... Oh, really.");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(7, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("P8307000_G02100", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Yes, it's okay now.\nSee you soon, bride.");
            Character_Chara_GS2(7, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Yeah, he may be right...\nOkay, I will do my best!)");
            }
        else if (Parameter_GetCh1Param(7, 130) >= 4){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Wow～, it's full of guests!\nMy heart's throbbing...)");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Character_Chara_GS2(7, "M7_17F", 0);
            Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
            Voice_PlayVoice("P8307000_G02200", 7, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Hello, ｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝!\nYou came to watch.");
            Character_ChFace(0, 0, 11);
            Voice_PlayVoice("P8307000_G02300", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Hello there, lovely bride....\nSurely the bridegroom will turn up?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, but today's performance is\nabout a woman.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(7, 2, (#1));
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("P8307000_G02400", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "In that case, I'm relieved.\nI'm not completely jealous.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            SoundEffect_PlayStream(3, "SS_T_00_041_M00");
            Voice_PlayVoice("P8307000_G02500", 7, "P8307000_G02501");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Yeah, so anyway.\nAside from that, it's your turn.\nGo perform, ｛主人公｝.");
            Character_Chara_GS2(7, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I wonder what ｛Wakaouji＊＊｝\nwas going to say?\n... Ah, it's starting soon.\nOkay, I'll do my best!)");
            }
        Message_CloseMsg();
        Screen_WipeOut(1);
        System_Wait(90);
        Environment_StopME(0, 40);
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Background_Bg_GS2("BG_SCD10_LI_0", #1, #1, 0);
        Screen_WipeIn(2);
        var0 = 51 + 13;
        var0 = Parameter_bunka_jyu(0);
        Graphic_OpenAnim(42, var0);
        Environment_PlayME(0, "", 127, 0);
        }
    Screen_WipeOut(1);
    System_Call_GS2("P74", "M7", 0);
    }
