section "p83_s1_000"{
    Background_Bg_GS2("BG_SCA80_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetPl1Param(322) == 0){
        SoundEffect_PlayStream(3, "SS_DSE_052_000");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ten copies, take them～!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It's getting cold～!\nWe're busier than usual during the\nCulture Festival.)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(14, "S1_04F", 0);
        Music_PlayBGM(0, "MN_C_14_000_D00", 127, 40);
        Voice_PlayVoice("P7314000_N00000", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "Sis～! I came to visit!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, Yuu-kun came to pay a visit.\nWait a second, please.\nThis place is off-limits with the\nexception of officials.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("P7314000_N00100", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "Okay, understood. I'll wait outside.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay, thank you.");
        Voice_PlayVoice("P7314000_W00200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student", "Can I ask for a copy of this, too?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, yes!");
        Message_CloseMsg();
        SoundEffect_StopStream(3, 40);
        Screen_WipeOut(1);
        Screen_ClearScreen();
        }
    else if (Parameter_GetPl1Param(322) == 1){
        Message_Who(0);
        Message_MsgDisp("主人公", "I've collected the drills!\nThe additional pamphlets will arrive\nfrom the print shop in one hour～!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Phew* I didn't think that being in\ncharge of materials would be this\ntough...)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(14, "S1_04F", 0);
        Music_PlayBGM(0, "MN_C_14_000_D00", 127, 40);
        Voice_PlayVoice("P7314000_N00300", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "Sis.\nI came to watch the culture\nfestival.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, Yuu-kun! Wait a second, please.\nThis place is off-limits with the\nexception of officials.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("P7314000_N00400", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "It's alright.\nEveryone's busy and no one seems to\nhave a day off, I pay attention to\nthese things.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Problems like that...");
        Voice_PlayVoice("P7314000_W00500", #1, "");
        Message_Who(0);
        Message_MsgDisp("Male Student", "You know, there's a projector\nmissing...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, okay! I'll go find it!");
        Character_BlinkStart(14, 2, (#1));
        Voice_PlayVoice("P7314000_N00600", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "Well then, I'll go with you, too～.\nMay I follow you?");
        Message_Who(0);
        Message_MsgDisp("主人公", "If you insist.");
        Message_CloseMsg();
        Screen_WipeOut(1);
        Screen_ClearScreen();
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "The connection between food and\ndrinks and managing your hygiene are\nconsistent.\nPlease be careful not to knock over\nthe sign in the hall.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Phew～* I was asked to be in charge\nof the floor, so I've got a lot of\nthings to do...)");
        Character_ChFace(0, 0, 10);
        Character_Chara_GS2(14, "S1_04F", 0);
        Music_PlayBGM(0, "MN_C_14_000_D00", 127, 40);
        Voice_PlayVoice("P7314000_N00700", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "Looks like you're doing your best.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yuu-kun! Why are you here!?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P7314000_N00800", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "What are you doing your best for,\nSis?\nI will assist you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, I appreciate your feelings, but\nSis is busy now...");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("P7314000_W00900", #1, "");
        Message_Who(0);
        Message_MsgDisp("Male Student", "There's a problem arising on the\nsecond floor!\nThe party in the Haunted House is\nmaking a commotion!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, okay! I'll approach with care!");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(14, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("P7314000_N01000", #1, "");
        Message_Who(14);
        Message_MsgDisp("Yuu", "Oh, things like that are\ninteresting!\nCan I come, too?");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Hmm～.\nYou will listen to exactly what Sis\nsays, right?");
        Message_CloseMsg();
        Screen_WipeOut(1);
        Character_Chara_GS2(14, "NON");
        }
    Music_StopBGM(0, 40);
    System_Call_GS2("P84", "S1", 0);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
