section "q13_m7_000"{
    int var0;
    var0 = System_Randam(0, 100);
    if (Parameter_GetCh1Param(7, 130) < 2){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Well, ｛Wakaouji＊＊｝ is...\nOh, there he is!)");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝!");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(7, "M7_17F", 0);
        Voice_PlayVoice("", 7, "Q0407000_G00000");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "｛主人公｝, is something\nwrong?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, today is free activity day,\nwould you like to spend it together?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 2, (#1));
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("Q0407000_G00100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Together...\nOh, come to think of it, you haven't\nhanded in your schedule, yet.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes... That's right.");
        Voice_PlayVoice("Q0407000_G00300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "How troubling.\nSensei and the vice principal are\ngoing over tomorrow's preliminary\ninspections.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so...");
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("Q0407000_G00400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I feel bad that you are going alone.\nTake care.");
        Character_Chara_GS2(7, "NON");
        }
    else if (Parameter_GetCh1Param(7, 130) == 2){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Well, ｛Wakaouji＊＊｝ is...\nOh, there he is!)");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝!");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(7, "M7_17F", 0);
        Voice_PlayVoice("", 7, "Q0407000_G00000");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "｛主人公｝, is something\nwrong?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, today is free activity day,\nwould you like to spend it together?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 2, (#1));
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("Q0407000_G00100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Together...\nOh, come to think of it, you haven't\nhanded in your schedule, yet.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes... That's right.");
        if (var0 <= 60){
            Voice_PlayVoice("Q0407000_G00200", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "*Sigh* ... Yes.\nWell then, Sensei will go with you.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Thank you!");
            Message_CloseMsg();
            Screen_WipeOut(2);
            Screen_ClearScreen();
            System_GlobalWork(2, 2, 7);
            System_GlobalWork(0, 2, 2);
            System_Call_GS2("Q16", "M7", 0);
            System_Call_GS2("Q17", "M7", 0);
            }
        else if (var0 >= 61){
            Voice_PlayVoice("Q0407000_G00300", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "How troubling.\nSensei and the vice principal are\ngoing over tomorrow's preliminary\ninspections.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Is that so...");
            Character_ChFace(0, 2, 5);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("Q0407000_G00400", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "I feel bad that you are going alone.\nTake care.");
            Character_Chara_GS2(7, "NON");
            }
        }
    else if (Parameter_GetCh1Param(7, 130) == 3){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Well, ｛Wakaouji＊＊｝ is...\nOh, there he is!)");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝!");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(7, "M7_17F", 0);
        Voice_PlayVoice("", 7, "Q0407000_G00500");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "｛主人公｝, is something\nwrong?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, today is free activity day,\nwould you like to spend it together?");
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("Q0407000_G00600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Oh...\nYou have yet to make a schedule.\nRight?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes... That's right.");
        Voice_PlayVoice("Q0407000_G00700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "*Sigh* Well then, Sensei will go\naround with you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Thank you!");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("Q0407000_G00800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "On the other hand, please guide me.\nSensei does not know this town....\nHowever, I will know it.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_GlobalWork(2, 2, 7);
        System_GlobalWork(0, 2, 2);
        System_Call_GS2("Q16", "M7", 0);
        System_Call_GS2("Q17", "M7", 0);
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "(Well, ｛Wakaouji＊＊｝ is...\nOh, there he is!)");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝!");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(7, "M7_17F", 0);
        Voice_PlayVoice("", 7, "Q0407000_G00900");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "｛主人公｝, is something\nwrong?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I haven't made plans for today,\nyet...\nIt's a free day, would you like to\ngo look around with me?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("Q0407000_G01000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "With a teacher?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes.");
        Voice_PlayVoice("Q0407000_G01100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Hmm...\nBut wouldn't that mean going around\nwith Sensei would be a study meet?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm... Really?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("Q0407000_G01200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Incorrect, of course.\n*Chuckles* Let's go together.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yay～!!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        System_GlobalWork(2, 2, 7);
        System_GlobalWork(0, 2, 2);
        System_Call_GS2("Q16", "M7", 10);
        System_Call_GS2("Q17", "M7", 0);
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 86, 1);
    }
