section "q16_m5_000"{
    Character_ChFace(0, 0, 11);
    Character_Chara_GS2(5, "M5_01F", 0);
    Background_Bg_GS2("BG_SCB50_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGG_016_000", 127, 40);
    Voice_PlayVoice("Q0705000_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Wow～...\nIt really is a gilded splendor.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is this your first time seeing\nGolden Pavilion Temple,\n｛Chris＊＊｝?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q0705000_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah.\nI've only ever seen it in books.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(5, 3, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("Q0705000_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "... ｛Chris＊＊｝?\nWhat's up?");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(5, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0705000_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "......... Ah, sorry.\nI was drawing a picture in my head.");
    Message_Who(0);
    Message_MsgDisp("主人公", "A picture?");
    Voice_PlayVoice("Q0705000_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah, of scenery in Japan that I'd\nlike to paint.\nI was just ranking the Golden\nPavilion Temple, too.");
    Message_Who(0);
    Message_MsgDisp("主人公", "\"Too\"?\nSo there are other things that you'd\nlike to paint.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q0705000_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah, lots of stuff.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0705000_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nI won't be able to finish them all\nwhen you're here with me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0705000_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Let's move on.\nNext is Kiyomizu Temple, right?\nI'm looking forward to that, too.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yeah.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 4);
    Background_Bg_GS2("BG_SCB70_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("Q0705000_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "What the... Is it slanting?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Well, now that you mention it...");
    Voice_PlayVoice("Q0705000_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Will the building be okay with this\nmany people inside...?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Probably.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("Q0705000_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nEven if everyone played jump rope?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I w-wonder...");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(5, 2, (#1));
    Voice_PlayVoice("Q0705000_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Wow.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("Q0705000_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "That yap-yap-yap person is coming\ntowards us!\nLet's take a picture and then run\nfor it!");
    Character_Chara_GS2(5, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(\"Yap-yap-yap\"...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Character_Chara_GS2(5, "M5_01F", 0);
    Background_Bg_GS2("BG_SCB60_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("Q0705000_E01300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Wow!\nThe way they used colors are so\npretty!");
    Message_Who(0);
    Message_MsgDisp("主人公", "How florid...");
    Voice_PlayVoice("Q0705000_E01400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It's somewhat empowering.\nWhich god is this for?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("Q0705000_E01500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah, it's written here.\nThe god of affinity...");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("Q0705000_E01600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "............");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝?");
    Voice_PlayVoice("Q0705000_E01700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "What does that mean?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh!?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0705000_E01800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Is it some kind of filini?\nIf it's a local speciality, I wanna\ntry eating it!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I'm sorry to say,\n｛Chris＊＊｝, but you're\nwrong...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(This is how ｛Chris＊＊｝\nand I spent our time sightseeing.)");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
