section "q16_m3_010"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(3, "M3_01F", 0);
    Background_Bg_GS2("BG_SCB50_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGG_016_000", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "The Golden Pavilion Temple really is\ngolden!");
    Voice_PlayVoice("Q0703010_C00000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "It looks as if it were glowing.\nTo me, I believe the elegance goes\ntogether with its reflection in the\nwater.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(3, 2, (#1));
    Voice_PlayVoice("Q0703010_C00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "However, it would be nice if I sent\nat least a snapshot to my friend\noverseas.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh, you have a friend from\noverseas?");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(3, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0703010_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I do.\nWe became close friends while\nplaying chess over the internet.\nJust one.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Amazing!\nSo ｛Hikami＊＊｝ must be\ngood at English.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(3, 3, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("Q0703010_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "No, it is just chess and e-mails...\nIt is to keep in touch.\nI can manage English from what we\nlearn in school.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so?\nNo, I think that's really amazing.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(3, 2, (#1));
    Voice_PlayVoice("Q0703010_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "That's exaggerating......\nAfter I take the picture, let's\ncarry on to the next area.\nWe have no time to lose.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 0, 10);
    Background_Bg_GS2("BG_SCB70_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("Q0703010_C00500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I was dying to come here!\nThe Kiyomizu Temple!");
    Message_Who(0);
    Message_MsgDisp("主人公", "The Kiyozumi Temple is so tall!\nIt's like you're being swallowed\nin...");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(3, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0703010_C00600", 3, "Q0703010_C00601");
    Message_Who(3);
    Message_MsgDisp("Hikami", "...... ｛主人公｝.\nI have a favor to ask of you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sure, what is it?");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0703010_C00700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I want you to take a picture of\nme...\nCan I ask this of you?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Of course.... Where shall I take it?\nOn the platform?\nOr would you like the main temple as\nyour background?");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(3, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0703010_C00800", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "No, a different one. Umm...\nAt \"Benkei's staff\", please.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Benkei's staff?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q0703010_C00900", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Yes! It weighs around 90 kilos.\nIt is said that you will be\nsuccessful if you can lift up\nBenkei's staff.");
    Voice_PlayVoice("Q0703010_C01000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Honestly, even though I do not have\nconfidence in my physical strength,\nI can lift it with my willpower!");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q0703010_C01100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Therefore, the moment I lift it up,\nI want you to press the shutter\nbutton.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay, got it.\nGood luck, ｛Hikami＊＊｝!");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(3, 2, (#1));
    Voice_PlayVoice("Q0703010_C01200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Thank you!\nI'm counting on you to take the\nshot.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("EV_03_14", #1, 0, 20);
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 4, 1);
    Screen_WipeIn(2);
    Still_Approach(3, 72, 0, 0, 1, 1);
    Voice_PlayVoice("Q0703010_C01300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "*Groans* It's heavy... Hah...\nHere I go! ... Now, shoot!!");
    Still_ApproachEnd();
    SoundEffect_PlayStream(3, "SS_T_00_055_M00");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 4, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hikami＊＊｝! I got it!");
    Voice_PlayVoice("Q0703010_C01400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Great, let's play it back and\nconfirm it.");
    Background_Bg_GS2("BG_SCB70_LI_1", #1, #1, 0);
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(3, 2, (#1));
    Still_Event("");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(3, "M3_01F", 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Wow, digital cameras are so\nconvenient.");
    Voice_PlayVoice("Q0703010_C01500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... Good thing I lifted it up...");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(3, 3, (#1));
    Voice_PlayVoice("Q0703010_C01600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Thank you.\nI am grateful that you made it a\nmemorable one.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Don't mention it....\nOkay, while I have the chance, I\nshould give it a try for my success,\nas well!");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q0703010_C01700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Umm, no, it is best if you give up.\nIt is said that they have other\nterms for girls...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh, like what?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0703010_C01800", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "...\nGirls who are able to lift it would\nlikely become a bossy wife.\nIf that sounds okay to you then, I\nwill not stop you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What!?... What should I do?");
    Character_ChFace(0, 0, 6);
    Character_BlinkStart(3, 2, (#1));
    Voice_PlayVoice("Q0703010_C01900", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I guess, it may be fun if we are to\nbe together.");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("Q0703010_C02000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Aah, no, umm... F-Forget it!");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hikami＊＊｝?");
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0703010_C02100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Wow, look at the time!\nWe better return soon.\nIt was brief but worthwhile.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, that was fun!");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(3, 61, 6);
    Parameter_AddCh1Param(3, 60, 3);
    Parameter_AddCh1Param(3, 62, #5);
    }
