section "q16_g2_000"{
    Background_Bg_GS2("BG_SCB50_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGG_016_000", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah, the Golden Pavilion temple!");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(11, 2, (#1));
    Character_Chara_GS2(11, "G2_01F", 0);
    Voice_PlayVoice("Q0711000_K00000", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "It's really golden...\nI'm astonished that I am actually\nseeing it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, you're right...\nOh, there are a lot of koi in the\npond.");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0711000_K00100", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Eh? ... Oh, that's true!");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q0711000_K00200", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "How lovely they are...\nThey are colorful.\nAlmost like jewels that are very\nmuch alive...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hey, it looks like they are giving\nfood to the koi over there.");
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0711000_K00300", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "... Food!\nIs it okay to give them food!?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?");
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0711000_K00400", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Where do they sell the food!?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Weeell, it looks like it's being\nsold at that place.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(11, 2, (#1));
    Voice_PlayVoice("Q0711000_K00500", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Please be there!\nI'm going to buy some right now!");
    Character_Chara_GS2(11, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(...\n｛Onoda＊＊｝ seems to be\nfond of koi.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SCB60_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "The landowner of the Shinto shrine\nis here.");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(11, "G2_01F", 0);
    Voice_PlayVoice("Q0711000_K00600", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "It appears as if the God of Marriage\nis worshiped here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Are you going to ask the God to\ngrant you love,\n｛Onoda＊＊｝?");
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0711000_K00700", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "I-I don't have a person in mind like\nthat!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh, okay.");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(11, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0711000_K00800", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "However, I will pray that it brings\nme closer to the person whom I\nrespect very much.");
    Character_Chara_GS2(11, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(...\nThere's a person in mind, after\nall.)");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
