section "q16_m7_000"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(7, "M7_17F", 0);
    Background_Bg_GS2("BG_SCB50_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGG_016_000", 127, 40);
    Voice_PlayVoice("Q0707000_G00000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Everyone～, on your right hand side\nyou can see the legendary Temple of\nthe Golden Pavilion.");
    Voice_PlayVoice("Q0707000_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "The formal name is Rokuon-ji.\nYou all are familiar with the gilded\nsplendor of the building, a part of\nthe Rokuon-ji halls.");
    Message_Who(0);
    Message_MsgDisp("主人公", "As expected, Sensei knows a lot!");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q0707000_G00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Ahem.\nThe preliminary investigation was\nperfect.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(7, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0707000_G00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "...\nActually, what I wanted to say was\nthat I secretly heard the tour guide\ntell another group.");
    SoundEffect_PlayStream(2, "SE_NS_AL_910_003000");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q0707000_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I'm sorry, I only heard that much.\nI will check each person later.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Oops...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SCB70_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "...\nSensei, we've finally arrived at the\nKiyomizu-dera temple!");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(7, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0707000_G00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I'm sorry.\nI would have ended up making you\nwalk past it.\nSensei hesitates a lot.");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's all right, I'm not tired.");
    Character_ChFace(0, 4, 0);
    Character_BlinkStart(7, 0, (#1));
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0707000_G00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Really? You don't mind?");
    Voice_PlayVoice("Q0707000_W00700", #1, "");
    Message_Who(0);
    Message_MsgDisp("Male Student A", "It's all right, Waka-chan,\neveryone's used to it!");
    SoundEffect_PlayStream(2, "SE_NS_AL_910_003000");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(7, 2, (#1));
    Voice_PlayVoice("Q0707000_G00800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Thank you. I owe it to all of you.\nThis scenery is very beautiful to\nview.");
    Voice_PlayVoice("Q0707000_G00900", 7, "Q0707000_G00901");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Now, let's go forward.\n｛主人公｝, may I ask for\nyou to be our guide?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh, me? ... O-Okay!");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SCB60_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Good, we arrived safely at Jishu\nShrine...)");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q0707000_G01000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "What?\nSensei would have been able to guide\nif he knew it was so close to the\nKiyomizu-dera temple.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh!?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(7, 2, (#1));
    Voice_PlayVoice("Q0707000_G01100", 7, "Q0707000_G01101");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Kidding, kidding.\nI'm bluffing right now.\nThank you, ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Really, Sensei...");
    SoundEffect_PlayStream(2, "SE_NS_AL_910_003000");
    Voice_PlayVoice("Q0707000_W01200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Waka-sama, is it okay if we go pray?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q0707000_G01300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Pray?");
    Message_Who(0);
    Message_MsgDisp("主人公", "This is the shrine for the God of\nMarriage.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q0707000_G01400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Is that right? It's fine, see you.");
    Voice_PlayVoice("Q0707000_W01500", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Thank you～!");
    SoundEffect_PlayStream(2, "SS_T_00_035_M00");
    Voice_PlayVoice("Q0707000_G01600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "... Sensei should go take a look.\nHow about you, as well?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes, I'll go!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝ and I were\nable to pray for marriage together.\nIt's a good memory...!)");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
