section "q16_m4_000"{
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 3);
    Character_Chara_GS2(4, "M4_01F", 0);
    Background_Bg_GS2("BG_SCB50_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGG_016_000", 127, 40);
    Voice_PlayVoice("Q0704000_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "The temple of the Golden Pavilion!\nLooking at the real thing is\nexquisite.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I guess.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0704000_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "This is enough...\nI will not be defeated.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What are you talking about?");
    Character_BlinkStart(4, 3, (#1));
    Voice_PlayVoice("Q0704000_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "The world class artist and the story\nof Harry's live performance at the\nGolden Pavilion.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? Can you do that?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q0704000_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Probably.\nBut I've never heard of someone\ndoing it before.");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0704000_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "No one has tried to, not until I do\nit first.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0704000_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Just wait, the Golden Pavilion!\nHahahahaha!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hariya＊＊｝'s so\noptimistic.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(4, 3, (#1));
    Background_Bg_GS2("BG_SCB70_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("Q0704000_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I'm burnt out...");
    Character_BlinkStart(4, 2, (#1));
    Voice_PlayVoice("Q0704000_D00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "That slope didn't treat me well.\nI'm not used to exercising...");
    Message_Who(0);
    Message_MsgDisp("主人公", "It was quite a slope.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q0704000_D00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah...\nWell, hey, if we happen to find an\nice cream shop on our way, we get\nroasted green tea ice cream, then\nhead home.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay!");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("Q0704000_D00900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Well.................. ...\nShall we get going?");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝, let's go look\nat the scenery some more...");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0704000_D01000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "But I wanna eat some ice cream...");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 4, 0);
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 2);
    Background_Bg_GS2("BG_SCB60_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("Q0704000_D01100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Marriage...... A good pair...");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("Q0704000_D01200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "The stone of love\nfortune-telling...!");
    Message_Who(0);
    Message_MsgDisp("主人公", "What's wrong, ｛Hariya＊＊｝?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 4);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0704000_D01300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "H-Huh!? What!?");
    Message_Who(0);
    Message_MsgDisp("主人公", "You've been acting so weird for some\ntime now.");
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0704000_D01400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Well, that's because of you!");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(4, 3, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("Q0704000_D01500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "You would be surprised if you were\nsuddenly brought to such a place...\nYou would be surprised...");
    Character_BlinkStart(4, 0, (#1));
    Character_ChFace(0, 4, 0);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("Q0704000_D01600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Anyway, seriously...\nWhy did you bring us here?");
    Character_BlinkStart(4, 2, (#1));
    Voice_PlayVoice("Q0704000_D01700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Are you sure this is good?\nGive me a break.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(4, 2, (#1));
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("Q0704000_D01800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nAnswering with a question like that?");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0704000_D01900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Right, you start! Yeah...\nWell, let's pray to the God in that\narea!");
    Character_ChFace(0, 4, 0);
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0704000_D02000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I'll definitely send a money\noffering!\nI beg of you, God!");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("Q0704000_D02100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Seriously.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hariya＊＊｝...?)");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
