section "q16_m7_010"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(7, "M7_17F", 0);
    Background_Bg_GS2("BG_SCB50_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGG_016_000", 127, 40);
    Voice_PlayVoice("Q0707010_W00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Aaaah!! Found Waka-sama!!");
    Voice_PlayVoice("Q0707010_W00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student B", "Really!! Waka-sama～!");
    Message_Who(0);
    Message_MsgDisp("主人公", "...?");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("EV_07_12", #1, 0, 60);
    Screen_WipeIn(2);
    Environment_PlayME(2, "SN_BGD_011_000", 127, 40);
    Still_Approach(7, 190, 0, 0, 1, 1);
    Voice_PlayVoice("Q0707010_X00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Waka-sama, you're mean!\nCome with us!");
    Still_ApproachEnd();
    Voice_PlayVoice("Q0707010_W00300", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student B", "Come on～!\nHogging him is not allowed～!");
    Voice_PlayVoice("Q0707010_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Oh, no... How embarrassing.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(It doesn't seem that\nembarrassing...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, please go. It's fine with me.");
    Voice_PlayVoice("Q0707010_G00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "... Really?\nWell then, I'll go for just a\nmoment.");
    Still_Approach(7, 190, 0, 0, 1, 5);
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh.");
    Still_ApproachEnd();
    Background_Bg_GS2("BG_SCB50_LI_0", #1, #1, 0);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He's really gone...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(He hasn't returned, yet...\n｛Wakaouji＊＊｝ is quite weak\nwhen it comes to pushing...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Maybe he got lost at another place.\nI wonder if he's alone...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_SCB70_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(... It's boring waiting like this.\nMaybe it wasn't good for me to come\nto this field trip...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SCB60_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, the tour guide here went to\nmake a prayer for love...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Everyone seems to be happy...\nOf course, I'm the only lonely\none...)");
    Voice_PlayVoice("", 7, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝.");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(7, "M7_17F", 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(7, 2, (#1));
    Voice_PlayVoice("Q0707010_G00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I took the initiative.\nYou cannot look down on me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "But, everyone else?");
    Voice_PlayVoice("Q0707010_G00700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Aah, well... They've all scattered.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Is that okay?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0707010_G00800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It's not okay. However, I promised.\nWe'll go around together...\nJust the two of us.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...");
    Voice_PlayVoice("Q0707010_G00900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "... Yes.\nI bought a written fortune paper.\nI will give one to you.");
    Character_Chara_GS2(7, "NON");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(7, "M7_17F", 0);
    SoundEffect_PlayStream(3, "SS_DSE_165_000");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh, excellent luck! What...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(\"A lover will come.\")");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(7, 2, (#1));
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("Q0707010_G01000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "What? Please show it to Sensei.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I-It's not good...");
    Voice_PlayVoice("Q0707010_G01100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Hey, you are surprisingly stingy.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(This will be a good memory...)");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 61, 6);
    Parameter_AddCh1Param(7, 60, 3);
    Parameter_AddCh1Param(7, 62, #5);
    }
