section "q16_m5_010"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(5, "M5_01F", 0);
    Background_Bg_GS2("BG_SCB20_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("Q0705010_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah, right.\nI got something I wanna ask you.\nA once in a lifeline request.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uhh...\nDo you mean \"Once in a lifetime?\"");
    Voice_PlayVoice("Q0705010_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah, that.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("Q0705010_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "There's a place I wanna go to...\nWill you come with me?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay. Let's go.");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(5, 3, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("Q0705010_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yay. Let's move then.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(5, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Still_Event("EV_05_15", #1, 0, 60);
    Screen_WipeIn(2);
    Environment_PlayME(0, "SN_BGE_011_000", 127, 0);
    Music_PlayBGM(0, "MN_C_05_001_D00", 127, 40);
    Voice_PlayVoice("Q0705010_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "As expected, the real thing is\npretty.\nThe photos don't even compare to the\nreal thing.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Have you seen this place before,\n｛Chris＊＊｝?");
    Voice_PlayVoice("Q0705010_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "The first picture of Japan I saw was\nof this place.");
    Still_Approach(5, 133, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so?");
    Still_ApproachEnd();
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("Q0705010_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I've always wanted to see it, so I'm\nvery moved.\nThanks for coming along with me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "You're welcome.\nIs there anything else?");
    Voice_PlayVoice("Q0705010_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... There is.");
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("Q0705010_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "There's a temple where a young lady\nwent to great lengths to go to in\norder to purify herself.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Purification?");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("Q0705010_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "In other words, she cleaned her mind\nand body so that she could serve the\ngods.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh～.");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("Q0705010_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It took her 3 years.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("Q0705010_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nAfter that, she only lived to serve\nthe gods.");
    Voice_PlayVoice("Q0705010_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Even though I get to do what I want\nduring these 3 years, it's not like\nI hate work--");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("Q0705010_E01300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It's not anyone else's problem.\nBut since I was here, I really\nwanted to come...");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝?");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("Q0705010_E01400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Crap.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Voice_PlayVoice("Q0705010_E01500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It was so pretty that I almost\nforgot to take a picture of it.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("Q0705010_E01600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Let's get someone to take a photo of\nus here.");
    Still_Approach(5, 133, 0, 0, 1, 5);
    Voice_PlayVoice("Q0705010_E01700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "As a memory....\nA very important memory.");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Chris＊＊｝...)");
    Environment_StopME(0, 40);
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Still_Event("");
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 61, 6);
    Parameter_AddCh1Param(5, 60, 3);
    Parameter_AddCh1Param(5, 62, #5);
    }
