section "q16_m2_010"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(2, "M2_01F", 0);
    Background_Bg_GS2("BG_SCB20_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("Q0702010_B00000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "By the way, have you thought about\nwhere you wanna go?");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, I haven't decided...");
    Character_BlinkStart(2, 2, (#1));
    Voice_PlayVoice("Q0702010_B00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nThen do you want to come with me?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, of course! Where are we going?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q0702010_B00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "On a walk.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? A walk?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(2, 2, (#1));
    Voice_PlayVoice("Q0702010_B00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Yes.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(2, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Voice_PlayVoice("Q0702010_B00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "We can take a break here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Still_Event("EV_02_15", #1, 0, 60);
    Screen_WipeIn(2);
    Environment_PlayME(1, "SN_BGA_043_000", 127, 0);
    Music_PlayBGM(0, "MN_C_02_002_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "We walked quite a bit.");
    Still_StillFace(0, 2, 1);
    Voice_PlayVoice("Q0702010_B00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Are you exhausted already?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... No, nothing like that, why?");
    Voice_PlayVoice("Q0702010_B00600", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "*Chuckles*... I see.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah.... It's a beautiful place.");
    Still_StillFace(0, 2, 0);
    Voice_PlayVoice("Q0702010_B00700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "It is.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hey, is that a cherry blossom tree\non the coast over there?");
    Voice_PlayVoice("Q0702010_B00800", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Probably.");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's beautiful...");
    Message_Who(2);
    Message_MsgDisp("Shiba", ".............");
    Still_Approach(2, 43, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "... ｛Shiba＊＊｝?");
    Still_ApproachEnd();
    if (Parameter_GetCh1Param(2, 25) == 1){
        Voice_PlayVoice("Q0702010_B01000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... You're right.\nI think was thinking of making a\nsingle hit at Koushi Garden.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Is that so?");
        Voice_PlayVoice("Q0702010_B01100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Yeah. But I'll stop now.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Why?");
        Voice_PlayVoice("Q0702010_B01200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "It feels like this trip is just\nabout going to places....\nAt least, to me.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I see...");
        Still_StillFace(0, 2, 1);
        Voice_PlayVoice("Q0702010_B01300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "I'm going to Koushi Garden for\nbaseball.\nI want you to watch.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Shiba＊＊｝...");
        Voice_PlayVoice("Q0702010_B01400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... What? We should go soon.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay!");
        }
    else {
        Still_StillFace(0, 2, 1);
        Voice_PlayVoice("Q0702010_B01500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "..........\nYou don't think this walk was a\nfailure, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh?");
        Voice_PlayVoice("Q0702010_B01600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "We're usually sightseeing, right?\nVisiting the Shinto shrine\ntemples...");
        Voice_PlayVoice("Q0702010_B01700", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "I wanted to go, but you hadn't\ndecided on anything...");
        Still_StillFace(0, 2, 0);
        Voice_PlayVoice("Q0702010_B01800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Was the walk boring?");
        Message_Who(0);
        Message_MsgDisp("主人公", "With ｛Shiba＊＊｝?");
        Still_StillFace(0, 2, 1);
        Voice_PlayVoice("Q0702010_B01900", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Me.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes. Did you have fun?");
        Voice_PlayVoice("Q0702010_B02000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", ".............. I enjoyed it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Then there's no problem!");
        Voice_PlayVoice("Q0702010_B02100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Is that so?\nWe should get moving soon.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay!");
        }
    Music_StopBGM(0, 40);
    Environment_StopME(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Still_Event("");
    Message_CloseMsg();
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 61, 6);
    Parameter_AddCh1Param(2, 60, 3);
    Parameter_AddCh1Param(2, 62, #5);
    }
