section "q16_m3_000"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(3, "M3_01F", 0);
    Background_Bg_GS2("BG_SCB50_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGG_016_000", 127, 40);
    Voice_PlayVoice("Q0703000_C00000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "So this is the Golden Pavilion\ntemple...\nAs I thought, seeing it in the\ntextbook and the real thing makes a\ndifference.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, it's shining pretty intensely.");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("Q0703000_C00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Indeed so.\nThe real thing is no laughing\nmatter.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What? A laughing matter?");
    Voice_PlayVoice("Q0703000_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Indeed.\nWhen you see it in the textbook\npicture, it looks a lot like a toy.");
    Voice_PlayVoice("Q0703000_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Ancient people built unusual things\nto show off and blow minds away.");
    Message_Who(0);
    Message_MsgDisp("主人公", "...\nPerhaps, that's what made\n｛Hikami＊＊｝ laugh???");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0703000_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Haha, something like that....\nHowever, it reflects on the water\nwith such elegance.\nI am glad I came.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, me too!");
    Voice_PlayVoice("Q0703000_C00500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... Uh-oh, we have lost much time.\nIt seems as if we cannot any stay\nlonger.\nLet's carry on.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SCB70_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Wow...\nThe Kiyomizu stage is really high!\nIt's like you're being swallowed\nin...");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(3, 3, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("Q0703000_C00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "\"Great\"? \"Breezy\"? \"Odd\"?\nNo, none of those...");
    Message_Who(0);
    Message_MsgDisp("主人公", "What's wrong, ｛Hikami＊＊｝?");
    Character_BlinkStart(3, 0, (#1));
    Voice_PlayVoice("Q0703000_C00700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Huh?\nNothing, oh, I have been thinking on\nwhich one kanji character to\nrepresent this year.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh, you mean that!");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q0703000_C00800", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "They present it here every year,\ncorrect?\nTherefore, how should I say this...\nI am pondering on the conditions to\nreflect.");
    Message_Who(0);
    Message_MsgDisp("主人公", "*Giggles*...\nYou still have months to do so.\nThe world can still change, you\nknow?");
    Voice_PlayVoice("Q0703000_C00900", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Well, that is the hard part.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q0703000_C01000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "However, would you not think that it\nis nice to see the kanji you have\nthought of boldly written in such a\nplace?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm... Most likely.");
    Voice_PlayVoice("Q0703000_C01100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Right?\nI wonder what character will that\nbe.\nI am excited to know.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q0703000_C01200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... No!!\nThis is bad, we have lost very much\ntime.\nWe have to hurry to the Jishu\nShrine.");
    Voice_PlayVoice("", 3, "Q0703000_C01300");
    Message_Who(3);
    Message_MsgDisp("Hikami", "｛主人公｝, run fast!");
    Message_Who(0);
    Message_MsgDisp("主人公", "What～!?");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SCB60_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("Q0703000_C01400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "This spot is... only famous due...\nto the matchmaking...!");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see....\nHey, ｛Hikami＊＊｝...\nAre you alright...?");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(3, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0703000_C01500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... I-I am fine... I am alright!\nI was just catching my breath...\nHowever, we do not have much time\nleft.");
    Voice_PlayVoice("Q0703000_C01600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Therefore... 3 minutes max.\nPray with all your heart within the\ntimeframe.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? W-Wait, hold on a second...");
    Character_ChFace(0, 0, 3);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q0703000_C01700", 3, "Q0703000_C01701");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Here we go, ｛主人公｝.\nReady and now!!");
    Character_Chara_GS2(3, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(...\n｛Hikami＊＊｝ is such an\ninteresting person...)");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
