section "q32_g1_000"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(10, "G1_01F", 0);
    Background_Bg_GS2("BG_SCB80_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGG_016_000", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, souvenirs.\nDo you want to buy anything,\n｛Toudou＊＊｝?");
    Voice_PlayVoice("Q1010000_J00000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "It's too much of a hassle for me.\nIt's fine.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eeh, but why don't you look around\nsince we went through all the\ntrouble of coming here?");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(10, 3, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("Q1010000_J00100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "And if I bring back a bad souvenir\nor something?\nI'm okay.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hey, this Nishijin silk furoshiki is\nlovely!");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(10, 2, (#1));
    Voice_PlayVoice("Q1010000_J00200", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah, this bag smells lovely, too～.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q1010000_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Let me see...\nDon't you want to see them all for a\nbit?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q1010000_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "They're really quite nice.\nMaybe I'll have a little look...");
    Character_BlinkStart(10, 3, (#1));
    Voice_PlayVoice("Q1010000_J00500", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I'm going to go buy something for\nsomeone.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.\nThen I'll go take a look around,\ntoo.");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
