section "q33_g4_000"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(13, "G4_01F", 0);
    Background_Bg_GS2("BG_SCB80_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "I was waiting for you,\n｛Mizushima＊＊｝.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("", #1, "Q1113000_M00000");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "｛主人公｝.\nDid you find something nice?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes, I found a plain T-shirt for the\nkid next door.\nWhat about you,\n｛Mizushima＊＊｝?");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(13, 2, (#1));
    Voice_PlayVoice("Q1113000_M00100", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "I've got beanbags.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ooh, cute!\nA red bird and a blue bird.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("Q1113000_M00200", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "There's Adzuki beans inside.\nThe red bird increases love luck and\nthe blue bird summons good fortune.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(13, 0, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q1113000_M00300", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "A yellow bird brings up your luck\nwith money and the green bird...");
    Message_Who(0);
    Message_MsgDisp("主人公", "H-Hey... How many are there?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(13, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1113000_M00400", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "They had 16 colors altogether...\nDon't pity me like a child, okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "(*Giggles* That's so like\n｛Mizushima＊＊｝.)");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
