section "q33_m2_000"{
    Screen_WipeIn(2);
    Voice_PlayVoice("Q1102000_B00000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... My bad, I made you wait.");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, it's okay.\nWere you able to find anything?");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(2, "M2_01F", 0);
    Voice_PlayVoice("Q1102000_B00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", ".. I bought two of the same thing.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Really? What did you buy?");
    Character_BlinkStart(2, 3, (#1));
    Voice_PlayVoice("Q1102000_B00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...............");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝?");
    Character_BlinkStart(2, 2, (#1));
    Voice_PlayVoice("Q1102000_B00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... You should be pleased.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'll surely be pleased with a\nthoughtful gift.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(2, 2, (#1));
    Voice_PlayVoice("Q1102000_B00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Is that so? Then, here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh... Two... One for me?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q1102000_B00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Only if you're satisfied with having\nthe same one as me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Thank you, ｛Shiba＊＊｝!\nCan I open it?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q1102000_B00600", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Yeah.");
    SoundEffect_PlayStream(3, "SS_DSE_165_000");
    Message_Who(0);
    Message_MsgDisp("主人公", "... A strap?\nWah, it has a small wooden sword\nattached to it!");
    Character_BlinkStart(2, 2, (#1));
    Voice_PlayVoice("Q1102000_B00700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "It's not much, but I hope you'll use\nit.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I will, thank you.\nI will take good care of it.");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
