section "q33_m4_000"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(4, "M4_01F", 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("Q1104000_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Oh, you finished first.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah.\nHey, did you find anything you\nliked?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q1104000_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Good thing you asked!");
    Character_ChFace(0, 2, 1);
    Voice_PlayVoice("Q1104000_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "The local skull bear strap!\nIt's Kyoto's armored-version.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see, there's something like\nthat...");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("Q1104000_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "There is....\nSo, since I got impressed by it, I\nbought one for you, too.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh...");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 0);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1104000_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Just don't get the wrong idea!");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(4, 2, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("Q1104000_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "However...\nI just thought having matching sets\nwasn't such a bad idea...");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1104000_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... I mean, no!\nAnyway, feel free to use it. Okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, thank you. I'll treasure it.");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
