section "q33_g1_000"{
    Character_ChFace(0, 0, 3);
    Character_Chara_GS2(10, "G1_01F", 0);
    Background_Bg_GS2("BG_SCB80_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Toudou＊＊｝!\nSorry I'm late.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q1110000_J00000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "It's fine, nevermind that.\nI went to go look at various places,\nas well.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?\nSo you bought a souvenir, after all.");
    Character_ChFace(0, 2, 0);
    Voice_PlayVoice("Q1110000_J00100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Yes... For the junior girls at work.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so?\nI'm sure they'll be pleased!");
    Character_BlinkStart(10, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q1110000_J00200", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Everyone is always being nice.\nThis is just an expression of\ngratitude.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q1110000_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Everyone enjoys lovely things when\nthey are doing their best.");
    Message_Who(0);
    Message_MsgDisp("主人公", "You seem really popular with the\nfemale juniors,\n｛Toudou＊＊｝.");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(10, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1110000_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I am not particularly happy to be\npopular with the ladies...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ahaha!");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
