section "q33_m3_000"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(3, "M3_01F", 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("Q1103000_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Sorry to keep you waiting.");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, you didn't.... What did you buy?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q1103000_C00500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "For my parents, an assorted pack of\nochazuke.\nPerhaps they will appreciate the\nthought a little.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh, why?");
    Voice_PlayVoice("Q1103000_C00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Nothing, that is...\nWell, it is likely that they will\nlove it because it is food.\nAnd also... this one is for you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh, for me? ... Oh, a strap.\nIt comes with a Kompetou.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(3, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1103000_C00700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "That is correct!\nL-Look, girls usually say things\nlike \"This is cute.\", right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, I think it's cute.");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1103000_C00800", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Is that so? Then great!\nI knew for sure...\nit will fit your tastes.");
    Voice_PlayVoice("Q1103000_C00900", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Therefore, this one...\nYou and I will make this as our\nkeepsake for our field trip.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yours and mine?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(3, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1103000_C01000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Yes... actually, I bought two.\nUmm, the other one is for me...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Well, that means\n｛Hikami＊＊｝ and I have a\nmatching set, right?");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1103000_C01100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I-I am not sure if that's what you\nwould label it.");
    Voice_PlayVoice("Q1103000_C01200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "If I got this for myself, it may be\nseen as a rugged star...\nHowever, it is actually from a\nmatching pair...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(...?\nI wonder if he had trouble\nchoosing...)");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
