section "q33_g3_000"{
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(12, 3, (#1));
    Character_Chara_GS2(12, "G3_01F", 0);
    Background_Bg_GS2("BG_SCB80_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("Q1112000_L00000", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Thanks for waiting～!");
    Message_Who(0);
    Message_MsgDisp("主人公", "You bought a lot,\n｛Nishimoto＊＊｝!");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q1112000_L00100", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ah, you mean these.\nBought these souvenirs for home and\nwork.");
    Character_BlinkStart(12, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1112000_L00200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I wanted to try and have one for\nmyself from looking at it.\nJust for the heck of it.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(12, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1112000_L00300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Pampering oneself with Japanese\nsweets on a menu...\nHaha.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What!? You bought everything?");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("Q1112000_L00400", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Yeah, I couldn't decide on which one\nto buy...\nEveything just seemed so delicious.");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(12, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1112000_L00500", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ah～, a heavy load of happiness!");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Nishimoto＊＊｝...");
    Character_ChFace(0, 0, 3);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q1112000_L00600", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Well, don't mind them.\nLet's not mention these details,\nagain!");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(12, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q1112000_L00700", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "\"A journey of two women on a special\nfood trip indulges in Kyoto\".\nCould this place be the\nconclusion...?");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I feel the title has changed,\nthough...)");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
