section "q34_g3_000"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(12, "G3_01F", 0);
    Background_Bg_GS2("BG_SCB20_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "*Sigh*...\nThe field trip has come to an end.");
    Voice_PlayVoice("Q1212000_L00000", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "It seems like this year's field trip\ngot crowded with couples here and\nthere.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so?\nI never really thought about it...");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(12, 3, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("Q1212000_L00100", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Everyone seemed so active...\nSeems like a lot of students from\nour school were sitting along the\nriverbank.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What are your thoughts on that,\n｛Nishimoto＊＊｝?");
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1212000_L00200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "D...Don't be stupid.\nWhat are you implying?");
    Character_BlinkStart(12, 3, (#1));
    Voice_PlayVoice("Q1212000_L00300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I have already told you before that\nI'm not into that, right?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(12, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1212000_L00400", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "We enjoyed ourselves happily hanging\nout and wandering.\nHonestly, I had fun.");
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("Q1212000_L00500", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Thanks, ｛主人公｝!");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, thank you!");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("Q1212000_L00600", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "What about you?\nWas it okay that you hung out with\nme?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, I had loads of fun!\nI'd like to visit, again.");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(12, 2, (#1));
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("Q1212000_L00700", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "What～?\nThe next place I visit won't be\nKyoto～.");
    Message_Who(0);
    Message_MsgDisp("主人公", "*Giggles* I guess.");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(12, 60, 6);
    }
