section "q34_g1_000"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(10, "G1_01F", 0);
    Background_Bg_GS2("BG_SCB20_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Hah... It will finally end tomorrow.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("Q1210000_J00000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "It was more interesting than I\nthought.\nThanks to you, that is.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Me?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("Q1210000_J00100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I hate hanging out with people.\nAssociating with other girls is\ntroublesome.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(10, 3, (#1));
    Voice_PlayVoice("Q1210000_J00200", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "However, I am relaxed when I'm with\nyou.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? Really?");
    Character_BlinkStart(10, 0, (#1));
    Voice_PlayVoice("Q1210000_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "It would have been fine if I went to\nvisit places alone.\nAnyway, it was a precious field\ntrip.");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("Q1210000_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Visiting places with you gave me\nsome good memories.\nThank you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, it was my pleasure! I had fun.\nLet's hang out together, again!");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(10, 60, 6);
    }
