section "c01_m5_000"{
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetCh1Param(5, 514) == 0){
        SoundEffect_PlayStream(2, "SS_T_00_193_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Why is it so crowded over here...\nIf I don't hurry, I'll be late for\nthe next class!)");
        Character_Chara_GS2(5, "NON");
        Still_Event("EV_05_13", #1, 0, 30);
        SoundEffect_StopStream(2, 40);
        Voice_PlayVoice("D0305000_E00700", #1, "");
        Message_Who(5);
        Message_MsgDisp("？？？", "... Ah!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Eh!?)");
        Message_CloseMsg();
        Still_Approach(5, 137, 1, 1, 1, 1);
        Message_TextSpeed(8);
        Message_DispMsg(1);
        Screen_WipeOut(2);
        Still_Event("");
        SoundEffect_PlayStream(2, "SS_T_00_007_M00");
        System_Wait(50);
        Music_PlayBGM(0, "MN_X_02_D03_D00", 127, 40);
        SoundEffect_PlayStream(3, "SS_T_00_042_M00");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　\n　　　　　　　 *Kiss*\n　　　　　　　　　");
        Message_DispMsg(0);
        SoundEffect_StopStream(3, 40);
        SoundEffect_StopStream(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Kyaa!");
        Message_Who(0);
        Message_MsgDisp("主人公", "O-Ouch...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Just now...\nI felt like something soft hit my\nforehead...)");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(5, 2, (#1));
        Character_ChFace(0, 3, 4);
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("D0305000_E00100", #1, "");
        Message_Who(5);
        Message_MsgDisp("？？？", "Ouch... Sorry, can you stand?\nDid I hit your head?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I-I'm alright...");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("D0305000_E00200", #1, "");
        Message_Who(5);
        Message_MsgDisp("？？？", "Ah, thank goodness.\nWhat hit your forehead were my lips,\nthough.");
        Message_Who(0);
        Message_MsgDisp("主人公", "L...Lips!?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(5, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("D0305000_E00300", #1, "");
        Message_Who(5);
        Message_MsgDisp("？？？", "Ah, a cute girl. Lucky.");
        Voice_PlayVoice("D0305000_E00400", #1, "");
        Message_Who(5);
        Message_MsgDisp("？？？", "You're lucky, too.\nIt's a page in your book of\nwonderful memories.");
        Character_ChFace(0, 0, 11);
        Character_BlinkStart(5, 0, (#1));
        Voice_PlayVoice("D0305000_E00500", #1, "");
        Message_Who(5);
        Message_MsgDisp("？？？", "... Ah. Crap, I have to hurry.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(5, 3, (#1));
        Voice_PlayVoice("D0305000_E00600", #1, "");
        Message_Who(5);
        Message_MsgDisp("？？？", "Next time we meet, I'll give you a\ngreeting kiss.\nSo wait until then～!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(5, "NON");
        SoundEffect_PlayStream(2, "SS_T_00_004_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "... What was that?\nAnd what was the last thing he\nsaid...?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(\"I'll give you\"......\nI should stop thinking about it so\nmuch...)");
        SoundEffect_StopStream(2, 40);
        }
    else {
        SoundEffect_PlayStream(2, "SS_T_00_193_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Why is it so crowded over here...\nIf I don't hurry, I'll be late for\nthe next class!)");
        Character_Chara_GS2(5, "NON");
        Still_Event("EV_05_13", #1, 0, 30);
        SoundEffect_StopStream(2, 40);
        Voice_PlayVoice("D0305000_E00700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... Ah!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Eh!?)");
        Message_CloseMsg();
        Still_Approach(5, 137, 1, 1, 1, 1);
        Message_TextSpeed(8);
        Message_DispMsg(1);
        Screen_WipeOut(2);
        Still_Event("");
        SoundEffect_PlayStream(2, "SS_T_00_007_M00");
        System_Wait(50);
        Music_PlayBGM(0, "MN_X_02_D03_D00", 127, 40);
        SoundEffect_PlayStream(3, "SS_T_00_042_M00");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　\n　　　　　　　 *Kiss*\n　　　　　　　　　");
        Message_DispMsg(0);
        SoundEffect_StopStream(3, 40);
        SoundEffect_StopStream(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Kyaa!");
        Message_Who(0);
        Message_MsgDisp("主人公", "O-Ouch...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Just now...\nI felt like something soft hit my\nforehead...)");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(5, 2, (#1));
        Character_ChFace(0, 3, 4);
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("D0305000_E00800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ouch... Sorry, can you stand?\nDid I hit your head?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I-I'm alright...");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("D0305000_E00900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ah, thank goodness.\nWhat hit your forehead was my lips,\nthough.");
        Message_Who(0);
        Message_MsgDisp("主人公", "L...Lips!?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(5, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("D0305000_E01000", 5, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ah, ｛主人公｝.");
        Voice_PlayVoice("D0305000_E01100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Lucky.");
        Voice_PlayVoice("D0305000_E01200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "You're lucky, too.\nIt's a page in your book of\nwonderful memories.");
        Character_ChFace(0, 0, 11);
        Character_BlinkStart(5, 0, (#1));
        Voice_PlayVoice("D0305000_E01300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... Ah. Crap, I have to hurry.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(5, 3, (#1));
        Voice_PlayVoice("D0305000_E01400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Next time we meet, I'll give you a\ngreeting kiss.\nSo wait until then～!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(5, "NON");
        SoundEffect_PlayStream(2, "SS_T_00_004_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "... What was that?\nAnd what was the last thing he\nsaid...?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(\"I'll give you\"......\nI should stop thinking about it so\nmuch...)");
        Parameter_AddCh1Param(5, 86, 1);
        }
    SoundEffect_StopStream(2, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    SoundEffect_StopStream(0, 40);
    Music_StopBGM(0, 40);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 61, 6);
    Parameter_AddCh1Param(5, 60, 3);
    Parameter_AddCh1Param(5, 62, #5);
    }
