section "c01_m3_000"{
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetCh1Param(3, 514) != 1){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Oh no, my next class is in the\nmusic room.\nI have to hurry!)");
        SoundEffect_PlayStream(1, "SS_DSE_060_000", 127, 0);
        Message_CloseMsg();
        Screen_WipeOut(2);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Background_Bg_GS2("BG_SC220_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlaySE(701);
        Message_Who(0);
        Message_MsgDisp("　　　", "*Thud*");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah...!)");
        Screen_StartShakePlane(0, 32, 32, 0, 16);
        SoundEffect_PlayStream(2, "SS_T_00_200_M00");
        System_Wait(92);
        Character_Chara_GS2(3, "NON");
        Still_Event("EV_03_12", #1, 0, 30);
        Voice_PlayVoice("D0303000_C00900", #1, "");
        Message_Who(3);
        Message_MsgDisp("？？？", "... Look out!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Waaaaaaaaaaah!!");
        Message_CloseMsg();
        Still_Approach(3, 76, 1, 1, 1, 1);
        Message_TextSpeed(8);
        Message_DispMsg(1);
        Screen_WipeOut(2);
        Still_Event("");
        SoundEffect_StopStream(2, 40);
        SoundEffect_PlayStream(3, "SS_DSE_130_000");
        System_Wait(50);
        SoundEffect_PlayStream(2, "SS_T_00_042_M00");
        Music_PlayBGM(0, "MN_X_02_D03_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　\n　　　　　　　 *Kiss*\n　　　　　　　　　");
        Message_DispMsg(0);
        SoundEffect_StopStream(2, 40);
        SoundEffect_StopStream(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        System_Wait(30);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 1);
        Character_Chara_GS2(3, "M3_01F", 0);
        Background_Bg_GS2("BG_SC220_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("D0303000_C00100", #1, "");
        Message_Who(3);
        Message_MsgDisp("？？？", "... Are you all right!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ouch... Y-Yes... somewhat.");
        Voice_PlayVoice("D0303000_C00200", #1, "");
        Message_Who(3);
        Message_MsgDisp("？？？", "I see, thank goodness.\nBut I feel like I hit\nsomething.........\nAh!");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0303000_C00300", #1, "");
        Message_Who(3);
        Message_MsgDisp("？？？", "D-Did I h-hit you somewhere!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Rather than \"somewhere\", my whole\nbody...\nI-I'm sorry.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(3, 3, (#1));
        Character_ChFace(0, 3, 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0303000_C00400", #1, "");
        Message_Who(3);
        Message_MsgDisp("？？？", "No, it couldn't be helped and I\ndidn't mean it that way, y-you...");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(3, 3, (#1));
        Character_ChFace(0, 3, 4);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0303000_C00500", #1, "");
        Message_Who(3);
        Message_MsgDisp("？？？", "Did you...\nnot lose something i-important just\nnow!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Something important?\nNothing, really...\nAll my things are here...");
        Character_ChFace(0, 0, 0);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0303000_C00600", #1, "");
        Message_Who(3);
        Message_MsgDisp("？？？", "No, I didn't mean it in that way,\nnot at all...\nNo, it's nothing.");
        Message_Who(0);
        Message_MsgDisp("主人公", "?");
        Voice_PlayVoice("D0303000_C00700", #1, "");
        Message_Who(3);
        Message_MsgDisp("？？？", "Don't worry about it!\nI also won't worry about it.\nNow then, let's agree on it.");
        Character_ChFace(0, 0, 8);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0303000_C00800", #1, "");
        Message_Who(3);
        Message_MsgDisp("？？？", "... *Sigh* That's right.\nDon't run within the school.\nThat's all.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(3, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah... my body hurts...\nI did something bad to that\nperson...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Anyway, what did he mean by \"lose\nsomething important\"?)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Could it be that what I felt\nearlier was!\n...\nI shouldn't think about it too\nmuch.)");
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "(Oh no, my next class is in the\nmusic room.\nI have to hurry!)");
        SoundEffect_PlayStream(1, "SS_DSE_060_000", 127, 0);
        Message_CloseMsg();
        Screen_WipeOut(2);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Background_Bg_GS2("BG_SC220_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlaySE(701);
        Message_Who(0);
        Message_MsgDisp("　　　", "*Thud*");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah...!)");
        Screen_StartShakePlane(0, 32, 32, 0, 16);
        SoundEffect_PlayStream(2, "SS_T_00_200_M00");
        System_Wait(92);
        Character_Chara_GS2(3, "NON");
        Still_Event("EV_03_12", #1, 0, 30);
        Voice_PlayVoice("D0303000_C00900", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "... Look out!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Waaaaaaaaaaah!!");
        Message_CloseMsg();
        Still_Approach(3, 76, 1, 1, 1, 1);
        Message_TextSpeed(8);
        Message_DispMsg(1);
        Screen_WipeOut(2);
        Still_Event("");
        SoundEffect_StopStream(2, 40);
        SoundEffect_PlayStream(3, "SS_DSE_130_000");
        System_Wait(50);
        SoundEffect_PlayStream(2, "SS_T_00_042_M00");
        Music_PlayBGM(0, "MN_X_02_D03_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　\n　　　　　　　 *Kiss*\n　　　　　　　　　");
        Message_DispMsg(0);
        SoundEffect_StopStream(2, 40);
        SoundEffect_StopStream(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!?");
        System_Wait(30);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 1);
        Character_Chara_GS2(3, "M3_01F", 0);
        Background_Bg_GS2("BG_SC220_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("D0303000_C01000", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "... Are you all right!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ouch... Y-Yes... somewhat.");
        Voice_PlayVoice("D0303000_C01100", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I see, thank gosh.\nBut I feel like I hit\nsomething.........\nAh!");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0303000_C01200", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "D-Did I h-hit you somewhere!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Rather than \"somewhere\", my whole\nbody...\nI-I'm sorry.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(3, 3, (#1));
        Character_ChFace(0, 3, 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0303000_C01300", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "No, it couldn't be helped and I\ndidn't mean it that way, y-you...");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(3, 3, (#1));
        Character_ChFace(0, 3, 4);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0303000_C01400", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Did you...\nnot lose something i-important just\nnow!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Something important?\nNothing, really...\nAll my things are here...");
        Character_ChFace(0, 0, 0);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0303000_C01500", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "No, I didn't mean it in that way,\nnot at all...\nNo, it's nothing.");
        Message_Who(0);
        Message_MsgDisp("主人公", "?");
        Voice_PlayVoice("D0303000_C01600", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Don't worry about it!\nI also won't worry about it.\nNow then, let's agree on it.");
        Character_ChFace(0, 0, 8);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0303000_C01700", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "... *Sigh* That's right.\nDon't run within the school.\nThat's all.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(3, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah... my body hurts...\nI did something bad to\n｛Hikami＊＊｝...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Anyway, what did he mean by \"lose\nsomething important\"?)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Could it be that what I felt\nearlier was!\n...\nI shouldn't think about it too\nmuch.)");
        Parameter_AddCh1Param(3, 86, 1);
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Music_StopBGM(0, 40);
    Screen_ClearScreen();
    Parameter_AddCh1Param(3, 61, 6);
    Parameter_AddCh1Param(3, 60, 3);
    Parameter_AddCh1Param(3, 62, #5);
    }
