section "c01_m8_000"{
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetCh1Param(8, 514) != 1){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah.\nThe flowerbeds are blooming\nnicely...\nMaybe I should go and take a\nlook...)");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Background_Bg_GS2("BG_SC410_SP_0", #1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, there is a visitor. Who is it?)");
        SoundEffect_PlayStream(2, "SS_T_00_021_M00");
        Voice_PlayVoice("D0308000_H00000", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "... *Sigh*...\nWhy did I get caught...\nThey'll definitely get angry at\nme...\nI'm in a bind.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Umm...\nAre you troubled by something?");
        Character_Chara_GS2(8, "NON");
        Still_Event("EV_08_12", #1, 0, 30);
        SoundEffect_StopStream(2, 40);
        Voice_PlayVoice("D0308000_H00100", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Wah!");
        Message_CloseMsg();
        Still_Approach(8, 225, 1, 1, 1, 1);
        Message_TextSpeed(8);
        Message_DispMsg(1);
        Screen_WipeOut(2);
        Still_Event("");
        SoundEffect_PlayStream(2, "SS_T_00_007_M00");
        System_Wait(50);
        Music_PlayBGM(0, "MN_X_02_D03_D00", 127, 40);
        SoundEffect_PlayStream(3, "SS_T_00_042_M00");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　\n　　　　　　　 *Kiss*\n　　　　　　　　　");
        Message_DispMsg(0);
        SoundEffect_StopStream(3, 40);
        SoundEffect_StopStream(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Kyaa!");
        Background_Bg_GS2("BG_SC410_SP_0", #1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(There was something soft just now\non my lips...)");
        Character_ChFace(0, 0, 11);
        Character_Chara_GS2(8, "M8_01F", 0);
        Voice_PlayVoice("D0308000_H00200", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Sorry, I was surprised and stood up\nunintentionally...\nAre you all right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-Yes...");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(8, 2, (#1));
        Voice_PlayVoice("D0308000_H00300", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Ah, I dirtied your uniform...\nI'll pay the cleaning fee.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, it's okay! It's nothing much.");
        Character_BlinkStart(8, 0, (#1));
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("D0308000_H00400", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Really? That's fine then...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes.\nAre you perhaps from the florist?");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("D0308000_H00500", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Yeah.");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(8, 3, (#1));
        Voice_PlayVoice("D0308000_H00600", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "I came to deliver flowers, but my\nformer teacher made me do the\nflowerbeds...\nAh.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(8, 0, (#1));
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("D0308000_H00700", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "...\nDidn't you just ask if I was\ntroubled?");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Yes.");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("D0308000_H00800", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "It's almost done, so I'll leave the\nrest up to you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh!");
        Character_ChFace(0, 2, 2);
        Voice_PlayVoice("D0308000_H00900", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "I have to hurry and get back to the\nstore or I'll be yelled at...!");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("D0308000_H01000", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Just loosen the soil and you're\ndone.\nAh, and water it, too.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(8, 3, (#1));
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("D0308000_H01100", #1, "");
        Message_Who(8);
        Message_MsgDisp("？？？", "Ah, this is bad... Later!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(8, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, umm...!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He left...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(So, what I just felt...\nI'll try not to think about it too\nmuch...)");
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah.\nThe flowerbeds are blooming\nnicely...\nMaybe I should go and take a\nlook...)");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Background_Bg_GS2("BG_SC410_SP_0", #1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, there's a visitor... Hmm?\nIt's ｛Masaki＊＊｝!)");
        SoundEffect_PlayStream(2, "SS_T_00_021_M00");
        Voice_PlayVoice("D0308000_H01200", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "... *Sigh*...\nWhy did I get caught...\nThey'll definitely get angry at\nme...\nI'm in a bind.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Masaki＊＊｝!");
        Character_Chara_GS2(8, "NON");
        Still_Event("EV_08_12", #1, 0, 30);
        SoundEffect_StopStream(2, 40);
        Voice_PlayVoice("D0308000_H01300", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Wah!");
        Message_CloseMsg();
        Still_Approach(8, 225, 1, 1, 1, 1);
        Message_TextSpeed(8);
        Message_DispMsg(1);
        Screen_WipeOut(2);
        Still_Event("");
        SoundEffect_PlayStream(2, "SS_T_00_007_M00");
        System_Wait(50);
        Music_PlayBGM(0, "MN_X_02_D03_D00", 127, 40);
        SoundEffect_PlayStream(3, "SS_T_00_042_M00");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　\n　　　　　　　 *Kiss*\n　　　　　　　　　");
        Message_DispMsg(0);
        SoundEffect_StopStream(3, 40);
        SoundEffect_StopStream(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Kyaa!");
        Background_Bg_GS2("BG_SC410_SP_0", #1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ouch! ...\nThere was something soft just now on\nmy lips...)");
        Character_ChFace(0, 0, 11);
        Character_Chara_GS2(8, "M8_01F", 0);
        Voice_PlayVoice("D0308000_H01400", 8, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Sorry, I was surprised and stood\nunintentionally...\nHuh? ｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Geez, ｛Masaki＊＊｝...\nSuddenly standing up is abnormal...");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("D0308000_H01500", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "My bad!\nAnyway, it's a good thing you came～!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_ChFace(0, 2, 2);
        Voice_PlayVoice("D0308000_H01600", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "I'll leave the final touches of the\nflowerbed to you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh!");
        Character_BlinkStart(8, 3, (#1));
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("D0308000_H01700", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "I have to hurry back to the store or\nI'll face Arisawa's wrath...!");
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, Arisawa-san said to\nhurry and finish it...");
        Character_BlinkStart(8, 0, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("D0308000_H01800", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "See?\nJust loosen the soil and you're\ndone!\nOkay!");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("D0308000_H01900", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Ah, water it, too.\nAh, this is bad... Later!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(8, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Masaki＊＊｝ is in a\nhurry...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Anyway, what was that feeling\nbefore...)");
        Parameter_AddCh1Param(8, 86, 1);
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(8, 61, 6);
    Parameter_AddCh1Param(8, 60, 3);
    }
