section "c02_s2_000"{
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    if (Parameter_ChkHoliday(2) == 0){
        Background_Bg_GS2("BG_SC220_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("C0215000_O00000", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "Daisy, you awful girl...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, Himeko-senpai!");
        Character_Chara_GS2(15, "S2_01F", 0);
        Music_PlayBGM(0, "MN_C_15_000_D00", 127, 40);
        Voice_PlayVoice("C0215000_O00100", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "How are you?\n*Giggle*▼ Should I get straight to\nthe point?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh?");
        Character_Chara_GS2(15, "NON");
        Character_Chara_GS2(15, "S2_18F", 0);
        Voice_PlayVoice("C0215000_O00200", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "Himeko can see through you. I see...\nI see a bomb...");
        Message_Who(0);
        Message_MsgDisp("主人公", "A b-bomb!?");
        Character_Chara_GS2(15, "NON");
        Character_Chara_GS2(15, "S2_01F", 0);
        Voice_PlayVoice("C0215000_O00300", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "See here now, Daisy.\nAll men hold bombs in their hearts.");
        Voice_PlayVoice("C0215000_O00400", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "If you don't get along with someone,\nyou are surely hurting them...\nThat is your nature...");
        Message_Who(0);
        Message_MsgDisp("主人公", "No way... What should I do?");
        Voice_PlayVoice("C0215000_O00500", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "Listen carefully.");
        Voice_PlayVoice("C0215000_O00600", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "First, you should see how much they\nlike you.\nYou know how to do this, don't you?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Yeah.\nI can find out by asking Yuu-kun...)");
        Voice_PlayVoice("C0215000_O00700", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "The heartbroken person should surely\nhave a bomb mark.");
        Voice_PlayVoice("C0215000_O00800", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "If you notice a bomb, you should\ncall that person right away.\nThat should take care of it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I see...");
        Voice_PlayVoice("C0215000_O00900", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "But if you really want to be with\nthat person, you must spend lots of\ntime together.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Like dates or seeing them after\nschool...)");
        Character_Chara_GS2(15, "NON");
        Character_Chara_GS2(15, "S2_18F", 0);
        Voice_PlayVoice("C0215000_O01000", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "If you spend too much time with one\nperson, you'll get another bomb!\nLove-bomb hell!");
        Message_Who(0);
        Message_MsgDisp("主人公", "What!? No way! Then what should I...");
        Character_Chara_GS2(15, "NON");
        Character_Chara_GS2(15, "S2_19F", 0);
        Voice_PlayVoice("C0215000_O01100", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "I can't say, Daisy.\nThat is something you have to figure\nout.\n*Giggle*▼");
        Voice_PlayVoice("C0215000_O01200", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "If you listen closely, you can hear\nthe ticking of a bomb...");
        Voice_PlayVoice("C0215000_O01300", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "Hohoho! Bye now, devilish Daisy.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(15, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "She left...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I should check who I've hurt and\ncall them right away!)");
        }
    else {
        Background_Bg_GS2("BG_EX100_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("C0215000_O01400", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "Daisy, you awful girl...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, Himeko-senpai!");
        Character_Chara_GS2(15, "S2_01F", 0);
        Music_PlayBGM(0, "MN_C_15_000_D00", 127, 40);
        Voice_PlayVoice("C0215000_O01500", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "How are you?\n*Giggle*▼ Should I get straight to\nthe point?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh?");
        Character_Chara_GS2(15, "NON");
        Character_Chara_GS2(15, "S2_18F", 0);
        Voice_PlayVoice("C0215000_O01600", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "Himeko can see through you. I see...\nI see a bomb...");
        Message_Who(0);
        Message_MsgDisp("主人公", "A b-bomb!?");
        Character_Chara_GS2(15, "NON");
        Character_Chara_GS2(15, "S2_01F", 0);
        Voice_PlayVoice("C0215000_O01700", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "See here now, Daisy.\nAll men hold bombs in their hearts.");
        Voice_PlayVoice("C0215000_O01800", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "If you don't get along with someone,\nyou are surely hurting them...\nThat is your nature...");
        Message_Who(0);
        Message_MsgDisp("主人公", "No way... What should I do?");
        Voice_PlayVoice("C0215000_O01900", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "Listen carefully.");
        Voice_PlayVoice("C0215000_O02000", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "First you should see how much they\nlike you.\nYou know how to do this, don't you?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Yeah.\nI can find out by asking Yuu-kun...)");
        Voice_PlayVoice("C0215000_O02100", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "The heartbroken person should surely\nhave a bomb mark.");
        Voice_PlayVoice("C0215000_O02200", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "If you notice a bomb, you should\ncall that person right away.\nThat should take care of it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I see...");
        Voice_PlayVoice("C0215000_O02300", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "But if you really want to be with\nthat person, you must spend lots of\ntime together.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Like dates or seeing them after\nschool...)");
        Character_Chara_GS2(15, "NON");
        Character_Chara_GS2(15, "S2_18F", 0);
        Voice_PlayVoice("C0215000_O02400", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "If you spend too much time with one\nperson, you'll get another bomb!\nLove-bomb hell!");
        Message_Who(0);
        Message_MsgDisp("主人公", "What!? No way! Then what should I...");
        Character_Chara_GS2(15, "NON");
        Character_Chara_GS2(15, "S2_19F", 0);
        Voice_PlayVoice("C0215000_O02500", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "I can't say, Daisy.\nThat is something you have to figure\nout.\n*Giggle*▼");
        Voice_PlayVoice("C0215000_O02600", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "If you listen closely, you can hear\nthe ticking of a bomb...");
        Voice_PlayVoice("C0215000_O02700", #1, "");
        Message_Who(15);
        Message_MsgDisp("Hanatsubaki", "Hohoho! Bye now, devilish Daisy.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(15, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "She left...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I should check who I've hurt and\ncall them right away!)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
