section "e01_g1_202"{
    Background_Bg_GS2("BG_FP000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, it's ｛Toudou＊＊｝.\nAnd next to her is...\n｛Shiba＊＊｝?");
    Character_ChFace(0, 0, 8);
    Character_Chara_GS2(10, "G1_04F", 0);
    Character_Chara_GS2(2, "M2_??F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_10_000_D00", 127, 40);
    Voice_PlayVoice("E0110202_B00000", #1, "");
    Message_WindowPosition(1);
    Message_Who(2);
    Message_MsgDisp("Shiba", "Why did you see the need to get that\nangry?");
    Character_BlinkStart(10, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0110202_J00100", #1, "");
    Message_WindowPosition(0);
    Message_Who(10);
    Message_MsgDisp("Toudou", "... Well.");
    Character_BlinkStart(10, 0, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0110202_J00200", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "What's strange is that you were\nbeing so cold.");
    Character_BlinkStart(2, 3, (#1), 2);
    Message_WindowPosition(1);
    Message_Who(2);
    Message_MsgDisp("Shiba", "......");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Toudou＊＊｝!\n｛Shiba＊＊｝!");
    Character_ChFace(0, 0, 3);
    Message_WindowPosition(0);
    Message_Who(10);
    Message_MsgDisp("Toudou", "｛主人公｝.");
    Character_BlinkStart(2, 0, (#1), 2);
    Message_WindowPosition(1);
    Message_Who(2);
    Message_MsgDisp("Shiba", "......");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "What are you guys doing here?");
    Character_BlinkStart(10, 2, (#1));
    Voice_PlayVoice("E0110202_J01300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... ｛主人公｝.");
    Voice_PlayVoice("E0110202_J00600", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "If there was a guy who was\nmentioning stuff from your past and\nlooking for a fight, what would you\ndo?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...?");
    Character_ChFace(1, 2, 4);
    Character_ChFace(1, 3, 2);
    Voice_PlayVoice("E0110202_B00700", #1, "");
    Message_WindowPosition(1);
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Hey.");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("E0110202_J00800", #1, "");
    Message_WindowPosition(0);
    Message_Who(10);
    Message_MsgDisp("Toudou", "What I hate the most is saying \"It's\nnot like you\".");
    Voice_PlayVoice("E0110202_J00900", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "But what you did earlier was not\nlike you at all.");
    Character_ChFace(1, 2, 2);
    Character_BlinkStart(2, 3, (#1), 2);
    Character_ChFace(1, 3, 5);
    Voice_PlayVoice("E0110202_B01000", #1, "");
    Message_WindowPosition(1);
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Maybe.");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(10, 3, (#1));
    Character_ChFace(0, 3, 0);
    Message_WindowPosition(0);
    Message_Who(10);
    Message_MsgDisp("Toudou", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Eh?");
    Character_BlinkStart(10, 0, (#1));
    Message_WindowPosition(0);
    Voice_PlayVoice("E0110202_J01100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Let's go.\nI'll treat you to some tea.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, okay... But...");
    Character_BlinkStart(2, 0, (#1), 2);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0110202_B01200", #1, "");
    Message_WindowPosition(1);
    Message_Who(2);
    Message_MsgDisp("Shiba", "I'm fine. Don't worry.... Toudou.");
    Voice_PlayVoice("E0110202_J01300", #1, "");
    Message_WindowPosition(0);
    Message_Who(10);
    Message_MsgDisp("Toudou", "......");
    Character_BlinkStart(2, 2, (#1), 2);
    Voice_PlayVoice("E0110202_B01400", #1, "");
    Message_WindowPosition(1);
    Message_Who(2);
    Message_MsgDisp("Shiba", "Sorry.");
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("E0110202_J01500", #1, "");
    Message_WindowPosition(0);
    Message_Who(10);
    Message_MsgDisp("Toudou", "I don't recall needing to be\napologized to.");
    Character_BlinkStart(2, 3, (#1), 2);
    Voice_PlayVoice("E0110202_B01600", #1, "");
    Message_WindowPosition(1);
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Right. Later.");
    Character_Chara_GS2(2, "NON");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Toudou＊＊｝...\nIs this alright?\n｛Shiba＊＊｝...");
    Character_ChFace(0, 4, 0);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Character_BlinkStart(10, 3, (#1));
    Voice_PlayVoice("E0110202_J01700", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "...\nIt's something that you have to do\nwith your own strength...");
    Character_BlinkStart(10, 0, (#1));
    Voice_PlayVoice("E0110202_J01800", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "But I'm glad that you came.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Why?");
    Character_ChFace(0, 2, 1);
    Voice_PlayVoice("E0110202_J01900", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "If you hadn't come, he would have\nlashed out at me.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0110202_J02000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I'm sorry for using you as an\nexcuse.\nI really will treat you to some tea,\nso let's go.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay...");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(10, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I kind of feel like I was listening\nto an adult's conversation.)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 86, 1);
    Parameter_AddCh1Param(10, 86, 1);
    }
