section "e01_m6_212"{
    Background_Bg_GS2("BG_WF000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("E0106212_F00000", #1, "");
    Message_Who(6);
    Message_MsgDisp("？？？", "It's rare!");
    Voice_PlayVoice("E0106212_L00100", #1, "");
    Message_WindowPosition(1);
    Message_Who(6);
    Message_MsgDisp("？？？", "No, it's definitely baked!");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Arguing over there is...\n｛Amachi＊＊｝ and\n｛Nishimoto＊＊｝!?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hey, you two! What exactly happened?");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(6, "M6_??F", 0);
    Music_PlayBGM(0, "MN_C_06_000_D00", 127, 40);
    Voice_PlayVoice("E0106212_F00200", 6, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Ah, ｛主人公｝!");
    Character_ChFace(1, 0, 0);
    Character_Chara_GS2(12, "G3_04F", 0, 0, 1);
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "｛主人公｝!");
    Character_ChFace(1, 0, 8);
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("E0106212_L00300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Listen to this! This kid is strange!");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("E0106212_F00400", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "I'm not strange!");
    Message_Who(0);
    Message_MsgDisp("主人公", "W-Wait... What exactly happened?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0106212_F00500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I happened to bump into\nNishimoto-senpai at that cake\nstore...");
    Character_ChFace(1, 0, 3);
    Voice_PlayVoice("E0106212_L00600", #1, "");
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "The both of us had our eye on this\nparticular cake so we were really\nexcited, but...");
    Message_Who(0);
    Message_MsgDisp("主人公", "... But?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(6, 3, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("E0106212_F00700", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "The issue is with the cheesecake.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(1, 0, 8);
    Voice_PlayVoice("E0106212_L00800", #1, "");
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "This kid said a real stupid thing.\nHe said that only rare cheesecakes\nare real!");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("E0106212_F00900", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "What are you saying?\nBaked cheesecakes are heretical!");
    Voice_PlayVoice("E0106212_F01000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "The only way you can enjoy the\nnatural sweetness of cheese is\nthrough rare cheesecakes!");
    Character_ChFace(1, 2, 2);
    Character_BlinkStart(12, 3, (#1), 2);
    Character_ChFace(1, 3, 0);
    Voice_PlayVoice("E0106212_L01100", #1, "");
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "You're smitten by cheesecakes that\ndon't take long to make?\nThis is why amateurs trouble me...");
    Character_ChFace(1, 0, 8);
    Voice_PlayVoice("E0106212_L01200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Think about the time it takes to\nmake a baked cheesecake!\nDoesn't it take much longer!?");
    Voice_PlayVoice("E0106212_L01300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "And if there's none of that profound\ntexture, then it's not a cheesecake!");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(6, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0106212_F01400", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "That is a huge misunderstanding!\nThe moment when the rich sweetness\nof the cheese hits your tongue is\nbliss...");
    Character_BlinkStart(6, 0, (#1));
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("E0106212_F01500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "You can only taste that in rare\ncheesecakes!\nThat's why baked cheesecakes are\nheretical!");
    Character_BlinkStart(12, 2, (#1), 2);
    Character_ChFace(1, 4, 1);
    Voice_PlayVoice("E0106212_L01600", #1, "");
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "You said \"heretical\" again! What...\na seriously stubborn kid!");
    Character_BlinkStart(12, 0, (#1), 2);
    Voice_PlayVoice("E0106212_L01700", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "The one saying \"heretical\" is the\nheretic!\nThis damned heretic!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Both of you, stop arguing.\nIt's just cheesecake...");
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("E0106212_F01800", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "Just!?");
    Character_ChFace(1, 4, 0);
    Character_ChFace(1, 2, 1);
    Character_ChFace(1, 3, 4);
    Voice_PlayVoice("E0106212_L01900", #1, "");
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Cheesecake!?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh, um...");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("E0106212_F02000", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "You don't understand.\nCheesecakes are the royalty of\ncakes!");
    Character_ChFace(1, 2, 1);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0106212_L02100", #1, "");
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "No matter what kind of pastry chef\nyou are, not having cheesecake is\njust not allowed!");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(6, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0106212_F02200", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "It requires diligence, and it shows\nthe maker's skills...");
    Character_ChFace(1, 2, 1);
    Character_BlinkStart(12, 3, (#1), 2);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0106212_L02300", #1, "");
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "That's why it's next to impossible\nto taste the most supreme\ncheesecake!");
    Character_BlinkStart(6, 0, (#1));
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0106212_F02400", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "That is what cheesecakes are about!\nSaying \"Just cheesecake\" is being\nrude to cheesecakes!");
    Character_BlinkStart(12, 0, (#1), 2);
    Character_ChFace(1, 2, 1);
    Character_ChFace(1, 3, 2);
    Voice_PlayVoice("E0106212_L02500", #1, "");
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Right! It's rude!!\nDo you understand!?\nWhere's your \"yes\" response!?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yes...");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Amachi＊＊｝ and\n｛Nishimoto＊＊｝ kind of make a\ngood combination...)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(6, 86, 1);
    Parameter_AddCh1Param(12, 86, 1);
    }
