section "e01_m3_305"{
    Background_Bg_GS2("BG_NE000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("E0103305_C00000", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "Please step out of the way, I do not\nhave any spare time!");
    Voice_PlayVoice("E0103305_E00100", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "You don't have to speak in such an\nunfriendly way...");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh?\n｛Hikami＊＊｝ and\n｛Chris＊＊｝?)");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 5);
    Character_Chara_GS2(3, "M3_??F", 0);
    Character_ChFace(1, 0, 10);
    Character_Chara_GS2(5, "M5_??F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
    Voice_PlayVoice("E0103305_C00200", 3, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "Ah, ｛主人公｝.");
    Voice_PlayVoice("", 5, "E0103305_E00300");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "｛主人公｝. Hello.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hello. What's wrong? You're yelling.");
    Voice_PlayVoice("E0103305_C00400", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "... Will you tell him, too?\nWeatherfield-kun is trying to steal\naway my effort.");
    Character_ChFace(1, 2, 2);
    Character_ChFace(1, 3, 1);
    Voice_PlayVoice("E0103305_E00500", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "No, all I did was ask him to teach\nme some things that I didn't know\nabout English.");
    Character_BlinkStart(3, 3, (#1));
    Voice_PlayVoice("E0103305_C00600", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "You're always like this before\ntests.\nYou should give up asking me next\ntime.");
    Character_BlinkStart(5, 2, (#1), 2);
    Voice_PlayVoice("E0103305_E00700", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "No way...\nBut my mom will get really angry if\nI got a bad score on my English\ntest.");
    Voice_PlayVoice("E0103305_C00800", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "That is reaping what you sow.");
    Message_WindowPosition(1);
    Message_Who(0);
    Message_MsgDisp("主人公", "Calm down...\nBut isn't English your native\nlanguage, ｛Chris＊＊｝?");
    Character_BlinkStart(5, 0, (#1), 2);
    Character_ChFace(1, 3, 1);
    Voice_PlayVoice("E0103305_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "But the English used in the textbook\nand tests is different to real\nEnglish.");
    Voice_PlayVoice("E0103305_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "If you argue that it's normal, and I\nshould get good marks, then you guys\nshould also be getting goods marks\nfor Modern Languages.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes, well that's true, but...");
    Character_BlinkStart(3, 0, (#1));
    Voice_PlayVoice("E0103305_C01100", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "I have never once been troubled by\nthe Modern Language tests.");
    Character_ChFace(1, 0, 9);
    Character_BlinkStart(5, 3, (#1), 2);
    Voice_PlayVoice("E0103305_E01200", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "That's because you're smart,\nHikami-kun.\nYou're different to us.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Chris＊＊｝ said \"us\"...)");
    Character_BlinkStart(5, 0, (#1), 2);
    Voice_PlayVoice("E0103305_E01300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Anyway, you've got to have some\ntrouble with at least another\nsubject, right?");
    Voice_PlayVoice("E0103305_E01400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "When the test results are displayed\nHikami-kun's name is always at the\ntop...");
    Character_ChFace(1, 0, 3);
    Voice_PlayVoice("E0103305_E01500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Hey, how do you study?");
    Voice_PlayVoice("E0103305_E01600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Just teach me that, Hikami-sensei.");
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("E0103305_C01700", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "... What did you just...?");
    Voice_PlayVoice("E0103305_E01800", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "Hm? I said \"sensei\", Hikami-sensei.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(3, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0103305_C01900", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "Hikami...sensei... Hahaha...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hikami＊＊｝?)");
    Character_BlinkStart(3, 0, (#1));
    Voice_PlayVoice("E0103305_C02000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Alright, Weatherfield-kun.\nIf you're alright with studying\nuntil 5p.m, I will teach you!");
    Character_ChFace(1, 0, 10);
    Voice_PlayVoice("E0103305_E02100", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "Alright. Thank you, Hikami-sensei.\nI'm really glad.");
    Voice_PlayVoice("E0103305_C02200", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "There is no time to waste, let's go\nto the library.\nNow then, follow me!");
    Message_CloseMsg();
    Character_Chara_GS2(5, "NON");
    Character_Chara_GS2(3, "NON");
    Music_StopBGM(0, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hikami＊＊｝ is quite weak\nwhen he's being flattered...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(3, 86, 1);
    Parameter_AddCh1Param(5, 86, 1);
    }
