section "e01_m4_212"{
    Background_Bg_GS2("BG_EX100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("E0104212_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "I said I'm fine!");
    Voice_PlayVoice("E0104212_L00100", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("？？？", "As if...\nI'm not going to leave you alone!");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hariya＊＊｝ and\n｛Nishimoto＊＊｝ are fighting\nover there...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "What are you guys doing here?");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 4);
    Character_Chara_GS2(4, "M4_??F", 0);
    Music_PlayBGM(0, "MN_C_04_000_D00", 127, 40);
    Voice_PlayVoice("E0104212_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Ah, it's you...");
    Character_ChFace(1, 0, 8);
    Character_Chara_GS2(12, "G3_04F", 0, 0, 1);
    Voice_PlayVoice("", #1, "E0104212_L00300");
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "... ｛主人公｝!");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(4, 3, (#1));
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("E0104212_D00400", #1, "");
    Message_WindowPosition(0);
    Message_Who(4);
    Message_MsgDisp("Hariya", "This girl's so persistent.\nTry and reason with her, will you?");
    Voice_PlayVoice("E0104212_L00500", #1, "");
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "You don't have to say it like that!");
    Character_BlinkStart(4, 0, (#1));
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0104212_D00600", #1, "");
    Message_WindowPosition(0);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Just remember that you don't have to\ndo this kinda thing for me!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Both of you calm down...\nWhat happened?");
    Character_ChFace(1, 2, 2);
    Character_ChFace(1, 3, 4);
    Voice_PlayVoice("E0104212_L00700", #1, "");
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I heard that Harry's throat was\nhurting lately, so I made some onion\njuice for him.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Onion juice...?");
    Voice_PlayVoice("E0104212_L00800", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Because Harry said that onions were\ngood for the throat...");
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("E0104212_D00900", #1, "");
    Message_WindowPosition(0);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Are you an idiot?\nNo matter how good it is for my\nthroat, there's no way I'd drink\nsuch a gross looking thing!");
    Voice_PlayVoice("E0104212_L01000", #1, "");
    Message_WindowPosition(1);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Come on, just try one mouthful of\nit...");
    Character_ChFace(0, 4, 0);
    Character_BlinkStart(4, 3, (#1));
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("E0104212_D01100", #1, "");
    Message_WindowPosition(0);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Ah, screw this!\nYou take care of her!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh, wait, ｛Hariya＊＊｝!");
    Message_CloseMsg();
    Character_Chara_GS2(4, "NON");
    Music_StopBGM(0, 40);
    System_Wait(30);
    Character_ChMove(12, 1);
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("E0104212_L01200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Geez!\nIt only smells a little bit～...");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(12, 2, (#1), 1);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("E0104212_L01300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "... Wah! Gross～!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(As I thought...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    Parameter_AddCh1Param(12, 86, 1);
    }
