section "e01_g3_410"{
    Background_Bg_GS2("BG_WF100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?\n｛Nishimoto＊＊｝ and\n｛Toudou＊＊｝ are over\nthere.");
    Character_ChFace(0, 0, 8);
    Character_Chara_GS2(12, "G3_04F", 0);
    Character_ChFace(1, 2, 1);
    Character_ChFace(1, 3, 2);
    Character_Chara_GS2(10, "G1_04F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_12_000_D02", 127, 40);
    Voice_PlayVoice("E0112410_J00000", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "That skirt...\nDo you really plan on buying it?");
    Voice_PlayVoice("E0112410_L00100", #1, "");
    Message_WindowPosition(0);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "O-Of course!\nI had planned on buying it from the\nstart!");
    Voice_PlayVoice("E0112410_L00200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "You shouldn't say such things to me!\nEspecially when I just happened to\nmeet you at the store!");
    Character_ChFace(1, 0, 3);
    Character_BlinkStart(10, 3, (#1), 2);
    Voice_PlayVoice("E0112410_J00300", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "...\nI only said it because from an\nobjective point of view, I don't\nthink it suits you.");
    Character_ChFace(1, 2, 1);
    Character_BlinkStart(10, 2, (#1), 2);
    Voice_PlayVoice("E0112410_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "You thought so too, which is why you\nasked me for my opinion, right?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("E0112410_L00500", #1, "");
    Message_WindowPosition(0);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ugh...\nSaying hurtful things really gets to\nme...!");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("E0112410_L00600", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Anyway, the skirt is featured in all\nthe magazines as being in style...\nIt's also a limited item!");
    Voice_PlayVoice("E0112410_J00700", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "It's fine if you buy things because\nof that, but it's also okay to buy\nthings because they suit you.");
    Character_ChFace(1, 0, 3);
    Character_BlinkStart(10, 3, (#1), 2);
    Voice_PlayVoice("E0112410_J00800", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "But I don't recommend it.\nThat's all I will say.");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("E0112410_L00900", #1, "");
    Message_WindowPosition(0);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ugh...");
    Character_Chara_GS2(10, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Nishimoto＊＊｝.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0112410_L01000", #1, "E0112410_L01001");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ah, ｛主人公｝!\nHey, this skirt, what do you think\nof it?\nDoesn't it suit me!?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm～...\nIt's a little different from your\nimage.");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(12, 3, (#1));
    Voice_PlayVoice("E0112410_L01100", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "... A-As expected...\nArgh, how annoying!\nIf only I were a little more\nglamorous!");
    Character_BlinkStart(12, 0, (#1));
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0112410_L01200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I'm still not there, yet...\nBut as expected, that person\nlikes...");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0112410_L01300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "That manner of speaking is really\nhonest!\nI also heard that she's popular at\nschool.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(12, 3, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0112410_L01400", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "...\nAlthough she's s...scary, maybe I\nshould try applying to be her\napprentice?");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("E0112410_L01500", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "... It might be a good idea.\nI'll ask her when I'm feeling\ncourageous.\nI'll see you later,\n｛主人公｝!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yeah.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(12, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(They might actually make a good\nteacher and student pair...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(12, 86, 1);
    Parameter_AddCh1Param(10, 86, 1);
    }
