section "e01_m1_216"{
    Background_Bg_GS2("BG_NE100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? Over there is...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "Master!");
    Character_ChFace(0, 0, 10);
    Character_Chara_GS2(16, "S3_17F", 0);
    Voice_PlayVoice("E0101216_P00000", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "Oh, it's you. Hello.\nAre you out shopping?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.\nAre you also out shopping, Master?\nUmm, are you alone?");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("E0101216_P00100", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "I had intended to be alone, but Teru\nfound me.");
    Message_CloseMsg();
    Character_ChMove(16, 1);
    Character_Chara_GS2(1, "M1_??F", 0);
    Music_PlayBGM(0, "MN_C_01_000_D02", 127, 40);
    Voice_PlayVoice("E0101216_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Grandpa, that silver set we saw\nearlier--");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, you're here too,\n｛Saeki＊＊｝.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("E0101216_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "You too... Why are you here?");
    Character_ChFace(1, 0, 8);
    Character_BlinkStart(16, 2, (#1), 2);
    Voice_PlayVoice("E0101216_P00400", #1, "");
    Message_WindowPosition(1);
    Message_Who(16);
    Message_MsgDisp("Master", "Hey, that's no way to talk to a\nwoman.");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, it's fine!\nI just happened to be passing by.\nAre you shopping together?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0101216_A00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Well, it's not like we always shop\ntogether.\nGrandpa has been having lower back\npain since last night.");
    Message_WindowPosition(1);
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh!? Are you alright?");
    Character_ChFace(1, 0, 3);
    Voice_PlayVoice("E0101216_P00600", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "Ah, it's not such a big deal.\nIt just comes with old age.");
    Voice_PlayVoice("E0101216_A00700", #1, "");
    Message_WindowPosition(0);
    Message_Who(1);
    Message_MsgDisp("Saeki", "Despite your age, you act as if\nyou're young.");
    Voice_PlayVoice("E0101216_P00800", #1, "");
    Message_WindowPosition(1);
    Message_Who(16);
    Message_MsgDisp("Master", "I'm sorry about that....\nRight, if it's alright with you,\nwould you like to come by the store?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that alright?\nEven though it's your day off.");
    Character_ChFace(1, 0, 10);
    Voice_PlayVoice("E0101216_P00900", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "It's an apology for hearing Teru's\nabusive language.\nWe will make coffee for you.\nRight, Teru?");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(1, 2, (#1));
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("E0101216_A01000", #1, "");
    Message_WindowPosition(0);
    Message_Who(1);
    Message_MsgDisp("Saeki", "Pfft, do what you want. I'm leaving!");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Character_Chara_GS2(1, "NON");
    Character_ChMove(16, 1);
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(16, 2, (#1), 1);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("E0101216_P01100", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "*Sigh* Good grief, only his body has\ngrown.\nHe's still a child... isn't he?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha.\nBut you two seem to get along really\nwell.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0101216_P01200", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "Even though you saw that, he's a\nnice kid.\nHe works really hard for the\nstore...\nLet's go, or Teru will make a fuss.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay!");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    }
