section "e01_g1_500"{
    Background_Bg_GS2("BG_WF000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? Over there is...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Toudou＊＊｝!");
    Character_Chara_GS2(10, "G1_04F", 0);
    Music_PlayBGM(0, "MN_C_10_000_D00", 127, 40);
    Voice_PlayVoice("E0110500_J00000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Ah, ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What are you doing, shopping?");
    Voice_PlayVoice("E0110500_J00100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "No, I'm going to school now.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh, even though it's our day off?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(10, 2, (#1));
    Voice_PlayVoice("E0110500_J00200", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I say school, but I mean nail art\nschool.\nI'm doing my best to learn.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so!");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(10, 3, (#1));
    Voice_PlayVoice("E0110500_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Actually, doing it properly is quite\ndifficult.");
    Character_BlinkStart(10, 0, (#1));
    Character_ChFace(0, 2, 1);
    Voice_PlayVoice("E0110500_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "But that's what gets me fired up.");
    Message_Who(0);
    Message_MsgDisp("主人公", "That seems like you,\n｛Toudou＊＊｝.");
    Character_ChFace(0, 2, 4);
    Voice_PlayVoice("E0110500_J00500", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Really? ... Ah, right.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0110500_J00600", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Let me practice doing your nails\nnext time.\nI'm not that great at it, but I can\ndo it better than those amateurs.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sure! I'm looking forward to it!");
    Voice_PlayVoice("E0110500_J00700", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Later.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Do your best!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(10, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Toudou＊＊｝ looks like\nshe's really enjoying it.)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(10, 86, 1);
    }
