section "e01_m3_211"{
    Background_Bg_GS2("BG_NES40_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh?\nOver there in front of the book\nstore is...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hikami＊＊｝!");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(3, 2, (#1));
    Character_ChFace(0, 3, 5);
    Character_Chara_GS2(3, "M3_??F", 0);
    Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
    Voice_PlayVoice("E0103211_C00000", 3, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Eh? ...\nAh, it's you, ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Are you looking for something?");
    Voice_PlayVoice("E0103211_C00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Yes, I am looking for \"Koujuen\".\nI've heard people talking about it\nat school lately.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Koujuen?\nI've also heard about that...\nIs that the name of a book?");
    Voice_PlayVoice("E0103211_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Actually, I don't know myself.\nJudging from the name, I think it\nwas perhaps a newly released\ndictionary.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0103211_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "But Hanegasaki Academy students\ndon't often talk about dictionaries,\nright?");
    Voice_PlayVoice("E0103211_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "That's why I wanted to see it, by\nall means.\nBut it is not here.\nI wonder where it would be?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm, I wonder....\nAh, over there is\n｛Onoda＊＊｝.\n｛Onoda＊＊｝!");
    Character_Chara_GS2(11, "G2_04F", 0, 0, 1);
    Voice_PlayVoice("E0103211_K00500", #1, "E0103211_K00501");
    Message_WindowPosition(1);
    Message_Who(11);
    Message_MsgDisp("Onoda", "Ah! ｛主人公｝.\nAnd Hikami-kun.\nWhat are you two doing?");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hikami＊＊｝ is looking for\nsomething.");
    Voice_PlayVoice("E0103211_C00600", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "Yes, \"Koujuen\".\nDo you know of it, Onoda?");
    Character_ChFace(1, 2, 0);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0103211_K00700", #1, "");
    Message_WindowPosition(1);
    Message_Who(11);
    Message_MsgDisp("Onoda", "Yes, \"Koujuen\". I do know.\nPlease wait a little while.");
    Character_Chara_GS2(11, "NON");
    SoundEffect_PlayStream(3, "SS_T_00_209_M00");
    Message_CloseMsg();
    Screen_WipeOut(2);
    SoundEffect_PlayStream(3, "SS_T_00_088_M00");
    Screen_WipeIn(2);
    Character_ChFace(1, 0, 10);
    Character_Chara_GS2(11, "G2_04F", 0, 0, 1);
    Voice_PlayVoice("E0103211_K00800", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Here it is.\nIt's a new brand type of Japanese\ntea, \"Koujuen\"!\nHere you go, Hikami-kun.");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("E0103211_C00900", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "Eh, Japanese tea!?");
    Message_Who(0);
    Message_MsgDisp("主人公", "T-That's what it seems like...");
    Voice_PlayVoice("E0103211_K01000", #1, "");
    Message_WindowPosition(1);
    Message_Who(11);
    Message_MsgDisp("Onoda", "Yes, it's the name of a\nlong-standing tea plantation.\nIt's become a hot topic lately.\nWas I of any use?");
    Voice_PlayVoice("E0103211_C01100", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "......... T-Thank you, Onoda.");
    Character_BlinkStart(11, 2, (#1), 2);
    Voice_PlayVoice("E0103211_K01200", #1, "");
    Message_WindowPosition(1);
    Message_Who(11);
    Message_MsgDisp("Onoda", "You are welcome....\nThis tea is nice, it's a little\nsweet but it has a refreshing\naftertaste.");
    Character_BlinkStart(11, 0, (#1), 2);
    Voice_PlayVoice("E0103211_K01300", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "I would be happy if Hikami-kun liked\nit, too....\nNow then, I have business to attend\nto.");
    Character_Chara_GS2(11, "NON");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0103211_C01400", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "So it was this...");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hikami＊＊｝...");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0103211_C01500", 3, "E0103211_C01501");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... What a nice name.\nI must hurry home and try it out.\nExcuse me, ｛主人公｝.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(3, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Maybe I should also bring some\nhome...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(3, 86, 1);
    Parameter_AddCh1Param(11, 86, 1);
    }
