section "e01_m1_504"{
    Background_Bg_GS2("BG_NE000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? Over there is...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝!\n｛Hariya＊＊｝!");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(1, "M1_??F", 0);
    Character_ChFace(1, 2, 1);
    Character_Chara_GS2(4, "M4_??F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_01_000_D02", 127, 40);
    Voice_PlayVoice("", 4, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "｛主人公｝.");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("E0101504_A00000", #1, "");
    Message_WindowPosition(0);
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ack...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Why are you saying \"ack\"...?\nWhere are the two of you going?\nAh, guitars?");
    Voice_PlayVoice("E0101504_D00100", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "It's...");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("E0101504_A00200", #1, "");
    Message_WindowPosition(0);
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ah, don't tell her--");
    Character_ChFace(1, 0, 3);
    Voice_PlayVoice("E0101504_D00300", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "He was really enthusiastic about\ngoing to a studio and playing\ntogether with the drums.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah, you're becoming more serious\nabout it!");
    Character_ChFace(1, 2, 2);
    Voice_PlayVoice("E0101504_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Not at all.\nHe's not bad at remembering things,\nbut his sense of rhythm is...");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(1, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("E0101504_A00500", #1, "");
    Message_WindowPosition(0);
    Message_Who(1);
    Message_MsgDisp("Saeki", "I don't have any.... I'm sorry.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see.\n｛Saeki＊＊｝ is good at\neverything, so this is a little\nrare, right?");
    Character_ChFace(1, 0, 3);
    Voice_PlayVoice("E0101504_D00600", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Isn't it about time you quit?\nIt's okay to not do the things\nyou're bad at, right?");
    Character_ChFace(0, 4, 0);
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(1, 3, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0101504_A00700", #1, "");
    Message_WindowPosition(0);
    Message_Who(1);
    Message_MsgDisp("Saeki", "No way.\nWhat you like and what you're good\nat are two different things.");
    Character_ChFace(1, 2, 2);
    Character_ChFace(1, 3, 5);
    Voice_PlayVoice("E0101504_D00800", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "... But you know.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah.");
    Character_ChFace(1, 2, 5);
    Character_BlinkStart(4, 3, (#1), 2);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0101504_D00900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It can't be helped.\nHarry-sensei should start teaching\nyou seriously now!");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(1, 2, (#1));
    Voice_PlayVoice("E0101504_A01000", #1, "");
    Message_WindowPosition(0);
    Message_Who(1);
    Message_MsgDisp("Saeki", "Wait a second....\nHariya, up until now, you--");
    Character_BlinkStart(4, 0, (#1), 2);
    Voice_PlayVoice("E0101504_D01100", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "I'm not going to hold back from now\non!\nLet's go!");
    Character_Chara_GS2(4, "NON");
    Character_BlinkStart(1, 0, (#1));
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0101504_A01200", #1, "");
    Message_WindowPosition(0);
    Message_Who(1);
    Message_MsgDisp("Saeki", "That punk...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, but ｛Hariya＊＊｝ is a\ngood friend, isn't he?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(1, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0101504_A01300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Maybe... Well, I'm going now.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(1, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay! Do your best!");
    Voice_PlayVoice("E0101504_D01400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Come on, hurry up!\nAnd call me \"Harry\" already!");
    Voice_PlayVoice("E0101504_A01500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "No way.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's great that\n｛Saeki＊＊｝ made a\nfriend.)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    Parameter_AddCh1Param(4, 86, 1);
    }
