section "e01_m7_500"{
    Background_Bg_GS2("BG_NE100_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? Over there is...)");
    Character_Chara_GS2(7, "M7_06F", 0);
    Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝!");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("", 7, "E0107500_G00000");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝.\nIt's fine, it's fine.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("E0107500_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Sensei isn't on out-of-school-\nmanagement duty today.\nIt's fine.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, I see...\n｛Wakaouji＊＊｝, are you out\nshopping today?");
    Character_BlinkStart(7, 0, (#1));
    Voice_PlayVoice("E0107500_G00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "That's right.\nWell, rather than shopping, I am\npurchasing.");
    Character_ChFace(0, 2, 2);
    Voice_PlayVoice("E0107500_G00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "The restaurant near my place is\nclosing for a week, as the owners\nare going overseas, so I thought to\nprepare my own dinner.");
    Message_Who(0);
    Message_MsgDisp("主人公", "That must be difficult.\nWhat will you be making,\n｛Wakaouji＊＊｝?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0107500_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Rather than making, I'm mostly\nstocking up on canned tuna.\nI'll eat it with my rice.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, for a whole week?");
    Character_ChFace(0, 4, 1);
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(7, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0107500_G00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Well, yes.");
    Message_Who(0);
    Message_MsgDisp("主人公", "......");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(7, 0, (#1));
    Voice_PlayVoice("E0107500_G00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Ah, should I also buy canned\nmackerel?");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, should we\nthink up a menu together?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0107500_G00700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Ah, that would help me out.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Maybe it would be better if\n｛Wakaouji＊＊｝ hurried up and\ngot married?)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 86, 1);
    }
