section "e01_g4_410"{
    Background_Bg_GS2("BG_WF200_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "... Huh?\nOver there is ｛Mizushima＊＊｝\nand ｛Toudou＊＊｝?");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(13, 2, (#1));
    Character_Chara_GS2(13, "G4_04F", 0);
    Character_ChFace(1, 2, 1);
    Character_ChFace(1, 3, 3);
    Character_Chara_GS2(10, "G1_04F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_13_000_D00", 127, 40);
    Voice_PlayVoice("E0113410_J00000", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "You hide your real self...\nNot even God realizes that you're\ndisguising your real self.");
    Voice_PlayVoice("E0113410_M00100", #1, "");
    Message_WindowPosition(0);
    Message_Who(13);
    Message_MsgDisp("Mizushima", "You haven't changed, have you\nTatsuko?\nDon't you think you should be a\nlittle more mature?");
    Character_BlinkStart(10, 3, (#1), 2);
    Character_ChFace(1, 3, 0);
    Voice_PlayVoice("E0113410_J00200", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "Unfortunately, I'm not like you, I\nlack the ability.\nSorry for not flattering you like a\nmale would.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0113410_M00300", #1, "");
    Message_WindowPosition(0);
    Message_Who(13);
    Message_MsgDisp("Mizushima", "I'd love to remind you of your\nmanners, but I have practice now.");
    Character_ChFace(1, 0, 8);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0113410_J00400", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "How coincidental.\nI don't have the time, either.\nI'm not the one boasting that I have\npractice, though.");
    Character_Chara_GS2(10, "NON");
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("E0113410_M00500", #1, "");
    Message_WindowPosition(0);
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Good grief...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(W-What should I do?\nI may have stumbled across an\ninteresting conversation...)");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("E0113410_M00600", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "!? ... Who is it?");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(13, 2, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0113410_M00700", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "... Were you eavesdropping?");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, I didn't hear a thing!");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("E0113410_M00800", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "...... Really?");
    Message_Who(0);
    Message_MsgDisp("主人公", "U-Um... Only a little.");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("E0113410_M00900", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "*sigh*...\nDon't misunderstand, and just\nlisten, okay?\nTatsuko and I've had a bit of a\nthing since middle school.");
    Message_Who(0);
    Message_MsgDisp("主人公", "A bit of a thing...?");
    Character_BlinkStart(13, 0, (#1));
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0113410_M01000", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "It's nothing.\nMy junior and Tatsuko's junior got\ninto a fight...");
    Voice_PlayVoice("E0113410_M01100", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Then, Tatsuko and I thought to\nnegotiate to reach an agreement,\nbut...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Agreement......?)");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("E0113410_M01200", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "All I heard from Tatsuko was her\nsaying she wanted a settlement...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(A settlement......?)");
    Character_BlinkStart(13, 0, (#1));
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0113410_M01300", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "When I was younger, I learned Aikido\nand Kendo, and then...");
    Message_Who(0);
    Message_MsgDisp("主人公", "H-Hmm... and then?");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("E0113410_M01400", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "I can't talk anymore, I'm making my\nteacher wait!\nCurse that Tatsuko!\nI'll see you later.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, later...");
    Music_StopBGM(0, 40);
    Character_ChMove(13, 0);
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0113410_M01500", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "This... is a secret, okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yes!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(13, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I'll try not to get into an\nargument with\n｛Mizushima＊＊｝...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(13, 86, 1);
    Parameter_AddCh1Param(10, 86, 1);
    }
