section "e01_m5_100"{
    Background_Bg_GS2("BG_NE000_?_0", 1, #1, 0);
    Character_Chara_GS2(5, "M5_??F", 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh, it's ｛Chris＊＊｝.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝!");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("E0105100_E00000", 5, "E0105100_E00001");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah, ｛主人公｝. Hello.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hello. What are you doing here?");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("E0105100_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I was looking for someone who would\nmodel for a painting, but no one\nwill do it.");
    Character_BlinkStart(5, 3, (#1));
    Voice_PlayVoice("E0105100_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I wonder why...?");
    Message_Who(0);
    Message_MsgDisp("主人公", "What did you say to them?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0105100_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "\"Please be a model for my painting\".");
    Voice_PlayVoice("E0105100_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "\"You're pretty, so I'd definitely\npaint you in the nude\".");
    Message_Who(0);
    Message_MsgDisp("主人公", ".........");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("E0105100_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Wah.");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("E0105100_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah, everyone looked at me with the\nsame eyes that you have now.\nWhy is that?");
    Character_BlinkStart(5, 3, (#1));
    Voice_PlayVoice("E0105100_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Aren't peoples' bodies more\nbeautiful when they're not wearing\nclothes?\nSeriously...");
    Message_Who(0);
    Message_MsgDisp("主人公", "That may be so, but saying that to\npeople you're meeting for the first\ntime is a little...");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("E0105100_E00800", 5, "E0105100_E00801");
    Message_Who(5);
    Message_MsgDisp("Chris", "......... ｛主人公｝....\nWhat did you just say?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0105100_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Then it's okay if it's not a person\nI've met for the first time?");
    Message_Who(0);
    Message_MsgDisp("主人公", "!!!");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0105100_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Then maybe I should ask you▼");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh! I'm no model...!");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("E0105100_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "You won't do it? Is it no good?\nThere's no one left to ask, but you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ugh...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0105100_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "If you don't like the nude idea then\nsemi-nude is fine.");
    Message_Who(0);
    Message_MsgDisp("主人公", "No!");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(5, 2, (#1));
    Voice_PlayVoice("E0105100_E01300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\n*Sigh*");
    Character_BlinkStart(5, 3, (#1));
    Voice_PlayVoice("E0105100_E01400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Then I guess I should give up...\nGoodbye...");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(5, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He left...\n｛Chris＊＊｝ looked quite\ndown.\nI wonder if he'll be okay?)");
    Voice_PlayVoice("E0105100_E01500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah, please be a model for me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(.........)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    }
