section "e01_m7_100"{
    Background_Bg_GS2("BG_NE100_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's a little late.\nI should hurry back home.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? Over there is...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝!");
    Character_Chara_GS2(7, "M7_17F", 0);
    Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
    Voice_PlayVoice("", 7, "E0107100_G00000");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝.\nWhat a coincidence. Hello.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hello. Are you out shopping?");
    Voice_PlayVoice("E0107100_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "No, Sensei is on out of school\nmanagement duty.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh!?\n\"Out of school management\", then I\nshould run...");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("E0107100_G00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Ah, that's right. Hey!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes? Um...");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0107100_G00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "If I shall explain, that \"Hey\" just\nnow carried the meaning of \"Hurry up\nand go home\"...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yes! Crap, I have to hurry home!");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("E0107100_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "You don't have to worry about me.\nI know that even if I say it, it\nholds no power of persuasion.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Um, ｛Wakaouji＊＊｝.\nPlease do your best, okay?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(7, 2, (#1));
    Voice_PlayVoice("E0107100_G00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Thank you.\nNow then, please be careful on your\nway home.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes. Goodbye!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(7, "NON");
    Voice_PlayVoice("E0107100_G00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Hey... Hey! *erhem*... Hey!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝ doesn't seem\nlike he suits an angry persona...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 86, 1);
    }
