section "e01_g2_203"{
    Background_Bg_GS2("BG_NE000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Onoda＊＊｝!");
    Character_ChFace(0, 0, 11);
    Character_Chara_GS2(11, "G2_04F", 0);
    Music_PlayBGM(0, "MN_C_11_000_D02", 127, 40);
    Voice_PlayVoice("E0111203_K00000", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Wah!! ｛主人公｝?");
    Message_Who(0);
    Message_MsgDisp("主人公", "What are you doing?\nAre you waiting for someone?");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0111203_K00100", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "N-No! I'm going to tutoring...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so?\nI was so sure that you were waiting\nfor someone...\nAh.");
    Character_Chara_GS2(3, "M3_??F", 0, 0, 1);
    Voice_PlayVoice("", 3, "E0111203_C00200");
    Message_WindowPosition(1);
    Message_Who(3);
    Message_MsgDisp("Hikami", "｛主人公｝, Onoda.\nI didn't expect to meet you here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hikami＊＊｝.\nAh, are you also going to tutoring,\n｛Hikami＊＊｝?");
    Voice_PlayVoice("E0111203_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Yes.");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(11, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("E0111203_K00400", #1, "");
    Message_WindowPosition(0);
    Message_Who(11);
    Message_MsgDisp("Onoda", "No, you're wrong!\nDon't say weird things!");
    Message_Who(0);
    Message_MsgDisp("主人公", "......?");
    Character_BlinkStart(11, 0, (#1));
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0111203_K00500", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "So if I leave from my house, point\nA, and Hikami leaves from his house,\npoint B, we arrive at the tutoring\nschool, point C...");
    Character_ChFace(1, 2, 4);
    Character_ChFace(1, 3, 2);
    Voice_PlayVoice("E0111203_C00600", #1, "");
    Message_WindowPosition(1);
    Message_Who(3);
    Message_MsgDisp("Hikami", "Onoda.\nI do not understand what you are\ntalking about.");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(11, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("E0111203_K00700", #1, "");
    Message_WindowPosition(0);
    Message_Who(11);
    Message_MsgDisp("Onoda", "I-In other words... You're wrong!\nIt's a coincidence! I'm going first!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(11, "NON");
    Voice_PlayVoice("E0111203_K00701", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Gya!");
    Message_Who(0);
    Message_MsgDisp("主人公", "She left... How strange.");
    Message_CloseMsg();
    Character_ChMove(3, 1);
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0111203_C00800", #1, "");
    Message_WindowPosition(0);
    Message_Who(3);
    Message_MsgDisp("Hikami", "That reminds me, whenever I go to\ntutor, I often unexpectedly bump\ninto her here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so?");
    Voice_PlayVoice("E0111203_C00900", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Yeah. About twice a week.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(... Unexpectedly?)");
    Character_BlinkStart(3, 2, (#1), 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0111203_C01000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Right, if that is the case, then you\ndo not have to think too hard about\nit to figure it out...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yeah.");
    Character_BlinkStart(3, 3, (#1), 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0111203_C01100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Onoda surely lives around this area.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... I wonder?");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(3, 2, (#1), 1);
    Voice_PlayVoice("E0111203_C01200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "It must be the case.\nOh, I must hurry! Farewell!");
    Character_Chara_GS2(3, "NON");
    Music_StopBGM(0, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, do your best studying,\n｛Hikami＊＊｝!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(But ｛Onoda＊＊｝ seemed\ndifferent from usual...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(3, 86, 1);
    Parameter_AddCh1Param(11, 86, 1);
    }
