section "e01_m6_100"{
    Background_Bg_GS2("BG_NE100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetCh1Param(6, 130) < 3){
        Voice_PlayVoice("", 6, "E0106100_F00000");
        Message_Who(6);
        Message_MsgDisp("？？？", "Hello, ｛主人公｝.");
        Character_Chara_GS2(6, "M6_??F", 0);
        Music_PlayBGM(0, "MN_C_06_000_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Amachi＊＊｝.\nAre you out shopping?");
        Voice_PlayVoice("E0106100_F00100", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Yes, at the book store.\nThere's a magazine that I want....\nIt's this.");
        Character_BlinkStart(6, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("E0106100_F00200", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "\"Habataki Watcher\".\nThey chose 10 different sweets in\nHabataki City for this month's\nspecial coverage!");
        Message_Who(0);
        Message_MsgDisp("主人公", "\"Sweets\"... you mean confectionary?");
        Voice_PlayVoice("E0106100_F00300", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Yes.\nI had a brief read of the magazine\nin the store...");
        Character_BlinkStart(6, 3, (#1));
        Voice_PlayVoice("E0106100_F00400", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "But just looking at any of the\nsweets made me really happy, because\nthey all look yummy.");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("E0106100_F00500", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "I might try going out next week to\nsome of the stores.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Amachi＊＊｝ really likes\nsweet food.)");
        Music_StopBGM(0, 40);
        }
    else {
        Voice_PlayVoice("", 6, "");
        Message_Who(6);
        Message_MsgDisp("？？？", "｛主人公｝!");
        Character_Chara_GS2(6, "M6_??F", 0);
        Music_PlayBGM(0, "MN_C_06_000_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Amachi＊＊｝.\nAre you out shopping?");
        Voice_PlayVoice("E0106100_F00600", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Yes, at the book store.\nThere was a magazine I wanted....\nTake a look!");
        Character_ChFace(0, 4, 0);
        Character_BlinkStart(6, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("E0106100_F00700", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "\"Habataki Watcher\".");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(6, 3, (#1));
        Voice_PlayVoice("E0106100_F00800", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "In this month's special coverage,\nthey choose 10 kinds of sweets in\nHabataki City!");
        Message_Who(0);
        Message_MsgDisp("主人公", "\"Sweets\"... you mean confectionary?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("E0106100_F00900", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Right!\nI read the magazine briefly in the\nstore...");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(6, 2, (#1));
        Character_ChFace(0, 3, 3);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("E0106100_F01000", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "But all of the sweets seemed yummy.\nJust looking at it was the best!");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("E0106100_F01100", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Right, doesn't this fluffy Chiffon\ncake look particularly yummy?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Amachi＊＊｝ really likes\nsweet food.)");
        }
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(6, 86, 1);
    }
