section "e01_g2_510"{
    Background_Bg_GS2("BG_NE000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Now then, it's about time I go\nhome...\nHuh, ｛Onoda＊＊｝?)");
    Character_Chara_GS2(11, "G2_04F", 0);
    Voice_PlayVoice("E0111510_K00000", #1, "E0111510_K00001");
    Message_Who(11);
    Message_MsgDisp("Onoda", "......? ｛主人公｝.\nAre you out shopping?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah.\nWhat about you,\n｛Onoda＊＊｝?");
    Voice_PlayVoice("E0111510_K00100", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "I'm returning from prep school.\nHey, if it's alright with you--");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_Who(10);
    Message_MsgDisp("？？？", "｛主人公｝.");
    Character_Chara_GS2(11, "NON");
    Music_StopBGM(0, 40);
    System_Wait(20);
    Character_Chara_GS2(10, "G1_04F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_10_000_D00", 127, 40);
    Message_WindowPosition(1);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Toudou＊＊｝.\nAre you out shopping?");
    Voice_PlayVoice("E0111510_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Yeah. You too?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes, that's right.");
    Character_ChFace(1, 2, 0);
    Character_ChFace(1, 3, 2);
    Voice_PlayVoice("E0111510_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... Hm?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Character_Chara_GS2(11, "G2_04F", 0);
    Voice_PlayVoice("E0111510_K00500", #1, "");
    Message_WindowPosition(0);
    Message_Who(11);
    Message_MsgDisp("Onoda", "H-Hello.");
    Character_ChFace(1, 0, 11);
    Voice_PlayVoice("E0111510_J00600", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "Ah.... You're \"Chobi\", right?");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("E0111510_K00700", #1, "");
    Message_WindowPosition(0);
    Message_Who(11);
    Message_MsgDisp("Onoda", "Eh? N-No, I'm not.\nI am Onoda Chiyomi.");
    Character_ChFace(1, 0, 10);
    Voice_PlayVoice("E0111510_J00800", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "As I thought.\nYou're smart, aren't you, Chobi?\nMizushima told me.");
    Character_ChFace(0, 0, 3);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("E0111510_K00900", #1, "");
    Message_WindowPosition(0);
    Message_Who(11);
    Message_MsgDisp("Onoda", "W-Well, I am not that smart.");
    Voice_PlayVoice("E0111510_J01000", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "She said that if I stood next to\nyou, I'd be shocked.\nYou really are small.\nIt kind of makes me want to give you\ncandy...");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("E0111510_K01100", #1, "");
    Message_WindowPosition(0);
    Message_Who(11);
    Message_MsgDisp("Onoda", "Even if I was bigger, my height is\nnothing special!\nAnd my name is Chiyomi.");
    Character_ChFace(1, 2, 4);
    Character_ChFace(1, 3, 2);
    Voice_PlayVoice("E0111510_J01200", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "...\nBut Mizushima also calls you\n\"Chobi\", right?");
    Character_BlinkStart(11, 2, (#1));
    Voice_PlayVoice("E0111510_K01300", #1, "");
    Message_WindowPosition(0);
    Message_Who(11);
    Message_MsgDisp("Onoda", "I thought Mizushima-san would do\nthat!\nShe's spreading around a weird\nnickname!");
    Character_ChFace(1, 0, 10);
    Voice_PlayVoice("E0111510_J01400", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "Isn't it fine? \"Chobi\" suits you.\nRight?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? U-Umm～...");
    Character_BlinkStart(11, 0, (#1));
    Voice_PlayVoice("E0111510_K01500", #1, "");
    Message_WindowPosition(0);
    Message_Who(11);
    Message_MsgDisp("Onoda", "It doesn't suit me! I am Chiyomi!");
    Voice_PlayVoice("E0111510_J01600", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "Now then, it's about time I go.\nLater.");
    Character_Chara_GS2(10, "NON");
    Character_BlinkStart(11, 3, (#1));
    Voice_PlayVoice("E0111510_K01700", #1, "");
    Message_WindowPosition(0);
    Message_Who(11);
    Message_MsgDisp("Onoda", "I don't like this kind of people.\nJust because they're a little\ntaller, they act so proud!");
    SoundEffect_PlayStream(3, "SS_T_00_009_M00");
    Character_ChFace(1, 2, 4);
    Character_ChFace(1, 3, 1);
    Character_Chara_GS2(10, "G1_04F", 0, 0, 1);
    Voice_PlayVoice("E0111510_J01800", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "Hey!!");
    Character_BlinkStart(11, 0, (#1));
    Character_ChFace(0, 2, 4);
    Voice_PlayVoice("E0111510_K01900", #1, "");
    Message_WindowPosition(0);
    Message_Who(11);
    Message_MsgDisp("Onoda", "!!");
    Character_ChFace(1, 7, 0);
    Character_ChFace(1, 0, 10);
    Character_BlinkStart(10, 2, (#1), 2);
    Character_Chara_GS2(10, "NON");
    Voice_PlayVoice("E0111510_J02000", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "Ahahaha! Later, Chobi!");
    Music_StopBGM(0, 40);
    Character_ChFace(0, 7, 0);
    Character_ChFace(0, 4, 1);
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(11, 2, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0111510_K02100", #1, "");
    Message_WindowPosition(0);
    Message_Who(11);
    Message_MsgDisp("Onoda", "Ugh...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Haha, but it seems like\n｛Toudou＊＊｝ likes\n｛Onoda＊＊｝.)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(11, 86, 1);
    Parameter_AddCh1Param(10, 86, 1);
    }
