section "e01_m2_304"{
    Background_Bg_GS2("BG_NE000_?_0", 1, #1, 0);
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(2, "M2_??F", 0);
    Character_ChFace(1, 0, 0);
    Character_Chara_GS2(4, "M4_??F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_02_000_D03", 127, 40);
    Screen_WipeIn(2);
    Voice_PlayVoice("", 2, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... ｛主人公｝.");
    Voice_PlayVoice("E0102304_D00100", 4, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yo, ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh, ｛Shiba＊＊｝ and\n｛Hariya＊＊｝.\nWhat are you two up to?");
    Character_ChFace(0, 4, 0);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 2);
    Message_WindowPosition(0);
    Message_Who(2);
    Message_MsgDisp("Shiba", "......");
    Character_ChFace(1, 4, 0);
    Character_ChFace(1, 2, 4);
    Character_BlinkStart(4, 2, (#1), 2);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0102304_D00300", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "We're going to Karaoke BOX now.");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(2, 2, (#1));
    Voice_PlayVoice("E0102304_B00400", #1, "");
    Message_WindowPosition(0);
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Like I said, I'm not going.");
    Character_ChFace(1, 0, 8);
    Voice_PlayVoice("E0102304_D00500", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Whatever!\nGive me a reason then, a reason.");
    Character_BlinkStart(2, 3, (#1));
    Voice_PlayVoice("E0102304_B00600", #1, "");
    Message_WindowPosition(0);
    Message_Who(2);
    Message_MsgDisp("Shiba", "Training.\nIf I don't run, my body will weaken.");
    Character_ChFace(1, 2, 2);
    Character_ChFace(1, 3, 4);
    Voice_PlayVoice("E0102304_D00700", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Ugh! If you say that...");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0102304_B00800", #1, "");
    Message_WindowPosition(0);
    Message_Who(2);
    Message_MsgDisp("Shiba", "Later...");
    Character_Chara_GS2(2, "NON");
    Character_ChFace(1, 0, 3);
    Voice_PlayVoice("E0102304_D00900", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Ah, wait a second.");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(2, "M2_??F", 0);
    Voice_PlayVoice("E0102304_B01000", #1, "");
    Message_WindowPosition(0);
    Message_Who(2);
    Message_MsgDisp("Shiba", "... What is it?");
    Voice_PlayVoice("E0102304_D01100", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Let me join you, as well.");
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("E0102304_B01200", #1, "");
    Message_WindowPosition(0);
    Message_Who(2);
    Message_MsgDisp("Shiba", "... In what?");
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0102304_D01300", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("Hariya", "In your training.\nIt's linked to my voice training!");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("E0102304_D01400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Alright, now that we've decided,\nlet's go get ready!");
    Character_ChFace(1, 2, 1);
    Voice_PlayVoice("E0102304_D01500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Shiba!\nI'll meet you at your place, so get\nready and wait for me!");
    Character_Chara_GS2(4, "NON");
    Voice_PlayVoice("E0102304_D01600", 4, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Later, ｛主人公｝!");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "He left...\nIs this okay, ｛Shiba＊＊｝?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0102304_B01700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Hmm? ... Yeah.\nThat guy is actually quite into it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Really?");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(2, 3, (#1));
    Voice_PlayVoice("E0102304_B01800", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nBecause the both of us have\nsomething we're aiming for.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("E0102304_B01900", 2, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Later, ｛主人公｝.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(2, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Shiba＊＊｝ and\n｛Hariya＊＊｝.\nThey seem like an interesting pair.)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 86, 1);
    Parameter_AddCh1Param(4, 86, 1);
    }
