section "e01_g3_311"{
    Background_Bg_GS2("BG_EX100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?\n｛Nishimoto＊＊｝ and\n｛Onoda＊＊｝ are over\nthere.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Nishimoto＊＊｝,\n｛Onoda＊＊｝!");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(12, "G3_04F", 0);
    Character_ChFace(1, 0, 0);
    Character_Chara_GS2(11, "G2_04F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_12_000_D02", 127, 40);
    Voice_PlayVoice("E0112311_L00000", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ah, ｛主人公｝.");
    Voice_PlayVoice("E0112311_K00100", #1, "");
    Message_WindowPosition(1);
    Message_Who(11);
    Message_MsgDisp("Onoda", "Hello.");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "What are you guys doing here?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("E0112311_L00200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "It's almost time for the Student\nCouncil elections, right?");
    Voice_PlayVoice("E0112311_L00300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "She said that she's running for the\nSecretary position, so I'm giving\nher advice.");
    Character_BlinkStart(12, 0, (#1));
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0112311_L00400", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "First of all, your hairstyle!\nLet's go for a sudden image change.");
    Character_ChFace(1, 2, 3);
    Character_ChFace(1, 3, 2);
    Voice_PlayVoice("E0112311_K00500", #1, "");
    Message_WindowPosition(1);
    Message_Who(11);
    Message_MsgDisp("Onoda", "I think my hairstyle has nothing to\ndo with elections or being a\nsecretary.\nRight, ｛主人公｝?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, well, that might be true...");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("E0112311_L00600", #1, "");
    Message_WindowPosition(0);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "No, no!\nFirst impressions are crucial for\nelections.\nYou want to be elected, don't you?");
    Character_ChFace(1, 0, 3);
    Character_BlinkStart(11, 3, (#1), 2);
    Voice_PlayVoice("E0112311_K00700", #1, "");
    Message_WindowPosition(1);
    Message_Who(11);
    Message_MsgDisp("Onoda", "... Yes, well...");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(12, 3, (#1));
    Voice_PlayVoice("E0112311_L00800", #1, "");
    Message_WindowPosition(0);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Honestly speaking, your hairstyle\nlooks like something an old lady\nfrom Osaka would have.");
    Character_BlinkStart(11, 0, (#1), 2);
    Character_ChFace(1, 2, 4);
    Character_ChFace(1, 3, 2);
    Voice_PlayVoice("E0112311_K00900", #1, "");
    Message_WindowPosition(1);
    Message_Who(11);
    Message_MsgDisp("Onoda", "An o...old lady!?");
    Character_BlinkStart(12, 0, (#1));
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("E0112311_L01000", #1, "");
    Message_WindowPosition(0);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Yeah!");
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0112311_L01100", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "So, let's go with the strategy to\nshow that you are a mature female!\nWe'll go for a \"Kobe Twist\"!");
    Voice_PlayVoice("E0112311_K01200", #1, "");
    Message_WindowPosition(1);
    Message_Who(11);
    Message_MsgDisp("Onoda", "What is a \"Kobe Twist\"? Is it food?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(12, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0112311_L01300", #1, "");
    Message_WindowPosition(0);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ah～...\nI guess it means that I'll have to\nstart explaining from there...");
    Character_ChFace(1, 2, 1);
    Character_BlinkStart(11, 2, (#1), 2);
    Voice_PlayVoice("E0112311_K01400", #1, "");
    Message_WindowPosition(1);
    Message_Who(11);
    Message_MsgDisp("Onoda", "... You don't need to explain.\nPlease eat the \"Kobe Twist\" by\nyourself.\nI am leaving. Excuse me.");
    Character_Chara_GS2(11, "NON");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("E0112311_L01500", #1, "");
    Message_WindowPosition(0);
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ah, wait a second.\nThere's still more!");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("E0112311_L01600", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ah, she's so fast.\nIt's because she's tiny.");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(12, 3, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0112311_L01700", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Hmm...\nAs expected, I want to see her with\na \"Kobe Twist\"...");
    Character_BlinkStart(12, 0, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0112311_L01800", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Alright, I'll try pressuring her to\nget it.\nSee you later,\n｛主人公｝!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(12, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(The insistent ｛Nishimoto＊＊｝\nand the escaping\n｛Onoda＊＊｝...\nThey actually make a good duo.)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(12, 86, 1);
    Parameter_AddCh1Param(11, 86, 1);
    }
