section "e01_m8_500"{
    Background_Bg_GS2("BG_NE100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh?\nThe person that's running towards me\nis...\n｛Masaki＊＊｝?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Masaki＊＊｝!");
    Message_CloseMsg();
    Character_ChFace(0, 0, 10);
    Character_Chara_GS2(8, "M8_??F", 0, 0, 1);
    Character_ChMove(8, 1);
    Music_PlayBGM(0, "MN_C_08_000_D00", 127, 40);
    Voice_PlayVoice("", 8, "E0108500_H00000");
    Message_Who(8);
    Message_MsgDisp("Masaki", "｛主人公｝!\nYou showed up at a good time!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(8, 3, (#1));
    Voice_PlayVoice("E0108500_H00100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I'm begging you!\nPlease go out with me!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh!?");
    Character_BlinkStart(8, 0, (#1));
    Voice_PlayVoice("E0108500_H00200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "To the special sale that is only\navailable at this time of day!");
    Message_Who(0);
    Message_MsgDisp("主人公", "T...Timed sales...?\nYou mean at the supermarket?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("E0108500_H00300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "There are only 500 packs of instant\nramen, 5 packs for 1 Rich.\nIt's limited to 5 packs per person!");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0108500_H00400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Alright, this will guarantee me 50\npacks...\nI won't be missing a meal for a\nwhile with these...");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(8, 2, (#1));
    Voice_PlayVoice("E0108500_H00500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I wondered what I should do since\nArisawa relentlessly refused!\nYou're really helping me out!");
    Voice_PlayVoice("E0108500_H00600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Let's go!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(8, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(But I didn't even say one word\nabout going...\nAh, whatever.)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(8, 86, 1);
    }
