section "e01_m8_100"{
    Background_Bg_GS2("BG_NE100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Is that... ｛Masaki＊＊｝?)");
    Character_Chara_GS2(8, "M8_01F", 0);
    Music_PlayBGM(0, "MN_C_08_000_D00", 127, 40);
    Voice_PlayVoice("E0108100_H00000", 8, "E0108100_H00001");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Oh, ｛主人公｝.\nAre you by yourself?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("E0108100_H00100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "What a lonely person you are.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uh...\nAnyway, what are you doing,\n｛Masaki＊＊｝?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0108100_H00200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I'm right in the middle of document\ncollection.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Documents... you say?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(8, 3, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("E0108100_H00300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I have to submit a report for a\nseminar....\n10 A4 pages.");
    Voice_PlayVoice("E0108100_H00400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "And I can only do it when I have a\nday off work.\nThat's why I have to use this free\ntime effectively.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...");
    Character_BlinkStart(8, 2, (#1));
    Voice_PlayVoice("E0108100_H00500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Ah.\nBut I can't work hard if I'm\nhungry...\nI wonder if I can keep up...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Masaki＊＊｝ seems like he\nhas it rough studying and doing his\ndaily activities...)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(8, 86, 1);
    }
