section "e01_g2_100"{
    Background_Bg_GS2("BG_WF100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(I'm done shopping.\nIt's still too early to go home,\nI'll go around to other stores.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? Over there is...)");
    Character_Chara_GS2(11, "G2_04F", 0);
    Music_PlayBGM(0, "MN_C_11_000_D02", 127, 40);
    Voice_PlayVoice("", #1, "E0111100_K00000");
    Message_Who(11);
    Message_MsgDisp("Onoda", "｛主人公｝. Hello.");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's you, ｛Onoda＊＊｝.\nAre you shopping?");
    Voice_PlayVoice("E0111100_K00100", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Yeah, for a hair ribbon.\nI still haven't decided on which one\nto get...");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(11, 3, (#1));
    Voice_PlayVoice("E0111100_K00200", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "I want one that is a calming color,\nsomething that will allow me to hold\nmy head up high.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, in other words, one that is\nplain and boring?");
    Character_BlinkStart(11, 0, (#1));
    Voice_PlayVoice("E0111100_K00300", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Yes, that's right.... I've decided.\nAs expected, I'll buy this ribbon.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0111100_K00400", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "The material, sewing and embroidery\nare perfect.\nIt is appropriate for helping me\nconcentrate.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("E0111100_K00500", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Now then, I will buy it!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(11, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(What exactly is a ribbon that is\nappropriate for concentrating...?)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(11, 86, 1);
    }
