section "e01_g1_100"{
    Background_Bg_GS2("BG_NE000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? ｛Toudou＊＊｝? ...\nIs she a little angry?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Toudou＊＊｝!");
    Character_ChFace(0, 0, 8);
    Character_Chara_GS2(10, "G1_04F", 0);
    Music_PlayBGM(0, "MN_C_10_000_D00", 127, 40);
    Voice_PlayVoice("E0110100_J00000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Ah!?");
    Message_Who(0);
    Message_MsgDisp("主人公", "!!! S-Sorry!");
    Message_Who(10);
    Message_MsgDisp("Toudou", "｛主人公｝!");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("E0110100_J00100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "My bad, that guy again...");
    Message_Who(0);
    Message_MsgDisp("主人公", "That guy?");
    Character_BlinkStart(10, 2, (#1));
    Voice_PlayVoice("E0110100_J00200", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "That annoying guy who always follows\nme around asking me if I want to\nbecome a model.");
    Message_Who(0);
    Message_MsgDisp("主人公", "You've been scouted! Amazing!");
    Voice_PlayVoice("E0110100_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I'm not interested so it's just a\nnuisance....\nIf it were the opposite, I might\nthink about it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "The opposite?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0110100_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I'm not interested in being dressed\nup, I'm interested in dressing\npeople up.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh... Is that so.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0110100_J00500", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "My dream is to be a stylist or a\nnail artist.");
    Voice_PlayVoice("E0110100_J00600", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I want to see how popular my styles\nwill be.........");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Toudou＊＊｝?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0110100_J00700", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... He's here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?\nThat person you were talking about\nbefore?\nHe's talking to another person...");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("", #1, "E0110100_J00800");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... ｛主人公｝.\nBe careful on your way home.");
    Message_Who(0);
    Message_MsgDisp("主人公", "W-What's wrong?");
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0110100_J00900", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "If the guy keeps doing as he\npleases, he's going to do great\nharm.");
    Character_BlinkStart(10, 3, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0110100_J01000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "And before that happens...");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Before that happens...?");
    Character_BlinkStart(10, 0, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0110100_J01100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... Later.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(10, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...\nW-Wait, ｛Toudou＊＊｝!?");
    Message_Who(0);
    Message_MsgDisp("主人公", "She left...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(W-Will the person that guy's\ntalking to be okay...?)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(10, 86, 1);
    }
