section "e01_g3_100"{
    Background_Bg_GS2("BG_NE100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh, ｛Nishimoto＊＊｝ is over\nthere...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(12, "G3_04F", 0);
    Background_Bg_GS2("BG_NES40_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_12_000_D02", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Nishimoto＊＊｝!");
    Voice_PlayVoice("E0112100_L00000", #1, "E0112100_L00001");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ah, ｛主人公｝!\nDid you also come here to buy books?");
    Message_Who(0);
    Message_MsgDisp("主人公", "No.\nI came here because I spotted you,\n｛Nishimoto＊＊｝.");
    Voice_PlayVoice("E0112100_L00100", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I see.\nBut since you're here, come take a\nlook with me.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(12, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0112100_L00200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I recommend \"The Legend of Pure\nLove\" and \"Naniwa's First Love\"!");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(12, 3, (#1));
    Voice_PlayVoice("E0112100_L00300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Both are masterpieces!\nYou can't help but cry and cry.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so...?\nHey, what are you reading now?\nThis...?");
    Character_BlinkStart(12, 0, (#1));
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("E0112100_L00400", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Wa-Wah, this is bad!\nDon't look, that's---!");
    Message_Who(0);
    Message_MsgDisp("主人公", "\"Rock for Beginners\".\nAre you starting a band,\n｛Nishimoto＊＊｝?");
    Character_ChFace(0, 4, 1);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0112100_L00500", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "No, this is just...\nI was just looking at it for a\nlittle reference...");
    Character_ChFace(0, 2, 4);
    Voice_PlayVoice("E0112100_L00600", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ah, right, I have something to do!");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(12, 3, (#1));
    Voice_PlayVoice("E0112100_L00700", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Now then, I will leave... Later～.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(12, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Nishimoto＊＊｝ looked\nflustered...\nI wonder why?)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(12, 86, 1);
    }
