section "e01_m6_405"{
    Background_Bg_GS2("BG_NES40_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("B0106405_F00000", #1, "");
    Message_Who(6);
    Message_MsgDisp("？？？", "...\nI can't just believe in you at the\nmoment...");
    Voice_PlayVoice("B0106405_E00100", #1, "");
    Message_WindowPosition(1);
    Message_Who(6);
    Message_MsgDisp("？？？", "Eh, you don't trust me?\nThat's cruel, Shota-kun.");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Those voices just now, were\n｛Amachi＊＊｝ and\n｛Chris＊＊｝'s voices.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Amachi＊＊｝,\n｛Chris＊＊｝.");
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 5);
    Character_Chara_GS2(6, "M6_??F", 0);
    Character_ChFace(1, 0, 10);
    Character_Chara_GS2(5, "M5_??F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_06_000_D00", 127, 40);
    Voice_PlayVoice("B0106405_F00200", 6, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Ah, ｛主人公｝.");
    Voice_PlayVoice("", 5, "B0106405_E00300");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "｛主人公｝. Hello.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hello.\nAre the two of you out shopping?");
    Voice_PlayVoice("B0106405_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I just met him at the art books\ncorner.");
    Character_ChFace(1, 2, 2);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("B0106405_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Shota-kun had a really bitter face.");
    Message_Who(0);
    Message_MsgDisp("主人公", "The art books corner?");
    Character_ChFace(1, 0, 3);
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("B0106405_F00600", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "...\nI heard that there were books that\ncan help you draw better.");
    Voice_PlayVoice("B0106405_F00700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "But Chris-senpai bought it...");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 1);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("B0106405_F00800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I would really like for him to give\nit to me...!");
    Message_Who(0);
    Message_MsgDisp("主人公", "It would be nice if he gave it to\nyou.");
    Character_ChFace(1, 2, 0);
    Character_BlinkStart(5, 3, (#1), 2);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("B0106405_E00900", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "But Shota-kun isn't bad at drawing.\nHe doesn't need it.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(6, 3, (#1));
    Voice_PlayVoice("B0106405_F01000", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "I don't believe you!\nMy art teacher said that I was\ncompletely hopeless at it...!");
    Character_ChFace(1, 2, 3);
    Character_BlinkStart(5, 2, (#1), 2);
    Character_ChFace(1, 3, 1);
    Voice_PlayVoice("B0106405_E01100", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "...... Did they? Shota-kun.\nListen carefully.");
    Character_ChFace(1, 3, 0);
    Voice_PlayVoice("B0106405_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "There is only one thing in the world\nof beauty.");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("B0106405_F01300", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "Eh?");
    Voice_PlayVoice("B0106405_E01400", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "In this world there are thousands,\nhundreds of thousands of different\nthings, aren't there?");
    Character_ChFace(1, 0, 10);
    Character_BlinkStart(5, 3, (#1), 2);
    Voice_PlayVoice("B0106405_E01500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "That's all we need to draw a\npicture.");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("B0106405_F01600", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "Chris-senpai.");
    Character_ChFace(1, 2, 0);
    Character_BlinkStart(5, 2, (#1), 2);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("B0106405_E01700", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "Sensor man is another story, though.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("B0106405_F01800", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "Sensor man...?");
    Character_ChFace(1, 2, 4);
    Character_BlinkStart(5, 3, (#1), 2);
    Voice_PlayVoice("B0106405_E01900", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "The person who lives in the toilet.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("B0106405_F02000", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "Toi...");
    Voice_PlayVoice("B0106405_F02100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Senpai.\nYou're mocking me, right...?");
    Character_BlinkStart(5, 0, (#1), 2);
    Character_ChFace(1, 3, 2);
    Voice_PlayVoice("B0106405_E02200", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "Eh?");
    Character_ChFace(0, 0, 9);
    Character_ChFace(0, 3, 5);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("B0106405_F02300", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "... It's fine.\nIt was my fault for being struck by\nSenpai's words...!");
    Character_ChFace(1, 0, 9);
    Character_BlinkStart(5, 2, (#1), 2);
    Character_ChFace(1, 3, 4);
    Voice_PlayVoice("B0106405_E02400", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "E... eh? Did I say something wrong?");
    Character_BlinkStart(6, 3, (#1));
    Voice_PlayVoice("B0106405_F02500", #1, "");
    Message_WindowPosition(0);
    Message_Who(6);
    Message_MsgDisp("Amachi", "Goodbye...!");
    Character_Chara_GS2(6, "NON");
    Character_ChFace(1, 2, 4);
    Character_ChFace(1, 3, 1);
    Voice_PlayVoice("B0106405_E02600", #1, "");
    Message_WindowPosition(1);
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah, wait... Shota-kun!");
    Character_Chara_GS2(5, "NON");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(... They left.)");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(6, 2, (#1));
    Character_ChFace(0, 3, 4);
    Character_Chara_GS2(6, "M6_??F", 0);
    Voice_PlayVoice("", 6, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah! W-What's wrong?");
    Voice_PlayVoice("B0106405_F02700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "About what Chris-senpai said\nearlier.");
    Voice_PlayVoice("B0106405_F02800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Are there perhaps an infinite\nvariety of interests and ideas out\nthere?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, that might be the case.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("B0106405_F02900", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... How interesting!\nI want to have another chat with\nhim!");
    Voice_PlayVoice("B0106405_F03000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Was Chris-senpai in the art club?\nMaybe I should go hang out there\nnext time.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(6, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0106405_F03100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I'm glad I came to the book store.\nI'll see you later, Senpai.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(6, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(As expected of\n｛Amachi＊＊｝ to confuse\n｛Chris＊＊｝ like that...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(6, 86, 1);
    Parameter_AddCh1Param(5, 86, 1);
    }
