section "e01_g4_100"{
    Background_Bg_GS2("BG_FP000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(... Huh?\nIs that ｛Mizushima＊＊｝\nsitting on the bench over there?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Mizushima＊＊｝!");
    Character_Chara_GS2(13, "G4_04F", 0);
    Music_PlayBGM(0, "MN_C_13_000_D00", 127, 40);
    Voice_PlayVoice("", #1, "E0113100_M00000");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "｛主人公｝, are you out\nshopping?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, something like that.\nAre you, ｛Mizushima＊＊｝?");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(13, 2, (#1));
    Voice_PlayVoice("E0113100_M00100", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "I was reading a book.\nThe weather is nice today, so I\nthought it would be nice if I read\nit outside.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Mizushima＊＊｝ reads books\nat the park.\nHmm～, it's probably picturesque...)");
    Character_BlinkStart(13, 0, (#1));
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0113100_M00200", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "... What is it?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Nothing! That's...\na book of fairy tales?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("E0113100_M00300", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Yes.\nIt's about how a princess saved a\ncursed prince.\n30 volumes have already been\nreleased.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, I've heard about those.\nSo you like those kinds of books,\n｛Mizushima＊＊｝?");
    Character_BlinkStart(13, 2, (#1));
    Voice_PlayVoice("E0113100_M00400", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Haha, I do, actually.\nIt's a little embarrassing,\nthough....\nIs it weird?");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, not at all.\nIt's just a little unexpected.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0113100_M00500", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Yeah...\nWhen I'm tired, I feel like reading\nthese kinds of books.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so...");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("E0113100_M00600", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Because I'm a girl.\nOr something like that, right? Haha.");
    Character_BlinkStart(13, 0, (#1));
    Voice_PlayVoice("E0113100_M00700", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Hey, since we happened to meet, is\nit alright if I come along with you?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, of course!");
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("E0113100_M00800", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Alright, let's go!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(13, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Although ｛Mizushima＊＊｝\nseems cheerful, it seems like she's\nworried about something...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(13, 86, 1);
    }
