section "e01_m1_400"{
    Background_Bg_GS2("BG_WF100_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? Over there is...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝!");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(1, 2, (#1));
    Character_ChFace(0, 3, 2);
    Character_Chara_GS2(1, "M1_13F", 0);
    Music_PlayBGM(0, "MN_C_01_000_D02", 127, 40);
    Voice_PlayVoice("E0101400_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "......");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝...\nHey, ｛Saeki＊＊｝!");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(1, 3, (#1));
    Message_Who(0);
    Message_MsgDisp("主人公", "(Eh? \"Come over here\"?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_BlinkStart(1, 0, (#1));
    Background_Bg_GS2("BG_WF000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("E0101400_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "......\nYou just don't get it, do you?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0101400_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It would be all kinds of annoying if\nsomeone saw you calling out my name\nin a loud voice, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah! ... Right.");
    Voice_PlayVoice("E0101400_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I'm not saying don't talk to me...\nBut be a little more careful, for my\nsake.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sorry...");
    Character_ChFace(0, 2, 5);
    Voice_PlayVoice("E0101400_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It's fine.... Later.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, do your best at work.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(1, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(When ｛Saeki＊＊｝ wears\nthat, he really seems mature....\nHuh?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝!");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(1, 3, (#1));
    Character_ChFace(0, 3, 2);
    Character_Chara_GS2(1, "M1_13F", 0);
    Voice_PlayVoice("E0101400_A00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "...\nIt seems like you need a chop, no\nmatter what...");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, no!\nYou have a rubber glove stuck to the\nback of your apron.");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(1, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("E0101400_A00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "......");
    Voice_PlayVoice("E0101400_A00700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It's supposed to be there.");
    Character_Chara_GS2(1, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(That sounds like something\n｛Saeki＊＊｝ would say...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    }
