section "e01_m2_100"{
    Background_Bg_GS2("BG_FP000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh, ｛Shiba＊＊｝.");
    Message_CloseMsg();
    Character_Chara_GS2(2, "M2_08F", 0);
    Music_PlayBGM(0, "MN_C_02_000_D03", 127, 40);
    Voice_PlayVoice("", 2, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hello. Are you training?");
    Character_BlinkStart(2, 2, (#1));
    Voice_PlayVoice("E0102100_B00000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... I run an hour every day.");
    Message_Who(0);
    Message_MsgDisp("主人公", "So, you run that often, do you?\nThat's amazing.");
    Character_BlinkStart(2, 3, (#1));
    Voice_PlayVoice("E0102100_B00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "This is normal.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I wonder...\nMaybe I should run with you?");
    Character_BlinkStart(2, 0, (#1));
    Voice_PlayVoice("E0102100_B00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... That's impossible for you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh, why?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0102100_B00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Our pace is different.\nDon't say these things on a whim.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uh... You're right. I'm sorry.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(2, 3, (#1));
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("E0102100_B00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nIf it's a light jog, I'll run by\nyour side.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Really?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("E0102100_B00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Only when I have free time.\nLater.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(2, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I wonder if he even has free\ntime...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 86, 1);
    }
