section "e01_g4_515"{
    Background_Bg_GS2("BG_WF000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Now then, it's about time I went\nhome...)");
    Voice_PlayVoice("E0113515_O00000", #1, "");
    Message_Who(13);
    Message_MsgDisp("？？？", "Impossible, impossible!\nI definitely won't forgive you!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh, that voice! Could it be...?)");
    Character_Chara_GS2(15, "S2_17F", 0);
    Voice_PlayVoice("E0113515_O00100", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Daisy, you came at a good time!\nPlease listen to me, as well.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Himeko-senpai.\nHuh, ｛Mizushima＊＊｝?");
    Message_CloseMsg();
    Character_Chara_GS2(15, "S2_01F", 0, 0, 1);
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 2);
    Character_Chara_GS2(13, "G4_04F", 0);
    Music_PlayBGM(0, "MN_C_13_000_D00", 127, 40);
    Message_WindowPosition(0);
    Message_Who(13);
    Message_MsgDisp("Mizushima", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What's wrong?\nI heard Himeko-senpai shouting...");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("E0113515_M00200", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "I don't know.\nI was only out shopping...");
    Voice_PlayVoice("E0113515_O00300", #1, "");
    Message_WindowPosition(1);
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Mizushima Hisoka is definitely\nbeautiful.\nPure, smart, and she is overflowing\nwith a kind spirit.");
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("E0113515_M00400", #1, "");
    Message_WindowPosition(0);
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Umm... Thank you very much.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes, ｛Mizushima＊＊｝ might be\nthe purest kind of maidens.");
    Character_Chara_GS2(15, "S2_18F", 0, 0, 1);
    Voice_PlayVoice("E0113515_O00500", #1, "");
    Message_WindowPosition(1);
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "No, Daisy, you mustn't be deceived.\nThe depths of her heart are whirling\nwith darkness.");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "... Whirling?");
    Character_BlinkStart(13, 0, (#1));
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0113515_M00600", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Well...");
    Character_Chara_GS2(15, "S2_17F", 0, 0, 1);
    Voice_PlayVoice("E0113515_O00700", #1, "");
    Message_WindowPosition(1);
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "She's feigning innocence!\nShe's trying to usurp Club Camellia,\ntoo...");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "... Usurp?");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(13, 2, (#1));
    Voice_PlayVoice("E0113515_M00800", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Well... First of all, I don't...");
    Character_Chara_GS2(15, "S2_18F", 0, 0, 1);
    Voice_PlayVoice("E0113515_O00900", #1, "");
    Message_WindowPosition(1);
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "I don't want to hear it! ...\nAnyway, you cannot join Club\nCamellia!");
    SoundEffect_PlayStream(3, "SS_T_00_030_M00");
    Character_Chara_GS2(15, "NON");
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("E0113515_M01000", #1, "");
    Message_WindowPosition(0);
    Message_Who(13);
    Message_MsgDisp("Mizushima", "......");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Mizushima＊＊｝, that was\nsomewhat unfortunate, right?");
    Character_BlinkStart(13, 0, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0113515_M01100", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "I'm fine. I'm used to it.\nIt's just unjustified jealousy.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I-Is that so?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("E0113515_M01200", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "It was a little annoying, though....\nHaha.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Is ｛Mizushima＊＊｝... angry?)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    SoundEffect_StopStream(3, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(13, 86, 1);
    Parameter_AddCh1Param(15, 86, 1);
    }
