section "e01_m4_311"{
    Background_Bg_GS2("BG_NE100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("E0104311_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "As expected, you need to drink tea\nafter cleaning the floors～.");
    Voice_PlayVoice("E0104311_K00100", #1, "");
    Message_WindowPosition(1);
    Message_Who(4);
    Message_MsgDisp("？？？", "That is right.\nThe wisdom of the people from the\npast is amazing.");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh?\nIt's ｛Hariya＊＊｝ and\n｛Onoda＊＊｝.)");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(4, "M4_??F", 0);
    Character_ChFace(1, 0, 0);
    Character_Chara_GS2(11, "G2_04F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_04_000_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Why are you two here?\nIt's a bit rare to see you two\ntogether.");
    Character_ChFace(0, 4, 1);
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("E0104311_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Ah, it's nothing in particular...\nIt's nothing. Right, Onoda?");
    Voice_PlayVoice("E0104311_K00300", #1, "");
    Message_WindowPosition(1);
    Message_Who(11);
    Message_MsgDisp("Onoda", "Yeah, I was just consulting\nHariya-kun on something...");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("E0104311_D00400", #1, "");
    Message_WindowPosition(0);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Ah! I've got stuff to do! L-Later!!");
    Message_CloseMsg();
    Character_Chara_GS2(4, "NON");
    Music_StopBGM(0, 40);
    System_Wait(30);
    Character_ChMove(11, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "What's up with\n｛Hariya＊＊｝?\nHe's so flustered...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0104311_K00500", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Perhaps it's because he's\nembarrassed?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Embarrassed?");
    Character_BlinkStart(11, 3, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0104311_K00600", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "There was some dusty places that he\ncouldn't reach, so he asked me what\na good cleaning tool was...");
    Character_BlinkStart(11, 0, (#1), 1);
    Character_ChFace(0, 2, 0);
    Voice_PlayVoice("E0104311_K00700", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "So I did a preliminary inspection\ntoday, and we bought something with\nthe Student Council budget.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(11, 2, (#1), 1);
    Voice_PlayVoice("E0104311_K00800", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Contrary to his appearance, it seems\nlike he pays quite a bit of\nattention to detail.");
    Voice_PlayVoice("E0104311_K00900", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "And for someone to catch a glimpse\nof that, perhaps he was embarrassed?");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I don't think it was that\nembarrassing, though.)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    Parameter_AddCh1Param(11, 86, 1);
    }
