section "e01_m7_301"{
    Background_Bg_GS2("BG_WF000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's late!\nI have to hurry and get home!)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh, it's ｛Wakaouji＊＊｝.\nAnd also... Ah!!)");
    Character_BlinkStart(1, 2, (#1));
    Character_Chara_GS2(7, "M7_06F", 0);
    Character_ChFace(1, 4, 0);
    Character_ChFace(1, 0, 6);
    Character_Chara_GS2(1, "M1_13F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
    Voice_PlayVoice("E0107301_A00000", #1, "");
    Message_WindowPosition(1);
    Message_Who(1);
    Message_MsgDisp("Saeki", "Wakaouji-sensei, I won't quit, no\nmatter what.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(What should I do...?\n｛Saeki＊＊｝ has finally\nbeen caught.)");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(7, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0107301_G00100", #1, "");
    Message_WindowPosition(0);
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Really...? Okay, it's fine.\nOf course, I don't think that\nworking late is fine though.");
    Character_BlinkStart(7, 0, (#1));
    Voice_PlayVoice("E0107301_G00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "As long as you know that you are in\na dangerous position, I will leave\nit at that for today.");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0107301_G00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "However, if there is something you\nwant to talk to me about, then feel\nfree to talk to me about anything.");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(7, 2, (#1));
    Voice_PlayVoice("E0107301_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "But all Sensei can do is worry with\nyou.\nIt's better than worrying by\nyourself.");
    Character_ChFace(1, 0, 9);
    Character_BlinkStart(1, 2, (#1), 2);
    Voice_PlayVoice("E0107301_A00500", #1, "");
    Message_WindowPosition(1);
    Message_Who(1);
    Message_MsgDisp("Saeki", "Okay.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0107301_G00600", #1, "");
    Message_WindowPosition(0);
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Okay. Now then, I am going.");
    Character_Chara_GS2(1, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝.");
    Voice_PlayVoice("", 7, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, ｛Saeki＊＊｝...");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0107301_G00700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Hey, isn't he an odd child?\nThat's what Sensei thinks.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0107301_G00800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "That's why we shall keep what you\njust saw a secret between us.\nCan you promise me?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes!");
    Character_ChFace(0, 2, 1);
    Voice_PlayVoice("E0107301_G00900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "... Ah, right. Hey! Go home.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Alright!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝ is an amazing\nteacher.\nAs expected...)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 86, 1);
    Parameter_AddCh1Param(1, 86, 1);
    }
