section "e01_m2_210"{
    Background_Bg_GS2("BG_NE100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh.\nIt's ｛Shiba＊＊｝ and\n｛Toudou＊＊｝.)");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(2, 2, (#1));
    Character_ChFace(0, 3, 2);
    Character_Chara_GS2(2, "M2_??F", 0);
    Character_ChFace(1, 2, 1);
    Character_ChFace(1, 3, 4);
    Character_Chara_GS2(10, "G1_04F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_02_000_D03", 127, 40);
    Voice_PlayVoice("E0102210_J00000", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "...\nAnd because of that, you should take\ncare.");
    Voice_PlayVoice("E0102210_B00100", #1, "");
    Message_WindowPosition(0);
    Message_Who(2);
    Message_MsgDisp("Shiba", "......... Yeah.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(...\nT-The atmosphere is somewhat\ntense...?)");
    Character_ChFace(1, 2, 4);
    Character_ChFace(1, 3, 2);
    Voice_PlayVoice("E0110202_J01300", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "... ｛主人公｝.");
    Character_BlinkStart(2, 0, (#1));
    Character_ChFace(0, 3, 4);
    Message_WindowPosition(0);
    Message_Who(2);
    Message_MsgDisp("Shiba", "......");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm... What's up?");
    Character_BlinkStart(2, 2, (#1));
    Character_ChFace(0, 3, 2);
    Character_ChFace(1, 2, 2);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0102210_J00400", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "...\nI heard a sort of distasteful rumor.\nSo I came to warn him.");
    Character_ChFace(1, 2, 1);
    Character_BlinkStart(10, 3, (#1), 2);
    Character_ChFace(1, 3, 0);
    Voice_PlayVoice("E0102210_J00500", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "You should also take care, okay?\nEspecially when you're around this\nguy.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_BlinkStart(2, 3, (#1));
    Voice_PlayVoice("E0102210_B00600", #1, "");
    Message_WindowPosition(0);
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Toudou.");
    Character_BlinkStart(10, 0, (#1), 2);
    Character_ChFace(1, 2, 1);
    Character_ChFace(1, 3, 2);
    Voice_PlayVoice("E0102210_J00700", #1, "");
    Message_WindowPosition(1);
    Message_Who(10);
    Message_MsgDisp("Toudou", "If you get into some mess, call me.\nI'll come flying in.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay...");
    Character_ChFace(1, 2, 0);
    Character_BlinkStart(10, 2, (#1), 2);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0102210_J00800", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Later.");
    Character_Chara_GS2(10, "NON");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Toudou＊＊｝ has left...\nBut are things okay?");
    Character_BlinkStart(2, 0, (#1));
    Voice_PlayVoice("E0102210_B00900", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... I've taken care of my business.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that... so?\nIf there's something happening...");
    Voice_PlayVoice("E0102210_B01000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "It's not something you should worry\nabout.\nLater.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(2, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He left...\nUgh, I'm somewhat curious...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 86, 1);
    Parameter_AddCh1Param(10, 86, 1);
    }
