section "e01_m4_507"{
    Background_Bg_GS2("BG_WF200_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah.\nIt's ｛Hariya＊＊｝ and\n｛Wakaouji＊＊｝.)");
    Character_ChFace(0, 0, 10);
    Character_Chara_GS2(4, "M4_??F", 0);
    Character_ChFace(1, 0, 10);
    Character_Chara_GS2(7, "M7_06F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_04_000_D00", 127, 40);
    Voice_PlayVoice("E0104507_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "An all-day ticket.");
    Voice_PlayVoice("E0104507_G00100", #1, "");
    Message_WindowPosition(1);
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It would be nice if we had one.");
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝!\n｛Wakaouji＊＊｝!");
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Voice_PlayVoice("", 4, "E0104507_D00200");
    Message_Who(4);
    Message_MsgDisp("Hariya", "｛主人公｝. Yo.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hello.");
    Voice_PlayVoice("E0104507_G00300", 7, "E0104507_G00301");
    Message_WindowPosition(1);
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Ah, ｛主人公｝....\nThat's right, Hariya-kun.\nWhy don't we invite her, too?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Are the both of you going somewhere?");
    Character_ChFace(1, 0, 10);
    Voice_PlayVoice("E0104507_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Correct.\nIt seems like there is a band that\nHariya-kun likes.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0104507_D00500", #1, "");
    Message_WindowPosition(0);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Anyway, don't worry about that!\nYou should come along, too!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Did you both originally plan on\ngoing together?");
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 0);
    Character_ChFace(1, 2, 4);
    Character_ChFace(1, 3, 0);
    Voice_PlayVoice("E0104507_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "No.");
    Voice_PlayVoice("E0104507_G00700", #1, "");
    Message_WindowPosition(1);
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "No, we didn't.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0104507_D00800", #1, "");
    Message_WindowPosition(0);
    Message_Who(4);
    Message_MsgDisp("Hariya", "We just bumped into each other.\nThen he gave me a lecture.");
    Character_BlinkStart(7, 3, (#1), 2);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0104507_G00900", #1, "");
    Message_WindowPosition(1);
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Right.");
    Character_ChFace(1, 0, 8);
    Voice_PlayVoice("E0104507_G01000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It went something like this: \"Hey,\nHariya-kun!\nDoing music is fine, but study as\nwell!\".");
    Message_Who(0);
    Message_MsgDisp("主人公", "... And why did you say that?");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 0);
    Character_ChFace(1, 2, 3);
    Character_ChFace(1, 3, 0);
    Voice_PlayVoice("E0104507_D01100", #1, "");
    Message_WindowPosition(0);
    Message_Who(4);
    Message_MsgDisp("Hariya", "I wonder.");
    Voice_PlayVoice("E0104507_G01200", #1, "");
    Message_WindowPosition(1);
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I wonder.");
    Message_Who(0);
    Message_MsgDisp("主人公", "......");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0104507_D01300", #1, "");
    Message_WindowPosition(0);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Ah, don't worry about that!");
    Character_ChFace(1, 2, 4);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0104507_G01400", #1, "");
    Message_WindowPosition(1);
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Right. You're coming too, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yes...");
    Character_BlinkStart(4, 2, (#1));
    Character_ChFace(0, 4, 1);
    Character_ChFace(1, 0, 10);
    Voice_PlayVoice("E0104507_D01500", #1, "");
    Message_WindowPosition(0);
    Message_Who(4);
    Message_MsgDisp("Hariya", "Alright, let's go!");
    Voice_PlayVoice("E0104507_G01600", #1, "");
    Message_WindowPosition(1);
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Yeah!");
    Character_Chara_GS2(4, "NON");
    Character_Chara_GS2(7, "NON");
    Music_StopBGM(0, 40);
    Message_WindowPosition(0);
    Message_Who(0);
    Message_MsgDisp("主人公", "(I... Is this okay?\nBut it sounds like fun.\nIt'll be enjoyable!)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    Parameter_AddCh1Param(7, 86, 1);
    }
