section "e01_g3_500"{
    Background_Bg_GS2("BG_NE600_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh...? ｛Nishimoto＊＊｝!");
    Character_Chara_GS2(12, "G3_04F", 0);
    Music_PlayBGM(0, "MN_C_12_000_D02", 127, 40);
    Voice_PlayVoice("E0112500_L00000", #1, "E0112500_L00001");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ah... ｛主人公｝!\nIt's so nice to bump into you here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ahaha. What are you doing?\nGoing out?");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(12, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0112500_L00100", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Hmm...\nI was going out to watch a movie by\nmyself.\nI've got nothing to do.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh, what did you come to watch?");
    Character_BlinkStart(12, 0, (#1));
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0112500_L00200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "...... Eh?\nW-Well, it's not that important.\nThe movie isn't a big deal.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Did you see that movie in the\npamphlet?\nIt's a love movie.");
    Voice_PlayVoice("E0112500_L00300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Y...Yeah...\nI did, but it really couldn't be\nhelped.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0112500_L00400", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "It's obvious those movies make you\nwant to cry.\nIt doesn't suit me.");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(12, 3, (#1));
    Voice_PlayVoice("E0112500_L00500", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I mean, don't I seem like the type\nto just laugh?\nLike the \"holding my stomach from\ntoo much laughter\" type!?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Really...?\nBut you bought the pamphlet?");
    Character_BlinkStart(12, 0, (#1));
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("E0112500_L00600", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Eh? Y-Yeah...\nI only bought it because it was\npopular...");
    Message_Who(0);
    Message_MsgDisp("主人公", "It also seems like your eyes are a\nbit red...");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(12, 3, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0112500_L00700", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Hmm, ah...\nI was reading the subtitles, so my\neyes got tired.\nI should go home and rest my eyes.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0112500_L00800", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I'll see you later,\n｛主人公｝.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(12, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(That movie is a Japanese film, so\nthere aren't any subtitles...\nAh, whatever...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(12, 86, 1);
    }
