section "e01_m1_302"{
    Background_Bg_GS2("BG_WF000_CH_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? Over there is...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝!");
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 2, 1);
    Music_PlayBGM(0, "MN_C_01_000_D02", 127, 40);
    System_Wait(20);
    Character_Chara_GS2(1, "M1_13F", 0);
    Voice_PlayVoice("E0101302_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "You...\nDon't call out my name when I'm\nwearing these clothes!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh yeah... Sorry.\nAre you out shopping?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0101302_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Yeah, I forgot that there are some\nthings that I need to buy for the\nstore.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see.\nThen you should hurry--");
    SoundEffect_PlayStream(3, "SS_T_00_007_M00");
    Screen_StartShakePlane(0, 32, 32, 0, 16);
    System_Wait(92);
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah!");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("E0101302_B00200", #1, "");
    Message_Who(2);
    Message_Who(2);
    Message_MsgDisp("？？？", "Pardon me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝!?");
    Character_Chara_GS2(2, "M2_??F", 0, 0, 1);
    Voice_PlayVoice("", 2, "E0101302_B00300");
    Message_Who(2);
    Message_MsgDisp("Shiba", "｛主人公｝. Sorry...\nAre you okay?");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(1, 2, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0101302_A00400", #1, "");
    Message_WindowPosition(0);
    Message_Who(1);
    Message_MsgDisp("Saeki", "......");
    Character_ChFace(1, 4, 0);
    Character_ChFace(1, 2, 1);
    Character_ChFace(1, 3, 4);
    Voice_PlayVoice("E0101302_B00500", #1, "");
    Message_WindowPosition(1);
    Message_Who(2);
    Message_MsgDisp("Shiba", "......");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Shiba＊＊｝ is looking at\n｛Saeki＊＊｝.\nWhat should I do?\nHis cover might be blown...)");
    Voice_PlayVoice("E0101302_B00600", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Who is that?");
    Character_BlinkStart(1, 0, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0101302_A00700", #1, "");
    Message_WindowPosition(0);
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ah, umm, I'm... nobody.");
    Voice_PlayVoice("E0101302_B00800", #1, "");
    Message_WindowPosition(1);
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Ah.");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("E0101302_A00900", #1, "");
    Message_WindowPosition(0);
    Message_Who(1);
    Message_MsgDisp("Saeki", "Wah!");
    Character_ChFace(1, 0, 3);
    Voice_PlayVoice("E0101302_B01000", #1, "");
    Message_WindowPosition(1);
    Message_Who(2);
    Message_MsgDisp("Shiba", "... I was in a hurry. Later.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yeah! Later!");
    Character_Chara_GS2(2, "NON");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(1, 3, (#1));
    Voice_PlayVoice("E0101302_A01100", #1, "");
    Message_WindowPosition(0);
    Message_Who(1);
    Message_MsgDisp("Saeki", "......\nI thought my heart was going to\nstop.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Me too...\nDo you know ｛Shiba＊＊｝?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("E0101302_A01200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ah, well, just his name and face.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Thank gosh your cover wasn't blown.");
    Voice_PlayVoice("E0101302_A01300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Does he not know who I am?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... I wonder?");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0101302_A01400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "... Is my face...\nthat plain-looking?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(1, 2, (#1));
    Voice_PlayVoice("E0101302_A01500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ah, it's nothing... Later.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(1, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Saeki＊＊｝ looked a bit\ndown...)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    Parameter_AddCh1Param(2, 86, 1);
    }
