section "e01_m4_100"{
    Background_Bg_GS2("BG_NE000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("E0104100_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("？？？", "Please attend our live!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Hm? That voice just now...)");
    Character_Chara_GS2(4, "M4_??F", 0);
    Music_PlayBGM(0, "MN_C_04_000_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, as I thought, it's you,\n｛Hariya＊＊｝.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0104100_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yo. What are you doing?");
    Message_Who(0);
    Message_MsgDisp("主人公", "What about you,\n｛Hariya＊＊｝?");
    Voice_PlayVoice("E0104100_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "You should be able to tell just by\nlooking.\nI'm handing out flyers.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...... For your live show?");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(4, 2, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("E0104100_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah. It's not going really well...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("E0104100_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Right!");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0104100_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I'll appoint you as the manager for\ntoday!\nBe thankful for this!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh, me? Why?");
    Voice_PlayVoice("E0104100_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "There's no particular reason.\nAlright, now I'll give you your\nfirst job!");
    Character_BlinkStart(4, 3, (#1));
    Voice_PlayVoice("E0104100_D00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Hand out these flyers.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh, no way!");
    Character_BlinkStart(4, 0, (#1));
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("E0104100_D00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Don't space out.\nHurry up and hand them out!\nPlease attend our live!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yes...");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("E0104100_D00900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I can't hear you!\nPut more oomph into it, more oomph!\nPlease attend our live!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Please attend our live!");
    Character_ChFace(0, 3, 5);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ugh... Why am I doing this...?)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    }
