section "e01_m8_415"{
    Background_Bg_GS2("BG_FP200_?_0", 1, #1, 0);
    Character_Chara_GS2(15, "S2_01F", 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("E0108415_O00000", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Oh, Daisy!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Himeko-senpai! Hello.");
    Voice_PlayVoice("E0108415_O00100", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "How are you?\nMeeting you here is quite\nunexpected, is it not?");
    Message_Who(0);
    Message_MsgDisp("主人公", "That's right. Huh...");
    Character_ChFace(1, 0, 0);
    Character_Chara_GS2(8, "M8_??F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_08_000_D00", 127, 40);
    Voice_PlayVoice("E0108415_H00200", 8, "E0108415_H00201");
    Message_WindowPosition(1);
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yo, ｛主人公｝.\nWhat are you... Huh?");
    Character_ChFace(1, 0, 11);
    Voice_PlayVoice("E0108415_H00300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Are you perhaps Himeko...senpai!?");
    Voice_PlayVoice("E0108415_O00400", #1, "");
    Message_WindowPosition(0);
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Oh, how are you, Masaki-kun?\nYou are still as energetic as ever.");
    Character_BlinkStart(8, 2, (#1), 2);
    Character_ChFace(1, 3, 5);
    Voice_PlayVoice("E0108415_H00500", #1, "");
    Message_WindowPosition(1);
    Message_Who(8);
    Message_MsgDisp("Masaki", "Huh.\nYou also haven't changed,\nHimeko-senpai...");
    Character_ChFace(1, 2, 2);
    Character_ChFace(1, 3, 4);
    Voice_PlayVoice("E0108415_H00600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Umm, could I just ask one thing?\nWhy are you wearing that uniform...");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Voice_PlayVoice("E0108415_O00700", #1, "");
    Message_WindowPosition(0);
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Is it strange?\nI really like this dress.");
    Voice_PlayVoice("E0108415_H00800", #1, "");
    Message_WindowPosition(1);
    Message_Who(8);
    Message_MsgDisp("Masaki", "No, I mean, when I had enrolled in\nHanegasaki Academy, Senpai had\nalready--");
    Character_Chara_GS2(15, "S2_17F", 0);
    Voice_PlayVoice("E0108415_O00900", #1, "");
    Message_WindowPosition(0);
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Stop it! I do not want to hear this!");
    Character_ChFace(1, 0, 11);
    Voice_PlayVoice("E0108415_H01000", #1, "");
    Message_WindowPosition(1);
    Message_Who(8);
    Message_MsgDisp("Masaki", "Ohh!");
    Character_Chara_GS2(15, "S2_01F", 0);
    Voice_PlayVoice("E0108415_O01100", #1, "");
    Message_WindowPosition(0);
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Oh, dear me!\nScreaming in such a loud voice.\n*Giggles* It's strange, right?");
    Character_ChFace(1, 2, 2);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("E0108415_H01200", #1, "");
    Message_WindowPosition(1);
    Message_Who(8);
    Message_MsgDisp("Masaki", "Haha, hahaha...\nUmm, Senpai, do you know her?");
    Voice_PlayVoice("E0108415_O01300", #1, "");
    Message_WindowPosition(0);
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Yes, Daisy and I get along really\nwell.\nWe are always together!\nLike two identical dolls.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I-Is that right...?)");
    Character_Chara_GS2(15, "S2_18F", 0);
    Voice_PlayVoice("E0108415_O01400", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Oh dear! Himeko is being careless!\nEven though she had to hurry!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, if you're talking about parting\nwith us, please don't worry about\nit.");
    Character_Chara_GS2(15, "S2_01F", 0);
    Voice_PlayVoice("E0108415_O01500", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "I'm sorry, Daisy.\nLet's have a nice, long talk next\ntime, okay?\nAnd also, Masaki-kun?");
    Character_ChFace(1, 0, 3);
    Voice_PlayVoice("E0108415_H01600", #1, "");
    Message_WindowPosition(1);
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yes?");
    Character_Chara_GS2(15, "S2_19F", 0);
    Voice_PlayVoice("E0108415_O01700", #1, "");
    Message_WindowPosition(0);
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "\"If the pheasant doesn't sing, it\nwon't get attacked\"....\n*Giggles* Ciao!");
    Message_CloseMsg();
    Character_Chara_GS2(15, "NON");
    Character_ChMove(8, 1);
    Voice_PlayVoice("E0108415_H01800", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Masaki＊＊｝, do you know\nHimeko-senpai?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(8, 3, (#1));
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("E0108415_H01900", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Rather than know...");
    Character_BlinkStart(8, 2, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("E0108415_H02000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "...\nYou should be a little cautious,\nokay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh!?");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("E0108415_H02100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Ah, no. It's nothing.\nDon't worry about it! Later, ciao!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(8, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Even if he says not to worry about\nit, I'm curious～!)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(8, 86, 1);
    Parameter_AddCh1Param(15, 86, 1);
    }
