section "f02_m7_000"{
    Character_BlinkStart(7, 1, (#1), 1);
    Character_BlinkStart(7, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    int var1 = Parameter_Kitaku_Kaiwa(1);
    if (var1 == 0){
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Wakaouji＊＊｝.)");
        }
    else if (var1 == 1){
        Character_Chara_GS2(7, "M7_17F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, have you\nheard any kind of rumors about the\nlighthouse?");
        Voice_PlayVoice("F0207000_G00000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Lighthouse...\nDo you mean the Hanegasaki\nLighthouse?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes.\nIt seems like there are many\ndifferent rumors...");
        Voice_PlayVoice("F0207000_G00100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I don't know much about the\nlighthouse, but...");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F0207000_G00200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Apparently, the name of \"Hanegasaki\"\nis derived from the name of\n\"Habataki City\".");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh...");
        Voice_PlayVoice("F0207000_G00300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That is what I know.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so...");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0207000_G00400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I will think of something for next\ntime.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You don't have to do that for me...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 2){
        Character_Chara_GS2(7, "M7_17F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0207000_G00500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I have looked into many things\nregarding to the lighthouse.");
        Message_Who(0);
        Message_MsgDisp("主人公", "There is a legend, isn't there?\nWhat did you learn?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F0207000_G00600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "A story about the lighthouse keeper\nand a beautiful mermaid meeting at\nthe beach.");
        Voice_PlayVoice("F0207000_G00700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Those two, who had solemnly swore to\nmeet again, were torn away from each\nother by fate.");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's a sad story.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0207000_G00800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That's right.\nBut there were also good things\nwithin the story.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Good things?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 3, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0207000_G00900", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "It would be a bit horrific, if\nperhaps the lighthouse keeper's\ndaughter washed ashore and she was\nhalf-mermaid.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...... Wah, you're right!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 3){
        Character_Chara_GS2(7, "M7_17F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "As expected, you don't believe in\nthe legends about Hanegasaki, do\nyou, ｛Wakaouji＊＊｝?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0207000_G01000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Why do you ask?\nI do believe in them.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so?\nIt's because you're a chemistry\nteacher, ｛Wakaouji＊＊｝.");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F0207000_G01100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Legends are a metaphor.\nIt is also fine to speak your heart.\nNo matter how science progresses--");
        Voice_PlayVoice("F0207000_G01200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Since humans are natural things, I\ndare say that you cannot erase\nthings like inherent myths.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm～...\nSo in other words--");
        Voice_PlayVoice("F0207000_G01300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "In other words, what's true to you\nis what you feel with your heart.\nThat is what I mean.");
        Message_Who(0);
        Message_MsgDisp("主人公", "What's true to me...\nWhat kind of legends do you believe\nin, ｛Wakaouji＊＊｝?");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(7, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0207000_G01400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I believe in the legend about\nundersea aliens....\nAliens are quite dubious.");
        Message_Who(0);
        Message_MsgDisp("主人公", ".........");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 4){
        Character_Chara_GS2(7, "M7_17F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost your birthday,\n｛Wakaouji＊＊｝.");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("F0207000_G01500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "... Ah.");
        Message_Who(0);
        Message_MsgDisp("主人公", "\"Ah\"...");
        Voice_PlayVoice("F0207000_G01600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That reminds me, it's almost my\nbirthday.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You say that, even though you had\nforgotten...");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(7, 3, (#1), 1);
        Voice_PlayVoice("F0207000_G01700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "......");
        Voice_PlayVoice("F0207000_G01800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Because I don't wanna be growing\nolder.");
        Message_Who(0);
        Message_MsgDisp("主人公", "\"Don't wanna be\"?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 5){
        Character_Chara_GS2(7, "M7_17F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0207000_G01900", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "It's almost the end-of-semester\ntests.\nAre you making progress with your\nstudying?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Uhh... It's going okay, perhaps?");
        Character_ChFace(0, 0, 8);
        Character_BlinkStart(7, 3, (#1), 1);
        Voice_PlayVoice("F0207000_G02000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Just \"okay\" is unsatisfactory.\nGo and study more, please.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-Yes!");
        Voice_PlayVoice("F0207000_G02100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", ".........");
        Message_Who(0);
        Message_MsgDisp("主人公", "(What's wrong with\n｛Wakaouji＊＊｝?\nHe's a little scary today...)");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(7, 2, (#1), 1);
        Voice_PlayVoice("F0207000_G02200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Just then when I said\n\"unsatisfactory\" and \"please\", did\nthey not seem a little teacher-ish?");
        Message_Who(0);
        Message_MsgDisp("主人公", "So you were just trying to surprise\nme!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 6){
        Character_Chara_GS2(7, "M7_17F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost the\nSports Festival.");
        Voice_PlayVoice("F0207000_G02300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "The Sports Festival.\nEven the teachers are really busy in\nthe staff room, dividing up the\nroles and making preparations.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh.\nWhat kind of preparations are you\nmaking, ｛Wakaouji＊＊｝?");
        Voice_PlayVoice("F0207000_G02400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Well, generally, the preparations\nare being done by the other\nteachers.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?\nThen what are you doing,\n｛Wakaouji＊＊｝?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0207000_G02500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I believe, all I have to do is\npractice for the folk dance.\nApparently, that will help them the\nmost.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm～...\nI kind of feel like I understand the\nreason...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 7){
        Character_Chara_GS2(7, "M7_17F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have plans for the summer\nholiday, ｛Wakaouji＊＊｝?");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("F0207000_G02600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Plans... Ah, right.\nI plan to go to America, once.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Wah, an overseas trip!");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F0207000_G02700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Well, I sort of have something to do\nthere.");
        Message_Who(0);
        Message_MsgDisp("主人公", "How nice...\nAre you looking forward to it?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(7, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0207000_G02800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I am not.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 8){
        if ((Parameter_GetPl1Param(25) <= 4) && (Parameter_GetPl1Param(25) != 0)){
            Character_Chara_GS2(7, "M7_17F", 0);
            Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
            Screen_WipeIn(2);
            Message_Who(0);
            Message_MsgDisp("主人公", "It's almost the Culture Festival.");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(7, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0207000_G02900", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "The Culture Festival. I am excited.");
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of things are you going to\ndo, Sensei?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(7, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0207000_G03000", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "The class display.\nI wonder what would be good to do\nthis year.\nWhat should we do?");
            Message_Who(0);
            Message_MsgDisp("主人公", "I think those things are better\ndecided during homeroom.");
            Character_BlinkStart(7, 2, (#1), 1);
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0207000_G03100", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "That is true! Ahaha!");
            Message_Who(0);
            Message_MsgDisp("主人公", "You're h-hyped up, aren't you...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
            }
        else {
            Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
            Screen_WipeIn(2);
            Message_Who(0);
            Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Wakaouji＊＊｝.)");
            }
        }
    else if (var1 == 10){
        Character_Chara_GS2(7, "M7_17F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "There is a school play in this\nyear's Culture Festival, isn't\nthere?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0207000_G03200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Yes.\nIt seems like even the staff members\nwill have a role to play.\nI'm excited.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, do you like plays,\n｛Wakaouji＊＊｝?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0207000_G03300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I don't know.\nI have never been in a play before.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Not even once?");
        Voice_PlayVoice("F0207000_G03400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Not even once.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so...");
        Character_BlinkStart(7, 0, (#1), 1);
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0207000_G03500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "!!\nI will not hand over the lead role.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Please don't worry, I'm not going to\ntake it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 11){
        Character_Chara_GS2(7, "M7_17F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost Winter Break.\nWhat will you do to pass the time,\n｛Wakaouji＊＊｝?");
        Voice_PlayVoice("F0207000_G03600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I will read books.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Books, is it?\nYou won't be going to your hometown?");
        Voice_PlayVoice("F0207000_G03700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I don't have a hometown.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so...");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0207000_G03800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Ah.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes?");
        Character_ChFace(0, 7, 0);
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0207000_G03900", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "A student's duty is to study.\nDon't forget about studying, too.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You say that, even though you had\nforgotten, as well...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 12){
        Character_Chara_GS2(7, "M7_17F", 0);
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(7, 3, (#1), 1);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0207000_G04000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "*Sigh*...");
        Message_Who(0);
        Message_MsgDisp("主人公", "What is the matter?\nWhy did you sigh,\n｛Wakaouji＊＊｝?");
        Character_BlinkStart(7, 2, (#1), 1);
        Voice_PlayVoice("F0207000_G04100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I am in the middle of writing up the\nresults sheet for grades.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, right.\nIt is almost Spring Break.");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F0207000_G04200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "If I move someone up in rank, I must\nmove someone down a rank.\nThis is something that I just cannot\nget accustomed to.");
        Character_BlinkStart(7, 3, (#1), 1);
        Voice_PlayVoice("F0207000_G04300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Although I think that everyone would\nbe sad, I'm the one who is sad.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That's right...");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nUmm, my grades for this semester\nare...");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F0207000_G04400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", ".........");
        Message_Who(0);
        Message_MsgDisp("主人公", "U-Umm...");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(7, 3, (#1), 1);
        Voice_PlayVoice("F0207000_G04500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Please don't be mad at me.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 13){
        Character_Chara_GS2(7, "M7_17F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost the school field trip.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0207000_G04600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That's right.\nPlease enjoy it as much as possible,\nand create many good memories.");
        Voice_PlayVoice("F0207000_G04700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "...\nAh, but please don't act without any\nrestraint.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0207000_G04800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Because if there were to be an\nincident, it would make it a sad\nmemory.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Understood.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 14){
        Character_Chara_GS2(7, "M7_17F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0207000_G04900", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Spring is coming soon.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 3, (#1), 1);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F0207000_G05000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "You will be graduating.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Yes.");
        Character_BlinkStart(7, 2, (#1), 1);
        Voice_PlayVoice("F0207000_G05100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Were your high school days fun?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes, but I'm a little sad now.");
        Character_BlinkStart(7, 3, (#1), 1);
        Voice_PlayVoice("F0207000_G05200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "It's a good thing.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Being sad?");
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0207000_G05300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "The feeling of being sad will make\nyou aware of the things that are\nimportant to you.");
        Character_BlinkStart(7, 3, (#1), 1);
        Voice_PlayVoice("F0207000_G05400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I have also recently become aware of\nthat fact...");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0207000_G05500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Treasure that feeling, and enjoy\nyour high school days until the very\nend.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Yes.\nYou've helped me a lot in these 3\nyears.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else {
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Wakaouji＊＊｝.)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
