section "f02_m2_000"{
    Character_BlinkStart(2, 1, (#1), 1);
    Character_BlinkStart(2, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    int var1 = Parameter_Kitaku_Kaiwa(1);
    if (var1 == 0){
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Shiba＊＊｝.)");
        }
    else if (var1 == 1){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0202000_B00000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...\nDo you know the legend of the\nlighthouse near the beach?");
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of legend?");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(2, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0202000_B00100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "At that lighthouse, a human prince\nand a mermaid princess swore to meet\nthere again...");
        Character_ChFace(0, 0, 3);
        Character_BlinkStart(2, 3, (#1), 1);
        Voice_PlayVoice("F0202000_B00200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "I heard that they're still looking\nforward to the next time they meet.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Huh?\nI feel like I've heard that story\nsomewhere before...)");
        }
    else if (var1 == 2){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0202000_B00300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Do you know?\nThe legend of the lighthouse?");
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of legend?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(2, 2, (#1), 1);
        Voice_PlayVoice("F0202000_B00400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "If you press a secret switch in the\nlighthouse, you'll become a robot.");
        Message_Who(0);
        Message_MsgDisp("主人公", "A robot!?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0202000_B00500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "You'll transform into Habataki\nSquadron's Sea Ranger Alliance's\nrobot.\nIsn't it nice that those heroes have\na dream?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I feel like it's different to the\nrumors that I know...)");
        }
    else if (var1 == 3){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0202000_B00600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Do you know?\nThe legend of the lighthouse?");
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of legend?");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0202000_B00700", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "If you face 2 mirrors against each\nother at night, your future lover\nwill get a blister on their hand\nfrom 1000 knocks.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(2, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0202000_B00800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "It's probably made up, but...\nI want to try doing it once.\n1000 knocks.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I feel like it's different to the\nrumors that I know...)");
        }
    else if (var1 == 4){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost your\nbirthday, ｛Shiba＊＊｝.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(2, 3, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0202000_B00900", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "......");
        Character_BlinkStart(2, 0, (#1), 1);
        Voice_PlayVoice("F0202000_B01000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... I see.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You forgot your own birthday?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F0202000_B01100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "It wouldn't be a problem even if I\ndid forget.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That might be so, but...");
        Voice_PlayVoice("F0202000_B01200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Your age is like a yardstick....\nTo measure the key things you've\ndone...\nright?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 5){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost the\nend-of-semester tests.");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(2, 2, (#1), 1);
        Voice_PlayVoice("F0202000_B01300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Right.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Are you studying,\n｛Shiba＊＊｝?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(2, 0, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0202000_B01400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... I will when I feel like it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He's probably not the type to\nstudy.)");
        }
    else if (var1 == 6){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost the\nSports Festival.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Have you already decided what events\nyou'll be participating in,\n｛Shiba＊＊｝?");
        Character_ChFace(0, 2, 5);
        Voice_PlayVoice("F0202000_B01500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Yeah.\n100m sprint and the 50m hurdles.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, two events...");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(2, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0202000_B01600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "The obstacle race, the relay, long\njump, and then...");
        Message_Who(0);
        Message_MsgDisp("主人公", "That many?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(2, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0202000_B01700", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...\nThere are lots of guys who are\npushing me to join those events.");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(2, 0, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0202000_B01800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Good grief...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nBut ｛Shiba＊＊｝ looks kind\nof happy...)");
        }
    else if (var1 == 7){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost Summer\nBreak.\nHave you decided on your plans?");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0202000_B01900", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Training.\nTraining during the harsh Summer\nbuilds stamina.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(2, 3, (#1), 1);
        Voice_PlayVoice("F0202000_B02000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "At the end, I plan to check my\nstamina by seeing how long it takes\nto go up and down Habataki Mountain.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh!?\nAre you going all the way to the\ntop?");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(2, 0, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0202000_B02100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Hmm, yeah...\nIf I'm feeling well, then I probably\nwill.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 8){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost the\nCulture Festival.");
        Character_ChFace(0, 2, 2);
        Voice_PlayVoice("F0202000_B02200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Yeah.\nI actually feel heavy-hearted...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Why?");
        Character_BlinkStart(2, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0202000_B02300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Normally, the guys around me at\nschool start approaching me.");
        Character_BlinkStart(2, 2, (#1), 1);
        Voice_PlayVoice("F0202000_B02400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "I'm being made to do something this\nyear...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Does that mean that he can't refuse\nif he's being depended upon?)");
        }
    else if (var1 == 9){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost the\nCulture Festival.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(2, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0202000_B02500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...\nIt hurts not being able to do club\nactivities.");
        Message_Who(0);
        Message_MsgDisp("主人公", "The baseball ground is also being\nused.\nBut you can still train, right?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0202000_B02600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Yeah.\nI plan on going to the batting\ncenter at night.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?\nAfter the preparations for the\nCulture Festival are done?");
        Character_ChFace(0, 0, 11);
        Character_BlinkStart(2, 2, (#1), 1);
        Voice_PlayVoice("F0202000_B02700", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Yeah... Is that strange?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He's got lots of physical\nstrength...)");
        }
    else if (var1 == 10){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost the\nCulture Festival.\nHow are preparations?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0202000_B02800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "It feels like the entire class is\nmaking the effort to work as one.");
        Voice_PlayVoice("F0202000_B02900", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "I heard that your 3rd Culture\nFestival is the most enjoyable.\nIt certainly is fun.");
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0202000_B03000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...\nIt will probably become a good\nmemory.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 11){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost Winter Break.\nHave you made plans?");
        Voice_PlayVoice("F0202000_B03100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Cleaning...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah. And then?");
        Character_ChFace(0, 2, 3);
        Voice_PlayVoice("F0202000_B03200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Look for a new leg for my kotatsu.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0202000_B03300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "It won't stand up with just three\nlegs.");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0202000_B03400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "It's comfortable sleeping under it,\nbut it's unstable, so I can't do\nanything else with it.");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(2, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0202000_B03500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "It's inconvenient...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He should look for one before\nWinter Break...)");
        }
    else if (var1 == 12){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost Spring\nBreak.\nDo you have any plans?");
        Voice_PlayVoice("F0202000_B03600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Right.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Like, are you going to go somewhere?");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(2, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0202000_B03700", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "No....\nIt's easier to get into a fight at\nthe beginning of Spring, so I plan\nto stay home.");
        Message_Who(0);
        Message_MsgDisp("主人公", "A fight... with whom?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F0202000_B03800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Strangers.");
        Message_Who(0);
        Message_MsgDisp("主人公", "......");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0202000_B03900", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "It's all against people who are\nsimilar to me, so getting into a\nfight with them is no big deal.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 13){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost time\nfor the school field trip.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(2, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0202000_B04000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... We're only going to Kyoto.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Did you want to go somewhere else?");
        Character_BlinkStart(2, 3, (#1), 1);
        Message_Who(2);
        Message_MsgDisp("Shiba", ".........");
        Message_Who(0);
        Message_MsgDisp("主人公", "Where?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F0202000_B04200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Well.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm, I'm curious...)");
        }
    else if (var1 == 14){
        Character_Chara_GS2(2, "M2_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "We're almost graduating.");
        Voice_PlayVoice("F0202000_B04300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Right.");
        Message_Who(0);
        Message_MsgDisp("主人公", "How were the past three years?");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(2, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0202000_B04400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... It wasn't bad.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0202000_B04500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Perhaps you were the one who made me\nspend my days at Hanegasaki Academy\nwith a smile.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(2, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0202000_B04600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...\nDon't cry at the graduation\nceremony, okay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Shiba＊＊｝...)");
        }
    else {
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Shiba＊＊｝.)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
