section "f02_m1_000"{
    Character_BlinkStart(1, 1, (#1), 1);
    Character_BlinkStart(1, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    int var1 = Parameter_Kitaku_Kaiwa(1);
    if (var1 == 0){
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Saeki＊＊｝.)");
        }
    else if (var1 == 1){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of store is Sangosho to\nyou, ｛Saeki＊＊｝?");
        Voice_PlayVoice("F0201000_A00000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Why?");
        Message_Who(0);
        Message_MsgDisp("主人公", "No particular reason.\nI just thought I'd ask.");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(1, 3, (#1), 1);
        Voice_PlayVoice("F0201000_A00100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Right... Surely, it's my pride.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Pride?");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F0201000_A00200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "...\nThe first time I had talked back to\nmy parents was about Sangosho.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!?");
        Voice_PlayVoice("F0201000_A00300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Don't be so shocked...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Sorry.");
        Voice_PlayVoice("F0201000_A00400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "My grandpa worked there by himself\nsince grandma died, but he's already\nold, isn't he?\nHe fainted once.");
        Voice_PlayVoice("F0201000_A00500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "So then my parents were going to\nclose Sangosho.\nThey said it was dangerous, and\nthere was no reason to continue on.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0201000_A00600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I couldn't forgive that.\nMy grandpa said that he wanted to\ncontinue, so that was enough of a\nreason.");
        Voice_PlayVoice("F0201000_A00700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "That's why I said I'd help out, and\nI begged him to continue.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That's why it's your pride?");
        Voice_PlayVoice("F0201000_A00800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "That's how it goes.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Saeki＊＊｝'s pride,\nhuh...)");
        }
    else if (var1 == 2){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝, since when\nhave you been helping out at\nSangosho?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F0201000_A00900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Since around middle school, I helped\nout here and there.\nI started seriously helping just\nbefore I entered high school.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Since middle school, huh.\nThat's why you're so accustomed to\nworking there.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0201000_A01000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "All I was allowed to do in middle\nschool was wash the dishes or be a\nwaiter.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, your grandpa is quite strict\nwhen it comes to coffee.");
        Voice_PlayVoice("F0201000_A01100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Yeah.\nBut now he lets me make coffee, and\noccasionally, he lets me make my own\nblend.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(1, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0201000_A01200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Right!\nDidn't my grandpa refer to me as\n\"our barista\" when he was talking to\na customer?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is a barista someone who makes\ncoffee?");
        Voice_PlayVoice("F0201000_A01300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It's not just that...\nIt's a person who allows you to\ndrink the best coffee.\nI'm still not good at making coffee,\nyet.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(1, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0201000_A01400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Since I have school now, I can't\ntake the exam, but after I graduate\nI'll study to--");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes?");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(1, 3, (#1), 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0201000_A01500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "... Well, that's how it goes.\nThis conversation is over.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He didn't have to stop.)");
        }
    else if (var1 == 3){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Sangosho is quite an old store,\nisn't it?");
        Voice_PlayVoice("F0201000_A01600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Right...\nAt the back of the store, there's a\nlighthouse, right?");
        Voice_PlayVoice("F0201000_A01700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Grandpa said that the store was\nbuilt after the lighthouse stopped\nbeing used, so the store is probably\nquite old.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh... So that's how it is.");
        Voice_PlayVoice("F0201000_A01800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Back then, grandpa and grandma used\nto run the store together.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0201000_A01900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "My grandma smiled a lot.\nShe would always say that she was\nactually a mermaid.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Mermaid?");
        Voice_PlayVoice("F0201000_A02000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "When my grandpa was young, he wanted\nto be a painter and often painted\npictures of mermaids.\nMy grandma was the model.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I see, ｛Saeki＊＊｝ surely\nloves his grandma, as well.)");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0201000_A02100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "... What is it?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Nothing.\nI was just thinking that you were\nmaking a nice face,\n｛Saeki＊＊｝.");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(1, 3, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0201000_A02200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I was born with a good face.\nCome on, let's go.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He's embarrassed.)");
        }
    else if (var1 == 4){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Right!\nIt's almost your birthday,\n｛Saeki＊＊｝.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(1, 3, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0201000_A02300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Is that so. *sigh*...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Aren't you happy that it will be\nyour birthday?");
        Character_BlinkStart(1, 0, (#1), 1);
        Voice_PlayVoice("F0201000_A02400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Surely, people like you are the only\nones who can get so jumpy and\nfestive about their birthday, at\nthis age.");
        Message_Who(0);
        Message_MsgDisp("主人公", "J-Jumpy... I don't think so.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(1, 2, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0201000_A02500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It's true.\nI mean when you talk about\nbirthdays, it's just about cake...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh? You hate cakes?");
        Voice_PlayVoice("F0201000_A02600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I like cake.\nBut on birthdays, I get treated to\ncake at Sangosho.");
        Voice_PlayVoice("F0201000_A02700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It seems like my grandpa tells the\nfemale customers about my birthday.\nThen... You know.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You're popular wherever you go,\n｛Saeki＊＊｝...\nYou don't refuse?");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(1, 3, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0201000_A02800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I can't refuse.\nEven presents from customers.\n*sigh*...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It seems tough being so popular.)");
        }
    else if (var1 == 5){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost time for the\nend-of-semester tests.\nHow are your preparations going?");
        Voice_PlayVoice("F0201000_A02900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Well, fine, I suppose.\nBecause I usually study.");
        Message_Who(0);
        Message_MsgDisp("主人公", "But you still get top grades, even\nthough you also work at Sangosho.\nIt's amazing.");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("F0201000_A03000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It's not.\nIt's just that I don't show my\nweaknesses.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...?");
        Voice_PlayVoice("F0201000_A03100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "My parents are aiming for me to be\nthe so-called \"elite\", so I have to\nbe at the top for everything.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That's...");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0201000_A03200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Strange, right? ...\nBut I've been thinking that way\nsince middle school.");
        Voice_PlayVoice("F0201000_A03300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "There was a huge fuss when I\nenrolled into Hanegasaki in order to\nwork at the store.\nMy mom was crying, my dad was\nyelling, and--");
        Voice_PlayVoice("F0201000_A03400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I don't know what they'll do if my\ngrades dropped or if there was a\nconflict with school because of\nSangosho.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I see, that's why\n｛Saeki＊＊｝ has to be an\nhonor student.)");
        }
    else if (var1 == 6){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "The Sports Festival is close.\nHow is your form,\n｛Saeki＊＊｝?");
        Voice_PlayVoice("F0201000_A03500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Whatever is fine.\nI don't have to attend athletic\nmeets now that I'm a high school\nstudent, right?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(1, 3, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0201000_A03600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It would be better if only the guys\nwho want to do it participated.\nI'm not interested.");
        Message_Who(0);
        Message_MsgDisp("主人公", "What a terrible way of saying it...\nAh, are you perhaps bad at running,\n｛Saeki＊＊｝?");
        Character_BlinkStart(1, 0, (#1), 1);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0201000_A03700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Who are you talking to?\nFor three straight years in middle\nschool, I was the anchor for the\nclass relays, you know?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, amazing!\nSo you'll be doing it this year as\nwell?");
        Voice_PlayVoice("F0201000_A03800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", ".........");
        Message_Who(0);
        Message_MsgDisp("主人公", "Are you the anchor this year as\nwell?");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0201000_A03900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Whatever is fine.\nMake those meatheads in the Track\nand Field Club do it...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He seems to have strange reasoning\nfor many things...)");
        }
    else if (var1 == 7){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost summer break!\nDo you have any plans,\n｛Saeki＊＊｝?");
        Voice_PlayVoice("F0201000_A04000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Right.\nWhen I don't have school, I want to\nenjoy myself, so I'll wake up\nearlier than usual...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, and do radio exercises?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0201000_A04100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "... Am I a junior school kid?\nI want to go surfing.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, so you surf,\n｛Saeki＊＊｝.");
        Voice_PlayVoice("F0201000_A04200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Kinda.\nThere's quite a nice swell when a\ntyphoon gets close to Hanegasaki,\nright?");
        Message_Who(0);
        Message_MsgDisp("主人公", "\"Right\"...\nYou go into the ocean when there's a\ntyphoon!?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0201000_A04300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It can't be helped, there are nice\nwaves.\nIf you don't like it, then just do\nyour radio exercises.");
        Message_Who(0);
        Message_MsgDisp("主人公", "How dangerous...");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(1, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0201000_A04400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I wonder when the typhoon will come\naround this year!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 8){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost the Culture Festival.\nHow are preparations going,\n｛Saeki＊＊｝?");
        Voice_PlayVoice("F0201000_A04500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I'm not doing anything.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I see, you're not in any clubs,\n｛Saeki＊＊｝.\nBut your class is doing something,\nright?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(1, 3, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0201000_A04600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "They are...\n*sigh* What is so fun about this?");
        Message_Who(0);
        Message_MsgDisp("主人公", "There might be something fun to do\nif you tried participating?");
        Character_BlinkStart(1, 0, (#1), 1);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0201000_A04700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "There isn't.\nBut more customers come to Sangosho\non the Culture Festival day.\nSo I guess it's good.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(How calculating...)");
        }
    else if (var1 == 10){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost the\nCulture Festival.");
        Voice_PlayVoice("F0201000_A04800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Will the play even be good?\nWe're not junior school kids.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That attitude again...\nBut you know, there are quite a few\npeople who are looking forward to\nit.");
        Voice_PlayVoice("F0201000_A04900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "But, well...\nTo see everyone running around\ntrying to get ready is actually\nquite fun.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(1, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0201000_A05000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I feel a bit of regret for never\nparticipating up until now...");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝...");
        Character_ChFace(0, 0, 3);
        Character_BlinkStart(1, 2, (#1), 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0201000_A05100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "...\nYou're greatly mistaken if you think\nI'd say something like that.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes, yes.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Because you're strange...)");
        }
    else if (var1 == 11){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost winter break.\nDo you have plans to go anywhere,\n｛Saeki＊＊｝?");
        Voice_PlayVoice("F0201000_A05200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "High school students have it easy...\nThere are lots of things on\nSangosho's seasonal menu.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You say that, even though you're a\nhigh school student...\nWhat's the seasonal menu?");
        Voice_PlayVoice("F0201000_A05300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "What we've thought up of at the\nmoment is hot apple pie and hot\nchocolate...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh?\nBut there's already hot cocoa on the\nmenu?");
        Voice_PlayVoice("F0201000_A05400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Hot chocolate and hot cocoa are\ndifferent, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is it?");
        Character_ChFace(0, 0, 0);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0201000_A05500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "... Is it? It isn't, is it?\nWhich is it?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm...\nPerhaps they are different after\nall...?");
        Voice_PlayVoice("F0201000_A05600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "... I suppose I should research it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Then you didn't have to ask me.)");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("F0201000_A05700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "...\nYou look like you want to say\nsomething.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Not really.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 12){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Spring break is close...\nWhat will you do,\n｛Saeki＊＊｝?");
        Voice_PlayVoice("F0201000_A05800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I might...\ngo back to my parents' house for\nspring break.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so?");
        Voice_PlayVoice("F0201000_A05900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I didn't go back for New Year's.\nThose guys make a huge fuss if I\ndon't show my face every now and\nthen.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You don't have to call them \"those\nguys\"...");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(1, 2, (#1), 1);
        Voice_PlayVoice("F0201000_A06000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Ah, sorry.\nIt's because my parents said they\nwanted to see me.\nI want to see their faces, too.");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("F0201000_A06100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "............");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He's angry...\nBut I wonder why they have such a\nbad relationship...)");
        }
    else if (var1 == 13){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost the school field trip.\nAre you ready,\n｛Saeki＊＊｝?");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("F0201000_A06200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "... I forgot! Crap...\nWill I make it in time?\nIf I hurry now...");
        Message_Who(0);
        Message_MsgDisp("主人公", "You don't have to be so flustered,\nyou can still take your time to\nprepare.");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F0201000_A06300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It's for five days, right?\nEven arranging a list of things to\nget is tough...");
        Message_Who(0);
        Message_MsgDisp("主人公", "You're exaggerating!\nIt's not like we're going on an\noverseas trip!");
        Voice_PlayVoice("F0201000_A06400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Wait, wait...\nWhat are we talking about?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?\nWe're talking about preparations for\nthe school field trip, right?");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F0201000_A06500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "You...\nAn hour would be enough to get\nready, right?\nI thought you were talking about\nSangosho.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, I see.");
        Character_BlinkStart(1, 3, (#1), 1);
        Voice_PlayVoice("F0201000_A06600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Ah...\nYour blockheadedness is still\naffecting me!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 14){
        Character_Chara_GS2(1, "M1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost the graduation\nceremony...\nTime has gone by in the blink of an\neye.");
        Voice_PlayVoice("F0201000_A06700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "... It's somewhat... sudden.\nWithout any rest and without any\nfree time.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah...");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0201000_A06800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Hey, you...");
        Message_Who(0);
        Message_MsgDisp("主人公", "What?");
        Voice_PlayVoice("F0201000_A06900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Do you remember what happened when\nwe first met?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah... I remember it clearly.");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0201000_A07000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Yeah... Me too.\nI thought that you would have\ndefinitely forgotten.");
        Message_Who(0);
        Message_MsgDisp("主人公", "As if I'd forget!\nIt was the morning of the entrance\nceremony!");
        Character_ChFace(0, 0, 11);
        Character_BlinkStart(1, 2, (#1), 1);
        Voice_PlayVoice("F0201000_A07100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "... Eh?");
        Message_Who(0);
        Message_MsgDisp("主人公", "You were really in a foul mood,\n｛Saeki＊＊｝.\nAh, but you did show me the way home\ntoo, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "You're quite spiteful,\n｛Saeki＊＊｝.\nBut perhaps it's because you're an\nadult--");
        Voice_PlayVoice("F0201000_A07200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Wait, wait. Wait a second.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("F0201000_A07300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "You...\nWhy are you making me feel this\npointless heart-throbbing...?");
        Message_Who(0);
        Message_MsgDisp("主人公", "H-Heart-throbbing...?");
        Voice_PlayVoice("F0201000_A07400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "As if I know!!");
        Message_Who(0);
        Message_MsgDisp("主人公", "W-Why are you angry all of a sudden?");
        Voice_PlayVoice("F0201000_A07500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Shut up.\nJust think about it for the rest of\nyour life!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad while walking home.)");
        }
    else {
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Saeki＊＊｝.)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
