section "f02_m5_000"{
    Character_BlinkStart(5, 1, (#1), 1);
    Character_BlinkStart(5, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    int var1 = Parameter_Kitaku_Kaiwa(1);
    if (var1 == 0){
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Chris＊＊｝.)");
        }
    else if (var1 == 1){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0205000_E00000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hey, do you know the legend of the\nlighthouse?");
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of legend?");
        Voice_PlayVoice("F0205000_E00100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "There was a prince that a mermaid\nprincess had been waiting for\nforever, but in the end, they\ncouldn't meet.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0205000_E00200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I don't know why, but it's so\npitiable...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Huh?\nI feel like I've heard that story\nsomewhere before...)");
        }
    else if (var1 == 2){
        Character_Chara_GS2(5, "M5_01F", 0);
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(5, 2, (#1), 1);
        Character_ChFace(0, 3, 1);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0205000_E00300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "That lighthouse...");
        Message_Who(0);
        Message_MsgDisp("主人公", "What's wrong with the lighthouse?");
        Voice_PlayVoice("F0205000_E00400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Apparently there is a maze inside.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, is that so?");
        Voice_PlayVoice("F0205000_E00500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Apparently there's a princess\nwaiting at the finish, but no one\nhas ever made it.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0205000_E00600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "She's waiting for someone to come...\nHow pitiable...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I feel like it's different to the\nrumors that I know...)");
        }
    else if (var1 == 3){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0205000_E00700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Have you heard the rumors about that\nlighthouse?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, what kind of rumors?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E00800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "There are heaps of cute mermaids\nthere, and if you go, they'll\nprovide you with entertainment.");
        Voice_PlayVoice("F0205000_E00900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "But apparently, there were people\nwho wanted to leave, but once you\ngo, you can't return.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E01000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "That seems like it would happen to\nme...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I feel like it's different to the\nrumors that I know...)");
        }
    else if (var1 == 4){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Right!\nIt's almost your birthday,\n｛Chris＊＊｝.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E01100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah. You remembered. I'm so glad～.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Of course I remembered!");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E01200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "*Sigh*～.\nBut I'm growing another year\nolder...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh?\nYou don't really like that fact?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E01300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... Hmm...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 5){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost the end-of-semester\ntests.\nAre your preparations going well,\n｛Chris＊＊｝?");
        Character_ChFace(0, 2, 2);
        Voice_PlayVoice("F0205000_E01400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "It feels like it is and isn't going\nwell...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, what do you mean?");
        Character_BlinkStart(5, 2, (#1), 1);
        Voice_PlayVoice("F0205000_E01500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "No matter how much I study for\ntests, I feel uneasy...\nCan't it just be over already...");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0205000_E01600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Like if I slept, woke up and it\nwould all be over.\nIf there was a world like that, I'd\nlike to go there～.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 6){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "The Sports Festival is soon.\nAre you ready,\n｛Chris＊＊｝?");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0205000_E01700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hahaha.\nI'm thinking of many things～.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Many things?");
        Character_BlinkStart(5, 0, (#1), 1);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E01800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Like if there's water in the paper\nball, or if the rope for the\nthree-legged race will be rubber.\nThings like that!");
        Message_Who(0);
        Message_MsgDisp("主人公", "I-I see...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 7){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost Summer break.\nDo you have plans,\n｛Chris＊＊｝?");
        Voice_PlayVoice("F0205000_E01900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I haven't decided on anything\nspecific, yet.\nI'll just do whatever.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E02000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ah, but I'd like to go to the pools\nor the beach.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Why?");
        Voice_PlayVoice("F0205000_E02100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Aren't there tons of cute girls at\nthose places?");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0205000_E02200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "And also, it's fun looking at the\ncute swimming costumes of the girls.");
        Character_BlinkStart(5, 2, (#1), 1);
        Voice_PlayVoice("F0205000_E02300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Summer is amazing.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Chris＊＊｝ really looks\nhappy...)");
        }
    else if (var1 == 8){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost the Culture Festival.\nHow are preparations going,\n｛Chris＊＊｝?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F0205000_E02400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I have an idea, it's to decorate the\nouter walls of the school.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh.\nDid the teachers say that it was\nokay?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E02500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "No.\nThe teachers and even the club\nmembers rejected my idea.");
        Character_BlinkStart(5, 0, (#1), 1);
        Voice_PlayVoice("F0205000_E02600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "They were like, \"Who will clean it\noff?\".\nI was a little shocked when I heard\nthat.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Why?");
        Character_BlinkStart(5, 2, (#1), 1);
        Voice_PlayVoice("F0205000_E02700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Why would they clean it off?\nIf I'm going to draw on it, I think\nthat they should just leave it on...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad while walking home.)");
        }
    else if (var1 == 9){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost the Culture Festival.\nIt's so exciting, isn't it,\n｛Chris＊＊｝!");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E02800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah.\nThe preparations are perfect, so it\nwould be nice if lots of people came\nto see.");
        Voice_PlayVoice("F0205000_E02900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I'd certainly feel happy if people\nsaw my works and smiled.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0205000_E03000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "A girl's smile is the source of my\nenergy.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I wonder...\nif it's just limited to girls?)");
        }
    else if (var1 == 10){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost the Culture Festival.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E03100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "It really is just a little while\naway.\nThe preparations are all complete,\nright?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm.");
        Voice_PlayVoice("F0205000_E03200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "But it can't be helped.\nLet's do our best in this last leg.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.\nYou're so forward looking,\n｛Chris＊＊｝.");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0205000_E03300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah. I'm really happy right now.");
        Voice_PlayVoice("F0205000_E03400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "We made a play with everyone's\npower, even though we'll only be\nperforming it once, right?");
        Character_BlinkStart(5, 0, (#1), 1);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E03500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "It's like the gory of youth.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Chris＊＊｝, it's not\ngory, it's \"glory\"...)");
        }
    else if (var1 == 11){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost Winter break.\nWhat will you be doing,\n｛Chris＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0205000_E03600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Spending it with my family...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, that's nice.\nLike a carefree feeling.");
        Character_BlinkStart(5, 2, (#1), 1);
        Voice_PlayVoice("F0205000_E03700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Staying at home during New Year's...\nAbsorbed in watching TV...\nEating mandarins under a kotatsu...");
        Message_Who(0);
        Message_MsgDisp("主人公", "... A complete holiday.");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E03800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... I want to do those things.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah...\nIt was what he wanted to do...)");
        }
    else if (var1 == 12){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Spring break is close...\nDo you have any plans,\n｛Chris＊＊｝?");
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E03900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Oh...\nI'm thinking about drawing the\ncherry blossoms on a canvas.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, is that so. Amazing.");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E04000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "It's because cherry blossoms in\nJapan are really beautiful...\nI probably won't be able to draw it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Chris＊＊｝ looks\nsomewhat sad...)");
        }
    else if (var1 == 13){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost the school field trip.\nI'm looking forward to it.");
        Voice_PlayVoice("F0205000_E04100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah, you're right.\nIt would be nice if we could share\nthe same room.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\n｛Chris＊＊｝, boys and\ngirls are in different rooms.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(5, 2, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0205000_E04200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Eh, is that so!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-Yeah...");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0205000_E04300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Really......");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He got depressed...)");
        }
    else if (var1 == 14){
        Character_Chara_GS2(5, "M5_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost the graduation\nceremony...\nIt went by in a blink of an eye.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0205000_E04400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... Yeah.");
        Voice_PlayVoice("F0205000_E04500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I wonder why time flies by when\nyou're having fun.");
        Character_BlinkStart(5, 2, (#1), 1);
        Voice_PlayVoice("F0205000_E04600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "We'll even have to say goodbye to\nthis school uniform in a little\nwhile...");
        Character_BlinkStart(5, 0, (#1), 1);
        Voice_PlayVoice("F0205000_E04700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Even being able to talk with you\nlike this when going home from\nschool...");
        Character_BlinkStart(5, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E04800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Although it was short, these three\nyears were fun...");
        Message_Who(0);
        Message_MsgDisp("主人公", "... ｛Chris＊＊｝?");
        Character_BlinkStart(5, 0, (#1), 1);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("", 5, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hm?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0205000_E04900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Please treat me well, until the very\nend of our high school days.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(What's wrong with\n｛Chris＊＊｝...?)");
        }
    else {
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Chris＊＊｝.)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
