section "f02_g3_000"{
    Character_BlinkStart(12, 1, (#1), 1);
    Character_BlinkStart(12, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    int var1 = Parameter_Kitaku_Kaiwa(1);
    if (var1 == 0){
        Background_Bg_GS2("BG_EX100_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Nishimoto＊＊｝.)");
        }
    else if (var1 == 1){
        Character_Chara_GS2(12, "G3_01F", 0);
        Character_ChFace(0, 0, 10);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0212000_L00000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Hey, did you know?\nApparently, there's a really amazing\nlegend about the lighthouse near the\nbeach!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, what kind?");
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0212000_L00100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "A couple who had their wedding\nceremony there were promised eternal\nhappiness...\nIsn't that amazing?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, it's wonderful.");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(12, 3, (#1), 1);
        Voice_PlayVoice("F0212000_L00200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "It's so romantic!\nWhen I heard about that, my body\njust started trembling...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, why?");
        Character_BlinkStart(12, 0, (#1), 1);
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0212000_L00300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Eh? Ah, it's...\nobviously because it's funny!\nSo funny to the point my stomach\nhurts!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm... is that so?");
        }
    else if (var1 == 2){
        Character_Chara_GS2(12, "G3_01F", 0);
        Character_ChFace(0, 3, 2);
        Background_Bg_GS2("BG_EX101_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0212000_L00400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "That reminds me, there's been some\nrumors lately about that lighthouse\nnear the beach.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, what kind of rumors?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F0212000_L00500", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Apparently, one large recreational\narea is going to be built there.\nLike the best ferris wheel in the\nworld.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, where the lighthouse is?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0212000_L00600", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "If they are, I want to work there in\nthe future...!\nAn amusement park there sounds like\nfun.");
        }
    else if (var1 == 3){
        Character_Chara_GS2(12, "G3_01F", 0);
        Character_ChFace(0, 0, 8);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0212000_L00700", #1, "F0212000_L00701");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "This is bad, ｛主人公｝!\nDon't go near that lighthouse near\nthe beach ever, again!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!\nWhy are you saying that all of a\nsudden?");
        Character_BlinkStart(12, 2, (#1), 1);
        Voice_PlayVoice("F0212000_L00800", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "It used to be a graveyard.\nMy friend who was near there in the\nmiddle of the night said she saw a\nphantom ship!");
        Message_Who(0);
        Message_MsgDisp("主人公", "That has to be a lie.");
        Character_BlinkStart(12, 0, (#1), 1);
        Voice_PlayVoice("F0212000_L00900", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Also, apparently, whoever sees the\nphantom ship can never return to the\nland of the living, again!");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F0212000_L01000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ah it's scary.\nIt's really scary, isn't it?\nEven just talking about it sends\nchills down my spine...!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh?\nBut didn't your friend see the\nphantom ship...?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0212000_L01100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Huh...?\nWell, I would say that she did see\nit, maybe?");
        }
    else if (var1 == 4){
        Character_Chara_GS2(12, "G3_01F", 0);
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(12, 2, (#1), 1);
        Background_Bg_GS2("BG_EX101_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0212000_L01200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "It's almost my birthday... *Sigh*.\nI'm getting older and older.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, you don't like that fact?");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("F0212000_L01300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "I want to be a child forever!\nMy height hasn't changed since\njunior school, though.");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F0212000_L01400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "The only thing enjoyable about my\nbirthday is the moment I blow out\nthe candles on a cake.");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0212000_L01500", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ah, but then there's also the moment\nI receive a present...");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0212000_L01600", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ah, and also the moment I eat\ncake...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Right, it's ｛Nishimoto＊＊｝'s\nbirthday soon...)");
        }
    else if (var1 == 5){
        Character_Chara_GS2(12, "G3_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost the\nend-of-semester tests.");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0212000_L01700", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "What? That's...\nYour ulterior motive is to make me\nfeel depressed by making me feel bad\nabout my grades...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, that's not it!");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0212000_L01800", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Argh.\nIf there were no exams then school\nwould be heaven!\nShould we have a no-tests motion?");
        Message_Who(0);
        Message_MsgDisp("主人公", "A no-tests motion?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0212000_L01900", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Collecting signatures to abolish\ntests!\nDon't you think we'd get a lot?\nHow's this for an idea!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm... It might be a bit difficult.");
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0212000_L02000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Is it no good?\nI thought it would go quite well,\nthough.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It's almost the end-of-semester\ntests...\nI must try my best!)");
        }
    else if (var1 == 6){
        Character_Chara_GS2(12, "G3_01F", 0);
        Character_ChFace(0, 0, 10);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0212000_L02100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ah, that reminds me, it's almost the\nSports Festival!\nWah, I really look forward to it!");
        Message_Who(0);
        Message_MsgDisp("主人公", "You're really eager, aren't you!?");
        Character_ChFace(0, 2, 1);
        Voice_PlayVoice("F0212000_L02200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "I run just about as fast as I talk!\nI'll show everyone my good points!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Haha, how promising!");
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0212000_L02300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Leave it to me～!\nMy blood boils with excitement when\nit's festival time!");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(12, 3, (#1), 1);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("F0212000_L02400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Don't you itch to do something when\nyou hear the word \"festival\"?\nDoesn't it seem fun?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, it would be nice if things\nwere really hyped up!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I should also do my best at the\nSports Festival!)");
        }
    else if (var1 == 7){
        Character_Chara_GS2(12, "G3_01F", 0);
        Background_Bg_GS2("BG_EX101_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "It's almost summer break.\nDo you have any plans for it,\n｛Nishimoto＊＊｝?");
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0212000_L02500", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Just a general idea.\nFirst would be to finish my homework\nby the end of July, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0212000_L02600", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Then I was thinking about going to\nthe school pool throughout August.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh... Why?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0212000_L02700", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ahaha...\nI eat too many sweet things, so my\nweight is a little out of hand...");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0212000_L02800", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "That's why I've set in place the\n\"Nishimoto Haruhi Demonic\nTransformation Diet\" plan.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0212000_L02900", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "I aim to finish the plan this\nsummer.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Isn't your aim to lose weight?");
        Character_ChFace(0, 2, 1);
        Voice_PlayVoice("F0212000_L03000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Yeah.\nThe biggest hurdle is the \"Conquest\nof homework by the end of July\".");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F0212000_L03100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "It's always been the same since\njunior school.\nThere hasn't been a time where it\nwent well.");
        Character_BlinkStart(12, 3, (#1), 1);
        Voice_PlayVoice("F0212000_L03200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Before I know it, it's the 31st of\nAugust.\nIt's bad, because there are lots of\ntemptations during summer break...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It seems like the same thing will\nhappen to ｛Nishimoto＊＊｝\nagain this year...)");
        }
    else if (var1 == 8){
        Character_Chara_GS2(12, "G3_01F", 0);
        Background_Bg_GS2("BG_EX101_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost the\nCulture Festival.\nAre your preparations going well?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0212000_L03300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Yes, perfectly!\nEarlier, I found a guy who had\nskipped the preparations and beat\nhim black and blue.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh! W-Was he okay...?");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0212000_L03400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "It's bad to spoil them like that!\nIf you tell them off with one blow,\nthey'll listen to you.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(12, 3, (#1), 1);
        Voice_PlayVoice("F0212000_L03500", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "It's because everyone has to be\nhyped up during festivals.\nIt will be better that way!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It's almost the Culture Festival.\nI'm looking forward to it!)");
        }
    else if (var1 == 10){
        Character_Chara_GS2(12, "G3_01F", 0);
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 2);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0212000_L03600", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "... Ehh... That goes, like this...\nBut then...");
        Message_Who(0);
        Message_MsgDisp("主人公", "What's up, ｛Nishimoto＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0212000_L03700", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Hmm...\nI was kind of panicking, thinking\nabout the Culture Festival play...");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(12, 3, (#1), 1);
        Voice_PlayVoice("F0212000_L03800", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "People are depending on me and I'm\nresponsible for the play.\nBut it's quite difficult...");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(12, 2, (#1), 1);
        Voice_PlayVoice("F0212000_L03900", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "It'll definitely be interesting!\nThe both of us should do our best!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, I look forward to it!");
        }
    else if (var1 == 11){
        Character_Chara_GS2(12, "G3_01F", 0);
        Background_Bg_GS2("BG_EX101_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Have you decided on your plans for\nthe winter break,\n｛Nishimoto＊＊｝?");
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0212000_L04000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ah, yes.\nI kind of dislike cold places,\nthough.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, is that so?\nYou look full of energy, though.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0212000_L04100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Of course, I love skiing and\nsnowboarding!\nI plan to have a lot of fun in\nWinter, as well.");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F0212000_L04200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "But you see, when it's frozen, my\ntongue can't move well, right?\nSo I speak slower in Winter.");
        Character_BlinkStart(12, 2, (#1), 1);
        Voice_PlayVoice("F0212000_L04300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "That is a little painful for me...\nSpeaking as fast as a machine gun is\nwhat people love too.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(So that means she'll speak like a\nnormal person then...)");
        }
    else if (var1 == 12){
        Character_Chara_GS2(12, "G3_01F", 0);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 4);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0212000_L04400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ah, it's almost spring break!\nWhat should I do? What should I do?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Why are so rushed?");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0212000_L04500", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Because spring break is short, isn't\nit?\nIf you space out, it'll be over\nbefore you know it!");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F0212000_L04600", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "The only relief is that there's no\nhomework.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh?\nDidn't Wakaouji-sensei say that he\nmight give out some spring break\nhomework?");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0212000_L04700", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "For real!? That's bad! Hmm...\nHow can I stop him from doing\nthat...?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0212000_L04800", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Attack him with sex appeal!? ...\nI can't.\nThat's really unsuitable for me...\nUgh～.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Nishimoto＊＊｝ really wants\nto stop him from giving out\nhomework...)");
        }
    else if (var1 == 13){
        Character_Chara_GS2(12, "G3_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0212000_L04900", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Hey.\nDo you think the destination for our\nschool field trip can be changed?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm? Why?");
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0212000_L05000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Because I go to Kyoto every year for\nNew Year's.");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F0212000_L05100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "It's also really close to my\ngrandma's place...\nIt's kind of stupid.");
        Message_Who(0);
        Message_MsgDisp("主人公", "But won't it be fun since you get to\ngo with everyone?");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0212000_L05200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ah, right.\nI can think about it that way.\nYou're really smart!");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0212000_L05300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ah, I'll also tell everyone about\nthe sweets stores that I recommend!");
        Character_BlinkStart(12, 3, (#1), 1);
        Voice_PlayVoice("F0212000_L05400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Hmm, I'm really looking forward to\nit now～!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I am also really looking forward to\nit!)");
        }
    else if (var1 == 14){
        Character_Chara_GS2(12, "G3_01F", 0);
        Character_ChFace(0, 0, 9);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0212000_L05500", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "... Hey, ｛主人公｝...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, what's up?");
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0212000_L05600", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "That...\nEven if we graduate, you'll still...\n*Sobs*...");
        Message_Who(0);
        Message_MsgDisp("主人公", "E-Wh--? W-What's wrong...?");
        Character_BlinkStart(12, 0, (#1), 1);
        Voice_PlayVoice("F0212000_L05700", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "... I-It's nothing.\nSomething went into my eye, that's\nall...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Are you alright...?");
        Character_BlinkStart(12, 3, (#1), 1);
        Voice_PlayVoice("F0212000_L05800", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Yeah.........");
        Message_Who(0);
        Message_MsgDisp("主人公", "I feel sad...");
        Voice_PlayVoice("F0212000_L05900", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "......");
        Message_Who(0);
        Message_MsgDisp("主人公", "(There is only a little while left\nbefore graduation...)");
        }
    else {
        Background_Bg_GS2("BG_EX100_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Nishimoto＊＊｝.)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
