section "f02_g1_000"{
    Character_BlinkStart(10, 1, (#1), 1);
    Character_BlinkStart(10, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    int var1 = Parameter_Kitaku_Kaiwa(1);
    if (var1 == 0){
        Background_Bg_GS2("BG_EX101_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Toudou＊＊｝.)");
        }
    else if (var1 == 1){
        Character_Chara_GS2(10, "G1_01F", 0);
        Background_Bg_GS2("BG_EX101_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0210000_J00000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Have you heard the legend of the\nlighthouse?");
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of legend?");
        Voice_PlayVoice("F0210000_J00100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Two separated lovers were able to\nmeet again, after they prayed for it\nat the lighthouse.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh... How romantic.");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0210000_J00200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Perhaps.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_BlinkStart(10, 0, (#1), 1);
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0210000_J00300", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I think the best way to be able to\nmeet each other again is to put in\nthe effort, not to rely on the\nlighthouse.");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0210000_J00400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Why would you rely on such a\nlegend...?\nI would be extremely puzzled if\nsomeone had tried it on me.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm, perhaps...)");
        }
    else if (var1 == 2){
        Character_Chara_GS2(10, "G1_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0210000_J00500", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Lately, I've heard some rumors about\nthe lighthouse near the beach.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, what kind of rumors?");
        Character_BlinkStart(10, 2, (#1), 1);
        Voice_PlayVoice("F0210000_J00600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "It's been said that the lighthouse\nmoves 1cm each year.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh, really?");
        Character_BlinkStart(10, 0, (#1), 1);
        Voice_PlayVoice("F0210000_J00700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "It's been said that lighthouse's aim\nis to be shining down over the area\nin the middle of the ocean.");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0210000_J00800", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "How unbelievable...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm, what an outrageous story.)");
        }
    else if (var1 == 3){
        Character_Chara_GS2(10, "G1_01F", 0);
        Background_Bg_GS2("BG_EX101_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0210000_J00900", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Do you know what they are saying\nabout the lighthouse?");
        Message_Who(0);
        Message_MsgDisp("主人公", "What are they saying?");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0210000_J01000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "There's a legend about the\nlighthouse, right?\nThey say that the lighthouse lures\npeople into it, then feeds on them.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Feeds!?");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0210000_J01100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Apparently, it steals the spirits of\nthe people who were tricked, and\nuses it to shine the light.");
        Message_Who(0);
        Message_MsgDisp("主人公", "What an a-amazing story.");
        Character_BlinkStart(10, 0, (#1), 1);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0210000_J01200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "It even seems like that rumor is\ngoing to be turned into a film.\nGood grief, there are so many people\nwith free time...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Rumors about the lighthouse being\nturned into a movie...\nHmm, I wonder if it's true?)");
        }
    else if (var1 == 4){
        Character_Chara_GS2(10, "G1_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me,\n｛Toudou＊＊｝, it's almost\nyour birthday!");
        Voice_PlayVoice("F0210000_J01300", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Yeah, right.");
        Message_Who(0);
        Message_MsgDisp("主人公", "How apathetic. Aren't you glad?");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0210000_J01400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Not really...");
        Character_BlinkStart(10, 0, (#1), 1);
        Voice_PlayVoice("F0210000_J01500", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I do want to become an adult, but\ngrowing older and becoming an adult\nare different things.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Toudou＊＊｝ is as dry as\never.)");
        }
    else if (var1 == 5){
        Character_Chara_GS2(10, "G1_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, we're close to the\nend of semester tests.");
        Voice_PlayVoice("F0210000_J01600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Hmm...");
        Message_Who(0);
        Message_MsgDisp("主人公", "\"Hmm\"...\nYou're confident about it, aren't\nyou, ｛Toudou＊＊｝?");
        Character_ChFace(0, 2, 0);
        Voice_PlayVoice("F0210000_J01700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Not really... Why are you rushing?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Because I have to study.");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0210000_J01800", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Wouldn't it be okay if you don't\nstudy, if you don't want to?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm, but...");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0210000_J01900", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Isn't it boring being made to do\nthings?");
        Character_BlinkStart(10, 0, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0210000_J02000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I don't study.\nI will take the path that I believe\nin.\nThat's all.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Toudou＊＊｝ seemed kind\nof radiant there for a second...)");
        }
    else if (var1 == 6){
        Character_Chara_GS2(10, "G1_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost the\nSports Festival.");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0210000_J02100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Hmph.");
        Message_Who(0);
        Message_MsgDisp("主人公", "What's up?");
        Character_BlinkStart(10, 0, (#1), 1);
        Character_ChFace(0, 7, 0);
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0210000_J02200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "...\nSince ages ago, people have always\ndepended on me during Sports\nFestivals for that...");
        Message_Who(0);
        Message_MsgDisp("主人公", "What do you mean by \"that\"?");
        Character_ChFace(0, 2, 2);
        Voice_PlayVoice("F0210000_J02300", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "That is tiring...\nAnd makes me sweat.\nI don't want to do it this year,\neither.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm... What is \"that\"?)");
        }
    else if (var1 == 7){
        Character_Chara_GS2(10, "G1_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Toudou＊＊｝, what will you\nbe doing during Summer break?");
        Voice_PlayVoice("F0210000_J02400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Probably work, and when I get the\nchance, go to school.");
        Message_Who(0);
        Message_MsgDisp("主人公", "School?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0210000_J02500", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "A nail course.\nLike a Summer short course.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh? Cool!");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(10, 2, (#1), 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0210000_J02600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I'm looking for people to practice\non.\nDo you want me to do your nails?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, I'd love for you to do that!");
        }
    else if (var1 == 8){
        Character_Chara_GS2(10, "G1_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost time\nfor the Culture Festival.\nAre your preparations going well?");
        Voice_PlayVoice("F0210000_J02700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Well...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Well?\nAre you doing something,\n｛Toudou＊＊｝?");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0210000_J02800", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Do you think I am?");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Probably not?");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(10, 2, (#1), 1);
        Voice_PlayVoice("F0210000_J02900", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "*Sigh*...\nThat's why I can't do my work.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(People probably don't ask\n｛Toudou＊＊｝ to do things\nbecause she's scary)");
        }
    else if (var1 == 10){
        Character_Chara_GS2(10, "G1_01F", 0);
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(10, 3, (#1), 1);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0210000_J03000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... *Phew*.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Why did you sigh?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F0210000_J03100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "We're doing a stage play, but it's\nquite tough...");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F0210000_J03200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "If I keep urging them to improve,\nI'll make the girls cry.");
        Character_BlinkStart(10, 2, (#1), 1);
        Voice_PlayVoice("F0210000_J03300", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "If I console them, another girl\nwould be like, \"You're hogging\nToudou-san\" and will start crying...");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0210000_J03400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I'm very weak against a girl's\ntears...\nI want them to forgive me, though...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It's unexpected that\n｛Toudou＊＊｝'s weak point\nis a girl's tears.)");
        }
    else if (var1 == 11){
        Character_Chara_GS2(10, "G1_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Have you made plans for the Winter\nbreak, ｛Toudou＊＊｝?");
        Voice_PlayVoice("F0210000_J03500", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I'll be writing New Year's cards,\nthen I'll do a major clean up,\nshrine visits, and then make New\nYear calls.");
        Message_Who(0);
        Message_MsgDisp("主人公", "It seems like it's a routine thing\nfor you.");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0210000_J03600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "It's because I have a principle of\nwanting to take clear\nresponsibility.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so...\nI must follow your example.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0210000_J03700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Haha.");
        }
    else if (var1 == 12){
        Character_Chara_GS2(10, "G1_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F0210000_J03800", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "It's almost Spring break...");
        Message_Who(0);
        Message_MsgDisp("主人公", "That's right.\nDo you have anything at all that\nyou're interested in?");
        Character_ChFace(0, 2, 3);
        Voice_PlayVoice("F0210000_J03900", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "National Baseball Championships...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, so you're interested in\nbaseball, ｛Toudou＊＊｝?");
        Character_BlinkStart(10, 3, (#1), 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0210000_J04000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Not really.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It seems like something she would\nbe interested in...)");
        }
    else if (var1 == 13){
        Character_Chara_GS2(10, "G1_01F", 0);
        Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, it's almost the\nschool field trip.");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0210000_J04100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I don't like group activities...");
        Character_ChFace(0, 2, 2);
        Voice_PlayVoice("F0210000_J04200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Isn't it embarrassing to have groups\nof people in the same school\nuniform, while out in the middle of\nthe town?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm, that doesn't really concern me.");
        Message_Who(0);
        Message_MsgDisp("主人公", "And there's also free time!");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0210000_J04300", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I envy you when you're like this.\nWell, perhaps I'll just try and do\nwhatever works.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(There's only a short while left\nbefore the school field trip.\nI'm looking forward to it!)");
        }
    else if (var1 == 14){
        Character_Chara_GS2(10, "G1_01F", 0);
        Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "We're graduating soon...");
        Voice_PlayVoice("F0210000_J04400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Right.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Are you sad about that,\n｛Toudou＊＊｝?");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0210000_J04500", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Not really.");
        Character_BlinkStart(10, 0, (#1), 1);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0210000_J04600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "It's because I think that I will be\nable to see the people that I really\nwant to see.");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0210000_J04700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Right, ｛主人公｝?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, that's right.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(We're graduating in a really short\nwhile...)");
        }
    else {
        Background_Bg_GS2("BG_EX101_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(I had fun walking home from school\nwith ｛Toudou＊＊｝.)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
