section "f03_g4_000"{
    Character_BlinkStart(13, 1, (#1), 1);
    Character_BlinkStart(13, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(13, "G4_03F", 0);
    Background_Bg_GS2("BG_EX000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGB_062_000", 127, 40);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hey, ｛Mizushima＊＊｝.\nCan I ask you something?");
    Voice_PlayVoice("F0313000_M00000", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Sure, go ahead.");
    Message_Sele_Kitaku_Kaiwa();
    int var1 = Parameter_Kitaku_Kaiwa(0);
    switch (var1){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you often watch TV,\n｛Mizushima＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M00100", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Yes, I do watch TV.\nMovies, dramas, and such...\nAlso, shows aimed at babies.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Shows aimed at babies?");
        Voice_PlayVoice("F0313000_M00200", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Yes. I watch it with my nephew.\nIt's called \"Sorashido Peanuts\".\nDo you know of it?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I haven't watched it, though...");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0313000_M00300", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "When the dance segment comes on, my\nnephew gets really happy, you know?\nI dance along with my nephew!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I kind of can't imagine that...)");
        Parameter_InCh1Param(13, 530, 35);
        break ;
        case 1:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have any foods that you don't\nlike?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0313000_M00400", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Not now.\nWhen I was younger, I really hated\nmany types of food.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, is that so?\nCan you eat anything?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M00500", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Yes. I might even eat too much.\nSince I've come to be able to cook\nmy own food, I've been overeating.");
        Message_Who(0);
        Message_MsgDisp("主人公", "So you cook, ｛Mizushima＊＊｝?");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0313000_M00600", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Sort of.\nIt doesn't taste that bad, you know?\nYou'll come to respect my cooking,\nokay?\nHaha.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm～, as expected,\n｛Mizushima＊＊｝ is amazing.)");
        Parameter_InCh1Param(13, 531, 36);
        break ;
        case 2:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you like sports?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0313000_M00700", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "I can't play ball games at all.\nI panic when the ball comes towards\nme.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you not like exercising?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0313000_M00800", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Hmm～...\nI did do Aikido when I was younger.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh! Ah, but it suits you, perhaps?!");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M00900", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Is that so? I also did Kendo.\nAnd a bit of halberd training.\nSee, my family is an old-fashioned\nfamily.");
        Message_Who(0);
        Message_MsgDisp("主人公", "E-Ehh...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It's probably better to not make\n｛Mizushima＊＊｝ angry...)");
        Parameter_InCh1Param(13, 532, 37);
        break ;
        case 3:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of music do you listen to,\n｛Mizushima＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M01000", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Jazz funk.... Do you know of it?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm～, somewhat.");
        Voice_PlayVoice("F0313000_M01100", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "When I was younger, I was made to\nlisten to classical music, but when\nin middle school, I borrowed my\nsister's jazz funk CDs.");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0313000_M01200", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "A really beautiful woman was playing\nthe saxophone.\nThen I thought \"I want to play the\nsax coolly, like she does\".");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, then perhaps...");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0313000_M01300", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Right!\nFrom then on, I started playing the\nsaxophone....\nHaha, is it a bit uncool?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(A saxophone player that\n｛Mizushima＊＊｝ aspires to\nbe...\nShe must be an amazing woman.)");
        Parameter_InCh1Param(13, 533, 38);
        break ;
        case 4:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have any kind of hobbies,\n｛Mizushima＊＊｝?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0313000_M01400", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Hmm～...\nI have many, but as expected, it has\nto be horoscopes.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, when we first\nmet...");
        Voice_PlayVoice("F0313000_M01500", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Yes.\nIf I don't check my horoscope daily,\nI cannot remain calm...");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0313000_M01600", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "But you know?\nThey are extremely accurate.\nIt's true, you know?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(So ｛Mizushima＊＊｝ is the\nkind to rely on horoscopes...)");
        Parameter_InCh1Param(13, 529, 34);
        break ;
        case 5:
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Mizushima＊＊｝, what were you\nlike in middle school?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M01700", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Right... Hmm...");
        Message_Who(0);
        Message_MsgDisp("主人公", "...?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M01800", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Hey, what do you think I was like?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm～...\nI can't imagine you being any\ndifferent to how you are now.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M01900", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Really?\nShould I just go with that answer\nthen?\nHaha...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-Yeah...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I want to ask, yet I can't ask.\nIf I push the issue any more than\nthis...)");
        Parameter_InCh1Param(13, 534, 39);
        break ;
        case 6:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have any kind of dream for\nthe future, ｛Mizushima＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M02000", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Dreams, huh... Dreams. Hmm～...");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nLike marrying into another family?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M02100", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Is that the kind of feeling you get\nfrom me?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Well, you have the feeling of being\na good wife and a wise mother,\n｛Mizushima＊＊｝.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M02200", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "That might be okay...\nAh, but he might have to marry into\nmy family, because my sister married\ninto another family.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I see.\nThen when you get a groom,\n｛Mizushima＊＊｝--");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M02300", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Hmm～... A groom, huh...");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Mizushima＊＊｝?");
        Character_ChFace(0, 4, 1);
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0313000_M02400", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Haha, hahaha!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nIt looks like ｛Mizushima＊＊｝\nis imagining something funny.)");
        Parameter_InCh1Param(13, 528, 33);
        break ;
        case 7:
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Mizushima＊＊｝, what kind of\nperson do you like?\nI mean your type.");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0313000_M02500", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Hmm!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Like a type of person you like.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M02600", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Hmm～, uhh～... Huh?\nWhat are we talking about?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, you're feigning ignorance!");
        Character_BlinkStart(13, 0, (#1), 1);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M02700", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Gee... Do I have to say it?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Please.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M02800", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "I...\nAs expected, a liberal person would\nbe nice.\nA person who can't be restrained\nfrom their freedom.");
        Voice_PlayVoice("F0313000_M02900", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "The people around him think he's\nweird, and he's a little perverted,\nbut that is just because he is\nnatural.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm... Huh?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0313000_M03000", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "According to my horoscope...\nNo, it's nothing. *Sigh*...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nIt seems like ｛Mizushima＊＊｝\nhas a person that she likes...)");
        Parameter_InCh1Param(13, 535, 40);
        break ;
        case 8:
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Mizushima＊＊｝, what kind of\nlove do you long for?");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M03100", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Ah...\nYou've got someone you like, don't\nyou?");
        Message_Who(0);
        Message_MsgDisp("主人公", "T-That's not it!");
        Voice_PlayVoice("F0313000_M03200", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "You're at that age, aren't you?");
        Message_Who(0);
        Message_MsgDisp("主人公", "We're the same age!");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0313000_M03300", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Haha....\nAs expected, I want the person I\nlike to have freedom.");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(13, 0, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0313000_M03400", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "I want them to be how they are\nnaturally...\nI'm quite attracted to people who\nshow off their freedom.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Eh... So that's how it is.)");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M03500", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "But in actuality...\nI'll surely be restrained.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Really?");
        Voice_PlayVoice("F0313000_M03600", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Yes, really.\nThis is too much already.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Mizushima＊＊｝ feels like\nit's too much...\nSo that's how it is...)");
        Parameter_InCh1Param(13, 536, 41);
        break ;
        case 9:
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Mizushima＊＊｝...\nUmm, have you ever kissed someone\nbefore?");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0313000_M03700", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "... Have you?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!? I'm not talking about myself.\nFor example!");
        Voice_PlayVoice("F0313000_M03800", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "For example?");
        Message_Who(0);
        Message_MsgDisp("主人公", "What do you think about accidentally\nkissing someone...?\nWould you become interested in them?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M03900", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Right...\nI think that it would be fine if\nboth people clarified their\nfeelings.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0313000_M04000", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "But I think that kind of fateful\nthing is amazing.\nLike the stars were aligned for it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "The stars were aligned...");
        Character_BlinkStart(13, 0, (#1), 1);
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0313000_M04100", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Hey, so then?\nWhen did it happen with that person?\nConfess to them!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ugh...\nI probably brought this on\nmyself...)");
        Parameter_InCh1Param(13, 537, 42);
        break ;
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Music_StopBGM(0, 40);
    Screen_ClearScreen();
    }
