section "f03_m5_000"{
    Character_BlinkStart(5, 1, (#1), 1);
    Character_BlinkStart(5, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(5, "M5_03F", 0);
    Background_Bg_GS2("BG_EX000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGB_062_000", 127, 40);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Hey, ｛Chris＊＊｝.");
    Voice_PlayVoice("F0305000_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Hmm?");
    Message_Sele_Kitaku_Kaiwa();
    int var1 = Parameter_Kitaku_Kaiwa(0);
    switch (var1){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of TV shows do you usually\nwatch, ｛Chris＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0305000_E00100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I watch anything, but...\nRight, I often watch educational\nshows.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, educational shows?\nLike the 'something' course?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E00200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah. Those are quite interesting.\nLike Japanese history.");
        Voice_PlayVoice("F0305000_E00300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "The latest hit TV show is \"Fun and\nEasy Conversational English\".");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Conversational English?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E00400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah.\nWhen I watch that, I really feel\nlike I can speak better English.\nIt's strange.");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0305000_E00500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I recommend that show～.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I wonder why he watches TV shows\nabout Conversational English...)");
        Parameter_InCh1Param(5, 530, 35);
        break ;
        case 1:
        Message_Who(0);
        Message_MsgDisp("主人公", "What Japanese food do you like,\n｛Chris＊＊｝?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0305000_E00600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I like everything.\nJapanese cuisine is healthy.");
        Voice_PlayVoice("F0305000_E00700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "My mother was also a Japanese food\nfanatic once.\nLike nattou or okra and avocado\nsalad.");
        Message_Who(0);
        Message_MsgDisp("主人公", "E-Eh...");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E00800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "What left a deep impression when I\ncame here was the flavoring on\nrice～.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Are you talking about furikake?");
        Voice_PlayVoice("F0305000_E00900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah.\nThat really left a deep impression.\nI have a lot at home.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nI wonder if you could also call\nfurikake Japanese food.)");
        Parameter_InCh1Param(5, 531, 36);
        break ;
        case 2:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you play any sports,\n｛Chris＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0305000_E01000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "One that I've always played is\ntennis.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh... Are you good at it?");
        Voice_PlayVoice("F0305000_E01100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I wonder.\nI was once chosen to play in a\ntournament.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Amazing!");
        Voice_PlayVoice("F0305000_E01200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "But in the end, I couldn't compete.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Why not?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E01300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hm.\nWhen people get more serious, aren't\nall of their faces scary?");
        Voice_PlayVoice("F0305000_E01400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Wouldn't it be more fun if everyone\ncould just keep playing rallies?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-Yeah.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E01500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Playing long rallies with the\ninstructor on my court is the most\nenjoyable...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(So ｛Chris＊＊｝ has a\ntennis court at his place...)");
        Parameter_InCh1Param(5, 532, 37);
        break ;
        case 3:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of music do you like,\n｛Chris＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E01600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I like songs on the piano.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Like classical music?");
        Voice_PlayVoice("F0305000_E01700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Classical, pop piano arrangements...\nThe genre doesn't matter to me.");
        Character_BlinkStart(5, 2, (#1), 1);
        Voice_PlayVoice("F0305000_E01800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I play sometimes too, but I prefer\nlistening, after all.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, so you can play the piano,\n｛Chris＊＊｝.");
        Character_BlinkStart(5, 0, (#1), 1);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E01900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah, just a little.\nBut I don't play with a score or\nanything.\nPlaying however I like is fun.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0305000_E02000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Although I can't play the same thing\ntwice, it's fun.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It really sounds like fun.)");
        Parameter_InCh1Param(5, 533, 38);
        break ;
        case 4:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have any hobbies,\n｛Chris＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E02100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "My hobbies are trying everything to\ndo with art.\nAmongst those, I like sketching the\nmost.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you even draw at home?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0305000_E02200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "No.\nI only draw occasionally, but\nthey're only sketches.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm. So then what do you do at home?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F0305000_E02300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Right...\nPerhaps I use the computer often.");
        Message_Who(0);
        Message_MsgDisp("主人公", "The internet?");
        Voice_PlayVoice("F0305000_E02400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah.\nOnce I find something, I won't stop.");
        Message_Who(0);
        Message_MsgDisp("主人公", "There are lots of websites with\ncute, older girls.");
        Character_BlinkStart(5, 0, (#1), 1);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E02500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Right～...\nI don't go to those sites, though.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E02600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "There may be many websites like\nthat, but it's not like I even\nforget the time when looking at\nthose websites.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(So he forgets the time...)");
        Parameter_InCh1Param(5, 529, 34);
        break ;
        case 5:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of a kid were you before\nyou came to Japan,\n｛Chris＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E02700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Right. I was a busy child.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh.\nDid you take lots of\nextra-curricular lessons and stuff?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E02800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah, something like that.");
        Voice_PlayVoice("F0305000_E02900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Even though my dad didn't care much\nabout it, my mom was really\nenthusiastic about it...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm...\nWhat kind of lessons did you take?");
        Character_BlinkStart(5, 0, (#1), 1);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E03000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Golf, polo school, and also horse\nriding and stuff...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh～. Amazing!");
        Voice_PlayVoice("F0305000_E03100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "It's not that amazing.\nWhere I lived, horse riding was a\npart of the life.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that... so?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0305000_E03200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "You didn't know?\nIf people lived nearby, you would go\nto their place by horse.");
        Voice_PlayVoice("F0305000_E03300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "The main form of traveling was by\nhorse taxis.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nIt's my first time hearing about\nsuch a thing.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E03400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "That's bad～.\nIf you don't learn more, you'll be\nleft behind in the times～.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm, is he making fun of me...?)");
        Parameter_InCh1Param(5, 534, 39);
        break ;
        case 6:
        Message_Who(0);
        Message_MsgDisp("主人公", "What do you want to do in the\nfuture, ｛Chris＊＊｝?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E03500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hmm...\nThat's quite a difficult question.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, really?\nHmm, what about your dreams, then?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E03600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I want to go to China and try\nlearning how to do India-ink\npaintings...");
        Voice_PlayVoice("F0305000_E03700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Also, Decotora.\nI want to try painting～.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Decotora?");
        Character_BlinkStart(5, 0, (#1), 1);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E03800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "It's an abbreviation for decoration\ntruck.\nHave you ever seen those extremely\nflashy trucks that have drawings on\nthem?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Perhaps...\nSo you want to try doing that?");
        Voice_PlayVoice("F0305000_E03900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah.\nI want to try doing everything in\nthe art world once.");
        Message_Who(0);
        Message_MsgDisp("主人公", "It seems like it would take a\nlifetime.");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0305000_E04000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Right...\nIt would be nice if I could do it\nsomeday, though...\nIt really does seem like it would\ntake a lifetime...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Chris＊＊｝...)");
        Parameter_InCh1Param(5, 528, 33);
        break ;
        case 7:
        Message_Who(0);
        Message_MsgDisp("主人公", "What type of girl is your type,\n｛Chris＊＊｝?");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0305000_E04100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "You▼");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nWhat type of girl is your ideal\ntype?");
        Character_BlinkStart(5, 0, (#1), 1);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E04200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "...... I like all girls.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh～. I don't understand that at all.");
        Character_BlinkStart(5, 3, (#1), 1);
        Voice_PlayVoice("F0305000_E04300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "...\nTo tell you the truth, I don't\nunderstand it, either.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_BlinkStart(5, 0, (#1), 1);
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0305000_E04400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "There has never been a girl that I\nhated.");
        Voice_PlayVoice("F0305000_E04500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Although there have been mean girls,\nI thought that as a whole, they were\ncute...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nThat's the kind of conversation we\nhad.)");
        Parameter_InCh1Param(5, 535, 40);
        break ;
        case 8:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of love do you want to\nhave, ｛Chris＊＊｝?");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0305000_E04600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I want it to be lovey-dovey▼");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nWhat about something more specific?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E04700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I can't say things like that～.\nIt's embarrassing!");
        Message_Who(0);
        Message_MsgDisp("主人公", "............");
        Character_BlinkStart(5, 0, (#1), 1);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E04800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... Sorry. Right, I want to elope.");
        Message_Who(0);
        Message_MsgDisp("主人公", "E-Elope?");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0305000_E04900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Throw away just about everything,\nand the two of us living on love...\nDon't you think that's beautiful?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm...\nbut it doesn't really seem\nrealistic.");
        Character_BlinkStart(5, 2, (#1), 1);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0305000_E05000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... Right. Yeah.\nI probably think it's beautiful\nbecause it's unrealistic.");
        Voice_PlayVoice("F0305000_E05100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "You wouldn't be able to live with\njust love...");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nIt's a little romantic, and a little\nrealistic...");
        Parameter_InCh1Param(5, 536, 41);
        break ;
        case 9:
        if (Parameter_GetPl1Param(312) != 5){
            Message_Who(0);
            Message_MsgDisp("主人公", "What is a kiss to you,\n｛Chris＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("F0305000_E05200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "A smooch?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Y-Yeah.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0305000_E05300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "My heart has already decided that\nI'd only want to smooch girls that I\nlove.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Are kisses and smooches...\ndifferent?");
            Character_BlinkStart(5, 0, (#1), 1);
            Voice_PlayVoice("F0305000_E05400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah. Kisses are greetings.\nSmooches are used exclusively on\npeople you like.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Is that so...");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("F0305000_E05500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I like the Japanese word for\n\"smooch\".\nIsn't it cute?");
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder?");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0305000_E05600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "This is bad～.\nEven though it makes such an amazing\nsound...\nWhat a waste.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Hmm, I wonder how they are\ndifferent...)");
            Parameter_InCh1Param(5, 537, 42);
            }
        else {
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of feeling does a kiss\nhave to you, ｛Chris＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0305000_E05700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "If you're talking about kisses...\nBump, kyaa, smooch.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Are you perhaps talking about...?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("F0305000_E05800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "That's the feeling it has to me\nright now.\nThat time, on your forehead...");
            Message_Who(0);
            Message_MsgDisp("主人公", "I-It's fine... Thanks.");
            Character_ChFace(0, 0, 9);
            Voice_PlayVoice("F0305000_E05900", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Eh.\nEven though I was going to do the\nreal thing now...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(\"Real thing\"...\nWhat does he mean by that～?)");
            Parameter_InCh1Param(5, 537, 42);
            }
        break ;
        }
    if (Parameter_GetCh1Param(5, 558) != 1){
        switch (var1){
            case 10:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder why guys usually think\nabout.");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_070_00000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Hmm.\nDon't you think it's better that you\ndon't know?");
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder.");
            Voice_PlayVoice("FD_05_070_00100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah.\nBecause you don't know, you'll want\nto know, and then you'll want to\ntalk to them, right?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_070_00200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "If you had a bit more of a\nmysterious feeling about you,");
            Voice_PlayVoice("FD_05_070_00300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "he might become interested in you.");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_070_00400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Of course, I also think that the way\nyou are now is fine.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I see...)");
            break ;
            case 11:
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of girls do guys like?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_080_00000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "This is the worst question to ask\nme.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh, why?");
            Voice_PlayVoice("FD_05_080_00100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Because every girl is cute to me.");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_080_00200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "See?\nWhat I say can't be used as any sort\nof reference.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I-I see.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Even though he said such a thing\nstraight away, the only thing that\nisn't strange here is\n｛Chris＊＊｝...)");
            break ;
            case 12:
            Message_Who(0);
            Message_MsgDisp("主人公", "At what kind of times does a guy's\nheart beat faster because of\nsomething a girl does?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_090_00000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "This is a hard question.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Hard?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_090_00100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah. There are too many things.");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_090_00200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Ah, I'll bring a list over to your\nplace next time.\nJust wait a little for it.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I wonder how many things there\ncould be...)");
            break ;
            case 13:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder what I should do in order\nto become feminine.");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_100_00000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I think that it would be good if you\nwere a little more aware.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Aware?");
            Voice_PlayVoice("FD_05_100_00100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Right.\nFor example, when you're sitting\ndown on a chair, keep your knees\ntogether.");
            Voice_PlayVoice("FD_05_100_00200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "When something falls on the the\nground, don't slouch forward to pick\nit up.");
            Voice_PlayVoice("FD_05_100_00300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Instead, crouch over and pick it up.\nAlso, use polite speech...");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_100_00400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Even with such things, you'll be\nreally different.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I see...\nIt's also something that depends on\nyour mental attitude, as well.");
            break ;
            case 14:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder if unrequited love is only\nfull of painful things.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_110_00000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Doesn't it depend on your feelings?");
            Voice_PlayVoice("FD_05_110_00100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Although even just thinking about\nhim may be painful,");
            Voice_PlayVoice("FD_05_110_00200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "you work hard to improve yourself in\norder to get his attention.\nAren't you more forward looking?");
            Voice_PlayVoice("FD_05_110_00300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I think that by having that happen\nover and over again, girls can\nbecome more beautiful.");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_110_00400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "That's why at painful times, you\nshould feel the pain.");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_110_00500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "And at fun times, you should have\nlots of fun!\nRight♪");
            Message_Who(0);
            Message_MsgDisp("主人公", "Haha, that might be true.");
            break ;
            case 16:
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_120_00000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I wonder if we can do it now.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Do it now?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_120_00100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah.\nAt any rate, whenever you want to do\nsomething amazing, I'll be ready.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah, same here... Eh!?");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_120_00200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Hehe, tricked you.");
            Message_Who(0);
            Message_MsgDisp("主人公", "G-Geez, ｛Chris＊＊｝!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ah, that surprised me...)");
            break ;
            case 17:
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_130_00000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "My greeting with you hurt...");
            Voice_PlayVoice("FD_05_130_00100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "It will be bad if you're not more\ngentle when you do it with him.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah.... Ehh!?");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 4);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_130_00200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "\"Ehh\"? Am I wrong?");
            Message_Who(0);
            Message_MsgDisp("主人公", "B-But coincidences like that don't\nusually happen, right?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_130_00300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "That's why you shouldn't have\ncoincidences, and greet people\nproperly.");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_130_00400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "It's just a greeting, so it's fine!\nJust strike, then break away!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Uh, that's absurd,\n｛Chris＊＊｝...)");
            break ;
            case 18:
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_140_00000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "The word \"skinship\" is Japanese.");
            Voice_PlayVoice("FD_05_140_00100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "In English, it's called \"touching\".");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh, is that so!");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_140_00200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah. What is it?\nYou want to touch him?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_140_00300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "If you do, then I'll coach you!\nWith great attention to detail!");
            Message_Who(0);
            Message_MsgDisp("主人公", "G... Great attention to detail!?");
            Character_ChFace(0, 0, 8);
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_140_00400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "...\nYou don't have to be so surprised...\nPfft.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(He's pouting...)");
            break ;
            case 19:
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you think that a friendship\nbetween a man and a woman is\npossible?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_150_00000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah.\nBut I feel like there are more cases\nwhere it isn't possible.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh, why?");
            Voice_PlayVoice("FD_05_150_00100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Peoples' hearts don't have a shape,\nright?");
            Voice_PlayVoice("FD_05_150_00200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I think that not even God knows how\ntheir hearts will change.");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_150_00300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Of course, there are times when it\ndoesn't change either.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_150_00400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Figuring out what is different and\nwhat is the same is quite difficult,\nisn't it?");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Hmm, that certainly may be true.)");
            break ;
            }
        }
    else {
        switch (var1){
            case 10:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder what I should do in order\nto make a guy happy.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_070_00500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "There's obviously only one answer,\nright?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Just one?");
            Voice_PlayVoice("FD_05_070_00600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah.\nMake the person you like happy.");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_070_00700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "...\nThat's why you're doing your best,\nisn't it?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh... That's...");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_070_00800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Right?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Y-Yeah...");
            break ;
            case 11:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder what I can do to become the\ngirl that the other person likes.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_080_00300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "First of all, it would be to\nunderstand the other person well,\nright?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_080_00400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "...\nBut changing yourself entirely is\nbad.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh, why?");
            Voice_PlayVoice("FD_05_080_00500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "It's impossible, right?\nThat will fall apart one day.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_080_00600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "...\nWhen that happens, the one who will\nend up getting hurt is you.\nI can't stand that.");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_080_00700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "That's why if you are going to suit\nhim, only do it with your clothes or\nhobbies.\nOkay?");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Chris＊＊｝...?)");
            break ;
            case 12:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder what you can do in order to\nclamp down this heart throbbing.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_090_00300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Wouldn't it be fine if you didn't\ntry to force it?");
            Message_Who(0);
            Message_MsgDisp("主人公", "But I think \"What if he hears it\"...");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_090_00400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "It'll be fine, even if it's heard.\nI mean, that's love, isn't it?");
            Message_Who(0);
            Message_MsgDisp("主人公", "I see...");
            Voice_PlayVoice("FD_05_090_00500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "But I would want them to hear it.");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_090_00600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "...\nHow much is my heart throbbing now?");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Chris＊＊｝...?)");
            break ;
            case 13:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder what I should do in order\nto become more feminine.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_100_00500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "You're feminine enough.... Right.\nYou haven't seen yourself in the\nmirror.");
            Voice_PlayVoice("FD_05_100_00600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "When you talk about him, your face\nis really feminine.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh! R-Really?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_100_00700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah. I think it's cute.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_100_00800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "So cute that I don't want anyone\nelse to see.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Chris＊＊｝?");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_100_00900", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah, you are fine the way you are.\nThere is nothing to worry about.");
            break ;
            case 14:
            Message_Who(0);
            Message_MsgDisp("主人公", "I want to quickly get out of this\nsituation of unrequited love...");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_110_00600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah.\nIf you do, then my feelings will\nalso...");
            Character_ChFace(0, 0, 9);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_110_00700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", ".........");
            Character_ChFace(0, 3, 3);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_110_00800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "-- As if they could ever become\nlight feelings.");
            Voice_PlayVoice("FD_05_110_00900", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "No matter what the result is, this\npain won't change...");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Chris＊＊｝?");
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_110_01000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Ah, sorry.\nI was just talking to myself.\nDon't worry about it, okay?");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Chris＊＊｝...)");
            break ;
            case 16:
            Message_Who(0);
            Message_MsgDisp("主人公", "Are you in love now,\n｛Chris＊＊｝?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_120_00300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... Maybe I am?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Is that so! How is it?\nDoes it seem like it will be a\nwonderful kind of love?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_120_00400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... With your permission.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh...?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_120_00500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Ahaha, just kidding!\nIt's going perfect, so don't worry.");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_120_00600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Anyway, what about you?\nCome on, tell me.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Chris＊＊｝...)");
            break ;
            case 17:
            Message_Who(0);
            Message_MsgDisp("主人公", "What do you think about that kiss,\n｛Chris＊＊｝?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_130_00500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... If I had done it to you...\nit would probably be more of a\nsmooch.");
            Message_Who(0);
            Message_MsgDisp("主人公", "A smooch...");
            Character_ChFace(0, 0, 11);
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_130_00600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Ah! Uhh... yeah.");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_130_00700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "See, it was on the forehead.\nThat's why you shouldn't worry about\nit.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Y-Yeah...");
            break ;
            case 18:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder if skinship is necessary.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(5, 0, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_140_00500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I think that if you did it, the\ndistance between you and him would\nsurely narrow...");
            Message_Who(0);
            Message_MsgDisp("主人公", "I see. So...");
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_140_00600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "But whether it's necessary or not is\nsomething you should decide, right?");
            Voice_PlayVoice("FD_05_140_00700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "...\nI won't say that I don't want you to\ndo it.");
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_140_00800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I can't encourage you or stop you...\nI'm so pathetic.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Chris＊＊｝...?)");
            break ;
            case 19:
            Message_Who(0);
            Message_MsgDisp("主人公", "So friendship between men and women\nare possible, after all.");
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_150_00500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Hmm... right.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... ｛Chris＊＊｝?\nWhat's the matter?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(5, 2, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_150_00600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "...\nI didn't think that the things I\nsaid would come back and haunt me\nlike this.");
            Voice_PlayVoice("FD_05_150_00700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "It might be more tiresome keeping\nthings the way they are now...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh... What do you mean by...");
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(5, 3, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_05_150_00800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... Yeah, it's fine. I can do it.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Chris＊＊｝...?)");
            break ;
            }
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Music_StopBGM(0, 40);
    }
