section "f03_m7_000"{
    Character_BlinkStart(7, 1, (#1), 1);
    Character_BlinkStart(7, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(7, "M7_17F", 0);
    Background_Bg_GS2("BG_SC002_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝.\nI have a question.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(7, 2, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("B0707000_G00000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I like being questioned.\nGo ahead and ask me anything.");
    Message_Sele_Kitaku_Kaiwa();
    int var1 = Parameter_Kitaku_Kaiwa(0);
    switch (var1){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of television shows do you\nusually watch,\n｛Wakaouji＊＊｝?");
        Character_ChFace(0, 0, 3);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G00100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Baseball night matches and variety\nshows.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh... Do you like baseball?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("B0707000_G00200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That is not the case.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...?");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G00300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I don't have a TV, so I always watch\nit at the restaurant.\nThe owner chooses the channel.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I feel like I can picture that kind\nof scene...)");
        Parameter_InCh1Param(7, 530, 35);
        break ;
        case 1:
        Message_Who(0);
        Message_MsgDisp("主人公", "What foods do you like,\n｛Wakaouji＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("B0707000_G00400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Foods I like...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, you don't have to think about\nit too deeply.\nI mean things that you usually eat.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G00500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Ah... It would be meals with rice.\nI mix it with canned tuna and eat\nit.\nIt is nice.");
        Message_Who(0);
        Message_MsgDisp("主人公", "So you mean... like a cat?");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(7, 2, (#1), 1);
        Voice_PlayVoice("B0707000_G00600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "\"Like a cat\"... What a good term.\nI will be using this term from now\non.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(So he didn't know the term \"like a\ncat\".)");
        Parameter_InCh1Param(7, 531, 36);
        break ;
        case 2:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you like sports,\n｛Wakaouji＊＊｝?");
        Character_ChFace(0, 0, 6);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("B0707000_G00700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I do.\nI do not do sports that have a lot\nof people playing.\nFor some reason, it makes me\nmentally drained.");
        Message_Who(0);
        Message_MsgDisp("主人公", "So then you play sports by yourself.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(7, 2, (#1), 1);
        Voice_PlayVoice("B0707000_G00800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "When I lived in America, I played\ntennis all the time.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Really!?\nYou don't play tennis anymore?");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("B0707000_G00900", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I do not. It is tiring.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(... So he hates sports.)");
        Parameter_InCh1Param(7, 532, 37);
        break ;
        case 3:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you listen to music,\n｛Wakaouji＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G01000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I do. I love music.\nI especially like hit songs from the\n60s and 70s.");
        Message_Who(0);
        Message_MsgDisp("主人公", "So does that mean you have a lot of\nthose kind of CDs?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("B0707000_G01100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I don't own CDs.\nAt my house--");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, you don't own a CD player...");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("B0707000_G01200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Correct. But I have a radio.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("B0707000_G01300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I cannot do anything about it when\nthe music program I like is not on,\nso I sing....\nAh, should I sing?");
        Message_Who(0);
        Message_MsgDisp("主人公", "No, you don't have to do that now.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(But ｛Wakaouji＊＊｝\nsinging...\nI kind of want to hear it.)");
        Parameter_InCh1Param(7, 533, 38);
        break ;
        case 4:
        Message_Who(0);
        Message_MsgDisp("主人公", "What are your hobbies,\n｛Wakaouji＊＊｝?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("B0707000_G01400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "If I had to say, being a teacher.\nIt is actually fun.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You're a teacher because it's your\nhobby!?");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(7, 2, (#1), 1);
        Voice_PlayVoice("B0707000_G01500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Yes.\nBeing a teacher is my occupation.");
        Message_Who(0);
        Message_MsgDisp("主人公", ".........");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G01600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "But talking like this with you\nstudents is really fun.\nEveryone is open...");
        Character_ChFace(0, 0, 3);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G01700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "There are many things to learn.\nA succession of discoveries.\nWhen I am in contact with you guys,\nI regain lost time.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Lost time?\n｛Wakaouji＊＊｝, that--");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G01800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Ah, yes, one of my hobbies is\ngetting fleas off of cats.\nI'm really into it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nDid you also learn that from\nstudents?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(But \"lost time\"...?)");
        Parameter_InCh1Param(7, 529, 34);
        break ;
        case 5:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of student were you during\nyour student days,\n｛Wakaouji＊＊｝?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("B0707000_G01900", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "My student days...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, you don't have to think about\nit too deeply!\nLike were you in a club or\nstudying...");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G02000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I have never been in a club.\nAs for studying, no.\nInstead, I was pursuing research.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G02100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I did not have a student period\nsimilar to what you students have.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(7, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G02200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", ".........\nI will tell you about it some other\ntime.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝...)");
        Parameter_InCh1Param(7, 534, 39);
        break ;
        case 6:
        Message_Who(0);
        Message_MsgDisp("主人公", "What was your future dream when you\nwere a child, ｛Wakaouji＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G02300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I wanted to own a cat.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Were you not allowed to have pets at\nhome?");
        Character_ChFace(0, 0, 3);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G02400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Well, something like that.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G02500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "When I was younger, I once had the\nexperience of holding a cat.\nI could never forget it.");
        Character_ChFace(0, 0, 3);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G02600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That's why I decided that when I\nlive by myself, I would own as much\ncats as I want.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Then you worked hard to fulfill your\ndream!");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G02700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "...\nI own too many, so I'm a little\ntroubled now.\nThey start bringing their friends\nalong...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(That sounds like\n｛Wakaouji＊＊｝.)");
        Parameter_InCh1Param(7, 528, 33);
        break ;
        case 7:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of feeling does your\nfavorite type have,\n｛Wakaouji＊＊｝?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G02800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "My favorite type...\nAh, you're talking about my favorite\ntype of girl.\nAm I correct?");
        Message_Who(0);
        Message_MsgDisp("主人公", "W-Well... That kind of thing.");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("B0707000_G02900", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "... I do not know.\nCompared to everyone else, they have\nmore of a sense of liking someone\n...\nI do not.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G03000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Ah, I do have one.\nA person who likes cats would be\nnice.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I see.\nIt's because you love cats, don't\nyou, ｛Wakaouji＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G03100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Or, I am a cat.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... What?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G03200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "It was a joke.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I know that....\nBut saying that he doesn't like\nanyone, isn't that lonesome...?)");
        Parameter_InCh1Param(7, 535, 40);
        break ;
        case 8:
        Message_Who(0);
        Message_MsgDisp("主人公", "In what kind of way do you think\nabout love, ｛Wakaouji＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("B0707000_G03300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Simply put, it is an effect due to\nintracranial chemicals.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That's quite blunt...");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("B0707000_G03400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That is not the case.");
        Voice_PlayVoice("B0707000_G03500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "For an individual to prefer another\nis a phenomenon only seen in the\nnatural world between mother and\nchild.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh? Uhh...");
        Character_ChFace(0, 0, 3);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G03600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Example, when people see the good\nwill of the opposite sex, their\npupils enlarge.\nThe other person seems like they are\nshining.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so...");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G03700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Desires of living things make them\nlose their judgement, and that\nweakness makes them feel like they\nare in love.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G03800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Why do people say things like \"Isn't\nthis romantic\"?");
        Message_Who(0);
        Message_MsgDisp("主人公", "You're right...");
        Character_ChFace(0, 0, 3);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("", 7, "B0707000_G03900");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That's why you should love,\n｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "What!?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("B0707000_G04000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "When you have found someone.");
        Message_Who(0);
        Message_MsgDisp("主人公", "............");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Somehow, in the end, he confused\nme...)");
        Parameter_InCh1Param(7, 536, 41);
        break ;
        case 9:
        if (Parameter_GetPl1Param(312) != 7){
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, umm...\nI wanted to ask you about kisses...");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(7, 3, (#1), 1);
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("B0707000_G04100", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Kisses... Kisses, is it....\nIn other words--");
            Character_ChFace(0, 0, 3);
            Character_BlinkStart(7, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0707000_G04200", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "You want to kiss me. Am I correct?");
            Message_Who(0);
            Message_MsgDisp("主人公", "W-Wrong...!\nUmm, I wanted to ask about how you\nthink about them and such.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(7, 3, (#1), 1);
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("B0707000_G04300", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Ah, I see. Well...");
            Character_ChFace(0, 0, 3);
            Character_BlinkStart(7, 2, (#1), 1);
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("B0707000_G04400", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "It differs in each cultural sphere.\nAlthough people think differently, I\nthink that it is important, after\nall.");
            Character_ChFace(0, 0, 3);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0707000_G04500", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "What is especially important is that\nyour first kiss is with someone you\nreally like.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(7, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0707000_G04600", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "I mean, there is no one who wouldn't\nfeel happy about that, correct?");
            Message_Who(0);
            Message_MsgDisp("主人公", "(A first kiss with someone you\nreally like, huh...)");
            Parameter_InCh1Param(7, 537, 42);
            }
        else {
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, um...\nI wanted to ask you about kisses...");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(7, 2, (#1), 1);
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("B0707000_G04700", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Kisses, was it...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes.");
            Character_ChFace(0, 0, 3);
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("B0707000_G04800", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Kisses... Not kissing fish, right?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Enough already,\n｛Wakaouji＊＊｝!");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("B0707000_G04900", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "If you are talking about that thing\nin the chemistry room, that was just\nan accident.");
            Message_Who(0);
            Message_MsgDisp("主人公", "............");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(7, 2, (#1), 1);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("B0707000_G05000", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "But if it were not for that, I feel\nlike I would not be my current self.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("B0707000_G05100", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Will you be responsible for it?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Geez!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(So ｛Wakaouji＊＊｝ remembers\nit, after all...)");
            Parameter_InCh1Param(7, 537, 42);
            }
        break ;
        }
    if (Parameter_GetCh1Param(7, 556) != 0){
        if (Parameter_GetCh1Param(7, 558) != 1){
            switch (var1){
                case 10:
                Message_Who(0);
                Message_MsgDisp("主人公", "I don't know about guys.\nI wonder what they are thinking\nabout...");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_070_00000", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Really?");
                Message_Who(0);
                Message_MsgDisp("主人公", "???");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_070_00100", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "You're anxious because you do not\nknow their feelings.\nIs it related to gender?\nIs it okay to stop them from\nthinking?");
                Message_Who(0);
                Message_MsgDisp("主人公", ".........");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_070_00200", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "What is important is that we realize\nwe are all different.\nAlso, think of others nicely, more\nthan you do about yourself.");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_070_00300", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "It will be all right.\nI do not know anything about men or\nwomen.\nHahaha...");
                Message_Who(0);
                Message_MsgDisp("主人公", "(Nicer to others more than you're\nnice to yourself...)");
                break ;
                case 11:
                Message_Who(0);
                Message_MsgDisp("主人公", "What kind of girls are loved by\nguys?");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_080_00000", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "It is different for each person, so\nany.\nI can talk about it, biologically.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Then, biologically speaking?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_080_00100", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Biologically speaking, huh?\nWell, uhh...\nAs expected, I cannot say it.");
                Message_Who(0);
                Message_MsgDisp("主人公", "?");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_080_00200", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "It's dangerous, really dangerous...\nIf I say it, I will become a teacher\nwho has committed sexual harassment.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(?)");
                break ;
                case 12:
                Message_Who(0);
                Message_MsgDisp("主人公", "At what kind of time does guys'\nhearts beat faster?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_090_00000", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "If you are trying to make his heart\nthrob, then of course it is the\neyes.");
                Message_Who(0);
                Message_MsgDisp("主人公", "The eyes?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_090_00100", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "In the world of living things, eyes\ncontact will create an emergency.");
                Voice_PlayVoice("FD_07_090_00200", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "You will either do it or you will\nhave it done to you.\nThat is why your heart rate\nincreases when there is eye contact.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Is that so...");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_090_00300", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "So it is the eyes.\nLet's aim for the eyes.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(And how exactly do I do that...?)");
                break ;
                case 13:
                Message_Who(0);
                Message_MsgDisp("主人公", "I wonder if I should be more\nfeminine...");
                Character_ChFace(0, 2, 4);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 4);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_100_00000", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Feminine...\nIn other words, you mean things like\ncooking, sewing, and the way you\ntalk?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Yes, those kind of things.");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_100_00100", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Wanting to become more feminine for\nhis sake is feminine enough.");
                Message_Who(0);
                Message_MsgDisp("主人公", "I wonder...");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_100_00200", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Yes.\nJust then, you made a really girly\nface.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(I'm kind of embarrassed...)");
                break ;
                case 14:
                Message_Who(0);
                Message_MsgDisp("主人公", "What do you think about unrequited\nlove?");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_110_00000", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Yeah...\nActually, I have not experienced\nunrequited love before.\nThat is why this is just my\nimagination.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Okay.");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_110_00100", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Since the ancient times, countless\nsongs or literature talk about this\npain, and made people around the\nworld shed tears.");
                Voice_PlayVoice("FD_07_110_00200", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Surely, people who experience\nunrequited love experience one of\nthe most extremely painful things.");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_110_00300", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "If I did experience it, my heart\nwould have to deal with it, even\nthough it is painful.\nThat is what I think.");
                Voice_PlayVoice("FD_07_110_00400", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Do your best. I will be with you.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝...)");
                break ;
                case 16:
                Message_Who(0);
                Message_MsgDisp("主人公", "｛Wakaouji＊＊｝.\nAre you in love?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_120_00000", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Work is my lover.");
                Message_Who(0);
                Message_MsgDisp("主人公", "What?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_120_00100", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "My lover is education.\nThat is why I cannot think about\nanything but work right now.");
                Message_Who(0);
                Message_MsgDisp("主人公", "I-is that so?");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_120_00200", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "There is no way that would not be\nthe case while being a teacher.\n*Sigh*...");
                Message_Who(0);
                Message_MsgDisp("主人公", "(It seems kind of tough...)");
                break ;
                case 17:
                Message_Who(0);
                Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, what do you\nthink about kisses?\nUmm, I'm not talking about kissing\nfish.");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_130_00000", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "You read my mind...");
                Message_Who(0);
                Message_MsgDisp("主人公", "(.........)");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_130_00100", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "If you are worried about what\nhappened in the chemistry room,\nthere is no need to.");
                Voice_PlayVoice("FD_07_130_00200", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "You will one day do it with the\nperson you love...\nThat will be a real kiss.");
                Message_Who(0);
                Message_MsgDisp("主人公", "... Yes.");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_130_00300", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "So, have you done it? As I thought.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(.........)");
                break ;
                case 18:
                Message_Who(0);
                Message_MsgDisp("主人公", "What do you think about skinship?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_140_00000", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "It is important.\nIt is appropriate with mammals.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Mammals?");
                Voice_PlayVoice("FD_07_140_00100", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "It increases feelings of solidarity\nand belonging.\nIt also seems to regulate hormonal\nbalance.\nPlease do it a lot.");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_140_00200", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Is what I want to say, but...\nEven though adolescent boys are\nmammals, they are also wild\nanimals...\nOkay?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Y-Yes...");
                Voice_PlayVoice("FD_07_140_00300", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "What is important is a trustworthy\nperson that will not hurt you.\nDo you understand?");
                Message_Who(0);
                Message_MsgDisp("主人公", "(I should be careful...)");
                break ;
                case 19:
                Message_Who(0);
                Message_MsgDisp("主人公", "Do you think that friendship between\nmen and women exists?");
                Character_ChFace(0, 2, 4);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 4);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_150_00000", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Wah!");
                Message_Who(0);
                Message_MsgDisp("主人公", "What!?");
                Voice_PlayVoice("FD_07_150_00100", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Nothing, I just think that youths\nare too radiant.\nIt blinded my eyes.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Geez, ｛Wakaouji＊＊｝!");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_150_00200", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "It is okay, it exists.\nIt is just like the relation between\nteacher and student.\nIsn't that right?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Huh...");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_150_00300", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Huh? What?");
                break ;
                }
            }
        else {
            switch (var1){
                case 10:
                Message_Who(0);
                Message_MsgDisp("主人公", "I don't know about guys.\nI wonder what they think about...");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_070_00400", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "What if you tried questioning why\nyou don't understand?");
                Message_Who(0);
                Message_MsgDisp("主人公", "But that's...");
                Voice_PlayVoice("FD_07_070_00500", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "If you can make a guess, then that\nwould be the best.\nBut there are times where you must\nuse words.");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(7, 2, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_070_00600", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "That is just my conclusion...\nthough.\nIt is a bother to put this\nconclusion into practice.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝?)");
                break ;
                case 11:
                Message_Who(0);
                Message_MsgDisp("主人公", "What kind of girls are loved by\nguys?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_080_00300", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "I see...\nSimply put, what they love is their\nappearance, after all.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Is that how it is after all? Hmm～...");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_080_00400", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "But it cannot be helped.\nLove that has no connection to\nfeelings of love will hurt those\nwith a heart.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Love that has no connection to\nfeelings of love...");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_080_00500", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "That is why if he is attracted to\nyour appearance...");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(7, 2, (#1), 1);
                Character_ChFace(0, 3, 1);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_080_00600", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "I will do an extremely unfavorable\nthing.\nSurely.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝...)");
                break ;
                case 12:
                Message_Who(0);
                Message_MsgDisp("主人公", "At what times do guys' hearts beat\nfaster?");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_090_00400", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "When they look at the eyes.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Huh?");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_090_00500", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "You want to make his heart throb.\nAm I correct?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Umm...");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_090_00600", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Looking at your eyes, their heart\nrate will increase, and their heart\nwill throb.\nSo look straight into their eyes.");
                Message_Who(0);
                Message_MsgDisp("主人公", "I wonder if that will work with\nme...");
                Voice_PlayVoice("FD_07_090_00700", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "You will be fine.\nIt was already proven a long time\nago.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(...?)");
                break ;
                case 13:
                Message_Who(0);
                Message_MsgDisp("主人公", "I wonder if I should be more\nfeminine.");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_100_00300", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Just now, you made a really feminine\nface.");
                Message_Who(0);
                Message_MsgDisp("主人公", "A feminine face?");
                Voice_PlayVoice("FD_07_100_00400", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "The \"I want to do something for him\"\nface.\nIt was really feminine.\nIt is beautiful.");
                Message_Who(0);
                Message_MsgDisp("主人公", "There's no way...");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 2, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_100_00500", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "It is true. I felt it.\nI felt it so much that I had a few\nguilty feelings when I saw it, and\nnot him.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(I'm kind of embarrassed...)");
                break ;
                case 14:
                Message_Who(0);
                Message_MsgDisp("主人公", "Unrequited love is painful...");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(7, 2, (#1), 1);
                Character_ChFace(0, 3, 1);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_110_00500", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Unrequited love... I see.");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 1);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_110_00600", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "If it were the former me, I think I\nwould have done something to\nencourage you.\nBut I cannot do that now.");
                Voice_PlayVoice("FD_07_110_00700", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "I do not have any words for you, the\none who is feeling pain.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Sorry...\nAs expected, I should take care of\nmy own--");
                Voice_PlayVoice("FD_07_110_00800", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "No... No, that is not it.\nIt is just that I...\nI really don't know myself.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(I wonder if ｛Wakaouji＊＊｝\nis worried about something...)");
                break ;
                case 16:
                Message_Who(0);
                Message_MsgDisp("主人公", "｛Wakaouji＊＊｝.\nAre you in love?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 2, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_120_00300", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "I might be...");
                Message_Who(0);
                Message_MsgDisp("主人公", "(Then, maybe...)");
                Character_ChFace(0, 2, 4);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 4);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_120_00400", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "So, how was my answer?\nIt was mysterious, right?\nI can use it to answer many\nquestions.");
                Message_Who(0);
                Message_MsgDisp("主人公", "......");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_120_00500", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Sorry. But... I really do not know.\nI do not know what love itself is.");
                Voice_PlayVoice("FD_07_120_00600", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "I think that it requires time from\nwhen you fall in love to when you\nrealize it.\nEspecially in my case.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(Then is ｛Wakaouji＊＊｝\nreally in love...?)");
                break ;
                case 17:
                Message_Who(0);
                Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, what do you\nthink about kisses?\nUm, I don't mean kissing fish.");
                Character_ChFace(0, 2, 2);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 2);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_130_00400", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "You read my mind...");
                Message_Who(0);
                Message_MsgDisp("主人公", "(.........)");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_130_00500", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "If you are worried about what\nhappened in the chemistry room,\nthere is no need to be.");
                Message_Who(0);
                Message_MsgDisp("主人公", "... Okay.");
                Voice_PlayVoice("FD_07_130_00600", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "There is no need to think about\nthings like \"I should\" and such.\nWhen the right time comes, you'll\nknow.");
                Message_Who(0);
                Message_MsgDisp("主人公", "The right time?");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_130_00700", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "When you are by their side, looking\nat them, when you want to just\nnaturally do it.\nEven I know that.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝...)");
                break ;
                case 18:
                Message_Who(0);
                Message_MsgDisp("主人公", "What do you think about skinship?");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(7, 2, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_140_00400", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "This is difficult.\nEven though it is a very natural\nthing.");
                Message_Who(0);
                Message_MsgDisp("主人公", "... Yes.");
                Character_ChFace(0, 2, 0);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 0);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_140_00500", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Truthfully, everyone wants to touch\nthe one they love and wants to be\ntouched.");
                Voice_PlayVoice("FD_07_140_00600", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "But in actuality, when you do touch,\nyou can't calm down, and you get\nanxious.");
                Voice_PlayVoice("FD_07_140_00700", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "It surely is scary.\nBecause you communicate more things\nthan you can with words.");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(7, 2, (#1), 1);
                Character_ChFace(0, 3, 1);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_140_00800", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Especially if you are lying.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(... Lying?)");
                break ;
                case 19:
                Message_Who(0);
                Message_MsgDisp("主人公", "Do you think that friendship between\nmen and women exists?");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_150_00400", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Of course.\nBecause things like trust and\nfriendship are not gender specific.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Hmm～...");
                Character_ChFace(0, 2, 3);
                Character_BlinkStart(7, 3, (#1), 1);
                Character_ChFace(0, 3, 3);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_150_00500", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Yes, I think that there are also\npeople who cannot understand that.");
                Character_ChFace(0, 2, 5);
                Character_BlinkStart(7, 0, (#1), 1);
                Character_ChFace(0, 3, 5);
                Character_ChFace(0, 4, 1);
                Voice_PlayVoice("FD_07_150_00600", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "The problem is, there are some\npeople that have stronger feelings\nthan friendship.");
                Voice_PlayVoice("FD_07_150_00700", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "Once those feelings are born, it is\nas if they are another living thing.\nThey do what they want.");
                Character_ChFace(0, 2, 1);
                Character_BlinkStart(7, 2, (#1), 1);
                Character_ChFace(0, 3, 1);
                Character_ChFace(0, 4, 0);
                Voice_PlayVoice("FD_07_150_00800", #1, "");
                Message_Who(7);
                Message_MsgDisp("Wakaouji", "What a parasite.");
                Message_Who(0);
                Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝...)");
                break ;
                }
            }
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
