section "f03_g1_000"{
    Character_BlinkStart(10, 1, (#1), 1);
    Character_BlinkStart(10, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(10, "G1_03F", 0);
    Background_Bg_GS2("BG_EX000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGB_062_000", 127, 40);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hey, ｛Toudou＊＊｝.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("F0310000_J00000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... What is it?");
    Message_Sele_Kitaku_Kaiwa();
    int var1 = Parameter_Kitaku_Kaiwa(0);
    switch (var1){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of TV shows do you like,\n｛Toudou＊＊｝?");
        Voice_PlayVoice("F0310000_J00100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Dramas, and stuff.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Like the dramas that are currently\npopular?");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0310000_J00200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I do watch popular dramas, but I\nalso watch repeats.\nLike period dramas and stuff.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, is that so.");
        Character_BlinkStart(10, 0, (#1), 1);
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0310000_J00300", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I often feel refreshed when I watch\nperiod dramas.\nThe feeling of rewarding the good\nand punishing the evil is nice.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Perhaps ｛Toudou＊＊｝ has\nan unexpectedly strong sense of\njustice?)");
        Parameter_InCh1Param(10, 530, 35);
        break ;
        case 1:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have favorite foods and\nstuff, ｛Toudou＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0310000_J00400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Favorite foods, huh...");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0310000_J00500", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Dried squid, nuts, dried\ncuttlefish...");
        Message_Who(0);
        Message_MsgDisp("主人公", "... That's...");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0310000_J00600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Also, dried fruits.\nThey're good for you as long as you\ndon't eat too much.\nIt's good for your skin, so I\nrecommend them.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It somewhat feels like those foods\nare what people drinking alcohol\nwould choose to eat...)");
        Parameter_InCh1Param(10, 531, 36);
        break ;
        case 2:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have any favorite sports,\n｛Toudou＊＊｝?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0310000_J00700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I'm good at all sports, but lately,\nI prefer watching them instead.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, for example?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0310000_J00800", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "...\nRecently, it has been baseball...\nand stuff.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Really?\nIs there are a player that you're\ninterested in?");
        Character_BlinkStart(10, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0310000_J00900", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Maybe.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I wonder which player...\nI'm curious.)");
        Parameter_InCh1Param(10, 532, 37);
        break ;
        case 3:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of music do you like,\n｛Toudou＊＊｝?");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0310000_J01000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Even though I hate popular music, I\nremember it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Why?");
        Character_BlinkStart(10, 0, (#1), 1);
        Voice_PlayVoice("F0310000_J01100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "It often plays at work, so I just\nnaturally remember it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, is that so?\nIsn't it great to be working at that\nkind of place?");
        Character_ChFace(0, 2, 1);
        Voice_PlayVoice("F0310000_J01200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Not really.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so?");
        Character_ChFace(0, 2, 2);
        Voice_PlayVoice("F0310000_J01300", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "...\nWithout realizing it, I start\nsinging the songs of those showy\nidols.");
        Character_BlinkStart(10, 3, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0310000_J01400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Even when I'm taking a bath...\n*Sigh*. It's unbelievable...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Toudou＊＊｝'s humming,\nhuh...\nI kind of want to hear it.)");
        Parameter_InCh1Param(10, 533, 38);
        break ;
        case 4:
        Message_Who(0);
        Message_MsgDisp("主人公", "What are your hobbies,\n｛Toudou＊＊｝?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0310000_J01500", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Nail art.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, that's a surprise!");
        Character_BlinkStart(10, 2, (#1), 1);
        Voice_PlayVoice("F0310000_J01600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "But since I'm working part-time, I\ncan't really do it on my own nails.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I see...");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F0310000_J01700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "And pilates.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Pilates?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0310000_J01800", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Yeah. It's a type of exercise.\nIt trains the most inner muscles of\nyour body and gives you better\nbalance.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0310000_J01900", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "If you don't get enough exercise,\nyour body will become weak.\nAlso, come the time, if you don't\nhave any strength...");
        Message_Who(0);
        Message_MsgDisp("主人公", "... \"The time\"?");
        Character_ChFace(0, 2, 1);
        Voice_PlayVoice("F0310000_J02000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "When you're troubled, right?\nWith something.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I wonder what time she's talking\nabout～!)");
        Parameter_InCh1Param(10, 529, 34);
        break ;
        case 5:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of kid were you in middle\nschool, ｛Toudou＊＊｝?");
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0310000_J02100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Just like the way I am now.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, then what about in elementary\nschool?");
        Character_BlinkStart(10, 0, (#1), 1);
        Voice_PlayVoice("F0310000_J02200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Well... just like the way I am now.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You've been composed ever since you\nwere in elementary school?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0310000_J02300", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Oh, in elementary school, I was\nmistaken for a high school student\nand had a dispute at the station\nticket gates.");
        Character_BlinkStart(10, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0310000_J02400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Since I was like this, the backpack\ndidn't suit me at all.\nIt's funny.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm, well it surely wouldn't suit\nyou.)");
        Parameter_InCh1Param(10, 534, 39);
        break ;
        case 6:
        Message_Who(0);
        Message_MsgDisp("主人公", "Have you decided on what you want to\nbe in the future,\n｛Toudou＊＊｝?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0310000_J02500", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I'd like to become a nail artist,\nand own my own store.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh... what an amazing dream.");
        Character_BlinkStart(10, 2, (#1), 1);
        Voice_PlayVoice("F0310000_J02600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "But I need the effort of other\npeople in order to realize that\ndream.");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0310000_J02700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Even so, I am fired up about it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Maybe I should be your first\ncustomer?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0310000_J02800", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Ah, I'll invite you. It's a promise.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Thanks! I look forward to it!");
        Parameter_InCh1Param(10, 528, 33);
        break ;
        case 7:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of guy do you like,\n｛Toudou＊＊｝?");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 2);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0310000_J02900", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "W-What's with you all of a sudden?");
        Message_Who(0);
        Message_MsgDisp("主人公", "\"What's with you\"...\nI was just a little curious...");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(10, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("F0310000_J03000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Right...\nA person who, no matter how many\nsetbacks there are, will crawl to\nthe top with their own strength.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(10, 2, (#1), 1);
        Voice_PlayVoice("F0310000_J03100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "...\nI probably won't be able to take my\neyes off such a guy.");
        Character_BlinkStart(10, 0, (#1), 1);
        Character_ChFace(0, 2, 0);
        Voice_PlayVoice("F0310000_J03200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "When I see them struggling, from the\nbottom of my heart, I want to save\nthem.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have an idea of who that kind\nof person is?");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(10, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0310000_J03300", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Well. I wonder.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I'm curious...)");
        Parameter_InCh1Param(10, 535, 40);
        break ;
        case 8:
        Message_Who(0);
        Message_MsgDisp("主人公", "Hey, ｛Toudou＊＊｝.\nWhat kind of love do you want to\nhave?");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 2);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0310000_J03400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "What's with you all of a sudden...");
        Message_Who(0);
        Message_MsgDisp("主人公", "But what if you met someone that you\nlike?");
        Character_ChFace(0, 0, 3);
        Character_BlinkStart(10, 3, (#1), 1);
        Voice_PlayVoice("F0310000_J03500", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "...\nI'd devote myself to the man I fell\nin love with.\nSurely...");
        Message_Who(0);
        Message_MsgDisp("主人公", "So you'd devote yourself!");
        Character_BlinkStart(10, 0, (#1), 1);
        Voice_PlayVoice("F0310000_J03600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "...\nI don't have a kind of love that I\nwant to have.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0310000_J03700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "If the guy that I fall in love with\nfalls in love with me, then that's\nenough.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0310000_J03800", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "But it might be hard to reach that\nstage...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Toudou＊＊｝ is quite\ntraditional...)");
        Parameter_InCh1Param(10, 536, 41);
        break ;
        case 9:
        Message_Who(0);
        Message_MsgDisp("主人公", "Hey, ｛Toudou＊＊｝.\nWhat do you imagine a kiss to be\nlike?");
        Voice_PlayVoice("F0310000_J03900", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Kiss...");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0310000_J04000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "......... Huh?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Uhh, I was wondering what you feel\nabout kisses.");
        Character_ChFace(0, 7, 0);
        Character_BlinkStart(10, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0310000_J04100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Even you ask stupid things.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Uh... I was a little curious...");
        Character_BlinkStart(10, 0, (#1), 1);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0310000_J04200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Isn't it a sacred thing?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_BlinkStart(10, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0310000_J04300", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "That's why you can't treat it so\nsimply...\nI think...");
        Character_ChFace(0, 0, 8);
        Character_BlinkStart(10, 2, (#1), 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0310000_J04400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Look at what you made me say.\nArgh, this is so embarrassing...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Toudou＊＊｝ is extremely\nembarrassed...\nIt's kind of a fresh feeling.)");
        Parameter_InCh1Param(10, 537, 42);
        break ;
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Music_StopBGM(0, 40);
    Screen_ClearScreen();
    }
