section "f03_m3_000"{
    Character_BlinkStart(3, 1, (#1), 1);
    Character_BlinkStart(3, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(3, "M3_03F", 0);
    Background_Bg_GS2("BG_EX000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGB_062_000", 127, 40);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "...\nBy the way, ｛Hikami＊＊｝.");
    Voice_PlayVoice("F0303000_C00000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "What is it?");
    Message_Sele_Kitaku_Kaiwa();
    int var1 = Parameter_Kitaku_Kaiwa(0);
    switch (var1){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have a favorite TV Show,\n｛Hikami＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0303000_C00100", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I do. \"Science Project\".");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, is that the rigid educational\nshow where many scientists talk\nabout research?");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(3, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0303000_C00200", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Rigid?\nIt's a serious and good program.\nIt's dramatic in the fact that even\nthe smallest problems are linked to\nthe great discoveries.");
        Voice_PlayVoice("F0303000_C00300", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "The solid conviction of the\nresearchers, and their diligence.\nThe facts they present are quite\nclear!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm, when you say it like that, it\nseems like an interesting program.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(3, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0303000_C00400", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Yes, I have deep interest in black\nholes, so I take many notes.\nThe recent theories are amazing.\nShould I tell you?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm, if there was another time to\nask you...");
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0303000_C00500", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "... I see.\nIf you want to ask, don't refrain\nfrom asking me questions.");
        Voice_PlayVoice("F0303000_C00600", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I am glad that I can have a\nconversation about this program.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(... I'll watch it next time.)");
        Parameter_InCh1Param(3, 530, 35);
        break ;
        case 1:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have likes and dislikes when\nit comes to food,\n｛Hikami＊＊｝?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(3, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C00700", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I do not like greasy foods.\nEven when I eat grilled meat, my\nstomach feels uneasy for the rest of\nthe day.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... What a delicate stomach.");
        Character_BlinkStart(3, 0, (#1), 1);
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C00800", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I like soumen, soba and boiled\ntofu....\nSo perhaps that means I like\nJapanese food?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Rather, perhaps he can only eat\nlight foods...?)");
        Parameter_InCh1Param(3, 531, 36);
        break ;
        case 2:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have any favorite sports,\n｛Hikami＊＊｝?");
        Voice_PlayVoice("F0303000_C00900", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "A favorite sport?\nYou are asking me that?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, did I say something bad?");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(3, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C01000", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "No, not bad, but...\nRight, I don't like sports that\ncompete in terms of points.");
        Character_BlinkStart(3, 0, (#1), 1);
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C01100", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Originally, sports were there to\nenjoy moving your body, right?\nRight, leisure.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nHmm, when you say it like that, it's\nprobably true.");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(3, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C01200", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Right.\nThat is why I do not like sports\nthat require you to improve your\npoint scoring techniques.");
        Character_BlinkStart(3, 2, (#1), 1);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0303000_C01300", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "That, however, limits the sports\nthat I like.\nHaha, I guess that cannot be helped.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I feel like he is coming up with\nexcuses...)");
        Parameter_InCh1Param(3, 532, 37);
        break ;
        case 3:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of music do you listen to,\n｛Hikami＊＊｝?");
        Voice_PlayVoice("F0303000_C01400", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I do not usually listen to music.\nI like sounds of nature.");
        Message_Who(0);
        Message_MsgDisp("主人公", "The sounds of nature?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(3, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0303000_C01500", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "The sound of bugs, or the chirping\nof birds.\nEven the silence of snow piling up.\nIf that can be called music, I like\nit.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(3, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C01600", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Rather, when I listen to noisy\nmusic, my head hurts.\nAbove all, rock music is the worst.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(... I see.\nThat sounds like\n｛Hikami＊＊｝.)");
        Parameter_InCh1Param(3, 533, 38);
        break ;
        case 4:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have any hobbies,\n｛Hikami＊＊｝?");
        Voice_PlayVoice("F0303000_C01700", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I do. Astronomical observation.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Wah, is that so!");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0303000_C01800", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "When I was young, I went to my\nfather's hometown, and saw a sky so\nbeautiful that you could not even\npicture here.");
        Voice_PlayVoice("F0303000_C01900", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I thought \"So there are beautiful\nstars in such a dark sky...\"\nEver since, I have enjoyed\nastronomical observation.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm...\nThen do you also like planetariums?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0303000_C02000", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "That is manmade.\nIt is no match for natural beauty.\nI do not go to planetariums.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, is that so?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I discovered something new about\n｛Hikami＊＊｝!)");
        Parameter_InCh1Param(3, 529, 34);
        break ;
        case 5:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of middle school student\nwere you, ｛Hikami＊＊｝?");
        Voice_PlayVoice("F0303000_C02100", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Right...\nI joined the Student Council,\nthinking to make the school a better\nplace, and did my best by myself.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, by yourself?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C02200", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Yes.\nThere wasn't a person in my middle\nschool who understood my thoughts.\nSo as a result, I had to do it by\nmyself.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That would surely be difficult.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(3, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0303000_C02300", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Yes, there were a few troubles.\nIf I had a friend like you in middle\nschool, things may have been\ndifferent.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nDid ｛Hikami＊＊｝ not have\nany friends?)");
        Parameter_InCh1Param(3, 534, 39);
        break ;
        case 6:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have a future dream,\n｛Hikami＊＊｝?");
        Voice_PlayVoice("F0303000_C02400", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I do.\nI also have set up a stringent plan\nin order to make it come true.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh? What kind of plan?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0303000_C02500", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I am studying all subjects, and I am\naiming to enter a first-rate\nuniversity.\nAfter that, I will study\nastrophysics.");
        Voice_PlayVoice("F0303000_C02600", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "After I graduate, I'll move on to\ngraduate school, and continue my\nstudies.\nWhen I get my PhD, I will study\noverseas.");
        Message_Who(0);
        Message_MsgDisp("主人公", "O-Okay...");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(3, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0303000_C02700", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I will get a PhD there and then\nreturn.\nI'll work for a space research\ninstitution, make a great discovery\nand win a Nobel Prize.");
        Character_BlinkStart(3, 0, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C02800", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "... That is all.\nBut only being able to just call it\nan \"amazing discovery\" is\nirritating.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(.........\nIf it's ｛Hikami＊＊｝, it\nseems like he can make it happen...)");
        Parameter_InCh1Param(3, 528, 33);
        break ;
        case 7:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of girl do you like,\n｛Hikami＊＊｝?");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(3, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C02900", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I have not even considered it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, really?");
        Character_BlinkStart(3, 0, (#1), 1);
        Voice_PlayVoice("F0303000_C03000", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Yes, because there are other things\nI should be thinking about.\nIt is low on my list of priorities.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so...");
        Character_BlinkStart(3, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0303000_C03100", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "But now that I have the chance, I\nwill think about it.\nHmm.........");
        Message_Who(0);
        Message_MsgDisp("主人公", "... How about it?");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(3, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C03200", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "... I am still thinking.");
        Message_Who(0);
        Message_MsgDisp("主人公", "O-Okay...");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(3, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C03300", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "... No, I cannot think of one.\nIt is actually a difficult question.\nSorry, will you give me a bit more\ntime to think?");
        Message_Who(0);
        Message_MsgDisp("主人公", "S-Sure.");
        Character_BlinkStart(3, 3, (#1), 1);
        Voice_PlayVoice("F0303000_C03400", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Good at cooking... Likes children...\nNo, it is not about marriage.\nA quick thinker...\nGood at listening...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, I made him worry about it...)");
        Parameter_InCh1Param(3, 535, 40);
        break ;
        case 8:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of love do you want to\nhave, ｛Hikami＊＊｝?");
        Voice_PlayVoice("F0303000_C03500", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "...........");
        Message_Who(0);
        Message_MsgDisp("主人公", "What's wrong, ｛Hikami＊＊｝?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C03600", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Nothing, it is a tough question, so\nI cannot answer you right away.\nLove...");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's okay if you don't think too\ndeeply about it, okay?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F0303000_C03700", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "That cannot be right.\nIn the world of literature and art,\nlove is the greatest theme.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Well, that's right, but...");
        Voice_PlayVoice("F0303000_C03800", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I think that I would like a nice\nkind of love.\nBut what exactly is a nice kind of\nlove?");
        Voice_PlayVoice("F0303000_C03900", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "How does love start?\nIs unrequited love still love?\nWhen you fall in love, you have a\nwider scope.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm, definitely...");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(3, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0303000_C04000", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Sorry, I cannot give a good answer.\nI want to understand what \"a nice\nkind of love\" is.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehhhhhh!");
        Parameter_InCh1Param(3, 536, 41);
        break ;
        case 9:
        if (Parameter_GetPl1Param(312) != 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Hikami＊＊｝...\nUmm, what do you think about kisses?");
            Character_ChFace(0, 0, 11);
            Voice_PlayVoice("F0303000_C04100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Y-You are asking me about something\nabsurd.\nIt is one way of expressing love,\nright?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh, is that all?");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("F0303000_C04200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Yes.... Is there anything else?");
            Message_Who(0);
            Message_MsgDisp("主人公", "H-Hmm, what kind of kiss do you want\nto have, ｛Hikami＊＊｝～?\nKidding.");
            Character_ChFace(0, 0, 8);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F0303000_C04300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "What, are you even thinking about\nyour own questions?\nThat is... Hmm...");
            Message_Who(0);
            Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
            Character_ChFace(0, 0, 9);
            Voice_PlayVoice("F0303000_C04400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It is difficult.\nIt is something that depends on the\nother person...\nThat person may also have an\nideal...");
            Character_BlinkStart(3, 3, (#1), 1);
            Voice_PlayVoice("F0303000_C04500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "No, if both people love one another,\nthen perhaps it has nothing to do\nwith ideals...\nHmm...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ah, I got him worrying...)");
            Parameter_InCh1Param(3, 537, 42);
            }
        else {
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Hikami＊＊｝...\nUmm, what do you think about kisses?");
            Character_ChFace(0, 0, 3);
            Character_BlinkStart(3, 3, (#1), 1);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F0303000_C04600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", ".........");
            Message_Who(0);
            Message_MsgDisp("主人公", "Umm, ｛Hikami＊＊｝?");
            Character_ChFace(0, 0, 11);
            Character_BlinkStart(3, 2, (#1), 1);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F0303000_C04700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Even if you ask me w-what...\nGenerally, it is one way to express\nlove.\nBut, there are also times when\nthat's not so...");
            Character_ChFace(0, 0, 3);
            Character_BlinkStart(3, 3, (#1), 1);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F0303000_C04800", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "......\nThat time was j-j-just a minor\ncollision!\nShould we not think about it that\nway?");
            Message_Who(0);
            Message_MsgDisp("主人公", "But accidents aren't kisses?");
            Character_ChFace(0, 0, 8);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F0303000_C04900", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Ah, no! Clearly!");
            Message_Who(0);
            Message_MsgDisp("主人公", "Hmm, right...");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(3, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F0303000_C05000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Eh...\nDo you count how many kisses you\nhave done?\nThat in itself is... embarrassing.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... ｛Hikami＊＊｝?\nWhy is it embarrassing?");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("F0303000_C05100", 3, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Eh?\nAre you not talking about that time,\n｛主人公｝?");
            Message_Who(0);
            Message_MsgDisp("主人公", "That time?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(3, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0303000_C05200", 3, "F0303000_C05201");
            Message_Who(3);
            Message_MsgDisp("Hikami", "...\nAh, right, I was just jumping to\nconclusions.\nDon't worry, ｛主人公｝.\nLet us not talk about this.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(...\nIs ｛Hikami＊＊｝ maybe\ntalking about that time...?)");
            Parameter_InCh1Param(3, 537, 42);
            }
        break ;
        }
    if (Parameter_GetCh1Param(3, 558) != 1){
        switch (var1){
            case 10:
            Message_Who(0);
            Message_MsgDisp("主人公", "What do guys usually think about?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(3, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_070_00000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I get it.\nYou are asking for advice about\nlove, right?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh? Y-Yeah, well, maybe.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 3, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_070_00100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Alright... Okay.\nAn objective they have for their\nlife...\nAs expected, would it not it be\ntheir future dreams?");
            Message_Who(0);
            Message_MsgDisp("主人公", "R-Really?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_070_00200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It surely must be that.\nThat is what I think.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Hmm...");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_070_00300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "So it was a consultation about\nlove...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Hikami＊＊｝...)");
            break ;
            case 11:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder what kind of girls guys\nlike...");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_080_00000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Wait...\nIn other words, you want to know his\npreferences.\nIs it that kind of consultation?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh? Umm...");
            Voice_PlayVoice("FD_03_080_00100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Alright, I will ask him what kind of\ngirl he likes.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ehh!? No, it's fine!");
            Voice_PlayVoice("FD_03_080_00200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Do not worry, I will not bring up\nyour name.\nRight, I will ask him as a friend.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Really, it's fine!");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_080_00300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Really? There is no need to refuse.");
            break ;
            case 12:
            Message_Who(0);
            Message_MsgDisp("主人公", "At what time does your heart beat\nfaster, ｛Hikami＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_090_00000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "In other words, when am I flustered?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah. Well that kind of feeling.");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_090_00100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I have no room to be flustered.\nIf you have enough flexibility, then\nyou will have room to cope with\nthese things.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Even in front of the person you\nlike?");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 4);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_090_00200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "O-Of course!\nAs if my heart would beat faster!\nHa-haha!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Is ｛Hikami＊＊｝\nflustered?)");
            break ;
            case 13:
            Message_Who(0);
            Message_MsgDisp("主人公", "What should I do to appear more\nfeminine?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_100_00000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Oh, a consultation about love?\nFemininity, huh. Right...");
            Voice_PlayVoice("FD_03_100_00100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "What if you tried putting a large\nribbon in your hair?");
            Message_Who(0);
            Message_MsgDisp("主人公", "A large... ribbon?");
            Voice_PlayVoice("FD_03_100_00200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "If you do, they will become aware of\nyou each time they look at the\nribbon, right?\nIt should be a color that stands\nout.");
            Message_Who(0);
            Message_MsgDisp("主人公", "H-Hmm～?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_100_00300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "... Is that no good?\nMy sense of fashion is...");
            break ;
            case 14:
            Message_Who(0);
            Message_MsgDisp("主人公", "Perhaps there is no reward in having\nfeelings of unrequited love...");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_110_00000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I do not want to hear such\ncomplaints coming from your mouth.");
            Message_Who(0);
            Message_MsgDisp("主人公", "But...");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_110_00100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It depends on the other person.\nIt might not go as you plan.\nBut that is why it is worth it.\nIs it not?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah...");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_110_00200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I believe there is achievement in\nunrequited love, rather than mutual\nlove.\nIt confirms that love is there.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Right... yeah. Thanks!");
            break ;
            case 16:
            Message_Who(0);
            Message_MsgDisp("主人公", "Are you in love,\n｛Hikami＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_120_00000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Although it is unfortunate, I never\nhad the experience.\nBut wait, I will collect the proper\ndata.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Data?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_120_00100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Yeah.\nI have a responsibility to, since I\nsaid I would advise you.");
            Voice_PlayVoice("FD_03_120_00200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "The chances of unrequited love\nhaving a happy end is above 70%.");
            Voice_PlayVoice("FD_03_120_00300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Even if you are enemies, there is a\n50% chance of becoming lovers.\nBut in this case, there are lots of\ndeaths.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Deaths!?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_120_00400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Yes, right.\nI analyzed 100 world literary\nmasterpieces...\nShould I analyze 200 instead?");
            Message_Who(0);
            Message_MsgDisp("主人公", ".........");
            break ;
            case 17:
            Message_Who(0);
            Message_MsgDisp("主人公", "What do you think about kisses,\n｛Hikami＊＊｝?");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 4);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_130_00000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Ki! ...\nDo you mean that thing that happened\nin May of first year?");
            Message_Who(0);
            Message_MsgDisp("主人公", "\"That\"? ... Ah!");
            Voice_PlayVoice("FD_03_130_00100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "T-That was an accident!\nIt has no effect on the love that\nyou will be experiencing from now\non.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Y-Yeah. I know.");
            Voice_PlayVoice("FD_03_130_00200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It is fine!\nIf we forget it, it will be like it\nnever happened.");
            Voice_PlayVoice("FD_03_130_00300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Alright, I have already forgotten\nabout it!\nWhat about you? Haha-hahahaha.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Hikami＊＊｝ is really\nrestless...)");
            break ;
            case 18:
            Message_Who(0);
            Message_MsgDisp("主人公", "Should I be engaging in more\nskinship?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_140_00000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Right, I think that it is fine, as\nlong as you want to do it.");
            Message_Who(0);
            Message_MsgDisp("主人公", "B-But, you know?\nIf I take it too far...");
            Voice_PlayVoice("FD_03_140_00100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Is that not fine?\nI do not hate it, even if they are\nforcing themselves.\nI can feel the love.");
            Message_Who(0);
            Message_MsgDisp("主人公", "R-Right...");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_140_00200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "But then when I asked my parents,\nthey told to me to never get carried\naway.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(So it's something you discuss with\nyour family...)");
            break ;
            case 19:
            Message_Who(0);
            Message_MsgDisp("主人公", "What do you think about friendship\nbetween men and women?");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 4);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_150_00000", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Between who and who?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Obviously, between me and you,\n｛Hikami＊＊｝.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_150_00100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I see.\nSo you generally find me useful.\nI am somewhat glad.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Why?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_150_00200", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "There are a lot of people who label\nme as a weird guy.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_150_00300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "What I am glad about, is having a\nfriend that I can consult with like\nthis.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Hikami＊＊｝...)");
            break ;
            }
        }
    else {
        switch (var1){
            case 10:
            Message_Who(0);
            Message_MsgDisp("主人公", "What do guys think about?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_070_00400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It depends on the person, and it\nalso depends on the time and place.\nWould you narrow it down a little?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Then what are you thinking about\nnow, ｛Hikami＊＊｝?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_070_00500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Me? I...");
            Voice_PlayVoice("FD_03_070_00600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Right now, I am thinking that it\nwould be nice if this could\ncontinue.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Now...\nAh, you mean your high school life?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_070_00700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Huh? ... Right, yes.");
            break ;
            case 11:
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of girls do guys like?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_080_00400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "That is...\nI think they will only know once\nthey like someone.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I see...\nAre you like that,\n｛Hikami＊＊｝?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(3, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_080_00500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Yes... I am.\nI think that I will never forget\nthem.\nEven if their preferences change in\nthe future.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Hikami＊＊｝?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 3, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_080_00600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Please, do not ask me anymore.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Hikami＊＊｝...)");
            break ;
            case 12:
            Message_Who(0);
            Message_MsgDisp("主人公", "At what kind of time does a guy's\nheart beat faster?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_090_00300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "R-Right...\nFor example, wouldn't their hearts\nthrob if they were together with the\ngirl they like?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Hmm...\nThen does that mean if their heart\ndoesn't beat faster, they don't like\nthe girl?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_090_00400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I do not know...\nPerhaps I did not choose a good\nexample.");
            Voice_PlayVoice("FD_03_090_00500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I am a coward.\nI have recently discovered this\nfact.\nI am surely different from him.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Hikami＊＊｝...)");
            break ;
            case 13:
            Message_Who(0);
            Message_MsgDisp("主人公", "Would it be bad if I didn't become\nmore feminine?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_100_00400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Did he say that to you?");
            Message_Who(0);
            Message_MsgDisp("主人公", "No. That's not it.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_100_00500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "You... are charming enough.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Really?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_100_00600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Of course!\nNot just your external appearance.\nYou are, how should I put it...\nRight, special!");
            Message_Who(0);
            Message_MsgDisp("主人公", "O-Okay, thanks.");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_100_00700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "If there was a guy who didn't\nunderstand that, I would...\nNo, it is none of my business.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Hikami＊＊｝...)");
            break ;
            case 14:
            Message_Who(0);
            Message_MsgDisp("主人公", "Perhaps there's no reward in having\nfeelings of unrequited love...");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_110_00300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "...\nIt is similar to astronomical\nobservation.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Astronomical observation?");
            Voice_PlayVoice("FD_03_110_00400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Even though you see it in front of\nyou, it is billions of light years\naway.\nSurely, you cannot reach it.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 2, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_110_00500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "That is what I have been thinking\nlately, when I watch the stars.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(What's wrong with\n｛Hikami＊＊｝?)");
            break ;
            case 16:
            Message_Who(0);
            Message_MsgDisp("主人公", "Are you in love right now?");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 4);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_120_00500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "!! ... Why do you ask?");
            Message_Who(0);
            Message_MsgDisp("主人公", "I was just wondering if you have\nanyone that you like,\n｛Hikami＊＊｝.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_120_00600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I do not want to answer.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I see, sorry...");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_120_00700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It has nothing to do with me now.\nI am a boring guy who only studies\nand does Student Council activities.");
            Message_Who(0);
            Message_MsgDisp("主人公", "That's not true!\nI think you're amazing,\n｛Hikami＊＊｝.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 2, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_120_00800", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Then why... No, it is fine.\nI want to stop talking about this.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Hikami＊＊｝...)");
            break ;
            case 17:
            Message_Who(0);
            Message_MsgDisp("主人公", "What do you think about kisses,\n｛Hikami＊＊｝?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_130_00400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "You mean...\nthat thing that happened earlier?");
            Message_Who(0);
            Message_MsgDisp("主人公", "\"That thing\"? ... Ah!");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_130_00500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It seems like you have forgotten.\nThat is fine.\nIt would be strange if you\nremembered.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Umm, I...");
            Voice_PlayVoice("FD_03_130_00600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I will also forget.\nIf we both forget about it, it will\nbe like it never happened.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_130_00700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Like it never happened...");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Hikami＊＊｝...");
            break ;
            case 18:
            Message_Who(0);
            Message_MsgDisp("主人公", "I want to be able to do skinship in\na better way.");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_140_00300", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Eh? R-Really...\nIt would be nice if it went well.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Hikami＊＊｝?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_140_00400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Sorry.\nSee, I am a straight-laced person,\nright?\nI cannot really talk about such\nthings.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Really...? Sorry.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_140_00500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "It is fine.\nBut I do not want to imagine it.\nYou and him... No.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Hikami＊＊｝...)");
            break ;
            case 19:
            Message_Who(0);
            Message_MsgDisp("主人公", "What do you think about friendship\nbetween men and women?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_03_150_00400", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "A friendship is something amazing.\nNo matter what happens, it is hard\nto change.\nIt has nothing to do with gender.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah, that's right.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_150_00500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "That is what I thought. But...");
            Voice_PlayVoice("FD_03_150_00600", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "I know now. Friendship is cruel.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... Friendship is cruel?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(3, 2, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("FD_03_150_00700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Friendship lied to me.\nThat is why it is cruel.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Hikami＊＊｝...)");
            break ;
            }
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Music_StopBGM(0, 40);
    Screen_ClearScreen();
    }
