section "f03_m6_000"{
    Character_BlinkStart(6, 1, (#1), 1);
    Character_BlinkStart(6, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(6, "M6_03F", 0);
    Background_Bg_GS2("BG_EX000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGB_062_000", 127, 40);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "...\nBy the way, ｛Amachi＊＊｝.");
    if (Parameter_GetCh1Param(6, 130) <= 2){
        Voice_PlayVoice("F0306000_F00000", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "What is it?");
        }
    else if (Parameter_GetCh1Param(6, 130) >= 3){
        Voice_PlayVoice("F0306000_F00100", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Yes, what?");
        }
    Message_Sele_Kitaku_Kaiwa();
    int var1 = Parameter_Kitaku_Kaiwa(0);
    switch (var1){
        case 0:
        if (Parameter_GetCh1Param(6, 130) <= 2){
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of TV shows do you usually\nwatch, ｛Amachi＊＊｝?");
            Voice_PlayVoice("F0306000_F00200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Well...\nVariety shows and music shows.\nI also watch dramas.");
            Message_Who(0);
            Message_MsgDisp("主人公", "You don't watch the news and stuff?");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("F0306000_F00300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Not really...\nDo you watch the news, Senpai?\nAs expected.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad.)");
            }
        else if (Parameter_GetCh1Param(6, 130) >= 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of TV shows do you usually\nwatch, ｛Amachi＊＊｝?");
            Voice_PlayVoice("F0306000_F00400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Well...\nMaybe variety shows and music shows?\nAh, I also watch dramas.");
            Message_Who(0);
            Message_MsgDisp("主人公", "You don't watch the news and stuff?");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("F0306000_F00500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I will watch the news if there is\nsomething interesting, but apart\nfrom that, I don't watch it.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad.)");
            }
        Parameter_InCh1Param(6, 530, 35);
        break ;
        case 1:
        if (Parameter_GetCh1Param(6, 130) <= 2){
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you have any favorite foods?");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F00600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Sweet food.\nI accidentally overeat sweet food.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh, is that so?\nDo you have anything that is your\nabsolute favorite?");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("F0306000_F00700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Choosing which is my absolute\nfavorite is difficult...\nMaybe cakes.");
            Voice_PlayVoice("F0306000_F00800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "When I was in junior school, there\nhad been a time where I cried,\nsaying that I wanted to be the son\nof a cake store owner.");
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 2, 5);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F00900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Even now, I still think about it a\nlittle.\nI want to move a little closer to\nthe stores.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(So he really likes cakes.)");
            }
        else if (Parameter_GetCh1Param(6, 130) >= 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you eat a proper breakfast,\n｛Amachi＊＊｝?");
            Character_ChFace(0, 2, 5);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F01000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Yes, of course!\nI'm in the Cheer Squad, so I need\nphysical energy.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I see.\nSo that must mean you eat three\nproper meals a day.");
            Voice_PlayVoice("F0306000_F01100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I often eat five meals a day.");
            Message_Who(0);
            Message_MsgDisp("主人公", "What!?");
            Voice_PlayVoice("F0306000_F01200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Breakfast, lunch, noon tea, dinner,\nand supper.\nEven so, when I'm hungry in between\nbreakfast and lunch, I eat a snack.");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("F0306000_F01300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "All that eating and my body doesn't\ngrow any taller.\nI wonder why...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(It doesn't look like he eats that\nmuch.)");
            }
        Parameter_InCh1Param(6, 531, 36);
        break ;
        case 2:
        if (Parameter_GetCh1Param(6, 130) <= 2){
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of sports do you like,\n｛Amachi＊＊｝?");
            Voice_PlayVoice("F0306000_F01400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I'm good at skiing and ice skating.\nI'm quite confident in my skating\nabilities.");
            Voice_PlayVoice("F0306000_F01500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Also, I'm good at swimming.\nNow that I think about it, I often\ngo to the pool.");
            Message_Who(0);
            Message_MsgDisp("主人公", "You don't play any ball games?\nLike baseball or soccer...");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F01600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I like sports that you can do by\nyourself.\nI kind of dislike sports where you\nhave to group with others.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad.)");
            }
        else if (Parameter_GetCh1Param(6, 130) >= 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you have any favorite sports,\n｛Amachi＊＊｝?");
            Voice_PlayVoice("F0306000_F01700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Maybe ice skating and skiing.\nI have confidence in my skating\nabilities.");
            Message_Who(0);
            Message_MsgDisp("主人公", "So you only like sports that require\nyou to slide.");
            Voice_PlayVoice("F0306000_F01800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Yeah, it's fine if you can maintain\nbalance, so it's fun.");
            Message_Who(0);
            Message_MsgDisp("主人公", "What about ball games?\nLike baseball or soccer...");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F01900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "You get sweaty and I dislike teaming\nup with other people.\nSo I'll pass when it comes to team\nsports!");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F02000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Ah, I like swimming, so team sports\nmight be okay if it was maybe\nsynchronised swimming.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I-I see...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad.)");
            }
        Parameter_InCh1Param(6, 532, 37);
        break ;
        case 3:
        if (Parameter_GetCh1Param(6, 130) <= 2){
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of music do you usually\nlisten to?");
            Voice_PlayVoice("F0306000_F02100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I listen to pretty much anything.\nAs expected, I don't listen to\nclassical music, though.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I see... What about singing?");
            Character_ChFace(0, 2, 5);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F02200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I like singing.\nDoesn't it feel good when you're\nsinging in a bath?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad.)");
            }
        else if (Parameter_GetCh1Param(6, 130) >= 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of music do you like,\n｛Amachi＊＊｝?");
            Voice_PlayVoice("F0306000_F02300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I listen to everything, but I don't\nlike classical music.\nIt makes me sleepy.");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F02400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I don't like hip-hop, either.\nMaybe it's because I can't keep up\nwith the lyrics no matter what...");
            Voice_PlayVoice("F0306000_F02500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I also don't know what's so good\nabout jazz music...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Hmm...\nI don't think you could say that you\nlisten to everything...)");
            }
        Parameter_InCh1Param(6, 533, 38);
        break ;
        case 4:
        if (Parameter_GetCh1Param(6, 130) <= 2){
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you have any hobbies,\n｛Amachi＊＊｝?");
            Voice_PlayVoice("F0306000_F02600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Well, nothing in particular...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Nothing at all?\nLike reading, playing sport, or\nplaying games?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F02700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Ah, I like games.\nI get really into it when I compete.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Really?");
            Voice_PlayVoice("F0306000_F02800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I get so into it that before I know\nit, I've won.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Saying that he always wins means\nhe's quite good at games, right?)");
            }
        else if (Parameter_GetCh1Param(6, 130) >= 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you have any sort of hobbies,\n｛Amachi＊＊｝?");
            Voice_PlayVoice("F0306000_F02900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I like...\ngames, but not to the point where it\nwould be a hobby.");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F03000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Hmm～... Ah!");
            Message_Who(0);
            Message_MsgDisp("主人公", "You thought of something?");
            Character_ChFace(0, 2, 3);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("F0306000_F03100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I like going to cake stores when\nthey release new products and eating\nthem right away!");
            Voice_PlayVoice("F0306000_F03200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "When a new product is released, I\nmust go and eat it right away.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad.)");
            }
        Parameter_InCh1Param(6, 529, 34);
        break ;
        case 5:
        if (Parameter_GetCh1Param(6, 130) <= 2){
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of student were you in\nyour middle school period?");
            Voice_PlayVoice("F0306000_F03300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "No different than how I am now.\nMy stature hasn't even changed that\nmuch.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Really?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F03400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "What should I do in order to grow\ntaller...?");
            Message_Who(0);
            Message_MsgDisp("主人公", "(He's worried.)");
            }
        else if (Parameter_GetCh1Param(6, 130) >= 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of kid were you in middle\nschool?");
            Voice_PlayVoice("F0306000_F03500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I probably haven't changed that\nmuch.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Meaning...?");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("F0306000_F03600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Yes, I was a good kid.\nBecause girls were happier that way.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Happier?");
            Voice_PlayVoice("F0306000_F03700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "When I made a face and said, \"I'm a\ngood kid\", all of the girls went\nwild.\nThey would come and talk to me.\nBut...");
            Voice_PlayVoice("F0306000_F03800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I wonder what would happen if they\nknew the real me?\nI have had times where I've been\ndown.");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F03900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... As if! Ahaha!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Even though he's laughing and\njoking, I wonder if it really is\ntrue...)");
            }
        Parameter_InCh1Param(6, 534, 39);
        break ;
        case 6:
        if (Parameter_GetCh1Param(6, 130) <= 2){
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you have a dream for the future\nor something you want to be,\n｛Amachi＊＊｝?");
            Voice_PlayVoice("F0306000_F04000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Not right now.\nThat's why when I see people with an\nobjective, I think they're amazing.");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F04100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It would be nice if I could discover\nwhat I want to do in these three\nyears at high school.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad.)");
            }
        else if (Parameter_GetCh1Param(6, 130) >= 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "What do you want to be in the\nfuture, ｛Amachi＊＊｝?");
            Character_BlinkStart(6, 3, (#1), 1);
            Voice_PlayVoice("F0306000_F04200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... I won't say.");
            Message_Who(0);
            Message_MsgDisp("主人公", "What, why?");
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 2, 1);
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("F0306000_F04300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nI'd hate for people to laugh at me\nand say that I'm not cut out for it\nbecause I'm bothersome.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I won't laugh.");
            Character_BlinkStart(6, 3, (#1), 1);
            Voice_PlayVoice("F0306000_F04400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "............ I won't say it!\nI'll say it if I feel like it!");
            Message_Who(0);
            Message_MsgDisp("主人公", "I see.\nThen if such a time comes, tell me.");
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 2, 3);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("F0306000_F04500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "O-Only if I remember!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(That's the kind of conversation we\nhad.)");
            }
        Parameter_InCh1Param(6, 528, 33);
        break ;
        case 7:
        if (Parameter_GetCh1Param(6, 130) <= 2){
            Message_Who(0);
            Message_MsgDisp("主人公", "What type of girl do you like,\n｛Amachi＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F04600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "A person like you, Senpai.");
            Message_Who(0);
            Message_MsgDisp("主人公", "What? R-Really?");
            Voice_PlayVoice("F0306000_F04700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Yes. A kind...\nand dependable, older person.");
            Voice_PlayVoice("F0306000_F04800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "That's why I unexpectedly depend on\nSenpai...\nHahaha.");
            }
        else if (Parameter_GetCh1Param(6, 130) >= 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "What type of girl do you like,\n｛Amachi＊＊｝?");
            Voice_PlayVoice("F0306000_F04900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Let me think...");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F05000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Senpai.");
            Message_Who(0);
            Message_MsgDisp("主人公", "W-What!?");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("F0306000_F05100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Yeah, that!\nI really like it when they take\nthings seriously.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... That...");
            Voice_PlayVoice("F0306000_F05200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Yeah.\nSomeone easy to tease is the best!");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ugh......");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("F0306000_F05300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... You also take this seriously.\nSenpai really is slow...");
            Message_Who(0);
            Message_MsgDisp("主人公", "What?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("F0306000_F05400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It's nothing.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I wonder what he said...)");
            }
        Parameter_InCh1Param(6, 535, 40);
        break ;
        case 8:
        if (Parameter_GetCh1Param(6, 130) <= 2){
            Message_Who(0);
            Message_MsgDisp("主人公", "What do you think in regards to\nlove, ｛Amachi＊＊｝?");
            Voice_PlayVoice("F0306000_F05500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Love, was it? What a serious topic.\nI don't know much, though...");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("F0306000_F05600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I think it would be nice if I could\ncome across an amazing person and\nshare an amazing kind of love with\nthem.");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F05700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Do you think I could do something\nlike that?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah, I think so.\nBecause you do level-headed things,\n｛Amachi＊＊｝.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F05800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... Level-headed, huh? Haha.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Amachi＊＊｝?)");
            }
        else if (Parameter_GetCh1Param(6, 130) >= 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of love do you want to\nhave, ｛Amachi＊＊｝?");
            Voice_PlayVoice("F0306000_F05900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... Senpai.\nDo you have a fever or something?\nOr did you eat something bad?");
            Message_Who(0);
            Message_MsgDisp("主人公", "I don't have a fever, and I haven't\neaten anything bad.\nI was a little curious.");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("F0306000_F06000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Hmm...");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F06100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nI would dislike it if when I thought\nof the other person, I felt lonely\nwhen I'm supposed to feel happy.");
            Voice_PlayVoice("F0306000_F06200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It would probably be like that if\nthere was a barrier between that\nperson and I, and nothing could be\ndone about it...");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("F0306000_F06300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "*Sigh*... Why are things like this?");
            Message_Who(0);
            Message_MsgDisp("主人公", "(... ｛Amachi＊＊｝?)");
            }
        Parameter_InCh1Param(6, 536, 41);
        break ;
        case 9:
        if (Parameter_GetPl1Param(312) != 6){
            Message_Who(0);
            Message_MsgDisp("主人公", "What kind of kiss is your ideal\nkiss, ｛Amachi＊＊｝?");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("F0306000_F06400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Senpai... what is the matter?\nAre you worried about something?");
            Message_Who(0);
            Message_MsgDisp("主人公", "That's not it!\nI just wanted to try asking.");
            Voice_PlayVoice("F0306000_F06500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Hmm... Well, it's fine.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F0306000_F06600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "My ideal kiss would be like in a\nmovie, where things get really\nheated up and then...");
            Voice_PlayVoice("F0306000_F06700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "You would see their two shadows\nholding each other!\nSomething like that...");
            Message_Who(0);
            Message_MsgDisp("主人公", "One with a romantic feeling?");
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("F0306000_F06800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Yeah!\nIn particular, the first kiss is\nimportant!");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("F0306000_F06900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nWhy did I have to emphasize that?");
            Character_ChFace(0, 0, 8);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F0306000_F07000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I can't believe you, Senpai.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Huh, why～?)");
            Parameter_InCh1Param(6, 537, 42);
            }
        else if (Parameter_GetPl1Param(312) == 6){
            Message_Who(0);
            Message_MsgDisp("主人公", "What do you think about kisses,\n｛Amachi＊＊｝?");
            Character_ChFace(0, 0, 11);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F0306000_F07100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "H...Huh?\nWhy are you asking all of a sudden!?\nNow after such a long time, you...");
            Message_Who(0);
            Message_MsgDisp("主人公", "After such a long time?");
            Character_ChFace(0, 0, 8);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F0306000_F07200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nI was just thinking \"As if\", Senpai.\nThat thing that happened then...\nLike maybe you didn't see it as a\nkiss...");
            Message_Who(0);
            Message_MsgDisp("主人公", "\"That thing that happened then\"...?");
            Character_ChFace(0, 0, 9);
            Character_BlinkStart(6, 3, (#1), 1);
            Voice_PlayVoice("F0306000_F07300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... As I thought...\nI thought it was amazing too,\nbecause it was like a drama.");
            Message_Who(0);
            Message_MsgDisp("主人公", "What?");
            Character_ChFace(0, 0, 9);
            Character_BlinkStart(6, 2, (#1), 1);
            Voice_PlayVoice("F0306000_F07400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Well, yes.\nThat was just an accident.");
            Voice_PlayVoice("F0306000_F07500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It's fine if you've forgotten.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Why is ｛Amachi＊＊｝\nangry...?)");
            Parameter_InCh1Param(6, 537, 42);
            }
        break ;
        }
    if (Parameter_GetCh1Param(6, 558) != 1){
        switch (var1){
            case 10:
            Message_Who(0);
            Message_MsgDisp("主人公", "What do guys think about?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 4);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_070_00000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It's useless just thinking about\nthat, Senpai.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_070_00100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Anyway! ... Is it okay?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Y-Yes.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_070_00200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "We should do some research to have\nfull knowledge about him!\nAnd to also see what things you can\nchange!");
            Message_Who(0);
            Message_MsgDisp("主人公", "A-Amazing...");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_070_00300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It's a sure-fire way to win.\nIt's what my older sister does.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I see... He's really persuasive.)");
            break ;
            case 11:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder what I should do in order\nto know what guys like?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_080_00000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Not guys, but the person you like,\nright?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_080_00100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "You shouldn't ask me, but the person\nthemself.\nDirectly.");
            Message_Who(0);
            Message_MsgDisp("主人公", "T-That's true, but...");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_080_00200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Wouldn't he tell you if you play\ndumb like you usually do?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_080_00300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "On that note, I think it would be\nbetter if you had self confidence,\nSenpai.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ugh... Am I being teased?)");
            break ;
            case 12:
            Message_Who(0);
            Message_MsgDisp("主人公", "At what time does your heart beat\nfaster because of a girl,\n｛Amachi＊＊｝?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_090_00000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nYou're asking a bold thing, Senpai.\nAre you already at your wit's end?");
            Message_Who(0);
            Message_MsgDisp("主人公", "I-I didn't ask because of that.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_090_00100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Hmm...... Heart throbbing, huh?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_090_00200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Maybe when I make them do something,\nbut not when they themselves do\nsomething.");
            Message_Who(0);
            Message_MsgDisp("主人公", ".........");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_090_00300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Sorry, I'm no use to you.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ugh, as expected of\n｛Amachi＊＊｝...)");
            break ;
            case 13:
            Message_Who(0);
            Message_MsgDisp("主人公", "What part about a girl makes you\nthink \"She's so feminine\",\n｛Amachi＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_100_00000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I think that when I see Senpai.\nSometimes.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh? Why?");
            Voice_PlayVoice("FD_06_100_00100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Guys don't usually listen to other\npeoples' love issues.\nSo...");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_100_00200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "When I see Senpai being so fidgety,\nI think \"She's a girl after all!\"");
            Message_Who(0);
            Message_MsgDisp("主人公", "I see...\nWait, what do you mean by, \"She's a\ngirl after all!\"!?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_100_00300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "You're so slow!\nSenpai really is a blockhead.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ugh......)");
            break ;
            case 14:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder what I should do to make\nsituations of unrequited love\nenjoyable?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_110_00000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Isn't there really no need to think\nit's fun if you're going to force\nyourself?");
            Voice_PlayVoice("FD_06_110_00100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Well, even though it is only\npainful, it's not like you won't go\non.");
            Voice_PlayVoice("FD_06_110_00200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Doesn't it mean there is nothing\nthat can make you think that it's\nfun?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah, well...");
            Voice_PlayVoice("FD_06_110_00300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "That includes everything that comes\nwith unrequited love.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_110_00400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "If everything was good and nothing\nbad happened, it would be boring.\nRight, Senpai?");
            Message_Who(0);
            Message_MsgDisp("主人公", "(As expected of\n｛Amachi＊＊｝.)");
            break ;
            case 16:
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_120_00000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I am.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_120_00100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nWith Anastasia's super limited new\ncake.\n10 Rich for one whole cake!");
            Message_Who(0);
            Message_MsgDisp("主人公", "10 Rich!?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_120_00200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Yeah.\nOf course, I wouldn't pay for it...");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_120_00300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "So yeah... Help me out, Senpai!\nWith my love.");
            Message_Who(0);
            Message_MsgDisp("主人公", "What?!");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_120_00400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Don't I also help you, Senpai?\nCome on, please!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Even if you ask me with those eyes,\nI'm not going to buy it for you～!)");
            break ;
            case 17:
            Message_Who(0);
            Message_MsgDisp("主人公", "What do you think about kisses,\n｛Amachi＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_130_00000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It was like a drama.\nThe kiss at that time.");
            Voice_PlayVoice("FD_06_130_00100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "And the fact that we could meet\nagain in high school...");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_130_00200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... Hey, Senpai.");
            Voice_PlayVoice("FD_06_130_00300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It could be that we are connected by\nthe red string of fate.");
            Message_Who(0);
            Message_MsgDisp("主人公", "What!? U-Umm... That's...");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_130_00400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Gee, Senpai, you're so flustered!\nBut you were so cute, just like a\nhamster!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Uhh, but your way of teasing is\ncruel, ｛Amachi＊＊｝...)");
            break ;
            case 18:
            Message_Who(0);
            Message_MsgDisp("主人公", "What is skinship to you,\n｛Amachi＊＊｝?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_140_00000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Headlock or a horizontal chop...");
            Message_Who(0);
            Message_MsgDisp("主人公", "What!?");
            Voice_PlayVoice("FD_06_140_00100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Because that's the kind of harsh\nthings my older sisters have done to\nme.\nThey say it's their weird way of\nshowing love.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Their way of showing love... I see.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_140_00200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... Senpai. You can't.\nThey're bad things to do.");
            Message_Who(0);
            Message_MsgDisp("主人公", "O-Okay.\nOf course I won't do those things.");
            Voice_PlayVoice("FD_06_140_00300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... How suspicious...");
            break ;
            case 19:
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you think that friendships\nbetween men and women exist?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_150_00000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "They do, don't they?");
            Voice_PlayVoice("FD_06_150_00100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It's unbelievable to think that all\nthe men and women in the world love\neach other.");
            Voice_PlayVoice("FD_06_150_00200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "But there are also times when\nfriendship changes into love.");
            Voice_PlayVoice("FD_06_150_00300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "So wouldn't it be better to notice\nthings like that?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh? Me?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_150_00400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... I'm worried.\nIt seems like there are many\nvictims.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(What does he mean by \"victims\"...?)");
            break ;
            }
        }
    else {
        switch (var1){
            case 10:
            Message_Who(0);
            Message_MsgDisp("主人公", "I don't know what guys think\nabout...");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_070_00400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "That can't be helped, can it?\nBecause you play dumb.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ugh......");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_070_00500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "If Senpai was sharp, you wouldn't\nhave asked me such a thing.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Umm...\nWhat did you just say,\n｛Amachi＊＊｝?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_070_00600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... I don't know.");
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_070_00700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Just stay oblivious.\nThat is something Senpai is more\nlike....\nYou're fine the way you are now.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Amachi＊＊｝?)");
            break ;
            case 11:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder what kind of girls guys\nlike?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_080_00400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "If you knew that, would you change\nfor the sake of the person you like?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Hmm... Maybe.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_080_00500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... Hmm...");
            Message_Who(0);
            Message_MsgDisp("主人公", "What? Is that strange?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_080_00600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Whatever is fine, isn't it?\nIf it's okay with you, Senpai.");
            Voice_PlayVoice("FD_06_080_00700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nEven if I said I didn't want that to\nhappen, it can't be helped for you,\nSenpai.\nRight?");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Amachi＊＊｝...?)");
            break ;
            case 12:
            Message_Who(0);
            Message_MsgDisp("主人公", "I want to know what I can do to make\nthe other person's heart throb.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_090_00400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nOnly if you tell me how I can get\nrid of this heart throbbing.");
            Character_ChFace(0, 0, 9);
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_090_00500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It seems like things would get\nstrange.\nEach and every time, this kind of...");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Amachi＊＊｝?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_090_00600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... I don't know. I can't answer.");
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_090_00700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nIf it was the me of the past, I may\nhave been able to tell you.");
            Voice_PlayVoice("FD_06_090_00800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Sorry, Senpai.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Amachi＊＊｝...)");
            break ;
            case 13:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder what I should do in order\nto be feminine?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_100_00400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nWill you be using what I say as a\nreference?");
            Voice_PlayVoice("FD_06_100_00500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Is it fine if my definition of\nfemininity is different from the\nperson that Senpai likes?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah, I wanted to try asking.");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_100_00600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... Alright.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_100_00700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Because of that, even if that other\nperson takes no notice of Senpai, I\nwouldn't know.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_100_00800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nEven though I take responsibility\nfor it.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Amachi＊＊｝?)");
            break ;
            case 14:
            Message_Who(0);
            Message_MsgDisp("主人公", "Unrequited love is painful...");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_110_00500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... Yeah.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_110_00600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Especially when you know the other\nperson will not look at you.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you have someone that you like,\n｛Amachi＊＊｝?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_110_00700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "That's.........");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Amachi＊＊｝?");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_110_00800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Don't worry about me.\nAnyway, let's talk about you,\nSenpai!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Amachi＊＊｝...)");
            break ;
            case 16:
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_120_00500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nWhy are you asking about a thing\nlike that?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_120_00600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It has nothing to do with you,\nright?\nWhether I'm in love or not.");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_120_00700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nEven if I was, there isn't anything\nyou can do about it, Senpai.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Nothing I can do...");
            Voice_PlayVoice("FD_06_120_00800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Nothing....\nNothing when you won't give up.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Give up on what?");
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_120_00900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "You don't have to worry.\nIt's impossible, no matter what....\nThis conversation is over.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Amachi＊＊｝...)");
            break ;
            case 17:
            Message_Who(0);
            Message_MsgDisp("主人公", "What is a kiss to you,\n｛Amachi＊＊｝?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_130_00500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... A good memory.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_130_00600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "What do you think, Senpai?");
            Message_Who(0);
            Message_MsgDisp("主人公", "I think the same.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_130_00700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... I see. That's fine.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh? What do you mean by...");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_130_00800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It's fine if you think that way....\nThat's enough.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(... ｛Amachi＊＊｝?)");
            break ;
            case 18:
            Message_Who(0);
            Message_MsgDisp("主人公", "I wonder what I should do so I can\ndo skinship naturally?");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_140_00400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "There are techniques, though...");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_140_00500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "What about a kind of love where you\ndon't make use of that?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh...?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_140_00600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... Sorry.\nIt's not something that I should be\nsaying.");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_140_00700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Anyway, if you're going to touch,\ndon't touch them in places that seem\nlike it'll make them dislike you.");
            Voice_PlayVoice("FD_06_140_00800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "And those places are things that you\nshould learn and discover for\nyourself.");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_140_00900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... That's how it is!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Amachi＊＊｝...)");
            break ;
            case 19:
            Message_Who(0);
            Message_MsgDisp("主人公", "Do you think that friendship between\nmen and women are possible?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(6, 0, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_150_00500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "It would be impossible if the\nbalance was broken.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Balance?");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_150_00600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Yeah.\nThe number of clogs are gradually\nincreasing.");
            Voice_PlayVoice("FD_06_150_00700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "If there are too many clogs, when\nthe balance tilts, we'll be forced\nout of the friendship frame...");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 2);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_150_00800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "......");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(6, 3, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("FD_06_150_00900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "...\nIt would have been better to\nseparate before this happened.\nI can't go back anymore...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Amachi＊＊｝...)");
            break ;
            }
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Music_StopBGM(0, 40);
    }
