section "f03_g3_000"{
    Character_BlinkStart(12, 1, (#1), 1);
    Character_BlinkStart(12, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 0, 0);
    int var0 = 0;
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(12, "G3_03F", 0);
    Background_Bg_GS2("BG_EX000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGB_062_000", 127, 40);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hey, ｛Nishimoto＊＊｝.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("F0312000_L00000", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "What, what?");
    Message_Sele_Kitaku_Kaiwa();
    int var1 = Parameter_Kitaku_Kaiwa(0);
    switch (var1){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of TV shows do you like,\n｛Nishimoto＊＊｝?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0312000_L00100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Eh? Probably comedy shows and stuff.\nI also watch quite a lot of dramas.");
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of dramas?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0312000_L00200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "I was watching it yesterday!\nThe one where the main character\ngets into a traffic accident and\nloses their memory!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, that really deep love drama...");
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0312000_L00300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Yeah, and the two people actually\ndon't know that they're brother and\nsister.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(12, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0312000_L00400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "I just happened to watch it.\nBut for some reason I feel defeated\nwhen watching it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Haha, is that so?");
        Character_BlinkStart(12, 0, (#1), 1);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0312000_L00500", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ah, yeah...\nLately, I've started watching music\nshows, every now and then...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, you watch a variety of shows.\nYou really like TV.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0312000_L00600", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Yeah, I like any kind of interesting\nTV show!");
        Parameter_InCh1Param(12, 530, 35);
        break ;
        case 1:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have favourite foods,\n｛Nishimoto＊＊｝?");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L00700", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Parfait, Jumbo Parfaits!\nThose strawberries.\nThe ones with lots of fresh cream.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Wah, it seems like it's sweet.");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 3);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("F0312000_L00800", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Will you listen to me for a bit?\nI'm really talkative when it comes\nto parfait!");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("F0312000_L00900", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "There are some with cereal at the\nbottom, right?\nThat's heretical!");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(12, 2, (#1), 1);
        Voice_PlayVoice("F0312000_L01000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "The ideal way to do it is to put in\nsome fruits and ice cream, you get\nme?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 2);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L01100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Crap, I really want to eat one\nnow...\nMaybe I should make one when I get\nhome today.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, you make it yourself?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("F0312000_L01200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "When I can't really find a parfait\nthat is like my ideal, isn't it\nfaster if I make it myself?");
        Character_ChFace(0, 2, 3);
        Voice_PlayVoice("F0312000_L01300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "I'll make one for you next time!\nCome over to my place to hang out,\nokay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, thanks!");
        Parameter_InCh1Param(12, 531, 36);
        break ;
        case 2:
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have any sports that you\nlike, ｛Nishimoto＊＊｝?");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0312000_L01400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Yeah, I generally like sports!\nA sport I won't do is probably\nsomething like sumo wrestling,\nperhaps?");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Nishimoto＊＊｝, sumo\nwrestling...");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0312000_L01500", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "You..\nWhat are you thinking about right\nnow...?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0312000_L01600", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "You just made a \"she can probably\nalso do sumo wrestling\" face.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I-I didn't...!");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(12, 3, (#1), 1);
        Voice_PlayVoice("F0312000_L01700", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ahaha, I'm joking!\nYou're a real funny one.");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F0312000_L01800", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "... But think about it a little.\nHey, I won't get angry, so will you\ntry answering honestly...?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Nishimoto＊＊｝, you don't\nlook like you're joking～)");
        Parameter_InCh1Param(12, 532, 37);
        break ;
        case 3:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of music do you like,\n｛Nishimoto＊＊｝?");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("F0312000_L01900", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "W... Why are you asking me that?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, I was just wondering what kind\nof music you listen to.");
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 3, 2);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L02000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Lately......\nI've been listening to\nr-rock............");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, is that so?");
        Character_ChFace(0, 0, 11);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L02100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Um, I'm not deeply interested in it\nor anything...!\nDon't read too much into it.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0312000_L02200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "I listened to it and liked it, so\nall I was doing was trying to dabble\nin it a bit, okay...!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(You don't have to get so flustered.\n｛Nishimoto＊＊｝ is weird...)");
        Parameter_InCh1Param(12, 533, 38);
        break ;
        case 4:
        Message_Who(0);
        Message_MsgDisp("主人公", "What are your hobbies,\n｛Nishimoto＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0312000_L02300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Hobbies? Right, probably travelling.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, so you like travelling.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(12, 2, (#1), 1);
        Voice_PlayVoice("F0312000_L02400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Yeah.\nI've moved a lot, so I have friends\nall over the country!");
        Character_BlinkStart(12, 3, (#1), 1);
        Voice_PlayVoice("F0312000_L02500", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "I look forward to going here and\nthere, and seeing everyone again.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, I'm jealous that you have so\nmany friends.");
        Character_BlinkStart(12, 0, (#1), 1);
        Voice_PlayVoice("F0312000_L02600", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "They're my life's assets!\nOf course, you're included.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Haha, thanks!");
        Parameter_InCh1Param(12, 529, 34);
        break ;
        case 5:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of kid were you in middle\nschool, ｛Nishimoto＊＊｝?");
        Voice_PlayVoice("F0312000_L02700", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Right.\nWhen I was in middle school, I\ntransferred schools twice, because\nof my parent's job.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0312000_L02800", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "But did you know that no matter\nwhere I went, I was popular?\nEven though I'm saying this about\nmyself.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah. I can picture that.");
        Character_BlinkStart(12, 3, (#1), 1);
        Voice_PlayVoice("F0312000_L02900", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "On the first day, I would suddenly\ntalk and bring down everyone!\nEveryone withdrew!");
        Character_BlinkStart(12, 2, (#1), 1);
        Voice_PlayVoice("F0312000_L03000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Even the homeroom teacher had their\nmouth opened and was gaping at me.\nThat was so funny!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Nishimoto＊＊｝ hasn't\nchanged at all!)");
        Parameter_InCh1Param(12, 534, 39);
        break ;
        case 6:
        Message_Who(0);
        Message_MsgDisp("主人公", "Have you decided what you want to be\nin the future,\n｛Nishimoto＊＊｝?");
        Character_ChFace(0, 0, 11);
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L03100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Eh... Hmm...... Generally, I have...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, what kind of dream?");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L03200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "...\nEven if you ask me, it's not\ninteresting and really average,\nokay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I wish you'd tell me.");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(12, 3, (#1), 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L03300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "............ Wife......");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh? I couldn't hear.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0312000_L03400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ah, whatever, it's fine!\nIt's stupid, so let's keep it a\nsecret!\nJust our secret, okay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm... What exactly did she say?)");
        Parameter_InCh1Param(12, 528, 33);
        break ;
        case 7:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of guy do you like,\n｛Nishimoto＊＊｝?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F0312000_L03500", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Aha, what are you saying?\nAll men are unreliable, so I've\nnever thought about it!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Not even once?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L03600", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "...\nN-No, it's impossible, just\nimpossible!\nThat kind of thing is impossible for\nme!");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0312000_L03700", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Don't you think that guys don't see\nme as a girl?\nI get treated like all the other\nguys.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Perhaps ｛Nishimoto＊＊｝\ndoesn't like this kind of subject.)");
        Parameter_InCh1Param(12, 535, 40);
        break ;
        case 8:
        Message_Who(0);
        Message_MsgDisp("主人公", "Hey, ｛Nishimoto＊＊｝.\nDo you have an interest in love?");
        Character_ChFace(0, 0, 11);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L03800", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", ".........! What's wrong with y-you?\nDo you have a fever or something?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I don't. I just wanted to ask.");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L03900", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Uh... Love...\nI'm not that kind of person though.");
        Character_ChFace(0, 0, 3);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L04000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Even when I imagine myself doing\nsomething like that, I start\nlaughing!");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0312000_L04100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Because... it's me, you know?\nL-L-Love and hate... Ahahaha!");
        Character_BlinkStart(12, 2, (#1), 1);
        Voice_PlayVoice("F0312000_L04200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ah, crap!\nThis is too funny, my stomach hurts!\nEveryone will definitely laugh.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Maybe. But...");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F0312000_L04300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "You're thinking too much!\nThis conversation is over!\nLet's talk about something more\ninteresting, okay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm...\nDoes she really not have any\ninterest in it?)");
        Parameter_InCh1Param(12, 536, 41);
        break ;
        case 9:
        Message_Who(0);
        Message_MsgDisp("主人公", "What kind of feeling do you imagine\na kiss to have,\n｛Nishimoto＊＊｝?");
        Character_ChFace(0, 0, 11);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L04400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "K!? ... K-K-K...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Kiss.");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0312000_L04500", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "You, w-w-why do you have such a\nblank look on your face...!?");
        Message_Who(0);
        Message_MsgDisp("主人公", "You don't have to be so flustered...");
        Character_ChFace(0, 0, 8);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L04600", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "You're too indifferent!\nW-What's with you, all of a sudden?\nI don't have an image...\nor anything.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You haven't even thought about it\nonce?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F0312000_L04700", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", ".........");
        Character_ChFace(0, 3, 3);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, you're thinking about it now,\nright?");
        Character_ChFace(0, 7, 0);
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F0312000_L04800", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "W-What are you saying!?\nI'm not thinking about anything!");
        Character_BlinkStart(12, 2, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F0312000_L04900", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "I just think that it would be nice\nif it were romantic...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F0312000_L05000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ah, the parfait has arrived.\nCome on, this stupid conversation is\nover!\nLet's just eat!");
        Parameter_InCh1Param(12, 537, 42);
        break ;
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Music_StopBGM(0, 40);
    Screen_ClearScreen();
    }
