section "f10_m4_206"{
    Character_BlinkStart(4, 1, (#1), 1);
    Character_BlinkStart(4, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    if (Parameter_GetCh1Param(4, 327) == 0){
        Parameter_AddCh1Param(4, 327, 1);
        Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
        Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
        Character_ChFace(0, 0, 0);
        Character_ChFace(0, 3, 5);
        Character_Chara_GS2(4, "M4_01F", 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("", 4, "F1004206_D00000");
        Message_Who(4);
        Message_MsgDisp("Hariya", "｛主人公｝. Yo.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Hariya＊＊｝. Yo.");
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F1004206_D00100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Hey, do you know that Amachi guy?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.\nAh, it seems like he's over there.");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(4, 2, (#1), 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F1004206_D00200", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "...\nThe guy that's surrounded by girls?\nHow conceited... Hey, Amachi!");
        Voice_PlayVoice("F1004206_F00300", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Sorry.\nI am being called, so I will go.");
        Character_ChFace(1, 3, 3);
        Character_Chara_GS2(6, "M6_01F", 0, 0, 1);
        Voice_PlayVoice("F1004206_F00400", 6, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Yes? ... Huh, ｛主人公｝.");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(4, 3, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F1004206_D00500", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "...\nI'm the one who has business with\nyou.\nI got something to ask you.\nWere you just in the music room?--");
        Character_ChFace(1, 0, 11);
        Character_ChFace(1, 3, 5);
        Voice_PlayVoice("F1004206_F00600", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Ah, Hariya-senpai.");
        Character_ChFace(0, 0, 11);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F1004206_D00700", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "You... You know me?");
        Character_ChFace(1, 2, 0);
        Character_BlinkStart(6, 3, (#1), 2);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("F1004206_F00800", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Of course.\nYou're Hanegasaki's famous person.");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1004206_D00900", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "... Really?\nWhat the-- You should have said\nthose things earlier!");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(4, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1004206_D01000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Alright, if you want it that badly,\nI'll give you my autograph!\nCome with me!");
        Character_BlinkStart(4, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1004206_D01100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Anyway, call me \"Harry-senpai\".");
        Voice_PlayVoice("F1004206_F01200", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Yes, Harry-senpai!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(4, "NON");
        Character_Chara_GS2(6, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\n｛Hariya＊＊｝, didn't you\nhave some business with\n｛Amachi＊＊｝?)");
        }
    else if (Parameter_GetCh1Param(4, 327) == 1){
        Parameter_AddCh1Param(4, 327, 1);
        Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Amachi＊＊｝ and\n｛Hariya＊＊｝.)");
        Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(6, "M6_01F", 0, 0, 1);
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 4);
        Character_Chara_GS2(4, "M4_01F", 0);
        Voice_PlayVoice("F1004206_D01300", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Like this? ............\n*Pout*");
        Voice_PlayVoice("F1004206_F01400", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "It's a little different. Like this.");
        Character_ChFace(1, 0, 8);
        Character_BlinkStart(6, 2, (#1), 2);
        Character_ChFace(1, 3, 3);
        System_Wait(30);
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(4, 0, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F1004206_D01500", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Oh, I see! That's how you do it!");
        Character_ChFace(1, 0, 3);
        Character_BlinkStart(6, 0, (#1), 2);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Hariya＊＊｝,\n｛Amachi＊＊｝.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(4, 0, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("", 4, "F1004206_D01600");
        Message_Who(4);
        Message_MsgDisp("Hariya", "｛主人公｝. Yo.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yo. What are you doing?");
        Character_ChFace(0, 0, 3);
        Character_BlinkStart(4, 0, (#1), 1);
        Voice_PlayVoice("F1004206_D01700", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "I'm practicing facial expressions\nthat I can use at live shows.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm... What kind of expressions?");
        Voice_PlayVoice("F1004206_D01800", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "What I'm being taught right now is a\nlittle devil style.");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(4, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1004206_D01900", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "............\n*Pout*");
        Character_ChFace(1, 2, 4);
        Character_BlinkStart(6, 2, (#1), 2);
        Character_BlinkStart(6, 0, (#1), 2);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("F1004206_F02000", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Ah, like that!");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(4, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1004206_D02100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "............\n*Pout*");
        Character_ChFace(1, 2, 0);
        Character_BlinkStart(6, 3, (#1), 2);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("F1004206_F02200", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "As expected, Harry-senpai!\nIt's perfect!");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(4, 2, (#1), 1);
        Character_BlinkStart(4, 0, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1004206_D02300", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Hahaha. I could do this in my sleep!\nAlright, next!");
        Character_ChFace(1, 2, 3);
        Character_BlinkStart(6, 2, (#1), 2);
        Character_BlinkStart(6, 0, (#1), 2);
        Character_ChFace(1, 3, 0);
        Voice_PlayVoice("F1004206_F02400", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "What should we do...?\nWhat about the pesky style then?");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(4, 0, (#1), 1);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F1004206_D02500", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Oh, that'd be good! How does it go?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nDoes he really plan on using them?)");
        Music_StopBGM(0, 40);
        }
    else if (Parameter_GetCh1Param(4, 327) == 2){
        Parameter_AddCh1Param(4, 327, 1);
        Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Hariya＊＊｝ and\n｛Amachi＊＊｝.)");
        Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 4);
        Character_ChFace(1, 4, 1);
        Character_Chara_GS2(6, "M6_01F", 0, 0, 1);
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(4, "M4_01F", 0);
        Voice_PlayVoice("F1004206_F02600", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Harry-senpai, umm...\nPlease keep what we talked about a\nsecret...");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1004206_D02700", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Alright, I don't mind.\nIt's because my cute junior asked me\nto!");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Hariya＊＊｝,\n｛Amachi＊＊｝.");
        Character_ChFace(1, 0, 3);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("", 4, "F1004206_D02800");
        Message_Who(4);
        Message_MsgDisp("Hariya", "｛主人公｝. Yo.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yo. What are you talking about?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1004206_D02900", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "At first I was looking for this guy.\nThat's why I spoke to him.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Well now that you mention it, that\nwould be right.\nWhy were you looking for him?");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1004206_D03000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "I just happened to see him, okay?\nEarlier, in the music room, this\nguy...");
        Character_ChFace(1, 0, 11);
        Character_ChFace(1, 4, 1);
        Voice_PlayVoice("F1004206_F03100", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Harry-senpai!\nDidn't I just tell you to keep it a\nsecret!?");
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F1004206_D03200", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Sorry, right.... Ah.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(4, 2, (#1), 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F1004206_D03300", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Sorry, okay? Forgive me, alright?");
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1004206_D03400", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "... Like this, right?\nThe pesky style expression you\ntaught me.");
        Character_ChFace(1, 2, 2);
        Character_BlinkStart(6, 3, (#1), 2);
        Character_ChFace(1, 3, 1);
        Character_ChFace(1, 4, 0);
        Voice_PlayVoice("F1004206_F03500", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "... As expected, Harry-senpai...\nIt's perfect...");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(4, 2, (#1), 1);
        Voice_PlayVoice("F1004206_D03600", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Hahahahaha, leave it to me!\nAh, and relax.\nI won't ever tell anyone else about\nthat, okay?");
        Character_ChFace(1, 2, 2);
        Character_BlinkStart(6, 0, (#1), 2);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("F1004206_F03700", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Ahaha... Please...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\nCan ｛Hariya＊＊｝ really\nkeep quiet about it?)");
        Music_StopBGM(0, 40);
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    Parameter_AddCh1Param(4, 86, 1);
    }
