section "f10_m5_100"{
    Character_BlinkStart(5, 1, (#1), 1);
    Character_BlinkStart(5, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Character_ChFace(0, 0, 0);
    if (Parameter_GetCh1Param(5, 326) == 0){
        Parameter_AddCh1Param(5, 326, 1);
        Background_Bg_GS2("BG_SC202_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Chris＊＊｝.)");
        Music_PlayBGM(0, "MN_C_05_003_D00", 127, 40);
        Character_Chara_GS2(5, "M5_01F", 0);
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F1005100_E00000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hmm...");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Chris＊＊｝!");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F1005100_E00100", 5, "F1005100_E00101");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ah, ｛主人公｝. Hello.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hello. What's up?\nYou're making a complex face.");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F1005100_E00200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah.\nI was just thinking that since the\nshoe cupboards are plain, I'd add\ncolor to them and make it pretty.");
        Character_BlinkStart(5, 2, (#1), 1);
        Voice_PlayVoice("F1005100_E00300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "But it would be tough with this\nmany, right?\nI was wondering if there was a good\nway to do them all...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you have permission from the\nschool...?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1005100_E00400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I don't.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ahaha, as I thought...\nIf you did that, you know you'd get\nyelled at, right?");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(5, 3, (#1), 1);
        Voice_PlayVoice("F1005100_E00500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hmm...");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1005100_E00600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Then I'll try it on my shoe cupboard\nfirst!");
        Character_BlinkStart(5, 3, (#1), 1);
        Voice_PlayVoice("F1005100_E00700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Then if I get a good response, I'll\ndo the others.\nYeah, I'll do that.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(5, 2, (#1), 1);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F1005100_E00800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Thanks.\nThanks to you, I devised a good\nplan.\nNow then, I'm going to do it!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(5, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(... Thanks to me?)");
        }
    else if (Parameter_GetCh1Param(5, 326) == 1){
        Parameter_AddCh1Param(5, 326, 1);
        Music_PlayBGM(0, "MN_C_05_003_D00", 127, 40);
        Character_Chara_GS2(5, "M5_01F", 0);
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Character_ChFace(0, 0, 0);
        Background_Bg_GS2("BG_SC220_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F1005100_E00900", 5, "F1005100_E00901");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ah, ｛主人公｝. Hello.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝. Hello.\nWhat's up?");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(5, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F1005100_E01000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hehe.\nSomehow, I got a request to power up\nsomeone's shoe cupboard!");
        Character_BlinkStart(5, 2, (#1), 1);
        Voice_PlayVoice("F1005100_E01100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "So I was thinking about going to\npaint it now.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I-Is that so?\nBy the way, the client is...?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1005100_E01200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Waka-chan.\nI'm going to make it so amazing.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(5, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1005100_E01300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Crap, I have to go.\nNow then, I'll see you later.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(5, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝ requested it\nwithout warning him...\nI guess it's something\n｛Wakaouji＊＊｝ would do.)");
        }
    else if (Parameter_GetCh1Param(5, 326) == 2){
        Parameter_AddCh1Param(5, 326, 1);
        Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hm?\nThe person who just came out of the\nguidance counseling room was...)");
        Music_PlayBGM(0, "MN_C_05_003_D00", 127, 40);
        Character_Chara_GS2(5, "M5_01F", 0);
        Voice_PlayVoice("", 5, "F1005100_E01400");
        Message_Who(5);
        Message_MsgDisp("Chris", "｛主人公｝. Hello.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hello... What's up?");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F1005100_E01500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I was scolded by the head teacher\nover the shoe cupboard thing.\nWith Waka-chan as well.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, as well?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F1005100_E01600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah. He's still in there.");
        Message_Who(0);
        Message_MsgDisp("主人公", ".........");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(5, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1005100_E01700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "But you know, the head teacher looks\nlike they also want their shoe\ncupboard painted.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1005100_E01800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Because at the end they said to me\n\"Won't you do mine, too?\nDo it, okay?\"");
        Voice_PlayVoice("F1005100_E01900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "That's what they said.");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1005100_E02000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "It's a technique that Japanese\ncomedians also use when they want\nsomething, right?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1005100_E02100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "That's why I'm going to go do it\nnow.\nI'm going to make it so cute.");
        Voice_PlayVoice("F1005100_E02200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Now then, I'll see you later.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, wait, ｛Chris＊＊｝!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(5, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He left...\n｛Chris＊＊｝ seems like\nhe's going to get scolded more this\ntime...)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    }
