section "f10_m5_204"{
    Character_BlinkStart(5, 1, (#1), 1);
    Character_BlinkStart(5, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC202_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetCh1Param(5, 327) == 0){
        Parameter_AddCh1Param(5, 327, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Chris＊＊｝ and\n｛Hariya＊＊｝.)");
        Music_PlayBGM(0, "MN_C_05_002_D01", 127, 40);
        Character_Chara_GS2(5, "M5_01F", 0, 0, 1);
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 1);
        Character_Chara_GS2(4, "M4_01F", 0);
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F1005204_D00000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "... So call me that next time.\nLater.");
        Character_Chara_GS2(4, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Chris＊＊｝!");
        Character_ChFace(1, 0, 3);
        Voice_PlayVoice("", 5, "F1005204_E00100");
        Message_Who(5);
        Message_MsgDisp("Chris", "｛主人公｝. Hello.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hello.\nWhat were you and\n｛Hariya＊＊｝ talking about?");
        Character_ChFace(1, 2, 0);
        Character_ChFace(1, 3, 2);
        Voice_PlayVoice("F1005204_E00200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah...\nHe said to me \"Call me Harry!\".\nHe said adding \"kun\" was no good.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh... Why?");
        Character_ChFace(1, 0, 9);
        Character_ChFace(1, 3, 4);
        Voice_PlayVoice("F1005204_E00300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "It seems like the nuance is\ndifferent, but I don't quite know\nmyself...\nI guess I'll practice.");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F1005204_E00400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Harry, Harry, Harry...");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(5, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm, will he be able to fix it that\nway...?)");
        }
    else if (Parameter_GetCh1Param(5, 327) == 1){
        Parameter_AddCh1Param(5, 327, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Chris＊＊｝.)");
        Music_PlayBGM(0, "MN_C_05_002_D01", 127, 40);
        Character_Chara_GS2(5, "M5_01F", 0);
        Voice_PlayVoice("", 5, "F1005204_E00500");
        Message_Who(5);
        Message_MsgDisp("Chris", "｛主人公｝. Hello.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hello. So how was it?\nCan you say \"Harry\"?");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(5, 2, (#1), 1);
        Voice_PlayVoice("F1005204_E00600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah... that's...\nIt seems like it will be a problem\nif I said it in front of the actual\nperson...");
        Message_Who(0);
        Message_MsgDisp("主人公", "A problem?\nAh, ｛Hariya＊＊｝.");
        Character_Chara_GS2(4, "M4_01F", 0, 0, 1);
        Voice_PlayVoice("F1005204_D00700", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Yo.");
        Character_ChFace(0, 0, 8);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F1005204_E00800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ha...Harry-k... Harry... Harry!");
        Character_ChFace(1, 2, 4);
        Character_BlinkStart(6, 2, (#1), 2);
        Character_ChFace(1, 3, 2);
        Voice_PlayVoice("F1005204_D00900", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Y-Yo.");
        Voice_PlayVoice("F1005204_E01000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "A...Are you okay?\nWhere are you going?");
        Character_ChFace(1, 0, 9);
        Character_ChFace(1, 3, 4);
        Voice_PlayVoice("F1005204_D01100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "... Huh?");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(5, 2, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F1005204_E01200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I'm going to take a walk.\nNow then, g...good bye. Harry-k...\nH...Harry～");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(5, "NON");
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 0);
        Voice_PlayVoice("F1005204_D01300", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "... What's up with him?\nThat way of speaking makes him seem\nlike that uptight Student Council\nPresident...");
        Voice_PlayVoice("F1005204_D01400", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "And he also said he's going for a\nwalk...\nWhat about class? Ah, I'm scared.");
        Character_Chara_GS2(4, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Chris＊＊｝ was extremely\nnervous...\nThat was definitely a problem.)");
        }
    else if (Parameter_GetCh1Param(5, 327) == 2){
        Parameter_AddCh1Param(5, 327, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, ｛Chris＊＊｝...\nAh, ｛Hariya＊＊｝ is\ncoming!)");
        Music_PlayBGM(0, "MN_C_05_002_D01", 127, 40);
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 2);
        Character_Chara_GS2(5, "M5_01F", 0);
        Character_Chara_GS2(4, "M4_01F", 0, 0, 1);
        Voice_PlayVoice("F1005204_E01500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ha...Hariri.");
        Character_ChFace(1, 2, 1);
        Character_BlinkStart(6, 3, (#1), 2);
        Character_ChFace(1, 3, 4);
        Voice_PlayVoice("F1005204_D01600", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Wait!");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F1005204_E01700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yes!");
        Character_ChFace(1, 0, 3);
        Character_ChFace(1, 3, 2);
        Voice_PlayVoice("F1005204_D01800", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "...\nYou can add the \"kun\" if you want.\nSo lighten up.");
        Character_ChFace(0, 0, 11);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F1005204_E01900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Eh... For real!?");
        Character_ChFace(1, 0, 3);
        Character_ChFace(1, 3, 5);
        Voice_PlayVoice("F1005204_D02000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Yeah.\nAt best, there's no real harm if one\nor two people add \"kun\" to my name.");
        Character_ChFace(1, 0, 8);
        Character_BlinkStart(6, 2, (#1), 2);
        Character_ChFace(1, 3, 2);
        Voice_PlayVoice("F1005204_D02100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Anyway, if you didn't speak Kansai\ndialect, it would be weird....\nI forgive you for what happened\nearlier.");
        Character_ChFace(0, 0, 11);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1005204_E02200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Thanks, Harry-kun...\nYou're really manly!");
        Character_ChFace(1, 0, 10);
        Voice_PlayVoice("F1005204_D02300", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Well, you know! Say more!");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(5, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1005204_E02400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Harry-kun is so cool!");
        Character_ChFace(1, 2, 1);
        Character_BlinkStart(4, 3, (#1), 2);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("F1005204_D02500", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Oh, I'll leave it to you.\nAnyway, me being cool is a given!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Case closed... maybe?)");
        Music_StopBGM(0, 40);
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    Parameter_AddCh1Param(5, 86, 1);
    }
