section "f10_m2_100"{
    Character_BlinkStart(2, 1, (#1), 1);
    Character_BlinkStart(2, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Character_ChFace(0, 0, 0);
    if (Parameter_GetCh1Param(2, 326) == 0){
        Parameter_AddCh1Param(2, 326, 1);
        Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Shiba＊＊｝.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Shiba＊＊｝!\nWhere are you going?");
        Character_Chara_GS2(2, "M2_01F", 0);
        Voice_PlayVoice("F1002100_B00000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "To where I please...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_ChFace(0, 0, 3);
        Character_BlinkStart(2, 2, (#1), 1);
        Voice_PlayVoice("F1002100_B00100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Goodnight.");
        Character_Chara_GS2(2, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(\"Goodnight\"...\nSo is he going somewhere to take a\nnap?)");
        }
    else if (Parameter_GetCh1Param(2, 326) == 1){
        Parameter_AddCh1Param(2, 326, 1);
        Background_Bg_GS2("BG_SC202_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Shiba＊＊｝.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Shiba＊＊｝!");
        Character_Chara_GS2(2, "M2_01F", 0);
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F1002100_B00200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... What?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Where are you going?");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(2, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F1002100_B00300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "In the direction of the wind...");
        Message_Who(0);
        Message_MsgDisp("主人公", "... An afternoon nap?");
        Character_ChFace(0, 0, 3);
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(2, 2, (#1), 1);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F1002100_B00400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Maybe.");
        Character_Chara_GS2(2, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm, what a mystery.)");
        }
    else if (Parameter_GetCh1Param(2, 326) == 2){
        Parameter_AddCh1Param(2, 326, 1);
        Background_Bg_GS2("BG_SC220_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Shiba＊＊｝.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Shiba＊＊｝!\nWhere are you going?\nYou're going to take an afternoon\nnap again, right?");
        Character_Chara_GS2(2, "M2_01F", 0);
        Voice_PlayVoice("F1002100_B00500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Papa is......");
        Voice_PlayVoice("F1002100_B00600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...... At your mercy, Mama.");
        SoundEffect_PlayStream(2, "SE_KOKE");
        Screen_StartShakePlane(0, 32, 32, 0, 32);
        System_Wait(124);
        Message_Who(0);
        Message_MsgDisp("主人公", "!!!");
        Character_ChFace(0, 0, 3);
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(2, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1002100_B00700", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Kidding.");
        Character_Chara_GS2(2, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(A joke from\n｛Shiba＊＊｝...\nThat might be a valuable thing.)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 86, 1);
    }
