section "f10_m1_100"{
    Character_BlinkStart(1, 1, (#1), 1);
    Character_BlinkStart(1, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    if (Parameter_GetCh1Param(1, 326) == 0){
        Parameter_AddCh1Param(1, 326, 1);
        Background_Bg_GS2("BG_SC220_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Saeki＊＊｝.)");
        Music_PlayBGM(0, "MN_C_01_002_D01", 127, 40);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Character_Chara_GS2(1, "M1_01F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝!");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1001100_A00000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Eh!? Ah, sorry!\nI was just on my way--");
        Message_Who(0);
        Message_MsgDisp("主人公", "\"Just on my way\"?\nHuh, did we have some kind of\npromise?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F1001100_A00100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "... It's you.\nWhat a waste of using manners.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You said that in a really\nreprehensible way...\nDo you need something from me?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1001100_A00200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It's nothing. Don't worry. Crap!");
        Voice_PlayVoice("F1001100_W00300", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Ah, I found Saeki-kun!");
        Voice_PlayVoice("F1001100_W00400", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student B", "That's unfair!\nIt's our turn to have lunch with you\ntoday!");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1001100_A00500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Ah, sorry.\nI was just on my way there, really.");
        Voice_PlayVoice("F1001100_W00600", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student B", "Hurry up!");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F1001100_A00700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Now then, I'll be leaving...");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(1, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I see... Being popular is tough.\nBut ｛Saeki＊＊｝ looked\ntired.\nWill he be alright?)");
        }
    else if (Parameter_GetCh1Param(1, 326) == 1){
        Parameter_AddCh1Param(1, 326, 1);
        Background_Bg_GS2("BG_SC220_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Saeki＊＊｝.\nHe's walking around absent-mindedly.\nAlright, I'll get revenge!)");
        Message_Who(0);
        Message_MsgDisp("主人公", "Saeki-kun, you're so mean～!\nIt's my turn to have lunch with you\ntoday!");
        Music_PlayBGM(0, "MN_C_01_002_D01", 127, 40);
        Character_ChFace(0, 0, 10);
        Character_Chara_GS2(1, "M1_01F", 0);
        Voice_PlayVoice("F1001100_A00800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Ah, sorry!\nI was just on my way--");
        Character_ChFace(0, 0, 0);
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(1, 2, (#1), 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F1001100_A00900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", ".........");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, eh... Ehehe!");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(1, 3, (#1), 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F1001100_A01000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Let me hear your explanation.");
        Message_Who(0);
        Message_MsgDisp("主人公", "It was j-just a joke...\nI'm against violence.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(1, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1001100_A01100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Buy me a \"Super Hot Curry Bun\" and\nmilk from the store.\nIt's your turn to have lunch with me\ntoday, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, the money?");
        Character_ChFace(0, 0, 0);
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(1, 2, (#1), 1);
        Voice_PlayVoice("F1001100_A01200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "What did you say?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I'll go and buy it...");
        Music_StopBGM(0, 40);
        }
    else if (Parameter_GetCh1Param(1, 326) == 2){
        Parameter_AddCh1Param(1, 326, 1);
        Background_Bg_GS2("BG_SC220_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, ｛Saeki＊＊｝.\nHe looks somewhat tired...\nI'll refrain from calling out to\nhim.)");
        Music_PlayBGM(0, "MN_C_01_002_D01", 127, 40);
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(1, 2, (#1), 1);
        Character_Chara_GS2(1, "M1_01F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah!");
        Voice_PlayVoice("F1001100_W01300", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student C", "Saeki-kun!\nIt's our turn to have lunch with you\ntoday!");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1001100_A01400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Ah, yeah. The rooftop, right?\nI'll be there soon.");
        Voice_PlayVoice("F1001100_W01500", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student C", "Okay, later!");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(1, 2, (#1), 1);
        Voice_PlayVoice("F1001100_A01600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "... Hmm? Ah, it's you...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hey, ｛Saeki＊＊｝, you\ndon't look so well.\nIf you're tired, why don't you just\nturn them down?");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(1, 3, (#1), 1);
        Voice_PlayVoice("F1001100_A01700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I can't do that.\nIf I turn down one person, it will\nbecome a headache later.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Later?");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F1001100_A01800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "They'll complain, right?\nThey'll ask if I'm going out with\nsomeone, or if I'm ignoring them.\nThat kinda stuff.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I see...");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F1001100_A01900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Hey, you act like a girl every once\nin a while.\nWell done.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm～...\nThat's kind of a weird way of\nexpressing it.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1001100_A02000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I'm complimenting you.\nIf you weren't the way you are, I\nwouldn't be hanging in there.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.\nWell, I'll just leave it at that!\nSee you! Do your best!");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1001100_A02100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Hah... Yeah, I'll do my best.\nNow then, I'll be leaving.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(1, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Saeki＊＊｝, it would be\nnice if you didn't push yourself so\nmuch...)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    }
