section "f10_m6_202"{
    Character_BlinkStart(6, 1, (#1), 1);
    Character_BlinkStart(6, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    if (Parameter_GetCh1Param(6, 327) == 0){
        Parameter_AddCh1Param(6, 327, 1);
        Background_Bg_GS2("BG_SC410_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Amachi＊＊｝ and\n｛Shiba＊＊｝.)");
        Character_ChFace(0, 0, 11);
        Character_ChFace(0, 3, 0);
        Character_Chara_GS2(6, "M6_01F", 0);
        Character_Chara_GS2(2, "M2_01F", 0, 0, 1);
        Voice_PlayVoice("F1006202_F00000", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Ah!");
        Character_BlinkStart(6, 2, (#1), 1);
        Voice_PlayVoice("F1006202_B00100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "............?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(6, 2, (#1), 1);
        Character_ChFace(0, 3, 5);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F1006202_F00200", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "S-Shiba-senpai! You've worked hard!");
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 0);
        Voice_PlayVoice("F1006202_B00300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Sorry.\nI don't remember your name...");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(6, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F1006202_F00400", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Y-Yes! I am Amachi Shota!");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(6, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F1006202_F00500", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Please treat me well!");
        Character_ChFace(1, 0, 9);
        Character_ChFace(1, 3, 4);
        Voice_PlayVoice("F1006202_B00600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Y-Yeah. Nice to meet you...?");
        Voice_PlayVoice("F1006202_F00700", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", ".........");
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 0);
        Voice_PlayVoice("F1006202_B00800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", ".........\nNow then, I'll be leaving...");
        Character_Chara_GS2(2, "NON");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(6, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F1006202_F00900", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "... *Sigh*.");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1006202_F01000", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "...\nI get nervous when he's actually in\nfront of me...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Does ｛Amachi＊＊｝ know\n｛Shiba＊＊｝?)");
        }
    else if (Parameter_GetCh1Param(6, 327) == 1){
        Parameter_AddCh1Param(6, 327, 1);
        Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Amachi＊＊｝ and\n｛Shiba＊＊｝.)");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 4, 1);
        Character_Chara_GS2(6, "M6_01F", 0);
        Character_Chara_GS2(2, "M2_01F", 0, 0, 1);
        Voice_PlayVoice("F1006202_F01100", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Ah!");
        Character_ChFace(1, 2, 0);
        Character_ChFace(1, 3, 4);
        Voice_PlayVoice("F1006202_B01200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Ah.");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 5);
        Character_ChFace(0, 7, 0);
        Voice_PlayVoice("F1006202_F01300", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "S-Shiba-senpai! You've worked hard!");
        Character_ChFace(1, 2, 2);
        Character_BlinkStart(2, 2, (#1), 2);
        Character_ChFace(1, 3, 0);
        Character_ChFace(1, 7, 0);
        Voice_PlayVoice("F1006202_B01400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Yeah. Uhh...");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(6, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F1006202_F01500", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Y-Yes! I am Amachi Shota!");
        Character_ChFace(1, 2, 0);
        Character_ChFace(1, 3, 4);
        Character_BlinkStart(2, 0, (#1), 2);
        Voice_PlayVoice("F1006202_B01600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Right, Amachi. You know me...");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(6, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F1006202_F01700", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Name... you remembered...");
        Character_ChFace(1, 2, 0);
        Character_BlinkStart(2, 2, (#1), 2);
        Character_ChFace(1, 3, 4);
        Voice_PlayVoice("F1006202_B01800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Eh? Y-Yeah.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(6, 2, (#1), 1);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F1006202_F01900", #1, "");
        Message_Who(6);
        Message_MsgDisp("Amachi", "Thank you very much! Alright!");
        SoundEffect_PlayStream(3, "SS_T_00_004_M00");
        Character_Chara_GS2(6, "NON");
        Character_ChFace(1, 0, 11);
        Voice_PlayVoice("F1006202_B02000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Who exactly is he?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Seriously, what is with\n｛Amachi＊＊｝?)");
        }
    else if (Parameter_GetCh1Param(6, 327) == 2){
        Parameter_AddCh1Param(6, 327, 1);
        Background_Bg_GS2("BG_SC420_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        if (Parameter_GetCh1Param(2, 25) == 1){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ah, it's ｛Amachi＊＊｝ and\n｛Shiba＊＊｝.)");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 0);
            Character_ChFace(0, 4, 1);
            Character_Chara_GS2(6, "M6_15F", 0);
            Character_Chara_GS2(2, "M2_15F", 0, 0, 1);
            Voice_PlayVoice("F1006202_F02100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Ah!");
            Voice_PlayVoice("F1006202_B02200", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "Amachi.");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("F1006202_F02300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Y-Yes! I am Amachi Shota!");
            Character_ChFace(1, 2, 3);
            Character_ChFace(1, 3, 5);
            Voice_PlayVoice("F1006202_B02400", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... I know. Do you know me?");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F1006202_F02500", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Y-Yes! Um, I...");
            Character_ChFace(1, 0, 3);
            Voice_PlayVoice("F1006202_F02600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I happened to see one of\nShiba-senpai's baseball matches when\nI was in middle school...");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("F1006202_F02700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Your efforts at that time were\namazing, Shiba-senpai...\nEven now, your eyes are on fire!");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(6, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F1006202_F02800", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "That's why I thought to cheer you on\none day!");
            Character_BlinkStart(6, 0, (#1), 1);
            Voice_PlayVoice("F1006202_F02900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "At practice games and at the\nchampionship games...\nI will cheer you on with all my\nstrength!");
            Character_BlinkStart(6, 3, (#1), 1);
            Voice_PlayVoice("F1006202_F03000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Please treat me well!");
            Character_ChFace(1, 0, 10);
            Character_BlinkStart(2, 2, (#1), 2);
            Character_ChFace(1, 3, 5);
            Voice_PlayVoice("F1006202_B03100", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... Yeah. Same here.");
            Character_ChFace(1, 2, 0);
            Character_ChFace(1, 3, 3);
            Voice_PlayVoice("F1006202_B03200", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "Now then, do your best.");
            Character_ChFace(0, 0, 11);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F1006202_F03300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Y-Yes! Thank you very much!");
            Character_Chara_GS2(2, "NON");
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("F1006202_F03400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... To have Shiba-senpai...\nsay \"do you best\" to me...");
            Voice_PlayVoice("F1006202_W03500", #1, "");
            Message_Who(0);
            Message_Who(6);
            Message_MsgDisp("？？？", "Amachi, what are you doing!?\nWe're in the middle of practice!");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F1006202_F03600", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Yes!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I wonder if ｛Amachi＊＊｝\nadmires ｛Shiba＊＊｝...)");
            }
        else {
            Message_Who(0);
            Message_MsgDisp("主人公", "(Ah, it's ｛Amachi＊＊｝ and\n｛Shiba＊＊｝.)");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 4, 1);
            Character_Chara_GS2(6, "M6_15F", 0);
            Character_Chara_GS2(2, "M2_01F", 0, 0, 1);
            Voice_PlayVoice("F1006202_F03700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Ah!");
            Voice_PlayVoice("F1006202_B03800", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "Amachi.");
            Character_BlinkStart(6, 2, (#1), 1);
            Voice_PlayVoice("F1006202_F03900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Y-Yes. I am Amachi Shota!");
            Character_ChFace(1, 0, 10);
            Character_ChFace(1, 3, 5);
            Voice_PlayVoice("F1006202_B04000", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... I know. Do you know me?");
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("F1006202_F04100", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Y-Yes! Um, I...");
            Character_ChFace(1, 0, 3);
            Voice_PlayVoice("F1006202_F04200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I happened to see one of\nShiba-senpai's baseball matches in\nmiddle school.");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("F1006202_F04300", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Even when you were doing club\nactivities then, and even now, your\neyes are on fire!");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F1006202_F04400", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "I'm glad I could meet you.");
            Character_ChFace(1, 0, 9);
            Character_ChFace(1, 3, 3);
            Voice_PlayVoice("F1006202_B04500", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "... I see. Thanks.");
            Character_ChFace(1, 0, 3);
            Voice_PlayVoice("F1006202_B04600", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "Are you in the Cheer Squad, Amachi?");
            Character_ChFace(0, 0, 11);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F1006202_F04700", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Y-Yes!");
            Character_ChFace(1, 0, 3);
            Character_BlinkStart(2, 2, (#1), 2);
            Character_ChFace(1, 3, 5);
            Voice_PlayVoice("F1006202_B04800", #1, "");
            Message_Who(2);
            Message_MsgDisp("Shiba", "Support becomes the strength of\nathletes....\nEven though practice seems tough, do\nyour best.");
            Voice_PlayVoice("F1006202_F04900", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Y-Yes! Thank you very much!");
            Character_Chara_GS2(2, "NON");
            Character_ChFace(0, 0, 11);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F1006202_F05000", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "... To have Shiba-senpai...\nsay \"do you best\" to me...");
            Voice_PlayVoice("F1006202_W05100", #1, "");
            Message_Who(0);
            Message_Who(6);
            Message_MsgDisp("？？？", "Amachi, what are you doing!?\nWe're in the middle of practice!");
            Character_ChFace(0, 0, 10);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("F1006202_F05200", #1, "");
            Message_Who(6);
            Message_MsgDisp("Amachi", "Yes!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I wonder if ｛Amachi＊＊｝\nadmires ｛Shiba＊＊｝...)");
            }
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(6, 86, 1);
    Parameter_AddCh1Param(6, 86, 1);
    }
