section "f10_g4_100"{
    Character_BlinkStart(13, 1, (#1), 1);
    Character_BlinkStart(13, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    if (Parameter_GetCh1Param(13, 326) == 0){
        Parameter_AddCh1Param(13, 326, 1);
        Background_Bg_GS2("BG_SC400_CO_0", #1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F1013100_M00000", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "I'm sorry.\nIt seems like you've misunderstood.\nI had no intention...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Mizushima＊＊｝....\nHm?)");
        Voice_PlayVoice("F1013100_W00100", #1, "");
        Message_Who(0);
        Message_MsgDisp("Male Student", "N-No way, I was so sure... Waaah!!");
        SoundEffect_PlayStream(3, "SS_T_00_032_M00");
        Music_PlayBGM(0, "MN_C_13_000_D00", 127, 40);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 1);
        Character_Chara_GS2(13, "G4_01F", 0);
        Voice_PlayVoice("", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "What's wrong?\nThat boy just now was crying as he\nran off...");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F1013100_M00200", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Yeah, it's... He confessed.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Did you turn him down?");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F1013100_M00300", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "I did, because it's impossible.\nI haven't even talked to him.");
        Message_Who(0);
        Message_MsgDisp("主人公", "R-Really!?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F1013100_M00400", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "*sigh*...\nI wonder why I get misunderstood.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(13, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(You would if you were as beautiful\nand nice as\n｛Mizushima＊＊｝...)");
        }
    else if (Parameter_GetCh1Param(13, 326) == 1){
        Parameter_AddCh1Param(13, 326, 1);
        Background_Bg_GS2("BG_SC400_CO_0", #1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("F1013100_M00500", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "I'm sorry.\nIt seems like you've misunderstood.\nI had no intention...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Mizushima＊＊｝.\nIs she being...)");
        Voice_PlayVoice("F1013100_W00600", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student", "N-No way, I was so sure...\n*weeps*");
        SoundEffect_PlayStream(3, "SS_T_00_099_M00");
        Music_PlayBGM(0, "MN_C_13_000_D00", 127, 40);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 1);
        Character_Chara_GS2(13, "G4_01F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "W-Was that a girl!?");
        Voice_PlayVoice("", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "What's wrong?\nThe girl just now was crying as she\nran off...");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F1013100_M00700", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Yeah, it's...\nShe asked me to become her older\nsister, but it's impossible...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-You would turn that kind of offer\ndown...\nas expected.");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F1013100_M00800", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "It's because it's impossible.\nI haven't even talked to her enough.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I feel like that's not the issue\nhere...)");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F1013100_M00900", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "*sigh*...\nI wonder why I get misunderstood.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(13, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Guys and even girls.\nEven ｛Mizushima＊＊｝ has it\ntough...)");
        }
    else if (Parameter_GetCh1Param(13, 326) == 2){
        Parameter_AddCh1Param(13, 326, 1);
        Background_Bg_GS2("BG_SC202_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Mizushima＊＊｝....\nHm?)");
        Music_PlayBGM(0, "MN_C_13_000_D00", 127, 40);
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(13, 3, (#1), 1);
        Character_Chara_GS2(13, "G4_01F", 0);
        Voice_PlayVoice("F1013100_M01000", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "*siiigh*...");
        Message_Who(0);
        Message_MsgDisp("主人公", "... What's wrong?\nThat was quite a long sigh.");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(13, 0, (#1), 1);
        Character_ChFace(0, 3, 4);
        Character_ChFace(0, 7, 0);
        Voice_PlayVoice("F1013100_M01100", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "There's another letter in my shoe\nlocker...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, a love letter! ...\nBut I feel that you're quite loved,\n｛Mizushima＊＊｝.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(13, 2, (#1), 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F1013100_M01200", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Yeah...\nBut if I get any more than this, I\nwon't be able to write a response.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Any more than this?");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("F1013100_M01300", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "It's because when I write a\nresponse, they also respond back,\nright?\nI wonder how I should end this...");
        Message_Who(0);
        Message_MsgDisp("主人公", "About how many people are you\nwriting letters to right now?");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(13, 3, (#1), 1);
        Voice_PlayVoice("F1013100_M01400", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "I think 14... or 15 people.\n*siiigh*...");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(13, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I feel like I understand the reason\nwhy ｛Mizushima＊＊｝ is\nmisunderstood...)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(13, 86, 1);
    }
