section "f10_m7_100"{
    Character_BlinkStart(7, 1, (#1), 1);
    Character_BlinkStart(7, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(7, "M7_01F", 0);
    Background_Bg_GS2("BG_SC330_?_0", 1, #1, 0);
    Music_PlayBGM(0, "MN_C_07_003_D00", 127, 40);
    Screen_WipeIn(2);
    if (Parameter_GetCh1Param(7, 326) == 0){
        Parameter_AddCh1Param(7, 326, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Sigh*... Chemistry is hard...)");
        Voice_PlayVoice("F1007100_G00000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Do you understand?\nDNA is base A, G and base T.\nWhen C is connected, the\ndeoxyribonucleotide--");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm～.... This is so confusing.)");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1007100_G00100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "In other words, just like a chain,\nthese two connected cords twist and\nbecome helical--");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I'm getting a little sleepy...)");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("", 7, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-Yes!");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F1007100_G00200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Were you listening to what I was\nsaying?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm... Yes.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1007100_G00300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Then try saying\n\"deoxyribonucleotide\" quickly 10\ntimes.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!?");
        Character_ChFace(0, 0, 3);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1007100_G00400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Now then, quickly.");
        Message_Who(0);
        Message_MsgDisp("主人公", "U-Umm, deoxyribo...");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F1007100_G00500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Wrong. I win this round.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(... \"Win\"?)");
        }
    else if (Parameter_GetCh1Param(7, 326) == 1){
        Parameter_AddCh1Param(7, 326, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Sigh*... Chemistry is hard...)");
        Voice_PlayVoice("F1007100_G00600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "In other words, when you look at\nliquid crystal from a certain angle,\nthe particles all tend one way--");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm～... This is so confusing.)");
        Voice_PlayVoice("F1007100_G00700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "By the way, liquid crystal from\nsquids are cholesteric liquid\ncrystal.\nThese aren't used for TVs, but for\nthermometers.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I'm getting a little sleepy...)");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("", 7, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-Yes!");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("F1007100_G00800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Were you listening to what I was\nsaying?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm... Yes.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1007100_G00900", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Then you should know what my\nfavorite type of squid is, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!? Umm, uh...");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(7, 2, (#1), 1);
        Voice_PlayVoice("F1007100_G01000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Here is a hint.\nIt tastes really nice grilled.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is it... the Pacific flying squid?");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1007100_G01100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Correct. Well done...\nI lose this round.");
        SoundEffect_PlayStream(2, "SE_NS_AL_910_003000");
        Message_Who(0);
        Message_MsgDisp("主人公", "(So I won...)");
        SoundEffect_StopStream(2, 40);
        }
    else if (Parameter_GetCh1Param(7, 326) == 2){
        Parameter_AddCh1Param(7, 326, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Sigh*...\nWhy am I so sleepy in afternoon\nclasses...?)");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("F1007100_G01200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "It seems like back then, they used\nto use a weird pun in order to\nremember this expression.");
        Voice_PlayVoice("F1007100_G01300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "\"Sailor love on my boat.\nHey, turning ship's clerk.\"");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1007100_G01400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "They say \"clerk\".");
        SoundEffect_PlayStream(2, "SE_NS_AL_910_003000");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F1007100_G01500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "It's obvious you'd get sleepy\nlistening to that.\nThey should have figured out whether\nthere was a need to remember this.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("", 7, "F1007100_G01600");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "｛主人公｝.\nDon't you think so?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-Yes!");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("", 7, "F1007100_G01700");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "｛主人公｝.\nWhat do you think of when you hear\nthe words \"sailor\" and \"ships\"?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!? U-Umm... The \"ocean\"?");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1007100_G01800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Yes!\nWho wants to go to the shore to play\ntoday?");
        SoundEffect_PlaySE(906);
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1007100_G01900", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I'll go get permission from the\nclerks, then we'll leave!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Yay!!)");
        SoundEffect_StopStream(2, 40);
        }
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 86, 1);
    }
