section "f10_g1_313"{
    Character_BlinkStart(10, 1, (#1), 1);
    Character_BlinkStart(10, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC410_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Character_ChFace(0, 0, 0);
    if (Parameter_GetCh1Param(10, 327) == 0){
        Parameter_AddCh1Param(10, 327, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, it's ｛Toudou＊＊｝ and\n｛Mizushima＊＊｝.");
        Music_PlayBGM(0, "MN_C_10_000_D02", 127, 40);
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(10, 2, (#1), 1);
        Character_ChFace(0, 3, 0);
        Character_Chara_GS2(10, "G1_01F", 0);
        Character_ChFace(1, 2, 1);
        Character_ChFace(1, 3, 2);
        Character_Chara_GS2(13, "G4_01F", 0, 0, 1);
        Voice_PlayVoice("F1010313_J00000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "... Good grief.\nYou're the candidate for the\nunrivalled, older sister Hisoka,\nright?");
        Voice_PlayVoice("F1010313_M00100", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Tatsuko...\nThat was in the past, wasn't it?\nWill you just forget about it\nalready?");
        Voice_PlayVoice("F1010313_J00200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Even though it's a thing of the past\nfor you, I'm sorry to say this, but\nI'm still unsatisfied.");
        Character_ChFace(1, 2, 1);
        Character_BlinkStart(13, 3, (#1), 2);
        Character_ChFace(1, 3, 4);
        Voice_PlayVoice("F1010313_M00300", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Really...? Then do what you want?");
        SoundEffect_PlayStream(2, "SS_T_00_079_S00");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(10, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F1010313_J00400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I will, if you come near me again.");
        Character_Chara_GS2(10, "NON");
        Character_ChFace(1, 2, 0);
        Character_BlinkStart(13, 2, (#1), 2);
        Character_ChFace(1, 3, 2);
        Voice_PlayVoice("", #1, "F1010313_M00500");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "｛主人公｝, have you been\nstanding there the whole time?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, I...");
        Character_ChFace(1, 0, 10);
        Character_BlinkStart(13, 3, (#1), 2);
        Voice_PlayVoice("F1010313_M00600", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Did you... hear anything?");
        Message_Who(0);
        Message_MsgDisp("主人公", "N-Nothing!");
        Character_ChFace(1, 2, 0);
        Character_BlinkStart(13, 2, (#1), 2);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("F1010313_M00700", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Right. Now, class is starting!\nLet's go!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(13, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It was a strange conversation...)");
        SoundEffect_StopStream(2, 40);
        }
    else if (Parameter_GetCh1Param(10, 327) == 1){
        Parameter_AddCh1Param(10, 327, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, over there is\n｛Toudou＊＊｝ and\n｛Mizushima＊＊｝.\nAre they at it again...?");
        Music_PlayBGM(0, "MN_C_10_000_D02", 127, 40);
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(10, 3, (#1), 1);
        Character_ChFace(0, 3, 2);
        Character_Chara_GS2(10, "G1_01F", 0);
        Character_ChFace(1, 2, 1);
        Character_ChFace(1, 3, 0);
        Character_Chara_GS2(13, "G4_01F", 0, 0, 1);
        Voice_PlayVoice("F1010313_J00800", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "That's why I'm asking if you feel\nlike settling it.\nThat's all I want to know.");
        Voice_PlayVoice("F1010313_M00900", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "You say the same thing all the time.\nIf I said...\nthat I want you to just forget the\npast, what would you do?");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(10, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1010313_J01000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "No matter what you say, I have no\nintention of running away, you know\nthat, don't you?");
        Character_ChFace(1, 2, 1);
        Character_BlinkStart(13, 3, (#1), 2);
        Character_ChFace(1, 3, 2);
        Voice_PlayVoice("F1010313_M01100", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Then wouldn't it be fine if you\ndidn't ask me?");
        SoundEffect_PlayStream(2, "SS_T_00_079_S00");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(10, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1010313_J01200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Hmph. Saved by the bell.\nAs always, you're a lucky one.");
        Character_ChFace(1, 2, 1);
        Character_BlinkStart(13, 2, (#1), 2);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("F1010313_M01300", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "And why do you say that?\nMaybe you're the one with the good\nluck, Tatsuko?");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(10, "NON");
        Character_Chara_GS2(13, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(... I don't like this.\nI wonder if they can just make up\nalready...)");
        SoundEffect_StopStream(2, 40);
        }
    else if (Parameter_GetCh1Param(10, 327) == 2){
        Parameter_AddCh1Param(10, 327, 1);
        Voice_PlayVoice("F1010313_J01400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "What the hell!\nI want a freaking explanation today!");
        Voice_PlayVoice("F1010313_M01500", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Tatsuko! Give me a break!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(!? That voice!!)");
        Music_PlayBGM(0, "MN_C_10_000_D02", 127, 40);
        Character_ChFace(0, 0, 8);
        Character_Chara_GS2(10, "G1_01F", 0);
        Character_ChFace(1, 2, 3);
        Character_ChFace(1, 3, 2);
        Character_Chara_GS2(13, "G4_01F", 0, 0, 1);
        Voice_PlayVoice("", #1, "F1010313_M01600");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "｛主人公｝, what's wrong?\nYou're making that face...");
        Message_Who(0);
        Message_MsgDisp("主人公", "B-Both of you calm down!\nNo violence allowed!");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("F1010313_J01700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Huh? Violence? Between who and whom?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, I mean...\nJust now, ｛Toudou＊＊｝'s\nvoice was...");
        Character_ChFace(1, 2, 4);
        Character_ChFace(1, 3, 0);
        Voice_PlayVoice("F1010313_M01800", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "See! Enough already!\nIt's because Tatsuko has a foul\nmouth!\nIt's alright, okay?\nWe're not fighting or anything.");
        Message_Who(0);
        Message_MsgDisp("主人公", "But just then, I heard you say\nresolve...");
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 3);
        Voice_PlayVoice("F1010313_M01900", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Oh no, you heard?\nIt's embarrassing...");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1010313_J02000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "You know that we're old enough to\nknow not to fight, right?\nI was trying to negotiate a knitting\nshowdown.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Knitting... showdown?");
        Character_ChFace(1, 0, 0);
        Voice_PlayVoice("F1010313_M02100", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Before we did a patchwork showdown.\nBut even though I say showdown, I'm\nalways the one who teaches her.");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F1010313_J02200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "It can't be helped, right?\nI'm an amateur.... So?\nWhat's next after the hook?");
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 4);
        Voice_PlayVoice("F1010313_M02300", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Gee!\nDidn't I teach you that yesterday?\nOkay? At that part...");
        Character_Chara_GS2(13, "NON");
        Character_Chara_GS2(10, "NON");
        Music_StopBGM(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "(... I'm tired.)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(10, 86, 1);
    Parameter_AddCh1Param(10, 86, 1);
    }
