section "f11_m7_100"{
    Character_BlinkStart(7, 1, (#1), 1);
    Character_BlinkStart(7, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC230_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Character_ChFace(0, 0, 0);
    if (Parameter_GetPl1Param(338) == 1){
        Voice_PlayVoice("F1107100_G00000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Please come to Cafe Young Prince.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝! ...\nWhat are you doing?");
        Music_PlayBGM(0, "MN_C_07_003_D00", 127, 40);
        Character_Chara_GS2(7, "M7_17F", 0);
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1107100_G00100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I am handing out flyers.\nPlease come to Cafe Young Prince.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I'm in your class, aren't I,\n｛Wakaouji＊＊｝?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1107100_G00200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That is right. Ahaha!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Haha.\nYou're in a good mood,\n｛Wakaouji＊＊｝.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1107100_G00300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I am.");
        Voice_PlayVoice("F1107100_W00400", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Waka-sama!\nPlease take a photo with me～!");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(7, 3, (#1), 1);
        Voice_PlayVoice("F1107100_G00500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Please take the photo in Cafe Young\nPrince.\nPlease accompany me.");
        Voice_PlayVoice("F1107100_W00600", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Students", "Sure!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(7, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I wonder if he's done this\nbefore...)");
        }
    else if (Parameter_GetPl1Param(338) == 2){
        Voice_PlayVoice("F1107100_G00700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Are you free, young lady?\nLet's dance.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!?");
        Music_PlayBGM(0, "MN_C_07_003_D00", 127, 40);
        Character_Chara_GS2(7, "M7_17F", 0);
        Character_ChFace(0, 0, 10);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...\nWhat are you doing?");
        Voice_PlayVoice("F1107100_G00800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I am getting customers.\nPlease come to Disco Young Prince.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, it kind of\nlooks like you're hitting on people.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1107100_G00900", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That's right.\nBecause you can attract many female\ncustomers by hitting on them.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1107100_G01000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "When you do that, the males will\nalso come, and the disco will\nthrive.\nIt's the \"Great Flirting Plan\".");
        Message_Who(0);
        Message_MsgDisp("主人公", "I see.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1107100_G01100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "So let's dance.");
        Message_Who(0);
        Message_MsgDisp("主人公", ".........");
        Voice_PlayVoice("F1107100_W01200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Waka-sama!\nPlease flirt with me, too～!");
        Voice_PlayVoice("F1107100_G01300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I will flirt! Let's dance.");
        Voice_PlayVoice("F1107100_W01400", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student B", "Me too～! Let's dance～!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(7, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It seems like it's going well.)");
        }
    else if (Parameter_GetPl1Param(338) == 3){
        Voice_PlayVoice("F1107100_G01500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "A play. The play is starting.");
        Message_Who(0);
        Message_MsgDisp("主人公", "!?");
        Music_PlayBGM(0, "MN_C_07_003_D00", 127, 40);
        Character_Chara_GS2(7, "M7_17F", 0);
        Character_ChFace(0, 0, 10);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝.\nAh, are you perhaps getting people--");
        Voice_PlayVoice("F1107100_G01600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "For this year's play.\nThe play is starting.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, it seems it's\nin your character to get customers.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1107100_G01700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Right.\nLately, I've been feeling that\nperhaps I'm more cut out for this\nthan being a teacher.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Haha!\nYou look like you're having fun,\n｛Wakaouji＊＊｝.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1107100_G01800", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I am having fun. A play.");
        Voice_PlayVoice("F1107100_W01900", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Ah, Waka-sama!");
        Voice_PlayVoice("F1107100_W02000", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student B", "You're right!!");
        Voice_PlayVoice("F1107100_G02100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "The play is starting!");
        Voice_PlayVoice("F1107100_W02200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Sensei!\nWill you be appearing in the play?");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1107100_G02300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That is a secret.\nLook forward to watching it.");
        Voice_PlayVoice("F1107100_W02400", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Students", "We'll go and watch it then～!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(7, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝ looks like\nhe's having more fun than the\nstudents.)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 86, 1);
    }
