section "f11_m1_104"{
    Character_BlinkStart(1, 1, (#1), 1);
    Character_BlinkStart(1, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC230_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Character_ChFace(0, 0, 0);
    if (Parameter_GetCh1Param(1, 328) == 0){
        Parameter_AddCh1Param(1, 328, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Saeki＊＊｝.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝!");
        Music_PlayBGM(0, "MN_C_01_003_D00", 127, 40);
        Character_Chara_GS2(1, "M1_01F", 0);
        Voice_PlayVoice("", 1, "F1101104_A00000");
        Message_Who(1);
        Message_MsgDisp("Saeki", "｛主人公｝.\nIt looks like you're working hard.\nLike a Japanese dancing mouse.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Because you're not doing anything...\nHey, if you have the time, come in\nand check out our class display!");
        Character_BlinkStart(1, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1101104_A00100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Ah, right.\nThen I will elegantly look at the--");
        Voice_PlayVoice("F1101104_W00200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Ah! Saeki-kun is over here!");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("F1101104_A00300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Crap... H-Hey!");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1101104_W00400", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Saeki-kun, won't you also take a\nlook at my class?");
        Voice_PlayVoice("F1101104_A00500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Sorry, I'll go there after I take a\nlook around here.");
        Voice_PlayVoice("F1101104_W00600", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student B", "Saeki-kun～! Come to my class too～!");
        Character_BlinkStart(1, 3, (#1), 1);
        Voice_PlayVoice("F1101104_A00700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Yeah, I'll go. I look forward to it.");
        Voice_PlayVoice("F1101104_W00800", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student C", "Eh～! Then what about my class?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(1, 0, (#1), 1);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("F1101104_A00900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "A-Alright. I'll go in order, okay?");
        Voice_PlayVoice("F1101104_W01000", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Hurry, hurry!");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(1, 3, (#1), 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1101104_A01100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Ha-hahaha... I'll see you later.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(1, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He doesn't look very elegant.\nI wonder when he'll be coming to my\nclass...)");
        }
    else if (Parameter_GetCh1Param(1, 328) == 1){
        Parameter_AddCh1Param(1, 328, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Saeki＊＊｝.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝!");
        Music_PlayBGM(0, "MN_C_01_003_D00", 127, 40);
        Character_Chara_GS2(1, "M1_01F", 0);
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("F1101104_A01200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "!!");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("", 1, "F1101104_A01300");
        Message_Who(1);
        Message_MsgDisp("Saeki", "｛主人公｝. It's you...\nDon't scare me.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... What's up?");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(1, 2, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("F1101104_A01400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "This and that...\nIf I'm careless, I'll be caught,\nagain.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That reminds me, last year...\nseemed like it was tough.\nYour fans took you to many places.");
        Character_ChFace(0, 0, 8);
        Character_BlinkStart(1, 3, (#1), 1);
        Voice_PlayVoice("F1101104_A01500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I'm not an idol. Give me a break.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Even though you say that, aren't you\nnot as disgruntled as you make it\nout to be?");
        Character_ChFace(0, 0, 8);
        Character_BlinkStart(1, 2, (#1), 1);
        Voice_PlayVoice("F1101104_A01600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Hey, you...\nIt seems like it's your turn for a\nchop...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Wah, I'm against violence!");
        Voice_PlayVoice("F1101104_W01700", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student A", "Ah! Saeki-kun is over there!");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("F1101104_W01800", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student B", "Ah, you're right!");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("F1101104_A01900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "You lucky one... Remember this!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(1, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He ran away...\nHis last words were like something a\nvillain would say.)");
        }
    else if (Parameter_GetCh1Param(1, 328) == 2){
        Parameter_AddCh1Param(1, 328, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Saeki＊＊｝.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I wonder if he is being chased by\ngirls this year, as well...)");
        Music_PlayBGM(0, "MN_C_01_003_D00", 127, 40);
        Character_Chara_GS2(1, "M1_01F", 0);
        Voice_PlayVoice("", 1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "How is it this year,\n｛Saeki＊＊｝?\nWhere are all your fans?");
        Character_ChFace(0, 0, 3);
        Character_BlinkStart(1, 3, (#1), 1);
        Voice_PlayVoice("F1101104_A02000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Hey, you... I'm fine this year.\nI've got a plan.");
        Message_Who(0);
        Message_MsgDisp("主人公", "A plan?");
        Character_ChFace(1, 0, 8);
        Character_Chara_GS2(4, "M4_01F", 0, 0, 1);
        Voice_PlayVoice("F1101104_D02100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Saeki! Hey you!\nSo you're skipping out and hanging\naround here?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Hariya＊＊｝.");
        Character_ChFace(1, 0, 3);
        Voice_PlayVoice("", 4, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "｛主人公｝.");
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("F1101104_A02200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "My bad, I was just about to go.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah!\nAre you guys doing something\ntogether this year?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1101104_A02300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Yeah, I'm working behind the scenes\nfor his band.\nIf I participate in something, I can\nturn down everyone.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I see...");
        Character_ChFace(1, 2, 0);
        Character_ChFace(1, 3, 2);
        Voice_PlayVoice("F1101104_D02400", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Saeki, they're waiting for you.\nHurry up and go.");
        Character_Chara_GS2(4, "NON");
        Character_ChFace(0, 0, 3);
        Character_BlinkStart(1, 3, (#1), 1);
        Voice_PlayVoice("F1101104_A02500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Hariya is so self-important with\neverything.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(1, "NON");
        Voice_PlayVoice("F1101104_D02600", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "That's not something you can say to\nme.\nAnd call me, \"Harry\".");
        Voice_PlayVoice("F1101104_A02700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "No way.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Haha.\n｛Saeki＊＊｝ looks like\nhe's having quite a lot of fun this\nyear.)");
        Parameter_AddCh1Param(1, 86, 1);
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    }
