section "f11_g2_100"{
    Character_BlinkStart(11, 1, (#1), 1);
    Character_BlinkStart(11, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC230_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetCh1Param(11, 328) == 0){
        Parameter_AddCh1Param(11, 328, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Onoda＊＊｝.)");
        Voice_PlayVoice("F1111100_K00000", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Please take that pipe chair to the\ngymnasium.\nAnd the cardboard to the council\nroom!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(... She seems to be busy.)");
        Music_PlayBGM(0, "MN_C_11_000_D03", 127, 40);
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(11, "G2_01F", 0);
        Voice_PlayVoice("F1111100_K00100", #1, "F1111100_K00101");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Ah, ｛主人公｝. Hello.");
        Voice_PlayVoice("F1111100_W00200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student", "Onoda-san, can I ask you to help me\nout a little?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1111100_K00300", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Ah, yes! ... Sorry.\nI'll see you later!");
        Character_Chara_GS2(11, "NON");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Character_Chara_GS2(11, "G2_01F", 0);
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F1111100_K00400", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Uhh, what were we talking about...?");
        Voice_PlayVoice("F1111100_W00500", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Student", "Onoda-san, where do I take this to?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F1111100_K00600", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "I'm going now!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(11, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(She really is busy.)");
        }
    else if (Parameter_GetCh1Param(11, 328) == 1){
        Parameter_AddCh1Param(11, 328, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Onoda＊＊｝.)");
        Music_PlayBGM(0, "MN_C_11_000_D03", 127, 40);
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(11, "G2_01F", 0);
        Voice_PlayVoice("F1111100_K00700", #1, "F1111100_K00701");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Ah, ｛主人公｝. Hello.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(11, 3, (#1), 1);
        Voice_PlayVoice("F1111100_K00800", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Last year was difficult, but this\nyear, we have it a bit easier...");
        Voice_PlayVoice("F1111100_W00900", #1, "");
        Message_Who(0);
        Message_MsgDisp("Male Student", "Onoda-san, can I leave you to tend\nto the reception desk?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F1111100_K01000", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Ah, yes! ... Sorry.\nI will see you later!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(11, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(She's busy, after all.)");
        }
    else if (Parameter_GetCh1Param(11, 328) == 2){
        Parameter_AddCh1Param(11, 328, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, it's ｛Onoda＊＊｝.)");
        Music_PlayBGM(0, "MN_C_11_000_D03", 127, 40);
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(11, "G2_01F", 0);
        Voice_PlayVoice("F1111100_K01100", #1, "F1111100_K01101");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Ah, ｛主人公｝. Hello.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(11, 2, (#1), 1);
        Voice_PlayVoice("F1111100_K01200", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "This year, I'll relax...");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("F1111100_K01300", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Ah, I told them to move that to the\nentrance!");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("F1111100_K01400", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "... Sorry. I'll see you later!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(11, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Perhaps she likes it when things\nare busy?)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(11, 86, 1);
    }
