section "f12_g2_000"{
    Character_BlinkStart(11, 1, (#1), 1);
    Character_BlinkStart(11, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC212_CO_1", #1, #1, 0);
    Music_PlayBGM(0, "MN_C_11_000_D03", 127, 40);
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(11, "G2_01F", 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("F1211000_K00000", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Let's walk home together!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah!");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(11, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SC000_WI_1", #1, #1, 0);
    Character_Chara_GS2(11, "G2_01F", 0);
    Screen_WipeIn(2);
    if (Parameter_GetCh1Param(11, 315) == 0){
        Parameter_AddCh1Param(11, 315, 1);
        Voice_PlayVoice("F1211000_K00100", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "It's almost Valentine's Day.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Right.\nWill you also be giving chocolates\nto the guys, ｛Onoda＊＊｝?");
        Character_ChFace(0, 0, 3);
        Character_BlinkStart(11, 2, (#1), 1);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("F1211000_K00200", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Right.\nThere is a person I would like to\ngive it to.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, really?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("F1211000_K00300", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "If you don't eat too much of it,\nchocolate is good for your body.\nThey say it used to be medicine, in\nthe past.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh, you know a lot.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Right, it's almost Valentine's\nDay.)");
        }
    else if (Parameter_GetCh1Param(11, 315) == 1){
        Parameter_AddCh1Param(11, 315, 1);
        Voice_PlayVoice("F1211000_K00400", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "It's almost Valentine's Day.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Right.\nAre you going to be giving hand made\nchocolate, ｛Onoda＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1211000_K00500", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Yes.\nIn order to do that, I've been doing\nmuch research.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so.");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1211000_K00600", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Currently, I am researching which\ncocoa beans have the most\npolyphenol.");
        Message_Who(0);
        Message_MsgDisp("主人公", "So you're fussy about that.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Right, it's almost Valentine's\nDay.)");
        }
    else if (Parameter_GetCh1Param(11, 315) == 2){
        Parameter_AddCh1Param(11, 315, 1);
        Voice_PlayVoice("F1211000_K00700", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "It's almost Valentine's Day.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Right.\nAre you going to be making your hand\nmade chocolate this year too?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("F1211000_K00800", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Yes.\nBut this year, I will be more fussy\nabout the design than the\ningredients.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(11, 2, (#1), 1);
        Voice_PlayVoice("F1211000_K00900", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "I want to make amazing chocolate\nthat is fancy, but also has a\nRenaissance feel.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That seems quite difficult.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Right, it's almost Valentine's\nDay.)");
        }
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(11, 86, 1);
    }
