section "s11_m4_000"{
    int var0;
    if (Parameter_GetCh1Param(4, 335) == 0){
        Message_Who(0);
        Message_MsgDisp("主人公", "(I wonder what fortune\n｛Hariya＊＊｝ got?)");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(4, 2, (#1));
        Character_ChFace(0, 4, 1);
        Character_Chara_GS2(4, "M4_??F", 0);
        Voice_PlayVoice("S1104000_D00000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "..............");
        Message_Who(0);
        Message_MsgDisp("主人公", "What's wrong, ｛Hariya＊＊｝?");
        Character_ChFace(0, 4, 0);
        Character_BlinkStart(4, 0, (#1));
        Voice_PlayVoice("S1104000_D00100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "... I'll pull all over, again.\nWait for me, I'll be right back.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh?");
        Character_BlinkStart(4, 2, (#1));
        Voice_PlayVoice("S1104000_D00200", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "I pulled again and it's still no\nuse!");
        Character_ChFace(0, 0, 8);
        Character_BlinkStart(4, 2, (#1));
        Voice_PlayVoice("S1104000_D00300", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Grrr... I give up...!");
        Character_Chara_GS2(4, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "Aaah, ｛Hariya＊＊｝...!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(... Maybe he got bad luck?)");
        }
    else if (Parameter_GetCh1Param(4, 335) == 1){
        Message_Who(0);
        Message_MsgDisp("主人公", "(I wonder what fortune\n｛Hariya＊＊｝ got?)");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 3);
        Character_Chara_GS2(4, "M4_??F", 0);
        Voice_PlayVoice("S1104000_D00400", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Kah..........");
        Message_Who(0);
        Message_MsgDisp("主人公", "Kah?");
        Character_BlinkStart(4, 3, (#1));
        Character_ChFace(0, 3, 5);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("S1104000_D00500", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "...............");
        Message_Who(0);
        Message_MsgDisp("主人公", "What's wrong?");
        Character_ChFace(0, 7, 0);
        Character_BlinkStart(4, 0, (#1));
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("S1104000_D00600", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "W-Whatever!");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(4, 2, (#1));
        Character_ChFace(0, 3, 5);
        Voice_PlayVoice("S1104000_D00700", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "...............");
        Character_ChFace(0, 7, 0);
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("S1104000_D00800", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Okay, I'm gonna end it here and go!\nHey, walk faster!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He smiled...\nDid he get excellent luck this\ntime?)");
        }
    else {
        var0 = System_Randam(0, 100);
        if (var0 <= 50){
            Message_Who(0);
            Message_MsgDisp("主人公", "(I wonder what fortune\n｛Hariya＊＊｝ got?)");
            Character_ChFace(0, 0, 9);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 4, 1);
            Character_Chara_GS2(4, "M4_??F", 0);
            Voice_PlayVoice("S1104000_D00000", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "...........");
            Message_Who(0);
            Message_MsgDisp("主人公", "What's wrong, ｛Hariya＊＊｝?");
            Character_ChFace(0, 4, 0);
            Character_BlinkStart(4, 0, (#1));
            Voice_PlayVoice("S1104000_D00100", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "... I'll pull all over, again.\nWait for me, I'll be right back.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh?");
            Character_BlinkStart(4, 2, (#1));
            Voice_PlayVoice("S1104000_D00200", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "I pulled again and it's still no\nuse!");
            Character_ChFace(0, 0, 8);
            Character_BlinkStart(4, 2, (#1));
            Voice_PlayVoice("S1104000_D00300", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Grrr... I give up...!");
            Character_Chara_GS2(4, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "Aaah, ｛Hariya＊＊｝...!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(... Maybe he got bad luck?)");
            }
        else if (var0 >= 51){
            Message_Who(0);
            Message_MsgDisp("主人公", "(I wonder what fortune\n｛Hariya＊＊｝ got?)");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 3);
            Character_Chara_GS2(4, "M4_??F", 0);
            Voice_PlayVoice("S1104000_D00400", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Kah............");
            Message_Who(0);
            Message_MsgDisp("主人公", "Kah?");
            Character_BlinkStart(4, 3, (#1));
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("S1104000_D00500", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "...............");
            Message_Who(0);
            Message_MsgDisp("主人公", "What's wrong?");
            Character_ChFace(0, 7, 0);
            Character_BlinkStart(4, 0, (#1));
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("S1104000_D00600", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "W-Whatever!");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(4, 2, (#1));
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("S1104000_D00700", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "...............");
            Character_ChFace(0, 7, 0);
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("S1104000_D00800", #1, "");
            Message_Who(4);
            Message_MsgDisp("Hariya", "Okay, I'm gonna end it here and go!\nHey, walk faster!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(He smiled...\nDid he get excellent luck this\ntime?)");
            }
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 335, 1);
    }
