section "t02_m3_230"{
    Background_Bg_GS2("BG_EX110_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("", 3, "");
    Message_Who(3);
    Message_MsgDisp("？？？", "｛主人公｝.");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 1);
    Character_Chara_GS2(3, "M3_01F", 0);
    Music_PlayBGM(0, "MN_C_03_005_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Hikami＊＊｝...");
    Character_ChFace(0, 0, 6);
    Character_BlinkStart(3, 0, (#1));
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("FD_03_230_00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Why are you making that face?\nCould it be...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, things didn't go too well.\nI'm sorry it turned out like this,\neven though you were supporting me.");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(3, 3, (#1));
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("FD_03_230_00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Damn it... As if this could happen!\nI will go and persuade him.");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's fine! Don't do that!");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(3, 0, (#1));
    Voice_PlayVoice("FD_03_230_00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "But you are so...\nAt this rate, I will not be able to\nunderstand.");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's enough already, really.");
    Voice_PlayVoice("FD_03_230_00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "But... I mean...\nThen what should I do...?");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's fine.\nYour sentiment is enough to make me\nhappy.");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(3, 3, (#1));
    Voice_PlayVoice("FD_03_230_00500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I am sorry that it is like this,\neven though I promised you that I\nwould be your power.\nI am powerless.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hikami＊＊｝...");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(3, 0, (#1));
    Voice_PlayVoice("FD_03_230_00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Right, I will write up a report\nabout your good points!\nI can write up many of those\nreports.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay.");
    Character_ChFace(0, 3, 3);
    Character_BlinkStart(3, 0, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("FD_03_230_00700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "It will prove what a wonderful\nperson you are.\nSo do not make that face, okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Okay. Thank you.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_InCh1Param(3, 305, 5);
    System_GlobalWork(3, 0, 39);
    Music_StopBGM(0, 40);
    }
