section "t02_m8_230"{
    Background_Bg_GS2("BG_EX110_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Character_Chara_GS2(8, "M8_06F", 0);
    Music_PlayBGM(0, "MN_C_08_002_D00", 127, 40);
    Voice_PlayVoice("", 8, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah... Masaki-senpai.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(8, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("FD_08_230_00000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Don't force yourself to smile....\nDid he not show up?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yes. I'm sorry, I...");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(8, 3, (#1), 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("FD_08_230_00100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Alright, stop.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(8, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("FD_08_230_00200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "You're the one who worked hard,\nright?");
    Voice_PlayVoice("FD_08_230_00300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I know I should be thanked, but I\ndon't remember you doing anything\nyou need to apologize for.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha. That's certainly true.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Thank you very much for everything.");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(8, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("FD_08_230_00400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "You're welcome....\nI think that things will start from\ntoday.");
    Message_Who(0);
    Message_MsgDisp("主人公", "From today?");
    Voice_PlayVoice("FD_08_230_00500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah.\nIf you ever need my advice on\nanything, just ask me and I'll do\nit, okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Okay!");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(8, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("FD_08_230_00600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Good response. You get a gold star!\n... Congrats on graduating.\nLet's go on another drive.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_InCh1Param(8, 305, 5);
    System_GlobalWork(3, 0, 89);
    Music_StopBGM(0, 40);
    }
