section "t02_g4_000"{
    Background_Bg_GS2("BG_ED010_SP_1", #1, #1, 1);
    System_Wait(1);
    Screen_WipeIn(2);
    Background_Check_BGScroll();
    System_GlobalWork(3, 0, 4);
    Voice_PlayVoice("", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(...?)");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(13, 2, (#1), 1);
    Character_Chara_GS2(13, "G4_01F", 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Mizushima＊＊｝.");
    Voice_PlayVoice("T0213000_M00000", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Congratulations on graduating.");
    Message_Who(0);
    Message_MsgDisp("主人公", "You too, ｛Mizushima＊＊｝.\nCongratulations on graduating.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("T0213000_M00100", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Yeah.... Graduation, huh.\nIt really went by in the blink of an\neye.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Right...\nWhen you think about it, don't you\nfeel like we were always together?");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("T0213000_M00200", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Yeah... but you know.\nI never told you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Never told me?");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(13, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_Chara_GS2(13, "G4_01F", 0);
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(13, 2, (#1));
    Character_ChFace(0, 3, 3);
    Background_Bg_GS2("BG_EX110_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_13_001_D00", 127, 40);
    Voice_PlayVoice("T0213000_M00300", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Do you remember the talk about\nhoroscopes we had when we first met?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I remember.\nIf memory serves, you said that you\nwould meet someone new...");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(13, 2, (#1));
    Voice_PlayVoice("T0213000_M00400", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "It actually said that I would meet a\nlifelong friend who would change me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so...");
    Character_BlinkStart(13, 0, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("T0213000_M00500", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "At first, I wondered what it meant\nby \"change\", but I knew right away.");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("T0213000_M00600", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "I knew that by being with you, I\nwould become a nice person.");
    Character_BlinkStart(13, 0, (#1));
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("T0213000_M00700", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "In the past, I was always worried\nabout how the people around me saw\nme...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("T0213000_M00800", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "But by spending time with you, I\ngradually came to like myself...");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("T0213000_M00900", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Ah, rather than wanting to be a\nperson who is loved by others for my\nlooks...");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(13, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("T0213000_M01000", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "I came to think that I wanted to be\na person whose presence was enjoyed\nby others.");
    Message_Who(0);
    Message_MsgDisp("主人公", "And you, ｛Mizushima＊＊｝.\nYou're a friend that I am proud to\nbe friends with.");
    if (Parameter_GetCh1Param(13, 513) != 2){
        Parameter_InCh1Param(13, 300, 1);
        Character_BlinkStart(13, 2, (#1));
        Voice_PlayVoice("T0213000_M01100", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "... Yeah. Thank you.\nWe'll always be friends, right?");
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("T0213000_M01200", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Is that okay?\nNo matter what kind of people walk\ninto your life, can I be your number\none?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.\nThen will you do the same for me,\n｛Mizushima＊＊｝?");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(13, 3, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("T0213000_M01300", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Hmm～, I wonder...\nAs expected, my future husband will\nbe my number one.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That's unfair!");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(13, 3, (#1));
        Voice_PlayVoice("T0213000_M01400", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Hahaha!");
        }
    else if (Parameter_GetCh1Param(13, 513) == 2){
        Parameter_InCh1Param(13, 300, 2);
        Character_BlinkStart(13, 0, (#1));
        Character_ChFace(0, 4, 0);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("T0213000_M02600", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Hey...\nIt's a good thing that Chris-kun has\nthis kind of happy feeling too,\nright?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Right...");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(13, 3, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("T0213000_M02700", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "No matter how old Chris-kun gets, he\nwill probably always be like an\nangel...");
        Character_BlinkStart(13, 2, (#1));
        Voice_PlayVoice("T0213000_M02800", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "He's a liberal person, bound by\nnothing.\nThat's why all we can do is look at\nhim, from the ground.");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(13, 2, (#1));
        Voice_PlayVoice("T0213000_M02900", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "It was painful to both fall in love\nwith the same person, and to both\nworry.");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("T0213000_M03000", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "We'll be able to make amazing\nmemories together, right?\nWe'll always be friends...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes, surely.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(13, 3, (#1));
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("T0213000_M03100", #1, "");
        Message_Who(13);
        Message_MsgDisp("Mizushima", "Hahaha! Well, first of all...\nlet's go and hang out somewhere!");
        }
    if (Parameter_GetCh1Param(13, 513) != 2){
        }
    else if (Parameter_GetCh1Param(13, 513) == 2){
        }
    Message_CloseMsg();
    Music_StopBGM(0, 60);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(13, 86, 1);
    Parameter_InCh1Param(13, 305, 1);
    }
