section "t02_m7_221"{
    Music_PlayBGM(0, "MN_C_07_090_D00", 127, 40);
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 4, 1);
    Voice_PlayVoice("FD_07_220_00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I thought about it here.\nI always thought about it.\nAbout what I should do to not lose\nyou.");
    Still_StillFace(0, 0, 2);
    Still_StillFace(0, 4, 0);
    Voice_PlayVoice("FD_07_220_00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "For many years, I have avoided\nconcerning myself deeply with\npeople.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Why would you...");
    Still_Pair_Event("EV_07_15", "EV_99_00", 1, 1);
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 4, 1);
    Voice_PlayVoice("FD_07_220_00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I knew too much of the awfulness of\nhumans.\nIf I lost any more faith, my heart\nwould have broken.");
    Voice_PlayVoice("FD_07_220_00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "That is how I thought.");
    Still_Pair_Event("EV_07_14", "EV_99_00", 0, 0);
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("FD_07_220_00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "That is why when you had made clear\nthat you were in love, this is what\nI thought:");
    Voice_PlayVoice("FD_07_220_00700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "\"This girl still believes in love\namongst humans.\nPure, yet idiotic. I pity her\".");
    Message_Who(0);
    Message_MsgDisp("主人公", ".........");
    Voice_PlayVoice("FD_07_220_00800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I prayed that you would not fall in\ndespair like I had.\nNot while I could protect you, at\nleast.");
    Voice_PlayVoice("FD_07_220_00900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "However, I was conceited.\nThere was no need to do that.");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 4, 1);
    Voice_PlayVoice("FD_07_220_01000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Though it hurt and made you worry,\nyou never doubted the value of love.\nAnd I, who had doubted love,");
    Voice_PlayVoice("FD_07_220_01100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "began to like people.\nYou taught me what a beautiful thing\nit is, and that it has value.");
    Still_StillFace(0, 0, 3);
    Still_StillFace(0, 4, 0);
    Voice_PlayVoice("FD_07_220_01200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Though I was supposed to teach you,\nyou had taught me.\nBefore I knew it, I...\nfell in love with you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝.");
    Still_StillFace(0, 0, 6);
    Voice_PlayVoice("FD_07_220_01300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I will understand what you will say.\nEven if your heart belongs to\nsomeone else,");
    Voice_PlayVoice("FD_07_220_01400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I will still confess.");
    Still_Pair_Event("EV_99_00", "EV_07_14", 0, 0);
    Still_StillFace(0, 0, 3);
    Voice_PlayVoice("FD_07_220_01500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I love you.\nI want us to share the joy of\nliving, together.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Me too.\nI want to be with you,\n｛Wakaouji＊＊｝...");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("FD_07_220_01600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "... Thank you.\nMany things will surely happen from\nnow on, but please treat me well.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Me too. I am in your care.");
    Voice_PlayVoice("FD_07_220_01700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Hey, what do you think the\nprincipal, or all of your classmates\nwill say if they knew of this?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Right...\nEveryone will surely be surprised.");
    Voice_PlayVoice("FD_07_220_01800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Right...\nShould we go and surprise them?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? Right now?");
    Still_StillFace(0, 0, 4);
    Voice_PlayVoice("FD_07_220_01900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It was a joke.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Geez.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("EV_07_17", #1, 1, 60);
    Screen_WipeIn(2);
    Voice_PlayVoice("FD_07_220_02000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Let's stay like this a little\nlonger, and listen to the sound of\nthe waves while holding hands.");
    Message_CloseMsg();
    Still_Event("EV_07_17", #1, 0, 60, 0, 1);
    System_Wait(180);
    Screen_WipeOut(3);
    Screen_ClearScreen();
    Music_StopBGM(0, 40);
    Background_Bg_GS2("BG_BK000_CO_0", #1, #1, 0);
    Screen_WipeIn(3);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
