section "t02_m1_230"{
    Background_Bg_GS2("BG_EX110_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("FD_01_230_00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("？？？", "Hey.");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Message_CloseMsg();
    Screen_WipeOut(2);
    SoundEffect_PlayStream(3, "SS_T_00_147_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ouch!");
    Character_Chara_GS2(1, "M1_04F", 0);
    Character_ChFace(0, 0, 6);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_01_001_D01", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝, why are you\nhere...?");
    Voice_PlayVoice("FD_01_230_00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "No reason.... What's with that face?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Even though you were supporting me,\nit seems like things didn't go\nwell...\nSorry.");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(1, 3, (#1), 1);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("FD_01_230_00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Really...? Then I'm glad I came.");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(1, 0, (#1), 1);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("FD_01_230_00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "There's no way a best friend would\nlet you cry alone today, right?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(1, 3, (#1), 1);
    Character_ChFace(0, 3, 2);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("FD_01_230_00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I know that you sometimes faked\nbeing happy.");
    Message_Who(0);
    Message_MsgDisp("主人公", "......");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(1, 0, (#1), 1);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("FD_01_230_00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Relax. I won't tell you to cheer up.\nDon't hold back today, okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Okay.");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(1, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("FD_01_230_00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "That guy's got no idea.\nYou're kinda cute.\nYou're a good person.\nYou're a little slow, though...");
    Voice_PlayVoice("FD_01_230_00700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Well, there may be some rumors going\naround, though.\nIt's the truth.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks...");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(1, 0, (#1), 1);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("FD_01_230_00800", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Alright.\nI'll treat you to some mean coffee\nat the usual cafe.\nLet's go.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_InCh1Param(1, 305, 5);
    System_GlobalWork(3, 0, 19);
    Music_StopBGM(0, 40);
    }
