section "t02_m5_001"{
    Background_Bg_GS2("BG_BK000_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Screen_WipeOut(3);
    Screen_ClearScreen();
    int var0;
    int var1;
    var1 = 0;
    System_GlobalWork(3, 0, 0);
    var0 = 0;
    int var2;
    if (Parameter_GetPl1Param(312) == 5){
        var0 = Parameter_GetCh1Param(5, 301);
        var2 = Parameter_GetCh1Param(5, 307);
        }
    else {
        var0 = Parameter_GetCh1Param(5, 300);
        var2 = Parameter_GetCh1Param(5, 306);
        }
    Message_TextSpeed(8);
    Message_DispMsg(1);
    Background_Bg_GS2("BG_ED000_SP_0", #1, #1, 0);
    Environment_StopME(0, 40);
    if (var2 == 2){
        Voice_PlayVoice("", 5, "");
        Message_Who(5);
        Message_MsgDisp("？？？", "｛主人公｝.");
        Message_CloseMsg();
        Message_MessageWindow(1);
        Message_Text_Color(16);
        Still_Pair_Event("EV_05_17", "EV_99_00", 0, 0);
        Screen_WipeIn(3);
        Music_PlayBGM(0, "MN_C_05_090_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Chris＊＊｝!!\nWhy are you here...?");
        Voice_PlayVoice("T9905000_E00100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I thought that you'd definitely come\nhere, so I waited.");
        Message_Who(0);
        Message_MsgDisp("主人公", "For me...");
        }
    else {
        Message_CloseMsg();
        Message_MessageWindow(1);
        Message_Text_Color(16);
        Still_Pair_Event("EV_05_17", "EV_99_00", 0, 0);
        Screen_WipeIn(3);
        Music_PlayBGM(0, "MN_C_05_090_D00", 127, 40);
        Message_TextSpeed(8);
        Message_DispMsg(1);
        Voice_PlayVoice("", 5, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Chris＊＊｝...!\nWhy are you here?");
        Voice_PlayVoice("T0205000_E00000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I wanted to have a chat with you.\nYou got the time?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.");
        }
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("T0205000_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... We've finally graduated.\nIt still doesn't feel like it...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah...");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("T0205000_E00200", 5, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Hey, ｛主人公｝.");
    Voice_PlayVoice("T0205000_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "When you enrolled in this school,\ndid you have any kind of aims or\nobjectives?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Aims or objectives?");
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("T0205000_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah.");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("T0205000_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nMy aim was to spend my time freely.");
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("T0205000_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "So I can inherit my dad's business,\nI decided that I'd go to uni and\nhelp my dad out with work--");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("T0205000_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "So that's why I wished to spend my 3\nyears at high school freely......");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so...");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("T0205000_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "That's why I made people laugh by\ndoing stupid things or causing a\nruckus, even if I got told off...");
    Still_StillFace(0, 0, 6);
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("T0205000_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nBut thinking about it now, I was\nsurely overdoing it.");
    Still_StillFace(0, 0, 5);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("T0205000_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah, but at those times, I was\ngenuinely laughing, and it was\nreally fun.");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("T0205000_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "But looking back, I was rushing\nthings.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("T0205000_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I kept telling myself \"Do more and\nmore, since I only have 3 years!\".");
    Voice_PlayVoice("T0205000_E01300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I kept telling myself \"If I don't do\nmore and more things, I'll run out\nof time!\".");
    Still_StillFace(0, 0, 6);
    Voice_PlayVoice("T0205000_E01400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nBut that's different to freedom,\nisn't it?");
    Still_StillFace(0, 0, 3);
    Voice_PlayVoice("T0205000_E01500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "You're the one who made me realize\nthat.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...?");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("T0205000_E01600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Of course, it was fun when I bumped\ninto you after school, and we went\nhome together.");
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("T0205000_E01700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "But being able to take it easy and\nfreely...\nIt had been a really long time since\nI had done that.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("T0205000_E01800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "That's how I realized it.");
    Still_StillFace(0, 0, 3);
    Voice_PlayVoice("T0205000_E01900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I realized that even though I had\nplanned to be free, I was actually\npushing myself.");
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("T0205000_E02000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I realized that up until now, I\nhaven't really laughed, from the\nbottom of my heart...");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝...");
    Still_StillFace(0, 0, 1);
    Still_Pair_Event("EV_99_00", "EV_05_17", 0, 0);
    Voice_PlayVoice("T0205000_E02100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I've mistaken the meaning of\n\"freedom\".");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("T0205000_E02200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Next time, I want to enjoy what real\nfreedom is, from the bottom of my\nheart, with you.");
    Still_StillFace(0, 0, 3);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("T0205000_E02300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "So will you...\nbe with me from now on?");
    if ((var0 != 4) && (var0 != 0)){
        if (var0 == 2){
            Still_StillFace(0, 0, 6);
            Voice_PlayVoice("T9905000_E00200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "That's your response?");
            Voice_PlayVoice("T9905000_E00300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... Was that a kiss?");
            Message_Who(0);
            Message_MsgDisp("主人公", "... Yeah.\nI think I was able to express my\nfeelings well.");
            }
        else if (var0 == 3){
            Still_StillFace(0, 0, 6);
            Voice_PlayVoice("T9905000_E00400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Hm... What?");
            Voice_PlayVoice("T9905000_E00500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "When you do that to me, it makes me\nnot wanna let go of you.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... I... always thought about it.\nI've always wanted to express my\nfeelings this way...");
            }
        else {
            Message_Who(0);
            Message_MsgDisp("主人公", "I want to be with you, too.");
            }
        Still_StillFace(0, 0, 4);
        Voice_PlayVoice("T0205000_E02400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... F...for... real...?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.");
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("T0205000_E02500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "...py.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Still_StillFace(0, 0, 3);
        Still_StillFace(0, 6, 0);
        Voice_PlayVoice("T0205000_E02600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... I'm heaps happy.\nI'm really glad.");
        Still_StillFace(0, 0, 0);
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("T0205000_E02700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ah, ignore how slow I was just then,\nokay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Haha, I won't say anything.");
        Still_StillFace(0, 0, 3);
        Still_StillFace(0, 6, 0);
        Voice_PlayVoice("T0205000_E02800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "...\nEven though the future might hold\ntough things.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Tough things?");
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("T0205000_E02900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I mean one day, you might become the\ncompany president's wife...");
        Still_StillFace(0, 6, 0);
        Voice_PlayVoice("T0205000_E03000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "When I ask you, will you say\n\"yes\"...?");
        Message_Who(0);
        Message_MsgDisp("主人公", "............");
        Still_StillFace(0, 0, 4);
        Voice_PlayVoice("T0205000_E03100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... Ah, forget I said that.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Still_StillFace(0, 0, 0);
        Voice_PlayVoice("T0205000_E03200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I'm not even gonna give you a second\nto say \"no\".");
        Still_StillFace(0, 0, 3);
        Voice_PlayVoice("T0205000_E03300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Let's spend each day smiling.\nSo that we can both smile each day,\nI will stay by your side.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Okay.");
        if (var0 != 1){
            Still_StillFace(0, 0, 3);
            Voice_PlayVoice("", 5, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "｛主人公｝.");
            Voice_PlayVoice("T9905000_E00700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I feel like copying you.... Can I?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Copy me?");
            Still_StillFace(0, 6, 1);
            Voice_PlayVoice("T9905000_E00800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Yeah. Words are not enough.");
            Still_StillFace(0, 6, 0);
            Voice_PlayVoice("T9905000_E00900", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "...\nWill you let me express my feelings?");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Chris＊＊｝...");
            }
        else {
            if (Parameter_GetPl1Param(312) == 5){
                Still_StillFace(0, 0, 4);
                Voice_PlayVoice("T0205000_E03400", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "Ah, right.\nI forgot about something important.");
                Message_Who(0);
                Message_MsgDisp("主人公", "What?");
                Still_StillFace(0, 0, 0);
                Voice_PlayVoice("T0205000_E03500", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "I couldn't carry out the promise\nthat I made to you when we first\nkissed.");
                Message_Who(0);
                Message_MsgDisp("主人公", "When we first... Ah!\nSo it was a kiss after all...?");
                Still_StillFace(0, 0, 3);
                Still_StillFace(0, 6, 1);
                Voice_PlayVoice("T0205000_E03600", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "Yeah. Do you remember what I said?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Uhh...");
                Still_StillFace(0, 0, 0);
                Still_StillFace(0, 6, 0);
                Voice_PlayVoice("T0205000_E03700", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "I said that I'll give you the\ngreeting kiss next time.");
                Message_Who(0);
                Message_MsgDisp("主人公", "Ah...");
                Still_StillFace(0, 0, 1);
                Voice_PlayVoice("T0205000_E03800", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "It's not a greeting...\nBut let me carry out this promise.");
                }
            Still_StillFace(0, 0, 1);
            Voice_PlayVoice("T0205000_E03900", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I like you.");
            Still_StillFace(0, 0, 3);
            Voice_PlayVoice("T0205000_E04000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "...\nI'm not gonna let go of you anymore.");
            }
        Music_StopBGM(0, 40);
        if (Parameter_GetPl1Param(312) == 5){
            }
        else {
            }
        Message_CloseMsg();
        Screen_WipeOut(2);
        Still_Event("EV_05_19", #1, 1, 120);
        Screen_WipeIn(2);
        System_Wait(120);
        Still_Event("EV_05_19", #1, 0, 120, 0, 1);
        System_Wait(120);
        Screen_WipeOut(3);
        System_GlobalWork(3, 0, 50);
        }
    else {
        if (Parameter_GetPl1Param(312) == 5){
            var0 = Parameter_GetCh1Param(5, 304);
            }
        else {
            var0 = Parameter_GetCh1Param(5, 303);
            }
        Message_Who(0);
        Message_MsgDisp("主人公", "It's so sudden that I...");
        Still_Pair_Event("EV_99_00", "EV_05_18", 1, 1);
        Voice_PlayVoice("T0205000_E04100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... As I thought, it's no good?");
        Message_Who(0);
        Message_MsgDisp("主人公", ".........");
        Voice_PlayVoice("T0205000_E04200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "So that means... We say goodbye...\nhere...?");
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("T0205000_E04300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... It is no good, after all.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Still_StillFace(0, 0, 1);
        System_Wait(60);
        Still_StillFace(0, 6, 0);
        Voice_PlayVoice("T0205000_E04400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "What I said today...\nI have no intention of saying it to\nanyone else.");
        Still_Pair_Event("EV_99_00", "EV_05_17", 0, 0);
        System_Wait(60);
        Still_StillFace(0, 0, 5);
        Voice_PlayVoice("T0205000_E04500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "So it's not gonna end so soon with a\n\"Yeah, okay\".");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Chris＊＊｝...");
        Still_StillFace(0, 0, 2);
        Voice_PlayVoice("T0205000_E04600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I know what I'm saying is absurd...\nBut I... believe.");
        Still_StillFace(0, 0, 2);
        Voice_PlayVoice("T0205000_E04700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I believe that I definitely won't do\nanything to cloud out that smile of\nyours...");
        if (var0 != 0){
            if (var0 == 2){
                Still_StillFace(0, 0, 6);
                Voice_PlayVoice("T9905000_E00200", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "That's your response?");
                Voice_PlayVoice("T9905000_E00300", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "... Was that a kiss?");
                Message_Who(0);
                Message_MsgDisp("主人公", "... Yeah.\nI think I was able to express my\nfeelings well.");
                }
            else if (var0 == 3){
                Still_StillFace(0, 0, 6);
                Voice_PlayVoice("T9905000_E00400", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "Hm... What?");
                Voice_PlayVoice("T9905000_E00500", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "When you do that to me, it makes me\nnot wanna let go of you.");
                Message_Who(0);
                Message_MsgDisp("主人公", "... I... always thought about it.\nI've always wanted to express my\nfeelings this way...");
                }
            Still_StillFace(0, 0, 4);
            Voice_PlayVoice("T0205000_E04800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... For real?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah.");
            Voice_PlayVoice("T0205000_E04900", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Really, for real?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yeah.\nI believe in you,\n｛Chris＊＊｝.");
            Still_StillFace(0, 0, 1);
            Still_StillFace(0, 6, 1);
            Voice_PlayVoice("T0205000_E05000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "...py.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            Still_StillFace(0, 0, 0);
            Still_StillFace(0, 6, 0);
            Voice_PlayVoice("T0205000_E05100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... I'm heaps happy.\nI'm really glad.");
            Still_StillFace(0, 0, 3);
            Voice_PlayVoice("T0205000_E05200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "If we're together, I feel like we'll\nbe able to overcome anything.");
            Still_StillFace(0, 0, 0);
            Still_StillFace(0, 6, 1);
            Voice_PlayVoice("T0205000_E05300", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Treat me well, okay?\nFuture wife of the company\npresident.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            Still_StillFace(0, 6, 0);
            Voice_PlayVoice("T0205000_E05400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Ah, I'm fine with you being my\nprivate secretary, too.\nEither way, we'll always be able to\nbe together.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Chris＊＊｝.\nWhen you say \"the company\npresident's wife\" and \"private\nsecretary\"...");
            Still_StillFace(0, 0, 2);
            Voice_PlayVoice("T0205000_E05500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... Yeah.");
            Still_StillFace(0, 0, 6);
            Voice_PlayVoice("T0205000_E05600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I'll do my best so that you can be\nhappy when the day comes, so just\nstay by my side and watch me, okay?");
            Message_Who(0);
            Message_MsgDisp("主人公", "... Okay.");
            if (var0 != 1){
                Still_StillFace(0, 0, 3);
                Voice_PlayVoice("", 5, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "｛主人公｝.");
                Voice_PlayVoice("T9905000_E00700", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "I feel like copying you.... Can I?");
                Message_Who(0);
                Message_MsgDisp("主人公", "Copy me?");
                Still_StillFace(0, 6, 1);
                Voice_PlayVoice("T9905000_E00800", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "Yeah. Words are not enough.");
                Still_StillFace(0, 6, 0);
                Voice_PlayVoice("T9905000_E00900", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "...\nWill you let me express my feelings?");
                Message_Who(0);
                Message_MsgDisp("主人公", "｛Chris＊＊｝...");
                }
            else {
                if (Parameter_GetPl1Param(312) == 5){
                    Still_StillFace(0, 0, 0);
                    Voice_PlayVoice("T0205000_E05700", #1, "");
                    Message_Who(5);
                    Message_MsgDisp("Chris", "We've...\nalready done a kiss of allegiance,\nright?\nIt's perfect.");
                    Message_Who(0);
                    Message_MsgDisp("主人公", "Eh?");
                    Still_StillFace(0, 0, 3);
                    Voice_PlayVoice("T0205000_E05800", #1, "");
                    Message_Who(5);
                    Message_MsgDisp("Chris", "But doing it on the forehead hurt a\nlittle.");
                    Message_Who(0);
                    Message_MsgDisp("主人公", "... Ah!\nSo that was a kiss after all...?");
                    Still_StillFace(0, 0, 6);
                    Voice_PlayVoice("T0205000_E05900", #1, "");
                    Message_Who(5);
                    Message_MsgDisp("Chris", "Right, so you didn't realize it...");
                    Message_Who(0);
                    Message_MsgDisp("主人公", "Umm, uhh...");
                    Still_StillFace(0, 0, 0);
                    Voice_PlayVoice("T0205000_E06000", #1, "");
                    Message_Who(5);
                    Message_MsgDisp("Chris", "Then let's settle it.");
                    Message_Who(0);
                    Message_MsgDisp("主人公", "Settle it?");
                    Still_StillFace(0, 6, 1);
                    Voice_PlayVoice("T0205000_E06100", #1, "");
                    Message_Who(5);
                    Message_MsgDisp("Chris", "Yeah.");
                    }
                Still_StillFace(0, 0, 1);
                Still_StillFace(0, 6, 0);
                Voice_PlayVoice("T0205000_E06200", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "I like you.");
                Still_StillFace(0, 0, 3);
                Voice_PlayVoice("T0205000_E06300", #1, "");
                Message_Who(5);
                Message_MsgDisp("Chris", "...\nI'm not gonna let go of you anymore.");
                }
            Music_StopBGM(0, 40);
            if (Parameter_GetPl1Param(312) == 5){
                }
            else {
                }
            Message_CloseMsg();
            Screen_WipeOut(2);
            Still_Event("EV_05_19", #1, 1, 120);
            Screen_WipeIn(2);
            System_Wait(120);
            Still_Event("EV_05_19", #1, 0, 120, 0, 1);
            System_Wait(40);
            Screen_WipeOut(3);
            System_GlobalWork(3, 0, 50);
            }
        else {
            Music_StopBGM(0, 40);
            Still_StillFace(0, 0, 6);
            Still_StillFace(0, 6, 1);
            Voice_PlayVoice("T0205000_E06400", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "......... Okay. I get it.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Chris＊＊｝...");
            Still_StillFace(0, 6, 0);
            Music_PlayBGM(0, "MN_C_05_001_D00", 127, 40);
            Voice_PlayVoice("T0205000_E06500", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Well, it can't be helped.\nEven the gods...");
            Message_Who(0);
            Message_MsgDisp("主人公", ".........");
            Still_StillFace(0, 0, 4);
            Voice_PlayVoice("T0205000_E06600", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Ah, don't make that face!");
            Still_StillFace(0, 0, 2);
            Voice_PlayVoice("T0205000_E06700", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "I...\nI really had fun at Hanegasaki\nAcademy.");
            Still_StillFace(0, 0, 0);
            Voice_PlayVoice("T0205000_E06800", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Being able to meet you, and laughing\nwith you during these 3 years is the\ngreatest treasure.");
            Still_StillFace(0, 0, 3);
            Voice_PlayVoice("T0205000_E06900", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "...\nSo I want to smile at the very end,\ntoo.\nHey, show me that cute face of\nyours▼");
            Message_Who(0);
            Message_MsgDisp("主人公", "Okay.... Okay.\nThank you, ｛Chris＊＊｝.");
            Still_StillFace(0, 6, 1);
            Voice_PlayVoice("T0205000_E07000", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... Yeah.\nI'm heaps satisfied, seeing that\nsmile of yours.");
            Still_StillFace(0, 6, 0);
            Voice_PlayVoice("T0205000_E07100", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "Now then.");
            Still_StillFace(0, 0, 0);
            Still_StillFace(0, 6, 1);
            Voice_PlayVoice("T0205000_E07200", #1, "");
            Message_Who(5);
            Message_MsgDisp("Chris", "... Goodbye.");
            Music_StopBGM(0, 60);
            Message_CloseMsg();
            Screen_WipeOut(3);
            System_GlobalWork(0, 2, 1);
            System_GlobalWork(3, 0, 51);
            }
        }
    Screen_ClearScreen();
    Message_TextSpeed(#1);
    Background_Bg_GS2("BG_BK000_CO_0", #1, #1, 0);
    Screen_WipeIn(3);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
