section "t02_m6_230"{
    Background_Bg_GS2("BG_EX110_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Character_Chara_GS2(6, "M6_01F", 0);
    Music_PlayBGM(0, "MN_C_06_002_D01", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Amachi＊＊｝...");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(6, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("FD_06_230_00000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "...\nAh, what a horrible face you're\nmaking.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sorry.... It was no good.");
    Voice_PlayVoice("FD_06_230_00100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Yeah. That's why I came.");
    Voice_PlayVoice("FD_06_230_00200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "...\nI thought that it'd be bad if you\ncried.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see... Thanks.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(6, 0, (#1), 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("FD_06_230_00300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "...\nGot any plans for what you're gonna\ndo after this?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? Nothing in particular...");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(6, 3, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("FD_06_230_00400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Thank gosh.\nLet's go hang out somewhere!");
    Message_Who(0);
    Message_MsgDisp("主人公", "But... is that okay?");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(6, 0, (#1), 1);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("FD_06_230_00500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "On top of being a good junior, I'm\nyour best friend.\nComforting you is also a part of my\njob.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, right.\nAlright, maybe I should ask you to\ntake me somewhere.");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(6, 3, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("FD_06_230_00600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "It's decided then!\nAlright, it's a race. Ready, go!");
    Character_Chara_GS2(6, "NON");
    SoundEffect_PlayStream(3, "SS_T_00_252_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah!\nThat's cheating,\n｛Amachi＊＊｝!");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_InCh1Param(6, 305, 5);
    System_GlobalWork(3, 0, 69);
    Music_StopBGM(0, 40);
    }
