section "t02_s2_000"{
    System_GlobalWork(3, 0, 15);
    Background_Bg_GS2("BG_EX110_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("T0215000_R00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "How are you?\nI have kept you waiting.\nAs expected, you were here?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... You guys are...");
    Voice_PlayVoice("T0215000_S00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student B", "Just as Himeko-sama said...\nThis is what we have been waiting\nfor, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, what is going on here exactly?");
    Voice_PlayVoice("T0215000RS00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Student A, B", "Let us go!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh, wait...");
    Message_CloseMsg();
    Background_Bg_GS2("BG_EX110_SP_1", #1, #1, 0);
    Background_Bg_GS2("BG_SC411_SP_1", #1, #1, 0);
    Background_Bg_GS2("BG_SC420_SP_1", #1, #1, 0);
    Background_Bg_GS2("BG_SC202_CO_1", #1, #1, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Wahhh!?");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Effect_OpenParticle(0);
    Background_Bg_GS2("BG_SC500_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "*Pant* *Pant*");
    Voice_PlayVoice("T0215000RS00300", #1, "");
    Message_Who(0);
    Message_MsgDisp("Student A, B", "We have brought her!");
    Voice_PlayVoice("T0215000_O00400", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Thank you. You may leave now.");
    Voice_PlayVoice("T0215000RS00500", #1, "");
    Message_Who(0);
    Message_MsgDisp("Student A, B", "Excuse us.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Himeko-senpai!?");
    Effect_OpenParticle(0);
    Effect_EffectParam(200, 10000, 8000, 3000, 2000);
    System_Wait(120);
    Character_Chara_GS2(15, "S2_01F", 0);
    Music_PlayBGM(0, "MN_Z_00_002_D00", 127, 40);
    Effect_EffectParam(30, 2000, 4000, 3000, 2000);
    Voice_PlayVoice("T0215000_O00600", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "How do you do, Daisy?\nThe cherry blossoms that are losing\ntheir petals are beautiful...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uh, rather... What is going on?");
    Voice_PlayVoice("T0215000_O00700", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Daisy... The time has finally come.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Pardon?");
    Voice_PlayVoice("T0215000_O00800", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Daisy.\nWhen I first laid eyes on you, I\nknew that this day would come.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?");
    Voice_PlayVoice("T0215000_O00900", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Daisy, you have followed my commands\nthese three years and have grown to\nbecome an amazing maiden.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm... yes. Thank you very much.");
    Voice_PlayVoice("T0215000_O01000", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "As I had expected, I will let you in\non my secret.\nI am flooded with many emotions\nright now.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(A secret...\nWill she be telling me her age!?)");
    Voice_PlayVoice("T0215000_O01100", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Many Springs have passed since I\ncame to this school...\nI cannot remember how many anymore.");
    Voice_PlayVoice("T0215000_O01200", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "I was young... Just around your age.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uhh, umm...\nThis may be rude, but how old are\nyou, Himeko-senpai?");
    Character_Chara_GS2(15, "NON");
    Character_Chara_GS2(15, "S2_18F", 0);
    Voice_PlayVoice("T0215000_O01300", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Himeko does not have an age.\nHimeko only reflects the heart of a\nmaiden...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, I don't know what you're\ntalking about...");
    Voice_PlayVoice("T0215000_O01400", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "I would wander the school for\neternity, protecting maidens, until\na successor came along...");
    Voice_PlayVoice("T0215000_O01500", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "It was a long time...\nBut the time has finally come.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, Himeko-senpai?");
    Character_Chara_GS2(15, "NON");
    Character_Chara_GS2(15, "S2_01F", 0);
    Voice_PlayVoice("T0215000_O01600", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "I will entrust this key to you.\nIt is the key for the secret maiden\nsociety \"Club Camellia\".");
    Message_Who(0);
    Message_MsgDisp("主人公", "I must decline!\nI only just graduated today--");
    Voice_PlayVoice("T0215000_O01700", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "You will inherit this key and\nprotect the maidens of the school.\nForever... Daisy...");
    Voice_PlayVoice("T0215000_O01800", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "No... Himeko.");
    Message_Who(0);
    Message_MsgDisp("主人公", "No way... \"Himeko\"... I'm Himeko...?");
    Character_Chara_GS2(15, "NON");
    Character_Chara_GS2(15, "S2_19F", 0);
    Effect_EffectParam(200, 10000, 8000, 3000, 2000);
    Voice_PlayVoice("T0215000_O01900", #1, "");
    Message_Who(15);
    Message_MsgDisp("Hanatsubaki", "Nice to meet you, new me.\nNow then... adieu!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(15, "NON");
    System_Wait(60);
    Effect_EffectParam(30, 2000, 4000, 3000, 2000);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Effect_CloseParticle();
    Parameter_InCh1Param(15, 305, 1);
    }
