section "t02_m7_011"{
    Background_Bg_GS2("BG_BK000_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Screen_WipeOut(3);
    Screen_ClearScreen();
    System_GlobalWork(3, 0, 0);
    System_Wait(90);
    Message_CloseMsg();
    Message_MessageWindow(1);
    Message_Text_Color(16);
    Background_Bg_GS2("BG_EX110_SP_1", #1, #1, 0);
    Screen_WipeIn(3);
    Message_TextSpeed(8);
    Message_DispMsg(1);
    if (System_GlobalWork(2, 1) == 1){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Saeki＊＊｝...)");
        }
    else if (System_GlobalWork(2, 1) == 2){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Shiba＊＊｝...)");
        }
    else if (System_GlobalWork(2, 1) == 3){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Hikami＊＊｝...)");
        }
    else if (System_GlobalWork(2, 1) == 4){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Hariya＊＊｝...)");
        }
    else if (System_GlobalWork(2, 1) == 5){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Chris＊＊｝...)");
        }
    else if (System_GlobalWork(2, 1) == 6){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Amachi＊＊｝...)");
        }
    else if (System_GlobalWork(2, 1) == 8){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Masaki＊＊｝...)");
        }
    Message_Who(0);
    Message_MsgDisp("主人公", "(But as expected, I...)");
    Voice_PlayVoice("", 7, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝.");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Character_Chara_GS2(7, "M7_17F", 0);
    Music_PlayBGM(0, "MN_C_07_090_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("T0207010_G00000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Are you taking a walk?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm...\nWhat about you,\n｛Wakaouji＊＊｝?");
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("T0207010_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I am taking a walk.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so......");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("T0207010_G00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It was a lie....\nI was looking for you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝.");
    Voice_PlayVoice("T0207010_G00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "There is something I need to talk to\nyou about...\nRather, there is something that I\nwould like to confirm.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Confirm?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("T0207010_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Yes, before you graduate.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Okay.");
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("T0207010_G00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I have had a unique way with\ncalculations, so I worked at a\nresearch company in America when I\nwas 13.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Then the rumors about you being a\ngenius scientist must be true...");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(7, 0, (#1));
    Voice_PlayVoice("T0207010_G00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Back then, I had thought so too....\nBut thinking about it now, I was\nlike a calculator.");
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("T0207010_G00700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "From morning to night, all I did was\nperform calculations without knowing\nwhat it would be used for.");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(7, 2, (#1));
    Voice_PlayVoice("T0207010_G00800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Before long, a lot of people began\nfighting over this talent...\nI had lost all hope for humanity.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...");
    Character_ChFace(0, 0, 9);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("T0207010_G00900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I quit and returned to Japan, and\nwent from place to place.\nIt was because I was entirely\ndisinterested.");
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("T0207010_G01000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It is because I had thought that if\nI lost any more faith, my heart\nwould break.");
    Message_Who(0);
    Message_MsgDisp("主人公", "No way...");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("T0207010_G01100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Yes, until I came across you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Me?");
    Voice_PlayVoice("T0207010_G01200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Ever since I met you, everything\nbegan to change.\nDo you remember what happened in the\nchemistry room?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm... Yes.");
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("T0207010_G01300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "That was just a coincidence, but I\nget the feeling that it was what\nstarted everything.");
    Character_BlinkStart(7, 0, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("T0207010_G01400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I did not comprehend it at all.\nWhy were you so bothered by such a\ntrivial thing?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Because...");
    Character_BlinkStart(7, 3, (#1));
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("T0207010_G01500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I started thinking about you, and\nwhile being with you, I came to\nunderstand various things.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Various things?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(7, 2, (#1));
    Voice_PlayVoice("T0207010_G01600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Like why many flowers bloom in\nspring.\nEven though they die right away,\npeople still feel joy.");
    Character_BlinkStart(7, 0, (#1));
    Voice_PlayVoice("T0207010_G01700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It is the same thing.\nNo matter how tightly you close your\nheart, you cannot kill the feeling\nof love.");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("T0207010_G01800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "You taught me these obvious things\nand perhaps the importance of them.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("T0207010_G01900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "To me, you are an irreplaceable\nperson.\nI love you.\nI would like to know your feelings.");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("T0207010_G02000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Yes......\nLet us love each other from now on.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.");
    Character_BlinkStart(7, 0, (#1));
    Voice_PlayVoice("", 7, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.");
    Voice_PlayVoice("T0207010_G02100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "There is something I want to confirm\nwith you.\nIs that okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm... What is it?");
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("T0207010_G02200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It might be sudden...\nBut let's kiss.");
    Message_Who(0);
    Message_MsgDisp("主人公", "!?");
    Character_BlinkStart(7, 0, (#1));
    Voice_PlayVoice("T0207010_G02300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I am an adult, and this is what\nadults do.\nDoes is surprise you?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm just...");
    Character_ChFace(0, 0, 3);
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(7, 2, (#1));
    Voice_PlayVoice("T0207010_G02400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Are you nervous? Am I right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yes.");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("T0207010_G02500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Me too. My heart is racing.");
    Message_Who(0);
    Message_MsgDisp("主人公", "You too, ｛Wakaouji＊＊｝?");
    Character_ChFace(0, 0, 6);
    Character_BlinkStart(7, 2, (#1));
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("T0207010_G02600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Of course.\nBut it is a very blissful feeling.\nHow do you feel?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I feel the same...");
    Character_BlinkStart(7, 3, (#1));
    Voice_PlayVoice("T0207010_G02700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Thank goodness.");
    Character_BlinkStart(7, 0, (#1));
    Voice_PlayVoice("T0207010_G02800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "This will be our second time, but it\nis the first kiss we share as people\nwho have fallen in love...");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("EV_07_21", #1, 0, 60);
    Screen_WipeIn(2);
    System_Wait(120);
    Still_Event("EV_07_21", #1, 1, 60, 0, 1);
    System_Wait(120);
    Screen_WipeOut(3);
    Character_Chara_GS2(7, "NON");
    System_GlobalWork(3, 0, 70);
    Screen_ClearScreen();
    Message_TextSpeed(#1);
    Background_Bg_GS2("BG_BK000_CO_0", #1, #1, 0);
    Screen_WipeIn(3);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
