section "t02_m4_230"{
    Background_Bg_GS2("BG_EX110_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(4, 0, (#1), 1);
    Character_ChFace(0, 3, 0);
    Character_ChFace(0, 4, 0);
    Character_Chara_GS2(4, "M4_01F");
    Music_PlayBGM(0, "MN_C_04_002_D00", 127, 40);
    Voice_PlayVoice("FD_04_230_00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yo.......");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝....\nYou didn't hear?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(4, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("FD_04_230_00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It's not like I didn't hear.\nWith the face you're making, it's\nlike it's the end of the world.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see....\nSorry, even though I had you give me\nlots of advice, it didn't work\nout...");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(4, 3, (#1), 1);
    Character_ChFace(0, 3, 2);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("FD_04_230_00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Well. You're awfully accepting.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(4, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("FD_04_230_00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It's fine to struggle a little.");
    Voice_PlayVoice("FD_04_230_00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It doesn't really mean the world is\nover.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝...");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(4, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("FD_04_230_00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Well, I'll forgive you today.\nSo in exchange, treat me to\nsomething.");
    Message_Who(0);
    Message_MsgDisp("主人公", "M-Me!?");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(4, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("FD_04_230_00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It's the consultation fee.\nYou're gonna treat me to something.");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(4, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("FD_04_230_00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "And a fee for working hard...\nAnd a fee for the future, too.");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(4, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("FD_04_230_00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Alright, let's go!");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Okay!");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_InCh1Param(4, 305, 5);
    System_GlobalWork(3, 0, 49);
    Music_StopBGM(0, 40);
    }
