section "t02_m1_221"{
    Music_PlayBGM(0, "MN_C_01_090_D00", 127, 40);
    Still_StillFace(0, 0, 6);
    Voice_PlayVoice("FD_01_220_00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I... had run away from this place.\nI thought that if I left, I'd\nforget.");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("FD_01_220_00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "About Sangosho... and about you.\nI thought that I could no longer get\nwhat I wanted.");
    Message_Who(0);
    Message_MsgDisp("主人公", "......");
    Still_StillFace(0, 0, 3);
    Voice_PlayVoice("FD_01_220_00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "At first, I thought it was nothing.\nI would talk about Sangosho, and you\nwould talk about him.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("FD_01_220_00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Even so... Something had changed.");
    Still_StillFace(0, 6, 0);
    Still_StillFace(0, 0, 6);
    Voice_PlayVoice("FD_01_220_00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It was really painful seeing your\ngloomy face.");
    Voice_PlayVoice("FD_01_220_00700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It was also painful seeing you\nhappily talk about the guy you\nliked...");
    Voice_PlayVoice("FD_01_220_00800", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Above all, the most unbearable thing\nwas lying to you.");
    Still_StillFace(0, 6, 1);
    Still_StillFace(0, 0, 4);
    Voice_PlayVoice("FD_01_220_00900", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "So I ran away.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝...");
    Still_StillFace(0, 6, 2);
    Still_StillFace(0, 0, 6);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("FD_01_220_01000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "But it was a mistake.\nJust leaving was even more\npainful...");
    Still_StillFace(0, 0, 4);
    Voice_PlayVoice("FD_01_220_01100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I thought about you a lot, and\nnothing could be done about it...\nAt this rate, nothing will ever\nhappen.");
    Voice_PlayVoice("FD_01_220_01200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "That's why I've come back.\nI won't run away or give up anymore.\nI've decided to get what I want.");
    Still_Pair_Event("EV_99_00", "EV_01_18", 0, 0);
    Still_StillFace(0, 0, 4);
    Voice_PlayVoice("FD_01_220_01300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I like you.\nI don't want anyone else to have\nyou.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm glad...\nbecause I also like you,\n｛Saeki＊＊｝.");
    Still_StillFace(0, 0, 6);
    Voice_PlayVoice("FD_01_220_01400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Really... But since when...");
    Message_Who(0);
    Message_MsgDisp("主人公", "I don't know for sure, but it was\nsurely when you started liking me,\ntoo.");
    Still_StillFace(0, 0, 4);
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("FD_01_220_01500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I see...\nNo, I definitely liked you first.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Why?");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 3);
    Voice_PlayVoice("FD_01_220_01600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Wanna know?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah.");
    Voice_PlayVoice("FD_01_220_01700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Then I'll tell you.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("EV_01_21", #1, 1, 60);
    Screen_WipeIn(2);
    Voice_PlayVoice("FD_01_220_01800", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Once upon a time, a young man lived\nin a village by the sea.\nOne morning, he met a beautiful\nmermaid.");
    Message_CloseMsg();
    System_Wait(20);
    Still_Event("EV_01_21", #1, 0, 60, 0, 1);
    System_Wait(180);
    Message_CloseMsg();
    Screen_WipeOut(3);
    Screen_ClearScreen();
    Music_StopBGM(0, 40);
    Background_Bg_GS2("BG_BK000_CO_0", #1, #1, 0);
    Screen_WipeIn(3);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
