section "t02_mb_001"{
    Message_TextSpeed(10);
    Message_DispMsg(1);
    Background_Bg_GS2("BG_BK000_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Screen_WipeOut(3);
    Screen_ClearScreen();
    Message_CloseMsg();
    Message_MessageWindow(1);
    Message_Text_Color(16);
    if (Parameter_GetCh1Param(26, 300) == 1){
        Still_Pair_Event("EV_92_02", "EV_99_00", 0, 0);
        Music_PlayBGM(0, "MN_Z_00_002_D00", 127, 40);
        Screen_WipeIn(3);
        Message_Who(0);
        Message_MsgDisp("主人公", "Tarou-kun...");
        Still_StillFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_17300", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "What a relief...\nI thought that I'd surely be able to\nsee you if I came here.");
        Still_StillFace(0, 0, 3);
        Voice_PlayVoice("NS_92_000_17400", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "It might be a bit long, and you\nmight end up hating me even more for\nit...");
        Still_StillFace(0, 0, 1);
        Voice_PlayVoice("NS_92_000_17500", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "But I was thinking of saying\neverything that's on my mind.\nSo please, I want you to listen.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Okay.");
        }
    else {
        Still_Pair_Event("EV_92_02", "EV_99_00", 0, 0);
        Music_PlayBGM(0, "MN_Z_00_002_D00", 127, 40);
        Screen_WipeIn(3);
        Message_Who(0);
        Message_MsgDisp("主人公", "Tarou-kun...");
        Voice_PlayVoice("NS_92_000_17600", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "One day, I thought I heard your\nvoice amongst a crowd of people...");
        Voice_PlayVoice("NS_92_000_17700", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I couldn't forget that voice...");
        Message_Who(0);
        Message_MsgDisp("主人公", "I've always wanted to have a proper\ntalk with you, Tarou-kun.\nAlways....");
        Still_StillFace(0, 0, 3);
        Voice_PlayVoice("NS_92_000_17800", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "You will hate me even more after\nthis...\nBut I have to say it.");
        Still_StillFace(0, 0, 1);
        Voice_PlayVoice("NS_92_000_17900", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I have to say it, so I will say\nwhat's on my mind.");
        }
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("NS_92_000_18000", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Do you remember when we first met?\nIt was when I was in 2nd year, the\nday of the graduation ceremony.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah.");
    Still_Pair_Event("EV_92_03", "EV_99_00", 1, 1);
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("NS_92_000_18100", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "On that day, one year earlier, I had\nbeen rejected for the very first\ntime.");
    Voice_PlayVoice("NS_92_000_18200", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "That person was a 3rd year, and was\nloved by many guys...\nI was ecstatic that I was chosen by\nher.");
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("NS_92_000_18300", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "That girl demanded many things from\nme.\nLike my hair style, my clothing, and\neven the way I spoke.");
    Voice_PlayVoice("NS_92_000_18400", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "It seemed like she would hate me if\nI objected, so I did as she said.\nThen one year later...");
    Still_StillFace(0, 0, 3);
    Voice_PlayVoice("NS_92_000_18500", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "She simply said to me \"Since I'm\ngraduating, let's break up\".");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so...");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("NS_92_000_18600", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "The idiotic me finally understood\nthat this was just a game.");
    Voice_PlayVoice("NS_92_000_18700", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "You lose if you become serious.\nLosers are idiots.\nI thought that I should just win\nnext time...");
    Still_Pair_Event("EV_92_02", "EV_99_00", 0, 0);
    Still_StillFace(0, 0, 3);
    Voice_PlayVoice("NS_92_000_18800", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "That's why I played every kind of\ngame.\nAs the girls fell for me, I\ndeveloped a superiority complex.");
    Still_StillFace(0, 0, 5);
    Voice_PlayVoice("NS_92_000_18900", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Even so, only you...");
    Still_Pair_Event("EV_92_03", "EV_99_00", 1, 1);
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("NS_92_000_19000", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Every time I did awful things to\nyou, it felt like a piece of my\nheart was being ripped off.");
    Voice_PlayVoice("NS_92_000_19100", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "It was painful...\nSo I thought that I should just make\nyou someone else's.");
    Voice_PlayVoice("NS_92_000_19200", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "It was something that couldn't be\nundone...");
    Message_Who(0);
    Message_MsgDisp("主人公", "But you saved me.... Why?");
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("NS_92_000_19300", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "When I saw that you were scared...\nI couldn't stand by and do nothing.");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("NS_92_000_19400", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "And you loved me, even though I was\nsuch an awful person.\nI cried...");
    Voice_PlayVoice("NS_92_000_19500", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "When you looked at me, I knew just\nwhat kind of a foul person I was.");
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("NS_92_000_19600", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "It was my first time knowing what\nlove was.");
    Still_Pair_Event("EV_92_02", "EV_99_00", 0, 0);
    Still_StillFace(0, 0, 5);
    Voice_PlayVoice("NS_92_000_19700", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "I don't mind if you throw all sorts\nof insults at me.\nI don't mind, so...");
    Still_Pair_Event("EV_99_00", "EV_92_02", 0, 0);
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("NS_92_000_19800", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "I want to do things from the start,\nand fall in love with you again.");
    switch (Parameter_GetCh1Param(26, 301)){
        case 1:
        Message_Who(0);
        Message_MsgDisp("主人公", "I want to start over again with you.");
        Still_StillFace(0, 0, 2);
        Voice_PlayVoice("NS_92_000_19900", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "With me... Thank you.");
        Still_StillFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_20000", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Since you are willing to love me, I\nwill become a man that won't bring\nany shame to you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I'll try to become a bit more mature\nso that I'll suit you, Tarou-kun...");
        Still_StillFace(0, 0, 2);
        Voice_PlayVoice("NS_92_000_20100", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Didn't I say it before?\nI'm fine with you. It has to be you.\nI don't need anything else from you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Tarou-kun...");
        Still_StillFace(0, 0, 2);
        Voice_PlayVoice("NS_92_000_20200", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I love you.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Still_Event("EV_92_04", #1, 1, 120);
        Music_StopBGM(0, 40);
        Screen_WipeIn(2);
        System_Wait(120);
        Still_Event("EV_92_04", #1, 0, 120, 0, 1);
        System_Wait(120);
        Screen_WipeOut(3);
        break ;
        case 2:
        Still_StillFace(0, 0, 4);
        Voice_PlayVoice("NS_92_000_20700", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I thought...\nthat my heart would stop.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I feel the same as you, Tarou-kun.\nLet's start again.");
        Still_StillFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_20800", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Yes... Thank you. Hey.");
        Message_Who(0);
        Message_MsgDisp("主人公", "What?");
        Still_StillFace(0, 0, 2);
        Voice_PlayVoice("NS_92_000_20900", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "When you met me, I was only full of\nlies, but only one thing was true.");
        Voice_PlayVoice("NS_92_000_21000", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Whenever you looked at me, my heart\nhurt.\nIt's been like that ever since I met\nyou.");
        Still_StillFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_21100", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I surely wanted to do this, ever\nsince that time...\nI love you.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Screen_ClearScreen();
        Still_Event("EV_92_04", #1, 1, 120);
        Screen_WipeIn(2);
        Music_StopBGM(0, 40);
        System_Wait(120);
        Still_Event("EV_92_04", #1, 0, 120, 0, 1);
        System_Wait(120);
        Screen_WipeOut(3);
        break ;
        }
    Screen_ClearScreen();
    Background_Bg_GS2("BG_BK000_CO_0", #1, #1, 0);
    Screen_WipeIn(3);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
