section "t02_m4_010"{
    System_GlobalWork(3, 0, 0);
    System_Wait(90);
    Message_CloseMsg();
    Message_MessageWindow(1);
    Message_Text_Color(16);
    Background_Bg_GS2("BG_EX110_SP_1", #1, #1, 0);
    Screen_WipeIn(3);
    Message_TextSpeed(8);
    Message_DispMsg(1);
    if (System_GlobalWork(2, 1) == 1){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Saeki＊＊｝.)");
        }
    else if (System_GlobalWork(2, 1) == 2){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Shiba＊＊｝.)");
        }
    else if (System_GlobalWork(2, 1) == 3){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Hikami＊＊｝.)");
        }
    else if (System_GlobalWork(2, 1) == 5){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Chris＊＊｝.)");
        }
    else if (System_GlobalWork(2, 1) == 6){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Amachi＊＊｝.)");
        }
    else if (System_GlobalWork(2, 1) == 7){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Wakaouji＊＊｝.)");
        }
    else if (System_GlobalWork(2, 1) == 8){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Sorry, ｛Masaki＊＊｝.)");
        }
    Message_Who(0);
    Message_MsgDisp("主人公", "(But as expected, I...)");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(4, 2, (#1), 1);
    Character_ChFace(0, 3, 1);
    Character_ChFace(0, 4, 0);
    Character_Chara_GS2(4, "M4_01F", 0);
    Music_PlayBGM(0, "MN_C_04_091_D00", 127, 40);
    Voice_PlayVoice("", 4, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝. What's up?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(4, 0, (#1));
    Character_ChFace(0, 3, 5);
    Character_ChFace(0, 7, 0);
    Voice_PlayVoice("T0204010_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Yo.");
    Character_ChFace(0, 2, 3);
    Voice_PlayVoice("T0204010_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I wanted... to have a chat with you.");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(4, 2, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("T0204010_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "So I followed you here.\nYou got time?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yeah.");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(4, 0, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("T0204010_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Umm............");
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("T0204010_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Right after we met each other, we...\nbumped into each other and kissed,\nright?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah! ...... Yeah.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(4, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("T0204010_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Somehow...\nIt was so freaking embarrassing,\njust like some boring drama, so...");
    Voice_PlayVoice("T0204010_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I had also thought to turn that\nexperience into a song.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(4, 0, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("T0204010_D00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "But you know, I was really worried\nabout it, so I couldn't write a\nsong.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("T0204010_D00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nThat's why I told you that you could\nboast about it.");
    Message_Who(0);
    Message_MsgDisp("主人公", ".........");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(4, 3, (#1));
    Character_ChFace(0, 3, 2);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("T0204010_D00900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "If you had told someone...\nand if it became a big deal, I\nwould've turned it into a song for\nyou.");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("T0204010_D01000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "But you didn't say a word about it,\ndid you?");
    Character_ChFace(0, 0, 6);
    Character_BlinkStart(4, 2, (#1));
    Voice_PlayVoice("T0204010_D01100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I couldn't tell anyone else, either.\nI didn't wanna tell anyone, I...\nwanted it to be my treasure.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝...");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(4, 0, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("T0204010_D01200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "So that's why, if you...\nperhaps think the same way I do,\nthen--");
    Character_BlinkStart(4, 2, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("T0204010_D01300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Be my girlfriend.");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("T0204010_D01400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "You're the only one for me.");
    Character_ChFace(0, 0, 6);
    Voice_PlayVoice("T0204010_D01500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I... like you!");
    System_Wait(#60);
    Message_MsgSel("Me too...!", "Sorry...");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "I like you too,\n｛Hariya＊＊｝...");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("T0204010_D01600", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Meaning... You're... okay with it?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Only if you're fine with me.");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("T0204010_D01700", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "... As if I'd say no! Idiot!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hey, that's mean.");
        Character_BlinkStart(4, 2, (#1));
        Voice_PlayVoice("T0204010_D01800", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Shut up!");
        Message_Who(0);
        Message_MsgDisp("主人公", "You're mean!");
        Character_BlinkStart(4, 0, (#1));
        Voice_PlayVoice("T0204010_D01900", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "You're freaking noisy, so shut up!\n...\nIf you're not gonna shut up, then\nhave this!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh...");
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Screen_WipeOut(2);
        Still_Event("EV_04_21", #1, 1, 120);
        Screen_WipeIn(2);
        System_Wait(120);
        Still_Event("EV_04_21", #1, 0, 120, 0, 1);
        System_Wait(120);
        Screen_WipeOut(3);
        Character_Chara_GS2(4, "NON");
        System_GlobalWork(3, 0, 40);
        Parameter_InCh1Param(4, 305, 3);
        break ;
        case 1:
        Music_StopBGM(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "I can't, ｛Hariya＊＊｝...");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(4, 2, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("T0204010_D02000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "... I... see...");
        Character_BlinkStart(4, 3, (#1));
        Music_PlayBGM(0, "MN_C_04_004_D00", 127, 40);
        Voice_PlayVoice("T0204010_D02100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", ".........");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(4, 0, (#1));
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("T0204010_D02200", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "I don't know how long it's gonna\ntake.");
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("T0204010_D02300", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "But I'm gonna show up in front of\nyou again.\nI'm definitely gonna be a better man\nthan I am now...\nfor sure!");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Hariya＊＊｝...");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(4, 2, (#1));
        Voice_PlayVoice("T0204010_D02400", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "I'll come back as a man.\nA man that would make you wanna\nboast about the fact that we kissed.");
        Character_BlinkStart(4, 3, (#1));
        Voice_PlayVoice("T0204010_D02500", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "That's why...");
        Character_BlinkStart(4, 2, (#1));
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("T0204010_D02600", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "That's why you should become an even\nbetter woman, one that will make me\nfall in love with you even more!");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(4, 0, (#1));
        Voice_PlayVoice("T0204010_D02700", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Got it?");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Okay.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("T0204010_D02800", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "... Alright!");
        Character_ChFace(0, 0, 6);
        Character_BlinkStart(4, 2, (#1));
        Voice_PlayVoice("T0204010_D02900", 4, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Later, ｛主人公｝.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(4, "NON");
        SoundEffect_PlayStream(3, "SS_T_00_252_M00");
        Message_CloseMsg();
        Screen_WipeOut(3);
        System_GlobalWork(3, 0, 41);
        break ;
        }
    Screen_ClearScreen();
    Message_TextSpeed(#1);
    Parameter_AddCh1Param(4, 86, 1);
    }
