section "t02_g3_000"{
    Background_Bg_GS2("BG_ED010_SP_1", #1, #1, 1);
    System_Wait(1);
    Screen_WipeIn(2);
    Background_Check_BGScroll();
    System_GlobalWork(3, 0, 3);
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 2);
    Character_Chara_GS2(12, "G3_01F", 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Nishimoto＊＊｝!\nWhat are you doing here?");
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("T0212000_L00000", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "......");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(12, 3, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("T0212000_L00100", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "...\nDoesn't everyone get gloomy at\ngraduation ceremonies?");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(12, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("T0212000_L00200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I don't like that kinda thing, so I\ncame here to be alone, and to smile\nabout graduating.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see...");
    Character_BlinkStart(12, 0, (#1));
    Character_ChFace(0, 2, 4);
    Voice_PlayVoice("T0212000_L00300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I feel so much better when I think\nabout not having to listen to those\nuseless lessons anymore, ahaha!");
    Character_ChFace(0, 2, 2);
    Voice_PlayVoice("T0212000_L00400", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ha, haha...");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(12, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("T0212000_L00500", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "... Dummy, why did you come here!?\nI thought that I could hold it all\nin too...!");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Nishimoto＊＊｝...");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(12, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_Chara_GS2(12, "G3_01F", 0);
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(12, 3, (#1));
    Background_Bg_GS2("BG_EX110_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_12_001_D00", 127, 40);
    Voice_PlayVoice("T0212000_L00600", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "... It really is very sad.\nGraduation, and parting ways...");
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("T0212000_L00700", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "... I've had bucket loads of fun...");
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("T0212000_L00800", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "That's why I shouldn't be feeling\nany bit of regret.\nBut why do I feel so lonely...");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("T0212000_L00900", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "... Crap!\nLosing sleep over something like\nthis, isn't Nishimoto Haruhi-ish!");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Nishimoto＊＊｝.");
    Character_ChFace(0, 4, 0);
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("T0212000_L01000", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "After school, we would do things\nlike talk, or laugh until our\nstomachs hurt.");
    if (Parameter_GetCh1Param(12, 513) != 2){
        Parameter_InCh1Param(12, 300, 1);
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(12, 3, (#1));
        Voice_PlayVoice("T0212000_L01100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "When I think about not being able to\ndo that anymore...\nI feel so sad.");
        }
    else if (Parameter_GetCh1Param(12, 513) == 2){
        Parameter_InCh1Param(12, 300, 2);
        Character_BlinkStart(12, 2, (#1));
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("T0212000_L02900", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "...\nWe even both fell in love with\nHarry.");
        Character_BlinkStart(12, 3, (#1));
        Voice_PlayVoice("T0212000_L03000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "I thought that it would be like\nnormal, it would become a good\nmemory.");
        Character_BlinkStart(12, 0, (#1));
        Character_ChFace(0, 4, 0);
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("T0212000_L03100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "But...\nWhy did you fall in love with Harry,\ntoo?");
        Character_BlinkStart(12, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("T0212000_L03200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "I never thought I'd see someone\nselfishly self-centered like me.");
        Character_ChFace(0, 2, 2);
        Voice_PlayVoice("T0212000_L03300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "... Did you see what happened today?\nEven though I didn't ask for it, he\ngave me his autograph!");
        Character_ChFace(0, 4, 1);
        Character_BlinkStart(12, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("T0212000_L03400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "That guy really is a dummy...");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Nishimoto＊＊｝...");
        Character_BlinkStart(12, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("T0212000_L03500", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "...\nSince I fell in love with such a\ndummy, it means that I'm a dummy,\ntoo.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Maybe.");
        Character_ChFace(0, 4, 0);
        Character_ChFace(0, 2, 0);
        Voice_PlayVoice("T0212000_L03600", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ahaha! You, too!");
        }
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("T0212000_L01200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I'm really glad that I could meet\nyou!\nI'm glad that we could be friends...");
    Character_BlinkStart(12, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("T0212000_L01300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I love you!\nPlease treat me well from now on.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah! Of course!");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("T0212000_L01400", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Haha, thanks...\nAnyway, this is so uncool...");
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("T0212000_L01500", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "It's my first time crying this much\nin front of someone...");
    Character_ChFace(0, 4, 0);
    Character_ChFace(0, 2, 0);
    Voice_PlayVoice("T0212000_L01600", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Argh, my eyes will probably turn\nred.\nI'm gonna go wash my face, wanna\ncome along?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, let's go! Everyone's waiting!");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(12, 3, (#1));
    Voice_PlayVoice("T0212000_L01700", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Alright!\nLet's liven things up, and let's\nmake this last thing a success!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah!");
    if (Parameter_GetCh1Param(12, 513) != 2){
        }
    else if (Parameter_GetCh1Param(12, 513) == 2){
        }
    Character_ChFace(0, 0, 10);
    Message_CloseMsg();
    Music_StopBGM(0, 60);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(12, 86, 1);
    Parameter_InCh1Param(12, 305, 1);
    }
