section "t02_m3_220"{
    Music_PlayBGM(0, "MN_C_03_090_D00", 127, 40);
    Still_StillFace(0, 0, 4);
    Voice_PlayVoice("FD_03_220_00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I have always been deceiving myself.\nIn other words, I... No, you...\nIn other words...");
    Message_Who(0);
    Message_MsgDisp("主人公", "U-Umm, calm down,\n｛Hikami＊＊｝.");
    Still_Pair_Event("EV_03_17", "EV_99_00", 1, 1);
    Voice_PlayVoice("FD_03_220_00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Y-Yes, you are right.\nI will start from the beginning.");
    Still_Pair_Event("EV_03_16", "EV_99_00", 0, 0);
    Still_StillFace(0, 0, 3);
    Voice_PlayVoice("FD_03_220_00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "When you had informed me that you\nhad wanted us to be friends, I was\nactually sad.");
    Voice_PlayVoice("FD_03_220_00500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "From the moment that you spoke your\nmind, I realized something.\nI realized that I love you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hikami＊＊｝...");
    Still_StillFace(0, 0, 4);
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("FD_03_220_00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "As soon as it had started, my first\nlove was already over.\nThat is why I was sad.");
    Voice_PlayVoice("FD_03_220_00700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "But even so, I had thought that\nsince you were in love, I should be\nelated.\nIf I really loved you, I should\nsupport you.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("FD_03_220_00800", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I wanted to believe that.\nIt is what I had honestly thought.\nBut that...");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("FD_03_220_00900", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "But that was just me making things\nharder for you.");
    Still_StillFace(0, 0, 5);
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("FD_03_220_01000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "After the graduation ceremony, when\nI saw you leave the school gates, I\nrealized...\nthat my heart feels like it will\nexplode.");
    Still_Pair_Event("EV_99_00", "EV_03_16", 0, 0);
    Still_StillFace(0, 6, 2);
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("FD_03_220_01100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I like you.\nI have been in love with you ever\nsince I met you.\nPlease be my girlfriend.");
    System_Wait(#60);
    Message_MsgSel("I like you too, ｛Hikami＊＊｝...", "I want to be friends, ｛Hikami＊＊｝.");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "I like you too,\n｛Hikami＊＊｝...");
        Still_StillFace(0, 0, 1);
        Still_StillFace(0, 4, 1);
        Voice_PlayVoice("FD_03_220_01200", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Eh!? I mean, weren't you...");
        Message_Who(0);
        Message_MsgDisp("主人公", "But I've realized that I like you,\n｛Hikami＊＊｝...");
        Still_StillFace(0, 0, 3);
        Still_StillFace(0, 4, 1);
        Voice_PlayVoice("FD_03_220_01300", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I see...\nYou did not realize it either.\nThen the both of us...");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Yeah.");
        Voice_PlayVoice("FD_03_220_01400", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Amazing, just amazing!\nWe share mutual feelings!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, that's right.");
        Still_StillFace(0, 0, 3);
        Still_StillFace(0, 4, 0);
        Voice_PlayVoice("FD_03_220_01500", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Will you give me your hand?");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Still_Event("EV_03_19", #1, 1, 60);
        Screen_WipeIn(2);
        Parameter_InCh1Param(3, 305, 4);
        Voice_PlayVoice("FD_03_220_01600", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "We are in love.\nLet us both carefully nurture this\nfeeling forever, even when we become\nadults.");
        Message_CloseMsg();
        Still_Event("EV_03_19", #1, 0, 60, 0, 1);
        System_Wait(180);
        System_GlobalWork(3, 0, 38);
        if (Parameter_GetCh1Param(3, 570) >= 400){
            Parameter_InCh1Param(3, 302, 2);
            }
        else {
            Parameter_InCh1Param(3, 302, 1);
            }
        break ;
        case 1:
        Music_StopBGM(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Sorry, ｛Hikami＊＊｝.\nI want to be friends.");
        Still_Pair_Event("EV_99_00", "EV_03_17", 1, 1);
        Music_PlayBGM(0, "MN_C_03_005_D00", 127, 40);
        Voice_PlayVoice("FD_03_220_01700", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "I see... Yes.");
        Still_Pair_Event("EV_99_00", "EV_03_16", 0, 0);
        Still_StillFace(0, 0, 3);
        Voice_PlayVoice("FD_03_220_01800", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "It is sad, but it seems like I am a\nlittle calmer than before.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I'm sorry...");
        Still_StillFace(0, 0, 5);
        Voice_PlayVoice("FD_03_220_01900", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "It is fine.\nThe both of us spoke our minds.\nThat is why this is fine.");
        Still_StillFace(0, 0, 3);
        Voice_PlayVoice("FD_03_220_02000", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Thank you for honestly responding to\nme.");
        Voice_PlayVoice("FD_03_220_02100", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Even though I was rejected, it seems\nlike I still like you.\nHowever, with this, I should surely\nbe able to get over this.");
        Still_StillFace(0, 0, 5);
        Voice_PlayVoice("FD_03_220_02200", #1, "");
        Message_Who(3);
        Message_MsgDisp("Hikami", "Goodbye.");
        System_GlobalWork(3, 0, 31);
        break ;
        }
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(3);
    Screen_ClearScreen();
    }
