section "t02_m6_221"{
    Music_PlayBGM(0, "MN_C_06_090_D00", 127, 40);
    Still_Pair_Event("EV_06_15", "EV_99_00", 0, 0);
    Voice_PlayVoice("FD_06_220_00300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I was thinking...\nthat I did something really stupid.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Something stupid?");
    Still_Pair_Event("EV_06_14", "EV_99_00", 1, 1);
    Still_StillFace(0, 0, 3);
    Voice_PlayVoice("FD_06_220_00400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Yeah. Right, this place.");
    Voice_PlayVoice("FD_06_220_00500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "This is the place that I said I\nwon't tell anyone, and that I'd\nlisten.");
    Voice_PlayVoice("FD_06_220_00600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I hid my own feelings, and acted\nstrong...");
    Voice_PlayVoice("FD_06_220_00700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I've always regretted saying it like\nthat.");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("FD_06_220_00800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I really am an idiot...");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Amachi＊＊｝...");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("FD_06_220_00900", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "...\nBecause I can't turn back time, I\nthought that I'd at least say it\nhere.");
    Voice_PlayVoice("FD_06_220_01000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I'm fed up with being treated as a\njunior or as a friend.");
    Still_Pair_Event("EV_06_15", "EV_99_00", 0, 0);
    Voice_PlayVoice("FD_06_220_01100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Please become my girlfriend.");
    Still_Pair_Event("EV_99_00", "EV_06_15", 0, 0);
    Voice_PlayVoice("FD_06_220_01200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I like you...!");
    Message_Who(0);
    Message_MsgDisp("主人公", "I was an idiot, too.\nI've always liked you,\n｛Amachi＊＊｝.");
    Still_Pair_Event("EV_99_00", "EV_06_14", 1, 1);
    Still_StillFace(0, 0, 3);
    Voice_PlayVoice("FD_06_220_01300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... I feel like I've been had.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Been had?");
    Voice_PlayVoice("FD_06_220_01400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "To the point that I think you've\njust been playing dumb this whole\ntime.");
    Still_StillFace(0, 0, 5);
    Voice_PlayVoice("FD_06_220_01500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "...\nBut it's fine, even if it's a lie or\neven if it's real.");
    Voice_PlayVoice("FD_06_220_01600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I have a senior who says that they\nlike me.\nThat is fine.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Amachi＊＊｝.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Still_Event("EV_06_17", #1, 1, 60);
    Screen_WipeIn(2);
    Parameter_InCh1Param(6, 305, 4);
    Voice_PlayVoice("FD_06_220_01700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Senpai.");
    Voice_PlayVoice("FD_06_220_01800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I will never let you go....\nNever, okay?");
    Message_CloseMsg();
    Still_Event("EV_06_17", #1, 0, 60, 0, 1);
    System_Wait(180);
    Screen_WipeOut(3);
    Screen_ClearScreen();
    Music_StopBGM(0, 40);
    Background_Bg_GS2("BG_BK000_CO_0", #1, #1, 0);
    Screen_WipeIn(3);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
