section "t02_m2_220"{
    Music_PlayBGM(0, "MN_C_02_090_D00", 127, 40);
    Character_BlinkStart(2, 3, (#1));
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("FD_02_220_00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... I came here to apologize to you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Apologize... Why?\nYou didn't do anything wrong.");
    Character_BlinkStart(2, 2, (#1));
    Voice_PlayVoice("FD_02_220_00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... No, I did.\nI've been lying to you. I'm sorry.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Lying...");
    Character_BlinkStart(2, 0, (#1));
    Voice_PlayVoice("FD_02_220_00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... I like you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("FD_02_220_00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "At first, I liked you as a friend.");
    Character_BlinkStart(2, 2, (#1));
    Voice_PlayVoice("FD_02_220_00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Now, I like you as a girl.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝...");
    Character_BlinkStart(2, 0, (#1));
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("FD_02_220_00600", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "I want you....\nFrom the very bottom of my heart.");
    Character_BlinkStart(2, 0, (#1));
    Voice_PlayVoice("FD_02_220_00700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "I like you.");
    Still_StillFace(0, 0, 1);
    Still_Pair_Event("EV_99_00", "EV_02_17", 0, 0);
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("FD_02_220_00800", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Forgive me for always betraying you.");
    System_Wait(#60);
    Message_MsgSel("I like you too, ｛Shiba＊＊｝...", "I want to be friends, ｛Shiba＊＊｝.");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "I don't think you're betraying me...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Because I like you too,\n｛Shiba＊＊｝.");
        Still_StillFace(0, 0, 0);
        System_Wait(80);
        Still_StillFace(0, 0, 4);
        Character_BlinkStart(2, 0, (#1));
        Voice_PlayVoice("FD_02_220_00900", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Give me your hand.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Okay.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Still_Event("EV_02_20", #1, 1, 60);
        Screen_WipeIn(2);
        Voice_PlayVoice("FD_02_220_01000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "We took the long way on our separate\nroads.");
        Voice_PlayVoice("FD_02_220_01100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "But from now on, we'll be walking on\nthe same road....\nTogether.");
        Message_CloseMsg();
        System_Wait(80);
        Still_Event("EV_02_20", #1, 0, 60, 0, 1);
        System_Wait(120);
        System_GlobalWork(3, 0, 28);
        if (Parameter_GetCh1Param(2, 570) >= 400){
            Parameter_InCh1Param(2, 302, 2);
            }
        else {
            Parameter_InCh1Param(2, 302, 1);
            }
        Parameter_InCh1Param(2, 305, 4);
        break ;
        case 1:
        Music_StopBGM(0, 40);
        Still_StillFace(0, 0, 1);
        Character_BlinkStart(2, 3, (#1));
        Voice_PlayVoice("FD_02_220_01200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... I understand.");
        Character_BlinkStart(2, 0, (#1));
        Music_PlayBGM(0, "MN_C_02_001_D00", 127, 40);
        Voice_PlayVoice("FD_02_220_01300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Sorry for saying these kinda things\nwhen things were going so well.");
        Character_BlinkStart(2, 0, (#1));
        Voice_PlayVoice("FD_02_220_01400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "--I didn't want you to make that\nkinda face, though.");
        Character_BlinkStart(2, 3, (#1));
        Still_StillFace(0, 0, 2);
        Voice_PlayVoice("FD_02_220_01500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "I knew that it would never\nhappen....\nI'm the worst, aren't I?");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Shiba＊＊｝...");
        Character_BlinkStart(2, 0, (#1));
        Still_StillFace(0, 0, 4);
        Voice_PlayVoice("FD_02_220_01600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Thanks for everything.\nI'm glad I met you.");
        Character_BlinkStart(2, 2, (#1));
        Voice_PlayVoice("FD_02_220_01700", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Later.");
        System_GlobalWork(3, 0, 21);
        break ;
        }
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(3);
    Screen_ClearScreen();
    }
