section "t02_m8_220"{
    Music_PlayBGM(0, "MN_C_08_090_D00", 127, 40);
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("FD_08_220_00300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "You know, when you told me that you\nhad your eye on someone.");
    Voice_PlayVoice("FD_08_220_00400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I honestly wanted to support you.");
    Still_StillFace(0, 0, 2);
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("FD_08_220_00500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I wanted to head towards the future\nthat you had wished for.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("FD_08_220_00600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I thought that if it was for that\nsake, I could suppress it.\nBut...");
    Still_StillFace(0, 0, 5);
    Voice_PlayVoice("FD_08_220_00700", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "But I ended up not being able to\nthink about anything but you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Masaki-senpai.");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("FD_08_220_00800", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I like you.");
    Still_Pair_Event("EV_99_00", "EV_08_15", 0, 0);
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("FD_08_220_00801", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I want you... to be by my side.\nNext to me.");
    System_Wait(#60);
    Message_MsgSel("I do too, Masaki-senpai...", "I want to be friends, Masaki-senpai.");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "I like you too, Masaki-senpai....\nI want to be by your side.");
        Still_StillFace(0, 0, 3);
        System_Wait(50);
        Still_StillFace(0, 0, 4);
        Still_StillFace(0, 0, 4);
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("FD_08_220_00900", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "... Huh... Hey you～......");
        Still_StillFace(0, 6, 0);
        Still_StillFace(0, 0, 4);
        Still_StillFace(0, 4, 1);
        Voice_PlayVoice("FD_08_220_01000", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Saying it like that, and with that\nface is foul play...");
        Still_StillFace(0, 0, 5);
        Still_StillFace(0, 4, 1);
        Voice_PlayVoice("FD_08_220_01100", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Ah, I feel like the words are just\ncoming out.\nCrap......");
        Message_Who(0);
        Message_MsgDisp("主人公", "Masaki-senpai?");
        Still_StillFace(0, 0, 2);
        Still_StillFace(0, 4, 0);
        Voice_PlayVoice("FD_08_220_01200", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "...... Yeah.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Still_Event("EV_08_18", #1, 1, 60);
        Screen_WipeIn(2);
        Voice_PlayVoice("FD_08_220_01300", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "The spot beside me will always\nbelong to you.");
        Voice_PlayVoice("FD_08_220_01400", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Please continue to treat me well.");
        Message_CloseMsg();
        Still_Event("EV_08_18", #1, 0, 60, 0, 1);
        System_Wait(180);
        System_GlobalWork(3, 0, 88);
        Parameter_InCh1Param(8, 305, 4);
        if (Parameter_GetCh1Param(8, 570) >= 300){
            Parameter_InCh1Param(8, 302, 2);
            }
        else {
            Parameter_InCh1Param(8, 302, 1);
            }
        break ;
        case 1:
        Music_StopBGM(0, 40);
        Still_StillFace(0, 0, 5);
        Voice_PlayVoice("FD_08_220_01500", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "Yeah...");
        Still_StillFace(0, 6, 1);
        Music_PlayBGM(0, "MN_C_08_000_D00", 127, 40);
        Voice_PlayVoice("FD_08_220_01600", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "I expected this.\nBut it's quite tough...");
        Message_Who(0);
        Message_MsgDisp("主人公", "I'm sorry...");
        Still_StillFace(0, 6, 0);
        Voice_PlayVoice("FD_08_220_01700", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "That's my line.\nYou don't need to be apologetic.");
        Message_Who(0);
        Message_MsgDisp("主人公", "But...");
        Still_StillFace(0, 0, 7);
        Still_StillFace(0, 6, 2);
        Voice_PlayVoice("FD_08_220_01800", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "I won't be able to be by your side\nanymore...\nWill you be okay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Masaki-senpai...");
        Still_StillFace(0, 0, 2);
        Still_StillFace(0, 6, 0);
        Voice_PlayVoice("FD_08_220_01900", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "It wasn't long...\nI'm glad that I could be the closest\nperson to you.\nReally glad.");
        Voice_PlayVoice("FD_08_220_02000", #1, "");
        Message_Who(8);
        Message_MsgDisp("Masaki", "... Later.\nCongratulations on graduating.");
        System_GlobalWork(3, 0, 81);
        break ;
        }
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(3);
    Screen_ClearScreen();
    }
