section "u02_g1_000"{
    if (Parameter_GetCh1Param(10, 64) == 0){
        Background_Bg_GS2("BG_NE600_?_0", 1, #1, 0);
        Character_Chara_GS2(10, "G1_04F", 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("U0210000_J00000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Wasn't it a stylish movie?\nThe graphics looked new, too.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah! It was interesting!");
        Character_ChFace(0, 0, 0);
        Character_BlinkStart(10, 3, (#1));
        Voice_PlayVoice("U0210000_J00100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "There's not much known about the\ndirector.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(10, 0, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("U0210000_J00200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I checked the director's work,\nbeforehand.");
        Message_Who(0);
        Message_MsgDisp("主人公", "As expected, ｛Toudou＊＊｝.\nUp to date with the latest craze.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(10, 2, (#1));
        Voice_PlayVoice("U0210000_J00300", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Oh, I expect for it to be a big hit,\neventually.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Wow... That's great!\nWell then, I'll have to check, too!");
        Character_BlinkStart(10, 3, (#1));
        Voice_PlayVoice("U0210000_J00400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Hah...");
        Message_Who(0);
        Message_MsgDisp("主人公", "What's so funny?");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("U0210000_J00500", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Nothing.\nWell, I was just thinking that it\nwould be nice to do this every once\nin a while...");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("U0210000_J00600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Though as a matter of principle, I\nalways go off to watch movies alone.");
        Voice_PlayVoice("U0210000_J00700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I don't think it was bad at all with\nyou, like this, sharing our thoughts\non the movie that we watched today.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.\nIt's probably twice as much fun than\nto be watching it alone, right?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(10, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("U0210000_J00800", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Haha. I guess so...\nI'll be inviting you, again.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay!");
        }
    else {
        Background_Bg_GS2("BG_NE600_?_0", 1, #1, 0);
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(10, 2, (#1), 1);
        Character_ChFace(0, 3, 3);
        Character_Chara_GS2(10, "G1_04F", 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("U0210000_J00900", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "How was it?\nDid you find it interesting?\n\"Heroism is an Forgotten Art.\"\nIt's a Japanese Showa movie, though.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Do you like these kind of movies,\n｛Toudou＊＊｝?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(10, 0, (#1));
        Voice_PlayVoice("U0210000_J01000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Yeah. Don't you find it cool?\nDuty and humanity...\nThe world of men risking their\nlives.\nI do like that.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm... I see.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("U0210000_J01100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I've seen it many times, but I've\nnever gotten bored...\nDid you not like it?\nI'm sorry for making you tag along.");
        Message_Who(0);
        Message_MsgDisp("主人公", "No, that's not it!\nI'm glad that you invited me.");
        Character_BlinkStart(10, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("U0210000_J01200", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "You... are a good girl.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh?");
        Character_BlinkStart(10, 3, (#1));
        Voice_PlayVoice("U0210000_J01300", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Doing this, sharing common interests\nwith other people.\nIt's admirable.");
        Character_BlinkStart(10, 0, (#1));
        Voice_PlayVoice("U0210000_J01400", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "It's because aside from my hobbies,\nother things hold little interest to\nme.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That's...\nnot much of a big deal, I think.");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(10, 2, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("U0210000_J01500", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Is that so...? Well, it's fine.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("U0210000_J01600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "If it's all right with you, let's go\nout, again.\nI might just give you a call.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Sure! Thank you.");
        }
    System_Call_GS2("U03", "G1", 0);
    }
