section "h3a_m7_000"{
    Background_Bg_GS2("BG_SCA22_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetBkParam(3, 52) >= 320){
        if (Parameter_GetCh1Param(7, 130) <= 2){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Yay, I won the championships!)");
            Character_ChFace(0, 0, 10);
            Character_Chara_GS2(7, "M7_17F", 0);
            Voice_PlayVoice("", 7, "H3A07000_G00000");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝,\ncongratulations on winning the\nchampionships.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Wakaouji＊＊｝!\nThank you very much!");
            Character_ChFace(0, 2, 3);
            Character_ChFace(0, 3, 0);
            Voice_PlayVoice("H3A07000_G00100", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "It might be sudden, but please tell\nme what you ate yesterday in\npreparation for today.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... Pardon?");
            Voice_PlayVoice("H3A07000_G00200", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "I have to learn some techniques so\nthat I can foster strong\ncompetitors.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I s-see. I ate what I usually eat...");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("H3A07000_G00300", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Is that so? ...\nI will collect other data.\nI am glad that you joined the Track\nand Field Club.");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(7, 3, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("H3A07000_G00400", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "I am really glad that I have the\ncountry's fastest runner.\nYour existence is a miracle.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(All I did was win...\nSo why is he speaking so highly...?)");
            }
        else if (Parameter_GetCh1Param(7, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Yay, I won the championships!)");
            Character_ChFace(0, 0, 10);
            Character_Chara_GS2(7, "M7_17F", 0);
            Voice_PlayVoice("", 7, "H3A07000_G00500");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Congratulations,\n｛主人公｝!\nYou won the championships.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝!\nThank you very much!");
            Voice_PlayVoice("H3A07000_G00600", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "You've changed form.\nAnd it's gone by unnoticed.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... Unnoticed?");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(7, 3, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("H3A07000_G00700", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "When you joined the club, I didn't\nthink that you would be the inter\nhigh school champion.");
            Character_ChFace(0, 0, 10);
            Voice_PlayVoice("H3A07000_G00800", 7, "H3A07000_G00801");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Even though you worked under a\ntrainer like me, you've really\nprogressed.\nThank you, ｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "That's... Thank you very much!");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I'm really glad that I could stay\nin the Track and Field Club!)");
            }
        else {
            Message_Who(0);
            Message_MsgDisp("主人公", "(Yay, I won the championships!)");
            Character_ChFace(0, 0, 10);
            Character_Chara_GS2(7, "M7_17F", 0);
            Voice_PlayVoice("", 7, "H3A07000_G00900");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝....\nCongratulations on winning the\nchampionships.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝!\nThank you very much!");
            Character_BlinkStart(7, 3, (#1));
            Voice_PlayVoice("H3A07000_G01000", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "You've finally become the top\nathlete....\nThat was your reason for joining the\nclub.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... You remembered.");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(7, 2, (#1));
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("H3A07000_G01100", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Of course.\nYour pupils were shining, so it left\na really strong impression on me.");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 1);
            Voice_PlayVoice("H3A07000_G01200", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "...\nI thought I'd need a handkerchief,\nbut it seems like I don't need one.\nYour smile is amazing.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...");
            Voice_PlayVoice("", 7, "H3A07000_G01300");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Congratulations,\n｛主人公｝.\nI will never forget today, no matter\nhow many years pass.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝...\nEven though he's glad, why does he\nsound so sad...?)");
            }
        }
    else {
        if (Parameter_GetCh1Param(7, 130) <= 2){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Argh～, I lost...)");
            Voice_PlayVoice("", 7, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(7, "M7_17F", 0);
            Voice_PlayVoice("H3A07000_G01400", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Cheer up. You worked quite hard.");
            Message_Who(0);
            Message_MsgDisp("主人公", "But...");
            Voice_PlayVoice("H3A07000_G01500", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Don't say \"but\".\nThe responsibility lies with me.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            Character_ChFace(0, 2, 2);
            Character_BlinkStart(7, 3, (#1));
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("H3A07000_G01600", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "It seems like I miscalculated the\nair resistance here.\nThe wind was stronger than I had\npredicted.");
            Voice_PlayVoice("H3A07000_G01700", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "I wasn't able to tell you that at\nthe meeting before the race.\nI apologize.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Is that... so?");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I feel a little better...\nBecause I tried my very best,\nthere's no regret.)");
            }
        else if (Parameter_GetCh1Param(7, 130) == 3){
            Message_Who(0);
            Message_MsgDisp("主人公", "(Argh～, I lost...)");
            Voice_PlayVoice("", 7, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝.");
            Character_ChFace(0, 0, 0);
            Character_Chara_GS2(7, "M7_17F", 0);
            Voice_PlayVoice("H3A07000_G01800", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Welcome back. You did well.");
            Message_Who(0);
            Message_MsgDisp("主人公", "But I...");
            Character_ChFace(0, 2, 0);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("H3A07000_G01900", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "No, you ran quite fast.\nAt the inter high school level, you\nfight against yourself.");
            Voice_PlayVoice("H3A07000_G02000", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "The feeling you have right now will\nbecome one of your assets one day.\nI believe in that.");
            Message_Who(0);
            Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...");
            Voice_PlayVoice("H3A07000_G02100", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "So, everyone is waiting. Let's go.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(It was unfortunate...\nBut I did all that I could, so I\nhave no regrets.)");
            }
        else {
            Message_Who(0);
            Message_MsgDisp("主人公", "(Argh, I lost...)");
            Voice_PlayVoice("", 7, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "｛主人公｝.");
            Message_Who(0);
            Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝.");
            Character_ChFace(0, 2, 2);
            Character_ChFace(0, 3, 1);
            Character_Chara_GS2(7, "M7_17F", 0);
            Voice_PlayVoice("H3A07000_G02200", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "... It was unfortunate.\nI feel very vexed.");
            Message_Who(0);
            Message_MsgDisp("主人公", "I'm sorry...");
            Character_ChFace(0, 2, 4);
            Character_BlinkStart(7, 2, (#1));
            Character_ChFace(0, 3, 2);
            Voice_PlayVoice("H3A07000_G02300", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "No, don't apologize.\nYou ran with all your might.\nI was watching you the whole time,\nso I know.");
            Character_ChFace(0, 0, 3);
            Voice_PlayVoice("H3A07000_G02400", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "Actually, motivating you is my job.\nBut during the race, I felt as if I\nwas running with you.");
            Message_Who(0);
            Message_MsgDisp("主人公", ".........");
            Character_ChFace(0, 4, 1);
            Character_ChFace(0, 2, 5);
            Character_ChFace(0, 3, 3);
            Voice_PlayVoice("H3A07000_G02500", #1, "");
            Message_Who(7);
            Message_MsgDisp("Wakaouji", "So we should both feel vexed....\nIf you want to cry, then cry.\nYou feel that way too, right?");
            Message_Who(0);
            Message_MsgDisp("主人公", "Yes, ｛Wakaouji＊＊｝...");
            Message_Who(0);
            Message_MsgDisp("主人公", "(I kind of feel more relaxed now...\nI did all that I could, so I have no\nregrets.)");
            }
        }
    Parameter_AddCh1Param(7, 86, 1);
    }
