section "h7g_m5_000"{
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(5, "M5_??F", 0);
    Background_Bg_GS2("BG_HO000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("", 5, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("H8G05000_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Hello.\nI heard that you won first prize for\na design contest?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah. News travels fast.");
    Voice_PlayVoice("H8G05000_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I re-enter everything that I hear\nabout you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Re-enter...?\nAh, you mean \"remember\"...");
    Voice_PlayVoice("H8G05000_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah, yeah.");
    Voice_PlayVoice("H8G05000_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Hey, will you show me your design\nplans next time?");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(5, 3, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("H8G05000_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I really wanna see it.\nIt seems like I'll be able to get\nheaps of motivation from it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sure, of course!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I'm glad that I did my best to\ncomplete the work!)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    }
