section "h8g_m3_000"{
    Character_ChFace(0, 0, 10);
    Character_Chara_GS2(3, "M3_01F", 0);
    Background_Bg_GS2("BG_SCA80_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("", 3, "H7G03000_C00000");
    Message_Who(3);
    Message_MsgDisp("Hikami", "｛主人公｝.\nCongratulations, it's an amazing\naward.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks, ｛Hikami＊＊｝!\nBut is it really fine to be\nreceiving this?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(3, 3, (#1));
    Voice_PlayVoice("H7G03000_C00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "If you look at the history of who\nwas named exemplary student, they\nwere the little people.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("H7G03000_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "And that's all you were doing.\nEveryone in school knows that.\nIt's fine to boast more about it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks...\nIt's because you were supporting me,\n｛Hikami＊＊｝.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(3, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("H7G03000_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "You. That kind of modesty is...\nYes, it is still one of your\ncharms...");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("H7G03000_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "If you don't act more happy, won't\nit seem like you're unhappy?\nI am proud that I can do club\nactivities with you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, stop it,\n｛Hikami＊＊｝!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(...\nI'm glad I did my best in Student\nCouncil activities!)");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(3, 86, 1);
    }
