section "k01_m5_001"{
    Character_BlinkStart(5, 1, (#1), 1);
    Character_BlinkStart(5, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "I wonder if ｛Chris＊＊｝ is\nhere....\nThere he is!");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝!");
    if (Parameter_GetCh1Param(5, 130) <= 2){
        Music_PlayBGM(0, "MN_C_05_002_D00", 127, 40);
        Character_Chara_GS2(5, "M5_01F", 0);
        Voice_PlayVoice("K0105000_E00000", 5, "K0105000_E00001");
        Message_Who(5);
        Message_MsgDisp("Chris", "Ah, ｛主人公｝. Hello.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hello! Here!\nThis is a birthday present.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0105000_E00100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Thanks. Can I open it?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, go ahead!");
        }
    else if (Parameter_GetCh1Param(5, 130) == 3){
        Music_PlayBGM(0, "MN_C_05_002_D00", 127, 40);
        Character_Chara_GS2(5, "M5_01F", 0);
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(5, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("", 5, "K0105000_E00200");
        Message_Who(5);
        Message_MsgDisp("Chris", "｛主人公｝. What's up?");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's your birthday today, right\n｛Chris＊＊｝?\nHere, it's a present!");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("K0105000_E00300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Wow, you remembered. I'm glad～.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Of course. Open it!");
        }
    else {
        Music_PlayBGM(0, "MN_C_05_002_D00", 127, 40);
        Character_Chara_GS2(5, "M5_01F", 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("", 5, "K0105000_E00400");
        Message_Who(5);
        Message_MsgDisp("Chris", "｛主人公｝.\nEven if you're that hurried, I'm not\ngoing anywhere.");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("K0105000_E00500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "What's up?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Here! This is a birthday present.");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("K0105000_E00600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "............");
        Message_Who(0);
        Message_MsgDisp("主人公", "... What's wrong?");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(5, 3, (#1));
        Voice_PlayVoice("K0105000_E00700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I'm so touched that you\nremembered...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Haha, you're exaggerating.\nHey, open it!");
        }
    if (Parameter_GetCh1Param(5, 67) == 1){
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("K0105000_E00800", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Amazing.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh? What is?");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(5, 2, (#1));
        Voice_PlayVoice("K0105000_E00900", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "You are my secret power.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm...\nI think it's not much, though.");
        Voice_PlayVoice("K0105000_E01000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "You just don't know it.");
        Music_StopBGM(0, 40);
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("K0105000_E01100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Thanks. I'll treasure it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Yay, it looks like he's really\nhappy!)");
        Parameter_AddCh1Param(5, 61, 3);
        Parameter_AddCh1Param(5, 60, 2);
        Parameter_AddCh1Param(5, 62, #3);
        }
    else if (Parameter_GetCh1Param(5, 67) == 2){
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("K0105000_E01200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I was just about to go and buy this.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0105000_E01300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Thanks. I will gratefully use it.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It looks like he's relatively\nhappy.)");
        Parameter_AddCh1Param(5, 61, 1);
        Parameter_AddCh1Param(5, 60, 0);
        Parameter_AddCh1Param(5, 62, #1);
        Music_StopBGM(0, 40);
        }
    else if (Parameter_GetCh1Param(5, 67) == 3){
        Character_ChFace(0, 0, 3);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("K0105000_E01400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "......");
        Message_Who(0);
        Message_MsgDisp("主人公", "... ｛Chris＊＊｝?");
        Character_ChFace(0, 2, 3);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("K0105000_E01500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "... Hey.\nDid you choose this present for me?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, I did.");
        Voice_PlayVoice("K0105000_E01600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "You didn't confuse me with someone\nelse?");
        Message_Who(0);
        Message_MsgDisp("主人公", "No... I didn't...");
        Music_StopBGM(0, 40);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0105000_E01700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I see... Thanks...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Hmm, it looks like he's not that\nhappy about it...)");
        Parameter_AddCh1Param(5, 61, #1);
        Parameter_AddCh1Param(5, 60, #2);
        Parameter_AddCh1Param(5, 62, 2);
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    }
