section "k02_m3_011"{
    Character_BlinkStart(3, 1, (#1), 1);
    Character_BlinkStart(3, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Character_Chara_GS2(3, "M3_D?F", 0);
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks for walking me home.");
    Voice_PlayVoice("K0203011_C00000", 3, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "It is not like I mind....\n｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("K0203011_C00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Today is your birthday, isn't it?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wow, thanks! You remembered.");
    Voice_PlayVoice("K0203011_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Yes. Happy Birthday.\nAnd thank you for being born.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Eh?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("K0203011_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... Is that strange?\nOur family says that.\nSo I think of it as something\nnormal.");
    Voice_PlayVoice("K0203011_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I will take my leave now.");
    Character_Chara_GS2(3, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Haha, it was a wonderful birthday.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    System_Call_GS2("K02", "M3", 20);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
