section "k02_m2_000"{
    Character_BlinkStart(2, 1, (#1), 1);
    Character_BlinkStart(2, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    if (Parameter_ChkPlayer(6) == 1){
        Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes～.");
        SoundEffect_PlayStream(3, "SS_T_00_039_M00");
        Character_Chara_GS2(2, "M2_??F", 0);
        Music_PlayBGM(0, "MN_C_02_002_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh, ｛Shiba＊＊｝?\nWhat's up?");
        Voice_PlayVoice("K0202000_B00000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Today's your birthday, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh! You remembered...");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(2, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("K0202000_B00100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Yeah.... Here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "A present! ... I'm so happy!\nI'll treasure it.");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(2, 0, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0202000_B00200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Later.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(2, "NON");
        }
    else if (Parameter_ChkPlayer(6) == 0){
        Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes～.");
        SoundEffect_PlayStream(3, "SS_T_00_039_M00");
        Character_Chara_GS2(2, "M2_??F", 0);
        Music_PlayBGM(0, "MN_C_02_002_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh, ｛Shiba＊＊｝?\nWhat's up?");
        Voice_PlayVoice("K0202000_B00000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Today's your birthday, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh! You remembered...");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(2, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("K0202000_B00100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Yeah.... Here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "A present! ... I'm so happy!\nI'll treasure it.");
        Character_ChFace(0, 2, 5);
        Character_BlinkStart(2, 0, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0202000_B00200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Later.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(2, "NON");
        }
    else {
        Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes.");
        SoundEffect_PlayStream(3, "SS_T_00_039_M00");
        Character_Chara_GS2(2, "M2_??F", 0);
        Music_PlayBGM(0, "MN_C_02_002_D00", 127, 40);
        Environment_StopME(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh, ｛Shiba＊＊｝?\nWhat's up?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0202000_B01200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Here.\nIt was your birthday a while ago,\nright.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You remembered,\n｛Shiba＊＊｝...");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(2, 3, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0202000_B01300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Sorry it's late.");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's fine! I'm glad. Thank you!");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(2, 2, (#1));
        Voice_PlayVoice("K0202000_B01400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Later.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(2, "NON");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 86, 1);
    System_Call_GS2("K02", "M2", 20);
    Parameter_InPl1Param(336, #1);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
