section "k02_m4_010"{
    Character_BlinkStart(4, 1, (#1), 1);
    Character_BlinkStart(4, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_Chara_GS2(4, "M4_??F", 0);
    Background_Bg_GS2("BG_HO000_WI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks for walking me home.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("K0204010_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Oi.... Here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? What is it?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(4, 3, (#1));
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("K0204010_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Ack, you shouldn't be asking,\nright!?\nToday's your birthday!\nIt's a present!");
    Message_Who(0);
    Message_MsgDisp("主人公", "You remembered...");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(4, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("K0204010_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I just happened to remember, okay!?\nSince it's... on New Year's Day.");
    Character_BlinkStart(4, 0, (#1));
    Voice_PlayVoice("K0204010_D00300", 4, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Anyway! ...\nHappy Birthday,\n｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(It seems like this year will be a\nvery good year!)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    }
