section "k02_m3_010"{
    Character_BlinkStart(3, 1, (#1), 1);
    Character_BlinkStart(3, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_Chara_GS2(3, "M3_??F", 0);
    Background_Bg_GS2("BG_HO000_WI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks for walking me home.");
    Voice_PlayVoice("K0203010_C00000", 3, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "It is not like I mind....\n｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What?");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("K0203010_C00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Today is your birthday, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wow, you remembered!");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(3, 3, (#1));
    Voice_PlayVoice("K0203010_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "...\nHaving your birthday on New Year's\nDay is unforgettable.\nI thank your parents for giving\nbirth to you on a great day.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("K0203010_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Happy Birthday.\nAlso, thank you for being born.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Eh?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("K0203010_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... Is that strange?\nOur family says that.\nSo I think of it as something\nnormal.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("K0203010_C00500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... This is a present.\nIt would be nice if you liked it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wow! Thanks, ｛Hikami＊＊｝.");
    Voice_PlayVoice("K0203010_C00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Excuse me, then.");
    Character_Chara_GS2(3, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I'll make sure that this year will\nbe a good year...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(3, 86, 1);
    }
