section "k02_m4_000"{
    Character_BlinkStart(4, 1, (#1), 1);
    Character_BlinkStart(4, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    if (Parameter_ChkPlayer(6) == 1){
        Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes～.");
        SoundEffect_PlayStream(3, "SS_T_00_039_M00");
        Character_Chara_GS2(4, "M4_??F", 0);
        Music_PlayBGM(0, "MN_C_04_002_D00", 127, 40);
        Voice_PlayVoice("K0204000_D00000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Yo.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Hariya＊＊｝.\nWhat's up?");
        Voice_PlayVoice("K0204000_D00100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Nothing's up.\nIt's your birthday today, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "You remembered?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0204000_D00200", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Kinda! Here, take this.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Thanks.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0204000_D00300", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "I'm just letting you know that\nbuying this was really embarrassing!");
        Voice_PlayVoice("K0204000_D00400", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Treasure it since you made me go\nthis far for you!\nLater!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(4, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Yay～!\nI received a present from\n｛Hariya＊＊｝!)");
        }
    else if (Parameter_ChkPlayer(6) == 0){
        Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes～.");
        SoundEffect_PlayStream(3, "SS_T_00_039_M00");
        Character_Chara_GS2(4, "M4_??F", 0);
        Music_PlayBGM(0, "MN_C_04_002_D00", 127, 40);
        Voice_PlayVoice("K0204000_D00000", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Yo.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Hariya＊＊｝.\nWhat's up?");
        Voice_PlayVoice("K0204000_D00100", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Nothing's up.\nIt's your birthday today, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "You remembered?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0204000_D00200", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Kinda! Here, take this.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Thanks!");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0204000_D00300", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "I'm just letting you know that\nbuying this was so embarrassing!");
        Voice_PlayVoice("K0204000_D00400", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Treasure it since you made me go\nthis far for you!\nLater!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(4, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Yay～!\nI received a present from\n｛Hariya＊＊｝!)");
        }
    else {
        Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes!");
        SoundEffect_PlayStream(3, "SS_T_00_039_M00");
        Character_Chara_GS2(4, "M4_??F", 0);
        Music_PlayBGM(0, "MN_C_04_002_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Hariya＊＊｝.\nWhat's up?");
        Voice_PlayVoice("K0204000_D00900", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "It's a little late, but I'm doing\nit, anyway.\nIt was your birthday a few days ago,\nright?");
        Message_Who(0);
        Message_MsgDisp("主人公", "You remembered...");
        Voice_PlayVoice("K0204000_D00700", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "Did you think that I'd forget?\nHere, it's a present!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Wow, thanks!");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0204000_D00800", #1, "");
        Message_Who(4);
        Message_MsgDisp("Hariya", "... Make sure you treasure it!\nLater!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(4, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Yay～!\nI received a present from\n｛Hariya＊＊｝!)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    System_Call_GS2("K02", "M4", 20);
    Parameter_InPl1Param(336, #1);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
