section "k02_m2_011"{
    Character_BlinkStart(2, 1, (#1), 1);
    Character_BlinkStart(2, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Character_Chara_GS2(2, "M2_D?F", 0);
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks for walking me home.");
    Voice_PlayVoice("K0202011_B00000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Yeah.............");
    Message_Who(0);
    Message_MsgDisp("主人公", "... What's wrong?");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(2, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("K0202011_B00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh... Is this...");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(2, 0, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("K0202011_B00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Happy birthday.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm so happy...! You remembered.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(2, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("K0202011_B00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... It's fine, just take it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay. Thanks...");
    Character_BlinkStart(2, 0, (#1));
    Voice_PlayVoice("K0202011_B00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "............ Today...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("K0202011_B00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nI'm glad that I could be with you\ntoday....\nLater.");
    Character_Chara_GS2(2, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Haha, this was an amazing\nbirthday!)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    System_Call_GS2("K02", "M2", 20);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
