section "k02_m1_010"{
    Character_BlinkStart(1, 1, (#1), 1);
    Character_BlinkStart(1, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_Chara_GS2(1, "M1_??F", 0);
    Background_Bg_GS2("BG_HO000_WI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks for walking me home.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("K0201010_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It's fine.\nAll of Japan is celebrating, so it's\na bit hard to say...\nthat.");
    Message_Who(0);
    Message_MsgDisp("主人公", "\"That\"?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("K0201010_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "... Congrats.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yeah...\nPlease treat me well this year, too.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("K0201010_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "No, not that. Happy birthday.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wow! You remembered!");
    Character_ChFace(0, 0, 6);
    Voice_PlayVoice("K0201010_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Well, it is also the New Year....\nHere's your present.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wow, thanks!");
    Character_ChFace(0, 0, 6);
    Voice_PlayVoice("K0201010_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Yeah.\nI'm glad I got to say it today.\nLater.");
    Character_Chara_GS2(1, "NON");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    }
