section "k02_m7_000"{
    Character_BlinkStart(7, 1, (#1), 1);
    Character_BlinkStart(7, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    if (Parameter_ChkPlayer(6) == 1){
        Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes.");
        SoundEffect_PlayStream(3, "SS_T_00_039_M00");
        Character_Chara_GS2(7, "M7_06F", 0);
        Music_PlayBGM(0, "MN_C_07_002_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝!?\nWhat is the matter...");
        Voice_PlayVoice("K0207000_G00000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Yes. It's a surprise home visit.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh!?\nUmm, I'm sorry to say, but my mother\nis--");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0207000_G00100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I'm kidding.");
        Message_Who(0);
        Message_MsgDisp("主人公", ".........");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0207000_G00200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Happy birthday.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Wow, thank you very much!\nYou came all the way here, as well.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0207000_G00300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Because I would get scolded by the\nvice principal if someone found out\nat school.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...\nSorry for making you come all the\nway here.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0207000_G00400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "No... It's fine. Happy birthday.\nI will take my leave.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(7, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝ remembered my\nbirthday...)");
        }
    else if (Parameter_ChkPlayer(6) == 0){
        Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes.");
        SoundEffect_PlayStream(3, "SS_T_00_039_M00");
        Character_Chara_GS2(7, "M7_06F", 0);
        Music_PlayBGM(0, "MN_C_07_002_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝!?\nWhat is the matter...");
        Voice_PlayVoice("K0207000_G00000", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Yes. It's a surprise home visit.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh!?\nUmm, I'm sorry to say, but my mother\nis--");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0207000_G00100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I'm kidding.");
        Message_Who(0);
        Message_MsgDisp("主人公", ".........");
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(7, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0207000_G00200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Happy birthday.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Wow, thank you very much!\nYou came all the way here, as well.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0207000_G00300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Because I would get scolded by the\nvice principal if someone found out\nat school.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...\nSorry for making you come all the\nway here.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0207000_G00400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "No... It's fine. Happy birthday.\nI will take my leave.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(7, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝ remembered my\nbirthday...)");
        }
    else {
        Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes.");
        SoundEffect_PlayStream(3, "SS_T_00_039_M00");
        Character_Chara_GS2(7, "M7_06F", 0);
        Music_PlayBGM(0, "MN_C_07_002_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝!?\nWhat is the matter...");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("K0207000_G01500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Yes. It's a surprise home visit.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ehh!?\nUmm, I'm sorry to say, but my mother\nis--");
        Voice_PlayVoice("K0207000_G01600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I'm kidding.");
        Message_Who(0);
        Message_MsgDisp("主人公", ".........");
        Character_ChFace(0, 2, 5);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0207000_G01700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Happy birthday. It is a little late.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Wow, thank you very much!\nYou came all the way here, as well.");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0207000_G00300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Because I would get scolded by the\nvice principal if someone found out\nat school.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...\nSorry for making you come all the\nway here.");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0207000_G00400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "No... It's fine. Happy birthday.\nI will take my leave.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(7, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Wakaouji＊＊｝ remembered my\nbirthday...)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 86, 1);
    System_Call_GS2("K02", "M7", 20);
    Parameter_InPl1Param(336, #1);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
