section "k02_g1_010"{
    Character_BlinkStart(10, 1, (#1), 1);
    Character_BlinkStart(10, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_HO100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    SoundEffect_PlayStream(3, "SS_T_00_038_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes～?");
    SoundEffect_PlayStream(3, "SS_T_00_039_M00");
    System_Wait(80);
    Character_Chara_GS2(10, "G1_04F", 0);
    Music_PlayBGM(0, "MN_C_10_000_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Toudou＊＊｝.\nHappy New Year. What's up?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("K0210000_J01600", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "You were born on quite a spectacular\nday.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah. Ah... you remembered?\nI'm so happy!");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("K0210000_J01700", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Here. It's not much, though.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh.... Is this a birthday present?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("K0210000_J01800", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "It's nothing expensive so use it as\nyou see fit.\nSorry for taking some of your time\nso early into the New Year.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("K0210000_J01900", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Later.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(10, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Toudou＊＊｝ came here\njust to give me a present...\nI'm so glad.)");
    }
