section "k02_m4_011"{
    Character_BlinkStart(4, 1, (#1), 1);
    Character_BlinkStart(4, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Character_Chara_GS2(4, "M4_D?F", 0);
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks for walking me home.");
    Voice_PlayVoice("K0204011_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah, it's not worth thanking me\nfor.");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(4, 2, (#1));
    Voice_PlayVoice("K0204011_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Ah... oh yeah. This, too...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("K0204011_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Here's your present.\nHappy birthday to you～♪ ...\nOr something like that.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝... Thanks!");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(4, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("K0204011_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nYou're too grateful for something as\nsimple as this....\nWhat a weird one.");
    Character_BlinkStart(4, 0, (#1));
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("K0204011_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Anyway, I'm going home.\nOpen it in secret later. See you!");
    Character_Chara_GS2(4, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Haha, this was an amazing\nbirthday!)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    System_Call_GS2("K02", "M4", 20);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
