section "k02_m5_000"{
    Character_BlinkStart(5, 1, (#1), 1);
    Character_BlinkStart(5, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    if (Parameter_ChkPlayer(6) == 1){
        Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes～.");
        SoundEffect_PlayStream(3, "SS_T_00_039_M00");
        Character_Chara_GS2(5, "M5_??F", 0);
        Music_PlayBGM(0, "MN_C_05_002_D00", 127, 40);
        Voice_PlayVoice("K0205000_E00000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hello.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝.\nWhat's up?");
        Voice_PlayVoice("K0205000_E00100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh? For me...?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0205000_E00200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah. Happy Birthday.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You remembered? I'm so happy.\nThanks!");
        Voice_PlayVoice("K0205000_E00300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "You're welcome▼ I'm glad I could\ndirectly say it to you.\nI'll see you later.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(5, "NON");
        }
    else if (Parameter_ChkPlayer(6) == 0){
        Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes～.");
        SoundEffect_PlayStream(3, "SS_T_00_039_M00");
        Character_Chara_GS2(5, "M5_??F", 0);
        Music_PlayBGM(0, "MN_C_05_002_D00", 127, 40);
        Voice_PlayVoice("K0205000_E00000", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hello.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝.\nWhat's up?");
        Voice_PlayVoice("K0205000_E00100", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh. For me...?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(5, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0205000_E00200", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Yeah. Happy Birthday.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You remembered? I'm so happy.\nThanks!");
        Voice_PlayVoice("K0205000_E00300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "You're welcome▼ I'm glad I could say\nit directly to you.\nI will see you later.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(5, "NON");
        }
    else {
        Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes.");
        SoundEffect_PlayStream(3, "SS_T_00_039_M00");
        Character_Chara_GS2(5, "M5_??F", 0);
        Music_PlayBGM(0, "MN_C_05_002_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝.\nWhat's up?");
        Voice_PlayVoice("K0205000_E01300", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Hello. And here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh...?");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("K0205000_E01400", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I'm sorry it's late.\nI wanted to give it to you on the\nactual day, but I didn't have the\ntime.");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(5, 3, (#1));
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("K0205000_E01500", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Happy Birthday.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You remembered...\nJust that makes me happy...");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("K0205000_E01600", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "Seeing you teary also makes me\nteary.");
        Voice_PlayVoice("K0205000_E01700", #1, "");
        Message_Who(5);
        Message_MsgDisp("Chris", "I will leave now. Good bye.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(5, "NON");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    System_Call_GS2("K02", "M5", 20);
    Parameter_InPl1Param(336, #1);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
