section "k02_m8_011"{
    Character_BlinkStart(8, 1, (#1), 1);
    Character_BlinkStart(8, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Character_Chara_GS2(8, "M8_D?F", 0);
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Thank you very much for driving me\nhome.");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(8, 2, (#1));
    Voice_PlayVoice("K0208011_H00000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah.... Right, I almost forgot.\nHere.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("K0208011_H00100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "It's your birthday today, right?\nHappy Birthday.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... You remembered? I'm glad.\nThank you very much!");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("K0208011_H00200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "...\nI'm glad that I could see that\nsmile.\nLater.");
    Character_Chara_GS2(8, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Haha, this was an amazing\nbirthday!)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    System_Call_GS2("K02", "M8", 20);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
