section "d01_m9_006"{
    Character_BlinkStart(9, 1, (#1), 1);
    Character_BlinkStart(9, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_WF000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It doesn't seem like Akagi-kun is\nhere, yet.)");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He's late...)");
    Voice_PlayVoice("D0109006_W00000", #1, "");
    Message_Who(20);
    Message_Who(20);
    Message_MsgDisp("？？？", "Hello, miss▼");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah!");
    Character_Chara_GS2(20, "N1_17F", 0);
    Voice_PlayVoice("D0109006_W00100", #1, "");
    Message_Who(20);
    Message_Who(20);
    Message_MsgDisp("Playboy", "Sorry! Did I surprise you?\nHey, so where are you going now?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Um, I'm waiting for someone.");
    Voice_PlayVoice("D0109006_W00200", #1, "");
    Message_Who(20);
    Message_Who(20);
    Message_MsgDisp("Playboy", "But they're not coming!\nI've been watching you for a while\nnow!");
    Message_Who(0);
    Message_MsgDisp("主人公", "They'll come! Please leave me alone.");
    SoundEffect_PlayStream(2, "SS_T_00_020_M00");
    Voice_PlayVoice("D0109006_W00300", #1, "");
    Message_Who(20);
    Character_Chara_GS2(20, "NON");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(20);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_WF200_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(*Pant* *Pant*... That was scary.\nGeez! This is Akagi-kun's fault!)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(What should I do...?\nPerhaps I should go back.\nBut what if that guy is still\nthere...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Why didn't I ask for his contact\ndetails...?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, right!\nIf I go to the hall, he'll be in the\nseat next to mine!)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_WF400_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_WindowPosition(1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Umm～... My ticket, my ticket...)");
    Still_Approach(9, 240, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh?\nI didn't drop it when I was running,\nright...?)");
    if (System_GlobalWork(10, 1) == 1){
        Still_Approach(9, 240, 0, 0, 1, 5);
        Message_Who(0);
        Message_MsgDisp("主人公", "(What should I do?)");
        if (System_GlobalWork(10, 1) == 1){
            Still_Approach(9, 240, 0, 0, 1, 9);
            Message_Who(0);
            Message_MsgDisp("主人公", "(At this rate...)");
            if (System_GlobalWork(10, 1) == 1){
                Message_Who(0);
                Message_MsgDisp("主人公", "(If I run, I'll still make it in\ntime for the start.\nI have to hurry!)");
                System_GlobalWork(20, 0, 2);
                SoundEffect_PlayStream(2, "SS_T_00_020_M00");
                }
            }
        }
    Still_ApproachEnd();
    Message_WindowPosition(0);
    if (System_GlobalWork(20, 1) != 2){
        Message_CloseMsg();
        Screen_WipeOut(2);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Background_Bg_GS2("BG_WF400_CO_1", #1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Sigh*...\nI couldnt find the ticket in the\nend.\nAkagi-kun is probably angry.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I'll be able to see him if I wait\nhere.\nI have to apologize to him...)");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Voice_PlayVoice("D0109006_I00400", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "......");
        Character_ChFace(0, 0, 8);
        Character_Chara_GS2(9, "M9_04F", 0);
        Music_PlayBGM(0, "MN_C_09_001_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, Akagi-kun! I'm sorry!\nThe ticket, I--");
        Voice_PlayVoice("D0109006_I00500", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "You did a pretty awful thing.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Eh?");
        Voice_PlayVoice("D0109006_W00600", #1, "");
        Message_Who(0);
        Message_MsgDisp("Little Girl", "Yuki～! Hurry～! Let's go eat!");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Who is that?");
        Character_BlinkStart(9, 2, (#1), 1);
        Voice_PlayVoice("D0109006_I00700", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "A girl in my class.\nShe happened to have your ticket.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nThat's because the ticket--");
        Character_BlinkStart(9, 0, (#1), 1);
        Voice_PlayVoice("D0109006_I00800", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "She bought it from a ticket scalper.\nBut you already know that.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... I didn't...");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(9, 2, (#1), 1);
        Voice_PlayVoice("D0109006_I00900", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "If you didn't want to come, all you\nhad to do was say so.\nYou didn't have to be so indirect.\nSee you...");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(9, "NON");
        Voice_PlayVoice("D0109006_W01000", #1, "");
        Message_Who(0);
        Message_MsgDisp("Little Girl", "Yuki! Over here! Hurry!");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I lost the ticket.\nI'm the one who wronged him...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(So Akagi-kun is called \"Yuki\" in\nclass....\nAnd what a pretty girl he was with.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(... I want to cry.\nI should go home.)");
        }
    else {
        Message_CloseMsg();
        Screen_WipeOut(2);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Background_Bg_GS2("BG_WF460_CO_0", #1, #1, 0);
        Environment_PlayME(0, "SN_BGE_027_014", 127, 40);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(First level, F21...)");
        Character_ChFace(0, 0, 8);
        Character_Chara_GS2(9, "M9_04F", 0);
        Environment_StopME(1, 80);
        Music_PlayBGM(0, "MN_C_09_000_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Akagi-kun! Sorry I'm late.");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(9, 3, (#1));
        Voice_PlayVoice("NS_09_000_00000", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "*Sigh*...\nI thought I'd get angry at you, but\nthere's no way I can do that if you\nmake a face like that, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Uh...");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(9, 1, (#1));
        Character_BlinkStart(9, 0, (#1));
        Voice_PlayVoice("NS_09_000_00100", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "It's fine.\nI was actually quite down, thinking\nthat perhaps you wouldn't come.\nThat's why I'm happy now.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Akagi-kun...");
        SoundEffect_PlayStream(3, "SS_DSE_121_000");
        Music_StopBGM(0, 40);
        System_Wait(70);
        SoundEffect_PlayStream(3, "GAYA_KANSEI_LOOP");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("NS_09_000_00200", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "It seems like it's about to start.\nI'll listen to your explanation\nlater.\nLet's have fun.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Screen_WipeIn(2);
        Music_PlayBGM(0, "SUPER_CHARGER", 127, 40);
        Voice_PlayVoice("NS_09_000_00300", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Wah, look out!");
        Character_Chara_GS2(9, "NON");
        Still_Event("EV_09_07", #1, 0, 60);
        Message_Who(0);
        Message_MsgDisp("主人公", "Thanks!!");
        Voice_PlayVoice("NS_09_000_00400", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "You're welcome!! ...\nIt's so noisy here.\nI actually can't understand a thing.");
        Still_Approach(9, 241, 0, 0, 1, 1);
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!? Did you say something!?");
        Still_ApproachEnd();
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("NS_09_000_00500", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "It's nothing!!");
        Still_StillFace(0, 0, 2);
        Still_StillFace(0, 6, 3);
        Voice_PlayVoice("NS_09_000_00600", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "SUPER CHARGER is the best!!");
        Message_Who(0);
        Message_MsgDisp("主人公", "The best!!");
        Still_StillFace(0, 0, 1);
        Still_Approach(9, 241, 0, 0, 1, 5);
        Voice_PlayVoice("NS_09_000_00700", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Dear, oh dear.\nIf you smile like that...");
        Still_ApproachEnd();
        Message_Who(0);
        Message_MsgDisp("主人公", "Did you say something!?");
        Still_StillFace(0, 0, 2);
        Still_Approach(9, 241, 0, 0, 0, 9);
        Voice_PlayVoice("NS_09_000_00800", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "SUPER CHARGER is the best!!");
        Still_ApproachEnd();
        Message_Who(0);
        Message_MsgDisp("主人公", "The best!!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Still_Event("");
        Music_StopBGM(0, 40);
        SoundEffect_StopStream(3, 40);
        Character_Chara_GS2(9, "NON");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Background_Bg_GS2("BG_WF400_CO_1", #1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Sorry to make you wait, Akagi-kun.\nThe bathroom was crowded.\nThanks for... Huh?");
        Voice_PlayVoice("NS_F2_090_00000", #1, "");
        Message_Who(0);
        Message_MsgDisp("Girl", "Everyone was all over the place\ntrying to buy tickets from that\nticket scalper, but you managed to\nget some?");
        Voice_PlayVoice("NS_09_000_00900", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "Well, with much trouble.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Akagi-kun!?)");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(9, "M9_04F", 0);
        Voice_PlayVoice("NS_F2_090_00100", #1, "");
        Message_Who(0);
        Message_MsgDisp("Girl", "But I did't know that you were a\nSUPER CHARGER fan, Yuki!");
        Voice_PlayVoice("NS_09_000_01000", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Well, yeah. I didn't know either.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(\"Yuki\". Who is that?\nThey seem like they get along\nwell...)");
        Voice_PlayVoice("NS_F2_090_00200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Girl", "Hey, you're coming to eat with us,\nright?");
        Message_Who(0);
        Message_MsgDisp("主人公", "(!!)");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("NS_09_000_01100", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Eh!? Ah, I kind of can't...");
        Voice_PlayVoice("NS_F2_090_00300", #1, "");
        Message_Who(0);
        Message_MsgDisp("Girl", "Come on, let's go!");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("NS_09_000_01200", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "No, how should I say it. I can't...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Why is he being so wishy-washy\nabout it!?)");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("NS_09_000_01300", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Hm?");
        Message_Who(0);
        Message_MsgDisp("主人公", "......");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("NS_09_000_01400", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "W-What, you were here the whole\ntime!?\nYou took your time.");
        Voice_PlayVoice("NS_F2_090_00400", #1, "");
        Message_Who(0);
        Message_MsgDisp("Girl", "Oh no!?\nYou should have told me earlier!\nI'll see you at school then!");
        SoundEffect_PlayStream(3, "SS_T_00_099_M00");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("NS_09_000_01500", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Ah, yeah.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... It's fine, you can go.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("NS_09_000_01600", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "What are you saying?\nI mean since we have that...\nyou know!\nThe platinum ticket--");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's not like I asked you to get it\nfor me.");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("NS_09_000_01700", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "...\nWhat's wrong with you all of a\nsudden?\nYou're being childish.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You too! Being called \"Yuki\"...\nJust like a girl.");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 2, 0);
        Voice_PlayVoice("NS_09_000_01800", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Um, are you perhaps... Jealous?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Who's jealous? I'm leaving!!");
        SoundEffect_PlayStream(3, "SS_T_00_099_M00");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("NS_09_000_01900", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Sorry, wait!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(9, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(As if I'm jealous!\nAll he had to say was \"I'm on a\ndate\", like a man!)");
        Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(... Huh?\nBut from the start, Akagi-kun had\nnever called it a \"date\"...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(And he has such a pretty friend.\nI somehow... misunderstood.)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(9, 86, 1);
    }
