section "d01_m2_004"{
    Character_BlinkStart(2, 1, (#1), 1);
    Character_BlinkStart(2, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    if (Parameter_GetPl1Param(25) == 1){
        Environment_PlayME(0, "SEQ_SE_EV_114_ENV", 127, 40);
        Background_Bg_GS2("BG_SC420_?_0", 1, #1, 0);
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(2, "M2_01F", 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("", 2, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Shiba＊＊｝...");
        Character_ChFace(0, 2, 4);
        Voice_PlayVoice("D0102004_B00000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... What's wrong?\nYou look like you're going to cry.");
        Message_Who(0);
        Message_MsgDisp("主人公", "The pitcher from the other school...");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(2, 2, (#1), 1);
        Voice_PlayVoice("D0102004_B00100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Pitcher?");
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(2, 0, (#1), 1);
        Voice_PlayVoice("D0102004_B00200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Him... Where have I...");
        Voice_PlayVoice("D0102004_W00300", #1, "");
        Message_Who(0);
        Message_MsgDisp("President", "Wah!");
        SoundEffect_PlayStream(2, "EV_SE_056");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah!");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("D0102004_B00400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... It's him...!");
        Voice_PlayVoice("D0102004_W00500", #1, "");
        Message_Who(0);
        Message_MsgDisp("Club Member B", "Manager!\nPlease take care of his injuries!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yes!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(We're winning, so the pitcher is\nthrowing nothing but dead balls, how\nawful...!)");
        Message_Who(0);
        Message_MsgDisp("主人公", "Sorry, ｛Shiba＊＊｝.\nJust wait...");
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("", 2, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Voice_PlayVoice("D0102004_B00600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Can you do something for me?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh... what...?");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(2, "NON");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        SoundEffect_PlayStream(2, "EV_SE_GAYA_007");
        Background_Bg_GS2("BG_SC420_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("D0102004_W00700", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "Hey now, who's the next batter～.\nAh～, you guys are so wimpy.");
        Still_Event("EV_02_09", #1, 0, 60);
        SoundEffect_StopStream(2, 60);
        Music_PlayBGM(0, "MN_C_02_000_D01", 127, 40);
        Voice_PlayVoice("D0102004_B00800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... I'm next.");
        Voice_PlayVoice("D0102004_W00900", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "... Huh? Who the hell are...... Hmm?");
        Voice_PlayVoice("D0102004_W01000", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "You're... Shiba!");
        Message_Who(2);
        Message_MsgDisp("Shiba", "......");
        Voice_PlayVoice("D0102004_W01200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "Eh～...\nAfter that violent incident, you\nstill have the guts to just stroll\nonto the baseball field!");
        Voice_PlayVoice("D0102004_W01300", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "Anyway～, are you even a club member?\nDon't just go joining whenever you\nwant!");
        Voice_PlayVoice("D0102004_B01400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Bad news.\nI just joined the club.");
        Voice_PlayVoice("D0102004_W01500", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "Huh?");
        Still_Approach(2, 38, 0, 0, 1, 1);
        Voice_PlayVoice("D0102004_B01600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "I'm saying that I'm a Baseball Club\nmember....\nIf you've got the time to babble,\nwhy don't you try pitching instead?");
        Still_ApproachEnd();
        Voice_PlayVoice("D0102004_W01700", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "-- As always, you don't know when to\nquit!\nThen have a taste of this!");
        SoundEffect_PlayStream(2, "SS_T_00_135_M00_02");
        Still_Event("EV_02_10", #1, 1, 60);
        Still_Approach(2, 39, 1, 0, 1, 1);
        Music_StopBGM(0, 20);
        System_Wait(1);
        Environment_StopME(0, 20);
        Voice_PlayVoice("D0102004_B01800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", ".........!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Still_Event("");
        SoundEffect_PlayStream(2, "EV_SE_060");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        SoundEffect_StopStream(2, 40);
        System_Wait(60);
        Background_Bg_GS2("BG_SC420_?_1", 1, #1, 0);
        Character_BlinkStart(2, 3, (#1), 1);
        Character_Chara_GS2(2, "M2_01F", 0);
        Music_PlayBGM(0, "MN_C_02_002_D01", 127, 40);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Sorry to keep you waiting,\n｛Shiba＊＊｝!");
        Character_BlinkStart(2, 0, (#1), 1);
        Voice_PlayVoice("D0102004_B01900", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "It's alright....\nI'm sorry that I got you involved.");
        Message_Who(0);
        Message_MsgDisp("主人公", "No, it's fine.");
        Message_Who(0);
        Message_MsgDisp("主人公", "The Baseball Club advisor said that\nyou were more than welcome here.\nWe also won the game!");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(2, 3, (#1), 1);
        Voice_PlayVoice("D0102004_B02000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...\nI had the determination to join,\nthanks to you being there for me.\nThanks.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I didn't do anything...");
        Voice_PlayVoice("D0102004_B02100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "No, you did.");
        Character_ChFace(0, 0, 0);
        Character_BlinkStart(2, 0, (#1), 1);
        Voice_PlayVoice("D0102004_B02200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...\nIf you weren't here, I'd just be\nstanding over there, watching...");
        Voice_PlayVoice("D0102004_B02300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "I think I'd be standing there, like\nI was in middle school.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Shiba＊＊｝...");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("D0102004_B02400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "So... thank you....\nI look forward to working with you,\nmanager.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah! Me too!");
        }
    else {
        Environment_PlayME(0, "SEQ_SE_EV_114_ENV", 127, 40);
        Background_Bg_GS2("BG_SC420_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Now maybe Hanegasaki Academy's\nBaseball Club can win!)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Huh...\nIs that ｛Shiba＊＊｝ over\nthere?)");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Shiba＊＊｝!");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 0);
        Character_Chara_GS2(2, "M2_01F", 0);
        Voice_PlayVoice("", 2, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... ｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Are you here to cheer for the\nBaseball Club?");
        Character_BlinkStart(2, 3, (#1), 1);
        Voice_PlayVoice("D0102004_B02600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Maybe...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(What's wrong with\n｛Shiba＊＊｝...\nHe looks like he's in a foul mood.)");
        Character_ChFace(0, 0, 8);
        Character_BlinkStart(2, 0, (#1), 1);
        Voice_PlayVoice("D0102004_W02700", #1, "");
        Message_Who(0);
        Message_MsgDisp("President", "That pitcher plays so dirty!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Eh!?)");
        Voice_PlayVoice("D0102004_W02800", #1, "");
        Message_Who(0);
        Message_MsgDisp("Club Member B", "He's continually throwing dead balls\nbecause we're winning.\nLet's withdraw!");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Shiba＊＊｝... This is...");
        Voice_PlayVoice("D0102004_B02900", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...\nThat guy's been pitching dangerously\nfor a while now.");
        Character_BlinkStart(2, 2, (#1), 1);
        Voice_PlayVoice("D0102004_B03000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...\nThat punk, he hasn't changed at\nall...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh? Ah, wait...\n｛Shiba＊＊｝!?");
        Character_Chara_GS2(2, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Shiba＊＊｝...\nHe went to the bench.\nWhat are they talking about...)");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        SoundEffect_PlayStream(2, "EV_SE_GAYA_007");
        Background_Bg_GS2("BG_SC420_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("D0102004_W03100", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "Hey now, who's the next batter?\nAh～, you guys are so wimpy.");
        Still_Event("EV_02_09", #1, 0, 60);
        SoundEffect_StopStream(2, 60);
        Music_PlayBGM(0, "MN_C_02_000_D01", 127, 40);
        Voice_PlayVoice("D0102004_B03200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... I'm next.");
        Voice_PlayVoice("D0102004_W03300", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "... Huh? Who the hell are...... Hmm?");
        Voice_PlayVoice("D0102004_W03400", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "You're... Shiba!");
        Message_Who(2);
        Message_MsgDisp("Shiba", "......");
        Voice_PlayVoice("D0102004_W03600", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "Eh...\nAfter that violent incident, you\nstill have the guts to just stroll\nonto the baseball field!");
        Voice_PlayVoice("D0102004_W03700", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "Anyway, are you even a club member?\nDon't just go joining whenever you\nwant!");
        Voice_PlayVoice("D0102004_B03800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Bad news.\nI just joined the club.");
        Voice_PlayVoice("D0102004_W03900", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "Huh?");
        Still_Approach(2, 38, 0, 0, 1, 1);
        Voice_PlayVoice("D0102004_B04000", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "I'm saying that I'm a Baseball Club\nmember....\nIf you've got the time to babble,\nwhy don't you try pitching instead?");
        Still_ApproachEnd();
        Voice_PlayVoice("D0102004_W01700", #1, "");
        Message_Who(0);
        Message_MsgDisp("Rival", "--As always, you don't know when to\nquit!\nThen have a taste of this!");
        SoundEffect_PlayStream(2, "SS_T_00_135_M00_02");
        Still_Event("EV_02_10", #1, 1, 60);
        Still_Approach(2, 39, 1, 0, 1, 1);
        Music_StopBGM(0, 40);
        System_Wait(1);
        Environment_StopME(0, 20);
        Voice_PlayVoice("D0102004_B04200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", ".........!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Still_Event("");
        SoundEffect_PlayStream(2, "EV_SE_060");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Character_Chara_GS2(2, "M2_01F", 0);
        SoundEffect_StopStream(2, 40);
        System_Wait(60);
        Background_Bg_GS2("BG_SC420_?_1", 1, #1, 0);
        Music_PlayBGM(0, "MN_C_02_002_D01", 127, 40);
        Screen_WipeIn(2);
        Voice_PlayVoice("", 2, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "｛主人公｝.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Shiba＊＊｝!\nAre you alright?");
        Voice_PlayVoice("D0102004_B04300", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "Yeah.... Sorry for making you wait.");
        Message_Who(0);
        Message_MsgDisp("主人公", "No, I'm fine...\nWhat did the advisor say?");
        Character_BlinkStart(2, 3, (#1), 1);
        Voice_PlayVoice("D0102004_B04400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...\nIf I've got the will to play, I'm\nwelcome here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That's great...!");
        Character_ChFace(0, 0, 6);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("D0102004_B04500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...\nI had the determination to join,\nthanks to you being there for me.\nThanks.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh. I didn't do anything...");
        Character_BlinkStart(2, 3, (#1), 1);
        Voice_PlayVoice("D0102004_B04600", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "No, you did.");
        Character_ChFace(0, 0, 0);
        Character_BlinkStart(2, 3, (#1), 1);
        Voice_PlayVoice("D0102004_B04700", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "...\nIf you weren't here, I'd just be\nstanding over there, watching...");
        Character_BlinkStart(2, 0, (#1), 1);
        Voice_PlayVoice("D0102004_B04800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "I think I'd be standing there, like\nI was in middle school.");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Shiba＊＊｝...");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("D0102004_B04900", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "So... thank you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... No problem. Do your best!");
        }
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_InCh1Param(2, 25, 1);
    Parameter_AddCh1Param(2, 86, 1);
    Parameter_AddCh1Param(2, 61, 6);
    Parameter_AddCh1Param(2, 60, 3);
    Parameter_AddCh1Param(2, 62, #5);
    }
