section "d01_m1_002"{
    Character_BlinkStart(1, 1, (#1), 1);
    Character_BlinkStart(1, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0 = Parameter_GetPl1Param(12);
    switch (var0){
        case 0:
        Background_Bg_GS2("BG_HO200_SU_0", #1, #1, 0);
        break ;
        case 1:
        Background_Bg_GS2("BG_HO210_SU_0", #1, #1, 0);
        break ;
        case 2:
        Background_Bg_GS2("BG_HO220_SU_0", #1, #1, 0);
        break ;
        case 3:
        Background_Bg_GS2("BG_HO230_SU_0", #1, #1, 0);
        break ;
        }
    Screen_WipeIn(2);
    SoundEffect_PlaySE(19, 127);
    System_Wait(#300);
    SoundEffect_StopSE(19, 0);
    SoundEffect_PlaySE(20, 127);
    Voice_PlayVoice("D0101002_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Hello? It's me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Saeki＊＊｝.\nWhat's up?");
    Voice_PlayVoice("D0101002_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Hey, you're free now, right?\nThe weather's nice today, and the\nsea is calm, so do you want to go to\nthe beach?");
    Message_Who(0);
    Message_MsgDisp("主人公", "...\nIt's a little sudden, but it sounds\nlike a good idea!");
    Voice_PlayVoice("D0101002_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Okay then. So hurry up.\nDon't forget your swimsuit, okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I won't forget!\nI mean, we're going to the beach,\nright?");
    Voice_PlayVoice("D0101002_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Hahaha.");
    Message_Who(0);
    Message_MsgDisp("主人公", "......?");
    Voice_PlayVoice("D0101002_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Let me just say this, don't come in\nyour school swimsuit-- No, those are\nprobably better these days...");
    Message_Who(0);
    Message_MsgDisp("主人公", "???");
    Voice_PlayVoice("D0101002_A00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Anyway, hurry up.\nAh, the beach is already crowded, so\nI'll be waiting at Sangosho.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sangosho, is it? Got it!");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Still_Event("EV_01_08", #1, 0, 20);
    Still_StillFace(0, 0, 1);
    Environment_PlayME(1, "SN_P_00_026_000", 127, 0);
    Music_PlayBGM(0, "MN_C_01_003_D01", 127, 40);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh～...\nI've bought wafers, stuffed olives,\nbean sprouts and sobatama!");
    Voice_PlayVoice("D0101002_A00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Nice!\nNow, take this order of \"Tropical\nYakisoba\" to table three when it's\ndone.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Hey.\nDid you call me out today to help\nout at the store?");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0101002_A00700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Don't think. Move.\nNow hurry and change into your\nswimsuit and put an apron on.\nThen work the floor.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ugh... Do I have to do it?\nIt's embarrassing.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0101002_A00800", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "It's not.\nThink of the financial benefit\nSangosho will get from a female high\nschool student in a swimsuit and\napron.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝, you pervert!\nEvil!");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0101002_A00900", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Say what you want. Hurry.\nThe \"Tropical Yakisoba\".");
    Message_Who(0);
    Message_MsgDisp("主人公", "......");
    Voice_PlayVoice("D0101002_W01000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Customer", "Young man!\nPlease attend to me, too▼");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 6, 0);
    Still_Approach(1, 7, 0, 0, 0, 1);
    Voice_PlayVoice("D0101002_A01100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Yes! Coming!");
    Still_ApproachEnd();
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("D0101002_A01200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Tropical Yakisoba!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Damn, I've been had!)");
    Message_CloseMsg();
    Environment_StopME(1, 40);
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Still_Event("");
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    Parameter_AddCh1Param(1, 61, 6);
    Parameter_AddCh1Param(1, 60, 3);
    Parameter_AddCh1Param(1, 62, #5);
    }
