section "d01_m1_003"{
    Character_BlinkStart(1, 1, (#1), 1);
    Character_BlinkStart(1, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC910_LI_0", #1, #1, 0);
    Music_PlayBGM(0, "MN_B_SC_910_000", 127, 40);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(I'm glad that our cafe is doing\nwell, but...\nit's a little crowded.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(What should I do...\nAt this rate, I might not be able to\ntend to the customers...)");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(1, "M1_01F", 0);
    Voice_PlayVoice("", 1, "D0101003_A00000");
    Message_Who(1);
    Message_MsgDisp("Saeki", "｛主人公｝.\nWhy are you pacing around?\nAre you a hamster?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Saeki＊＊｝! Yeah...\nWe're a little short-handed at the\nmoment.");
    Character_BlinkStart(1, 2, (#1), 1);
    Voice_PlayVoice("D0101003_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "No, you're not.\nIt's a question of skills.\nYou can't serve all the customers.\nYou guys are inefficient.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah～... Oh, right!\nHelp us out a little,\n｛Saeki＊＊｝.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(1, 0, (#1), 1);
    Voice_PlayVoice("D0101003_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Sorry, I can't, I'm a customer.\nOne hot coffee, please.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Come on!\nYou're a pro, ｛Saeki＊＊｝!\nSo isn't this your forte?");
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0101003_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Wah! Idiot!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Please!\nThere are some aprons over there!");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(1, 3, (#1), 1);
    Voice_PlayVoice("D0101003_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "You...");
    Music_StopBGM(0, 40);
    Environment_StopME(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(1, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Still_Event("EV_01_09", #1, 0, 60);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_01_000_D00", 127, 40);
    Voice_PlayVoice("D0101003_A00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "An order. One hot coffee.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Understood!");
    Voice_PlayVoice("D0101003_A00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "While you're at it, clean up table\nthree.\nAlso, have two people clean the\ndishes.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay!");
    Voice_PlayVoice("D0101003_W00700", #1, "");
    Message_Who(0);
    Message_MsgDisp("Customer A", "Look, a prince!\nHow cool～▼");
    Voice_PlayVoice("D0101003_W00800", #1, "");
    Message_Who(0);
    Message_MsgDisp("Customer B", "He looks so good as a waiter～▼ Hey,\nlet's have a drink here!");
    Voice_PlayVoice("D0101003_A00900", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Welcome.\nI will show you to your table.");
    Still_Approach(1, 8, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(As expected of\n｛Saeki＊＊｝...\nThe orders are now settled.)");
    Still_ApproachEnd();
    Character_ChFace(0, 3, 2);
    Character_BlinkStart(1, 3, (#1), 1);
    Character_Chara_GS2(1, "M1_01F", 0);
    Background_Bg_GS2("BG_SC910_LI_0", #1, #1, 0);
    Still_Event("");
    Voice_PlayVoice("D0101003_A01000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "*Phew*... We can relax for a moment.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Thanks to you, we somehow got\nthrough it all.\nThanks, ｛Saeki＊＊｝.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0101003_A01100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Well.\nIt's expected if I'm the one\nmanaging this place.");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(1, 2, (#1), 1);
    Voice_PlayVoice("D0101003_A01200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ah, I'm tired... Get me a coffee.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay～! One hot coffee!\nThat will be 1 Rich.");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(1, 0, (#1), 1);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0101003_A01300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "You're charging me?");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    Parameter_AddCh1Param(1, 61, 6);
    Parameter_AddCh1Param(1, 60, 3);
    Parameter_AddCh1Param(1, 62, #5);
    }
