section "d01_m2_002"{
    Character_BlinkStart(2, 1, (#1), 1);
    Character_BlinkStart(2, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC421_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Next is... the 400m race. Hmm?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝!\nWhy are you hurrying?");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(2, "M2_08F", 0);
    Voice_PlayVoice("D0102002_B00000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Ah.\nThe guy who was supposed to run the\n400m race got injured, so I'm taking\nhis place.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Really? Do your best!");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0102002_B00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Yeah.");
    Character_Chara_GS2(2, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Alright, I'll cheer for him!)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Voice_PlayVoice("D0102002_W00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Student Council", "Ready. Set!");
    Message_CloseMsg();
    System_Wait(10);
    SoundEffect_PlayStream(2, "SE_PISTOL");
    Music_StopBGM(0, 40);
    Music_PlayBGM(0, "MN_C_02_000_D00", 127, 40);
    Still_Event("EV_02_07", #1, 0, 60);
    Screen_WipeIn(2);
    Still_Approach(2, 36, 1, 0, 1, 1);
    System_Wait(60);
    Screen_WipeOut(2);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Environment_StopME(1, 40);
    Character_Chara_GS2(2, "M2_08F", 0);
    Background_Bg_GS2("BG_SC421_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝,\ncongratulations on first place!");
    Voice_PlayVoice("D0102002_B00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Ah... Thanks.");
    Message_Who(0);
    Message_MsgDisp("主人公", "You run really fast,\n｛Shiba＊＊｝.");
    Voice_PlayVoice("D0102002_B00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Really?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah! Everyone was surprised.");
    Message_Who(0);
    Message_MsgDisp("主人公", "You could probably pass for a member\nof the Track and Field Club.");
    Character_BlinkStart(2, 2, (#1), 1);
    Voice_PlayVoice("D0102002_B00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Track and Field, huh...");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(2, 3, (#1), 1);
    Voice_PlayVoice("D0102002_B00600", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Maybe I should try joining?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... ｛Shiba＊＊｝?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0102002_B00700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... It's nothing.\nI'm going to wash my face.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, okay...");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(2, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Even though he won first place, he\nlooked sad...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 86, 1);
    Parameter_AddCh1Param(2, 61, 6);
    Parameter_AddCh1Param(2, 60, 3);
    Parameter_AddCh1Param(2, 62, #5);
    }
