section "d01_m8_002"{
    Character_BlinkStart(8, 1, (#1), 1);
    Character_BlinkStart(8, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC302_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's a little late.\nI should go home now.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_SC100_AU_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("", 8, "");
    Message_Who(8);
    Message_MsgDisp("？？？", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes? Ah... ｛Masaki＊＊｝!");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(8, "M8_06F", 0);
    Music_PlayBGM(0, "MN_C_08_002_D00", 127, 40);
    Voice_PlayVoice("D0108002_H00000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yo.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Are you making a delivery?");
    Voice_PlayVoice("D0108002_H00100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "No.\nI came here to see what it feels\nlike to be a high schooler.");
    Message_Who(0);
    Message_MsgDisp("主人公", "A high schooler... was it?");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(8, 3, (#1), 1);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("D0108002_H00200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah....\nI thought I'd walk home with you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...\nSo were you perhaps waiting all\nthis...");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0108002_H00300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Don't finish what you're saying! ...\nIt's awkward and it's embarrassing!");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay.");
    Character_ChFace(0, 3, 3);
    Character_BlinkStart(8, 0, (#1), 1);
    Voice_PlayVoice("D0108002_H00400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "What have you got planned now?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Nothing.");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("D0108002_H00500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... I see. So, should we go?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(8, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Still_Event("EV_08_09", #1, 0, 60);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0108002_H00600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "You were at school quite late.");
    Message_Who(0);
    Message_MsgDisp("主人公", "It just happened to be today.\nI was asking the teachers many\nthings.");
    Still_StillFace(0, 6, 2);
    Still_Approach(8, 218, 0, 0, 1, 1);
    Voice_PlayVoice("D0108002_H00700", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Wakaouji-sensei?\nEven though he looks like that, he\nreally gives his students a hard\ntime...");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0108002_H00800", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Oh yeah, is there still, \"The 7\nWonders of Hanegasaki\"?");
    Message_Who(0);
    Message_MsgDisp("主人公", "There were 7 Wonders?");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("D0108002_H00900", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "There are!");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0108002_H01000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "If you hang a wish on the ribcage of\nthe skeleton in the science room, it\nwill come true.\nLike it did for Wakaouji.");
    Voice_PlayVoice("D0108002_H01100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "The coffee that Wakaouji makes with\nhis flask siphon makes him smarter\nfor three days.");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0108002_H01200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "...\nWell rather than, \"The 7 Wonders of\nHanegasaki\", it's more like, \"The 7\nWonders of Wakaouji\".");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ahaha, it's my first time hearing\nthis!");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0108002_H01300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Really?\nMaybe those rumors were around when\nI attended school.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Are there more?");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("D0108002_H01400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah, another one is...");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_Chara_GS2(8, "M8_06F", 0);
    Background_Bg_GS2("BG_HO000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0108002_H01500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "We're here!\nTalking while walking goes by so\nquickly.");
    Message_Who(0);
    Message_MsgDisp("主人公", "It does.\nDid you get a taste of what being a\nhigh schooler feels like?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0108002_H01600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Haha, I did. It was perfect.");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("D0108002_H01700", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "It was nostalgic...\nI was a little happy that I could\nwalk home with you, seeing the same\nscenery.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Masaki＊＊｝...");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(8, 3, (#1), 1);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("D0108002_H01800", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Next time I'll come wearing the\nuniform.\nIt'll increase the high schooler\nfeeling even more.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh!? Are you really going to do it?");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(8, 0, (#1), 1);
    Voice_PlayVoice("D0108002_H01900", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... It was a joke!\nAs if I would ever do that...\nYou're really cute.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uhh...");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0108002_H02000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Now then, I should go home.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, okay!\nThank you very much for walking me\nhome.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0108002_H02100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... I should be thanking you. Later.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(8, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I never thought I'd walk home from\nschool with ｛Masaki＊＊｝...\nIt felt a little embarrassing.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(8, 86, 1);
    Parameter_AddCh1Param(8, 61, 6);
    Parameter_AddCh1Param(8, 60, 3);
    }
