section "d01_m4_002"{
    Character_BlinkStart(4, 1, (#1), 1);
    Character_BlinkStart(4, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 4);
    Character_BlinkStart(4, 3, (#1), 1);
    Character_Chara_GS2(4, "M4_01F", 0);
    Background_Bg_GS2("BG_SC302_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_04_000_D00", 127, 40);
    Voice_PlayVoice("D0104002_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\n*Phew*");
    SoundEffect_PlayStream(2, "SE_CLAP_01");
    Message_Who(0);
    Message_MsgDisp("主人公", "What an amazing song!");
    SoundEffect_StopStream(2, 40);
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(4, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0104002_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Right?\nI composed it with confidence!\nIt also goes well at lives.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(4, 3, (#1), 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0104002_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "But...\nIf I were to tally how satisfied I\nwas with it...");
    Voice_PlayVoice("D0104002_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "If only I could always sing like\nthis...\n*Sigh*");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(4, 0, (#1), 1);
    Voice_PlayVoice("D0104002_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Ah, whatever.\nYou're going home now, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah.\nWhat about you,\n｛Hariya＊＊｝?");
    Voice_PlayVoice("D0104002_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I've still got things to do, so go\nhome first.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay, I will. See you later.");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0104002_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah.");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(4, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SC000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(... Ah, crap.\nI forgot some things.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(It can't be helped, I have to go\nback...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SC212_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(That reminds me,\n｛Hariya＊＊｝ said he still\nhas things to do...\nI wonder what it is.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, he's here.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("EV_04_08", #1, 0, 60);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_04_002_D03", 127, 40);
    Voice_PlayVoice("D0104002_D00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "......\nShould I start all over again...?");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Start over?\nIs he holding a music sheet?)");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0104002_D00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... This is wrong...");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0104002_D00900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Hmmm～......\nIt's just not coming to me...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He looks like he's really focusing.\nIt'd be bad to disturb him, so I'll\njust go home.)");
    Still_StillFace(0, 6, 2);
    Still_Approach(4, 97, 0, 0, 1, 1);
    Voice_PlayVoice("D0104002_D01000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "C, G...");
    Still_ApproachEnd();
    Still_StillFace(0, 7, 1);
    Voice_PlayVoice("D0104002_D01100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Do your best,\n｛Hariya＊＊｝.)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Still_Event("");
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    Parameter_AddCh1Param(4, 61, 6);
    Parameter_AddCh1Param(4, 60, 3);
    Parameter_AddCh1Param(4, 62, #5);
    }
