section "d01_m5_002"{
    Character_BlinkStart(5, 1, (#1), 1);
    Character_BlinkStart(5, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC311_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's raining...\nDid I bring a spare umbrella...?)");
    Voice_PlayVoice("", 5, "");
    Message_Who(5);
    Message_MsgDisp("？？？", "｛主人公｝.");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(5, "M5_01F", 0);
    Music_PlayBGM(0, "MN_C_05_002_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Chris＊＊｝.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(5, 3, (#1), 1);
    Voice_PlayVoice("D0105002_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Hello. What are you doing?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hello. I'm studying.\nWhat about you,\n｛Chris＊＊｝?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0105002_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I came here to return a book, but I\nfeel like I should make use of this\ntime.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Why?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(5, 3, (#1), 1);
    Voice_PlayVoice("D0105002_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Being alone with you is nothing but\nbeneficial.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha.\nThen maybe I should make the most of\nthis time, too.");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(5, 2, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0105002_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Hm? To do what?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I just can't understand this part...");
    Voice_PlayVoice("D0105002_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Haha. So are you asking me?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0105002_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nIt's a completely different kind of\n\"benefit\".");
    Message_Who(0);
    Message_MsgDisp("主人公", "Don't say that.\nLet's study together.");
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0105002_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nHow can I refuse when you ask me\nwith such cute eyes?\nI'll go look for a textbook then～.");
    Character_Chara_GS2(5, "NON");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Voice_PlayVoice("D0105002_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Here it is. Alright...");
    SoundEffect_PlayStream(2, "SEQ_SE_EV_005");
    Still_Event("EV_05_09", #1, 0, 60);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0105002_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Hmm...\nI thought that you used the other\nformula...");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yeah...");
    Still_Approach(5, 128, 0, 0, 1, 1);
    Voice_PlayVoice("D0105002_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Huh? ...\nIs it this formula then...?");
    Still_ApproachEnd();
    Still_Approach(5, 128, 0, 0, 1, 5);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝...");
    Still_ApproachEnd();
    Voice_PlayVoice("D0105002_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Crap～.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...");
    Background_Bg_GS2("BG_SC311_CO_0", #1, #1, 0);
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 1);
    Character_BlinkStart(5, 3, (#1), 1);
    Character_Chara_GS2(5, "M5_01F", 0);
    Still_Event("");
    Voice_PlayVoice("D0105002_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "The statistics show that my head\ndoesn't work on rainy days.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(5, 3, (#1), 1);
    Voice_PlayVoice("D0105002_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "So I will go home now.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ehh! But we just started studying...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0105002_E01300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "The rain is unbearable.\nIt can't be helped that it's like\nthis.");
    Voice_PlayVoice("D0105002_E01400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Don't they say that great kings also\nrest on rainy days?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Haha, yeah.\nSo should we go home, then?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(5, 3, (#1), 1);
    Voice_PlayVoice("D0105002_E01500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah.\nLet's share an umbrella▼");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    Parameter_AddCh1Param(5, 61, 6);
    Parameter_AddCh1Param(5, 60, 3);
    Parameter_AddCh1Param(5, 62, #5);
    }
