section "d01_m6_001"{
    Character_BlinkStart(6, 1, (#1), 1);
    Character_BlinkStart(6, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    SoundEffect_PlayStream(2, "SS_T_00_079_S00");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh, ｛Amachi＊＊｝?");
    Character_Chara_GS2(6, "M6_01F", 0);
    Music_PlayBGM(0, "MN_C_06_001_D00", 127, 40);
    Voice_PlayVoice("", 6, "D0106001_F00000");
    Message_Who(6);
    Message_MsgDisp("Amachi", "｛主人公｝.\nThat smells good.\nWere you practicing cooking?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah. We made cupcakes.");
    Voice_PlayVoice("D0106001_F00100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Nice.\nI only have an eye out for sweet\nthings.\nI want to eat them.");
    Voice_PlayVoice("D0106001_W00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Ah, Amachi-kun.\nIf it's fine with you, please take\none.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0106001_F00300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Is it okay? Thank you very much.");
    Voice_PlayVoice("D0106001_W00400", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student B", "If it's fine with you, please also\neat one of mine!");
    Voice_PlayVoice("D0106001_W00500", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student C", "Mine too!");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(6, 3, (#1), 1);
    Voice_PlayVoice("D0106001_F00600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I'm glad that I have so many!\nI will enjoy them all! ...\nNow then, excuse me.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(6, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(No matter how much he likes sweet\nfood, can he even finish them all by\nhimself?)");
    Message_CloseMsg();
    SoundEffect_StopStream(2, 40);
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_SC302_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? My pencil case isn't here...\nWhere did I leave it?");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_SC220_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm, where is it...");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SC212_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0106001_F00700", #1, "");
    Message_Who(6);
    Message_MsgDisp("？？？", "Hmm～, lacking. 27 points.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? That voice just now...");
    Voice_PlayVoice("D0106001_F00800", #1, "");
    Message_Who(6);
    Message_MsgDisp("？？？", "Wah, too sweet! 14 points.");
    Voice_PlayVoice("D0106001_F00900", #1, "");
    Message_Who(6);
    Message_MsgDisp("？？？", "Hmm...\nIt's not bad, but it's not good\neither.\n59 points.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(It sounds like\n｛Amachi＊＊｝, but his tone\nis a little different...?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I'm curious...\nMaybe I should take a peek?)");
    Still_Event("EV_06_07", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_06_003_D00", 127, 40);
    Voice_PlayVoice("D0106001_F01000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Now then, the one that is covered in\nchocolate...");
    Still_StillFace(0, 5, 1);
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("D0106001_F01100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Wah, so bitter! What is this?\n3 points.");
    Still_Approach(6, 156, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ehhh!?\nThat's ｛Amachi＊＊｝, right?\nR-Really...?)");
    Still_ApproachEnd();
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Background_Bg_GS2("BG_SC360_?_0", 1, #1, 0);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 4);
    Character_BlinkStart(6, 3, (#1), 1);
    Character_Chara_GS2(6, "M6_01F", 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0106001_F01200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Hmph. Is this all of them?\nEveryone is so bad at cooking.");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(6, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0106001_F01300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Ah, whatever.\nWell thanks to them, I saved on\nlunch money.\nThanks for the food, seniors.");
    SoundEffect_PlayStream(2, "SS_T_00_223_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah!?)");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(6, 0, (#1), 1);
    Voice_PlayVoice("D0106001_F01400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Wah!! S...Senpai!?");
    Message_Who(0);
    Message_MsgDisp("主人公", "S-Sorry!\nI had no intention of watching\nyou...!");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(6, 2, (#1), 1);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("D0106001_F01500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Meaning... you saw.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uh...");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("D0106001_F01600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "...... Ah! This place!");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(6, 3, (#1), 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "W-What!?");
    Character_Chara_GS2(6, "NON");
    Voice_PlayVoice("D0106001_F01700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Bye bye! Senpai, please clean up～!");
    Music_StopBGM(0, 40);
    SoundEffect_PlayStream(2, "SS_T_00_004_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "W-Wait, ｛Amachi＊＊｝!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(... He left.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Anyway, was that really\n｛Amachi＊＊｝?\nWhat a shock...)");
    Message_CloseMsg();
    SoundEffect_StopStream(2, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(6, 86, 1);
    Parameter_AddCh1Param(6, 61, 6);
    Parameter_AddCh1Param(6, 60, 3);
    Parameter_AddCh1Param(6, 62, #5);
    }
