section "d01_m9_002"{
    Character_BlinkStart(9, 1, (#1), 1);
    Character_BlinkStart(9, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_TR000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's a little late.\nI should catch a bus home...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_EX160_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(*Phew*, I'm a little tired from all\nthe walking today...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, an elder is standing on the\nbus.\nWhat should I do...)");
    Message_MsgSel("I have to give up my seat.", "I'm tired today, so...");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, if it's alright with you,\nplease take this seat.");
        Voice_PlayVoice("D0109002_W00000", #1, "");
        Message_Who(0);
        Message_MsgDisp("Passenger", "Oh, thank you for being so kind.\nBut I'm getting off soon, so it's\nalright.");
        Message_Who(0);
        Message_MsgDisp("主人公", "No, I'm also getting off soon, so\nplease take the seat.");
        Voice_PlayVoice("D0109002_W00100", #1, "");
        Message_Who(0);
        Message_MsgDisp("Passenger", "Dear, oh dear, but...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Please don't say such a thing.");
        Voice_PlayVoice("D0109002_W00200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Passenger", "My goodness, what should I--");
        Voice_PlayVoice("D0109002_I00300", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "This girl is just plain stubborn, so\nbefore she gets mad at you, you\nshould just take the seat.");
        Voice_PlayVoice("D0109002_W00400", #1, "");
        Message_Who(0);
        Message_MsgDisp("Passenger", "Eh? Ah, okay, I won't refuse then.");
        Message_Who(0);
        Message_MsgDisp("主人公", "??? ... Ah!!");
        Character_Chara_GS2(9, "M9_01F", 0);
        Music_PlayBGM(0, "MN_C_09_000_D00", 127, 40);
        Voice_PlayVoice("D0109002_I00500", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "Hey, so you do have some good\ntraits.");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's common sense to give your seat\nto your elders.\nAnd what do you mean by \"just plain\nstubborn\"?");
        Character_BlinkStart(9, 3, (#1), 1);
        Voice_PlayVoice("D0109002_I00600", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "I mean you're an impossibly stubborn\nperson.\nAnyway, what's with your outfit?\nAre you coming home from a date?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Leave me alone. And what about you?\nIt's a day off yet you're wearing\nyour school uniform.");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("D0109002_I00700", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "I like school uniforms.\nSo leave me alone.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Right, are you a student from\nHabataki Academy?\nI guess it can't be helped that you\nwant to show off.");
        Character_BlinkStart(9, 2, (#1), 1);
        Voice_PlayVoice("D0109002_I00800", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "What spiteful words...\nMaybe you should try to speak in a\nmore gentle way?");
        Message_Who(0);
        Message_MsgDisp("主人公", "If you don't like it, then don't\ntalk to me!");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 5);
        Character_BlinkStart(9, 3, (#1), 1);
        Voice_PlayVoice("D0109002_I00900", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "Ah, fine. That's what I'll do!");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Voice_PlayVoice("D0109002_I01000", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "I'm just talking to myself here...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...?)");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 2);
        Character_BlinkStart(9, 2, (#1), 1);
        Voice_PlayVoice("D0109002_I01100", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "I had business to attend to at\nschool.\nIt's not like I wanted to walk\naround showing off my uniform.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Is that so...\nPerhaps I went too far?)");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(9, 3, (#1), 1);
        Voice_PlayVoice("D0109002_I01200", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "And... sorry.\nFor unnecessarily meddling in your\nbusiness....\nThis is also just me talking to\nmyself.");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's fine...\nAh, this is me talking to myself!");
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("D0109002_I01300", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "Haha...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hahaha.");
        Voice_PlayVoice("D0109002_I01400", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "Um...\nIf you're not angry anymore, would\nyou tell me your--");
        Voice_PlayVoice("D0109002_W01500", #1, "");
        Message_Who(0);
        Message_MsgDisp("Driver", "3rd Block of Hanegasaki, the 3rd\nBlock.\nAlighters, please remember to take\nall of your belongings with you.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(9, 0, (#1), 1);
        Character_ChFace(0, 3, 5);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, my stop!\nEh, I'm getting off here, so...");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("D0109002_I01600", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "Ah. Ahh... Is that so. Later.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, later...");
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(9, "NON");
        SoundEffect_PlayStream(2, "SS_T_00_026_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "(That was surprising...\nBumping into him again really is the\nkind of thing you see in a drama.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(If I meet him again, I'll make sure\nto apologize to him.\nBut as if I would meet him, again.)");
        System_GlobalWork(20, 0, 1);
        Parameter_AddCh1Param(9, 86, 1);
        break ;
        case 1:
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Voice_PlayVoice("D0109002_W01700", #1, "");
        Message_Who(0);
        Message_MsgDisp("Driver", "3rd Block of Hanegasaki, the 3rd\nBlock.\nAlighters, please don't leave\nanything behind.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, I'm getting off!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        SoundEffect_PlayStream(2, "SS_T_00_026_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Huh?)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(The person we just passed looked\nlike that guy from Habataki\nAcademy...\nNo, it can't be.)");
        break ;
        }
    Message_CloseMsg();
    SoundEffect_StopStream(2, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
