section "d01_mb_009"{
    Background_Bg_GS2("BG_EX200_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("NS_F1_922_00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Woman A", "What do you mean by \"break up\"?");
    Voice_PlayVoice("NS_F2_921_00300", #1, "");
    Message_Who(0);
    Message_MsgDisp("Woman B", "You're being really annoying!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(!?)");
    Voice_PlayVoice("NS_92_000_14000", #1, "");
    Message_Who(26);
    Message_MsgDisp("？？？", "Sorry.\nNo matter what you say to me, all I\ncan do is apologize.");
    Character_ChFace(0, 0, 9);
    Character_Chara_GS2(26, "MB_02F", 0);
    Music_PlayBGM(0, "MN_C_92_001_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Tarou-kun...)");
    Voice_PlayVoice("NS_F1_922_00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Woman A", "Then why don't you kneel down and\napologize?\nLike a frog!");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(26, 3, (#1));
    Voice_PlayVoice("NS_92_000_14100", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Alright, I will, if it will make you\nfeel a little better--");
    Message_Who(0);
    Message_MsgDisp("主人公", "W-Wait a moment!");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(26, 1, (#1));
    Character_BlinkStart(26, 0, (#1));
    Voice_PlayVoice("NS_92_000_14200", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "!! It's fine, it's my problem.\nI'm sorry that we're causing a fuss.");
    Voice_PlayVoice("NS_F1_922_00300", #1, "");
    Message_Who(0);
    Message_MsgDisp("Woman A", "Hey, don't interfere!");
    Voice_PlayVoice("NS_F2_921_00400", #1, "");
    Message_Who(0);
    Message_MsgDisp("Woman B", "And who are you? His junior, was it?\nHe was playing you, wasn't he?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I--");
    Character_ChFace(0, 0, 6);
    Character_BlinkStart(26, 2, (#1));
    Voice_PlayVoice("NS_92_000_14300", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "... This person is important to me.\nThat's why I can't see either of you\nanymore.");
    Voice_PlayVoice("NS_F1_922_00400", #1, "");
    Message_Who(0);
    Message_MsgDisp("Woman A", "Huh? This average waitress?");
    Voice_PlayVoice("NS_F2_921_00500", #1, "");
    Message_Who(0);
    Message_MsgDisp("Woman B", "Isn't she a high school student?\nShouldn't you go home and study?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm sorry but, umm...");
    Voice_PlayVoice("NS_92_000_14400", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Come here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_Chara_GS2(26, "NON");
    Still_Event("EV_92_05", #1, 0, 60);
    Voice_PlayVoice("NS_92_000_14500", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Sorry... But I'm fine with her.\nIf she is with me...\nthen that's all I need.");
    Still_Approach(26, 302, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Tarou-kun...)");
    Still_ApproachEnd();
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Character_Chara_GS2(26, "MB_02F", 0);
    Music_StopBGM(0, 40);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(26, 2, (#1));
    Screen_WipeIn(2);
    Voice_PlayVoice("NS_92_000_14600", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "...\nThe manager yelled at you quite a\nbit, didn't they?");
    Message_Who(0);
    Message_MsgDisp("主人公", "It can't be helped if I'm going to\ndo such a thing at the store.");
    Character_ChFace(0, 0, 6);
    Character_BlinkStart(26, 2, (#1));
    Voice_PlayVoice("NS_92_000_14700", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "It just ended up that way.\nIt couldn't be helped.\nI've decided to be honest.");
    Message_Who(0);
    Message_MsgDisp("主人公", "How suprising...\nfor you to say that.");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(26, 0, (#1));
    Voice_PlayVoice("NS_92_000_14800", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Yeah.\nIt seems like I am not as skilled as\nI thought I was.\nThat's why my timing is bad.");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Character_ChFace(0, 4, 1);
    Character_ChFace(0, 0, 6);
    Voice_PlayVoice("NS_92_000_14900", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "I want you to go on a date with me.\nA real one.... Is that okay?");
    Message_MsgSel("Yeah, it's okay.", "It's impossible...");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "... Okay. So the Forest Park?");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(26, 2, (#1));
        Voice_PlayVoice("NS_92_000_15000", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "How unforgiving. But...\nyou're right.\nIt seems like I can patch things up.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay.\nAs expected, you like sexy clothing?");
        Character_ChFace(0, 0, 6);
        Character_BlinkStart(26, 0, (#1));
        Voice_PlayVoice("NS_92_000_15100", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "You're teasing me.\nYou can wear anything.\nI'll learn to like it.... Goodnight.");
        Character_Chara_GS2(26, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I teased him a little.\nBut Tarou-kun is actually a shy\nperson...\nIt seems like things will go well!)");
        System_GlobalWork(19, 0, 15);
        Date_SetNextSandayDateEvent(26);
        break ;
        case 1:
        Message_Who(0);
        Message_MsgDisp("主人公", "I don't think that way.\nIt's impossible...");
        Character_ChFace(0, 0, 0);
        Character_BlinkStart(26, 3, (#1));
        Voice_PlayVoice("NS_92_000_15200", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Really... You're right.\nYou did the right thing.\nI have no honor at all.");
        Character_BlinkStart(26, 1, (#1));
        Character_BlinkStart(26, 0, (#1));
        Voice_PlayVoice("NS_92_000_15300", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I must apologize to the people that\nI've hurt rather than think of\nmyself.\nI will be alone tomorrow.");
        Message_Who(0);
        Message_MsgDisp("主人公", "If it's you, Tarou-kun, you'll\nsurely be okay.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("NS_92_000_15400", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Thank you...\nIf I meet you again, I will try once\nmore.\nWhen such a time comes, please don't\nbe too hard on me.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay.");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("NS_92_000_15500", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Goodbye...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Tarou-kun, do your best.)");
        System_GlobalWork(19, 0, 30);
        break ;
        }
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
