section "d01_m5_001"{
    Character_BlinkStart(5, 1, (#1), 1);
    Character_BlinkStart(5, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SCA50_?_0", 1, #1, 0);
    SoundEffect_PlayStream(2, "SS_T_00_124_S00");
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(... Huh?\nThe Art Club is very noisy.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, it's ｛Chris＊＊｝.\nIt looks like the people have\ncrowded around one spot...)");
    SoundEffect_StopStream(2, 80);
    Voice_PlayVoice("D0105001_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I can't today.");
    Voice_PlayVoice("D0105001_W00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Male Student", "What～, you're bad at keeping people\ncompany.\nRight?");
    Voice_PlayVoice("D0105001_W00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student", "That's right! It's not like Chris～.");
    Voice_PlayVoice("D0105001_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It can't be helped.\nI am not in the mood to hang out\ntoday, as I've discovered a new form\nof art.");
    Voice_PlayVoice("D0105001_W00400", #1, "");
    Message_Who(0);
    Message_MsgDisp("Male Student", "Pfft.\nThen hang out with us next time!");
    Voice_PlayVoice("D0105001_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Okay. Invite me again sometime.");
    SoundEffect_PlayStream(2, "SS_DSE_069_000");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝.");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(5, "M5_01F", 0);
    Music_PlayBGM(0, "MN_C_05_002_D00", 127, 40);
    Voice_PlayVoice("", 5, "D0105001_E00600");
    Message_Who(5);
    Message_MsgDisp("Chris", "｛主人公｝. Hello.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hello.\nYou're quite popular,\n｛Chris＊＊｝.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(5, 3, (#1), 1);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("D0105001_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I'm actually quite reluctant to turn\ndown an invitation from a girl,\nthough.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0105001_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It can't be helped.\nI'm madly in love with this one▼");
    Message_Who(0);
    Message_MsgDisp("主人公", "This one?");
    Character_Chara_GS2(5, "NON");
    Still_Event("EV_05_08", #1, 0, 60);
    Still_Approach(5, 127, 0, 0, 1, 1);
    Voice_PlayVoice("D0105001_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah, this India-ink painting.\nIt's been done really well.");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...\nIt looks simple, yet it looks\ndifficult.");
    Voice_PlayVoice("D0105001_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah.\nThe way they use the brush is\ndifferent to water-coloring, so I\njust can't get it right.");
    Voice_PlayVoice("D0105001_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I must get the right materials for\nthis...");
    Background_Bg_GS2("BG_SCA50_?_0", 1, #1, 0);
    Character_Chara_GS2(5, "M5_01F", 0);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("主人公", "You're amazing,\n｛Chris＊＊｝.\nYou tackle a variety of things.\nI should learn from you.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0105001_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "The current me wants to do\neverything that I want to do.");
    Message_Who(0);
    Message_MsgDisp("主人公", "\"The current me\"...?");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(5, 2, (#1), 1);
    Voice_PlayVoice("D0105001_E01300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nYeah, because there is no time like\nthe present.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Chris＊＊｝...)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Environment_StopME(1, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    Parameter_AddCh1Param(5, 61, 6);
    Parameter_AddCh1Param(5, 60, 3);
    Parameter_AddCh1Param(5, 62, #5);
    }
