section "d01_m7_002"{
    Character_BlinkStart(7, 1, (#1), 1);
    Character_BlinkStart(7, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0 = 0;
    Background_Bg_GS2("BG_SC331_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Tidying up after experiments is\ntroublesome...\nEh, the prep racks are... here.)");
    SoundEffect_PlayStream(2, "SS_T_00_165_M00");
    Voice_PlayVoice("D0107002_G00000", 7, "");
    Message_Who(7);
    Message_MsgDisp("？？？", "Huh? ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes? ... Wah!!");
    SoundEffect_PlayStream(2, "SE_GLASS");
    Message_Who(0);
    Message_MsgDisp("主人公", "*Phew*... Safe!\nThat was dangerous...");
    if (Parameter_GetPl1Param(312) != 7){
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(7, 2, (#1), 1);
        Character_Chara_GS2(7, "M7_01F", 0);
        Music_PlayBGM(0, "MN_C_07_003_D00", 127, 40);
        Voice_PlayVoice("D0107002_G00100", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I appreciate your hard work....\nAre you alright?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, yes. Somehow, I'm safe.");
        Character_BlinkStart(7, 0, (#1), 1);
        Voice_PlayVoice("D0107002_G00200", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "That surprised me.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(You don't really appear that way,\nthough...)");
        Voice_PlayVoice("D0107002_G00300", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "I was boiling water for coffee.\nHave some, too.");
        var0 = 1;
        }
    else {
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 5);
        Character_Chara_GS2(7, "M7_01F", 0);
        Music_PlayBGM(0, "MN_C_07_003_D00", 127, 40);
        Voice_PlayVoice("D0107002_G00400", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "You don't have to be so frightened.\nI won't help you today.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh? ...... Ah!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Right, a similar kind of thing has\nhappened before...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, umm...\nI didn't mean it that way...");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("D0107002_G00500", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Eh?");
        Character_ChFace(0, 0, 0);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0107002_G00600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Ah... I see. Yeah, I understand...");
        Character_ChFace(0, 2, 3);
        Voice_PlayVoice("D0107002_G00700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Right!");
        var0 = 5;
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(7, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    SoundEffect_StopStream(2, 40);
    Still_Event("EV_07_07", #1, 0, 60);
    Screen_WipeIn(2);
    Still_Approach(7, 186, 0, 0, 1, var0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Do you always drink coffee like\nthis, ｛Wakaouji＊＊｝?");
    Still_ApproachEnd();
    Voice_PlayVoice("D0107002_G00800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I do.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, is it more yummy or something?\nMaking it this way...?");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0107002_G00900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I wonder...\nThat shouldn't be the case.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Then...");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0107002_G01000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Every time I drank coffee like this,\nI always thought to bring my\ncoffeemaker from home, but...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0107002_G01100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "In other words, when I woke up the\nnext morning, I would completely\nforget.\nSo I gave up on the idea.");
    Message_Who(0);
    Message_MsgDisp("主人公", "So you gave up.");
    Voice_PlayVoice("D0107002_G01200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Yeah.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Haha.\nThat sounds like\n｛Wakaouji＊＊｝.)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Still_Event("");
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 86, 1);
    Parameter_AddCh1Param(7, 61, 6);
    Parameter_AddCh1Param(7, 60, 3);
    }
