section "d01_m2_000"{
    Character_BlinkStart(2, 1, (#1), 1);
    Character_BlinkStart(2, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC410_SP_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's about time I head back to the\nclassroom...)");
    Voice_PlayVoice("D0102000_H00000", #1, "");
    Message_Who(2);
    Message_MsgDisp("？？？", "You really saved me.\nThanks, Katsumi.");
    Voice_PlayVoice("D0102000_B00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("？？？", "...\nDon't get people involved in your\nmess.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? That voice just now...\n｛Shiba＊＊｝?)");
    Voice_PlayVoice("D0102000_H00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("？？？", "\"Mess\"?\nYou don't respect people, at all.\nHow cold of you.");
    Voice_PlayVoice("D0102000_B00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("？？？", "Isn't this your job?");
    Voice_PlayVoice("D0102000_H00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("？？？", "Come on, don't say that.\nYou should be cursing your luck\ninstead of me, Katsumi.");
    Voice_PlayVoice("D0102000_B00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("？？？", "Don't call me \"Katsumi\".");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝!\n｛Masaki＊＊｝!");
    Character_ChFace(0, 2, 2);
    Character_Chara_GS2(2, "M2_01F", 0);
    Character_ChFace(1, 3, 4);
    Character_Chara_GS2(8, "M8_01F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_02_000_D00", 127, 40);
    Voice_PlayVoice("", 2, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... ｛主人公｝.");
    Voice_PlayVoice("D0102000_H00700", 8, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Oh. ｛主人公｝.");
    Character_Chara_GS2(8, "NON");
    Character_Chara_GS2(2, "NON");
    Still_Event("EV_02_05", #1, 0, 60);
    Message_Who(0);
    Message_MsgDisp("主人公", "Should I also help you out,\n｛Shiba＊＊｝?");
    Still_StillFace(1, 6, 1);
    Voice_PlayVoice("D0102000_H00800", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "How nice of you.\nSo different to a certain Mr.\nUnwilling.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0102000_B00900", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Shut up.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0102000_B01000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... It's fine, I'll do it.");
    Still_StillFace(1, 6, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Really? Is it really okay?");
    Still_StillFace(0, 0, 1);
    Still_Approach(2, 34, 0, 0, 1, 1);
    Voice_PlayVoice("D0102000_B01100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nThere's no way you'd be able to\ncarry this kind of weight.");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0102000_B01200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Lunch break is about to end, you\nshould go back to the classroom.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, okay...");
    Still_StillFace(1, 6, 2);
    Voice_PlayVoice("D0102000_H01300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Why can you only say things in a\ncold way...");
    Still_StillFace(1, 6, 0);
    Still_Approach(2, 34, 0, 0, 1, 5);
    Voice_PlayVoice("", 8, "D0102000_H01400");
    Message_Who(8);
    Message_MsgDisp("Masaki", "｛主人公｝.\nThis guy's just embarrassed, so\ndon't worry about it.");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0102000_B01500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "......... Shut up. Go away already.");
    Voice_PlayVoice("D0102000_H01600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Okay, okay...\nKatsumi-kun is so impatient.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0102000_B01700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Don't call me \"Katsumi-kun\".");
    Voice_PlayVoice("D0102000_H01800", 8, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Okay, okay.\nSee you later,\n｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, okay!");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0102000_B01900", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...... Later.");
    Background_Bg_GS2("BG_SC410_SP_0", #1, #1, 0);
    Music_StopBGM(0, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Shiba＊＊｝ is a little\ndifferent when he's with\n｛Masaki＊＊｝.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(A fresh kind of feeling.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 86, 1);
    Parameter_AddCh1Param(2, 86, 1);
    Parameter_AddCh1Param(2, 61, 6);
    Parameter_AddCh1Param(2, 60, 3);
    Parameter_AddCh1Param(2, 62, #5);
    }
