section "d01_g4_001"{
    Character_BlinkStart(13, 1, (#1), 1);
    Character_BlinkStart(13, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC212_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(I arrived a little early today...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_SC303_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(No one is here yet...)");
    SoundEffect_PlayStream(2, "SS_DSE_069_000");
    System_Wait(80);
    Voice_PlayVoice("", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "｛主人公｝.");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(13, "G4_01F", 0);
    Music_PlayBGM(0, "MN_C_13_000_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Mizushima＊＊｝.\nGood morning.");
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("D0113001_M00000", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Good morning. Ah...\nlook, the cuff of your sleeves are\nbreaking.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, you're right!\nWah～ When did this happen...");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0113001_M00100", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Give me your hand.\nI'll fix it for you.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(13, "NON");
    Still_Event("EV_13_01", #1, 0, 10);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0113001_M00200", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "This part damages easily.\nI'll fix it so it's stronger, okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay, thank you....\nSo you're also good at sewing,\n｛Mizushima＊＊｝.");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0113001_M00300", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Haha, maybe...");
    Message_Who(0);
    Message_MsgDisp("主人公", "You're really feminine.\nIt's amazing...");
    Still_StillFace(0, 6, 3);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0113001_M00400", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "... You think so?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, I think so.");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0113001_M00500", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "But isn't it a little irritating?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is it? I don't think so, though.");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0113001_M00600", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Ah, thank you....\nDid you know that my parents are\nreally old-fashioned?\nThey are strict people.");
    Still_StillFace(0, 6, 3);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0113001_M00700", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Since I was a child, they would\nalways say \"girls don't do these\nkinds of things\" and such.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Really? That sounds tough.");
    Voice_PlayVoice("D0113001_M00800", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "That's why...\nI aspire to be a free person.\nSomeone who can do the things that I\ncould never do.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so...");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0113001_M00900", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "But when those people look at me, I\nget annoyed, and I get irritated...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I wonder if ｛Mizushima＊＊｝\nhas someone she likes...)");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 3);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0113001_M01000", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "... Alright. It's done!");
    Background_Bg_GS2("BG_SC303_CO_0", #1, #1, 0);
    Character_Chara_GS2(13, "G4_01F", 0);
    Character_ChFace(0, 0, 10);
    Message_Who(0);
    Message_MsgDisp("主人公", "Thank you.");
    Character_BlinkStart(13, 3, (#1), 1);
    Voice_PlayVoice("D0113001_M01100", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Haha. You're welcome.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(13, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Mizushima＊＊｝ looks like\nshe's troubled...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(13, 86, 1);
    Parameter_AddCh1Param(13, 60, 5);
    }
