section "d01_m4_001"{
    Character_BlinkStart(4, 1, (#1), 1);
    Character_BlinkStart(4, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC100_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's nice to come by here\noccasionally after school, but I\nshould go home now.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_WF200_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh... Over there is...)");
    Still_Event("EV_04_07", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_04_002_D00", 127, 40);
    Still_Approach(4, 96, 0, 0, 1, 1);
    Voice_PlayVoice("D0104001_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah...... Alright.");
    Still_ApproachEnd();
    Background_Bg_GS2("BG_WF200_?_1", 1, #1, 0);
    Character_ChFace(0, 0, 11);
    Character_Chara_GS2(4, "M4_01F", 0);
    Still_Event("");
    Voice_PlayVoice("D0104001_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... You...");
    Character_ChFace(0, 0, 9);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("D0104001_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Did you see?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yeah...\nSorry, perhaps I shouldn't have.");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("D0104001_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... It's no worry.\nI don't mind if it's you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "That's good. What were you doing?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0104001_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Imatrain.");
    Message_Who(0);
    Message_MsgDisp("主人公", "\"Imatrain\"?");
    Voice_PlayVoice("D0104001_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Image training.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0104001_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nTo prepare myself for the tens of\nthousands of people in the audience!");
    Character_BlinkStart(4, 3, (#1), 1);
    Voice_PlayVoice("D0104001_D00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "The live starts with my shout and\nends with our wild enthusiasm...");
    Character_BlinkStart(4, 0, (#1), 1);
    Voice_PlayVoice("D0104001_D00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nThat's the image that I imagined in\nmy head.\nThen by doing so--");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0104001_D00900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nThen by doing so, I can be even\nbetter for the real thing.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0104001_D01000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Or so it should be.\nIt doesn't seem like such an easy\nthing to do though, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝...");
    Character_BlinkStart(4, 3, (#1), 1);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("D0104001_D01100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "But I...");
    Voice_PlayVoice("D0104001_D01200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I can't just easily throw away my\ndream of wanting as many people as\npossible to listen to the songs I\nmake.");
    Character_ChFace(0, 0, 6);
    Character_BlinkStart(4, 0, (#1), 1);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("D0104001_D01300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "That's why I do this...\nIt's fine if I do it a little, so I\nhave no choice but to do it.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0104001_D01400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Anyway, what am I talking about?\nSorry, I just started rambling on.");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, it's fine.\nI was only going back home.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0104001_D01500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Really....\nSo would you like to listen?");
    Message_Who(0);
    Message_MsgDisp("主人公", "To what?");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("D0104001_D01600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "A song.\nI feel like singing something.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sure!");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0104001_D01700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Alright! This part is the stage....");
    Character_BlinkStart(4, 3, (#1), 1);
    Voice_PlayVoice("D0104001_D01800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "So please listen to this...\n\"only You\".");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    Parameter_AddCh1Param(4, 61, 6);
    Parameter_AddCh1Param(4, 60, 3);
    Parameter_AddCh1Param(4, 62, #5);
    }
