section "d01_m7_001"{
    Character_BlinkStart(7, 1, (#1), 1);
    Character_BlinkStart(7, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SCA30_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    SoundEffect_PlayStream(2, "SS_T_00_002_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Wah, I'm late! The club, the club!)");
    Voice_PlayVoice("D0107001_W00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Male Club Member", "It's impossible, even if you say\nthings in such detail!\nAnd not at this height!");
    Voice_PlayVoice("D0107001_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("？？？", "Is that so...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Wakaouji＊＊｝.");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(7, "M7_08F", 0);
    Music_PlayBGM(0, "MN_C_07_003_D00", 127, 40);
    Voice_PlayVoice("", 7, "D0107001_G00200");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝.\nHey, you're late.\nI came 15 minutes ago.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I apologize.\nAnyway, what is happening?");
    Character_ChFace(0, 2, 4);
    Voice_PlayVoice("D0107001_G00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Ah, this. Is it okay?");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(7, 3, (#1), 1);
    Voice_PlayVoice("D0107001_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It is 3cm off the starting position,\nthe angle of entry is 2 degrees.\nThe jump--");
    Voice_PlayVoice("D0107001_W00500", #1, "");
    Message_Who(0);
    Message_MsgDisp("Male Club Member", "I said it's impossible!\nIf you're so sure, then you should\ntry doing it, Waka-chan.");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(7, 0, (#1), 1);
    Voice_PlayVoice("D0107001_G00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I see. That is right.");
    Voice_PlayVoice("D0107001_W00700", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Member", "Waka-sama, you shouldn't do it!\nIt's dangerous!");
    Message_Who(0);
    Message_MsgDisp("主人公", "You shouldn't overdo it,\n｛Wakaouji＊＊｝.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(7, 2, (#1), 1);
    Voice_PlayVoice("D0107001_G00800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Impossible, you say...?");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(7, 3, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0107001_G00900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Now then, I will show you proof.");
    Environment_StopME(1, 40);
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(7, "NON");
    Voice_PlayVoice("D0107001_G01000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Torsion moment will work with this\nvector.\nThe balance of inertia, gravity, and\nresistance...\nI can do this!");
    SoundEffect_PlayStream(2, "SS_DSE_060_000");
    Voice_PlayVoice("D0107001_G01100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Ha!!");
    SoundEffect_PlayStream(2, "SS_T_00_135_M00");
    Still_Event("EV_07_06", #1, 0, 60);
    Screen_WipeIn(2);
    Still_Approach(7, 185, 1, 0, 1, 1);
    SoundEffect_PlayStream(2, "EV_SE_GAYA_025");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    SoundEffect_PlaySE(866, 127);
    Background_Bg_GS2("BG_SCA30_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_07_003_D00", 127, 40);
    Voice_PlayVoice("D0107001_G01200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "So that's how it goes.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝!\nThat was amazing!!");
    Voice_PlayVoice("D0107001_G01300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Thank you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...\nWhy can't you stand up?");
    Voice_PlayVoice("D0107001_G01400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "My neck and back are cramped.\nPlease help me.");
    SoundEffect_PlayStream(2, "SE_NS_AL_910_003000");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah! ｛Wakaouji＊＊｝!");
    Message_CloseMsg();
    SoundEffect_StopStream(2, 40);
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 86, 1);
    Parameter_AddCh1Param(7, 61, 6);
    Parameter_AddCh1Param(7, 60, 3);
    }
