section "d01_ma_008"{
    SoundEffect_PlayStream(3, "SS_T_00_038_M00");
    Background_Bg_GS2("BG_EX190_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Komori-kun, let's go to school--");
    SoundEffect_PlayStream(3, "SEQ_SE_EV_144");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Character_Chara_GS2(25, "MA_01F", 0);
    Music_PlayBGM(0, "MN_C_91_000_D00", 127, 40);
    Message_Who(25);
    Message_MsgDisp("Komori", "......");
    Message_Who(0);
    Message_MsgDisp("主人公", "... You're Komori-kun, right?");
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("NS_91_000_07400", #1, "");
    Message_Who(25);
    Message_MsgDisp("Komori", "I feel the cool air, around my\nneck...");
    if (Parameter_GetPl1Param(20) >= 220){
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, you're kind of cute!");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("NS_91_000_07500", #1, "");
        Message_Who(25);
        Message_MsgDisp("Komori", "Cute, huh.... Let's go.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Maybe I should have said \"cool\"\ninstead...)");
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "Is it a little weird?");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("NS_91_000_07600", #1, "");
        Message_Who(25);
        Message_MsgDisp("Komori", "When I told my dad I was going to\nschool, he...\nHe said I had bad tastes...");
        Message_Who(0);
        Message_MsgDisp("主人公", "So you cut your hair! Let's go!");
        }
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 4, 0);
    Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Alright, so we're going in, okay?");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("NS_91_000_07700", #1, "");
    Message_Who(25);
    Message_MsgDisp("Komori", "A-As expected...");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's fine.\nIt's surely another present.");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(25, 3, (#1));
    Voice_PlayVoice("NS_91_000_07800", #1, "");
    Message_Who(25);
    Message_MsgDisp("Komori", "Y-Yeah.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    SoundEffect_PlayStream(3, "SS_DSE_040_000");
    Background_Bg_GS2("BG_SC302_?_0", #1, #1, 0);
    Screen_WipeIn(2);
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 4, 1);
    SoundEffect_PlayStream(1, "SE_NS_AL_910_009000", 127, 0);
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("NS_91_000_07900", #1, "");
    Message_Who(25);
    Message_MsgDisp("Komori", "Um... H-Hello.");
    Voice_PlayVoice("NS_AL_910_01000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Students", "Hahaha! You mean good morning!\nHello! How cute～!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(W-Well, it seems to be going well!)");
    System_GlobalWork(18, 0, 18);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
