section "d01_ma_010"{
    int var0 = 0;
    Background_Bg_GS2("BG_SC100_?_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Komori-kun finishes earlier than I\ndo today.\nIs he waiting...?)");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(25, "MA_01F", 0);
    Music_PlayBGM(0, "MN_C_91_000_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, Komori-kun!\nSorry, were you waiting!");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("NS_91_000_09100", #1, "");
    Message_Who(25);
    Message_MsgDisp("Komori", "I-It's no problem at all!\nI'm good at waiting.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, so should we go? Huh?");
    Voice_PlayVoice("NS_M1_911_00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Boy A", "Komori-senpai!\nAre you going home now?");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("NS_91_000_09200", #1, "");
    Message_Who(25);
    Message_MsgDisp("Komori", "Ah... Y-Yeah.\nBut calling me Senpai, is a\nlittle...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Komori-kun, are these your\nclassmates?");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("NS_91_000_09300", #1, "");
    Message_Who(25);
    Message_MsgDisp("Komori", "Yeah.");
    Voice_PlayVoice("NS_M2_911_00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Boy B", "Nice to meet you!\nWe're going to play basketball now.\nWhy not come along with us,\nKomori-san?");
    Voice_PlayVoice("NS_M1_911_00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Boy A", "Idiot, get a feel for the situation!\nHe's with his girlfriend!");
    if (Parameter_GetPl1Param(20) >= 260){
        Message_Who(0);
        Message_MsgDisp("主人公", "It's okay.\nI'm not his girlfriend or anything.");
        Character_ChFace(0, 0, 11);
        Character_ChFace(0, 4, 0);
        Character_BlinkStart(25, 2, (#1));
        Message_Who(25);
        Message_MsgDisp("Komori", ".........");
        Voice_PlayVoice("NS_M2_911_00100", #1, "");
        Message_Who(0);
        Message_MsgDisp("Boy B", "Let's go!\nWe don't have enough members.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Don't worry about me, I remembered\nthat I have some things to do.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(25, 3, (#1));
        Voice_PlayVoice("NS_91_000_09500", #1, "");
        Message_Who(25);
        Message_MsgDisp("Komori", "Sorry...\nI'm indecisive, so I don't know...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh? ... Ah!");
        Character_Chara_GS2(25, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(That's great...\nHe's a popular person now, so I have\nto support him.)");
        System_GlobalWork(18, 0, 20);
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "Komori-kun, what will you do?");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(25, 2, (#1));
        Voice_PlayVoice("NS_91_000_09600", #1, "");
        Message_Who(25);
        Message_MsgDisp("Komori", "Um, I...");
        Voice_PlayVoice("NS_M2_911_00100", #1, "");
        Message_Who(0);
        Message_MsgDisp("Boy B", "Let's go!\nWe don't have enough players.");
        Character_ChFace(0, 0, 11);
        Character_BlinkStart(25, 0, (#1));
        Voice_PlayVoice("NS_91_000_09700", #1, "");
        Message_Who(25);
        Message_MsgDisp("Komori", "But... Wah!");
        Character_Chara_GS2(25, "NON");
        Voice_PlayVoice("NS_M1_911_00200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Boy A", "Excuse us!\nWe'll be borrowing Komori-senpai!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He left. He's indecisive...)");
        System_GlobalWork(18, 0, 24);
        }
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
