section "d01_m5_004"{
    Character_BlinkStart(5, 1, (#1), 1);
    Character_BlinkStart(5, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_EX101_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's really late...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh, over there is...\n｛Chris＊＊｝?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝!");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Character_Chara_GS2(5, "M5_17F", 0);
    Music_PlayBGM(0, "MN_C_05_001_D01", 127, 40);
    Voice_PlayVoice("D0105004_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "... ｛Chris＊＊｝?");
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0105004_E00100", 5, "D0105004_E00101");
    Message_Who(5);
    Message_MsgDisp("Chris", "... ｛主人公｝.\nGood evening.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Good evening.");
    Voice_PlayVoice("D0105004_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "What are you doing here alone?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I've just come back from shopping.\nWhat about you,\n｛Chris＊＊｝?");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(5, "NON");
    Still_Event("EV_05_11", #1, 0, 60);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0105004_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Hm...\nI feel a little guilty because of\nsomething I did at work...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Did you get yelled at or something?");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0105004_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... The opposite.");
    Message_Who(0);
    Message_MsgDisp("主人公", "The opposite?");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0105004_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah...\nI said that getting yelled at was a\ngood way to learn, but my dad just\nlaughed.");
    Voice_PlayVoice("D0105004_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I had stuffed up a project due to\nextreme clumsiness.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0105004_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "The company employees had been\nworking really hard on it, too.");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0105004_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "And yet...\nTo see my dad laugh like that\nactually gets me down...");
    Still_Approach(5, 130, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so...");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 0);
    Still_StillFace(0, 7, 1);
    Voice_PlayVoice("D0105004_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", ".........");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Character_Chara_GS2(5, "M5_17F", 0);
    Background_Bg_GS2("BG_EX101_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0105004_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nSo I went out for a review meeting\nby myself, and that's when you came\nalong.");
    Character_BlinkStart(5, 3, (#1), 1);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("D0105004_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "A life isn't something that you\nshould throw away.\nThe gods are sometimes nice.");
    Message_Who(0);
    Message_MsgDisp("主人公", "...\nDid I interrupt your review meeting?");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(5, 3, (#1), 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0105004_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... No.\nI'm really glad that I was able to\ntalk.\nI feel better.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝...");
    Character_BlinkStart(5, 0, (#1), 1);
    Voice_PlayVoice("D0105004_E01300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I will talk to my dad when I get\nhome.\nThank you for supporting me.");
    Voice_PlayVoice("D0105004_E01400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I can't see you home, but will you\nbe alright?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, I will.\nDo your best, ｛Chris＊＊｝.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(5, 3, (#1), 1);
    Voice_PlayVoice("D0105004_E01500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Thank you. Goodbye.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(5, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Chris＊＊｝ looks like he\nhas many troubles...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    Parameter_AddCh1Param(5, 61, 6);
    Parameter_AddCh1Param(5, 60, 3);
    Parameter_AddCh1Param(5, 62, #5);
    }
