section "d01_m9_005"{
    Character_BlinkStart(9, 1, (#1), 1);
    Character_BlinkStart(9, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC101_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(I was chatting in the classroom,\nand now it's gotten late!)");
    Voice_PlayVoice("D0109005_W00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Hey look!\nIsn't that a student from Habataki\nAcademy?");
    Voice_PlayVoice("D0109005_W00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student B", "No way! He's so cool...\nAs expected of the guys from\nHabataki Academy.");
    Voice_PlayVoice("D0109005_W00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Hey, do you think he's waiting for\nsomeone?");
    Voice_PlayVoice("D0109005_W00300", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student B", "Yeah, he must be! I'm so jealous～!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Is that perhaps...\nAh, as I thought!)");
    Character_Chara_GS2(9, "M9_01F", 0);
    Music_PlayBGM(0, "MN_C_09_000_D00", 127, 40);
    Voice_PlayVoice("D0109005_I00400", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "Hey.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Akagi-kun. What's up?");
    Voice_PlayVoice("D0109005_I00500", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "I was here arranging a meeting for\nthe Student Council.\nThen something came to my mind.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that why you were waiting?\nHere...?");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(9, 3, (#1), 1);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("D0109005_I00600", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "Yeah.\nYou know you made me wait quite a\nwhile?\nBecause you wouldn't give me your\ncontact details.");
    Message_Who(0);
    Message_MsgDisp("主人公", "You neither!");
    Voice_PlayVoice("D0109005_W00700", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "They're having a fight...");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(9, 0, (#1), 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("D0109005_W00800", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student B", "Maybe they're breaking up...\nThey should do this at another\nplace.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("D0109005_I00900", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "Perhaps I stand out too much....\nAfter all.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Just a little...\nShould we go to the rooftop?\nI think it will be quieter than\nhere.");
    Voice_PlayVoice("D0109005_I01000", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "Sure.");
    Environment_StopME(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(9, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_Chara_GS2(9, "M9_01F", 0);
    Background_Bg_GS2("BG_SC500_AU_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0109005_I01100", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "Eh... what a nice view.\nHanegasaki Lighthouse seems so close\nto here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Doesn't it? I like the beach there.\nI occasionally take walks there.");
    Character_BlinkStart(9, 2, (#1), 1);
    Voice_PlayVoice("D0109005_I01200", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "It must be beautiful there.");
    Message_Who(0);
    Message_MsgDisp("主人公", "So, what came to your mind?");
    Character_BlinkStart(9, 0, (#1), 1);
    Voice_PlayVoice("D0109005_I01300", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "Right.\nI have tickets to a SUPER CHARGER\nconcert.\nEh... I just happened to get them.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Amazing!\nIt's quite hard to get a hold of\nthose tickets, right?");
    Voice_PlayVoice("D0109005_I01400", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "Maybe. So...\nMy friend who I was supposed to go\nwith kind of can't make it anymore,\nso...");
    Character_ChFace(0, 0, 6);
    Voice_PlayVoice("D0109005_I01500", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "It's this Sunday...\nSo if it's alright with you, maybe?\nWe could go together...");
    Message_MsgSel("Of course!", "I'll have to pass.");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "Of course! But is it alright?\nAren't the tickets expensive?");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("D0109005_I01600", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Don't worry about it!\nIt was worth all that trouble!\nAlright!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_ChFace(0, 0, 0);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0109005_I01700", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Ah, no, I meant it was worth\nwaiting.");
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("D0109005_I01800", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Let's go home.\nSo, next Sunday, we'll meet at the\nnew Habataki Station!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(9, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Next Sunday at the new Habataki\nStation, huh...\nI must not be late!)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah! Contact details...\nI should remember to ask him on\nSunday.)");
        Date_DateReserveAkagi();
        Date_SetNextSandayDateEvent(9);
        break ;
        case 1:
        Message_Who(0);
        Message_MsgDisp("主人公", "I'll have to pass on that.");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("D0109005_I01900", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "... Really, I see.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Sorry, Akagi-kun.");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("D0109005_I02000", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "It's fine! I'm also sorry...");
        Voice_PlayVoice("D0109005_I02100", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Since I have these tickets, I might\nas well try to invite some colleague\nfrom the Student Council.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(9, 3, (#1), 1);
        Character_ChFace(0, 3, 1);
        Voice_PlayVoice("D0109005_I02200", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Goodbye then.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(9, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Akagi-kun looked a little sad.\nPerhaps it's better this way.)");
        break ;
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(9, 86, 1);
    }
