section "d01_m1_004"{
    Character_BlinkStart(1, 1, (#1), 1);
    Character_BlinkStart(1, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC303_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(I came early because it's my turn\nfor classroom duties, but I might\nhave come too early.\nI'm probably the first... Hmm?)");
    Music_PlayBGM(0, "MN_C_01_002_D00", 127, 40);
    Still_Event("EV_01_10", #1, 0, 60);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Isn't that ｛Saeki＊＊｝?\nHe's studying... Huh?)");
    Still_Approach(1, 9, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(He's wearing glasses!!\nWow, how rare...)");
    Still_ApproachEnd();
    SoundEffect_PlayStream(3, "SS_DSE_141_000");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah!");
    Voice_PlayVoice("D0101004_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Hmm?");
    Character_ChFace(0, 3, 2);
    Character_BlinkStart(1, 2, (#1), 1);
    Character_Chara_GS2(1, "M1_01F", 0);
    Background_Bg_GS2("BG_SC303_CO_0", #1, #1, 0);
    Still_Event("");
    Voice_PlayVoice("D0101004_A00100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "You were silently watching me,\nweren't you?\nYou've got bad hobbies.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sorry! ...\nBut why are you here so early?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0101004_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Last night I had to check the stock,\nso I couldn't prepare for class.\nWhen I'm at the store, I end up\nworking.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see...\nIt must be tough, balancing working\nat the store and school.");
    Character_BlinkStart(1, 3, (#1), 1);
    Voice_PlayVoice("D0101004_A00300", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Not really.\nI willingly do these things.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, I see.\nHey, so you own a pair of glasses?\nThat's surprising.");
    Character_BlinkStart(1, 0, (#1), 1);
    Voice_PlayVoice("D0101004_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Isn't it normal for people with bad\neyesight?\nIt's more comfortable reading books\nwith them.");
    Message_Who(0);
    Message_MsgDisp("主人公", "But you usually wear contacts. Why?");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(1, 2, (#1), 1);
    Voice_PlayVoice("D0101004_A00500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Because... glasses are uncool.");
    Message_Who(0);
    Message_MsgDisp("主人公", "You think so?\nI think they suit you quite well,\nthough.");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(1, 3, (#1), 1);
    Voice_PlayVoice("D0101004_A00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "No they don't!\nAh, geez, go somewhere else!\nI have to finish before everyone\ncomes!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay! Sorry for interrupting!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I see...\n｛Saeki＊＊｝ puts a lot of\neffort in when people aren't\nwatching him...)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    Parameter_AddCh1Param(1, 61, 6);
    Parameter_AddCh1Param(1, 60, 3);
    Parameter_AddCh1Param(1, 62, #5);
    }
