section "d01_m3_001"{
    Character_BlinkStart(3, 1, (#1), 1);
    Character_BlinkStart(3, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC302_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Today is election day for the\nStudent Council Executives.\nThe speeches will be starting\nsoon...");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SC603_LI_0", #1, #1, 0);
    Environment_PlayME(1, "SN_BGE_027_014", 127, 0);
    Voice_PlayVoice("D0103001_W00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Moderator", "Please be quiet.\nNext is a 2nd year, Hikami\nItaru-kun.\nPlease go ahead.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, it's ｛Hikami＊＊｝.)");
    Still_Event("EV_03_05", #1, 0, 60);
    Still_Event("EV_03_06", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_03_005_D00", 127, 40);
    Voice_PlayVoice("D0103001_C00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I want to ask everyone if they are\nsatisfied with their current high\nschool life.");
    Environment_StopME(1, 40);
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("D0103001_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "There are people who are studying\nhard, people who are doing sports,\nand people who are searching for\nlifelong friends.");
    Still_StillFace(0, 6, 1);
    Still_Approach(3, 65, 0, 0, 1, 1);
    Voice_PlayVoice("D0103001_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "...\nHaha, this is like a greeting at a\nwelcoming ceremony.");
    Still_ApproachEnd();
    SoundEffect_PlayStream(2, "SS_T_00_015_S00");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0103001_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "In other words, everyone is spending\nthis precious time doing as they\nplease...");
    Voice_PlayVoice("D0103001_C00500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "As students, shouldn't we be\nbreaking down obstacles with our own\nhands?");
    Still_StillFace(0, 0, 2);
    Still_StillFace(0, 4, 1);
    Voice_PlayVoice("D0103001_C00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Without restraint, I would like to\nbreak the distinction between the\nrules and the students!");
    Still_Approach(3, 65, 0, 0, 1, 5);
    Voice_PlayVoice("D0103001_C00700", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "And I want to find a solution to\neach and every thing!");
    SoundEffect_PlayStream(2, "SS_DSE_143_000");
    System_Wait(30);
    Message_CloseMsg();
    Screen_WipeOut(2);
    SoundEffect_StopStream(2, 60);
    Still_Event("");
    Music_StopBGM(0, 40);
    System_Wait(60);
    Background_Bg_GS2("BG_SC603_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0103001_W00800", #1, "");
    Message_Who(0);
    Message_MsgDisp("Moderator", "As a result of the votes, the next\nStudent Council President is Hikami\nItaru-kun.");
    Voice_PlayVoice("D0103001_W00900", #1, "");
    Message_Who(0);
    Message_MsgDisp("Moderator", "Now then, we will hear Hikami\nItaru's aspirations as the next\nStudent Council President...");
    Message_CloseMsg();
    Screen_WipeOut(2);
    System_Wait(60);
    Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hikami＊＊｝,\ncongratulations!");
    Character_ChFace(0, 0, 10);
    Character_Chara_GS2(3, "M3_01F", 0);
    Music_PlayBGM(0, "MN_C_03_000_D00", 127, 40);
    Voice_PlayVoice("D0103001_C01000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "It's you!\nThank you, Things will get busy from\nnow on.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah. Do your best!");
    Voice_PlayVoice("D0103001_C01100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Of course.\nI'm also counting on your advice.\nI want to hear lots of opinions.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay!");
    Voice_PlayVoice("D0103001_C01200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I must head to the Student Council\nroom...\nI'm sorry, excuse me.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(3, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Isn't that great,\n｛Hikami＊＊｝!)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(3, 86, 1);
    Parameter_AddCh1Param(3, 61, 6);
    Parameter_AddCh1Param(3, 60, 3);
    Parameter_AddCh1Param(3, 62, #5);
    }
