section "d01_m1_000"{
    Character_BlinkStart(1, 1, (#1), 1);
    Character_BlinkStart(1, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC100_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(That's another day gone by!\nI should hurry home!)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(There's a crowd over there...\nMaybe a famous person is over\nthere?)");
    Voice_PlayVoice("D0101000_A00000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Sorry. I really have to go.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, it's ｛Saeki＊＊｝...)");
    Environment_StopME(1, 40);
    Still_Event("EV_01_06", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_01_003_D01", 127, 40);
    Voice_PlayVoice("D0101000_W00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "Eh～!\nYou can at least stay a little\nlonger, right?");
    Voice_PlayVoice("D0101000_A00200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I'm sorry.\nI sort of have something to do at\nhome.");
    Voice_PlayVoice("D0101000_W00300", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student B", "No!\nYou said the same thing last time!");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0101000_A00400", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Haha... Did I?\nAh, that's right, I have prep-school\ntoday!");
    Voice_PlayVoice("D0101000_W00500", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student C", "That's so sly～!\nI want to see proof～!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Whoa...\nHe's so popular that he's surrounded\nby girls.\nJust like in manga...)");
    Still_StillFace(0, 6, 2);
    Still_Approach(1, 5, 0, 0, 1, 1);
    Voice_PlayVoice("D0101000_A00600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I'm beat.");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Saeki＊＊｝!");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0101000_A00700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Ah!\nHey, are you going home now, too?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yeah, I am.\nYou addressed me so politely...");
    Voice_PlayVoice("D0101000_A00800", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I'll walk you home then.\nYou still don't know the way home,\nright?");
    Voice_PlayVoice("D0101000_W00900", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student A", "That's unfair～! Walk us home, too!");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0101000_A01000", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "She lives in my neighborhood.\nShe also said she just moved here,\nso she still doesn't know the way\nhome.");
    Still_Approach(1, 5, 0, 0, 1, 5);
    Message_Who(0);
    Message_MsgDisp("主人公", "No, I'm fine!");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0101000_A01100", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "......\nShe said she still doesn't know the\nway home.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh!? Umm, ehh, y-yeah...");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0101000_A01200", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Shall we go? I'm going home, too.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Why is he being so polite...?)");
    Voice_PlayVoice("D0101000_W01300", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student B", "Geez! Saeki-kun is so nice～!");
    Voice_PlayVoice("D0101000_W01400", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student C", "Maybe I should move to Saeki-kun's\nneighborhood, too～!");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm sorry, e-everyone.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ugh...\nTheir death stares could kill...)");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Music_PlayBGM(0, "MN_C_01_002_D01", 127, 40);
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(1, 3, (#1), 1);
    Character_Chara_GS2(1, "M1_02F", 0);
    Background_Bg_GS2("BG_SC000_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0101000_A01500", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Thanks.\nIf I stick around at school, I won't\nmake it back in time to open\nSangosho.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see, you're busy with\nSangosho......\nYou're popular as well, aren't you?");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(1, 2, (#1), 1);
    Character_ChFace(0, 3, 4);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("D0101000_A01600", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Shut up.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Aha, you're blushing.\nBut why are you keeping Sangosho a\nsecret?");
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("D0101000_A01700", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I'm keeping it a secret from school.\nSangosho opens till late, so that's\nan issue.\nAlso...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Also...?");
    Character_BlinkStart(1, 3, (#1), 1);
    Voice_PlayVoice("D0101000_A01800", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "I can't let it affect my grades.\nIt must not become a problem for\nschool.\nThose are the terms.");
    Message_Who(0);
    Message_MsgDisp("主人公", "\"Terms\"?\nDo you mean that's what you promised\nyour parents?");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(1, 0, (#1), 1);
    Voice_PlayVoice("D0101000_A01900", #1, "");
    Message_Who(1);
    Message_MsgDisp("Saeki", "Well, yeah...\nOh no, I have to hurry! Later!");
    Character_Chara_GS2(1, "NON");
    Music_StopBGM(0, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Saeki＊＊｝ has it\nrough...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(1, 86, 1);
    Parameter_AddCh1Param(1, 61, 6);
    Parameter_AddCh1Param(1, 60, 3);
    Parameter_AddCh1Param(1, 62, #5);
    }
