section "d01_mb_003"{
    Background_Bg_GS2("BG_SC220_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    SoundEffect_PlayStream(2, "SS_T_00_079_S00");
    Message_Who(0);
    Message_MsgDisp("主人公", "(The weather is nice today and I've\ngot a \"Super Hot Curry Bun\".\nI'll go eat on the rooftop!)");
    Voice_PlayVoice("NS_92_000_02900", #1, "");
    Message_Who(26);
    Message_MsgDisp("？？？", "You look energetic today.");
    Character_Chara_GS2(26, "MB_01F", 0);
    Character_ChFace(0, 0, 10);
    Music_PlayBGM(0, "MN_C_92_000_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, Majima-senpai! Yes. Umm...\nwhat about Senpai?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("NS_92_000_03000", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Hmm, yeah, I'm half okay.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, as expected, what happened\nbefore...");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(26, 3, (#1), 1);
    Voice_PlayVoice("NS_92_000_03100", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Ouch...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh!?");
    Voice_PlayVoice("NS_92_000_03200", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Don't worry about it.\nWhen I remember that, it hurts my\nchest, is all...");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm sorry!");
    Character_BlinkStart(26, 1, (#1), 1);
    Character_BlinkStart(26, 0, (#1), 1);
    Voice_PlayVoice("NS_92_000_03300", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "I think it would be healed if you\ngave me half of that \"Super Hot\nCurry Bun\"...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah! Haha, that's fine by me.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(26, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SC500_?_0", 1, #1, 0);
    Character_Chara_GS2(26, "MB_01F", 0);
    Screen_WipeIn(2);
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("NS_92_000_03400", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Hmm...\nSo that means you also believe in\nthe legend about the lighthouse?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is it a bit childish?");
    Voice_PlayVoice("NS_92_000_03500", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Hmm～... Maybe just a little.\nBut actually, I--");
    SoundEffect_PlayStream(2, "SS_T_00_079_S00");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("NS_92_000_03600", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Oh, the bell.\nIt's unfortunate, but I will take my\nleave here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("NS_92_000_03700", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "It was very fun.\nWhen I'm alone, all I think about\nare painful things...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Majima-senpai is still hurt...)");
    Character_ChFace(0, 0, 6);
    Character_BlinkStart(26, 2, (#1), 1);
    Voice_PlayVoice("NS_92_000_03800", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Hey...\nIf it's alright with you, let's go\nout this Sunday.\nThe two of us.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?");
    Message_MsgSel("But, I'm kind of...", "That's a little...");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "But, I'm kind of not suitable to be\nyour...\nI mean Majima-senpai probably\nprefers more--");
        Voice_PlayVoice("NS_92_000_03900", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Prettier, older types?");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's because Senpai seems really\nmature.");
        Character_BlinkStart(26, 1, (#1), 1);
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_04000", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I really like that you are so\nhumble.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I...");
        Voice_PlayVoice("NS_92_000_04100", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I want to know more about you.\nSo this Sunday at the Forest Park\nEntrance.\nOkay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm... Okay.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("NS_92_000_04200", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Thank you.");
        Character_Chara_GS2(26, "NON");
        Music_StopBGM(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Majima-senpai invited me out on a\ndate...)");
        System_GlobalWork(19, 0, 3);
        Date_SetNextSandayDateEvent(26);
        break ;
        case 1:
        Character_ChFace(0, 0, 6);
        Character_ChFace(0, 4, 1);
        Character_BlinkStart(26, 3, (#1));
        Voice_PlayVoice("NS_92_000_04300", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Really... That's unfortunate.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I'm sorry...");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(26, 1, (#1));
        Character_BlinkStart(26, 3, (#1));
        Voice_PlayVoice("NS_92_000_04400", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Really...\nYou're actually quite level-headed.\nThat's bothersome, but I'll ask\nsomeone else out.\nLater.");
        Character_Chara_GS2(26, "NON");
        Music_StopBGM(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "(... Majima-senpai...\nWhat a character.)");
        System_GlobalWork(19, 0, 30);
        break ;
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
