section "d01_g1_000"{
    Character_BlinkStart(10, 1, (#1), 1);
    Character_BlinkStart(10, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC421_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Next is the cheer squad battle.)");
    Voice_PlayVoice("D0110000_W00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Female Student", "Kya! Toudou-san!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Eh? ｛Toudou＊＊｝?)");
    Music_StopBGM(0, 40);
    Still_Event("EV_10_01", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_10_000_D02", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It really is ｛Toudou＊＊｝!\nW-Why is she participating!?)");
    Voice_PlayVoice("D0110000_J00100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... You guys! Are you ready!?");
    Voice_PlayVoice("D0110000_W00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Male Student", "Yes, leader!");
    Voice_PlayVoice("D0110000_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I can't hear you!");
    Voice_PlayVoice("D0110000_W00400", #1, "");
    Message_Who(0);
    Message_MsgDisp("Male Student", "Yes, leader!!");
    Voice_PlayVoice("D0110000_J00500", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Alright! Let's go!");
    Voice_PlayVoice("D0110000_W00600", #1, "");
    Message_Who(0);
    Message_MsgDisp("Male Student", "Yes, leader!!!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(They're really pumped up...!)");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Environment_StopME(1, 40);
    Background_Bg_GS2("BG_SC421_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGB_016_000", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Toudou＊＊｝!");
    Character_Chara_GS2(10, "G1_08F", 0);
    Voice_PlayVoice("", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "The cheering battle was amazing!");
    Voice_PlayVoice("D0110000_J00700", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "What, you saw?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah! You were cool.\nBut why are you participating?");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(10, 3, (#1), 1);
    Voice_PlayVoice("D0110000_J00800", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... I have to do something.\nI don't hate this, so it's fine.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see... Ah, ｛Shiba＊＊｝.");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(10, 3, (#1), 1);
    Character_ChFace(0, 3, 0);
    Character_ChFace(0, 4, 1);
    Character_Chara_GS2(2, "M2_08F", 0, 0, 1);
    Voice_PlayVoice("D0110000_J00900", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "......");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝ also saw your\ncheering, ｛Toudou＊＊｝!");
    Voice_PlayVoice("D0110000_B01000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Yeah.\nYou guys were really into it.");
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("D0110000_J01100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... You saw that?");
    Voice_PlayVoice("D0110000_B01200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "You guys were pretty into it, it\nwould've been harder not seeing it.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0110000_J01300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "......");
    Character_ChFace(1, 2, 0);
    Character_BlinkStart(2, 2, (#1), 2);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("D0110000_B01400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Your cheer was the most\norganized....\nMaybe you won the cheer battle?");
    Voice_PlayVoice("D0110000_B01500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Later.");
    Character_Chara_GS2(2, "NON");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝ also voted for\nyour team.\nIsn't that a sure win,\n｛Toudou＊＊｝?");
    Voice_PlayVoice("D0110000_J01600", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I thought he wasn't watching...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("D0110000_J01700", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Dammit, he always sees me doing\nabsurd things...");
    Character_Chara_GS2(10, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(What's up with\n｛Toudou＊＊｝...)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(10, 86, 1);
    Parameter_AddCh1Param(10, 86, 1);
    Parameter_AddCh1Param(10, 60, 5);
    }
