section "d01_mb_006"{
    int var0;
    Background_Bg_GS2("BG_EX200_CO_0", #1, #1, 0);
    Character_Chara_GS2(26, "MB_02F", 0);
    Music_PlayBGM(0, "MN_C_92_000_D00", 127, 40);
    Screen_WipeIn(2);
    var0 = System_GlobalWork(19, 1);
    switch (var0){
        case 5:
        Character_ChFace(0, 0, 11);
        Character_ChFace(0, 2, 4);
        Character_BlinkStart(26, 0, (#1), 1);
        Character_ChFace(0, 3, 4);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("NS_92_000_07600", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Huh, you really started working here\npart-time?");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Yeah.");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_07700", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "So then, waitress.\nI'd like another cup of coffee.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(......)");
        System_GlobalWork(19, 0, 6);
        break ;
        case 6:
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_07800", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Hey, it seems like you're still\nworking here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm...");
        Voice_PlayVoice("NS_F1_922_00000", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Customer", "Tarou-kun! Let's go already!");
        Voice_PlayVoice("NS_92_000_07900", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Ah, I'm going now! *Sigh*...\nThat's how it is.\nWell, do your best.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(......)");
        break ;
        case 7:
        SoundEffect_PlayStream(3, "SS_T_00_129_M00");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_08000", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Hey, you're working hard.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, Tarou-kun... Yeah.");
        Voice_PlayVoice("NS_92_000_08100", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "You've gotten quite used to your\nposition.\nWell, you look quite plain, though.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so...");
        Voice_PlayVoice("NS_F2_921_00000", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Customer", "Hey, who is that?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("NS_92_000_08200", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Ah, she's a junior from my high\nschool...\nIsn't that right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Tarou-kun...");
        Voice_PlayVoice("NS_F2_921_00100", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Customer", "Hey you, wait a second, don't go\nacting over-familiar with him, okay?");
        Message_Who(0);
        Message_MsgDisp("主人公", "... I'm sorry.");
        Voice_PlayVoice("NS_92_000_08300", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Now, now.\nLet's go out to eat something.");
        Voice_PlayVoice("NS_F2_921_00200", #1, "");
        Message_Who(0);
        Message_MsgDisp("Female Customer", "I want Neapolitan Spaghetti!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(......)");
        break ;
        case 8:
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_08400", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "You're finishing soon, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, Tarou-kun!\nYeah, in just a little while.");
        Voice_PlayVoice("NS_92_000_08500", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "My plans for today fell through.\nGet ready, we're going out later.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Music_StopBGM(0, 40);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Background_Bg_GS2("BG_EX101_?_2", 1, #1, 0);
        Character_ChFace(0, 0, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("NS_92_000_08600", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Now then... Where should we go now?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, Tarou-kun, I have to go home\nnow.");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("NS_92_000_08700", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Huh? Didn't you want to be with me?");
        Message_Who(0);
        Message_MsgDisp("主人公", "But it's already late...");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_08800", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I see, you're still in school.\nI can't see you home today.\nSo take care.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Sigh*...)");
        break ;
        case 9:
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_08900", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Have you finished, yet?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, Tarou-kun!\nYeah, in just a little while.");
        Voice_PlayVoice("NS_92_000_09000", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I have time.\nCan you get ready right away?\nWe're going out.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Music_StopBGM(0, 40);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Background_Bg_GS2("BG_EX101_?_2", 1, #1, 0);
        Character_ChFace(0, 0, 0);
        Screen_WipeIn(2);
        SoundEffect_PlaySE(339);
        System_Wait(70);
        SoundEffect_StopSE(339, 0);
        SoundEffect_PlaySE(319);
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("NS_92_000_09100", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Oh, a phone call.");
        Character_Chara_GS2(26, "NON");
        Voice_PlayVoice("NS_92_000_09200", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Ah, you! Eh, now?");
        SoundEffect_StopSE(31, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "(So Tarou-kun bought a phone...)");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Character_Chara_GS2(26, "MB_02F", 0);
        Character_ChFace(0, 0, 0);
        Screen_WipeIn(2);
        Environment_PlayME(0, "");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("NS_92_000_09300", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Well, this is how it goes.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_09400", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I'm meeting someone.\nSo that means I can't see you home.\nLater.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Okay.");
        Character_Chara_GS2(26, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I wonder if Tarou-kun is going to\nhang out somewhere else...)");
        break ;
        case 10:
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_09500", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Your shift is about to end, right?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Tarou-kun. Umm, it's already late...");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("NS_92_000_09600", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Isn't it?\nSo I'm going to see you home.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Really?");
        Character_BlinkStart(26, 3, (#1));
        Voice_PlayVoice("NS_92_000_09700", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Really. So, get ready.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay.");
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(26, "NON");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Character_Chara_GS2(26, "MB_02F", 0);
        Background_Bg_GS2("BG_EX101_?_2", 1, #1, 0);
        Character_ChFace(0, 0, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Thank you for seeing me home.\nYou're nice today, Tarou-kun...");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("NS_92_000_09800", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "You're mean.\nI do these kinds of things, too.\nI'm a gentleman, aren't I?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Sorry, you're right.");
        Character_ChFace(0, 0, 6);
        Character_BlinkStart(26, 2, (#1));
        Voice_PlayVoice("NS_92_000_09900", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "By the way, let's go on a date this\nSunday.\nIt's been a while.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... This Sunday, during the day?");
        Character_ChFace(0, 0, 0);
        Character_BlinkStart(26, 1, (#1));
        Character_BlinkStart(26, 0, (#1));
        Voice_PlayVoice("NS_92_000_10000", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Yeah.\nWe should meet occasionally during\nthe day....\nYou don't want to?");
        Message_Who(0);
        Message_MsgDisp("主人公", "No, no, I'm glad...");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("NS_92_000_10100", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Then it's decided.\nI remember, let's go to the Forest\nPark that we went to together that\ntime.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay, I look forward to it.");
        Voice_PlayVoice("NS_92_000_10200", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Ah, right. I have one request.");
        Message_Who(0);
        Message_MsgDisp("主人公", "What is it?");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("NS_92_000_10300", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "My principle is not to interfere\nwith a girl's clothing, but will you\ncome wearing some mature clothes?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Maybe I do look childish...");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("NS_92_000_10400", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "See, I'm a university student.\nIt's called balance.\nBe as sexy as you can, okay?");
        Message_MsgSel("I'll try my best.", "I can't...");
        switch (Message_TextSelect()){
            case 0:
            Message_Who(0);
            Message_MsgDisp("主人公", "Okay. I'll try my best, then.");
            Character_ChFace(0, 0, 6);
            Character_BlinkStart(26, 2, (#1), 1);
            Voice_PlayVoice("NS_92_000_10500", #1, "");
            Message_Who(26);
            Message_MsgDisp("Majima", "It'll surely suit you.\nI'm looking forward to it....\nGoodnight.");
            Character_Chara_GS2(26, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Sexy clothes, huh...\nAlright, I'll do my best!)");
            break ;
            case 1:
            Message_Who(0);
            Message_MsgDisp("主人公", "Being sexy... is impossible for me.");
            Character_ChFace(0, 0, 8);
            Character_BlinkStart(26, 3, (#1), 1);
            Voice_PlayVoice("NS_92_000_10600", #1, "");
            Message_Who(26);
            Message_MsgDisp("Majima", "Then let's not go out.");
            Message_Who(0);
            Message_MsgDisp("主人公", "... Huh?");
            Character_ChFace(0, 0, 0);
            Character_BlinkStart(26, 1, (#1), 1);
            Character_BlinkStart(26, 0, (#1), 1);
            Voice_PlayVoice("NS_92_000_10700", #1, "");
            Message_Who(26);
            Message_MsgDisp("Majima", "Just be as sexy as you can.\nSo, I'll see you on Sunday. Later.");
            Character_Chara_GS2(26, "NON");
            Message_Who(0);
            Message_MsgDisp("主人公", "(How troubling...)");
            break ;
            }
        System_GlobalWork(19, 0, 11);
        Date_SetNextSandayDateEvent(26);
        break ;
        }
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
