section "d01_m9_004"{
    Character_BlinkStart(9, 1, (#1), 1);
    Character_BlinkStart(9, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC101_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh, what's happening?\nThere are a lot of students from\nHabataki Academy...)");
    Voice_PlayVoice("D0109004_I00000", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "Hey!");
    Character_Chara_GS2(9, "M9_01F", 0);
    Music_PlayBGM(0, "MN_C_09_000_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Akagi-kun! You surprised me...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0109004_I00100", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "Hahaha! Yeah.\nIt was worth surprising you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Geez!");
    Voice_PlayVoice("D0109004_I00200", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "Sorry!\nWe had to come to Hanegasaki today,\nso I thought it would be nice if I\ncould see you.");
    Voice_PlayVoice("D0109004_I00300", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "And then you really did appear!\nAmazing!\nThat's why I'm so glad to--");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0109004_I00400", #1, "");
    Message_Who(9);
    Message_MsgDisp("Akagi", "... Ah, was I just being a nuisance?");
    Message_MsgSel("No, I'm glad, too.", "Just a little.");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "No, I'm glad, too...\nBut it's a little embarrassing.\nEveryone is looking at us.");
        Character_ChFace(0, 2, 1);
        Character_ChFace(0, 3, 0);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("D0109004_I00500", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "R-Really. That's right. Haha...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hey, anyway, what are you doing\ntoday?\nYou're with other students as well.");
        Character_ChFace(0, 0, 0);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("D0109004_I00600", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Let's see, what are we doing?");
        Character_Chara_GS2(3, "M3_01F", 0, 0, 1);
        if (Parameter_GetCh1Param(3, 514) == 1){
            Voice_PlayVoice("D0109004_C00700", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Are you Akagi-kun?");
            Character_ChFace(0, 0, 11);
            Voice_PlayVoice("D0109004_I00800", #1, "");
            Message_Who(9);
            Message_MsgDisp("Akagi", "Ah, yes. That is right.");
            Voice_PlayVoice("D0109004_C00900", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Sorry for making you wait.\nI came to greet the students from\nHabataki Academy, as a member of\nHanegasaki's Student Council.");
            Character_ChFace(0, 0, 9);
            Voice_PlayVoice("D0109004_I01000", #1, "");
            Message_Who(9);
            Message_MsgDisp("Akagi", "Ah, thank you for that.\nSo, you are--");
            Voice_PlayVoice("D0109004_C01100", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Let's introduce ourselves later.\nThere is little time left before the\nmeeting starts.\nCome with me.");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("D0109004_I01200", #1, "");
            Message_Who(9);
            Message_MsgDisp("Akagi", "Y-Yes.");
            Character_Chara_GS2(3, "NON");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(9, 2, (#1), 1);
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("D0109004_I01300", #1, "");
            Message_Who(9);
            Message_MsgDisp("Akagi", "There are amazing people at\nHanegasaki Academy too...\nIs everyone like that?");
            Message_Who(0);
            Message_MsgDisp("主人公", "As if!");
            Voice_PlayVoice("D0109004_I01400", #1, "");
            Message_Who(9);
            Message_MsgDisp("Akagi", "You're right. That's fine...");
            Character_ChFace(0, 0, 11);
            Character_BlinkStart(9, 0, (#1), 1);
            Voice_PlayVoice("D0109004_C01500", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Akagi-kun! Hurry!");
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("D0109004_I01600", #1, "");
            Message_Who(9);
            Message_MsgDisp("Akagi", "I'm going now! Later!");
            }
        else {
            Voice_PlayVoice("D0109004_C00700", #1, "");
            Message_Who(3);
            Message_Who(3);
            Message_MsgDisp("？？？", "Are you Akagi-kun?");
            Character_ChFace(0, 0, 11);
            Voice_PlayVoice("D0109004_I00800", #1, "");
            Message_Who(9);
            Message_MsgDisp("Akagi", "Ah, yes. That is right.");
            Voice_PlayVoice("D0109004_C00900", #1, "");
            Message_Who(3);
            Message_Who(3);
            Message_MsgDisp("？？？", "Sorry for making you wait.\nI came to greet the students from\nHabataki Academy, as a member of\nHanegasaki's Student Council.");
            Character_ChFace(0, 0, 9);
            Voice_PlayVoice("D0109004_I01000", #1, "");
            Message_Who(9);
            Message_MsgDisp("Akagi", "Ah, thank you for that.\nSo, you are--");
            Voice_PlayVoice("D0109004_C01100", #1, "");
            Message_Who(3);
            Message_Who(3);
            Message_MsgDisp("？？？", "Let's introduce ourselves later.\nThere is little time left before the\nmeeting starts.\nCome with me.");
            Character_ChFace(0, 2, 4);
            Character_ChFace(0, 3, 5);
            Voice_PlayVoice("D0109004_I01200", #1, "");
            Message_Who(9);
            Message_MsgDisp("Akagi", "Y-Yes.");
            Character_Chara_GS2(3, "NON");
            Character_ChFace(0, 2, 0);
            Character_BlinkStart(9, 2, (#1), 1);
            Character_ChFace(0, 3, 4);
            Voice_PlayVoice("D0109004_I01300", #1, "");
            Message_Who(9);
            Message_MsgDisp("Akagi", "There are amazing people at\nHanegasaki Academy too...\nIs everyone like that?");
            Message_Who(0);
            Message_MsgDisp("主人公", "As if!");
            Voice_PlayVoice("D0109004_I01400", #1, "");
            Message_Who(9);
            Message_MsgDisp("Akagi", "You're right. That's fine...");
            Character_ChFace(0, 0, 11);
            Character_BlinkStart(9, 0, (#1), 1);
            Voice_PlayVoice("D0109004_C01500", #1, "");
            Message_Who(3);
            Message_Who(3);
            Message_MsgDisp("？？？", "Akagi-kun! Hurry!");
            Character_ChFace(0, 3, 1);
            Voice_PlayVoice("D0109004_I01600", #1, "");
            Message_Who(9);
            Message_MsgDisp("Akagi", "I'm going now! Later!");
            }
        Music_StopBGM(0, 40);
        Character_Chara_GS2(9, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, later!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(So Akagi-kun is on Habataki\nAcademy's Student Council.\nHe must be an honor student...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Oh no!\nI forgot to ask him for his contact\ndetails, again...)");
        System_GlobalWork(22, 0, 1);
        break ;
        case 1:
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, a little.\nEveryone is looking over here.\nPerhaps it's just a weird\nmisunderstanding.");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("D0109004_I01700", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "I see... You're right.\nSorry for causing trouble for you.");
        Character_Chara_GS2(3, "M3_01F", 0, 0, 1);
        if (Parameter_GetCh1Param(3, 514) == 1){
            Message_Who(3);
            Voice_PlayVoice("D0109004_C01800", #1, "");
            Message_Who(3);
            Message_MsgDisp("Hikami", "Akagi-kun! Hurry!");
            }
        else {
            Message_Who(3);
            Voice_PlayVoice("D0109004_C01800", #1, "");
            Message_Who(3);
            Message_MsgDisp("？？？", "Akagi-kun! Hurry!");
            }
        Character_ChFace(0, 2, 1);
        Character_BlinkStart(9, 3, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("D0109004_I01900", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "I'm going now! Later!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(9, "NON");
        Character_Chara_GS2(9, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, later.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah!\nI didn't get to ask him for his\ncontact details...\nAh, well it can't be helped.)");
        break ;
        }
    Message_CloseMsg();
    Environment_StopME(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(9, 86, 1);
    }
