section "d01_m4_003"{
    Character_BlinkStart(4, 1, (#1), 1);
    Character_BlinkStart(4, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC202_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's really late.\nI should go home now.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SC000_WI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? Over there is...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝!");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(4, "M4_05F", 0);
    Music_PlayBGM(0, "MN_C_04_000_D02", 127, 40);
    Voice_PlayVoice("", 4, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Are you going out somewhere?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0104003_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah.\nI'm going to get some clothes to\nwear at lives.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so?\nWhat kind of clothes are you\nplanning to buy?");
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0104003_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I don't know yet.\nSo do you want to come along?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is it okay for me to come along?");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0104003_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I don't mind as long as you don't\nget in the way.\nAlright, let's go!");
    Character_Chara_GS2(4, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, wait!");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_Chara_GS2(4, "M4_05F", 0);
    Background_Bg_GS2("BG_WF100_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0104003_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "So we'll split up here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh!");
    Voice_PlayVoice("D0104003_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "When I choose clothes I start to\nignore everything around me.\nSo there's no point in going around\ntogether.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see...");
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("D0104003_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Go to the stores you like.\nWe'll meet back here later.");
    Voice_PlayVoice("D0104003_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Later.");
    Character_Chara_GS2(4, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He really left...\nI should also go to some stores.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_WF100_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Is it about time I went back...\nHuh? Over there is...)");
    Still_Event("EV_04_09", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_04_003_D01", 127, 40);
    Still_Approach(4, 98, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's ｛Hariya＊＊｝.\nWho is he with?)");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, he's waving.\nIs he already done?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_WF100_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Did you find anything good,\n｛Hariya＊＊｝?");
    Character_ChFace(0, 0, 10);
    Character_Chara_GS2(4, "M4_05F", 0);
    Voice_PlayVoice("D0104003_D00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I've got the perfect things.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, did those people who you were\nwith before help you choose?");
    Voice_PlayVoice("D0104003_D00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Ah, those guys...");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("D0104003_D00900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "What the-- You saw?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, just a little bit when I came\nhere.\nAre they your friends?");
    Character_ChFace(0, 4, 1);
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("D0104003_D01000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Don't go looking as you please.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("D0104003_D01100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... They're the band members.\nThere's one guy I've known since\nelementary school.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so! Hmm...\nthat's why you looked so happy.");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("D0104003_D01200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Huh?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I mean you looked so carefree.");
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("D0104003_D01300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "As if! ... Are you an idiot!?");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(4, 2, (#1), 1);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("D0104003_D01400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "But we're all working hard, aiming\nfor the same thing.\nSo it's not like it's not fun...");
    Voice_PlayVoice("D0104003_D01500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It's just...");
    Character_ChFace(0, 0, 8);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("D0104003_D01600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "They're different from the guys at\nschool, I don't need to put effort\nin to talk to them!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(That's basically what I just\nsaid...)");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0104003_D01700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Anyway!\nYou're probably curious as to what I\nbought, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yeah.");
    Voice_PlayVoice("D0104003_D01800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I'll show you, so let's go.\nLet's go to a larger shop!\nCome on, let's go!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(4, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Is ｛Hariya＊＊｝\nembarrassed?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    Parameter_AddCh1Param(4, 61, 6);
    Parameter_AddCh1Param(4, 60, 3);
    Parameter_AddCh1Param(4, 62, #5);
    }
