section "d01_m9_003"{
    Character_BlinkStart(9, 1, (#1), 1);
    Character_BlinkStart(9, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_NE100_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, I'm hungry!\nMaybe I should grab a bite to eat.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_EX120_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0109003_W00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Clerk", "Welcome to Winning Burger!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Eh～, today I'll have...\nAh, the Teriyaki Udon Burger they\nwere advertising!)");
    Message_Who(0);
    Message_MsgDisp("主人公", "Um, could I please have a Teriyaki\nUdon...");
    Voice_PlayVoice("D0109003_I00100", #1, "");
    Message_Who(9);
    Message_MsgDisp("？？？", "One Teriyaki Udon Burger Meal with\nOolong tea, please.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah!!");
    Voice_PlayVoice("D0109003_I00200", #1, "");
    Message_Who(9);
    Message_MsgDisp("？？？", "? ... Ah!!");
    Character_Chara_GS2(9, "M9_01F", 0);
    Music_PlayBGM(0, "MN_C_09_000_D00", 127, 40);
    Voice_PlayVoice("D0109003_I00300", #1, "");
    Message_Who(9);
    Message_MsgDisp("？？？", "Hey.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Hey.\nUm, about that time--");
    Character_BlinkStart(9, 2, (#1), 1);
    Voice_PlayVoice("D0109003_I00400", #1, "");
    Message_Who(9);
    Message_MsgDisp("？？？", "Gee, shouldn't you just stop with\nthe talking to yourself?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Geez!\nWhy do you have so much to say?");
    Voice_PlayVoice("D0109003_W00500", #1, "");
    Message_Who(0);
    Message_MsgDisp("Clerk", "Umm, is it okay to bundle your order\ntogether?");
    Message_MsgSel("It's fine.", "Of course it's not!");
    switch (Message_TextSelect()){
        case 0:
        Character_BlinkStart(9, 0, (#1), 1);
        Voice_PlayVoice("D0109003_I00600", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "Please do so.");
        Voice_PlayVoice("D0109003_W00700", #1, "");
        Message_Who(0);
        Message_MsgDisp("Clerk", "I understand.\nIt will take approximately 10\nminutes to make one Teriyaki Udon\nBurger, though...");
        Voice_PlayVoice("D0109003_I00800", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "Oh, I will change my order then.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, I will change my order!");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("D0109003_I00900", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "It's fine.\nYou ordered first, didn't you?");
        Message_Who(0);
        Message_MsgDisp("主人公", "But I should apologize for the other\nday...");
        Voice_PlayVoice("D0109003_W01000", #1, "");
        Message_Who(0);
        Message_MsgDisp("Customer", "Please get me a Teriyaki Udon\nBurger!");
        Voice_PlayVoice("D0109003_W01100", #1, "");
        Message_Who(0);
        Message_MsgDisp("Clerk", "Understood!\nOne Teriyaki Udon Burger!");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 4);
        Voice_PlayVoice("D0109003_I01200", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "Ah～");
        Message_Who(0);
        Message_MsgDisp("主人公", "This has happened before.");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("D0109003_I01300", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "...\nAre you still trying to pick a\nfight?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Gee...");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(9, "NON");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Voice_PlayVoice("D0109003_W01400", #1, "");
        Message_Who(0);
        Message_MsgDisp("Clerk", "Thank you very much!");
        Character_Chara_GS2(9, "M9_01F", 0);
        Background_Bg_GS2("BG_NE100_?_1", 1, #1, 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("D0109003_I01500", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "It doesn't seem like it's something\nto wait for.\nI mean the Teriyaki Udon Burger.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Maybe it's better to not put\nteriyaki flavoring on udon.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("D0109003_I01600", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "I agree....\nWe got quite worked up, didn't we?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah. Sorry about last time, okay?\nI said some terribly awful things...");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("D0109003_I01700", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "Ah, don't worry about it.\nAnyhow, we still haven't introduced\nourselves.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That's right!\nI am ｛主人公苗字｝\n｛主人公｝.\nI'm in year ｛学年｝ at\nHanegasaki Academy.");
        Voice_PlayVoice("D0109003_I01800", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Then you're in the same grade as me.\nI am Akagi Kazuyuki.\nI'm the awful \"Habataki Academy\"\nstudent.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Come on, give me a break...");
        Character_BlinkStart(9, 2, (#1), 1);
        Voice_PlayVoice("D0109003_I01900", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Sorry.\nBut do Habataki Academy students\nappear to be proud?");
        Message_Who(0);
        Message_MsgDisp("主人公", "They don't.\nIt's just that there are lots who\nare rich and smart...\nIt feels awkward around them.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(9, 0, (#1), 1);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("D0109003_I02000", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Even around me?");
        Message_Who(0);
        Message_MsgDisp("主人公", "No, not at all!\nThanks to you, my impression of them\nmight have changed.");
        Character_ChFace(0, 0, 0);
        Voice_PlayVoice("D0109003_I02100", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "There are lots of us who live in a\nnormal house.\nBesides, I am not that smart.\nMy parents forcibly enrolled me\nhere.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so?");
        Character_BlinkStart(9, 3, (#1), 1);
        Voice_PlayVoice("D0109003_I02200", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "Because of that I had a hard time\nkeeping up with class and...\nOh no!");
        Message_Who(0);
        Message_MsgDisp("主人公", "What's wrong?");
        Character_BlinkStart(9, 0, (#1), 1);
        Voice_PlayVoice("D0109003_I02300", #1, "");
        Message_Who(9);
        Message_MsgDisp("Akagi", "I have to go to prep school!\nI'll see you later!");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, okay! Do your best!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(9, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I see...\nHabataki Academy students also have\nit tough.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, I didn't ask for his phone\nnumber!\nWe probably won't see each other,\nagain...)");
        System_GlobalWork(21, 0, 1);
        break ;
        case 1:
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("D0109003_I02400", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "Ah, of course!");
        Voice_PlayVoice("D0109003_W02500", #1, "");
        Message_Who(0);
        Message_MsgDisp("Clerk", "O-Okay! I understand.");
        Character_BlinkStart(9, 3, (#1), 1);
        Voice_PlayVoice("D0109003_I02600", #1, "");
        Message_Who(9);
        Message_MsgDisp("？？？", "So, farewell!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(9, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(He said \"farewell\".\nHe's probably trying to act cool\nsince he's from \"Habataki Academy\"!)");
        break ;
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(9, 86, 1);
    }
