section "d01_m3_000"{
    Character_BlinkStart(3, 1, (#1), 1);
    Character_BlinkStart(3, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC302_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Today is election day for the\nStudent Council Executives.\nThe speeches will be starting\nsoon...");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SC603_LI_0", #1, #1, 0);
    Environment_PlayME(1, "SN_BGE_027_014", 127, 0);
    Voice_PlayVoice("D0103000_W00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Moderator", "Please be quiet.\nNext is a first year, Hikami\nItaru-kun.\nPlease go ahead.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, it's ｛Hikami＊＊｝.)");
    Still_Event("EV_03_05", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_03_005_D00", 127, 40);
    Still_StillFace(0, 3, 0);
    Voice_PlayVoice("D0103000_C00100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Don't chatter.\nDo you all even have a\nself-awareness that you are high\nschool students!?");
    Environment_StopME(1, 40);
    Voice_PlayVoice("D0103000_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Now is the time to choose new\nStudent Council Executives who will\ngreatly impact upon your school\nlife.");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0103000_C00300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Aren't there a lot of students who\ndon't understand this fact, and\nthink that it doesn't matter who is\nchosen?");
    Voice_PlayVoice("D0103000_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "This tendency isn't just limited to\nnow.");
    Still_StillFace(0, 6, 3);
    Still_Event("EV_03_06", #1, 0, 60);
    Still_Approach(3, 64, 0, 0, 1, 1);
    Voice_PlayVoice("D0103000_C00500", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "In other words, there are a lot of\nstudents in Hanegasaki Academy who\naren't upholding the tradition of\nour school!");
    Still_ApproachEnd();
    SoundEffect_PlayStream(1, "SS_DSE_096_000", 127, 0);
    Voice_PlayVoice("D0103000_C00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I have a suggestion.\nShouldn't the basic rules of the\nschool be known to all!?");
    SoundEffect_PlayStream(2, "SS_T_00_151_S00");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Wow...\nEveryone is getting angry...)");
    Music_StopBGM(0, 40);
    Environment_StopME(1, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    System_Wait(60);
    Background_Bg_GS2("BG_SC603_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0103000_W00700", #1, "");
    Message_Who(0);
    Message_MsgDisp("Moderator", "As a result of the votes, the next\nStudent Council President is Satou\nIchirou.");
    Voice_PlayVoice("D0103000_W00800", #1, "");
    Message_Who(0);
    Message_MsgDisp("Moderator", "Now then, we will hear Satou\nIchirou's aspirations as the next\nStudent Council President...");
    Message_CloseMsg();
    Screen_WipeOut(2);
    System_Wait(60);
    Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hikami＊＊｝.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Character_BlinkStart(3, 3, (#1), 1);
    Character_Chara_GS2(3, "M3_01F", 0);
    Voice_PlayVoice("D0103000_C00900", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "It was unfortunate.");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(3, 0, (#1), 2);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("D0103000_C01000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Yeah.... Very unfortunate.");
    Voice_PlayVoice("D0103000_C01100", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Even though I said the right things,\nthey didn't understand...\nIt's always like this.\nHave I been mistaken?");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hikami＊＊｝...");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(3, 3, (#1), 2);
    Voice_PlayVoice("D0103000_C01200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "People see me as an unpleasant\nguy...\nBut I cannot lie to myself...\nI have to accept the results.");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("D0103000_C01300", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... Sorry.\nI was just thinking to myself a\nlittle.\nExcuse me.");
    Character_Chara_GS2(3, "NON");
    Music_StopBGM(0, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hikami＊＊｝...\nIt would have been nice if I had\ncheered him up...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(3, 86, 1);
    Parameter_AddCh1Param(3, 61, 6);
    Parameter_AddCh1Param(3, 60, 3);
    Parameter_AddCh1Param(3, 62, #5);
    }
