section "d01_mb_005"{
    Background_Bg_GS2("BG_SC602_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    SoundEffect_PlayStream(2, "SS_T_00_183_S00");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Tarou-kun will graduate today...\nIt will be sad not being able to see\nhim at school.)");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I should look for Tarou-kun and ask\nfor his contact details!)");
    SoundEffect_StopStream(2, 45);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SC410_SP_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(He's not in his classroom either...\nMaybe he already went home... Ah!)");
    Character_Chara_GS2(26, "MB_01F", 0);
    Character_ChFace(0, 0, 10);
    Music_PlayBGM(0, "MN_C_92_000_D00", 127, 40);
    Voice_PlayVoice("NS_F2_920_00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Girl A", "Senpai, even if you're going to\nattend university, please hang out\nwith us!");
    Voice_PlayVoice("NS_F1_921_00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Girl B", "You must, okay?");
    Voice_PlayVoice("NS_92_000_06100", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Ah. Well, okay.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm...");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("NS_92_000_06200", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Hmm? Ah, it's you.");
    Voice_PlayVoice("NS_F1_921_00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Girl B", "Hey, is that girl the one you\nwere...");
    Voice_PlayVoice("NS_F2_920_00100", #1, "");
    Message_Who(0);
    Message_MsgDisp("Girl A", "Idiot, be quiet! She can hear you!");
    Message_Who(0);
    Message_MsgDisp("主人公", "(... Are they talking about me?)");
    Voice_PlayVoice("NS_F2_920_00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Girl A", "N-Now then, please excuse us!");
    SoundEffect_PlayStream(2, "SS_T_00_099_M00");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("NS_92_000_06300", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Okay.... And what do you want?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Tarou-kun, congratulations on\ngraduating.");
    Voice_PlayVoice("NS_92_000_06400", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Ah, thanks for that.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, since we can't see each other\nat school anymore, I thought I'd ask\nfor your contact--");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("NS_92_000_06500", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Sorry.\nI have a principle to not own a\ncellphone.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Then, I'll give you mine--");
    Character_BlinkStart(26, 3, (#1));
    Voice_PlayVoice("NS_92_000_06600", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Hey...\nI know you want to be sentimental,\nbut I can't go that far.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Eh?");
    Character_BlinkStart(26, 1, (#1));
    Character_BlinkStart(26, 0, (#1));
    Voice_PlayVoice("NS_92_000_06700", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "I just wanted to make a high school\nmemory of going out with a kind of\ncute junior.");
    Voice_PlayVoice("NS_92_000_06800", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "But that in itself should have been\nenough.");
    Character_BlinkStart(26, 2, (#1));
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("NS_92_000_06900", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Exchanging contact details is\nannoying.\nThat's why we should find someone\nelse.\nThe both of us.");
    Message_Who(0);
    Message_MsgDisp("主人公", "That's...");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("NS_92_000_07000", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Stop it. It's just a game, right?\nSomeone as pretty as you should know\nthat.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I didn't have those intentions...");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("NS_92_000_07100", #1, "");
    Message_Who(26);
    Message_MsgDisp("Majima", "Then did you really fall in love\nwith me?");
    Message_MsgSel("This isn't like you.", "Enough already...");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "I did.\nI think that what you're feeling\nright now aren't your real feelings.");
        Character_ChFace(0, 0, 8);
        Character_BlinkStart(26, 2, (#1));
        Voice_PlayVoice("NS_92_000_07200", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Eh... Right.\nThat's an interesting opinion.");
        Character_ChFace(0, 0, 0);
        Character_BlinkStart(26, 0, (#1));
        Voice_PlayVoice("NS_92_000_07300", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Do you know Cafe Alucard?\nI go there sometimes.\nIf you worked there, we could\nprobably see each other.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Cafe Alucard...");
        Voice_PlayVoice("NS_92_000_07400", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I'm going now.");
        Character_Chara_GS2(26, "NON");
        Music_StopBGM(0, 40);
        System_GlobalWork(19, 0, 5);
        break ;
        case 1:
        Message_Who(0);
        Message_MsgDisp("主人公", "Enough already.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("NS_92_000_07500", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Right. I'm going now.\nSorry for making you misunderstand.");
        Character_Chara_GS2(26, "NON");
        Music_StopBGM(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Tarou-kun is that kind of person...\nI should forget him.)");
        System_GlobalWork(19, 0, 30);
        break ;
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
