section "d01_ma_002"{
    Background_Bg_GS2("BG_SC301_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Character_ChFace(0, 0, 10);
    Character_Chara_GS2(7, "M7_01F", 0);
    Environment_StopME(1, 40);
    Voice_PlayVoice("NS_07_000_01300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Ok, this concludes homeroom!");
    SoundEffect_PlayStream(1, "SE_NS_AL_910_006000", 127, 0);
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("NS_07_000_01400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Ah! Wait a moment please!\nWill someone bring this print out\nsheet to Komori-kun, who has been\naway?");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Speaking of which, Komori-kun has\nbeen away this whole time...)");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("NS_07_000_01500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Sensei can't bring them to him\nanymore.\nI'm beat...");
    Message_MsgSel("Should I bring it to him?", "I'm busy, myself...");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, should I\nbring them to him?");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("NS_07_000_01600", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Yes! That would help.\nSo would you please?\nKomori-kun's house is...");
        System_GlobalWork(18, 0, 2);
        Message_CloseMsg();
        SoundEffect_StopStream(1, 40);
        Screen_WipeOut(2);
        Screen_ClearScreen();
        break ;
        case 1:
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(25, 3, (#1));
        Voice_PlayVoice("NS_07_000_01700", #1, "");
        Message_Who(7);
        Message_MsgDisp("Wakaouji", "Hm～... It can't be helped.\nI guess Sensei has to go then.");
        Character_Chara_GS2(7, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Was it better for me to have\nhelped?\nBut I'm busy myself...)");
        break ;
        }
    if (System_GlobalWork(18, 1) == 2){
        Background_Bg_GS2("BG_EX100_?_0", 1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Umm, Hanegasaki Apartments,\nbuilding F.\nIt's quite close to my place.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It should be around here-- Ah,\nthere it is!)");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Background_Bg_GS2("BG_EX190_CO_0", #1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Room 302...\nIt doesn't have a name plate, is\nthis is?\nI'll press the buzzer--)");
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...... Is no one home?)");
        SoundEffect_PlayStream(3, "SS_T_00_038_M00");
        System_Wait(30);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Voice_PlayVoice("NS_91_000_00800", #1, "");
        Message_Who(25);
        Message_MsgDisp("Komori", "\"Yes\".");
        Message_Who(0);
        Message_MsgDisp("主人公", "U-Umm!\nI'm ｛主人公姓名｝ from\nTaku-kun's class...");
        Voice_PlayVoice("NS_91_000_00900", #1, "");
        Message_Who(25);
        Message_MsgDisp("Komori", "\"Umm, why are you...\"");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, is that Komori-kun?\nI brought you some print outs.");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        SoundEffect_PlayStream(3, "SEQ_SE_EV_144");
        Character_ChFace(0, 0, 0);
        Character_Chara_GS2(25, "MA_??F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "Komori-kun! ...\nYour complexion doesn't look too\ngood.\nAre you still unwell?");
        Voice_PlayVoice("NS_91_000_01000", #1, "");
        Message_Who(25);
        Message_MsgDisp("Komori", "Um, the print outs...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, yes, here!");
        Voice_PlayVoice("NS_91_000_01100", #1, "");
        Message_Who(25);
        Message_MsgDisp("Komori", ".........");
        Message_Who(0);
        Message_MsgDisp("主人公", "?");
        Voice_PlayVoice("NS_91_000_01200", #1, "");
        Message_Who(25);
        Message_MsgDisp("Komori", "... Later.");
        Character_Chara_GS2(25, "NON");
        SoundEffect_PlayStream(3, "SEQ_SE_EV_145");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay... later.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Is Komori-kun okay...?)");
        }
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    }
