section "d01_g3_001"{
    Character_BlinkStart(12, 1, (#1), 1);
    Character_BlinkStart(12, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC410_SA_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, it's ｛Nishimoto＊＊｝...)");
    Voice_PlayVoice("D0112001_L00000", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "*Sobs*.........");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh... Is she crying?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Nishimoto＊＊｝.");
    Environment_StopME(0, 40);
    Still_Event("EV_12_01", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_12_002_D00", 127, 40);
    Voice_PlayVoice("D0112001_L00100", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ah... ｛主人公｝...!");
    Message_Who(0);
    Message_MsgDisp("主人公", "W-What's wrong?");
    Voice_PlayVoice("D0112001_L00200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Nothing...\nThis novel is so emotionally moving.\n*Sobs*...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah...\nIsn't that the love novel that was\npopular a little while ago?");
    Voice_PlayVoice("D0112001_L00300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Yeah.\nThese kinda things really hit my\nweak spots...");
    Voice_PlayVoice("D0112001_L00400", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I understand the feelings of the\nheroine so much that it hurts...\nAh, this is so sad...");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's that touching?");
    Background_Bg_GS2("BG_SC410_SA_0", #1, #1, 0);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Character_BlinkStart(12, 3, (#1), 1);
    Character_ChFace(0, 4, 1);
    Character_Chara_GS2(12, "G3_01F", 0);
    Voice_PlayVoice("D0112001_L00500", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "...\nAt the end, the heroine whispers to\nhim that she will let him go and\nchase his dreams...");
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("D0112001_L00600", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "\"You'll definitely be able to become\na top musician.\nI believe in you.\nI'll watch over you\".");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("D0112001_L00700", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Then...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah?");
    Character_BlinkStart(12, 3, (#1), 1);
    Voice_PlayVoice("D0112001_L00800", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "There's still more～.\nWithout looking at her, he looks to\nthe sky...");
    Character_BlinkStart(12, 0, (#1), 1);
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("D0112001_L00900", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "And yells \"I need you in my dreams!\nSo don't watch and come with me!\"");
    Character_BlinkStart(12, 3, (#1), 1);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0112001_L01000", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "*Sobs* I really want that to happen!\nI want him to to say that...");
    Message_Who(0);
    Message_MsgDisp("主人公", "To you, ｛Nishimoto＊＊｝?");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(12, 0, (#1), 1);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("D0112001_L01100", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ye-... No, no, no, you're wrong!");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(12, 3, (#1), 1);
    Voice_PlayVoice("D0112001_L01200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ahaha, don't go around mishearing\nthings, okay?\nDon't they say to be patient?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I wasn't being impatient, though...");
    Character_BlinkStart(12, 2, (#1), 1);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("D0112001_L01300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Don't look into the finer details!");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay. Hey, earlier...");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(12, 0, (#1), 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0112001_L01400", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Ah! It's already time!\nI wanted to chat with you a little\nmore, too～...");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0112001_L01500", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "S-See you!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(12, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "She left...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(But she looked like she had fun\ntalking about it.\nShe's actually a romantic.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(12, 86, 1);
    Parameter_AddCh1Param(12, 60, 5);
    }
