section "d01_s3_000"{
    Character_BlinkStart(16, 1, (#1), 1);
    Character_BlinkStart(16, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC002_WI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(I came all the way here...\n｛Saeki＊＊｝ isn't here\nanymore, though.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_BH110_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(The store looks like it's closed.\nAs expected, he hasn't come back...)");
    Character_Chara_GS2(16, "S3_17F", 0);
    Music_PlayBGM(0, "MN_C_16_000_D00", 127, 40);
    Voice_PlayVoice("D0116000_P00000", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "Oh? A customer?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Master!");
    Voice_PlayVoice("D0116000_P00100", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "Ah, it's been a while.\nHave you been doing well?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes. Umm, I...");
    Voice_PlayVoice("D0116000_P00200", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "... Teru isn't here anymore.\nYou know that, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.\nBut if he did come back and didn't\nreceive any chocolate, he'd surely\nsulk about it.");
    Voice_PlayVoice("D0116000_P00300", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "Oh yes, today is Valentine's Day....\nThank you for liking a guy like\nTeru.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I...");
    Voice_PlayVoice("D0116000_P00400", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "We're still clearing things out, so\nit's messy.\nBut if it's alright with you, please\ncome in.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_AR101_CO_2", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "...\nUmm, will you please tell me the\nreal reason why you closed the\nstore?");
    Voice_PlayVoice("D0116000_P00500", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "Alright...\nDid you know that ever since Teru\nwas a child that he was really\nstubborn and vain...?");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Voice_PlayVoice("D0116000_P00600", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "No matter how painful things were,\nhe would always act as if nothing\nwas wrong in front of others...");
    Voice_PlayVoice("D0116000_P00700", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "But when people weren't around, he\nwould often cry by himself at the\nbeach at night.");
    Voice_PlayVoice("D0116000_P00800", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "I couldn't stand seeing him worn out\nlike that from school and the store\nanymore.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Master...\nSo you were looking out for\n｛Saeki＊＊｝, after all...");
    Voice_PlayVoice("D0116000_P00900", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "No matter how strong he is, and no\nmatter how often he expresses his\nenthusiasm,");
    Voice_PlayVoice("D0116000_P01000", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "to me, he will always be that\nlittle, stubborn kid who resists\nshedding tears.");
    Message_Who(0);
    Message_MsgDisp("主人公", "If ｛Saeki＊＊｝ heard this\nhe'd surely get mad, right?");
    Voice_PlayVoice("D0116000_P01100", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "Haha, right! ...\nBut it seems like I have\nmisunderstood.");
    Voice_PlayVoice("D0116000_P01200", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "I thought he would have given up if\nI closed the store, but that's not\nit.\nHe left me and went off.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(...?\n｛Saeki＊＊｝ gave up on the\nstore...?)");
    Voice_PlayVoice("D0116000_P01300", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "All young people mature.\nAlthough it feels like they're\ndeserting the people around them, it\ncan't be helped.");
    Message_Who(0);
    Message_MsgDisp("主人公", "But it's sad...");
    Voice_PlayVoice("D0116000_P01400", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "You will mature.\nYou're already a wonderful young\nwoman.\nYou shouldn't cry.");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Voice_PlayVoice("D0116000_P01500", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "Hahaha...");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Voice_PlayVoice("D0116000_P01600", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "Teru will surely come back.\nHe won't be able to leave such a\nwonderful young lady behind.");
    Message_Who(0);
    Message_MsgDisp("主人公", "That's...");
    Voice_PlayVoice("D0116000_P01700", #1, "");
    Message_Who(16);
    Message_MsgDisp("Master", "If he comes back, I'll call you\nright away.\nJust give it some time and please\nbelieve me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
