section "d01_g1_001"{
    Character_BlinkStart(10, 1, (#1), 1);
    Character_BlinkStart(10, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC410_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0110001_W00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Male Student", "Thank you very much.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh, is that ｛Toudou＊＊｝\nover there?)");
    Voice_PlayVoice("D0110001_J00100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "You're a guy, aren't you?\nThen you should just go for it.");
    Voice_PlayVoice("D0110001_W00200", #1, "");
    Message_Who(0);
    Message_MsgDisp("Male Student", "Yes, Toudou-san!!\nThank you in advance, again!");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Toudou＊＊｝!");
    Character_Chara_GS2(10, "G1_01F", 0);
    Music_PlayBGM(0, "MN_C_10_000_D00", 127, 40);
    Voice_PlayVoice("D0110001_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Ah, ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What's up? Did something happen?");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(10, 2, (#1), 1);
    Voice_PlayVoice("D0110001_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Something? ...\nOh, you mean earlier...");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(10, 0, (#1), 1);
    Voice_PlayVoice("D0110001_J00500", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I don't know why, but I often\nconsult people.\nMen and women of all ages.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh, is that so?\nWhat do you consult them on?");
    Character_BlinkStart(10, 3, (#1), 1);
    Voice_PlayVoice("D0110001_J00600", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Mostly about love...\nThe guy just now wanted me to give\nhim the guts to do it.");
    Character_ChFace(0, 2, 2);
    Voice_PlayVoice("D0110001_J00700", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "And wanted to know what I thought...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ahaha...\nYou're being depended upon,\n｛Toudou＊＊｝.");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(10, 0, (#1), 1);
    Voice_PlayVoice("D0110001_J00800", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Depended, huh...\nWell it has nothing to do with me.\nWhatever is fine.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Even if you say that, you can't just\nignore them, right?");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(10, 2, (#1), 1);
    Voice_PlayVoice("D0110001_J00900", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "... Maybe. I just say what I want.\nThe rest is up to them.");
    Character_BlinkStart(10, 3, (#1), 1);
    Voice_PlayVoice("D0110001_J01000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Let's not talk about such trivial\nthings, we should head back to\nclass.");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(10, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Does ｛Toudou＊＊｝ perhaps\nget shy easily...?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(10, 86, 1);
    }
