section "d01_g2_000"{
    Character_BlinkStart(11, 1, (#1), 1);
    Character_BlinkStart(11, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC210_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Now, I've sorted out the cardboard,\nnext is...)");
    Character_Chara_GS2(11, "G2_01F", 0);
    Music_PlayBGM(0, "MN_C_11_000_D02", 127, 40);
    Voice_PlayVoice("", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Onoda＊＊｝.\nYou're still here.");
    Voice_PlayVoice("D0111000_K00000", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "I'm an executive of the Student\nCouncil, so I have much to do, like\norganizing the Culture Festival.");
    Character_ChFace(0, 0, 11);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0111000_K00100", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Ah, that's right, I was looking for\nyou.\nCan you drink red tea?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Red tea... you mean Japanese tea?\nI can drink it...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0111000_K00200", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "That's great.\nWould you please come with me?\nI want to practice.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Practice?");
    Voice_PlayVoice("D0111000_K00300", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "We will use a classroom as a rest\nstop during the Culture Festival.\nWe'll be serving tea and sweets.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0111000_K00400", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "The tea we have does not have any\nprecise instructions written on the\npack.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Can't you just add hot water to it?");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0111000_K00500", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "No!\nThe amount of tea leaves and water\ntemperature should vary for each\ntype of tea.");
    Voice_PlayVoice("D0111000_K00600", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "We have prepared three types of tea.\nNow we will research how to make it.");
    Character_ChFace(0, 2, 3);
    Voice_PlayVoice("D0111000_K00700", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "So I will vary the amount of tea\nleaves and water temperature.\nPlease compare them.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay, I understand.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0111000_K00800", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "So there are 5 patterns of water\ntemperature and 3 patterns of the\namount of leaves...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(How many cups of tea will I have to\ndrink...?)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(11, 86, 1);
    Parameter_AddCh1Param(11, 60, 5);
    }
