section "d01_m6_003"{
    Character_BlinkStart(6, 1, (#1), 1);
    Character_BlinkStart(6, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC212_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0106003_F00000", #1, "");
    Message_Who(6);
    Message_MsgDisp("？？？", "Ah, damn! Why is it like this?");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Hmm? That voice just now...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_SCA52_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Amachi＊＊｝?");
    Still_Event("EV_06_09", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_06_002_D00", 127, 40);
    Voice_PlayVoice("D0106003_F00100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Wah! Senpai? W-Why are you here!?");
    Message_Who(0);
    Message_MsgDisp("主人公", ".... What, is that?");
    Still_Approach(6, 158, 0, 0, 1, 1);
    Voice_PlayVoice("D0106003_F00200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "What... is... it...? Ah, don't look!\nEven if you are my senior, this\nis...!");
    Still_ApproachEnd();
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Character_BlinkStart(6, 3, (#1), 1);
    Character_Chara_GS2(6, "M6_01F", 0);
    Background_Bg_GS2("BG_SCA52_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "You don't have to panic and hide it.");
    Voice_PlayVoice("D0106003_F00300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "It was because Senpai was being\nchildish and tried to look at it!");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm sorry.\nWhy are you drawing by yourself?");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(6, 0, (#1), 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("D0106003_F00400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Detention.\nBecause I didn't draw anything when\nI was in art class.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("D0106003_F00500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Hey, Senpai!\nDon't tell anyone about this, okay?\nPlease!!");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay.... But why?");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("D0106003_F00600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "It's...\nI don't know how, but I've gotten\nthe reputation of being an\nall-rounded person.");
    Voice_PlayVoice("D0106003_F00700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "If it's studying or sports, I can\nsomehow manage it, but arts is a\nlittle...");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(6, 3, (#1), 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0106003_F00800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "That's why...\nI do art-related things where no one\nwill see me.");
    Voice_PlayVoice("D0106003_F00900", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "...\nThe burden of everyone's\nexpectations is tough to deal with.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see...\nDo your best, ｛Amachi＊＊｝.");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(6, 2, (#1), 1);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("D0106003_F01000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Yeah, thank you.");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(6, 0, (#1), 1);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("D0106003_F01100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... But I've got no luck.\nSenpai saw.");
    Voice_PlayVoice("D0106003_F01200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I'm so uncool...");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Amachi＊＊｝ actually has\nlots of hardships, too...)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(6, 86, 1);
    Parameter_AddCh1Param(6, 61, 6);
    Parameter_AddCh1Param(6, 60, 3);
    Parameter_AddCh1Param(6, 62, #5);
    }
