section "d01_m4_000"{
    Character_BlinkStart(4, 1, (#1), 1);
    Character_BlinkStart(4, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC230_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    SoundEffect_PlayStream(1, "SS_DSE_060_000", 127, 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "Is ｛Hariya＊＊｝'s\nperformance already over...?\nI have to hurry!");
    SoundEffect_PlayStream(3, "SS_T_00_070_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah! What was that sound just now...");
    Message_Who(0);
    Message_MsgDisp("主人公", "I heard it coming from here... Ah.");
    Environment_StopME(0, 40);
    SoundEffect_StopStream(3, 40);
    SoundEffect_PlayStream(2, "SS_T_00_071_M00");
    Still_Event("EV_04_06", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_04_004_D00", 127, 40);
    Voice_PlayVoice("D0104000_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...... Dammit! Why do I always...!!");
    Still_StillFace(0, 6, 1);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0104000_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... How shameful...");
    Message_Who(0);
    Message_MsgDisp("主人公", "... ｛Hariya＊＊｝?");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("", 4, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Is the performance already over?");
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("D0104000_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nYeah, it finished a long time ago.\nSo go somewhere else.");
    Message_Who(0);
    Message_MsgDisp("主人公", "But...");
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("D0104000_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Just go somewhere else!");
    Message_Who(0);
    Message_MsgDisp("主人公", "... I'm sorry.\nI missed seeing your live...");
    Still_StillFace(0, 0, 2);
    Voice_PlayVoice("D0104000_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nI think that it's better that you\ndidn't see it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0104000_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "My performance wasn't worthy of you\nlooking forward to it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "That's not true...!");
    Still_Approach(4, 95, 0, 0, 1, 1);
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("D0104000_D00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Just be quiet!");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0104000_D00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Sorry...\nI'm really bad after lives...");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0104000_D00900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It's always like this...\nI haven't progressed at all......");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("D0104000_D01000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nBut because of you, I cooled my head\noff a little.");
    Voice_PlayVoice("D0104000_D01100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I want some time alone to think, so\ndo you mind leaving?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay... I get it.");
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("D0104000_D01200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I'm sorry..\nfor my outburst of anger.");
    Still_Approach(4, 95, 0, 0, 1, 5);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hariya＊＊｝...)");
    Still_ApproachEnd();
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    Parameter_AddCh1Param(4, 61, 6);
    Parameter_AddCh1Param(4, 60, 3);
    Parameter_AddCh1Param(4, 62, #5);
    }
