section "d01_mb_007"{
    int var0;
    var0 = Parameter_GetPl1Param(12);
    switch (var0){
        case 0:
        Background_Bg_GS2("BG_HO200_?_0", 1, #1, 0);
        break ;
        case 1:
        Background_Bg_GS2("BG_HO210_?_0", 1, #1, 0);
        break ;
        case 2:
        Background_Bg_GS2("BG_HO220_?_0", 1, #1, 0);
        break ;
        case 3:
        Background_Bg_GS2("BG_HO230_?_0", 1, #1, 0);
        break ;
        }
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(I have a date with Tarou-kun today.\nWhat should I wear...?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Run_Kigae(0);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Background_Bg_GS2("BG_FP000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetPl1Param(33) == 2){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Tarou-kun...\ndoesn't look like he's here, yet.)");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Oh no, there's a shady guy staring\nat me...\nAh, he's coming over here!)");
        Character_Chara_GS2(20, "N1_17F", 0);
        Voice_PlayVoice("NS_M1_920_00000", #1, "");
        Message_Who(20);
        Message_Who(20);
        Message_MsgDisp("Playboy", "Hey, Miss! Aren't you sexy～!\nI'm sexy, as well.\nShould we go somewhere?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, I'm waiting for someone, so--");
        Voice_PlayVoice("NS_M1_920_00100", #1, "");
        Message_Who(20);
        Message_Who(20);
        Message_MsgDisp("Playboy", "Ah, he won't come!");
        Message_Who(0);
        Message_MsgDisp("主人公", "He will!");
        Voice_PlayVoice("NS_M1_920_00200", #1, "");
        Message_Who(20);
        Message_Who(20);
        Message_MsgDisp("Playboy", "He won't～!\nHehehe, come on, let's go.");
        Message_Who(0);
        Message_MsgDisp("主人公", "No! Please stop this!");
        Character_Chara_GS2(20, "NON");
        Character_Chara_GS2(20, "N1_17F", 0, 0, 1);
        Character_ChFace(0, 0, 8);
        Character_Chara_GS2(26, "MB_02F", 0);
        Music_PlayBGM(0, "MN_C_92_000_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Tarou-kun!");
        Voice_PlayVoice("NS_92_000_10800", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Hey you. That's enough.\nGet out of my sight.");
        Voice_PlayVoice("NS_M1_920_00300", #1, "");
        Message_Who(20);
        Message_Who(20);
        Message_MsgDisp("Playboy", "Huh!? No, but...");
        Voice_PlayVoice("NS_92_000_10900", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Let's go.");
        Character_Chara_GS2(26, "NON");
        Music_StopBGM(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "O-Okay.");
        Voice_PlayVoice("NS_M1_920_00400", #1, "");
        Message_Who(20);
        Message_Who(20);
        Message_MsgDisp("Playboy", "No way! Wait!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(20, "NON");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Background_Bg_GS2("BG_FP220_?_0", #1, #1, 0);
        Character_Chara_GS2(26, "MB_02F", 0);
        Character_ChFace(0, 0, 8);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Tarou-kun, thank you for rescuing me\nearlier.");
        Voice_PlayVoice("NS_92_000_11000", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Yeah.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm... How are my clothes?\nDo I look a little more mature?");
        Character_BlinkStart(26, 2, (#1));
        Voice_PlayVoice("NS_92_000_11100", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Yeah.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Thank gosh.\nI was a little worried, so--");
        Character_BlinkStart(26, 3, (#1));
        Voice_PlayVoice("NS_92_000_11200", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "It really suits you.\nIt seems like you're wearing too\nlittle.");
        Message_Who(0);
        Message_MsgDisp("主人公", "That's...\nBut Tarou-kun--");
        Character_BlinkStart(26, 1, (#1));
        Character_BlinkStart(26, 0, (#1));
        Voice_PlayVoice("NS_92_000_11300", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Won't you be quiet?");
        Message_Who(0);
        Message_MsgDisp("主人公", "......");
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(26, 3, (#1));
        Voice_PlayVoice("NS_92_000_11400", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "My bad... I've changed my mind.\nI'm leaving.");
        Character_BlinkStart(26, 1, (#1));
        Character_BlinkStart(26, 0, (#1));
        Voice_PlayVoice("NS_92_000_11500", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "You should go home as well.\nYou'll get cornered by more weird\nguys, looking like that.\nLater.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Tarou-kun...)");
        System_GlobalWork(19, 0, 12);
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "(Even though I wore these clothes,\nTarou-kun...\nIt doesn't look like he'll come,\nagain.)");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Oh no, there's a shady guy staring\nat me...\nAh, he's coming over here!)");
        Character_Chara_GS2(26, "MB_02F", 0);
        Character_BlinkStart(26, 2, (#1));
        Character_ChFace(0, 0, 11);
        Music_PlayBGM(0, "MN_C_92_000_D00", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Tarou-kun! Thank gosh...\nThat guy over there--");
        Character_BlinkStart(26, 2, (#1));
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("NS_92_000_11600", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Come here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "O-Okay.");
        Voice_PlayVoice("NS_92_000_11700", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Hurry!");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Music_StopBGM(0, 40);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Background_Bg_GS2("BG_FP220_?_0", #1, #1, 0);
        Character_ChFace(0, 0, 8);
        Character_BlinkStart(26, 2, (#1));
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "Tarou-kun, are you mad?");
        Voice_PlayVoice("NS_92_000_11800", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Are my eyes deceiving me?\nOr are you just a blockhead?");
        Message_Who(0);
        Message_MsgDisp("主人公", "If you're talking about these\nclothes--");
        Character_BlinkStart(26, 1, (#1));
        Character_BlinkStart(26, 0, (#1));
        Voice_PlayVoice("NS_92_000_11900", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Didn't I say to come wearing sexy\nclothes?");
        Message_Who(0);
        Message_MsgDisp("主人公", "But I don't wear such...");
        Character_ChFace(0, 0, 0);
        Character_BlinkStart(26, 2, (#1));
        Voice_PlayVoice("NS_92_000_12000", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Ah, right. Then this date is over.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You're not serious, are you?");
        Character_BlinkStart(26, 0, (#1));
        Voice_PlayVoice("NS_92_000_12100", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I am being serious.\nIf you're not going to listen to\nwhat I say, then why did you even\ncome?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Because I was happy that you invited\nme out on a proper date...");
        Character_ChFace(0, 0, 9);
        Voice_PlayVoice("NS_92_000_12200", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "What... do you mean.");
        Message_Who(0);
        Message_MsgDisp("主人公", "It seems like the current Tarou-kun\nis forcing himself...");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("NS_92_000_12300", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Stop it! ...\nMy bad, I'm going home now. Later.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Tarou-kun...)");
        System_GlobalWork(19, 0, 13);
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
