section "d01_m8_000"{
    Character_BlinkStart(8, 1, (#1), 1);
    Character_BlinkStart(8, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Character_Chara_GS2(8, "M8_01F", 0);
    Background_Bg_GS2("BG_AR500_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("", 8, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Masaki＊＊｝.\nYou've worked hard.");
    Voice_PlayVoice("D0108000_H00000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "You too.\nYou've gotten quite used to working,\nhaven't you?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I'm still uncertain about things,\nbut I've kind of gotten used to\nworking here...");
    Character_BlinkStart(8, 3, (#1), 1);
    Voice_PlayVoice("D0108000_H00100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "You memorize things quickly, too.\nYou're so different from me.");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(8, 0, (#1), 1);
    Voice_PlayVoice("D0108000_H00200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "So that means I'd like for you to\ntend to these roses～.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, understood!");
    Voice_PlayVoice("D0108000_H00300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Thank you!");
    Character_Chara_GS2(8, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Now then...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Ouch!");
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 2);
    Character_Chara_GS2(8, "M8_01F", 0);
    Voice_PlayVoice("D0108000_H00400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Ah, I forgot to tell you............\nIt's too late...");
    Character_ChFace(0, 2, 2);
    Voice_PlayVoice("D0108000_H00500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I was just about to tell you to be\nwary of thorns...\nThis isn't the time to tell you.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 2, 2);
    Voice_PlayVoice("D0108000_H00600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Come here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(8, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Still_Event("EV_08_07", #1, 0, 60);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_08_002_D00", 127, 40);
    Voice_PlayVoice("D0108000_H00700", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Show me your injury.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, it's fine, I can do it\nmyself...");
    Voice_PlayVoice("D0108000_H00800", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Just show me your injury!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yes!");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0108000_H00900", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "...\nI also did the same thing when I\nfirst started working here.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0108000_H01000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "When I had said that it wasn't a big\ndeal, the manager and Arisawa got\nangry at me...");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0108000_H01100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "In the end, germs had infected my\ninjury and it became a huge pain.\nI wish I could redo that event.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Uh... Is that so...");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0108000_H01200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah.\nI wouldn't be able to handle it if\nyour injury turned into something\nlike that.");
    Still_Approach(8, 216, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Masaki＊＊｝...");
    Still_ApproachEnd();
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Character_Chara_GS2(8, "M8_01F", 0);
    Background_Bg_GS2("BG_AR500_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0108000_H01300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Alright, it should be fine.\nAfter you bathe, sterilize it...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, it's alright.\nYou're a worrier,\n｛Masaki＊＊｝.");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 4, 1);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0108000_H01400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... Shoosh. Does your finger hurt?");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's fine. Umm...\nThank you very much,\n｛Masaki＊＊｝.");
    Character_ChFace(0, 0, 0);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("D0108000_H01500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "You're welcome.\nNow, should I give you a hand with\ntending to the roses?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(8, 86, 1);
    Parameter_AddCh1Param(8, 61, 6);
    Parameter_AddCh1Param(8, 60, 3);
    }
