section "d01_m8_003"{
    Character_BlinkStart(8, 1, (#1), 1);
    Character_BlinkStart(8, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC212_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Now then, it's about time I went\nhome.)");
    Voice_PlayVoice("D0108003_H00000", 8, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Huh, ｛主人公｝.");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(8, "M8_01F", 0);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Masaki＊＊｝!\nWhy are you here!?");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0108003_H00100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Working for Anneri.\nI'm delivering flowers to the\nPrincipal's office.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Is that so?");
    Voice_PlayVoice("D0108003_H00200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Are you going home now?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0108003_H00300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Wait for me then.\nI'll walk you home.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh, but...");
    Voice_PlayVoice("D0108003_H00400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "It's on the way back to work,\nanyway.\nStay here, I'll be back soon... Ah.\nIs that your classroom?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes, it is.");
    Voice_PlayVoice("D0108003_H00500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Really?\nIt's cold in the hallway, so wait\nfor me in the classroom.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Character_Chara_GS2(8, "NON");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    SoundEffect_PlayStream(2, "SS_T_00_165_M00");
    Character_ChFace(0, 0, 10);
    Character_Chara_GS2(8, "M8_01F", 0);
    Background_Bg_GS2("BG_SC302_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0108003_H00600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Thanks for waiting!");
    Message_Who(0);
    Message_MsgDisp("主人公", "You've worked hard.");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0108003_H00700", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah.... What a beautiful sunset.\nI came here at a good time.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, you're right.");
    Character_BlinkStart(8, 2, (#1), 1);
    Voice_PlayVoice("D0108003_H00800", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "How nostalgic. A classroom...\nAh, this is the desk that I used.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? Really?");
    Still_Event("EV_08_10", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_08_002_D00", 127, 40);
    Voice_PlayVoice("D0108003_H00900", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "This one.\nI used a chisel to make a small\nplace to put my eraser.");
    Still_Approach(8, 219, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ahaha, you really did.\nThere's a hole there.");
    Still_ApproachEnd();
    Voice_PlayVoice("D0108003_H01000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "...\nSeeing it now, there was no reason\nfor me to do it.\nBut it's good that I can have a\nlaugh about it now.");
    Still_StillFace(0, 2, 1);
    Voice_PlayVoice("D0108003_H01100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "...\nYou should create memories that will\nmake you feel warm when you think\nback upon them.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yes.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Background_Bg_GS2("BG_SC302_?_1", 1, #1, 0);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Character_BlinkStart(8, 3, (#1), 1);
    Character_Chara_GS2(8, "M8_01F", 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0108003_H01200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... Ah.\nIf I could return, I'd want to\nreturn.");
    Message_Who(0);
    Message_MsgDisp("主人公", "To your high school years?");
    Voice_PlayVoice("D0108003_H01300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah.\nI want to see what it would be like\nif I was your classmate.");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(8, 2, (#1), 1);
    Voice_PlayVoice("D0108003_H01400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I wonder what it would feel like.\nI can't imagine it, though.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Masaki＊＊｝...");
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 0);
    Character_BlinkStart(8, 3, (#1), 1);
    Voice_PlayVoice("D0108003_H01500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "...\nNothing can be done about it, even\nif we talk about the hypothetical\nworld.\nThings now aren't bad, though.");
    Character_BlinkStart(8, 0, (#1), 1);
    Voice_PlayVoice("D0108003_H01600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "If I was your classmate, it'd be\nrisky and impossible to drive you\nhome.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ahaha, that's right.");
    Character_BlinkStart(8, 2, (#1), 1);
    Voice_PlayVoice("D0108003_H01700", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "So should we go home before the sun\ngoes down?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes!");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(8, 86, 1);
    Parameter_AddCh1Param(8, 61, 6);
    Parameter_AddCh1Param(8, 60, 3);
    Parameter_AddCh1Param(8, 62, #5);
    }
