section "d01_m7_003"{
    Character_BlinkStart(7, 1, (#1), 1);
    Character_BlinkStart(7, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0;
    int var1;
    Background_Bg_GS2("BG_SC303_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(*Sigh*...\nI have no clue whatsoever.\nWhy do we have to memorize such\ndifficult things...?)");
    SoundEffect_PlayStream(2, "SS_T_00_093_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh, ｛Wakaouji＊＊｝.");
    Character_Chara_GS2(7, "M7_01F", 0);
    Music_PlayBGM(0, "MN_C_07_000_D00", 127, 40);
    Voice_PlayVoice("D0107003_G00000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "How is it? Are you making progress?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Well, umm...");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(7, 3, (#1), 1);
    Voice_PlayVoice("D0107003_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Dear, oh dear.");
    Character_Chara_GS2(7, "NON");
    Message_CloseMsg();
    Screen_WipeOut(2);
    SoundEffect_PlayStream(2, "SS_T_00_216_M00");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    SoundEffect_StopStream(2, 40);
    Environment_StopME(0, 40);
    Still_Event("EV_07_08", #1, 0, 60);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0107003_G00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "See, you can solve it.\nNow, the next one.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.");
    SoundEffect_PlayStream(2, "SS_T_00_216_M00");
    Still_StillFace(0, 7, 1);
    Voice_PlayVoice("D0107003_G00300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", ".........");
    Still_StillFace(0, 7, 0);
    Still_Approach(7, 187, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝ looks really\nhappy...)");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "(He must have really liked studying\nsince he was a child...)");
    Still_StillFace(0, 7, 0);
    Voice_PlayVoice("D0107003_G00400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "What is the matter?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, nothing! Umm...\nDid you like studying when you were\na student, ｛Wakaouji＊＊｝?");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0107003_G00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Do you hate studying?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm...\nI do say that I should study, but\nmaybe I'm not cut out for it...");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0107003_G00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I wonder.... Is that true?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm...");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0107003_G00700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I like learning.\nWhen I understand something, I am\ngenuinely happy.");
    Voice_PlayVoice("D0107003_G00800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It doesn't matter if it is useful or\nnot.");
    Voice_PlayVoice("D0107003_G00900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "By just studying, you can become a\nrich person.\nIt's the truth.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(A rich person, huh...)");
    SoundEffect_StopStream(2, 40);
    Still_StillFace(0, 2, 1);
    Voice_PlayVoice("", 7, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes!");
    Voice_PlayVoice("D0107003_G01000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Look into my eyes.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yes...");
    Still_Approach(7, 187, 1, 0, 1, 5);
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes...");
    SoundEffect_PlayStream(2, "SS_T_00_053_S00");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh?\nThey seem to be brimming with\npower!!)");
    Still_Event("");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    SoundEffect_StopStream(2, 40);
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(7, 3, (#1), 1);
    Character_Chara_GS2(7, "M7_01F", 0);
    Background_Bg_GS2("BG_SC303_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0107003_G01200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Yes. This is all for today.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝, thank you\nvery much.");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(7, 0, (#1), 1);
    Voice_PlayVoice("D0107003_G01300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "You are welcome. You can always...\nAh, no.\nTry hard so you don't have to attend\nsupplementary classes.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay!");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 86, 1);
    Parameter_AddCh1Param(7, 61, 6);
    Parameter_AddCh1Param(7, 60, 3);
    Parameter_AddPl1Param(16, 10);
    var0 = Parameter_GetPl1Param(22);
    var1 = (var0 / 2);
    Parameter_AddPl1Param(22, #var1);
    }
