section "d01_m2_005"{
    Character_BlinkStart(2, 1, (#1), 1);
    Character_BlinkStart(2, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0 = Parameter_GetPl1Param(12);
    switch (var0){
        case 0:
        Background_Bg_GS2("BG_HO200_CO_2", #1, #1, 0);
        break ;
        case 1:
        Background_Bg_GS2("BG_HO210_CO_2", #1, #1, 0);
        break ;
        case 2:
        Background_Bg_GS2("BG_HO220_CO_2", #1, #1, 0);
        break ;
        case 3:
        Background_Bg_GS2("BG_HO230_CO_2", #1, #1, 0);
        break ;
        }
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(The Baseball Club is finally at the\nnational championships...!\nI'm somewhat nervous.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(.......\nHmm, I probably won't be able to\nsleep today.)");
    SoundEffect_PlaySE(19, 127);
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah! That surprised me... Who is it?");
    SoundEffect_StopSE(19, 0);
    SoundEffect_PlaySE(20, 127);
    Message_Who(0);
    Message_MsgDisp("主人公", "Hello.");
    Voice_PlayVoice("D0102005_B00000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Sorry to call you at this time.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝!?");
    Voice_PlayVoice("D0102005_B00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Are you busy now?");
    Message_Who(0);
    Message_MsgDisp("主人公", "No. What's up? Did something happen?");
    Voice_PlayVoice("D0102005_B00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... No.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Where are you now,\n｛Shiba＊＊｝...");
    Voice_PlayVoice("D0102005_B00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Near your place.");
    Message_Who(0);
    Message_MsgDisp("主人公", "W...Wait a second, okay!");
    Voice_PlayVoice("D0102005_B00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Ah, hey...");
    SoundEffect_StopStream(0, 40);
    SoundEffect_PlaySE(20, 127);
    Message_CloseMsg();
    SoundEffect_PlayStream(2, "SEQ_SE_EV_003");
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_HO100_CO_2", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(He wouldn't really...\nbe near my place, right?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    SoundEffect_PlayStream(2, "SEQ_SE_EV_138");
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh... he's not here.\nMaybe I misheard?)");
    SoundEffect_PlayStream(3, "EV_SE_077");
    Message_Who(0);
    Message_MsgDisp("主人公", "!!!");
    SoundEffect_StopStream(3, 40);
    SoundEffect_StopStream(0, 40);
    Still_Event("EV_02_11", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_02_002_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝...");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0102005_B00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... You just hung up on me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah! S-Sorry, I just...");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0102005_B00600", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nAnd it was also careless of you to\ncome outside at this time of night.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ugh...");
    Voice_PlayVoice("D0102005_B00700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... I'm glad I could see your face.");
    Still_Approach(2, 40, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...?");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0102005_B00800", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Later.");
    Still_Approach(2, 40, 0, 0, 1, 5);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah... ｛Shiba＊＊｝!");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0102005_B00900", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Goodnight.");
    Music_StopBGM(0, 40);
    Background_Bg_GS2("BG_HO000_?_2", 1, #1, 0);
    Still_Event("");
    SoundEffect_PlayStream(3, "SS_T_00_020_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Perhaps...\n｛Shiba＊＊｝ is also\nnervous and can't sleep...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Goodnight, ｛Shiba＊＊｝.\nDo your best...!)");
    Message_CloseMsg();
    SoundEffect_StopStream(3, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 86, 1);
    Parameter_AddCh1Param(2, 61, 6);
    Parameter_AddCh1Param(2, 60, 3);
    Parameter_AddCh1Param(2, 62, #5);
    }
