section "d01_mb_001"{
    Background_Bg_GS2("BG_SC602_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    SoundEffect_PlayStream(2, "SS_T_00_183_S00");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Today, we will part with our 3rd\nyear seniors...\nThe speech from the student\nrepresentative was touching.)");
    SoundEffect_StopStream(2, 45);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(So, I should tidy up!\nI should return the gymnasium key to\nthe staff room...\nHuh?)");
    Still_Event("EV_92_01", #1, 0, 60);
    Still_StillFace(0, 6, 1);
    Still_Approach(26, 300, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(That person...\nHe is my 2nd year senior who gave\nthe speech.)");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "(He looks like a Greek sculpture.\nA beautiful person...\nBut he kind of looks like he's in\npain...)");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 3);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("NS_92_000_00000", #1, "");
    Message_Who(26);
    Message_MsgDisp("？？？", "Hmm?");
    Message_Who(0);
    Message_MsgDisp("主人公", "(!!)");
    Background_Bg_GS2("BG_SC930_LI_0", #1, #1, 0);
    Character_Chara_GS2(26, "MB_01F", 0);
    Music_PlayBGM(0, "MN_C_92_000_D00", 127, 40);
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(26, 0, (#1), 1);
    Character_ChFace(0, 3, 0);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("NS_92_000_00100", #1, "");
    Message_Who(26);
    Message_MsgDisp("？？？", "Hello.");
    Message_Who(0);
    Message_MsgDisp("主人公", "H-Hello! Umm, I...");
    Voice_PlayVoice("NS_92_000_00200", #1, "");
    Message_Who(26);
    Message_MsgDisp("？？？", "This place is closed, isn't it?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yes. I'm sorry.");
    if (Parameter_GetPl1Param(21) < 30){
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(26, 0, (#1), 1);
        Character_ChFace(0, 3, 3);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("NS_92_000_00300", #1, "");
        Message_Who(26);
        Message_MsgDisp("？？？", "Me too.\nI'm sorry for interrupting you.\nYou've worked hard.");
        Character_Chara_GS2(26, "NON");
        Music_StopBGM(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh...\nI thought you were a scary person,\nbut you're actually an amazing\nsenior.");
        System_GlobalWork(19, 0, 30);
        }
    else {
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(26, 0, (#1), 1);
        Character_ChFace(0, 3, 2);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("NS_92_000_00500", #1, "");
        Message_Who(26);
        Message_MsgDisp("？？？", "Why are you apologizing? Ah...\nDid I scare you?");
        Message_Who(0);
        Message_MsgDisp("主人公", "N-No, you didn't...");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(26, 0, (#1), 1);
        Character_ChFace(0, 3, 0);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("NS_92_000_00600", #1, "");
        Message_Who(26);
        Message_MsgDisp("？？？", "Majima Tarou. 2nd year.\nPeople often tell me my name and\nface don't suit each other.");
        Message_Who(0);
        Message_MsgDisp("主人公", "You're right-- No! Umm...");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(26, 0, (#1), 1);
        Character_ChFace(0, 3, 2);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("NS_92_000_00700", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "You're laughing.\nI'm quite concerned about it, too.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I'm sorry!");
        Character_ChFace(0, 2, 3);
        Character_BlinkStart(26, 0, (#1), 1);
        Character_ChFace(0, 3, 3);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("NS_92_000_00800", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "I will pardon it, as long as you\ntell me your name.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah!\nI am a first year,\n｛主人公姓名｝.");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(26, 3, (#1), 1);
        Character_ChFace(0, 3, 0);
        Character_ChFace(0, 4, 0);
        Voice_PlayVoice("NS_92_000_00900", #1, "");
        Message_Who(26);
        Message_MsgDisp("Majima", "Hmm... You're cute.\nYou think that about yourself, don't\nyou?");
        Message_MsgSel("I don't!", "Well, actually, yeah.");
        switch (Message_TextSelect()){
            case 0:
            Message_Who(0);
            Message_MsgDisp("主人公", "I-I don't think so!");
            Character_ChFace(0, 2, 5);
            Character_BlinkStart(26, 3, (#1), 1);
            Character_ChFace(0, 3, 5);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("NS_92_000_01000", #1, "");
            Message_Who(26);
            Message_MsgDisp("Majima", "I thought you'd say that.\nSo I'll tell you. You know...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Huh?");
            Character_Chara_GS2(26, "NON");
            Music_StopBGM(0, 40);
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(26, 2, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("NS_92_000_01100", #1, "");
            Message_Who(26);
            Message_MsgDisp("Majima", "You're really cute.\nMy heart is throbbing.... Later.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(Eh? Huh!?)");
            System_GlobalWork(19, 0, 1);
            break ;
            case 1:
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh, just a little.");
            Character_ChFace(0, 2, 3);
            Character_BlinkStart(26, 0, (#1), 1);
            Character_ChFace(0, 3, 3);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("NS_92_000_01200", #1, "");
            Message_Who(26);
            Message_MsgDisp("Majima", "I thought so. So I'll tell you.\nYou know...");
            Message_Who(0);
            Message_MsgDisp("主人公", "Eh?");
            Character_Chara_GS2(26, "NON");
            Music_StopBGM(0, 20);
            Character_ChFace(0, 2, 1);
            Character_BlinkStart(26, 0, (#1), 1);
            Character_ChFace(0, 3, 1);
            Character_ChFace(0, 4, 0);
            Voice_PlayVoice("NS_92_000_01300", #1, "");
            Message_Who(26);
            Message_MsgDisp("Majima", "You're nothing special.... Later.");
            Message_Who(0);
            Message_MsgDisp("主人公", "(......)");
            Message_Who(0);
            Message_MsgDisp("主人公", "(How mean!)");
            System_GlobalWork(19, 0, 30);
            break ;
            }
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    }
