section "d02_m5_000"{
    Character_BlinkStart(5, 1, (#1), 1);
    Character_BlinkStart(5, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Character_ChFace(0, 2, 5);
    Character_ChFace(0, 3, 1);
    Character_BlinkStart(5, 2, (#1), 1);
    Character_Chara_GS2(5, "M5_??F", 0);
    Effect_OpenParticle(0);
    Background_Bg_GS2("BG_FP230_SP_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "The cherry blossoms are so\nbeautiful.");
    Voice_PlayVoice("D0205000_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah.........");
    Message_Who(0);
    Message_MsgDisp("主人公", "... ｛Chris＊＊｝?\nAre you alright?");
    Character_BlinkStart(5, 0, (#1), 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0205000_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "......... Yeah. Ah, sorry.");
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0205000_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I think it's pretty, but...\nwhen the petals fall, it means that\nthe cherry blossoms for the year are\nfinished.");
    Character_BlinkStart(5, 2, (#1), 1);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0205000_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Then until the cherry blossoms\nblossom again, no one will take\nnotice of them...");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(5, 2, (#1), 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0205000_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nWhen I think about it like that,\nit's extremely sad......");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝...");
    Character_ChFace(0, 2, 5);
    Character_BlinkStart(5, 0, (#1), 1);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0205000_E00600", 5, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... ｛主人公｝.");
    Voice_PlayVoice("D0205000_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I...\nhave something that I've wanted to\nsay to you for a long time now.");
    Voice_PlayVoice("D0205000_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Just like the cherry blossoms,\nbefore I fall apart...");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Kyaa!");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(5, 2, (#1), 1);
    SoundEffect_PlayStream(2, "SS_T_00_074_M00");
    Effect_EffectParam(200, 10000, 8000, 3000, 2000);
    System_Wait(20);
    System_Wait(60);
    Effect_EffectParam(30, 2000, 4000, 3000, 2000);
    Message_Who(0);
    Message_MsgDisp("主人公", "That was some gust of wind...\nIt surprised me...");
    Voice_PlayVoice("D0205000_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", ".........");
    Message_Who(0);
    Message_MsgDisp("主人公", "...\n｛Chris＊＊｝, what's wrong?");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(5, 2, (#1), 1);
    Voice_PlayVoice("D0205000_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...... In this world......");
    Effect_CloseParticle();
    Character_Chara_GS2(5, "NON");
    Still_Event("EV_05_12", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_05_001_D00", 127, 40);
    Voice_PlayVoice("D0205000_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Were it not for the cherry blossoms\nin this world, our hearts and minds\nwould not be so serene and\npeaceful...");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0205000_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... I wonder why the two of us met.");
    Still_StillFace(0, 6, 2);
    Still_Approach(5, 131, 0, 0, 1, 1);
    Voice_PlayVoice("D0205000_E01300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It seems like it will take quite a\nlong time before I know if there is\na reason or not behind our\nmeeting...");
    Still_ApproachEnd();
    Background_Bg_GS2("BG_FP230_SP_0", #1, #1, 0);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Character_Chara_GS2(5, "M5_??F", 0);
    Screen_WipeIn(2);
    Effect_OpenParticle(0);
    Voice_PlayVoice("D0205000_E01400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ah, sorry.\nI've just been saying weird things.\nDon't worry about it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "But...");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(5, 3, (#1), 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0205000_E01500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "It's fine. Now, let's go somewhere.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Chris＊＊｝...)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Effect_CloseParticle();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(5, 61, 6);
    Parameter_AddCh1Param(5, 60, 3);
    Parameter_AddCh1Param(5, 62, #5);
    }
