section "d02_m1_000"{
    Character_BlinkStart(1, 1, (#1), 1);
    Character_BlinkStart(1, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0 = Parameter_GetPl1Param(12);
    switch (var0){
        case 0:
        Background_Bg_GS2("BG_HO200_WI_0", #1, #1, 0);
        break ;
        case 1:
        Background_Bg_GS2("BG_HO210_WI_0", #1, #1, 0);
        break ;
        case 2:
        Background_Bg_GS2("BG_HO220_WI_0", #1, #1, 0);
        break ;
        case 3:
        Background_Bg_GS2("BG_HO230_WI_0", #1, #1, 0);
        break ;
        }
    Screen_WipeIn(2);
    if (Parameter_GetCh1Param(1, 556) == 1){
        SoundEffect_PlaySE(19);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Ah, who is it?)");
        SoundEffect_StopSE(19, 0);
        SoundEffect_PlaySE(319);
        Voice_PlayVoice("FD_01_240_00000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Hello? It's me. Can you talk now?\nIt won't take long.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Sure. What's up?");
        Voice_PlayVoice("FD_01_240_00100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I've been doing some thinking, and\nI've decided I will be going back to\nmy parents' house.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!? But it's so sudden...");
        Voice_PlayVoice("FD_01_240_00200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Sangosho has closed, and I can't\nthink of any reasons for me to stay\nhere.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Is that so... When will you move?");
        Voice_PlayVoice("FD_01_240_00300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Ah, this... No.\nIf I tell you, you'll probably come\nto see me off.\nIt'll be too hard to look at you.");
        Voice_PlayVoice("FD_01_240_00400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I have to prepare, so I'm going to\nhang up.\nStay healthy. And...");
        Voice_PlayVoice("FD_01_240_00500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It'd be great if things between you\nand home go well.\nI'll be supporting you.... Later.");
        SoundEffect_PlaySE(330);
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Saeki＊＊｝ is going far\naway...)");
        }
    else {
        SoundEffect_PlaySE(19);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Who is it?)");
        SoundEffect_StopSE(19, 0);
        SoundEffect_PlaySE(20);
        Voice_PlayVoice("D0201000_A00000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Hello? Hey, can you come out now?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Now? Hmm... I can.\nWhere are you now?");
        Voice_PlayVoice("D0201000_A00100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "The breakwater.\nI'm sorry for it being so sudden,\nbut I don't have much time.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ok, I got it...\n｛Saeki＊＊｝, is something\nthe matter?");
        Voice_PlayVoice("D0201000_A00200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "We have to talk....\nSo, I'll be waiting.");
        SoundEffect_PlaySE(319);
        Message_Who(0);
        Message_MsgDisp("主人公", "(What's wrong...?)");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Still_Event("EV_01_12", #1, 0, 60);
        Screen_WipeIn(2);
        Still_StillFace(0, 6, 2);
        Environment_PlayME(1, "SN_BGF_035_000", 127, 0);
        Music_PlayBGM(0, "MN_C_01_001_D01", 127, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "Thanks for waiting!");
        Still_Event("EV_01_12", #1, 1, 60);
        Voice_PlayVoice("D0201000_A00300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Sorry for calling you out so\nsuddenly...");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's fine.\nAnyway, you said that we have to\ntalk.");
        Voice_PlayVoice("D0201000_A00400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I... am going back home.\nTo where my parents are.");
        Message_Who(0);
        Message_MsgDisp("主人公", "But, surely, ｛Saeki＊＊｝'s\nhouse is...");
        Voice_PlayVoice("D0201000_A00500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It's really far from here.\nThat's why I got my graduation\ncertificate a little early.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Your graduation certificate.\nSo then...");
        Voice_PlayVoice("D0201000_A00600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "So I'm going to wait for a chance to\nenter university, one that my\nparents will recommend.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Are you giving up on Sangosho?");
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("D0201000_A00700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Ah, it wasn't going to get anywhere\nfrom the beginning.\nIt will be shameful if I throw any\nmore tantrums.");
        Message_Who(0);
        Message_MsgDisp("主人公", "\"Shameful\"...\nBut you were trying so desperately\nhard.");
        Voice_PlayVoice("D0201000_A00800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It was just stubbornness.\nI was like a kid who couldn't do\nanything alone.\nIt's about time I grew up.");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's not like you,\n｛Saeki＊＊｝, to say such\nthings.");
        Still_Event("EV_01_23", #1, 0, 60);
        Voice_PlayVoice("D0201000_A00900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "... Then what is \"like me\"?\nWhat do you know about me?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I know you. We were always together.");
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("D0201000_A01000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "......");
        Message_Who(0);
        Message_MsgDisp("主人公", "You're a good guy at school, but\nyou're actually a little rude and\nsarcastic...");
        Message_Who(0);
        Message_MsgDisp("主人公", "However, when you talk about the\nsea, Sangosho, or your Grandpa, you\nare very gentle--");
        Still_StillFace(0, 0, 0);
        Still_StillFace(0, 6, 0);
        Voice_PlayVoice("D0201000_A01100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "What if that was a lie?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh?");
        Voice_PlayVoice("D0201000_A01200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It could be that the real me is how\nI act at school, and the me that was\nwith you was all a lie.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...\nThe times we laughed together, the\ntimes we fought...\nIt was all a lie?");
        Still_StillFace(0, 6, 2);
        Voice_PlayVoice("D0201000_A01300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Yeah... I'm awful, aren't I?");
        Message_Who(0);
        Message_MsgDisp("主人公", "It can't be...");
        Voice_PlayVoice("D0201000_A01400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "That's why I want you to forget.\nAbout Sangosho... and about me.");
        Message_Who(0);
        Message_MsgDisp("主人公", "I can't...");
        Still_StillFace(0, 0, 1);
        Still_StillFace(0, 6, 0);
        Voice_PlayVoice("D0201000_A01500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I'm begging you, I can't handle it\nany more!\nI don't want you to see me being so\nshameful...");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝...");
        Still_StillFace(0, 0, 0);
        Still_StillFace(0, 6, 2);
        Voice_PlayVoice("D0201000_A01600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "The mermaid and the young man...\nwere never supposed to meet.");
        Still_Approach(1, 11, 0, 0, 0, 1);
        Voice_PlayVoice("D0201000_A01700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "If that was the case, then there\nwouldn't be a sad story.");
        Still_ApproachEnd();
        Still_StillFace(0, 6, 0);
        Voice_PlayVoice("D0201000_A01800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "... Goodbye.");
        Music_StopBGM(0, 40);
        Still_Event("EV_01_26", #1, 1, 60);
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Saeki＊＊｝ left...\nI won't be able to see him\nanymore...)");
        Message_CloseMsg();
        Environment_StopME(1, 40);
        Screen_WipeOut(2);
        Still_Event("");
        }
    Screen_ClearScreen();
    Parameter_InCh1Param(1, 540, 45);
    Parameter_AddCh1Param(1, 61, 6);
    Parameter_AddCh1Param(1, 60, 3);
    Parameter_AddCh1Param(1, 62, #5);
    }
