section "d02_s1_001"{
    Character_BlinkStart(14, 1, (#1), 1);
    Character_BlinkStart(14, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    int var0 = Parameter_GetPl1Param(12);
    switch (var0){
        case 0:
        Background_Bg_GS2("BG_HO200_SP_0", #1, #1, 0);
        break ;
        case 1:
        Background_Bg_GS2("BG_HO210_SP_0", #1, #1, 0);
        break ;
        case 2:
        Background_Bg_GS2("BG_HO220_SP_0", #1, #1, 0);
        break ;
        case 3:
        Background_Bg_GS2("BG_HO230_SP_0", #1, #1, 0);
        break ;
        }
    Screen_WipeIn(2);
    Voice_PlayVoice("D0214001_N00000", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Sis! Hey～! Wake up! Sis!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm～... Yuu-kun? Wait a second...");
    SoundEffect_PlayStream(2, "SS_T_00_109_M00");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(14, "S1_17F", 0);
    Background_Bg_GS2("BG_BH200_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_14_000_D00", 127, 40);
    Voice_PlayVoice("D0214001_N00100", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Good morning!\nHey, you're free today as well,\nright?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Not as well, just today.\nBut yeah, I'm free.");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(14, 3, (#1), 1);
    Voice_PlayVoice("D0214001_N00200", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Alright! ...\n*Erhem*");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(14, 0, (#1), 1);
    Voice_PlayVoice("D0214001_N00300", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "So, umm～...\nDo you want to go to the Amusement\nPark?");
    Message_Who(0);
    Message_MsgDisp("主人公", "The Amusement Park?\nYou want me to take you there?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(14, 3, (#1), 1);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0214001_N00400", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "No... Geez, you're slow!\nI was saying that I'd take you out\non a date...");
    Message_Who(0);
    Message_MsgDisp("主人公", "A date!? With Yuu-kun?");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(14, 0, (#1), 1);
    Voice_PlayVoice("D0214001_N00500", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "What...\nYou don't like being with me...?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? No, that's not it...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0214001_N00600", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Alright!\nThen hurry up and get ready!\nGirls take a long time to get ready,\nright?");
    Message_Who(0);
    Message_MsgDisp("主人公", "(A date with Yuu-kun...\nWell, it's fine, I suppose?)");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(14, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 2, 4);
    Character_ChFace(0, 3, 3);
    Character_Chara_GS2(14, "S1_04F", 0);
    Background_Bg_GS2("BG_TR500_SP_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_B_TR_500_000", 127, 40);
    SoundEffect_PlayStream(2, "EV_SE_FOOT_1001");
    Voice_PlayVoice("D0214001_N00700", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Bam! We're here! Whoa～! Cool!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yuu-kun, if you run like that you'll\nfall over!");
    Character_ChFace(0, 2, 2);
    Voice_PlayVoice("D0214001_N00800", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "I won't!\nOh, I found the roller coaster!!\nHurry, Sis!!");
    SoundEffect_PlayStream(2, "SS_T_00_140_M00");
    Character_Chara_GS2(14, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, wait a second!");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(14, 3, (#1), 1);
    Character_Chara_GS2(14, "S1_04F", 0);
    Background_Bg_GS2("BG_TR510_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0214001_N00900", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Hah... We got to play quite a lot.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, is it about time we headed\nhome?\nIf you're late, your mother will\nworry about you, right?");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(14, 0, (#1), 1);
    Voice_PlayVoice("D0214001_N01000", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "What... Don't talk about my mother!\nIt's not late at all!");
    Message_Who(0);
    Message_MsgDisp("主人公", "S-Sorry...\nSo, should we ride the roller\ncoaster once more? test");
    Character_ChFace(0, 3, 2);
    Character_BlinkStart(14, 2, (#1), 1);
    Voice_PlayVoice("D0214001_N01100", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Roller coaster!! No...\nwait a second.");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(14, 3, (#1), 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("D0214001_N01200", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Hmm... No, I shouldn't.\nWe'll ride the Ferris Wheel.\nIt's common sense.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Is that so?");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(14, "NON");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(14, 0, (#1), 1);
    Character_Chara_GS2(14, "S1_04F", 0);
    Background_Bg_GS2("BG_TR520_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0214001_N01300", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Yeah!\nIt's so big when you look at it up\nclose.\nCome on, hurry!");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(14, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 2);
    Character_Chara_GS2(14, "S1_04F", 0);
    Background_Bg_GS2("BG_TR501_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0214001_N01400", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Umm, when couples ride on a Ferris\nWheel, do they just sit?");
    Music_PlayBGM(0, "MN_C_14_001_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh!? U-Umm...\nI think it's different for everyone?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(14, 3, (#1), 1);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0214001_N01500", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "I see. What's so fun...\nAh, whatever.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hey, Yuu-kun.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("D0214001_N01600", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Hmm?");
    Message_Who(0);
    Message_MsgDisp("主人公", "What's with you all of a suddenly\nasking me on a date?");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(14, 3, (#1), 1);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0214001_N01700", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "......");
    Character_BlinkStart(14, 0, (#1), 1);
    Voice_PlayVoice("D0214001_N01800", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "I grew 5cm since last year.");
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("D0214001_N01900", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Do you think I'm a kid? It's fine.\nBut I will become bigger soon!\nI'll be a middle school student this\nSpring!");
    Character_BlinkStart(14, 3, (#1), 1);
    Voice_PlayVoice("D0214001_N02000", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "And when I do...\npeople will definitely see us as a\ncouple.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Yuu-kun...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(14, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_ChFace(0, 0, 9);
    Character_Chara_GS2(14, "S1_04F", 0);
    Background_Bg_GS2("BG_TR500_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "What should we do now?\nWhat should we do on a date?");
    Voice_PlayVoice("D0214001_N02100", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Haha, I wonder...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0214001_N02200", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "...\nHmm, it's already late, I'll walk\nyou home.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Please.");
    Character_BlinkStart(14, 3, (#1), 1);
    Voice_PlayVoice("D0214001_N02300", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Leave it to me!");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(14, "NON");
    Character_Chara_GS2(14, "S1_04F", 0);
    Background_Bg_GS2("BG_HO000_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("D0214001_N02400", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Sis. Thank you for today.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Same here.");
    Voice_PlayVoice("D0214001_N02500", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Hey, if it's alright, we should--\nAh!!");
    Message_Who(0);
    Message_MsgDisp("主人公", "What!?");
    Character_ChFace(0, 0, 11);
    Voice_PlayVoice("D0214001_N02600", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "I forgot to buy you juice, Sis!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Haha, then buy it for me next time,\nokay?");
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("D0214001_N02700", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "I promise.\nWe'll have a proper date next time.\nI'll be a middle schooler by then.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Sure.");
    Character_ChFace(0, 2, 3);
    Voice_PlayVoice("D0214001_N02800", #1, "");
    Message_Who(14);
    Message_MsgDisp("Yuu", "Later!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(14, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Right...\nYuu-kun is going to be a middle\nschool student in Spring...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(14, 86, 1);
    Parameter_InCh1Param(14, 538, 43);
    }
