section "d02_m6_000"{
    Character_BlinkStart(6, 1, (#1), 1);
    Character_BlinkStart(6, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Character_Chara_GS2(6, "M6_??F", 0);
    Background_Bg_GS2("BG_NE100_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah, it's so pretty!");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(6, 2, (#1), 1);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("D0206000_F00000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... It's a little like... a lie.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?");
    Character_ChFace(0, 0, 6);
    Character_BlinkStart(6, 3, (#1), 1);
    Character_ChFace(0, 4, 0);
    Voice_PlayVoice("D0206000_F00100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "For me to be here in such a place.");
    Character_Chara_GS2(6, "NON");
    Still_Event("EV_06_10", #1, 0, 60);
    Music_PlayBGM(0, "MN_X_01_D02_D00", 127, 40);
    Voice_PlayVoice("D0206000_F00200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Because it's cold, I don't like\nWinter, especially around this time.");
    Voice_PlayVoice("D0206000_F00300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "The city is noisy and there are many\npeople.\nI would never think that I'd want to\ngo out.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D0206000_F00400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "This kind of illumination is a waste\nof electricity.");
    Voice_PlayVoice("D0206000_F00500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I'm made to always listen to\nChristmas songs that I don't want to\nlisten to.");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0206000_F00600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I also don't like the shady looking\nSanta recommending I buy a\ndisgusting looking cake that I don't\nwant to eat.");
    Voice_PlayVoice("D0206000_F00700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "But even so--");
    Still_StillFace(0, 6, 1);
    Still_StillFace(0, 3, 1);
    Voice_PlayVoice("D0206000_F00800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "The illumination is pretty and\nlistening to the Christmas songs are\nenjoyable.");
    Voice_PlayVoice("D0206000_F00900", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "And now I think that those\nrecommended cakes aren't that bad.");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 6, 0);
    Still_Approach(6, 159, 0, 0, 1, 1);
    Voice_PlayVoice("D0206000_F01000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "All of those things are because of\nthat one girl.\nIt's really unbelievable.");
    Still_ApproachEnd();
    Background_Bg_GS2("BG_NE100_LI_1", #1, #1, 0);
    Character_ChFace(0, 0, 3);
    Character_ChFace(0, 3, 3);
    Character_Chara_GS2(6, "M6_??F", 0);
    Still_Event("");
    Voice_PlayVoice("D0206000_F01100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "You don't know how amazing this\nis...\nDo you, Senpai?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yeah...");
    Character_BlinkStart(6, 2, (#1), 1);
    Voice_PlayVoice("D0206000_F01200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "But that... may be my salvation.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Salvation?");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(6, 3, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0206000_F01300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Ahaha, yeah, that.\nIf Senpai wasn't the class clown,\nyou wouldn't be right for me.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0206000_F01400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "But... it's fine.\nI want you to be aware of it.\nThe fact that I've changed.");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0206000_F01500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Surely no one else except Senpai can\nunderstand.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Amachi＊＊｝...");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(6, 2, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0206000_F01600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Ah, maybe it was an impossible\nrequest, after all.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0206000_F01700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I'm sorry for suddenly making things\ncomplicated for an ignorant person\nlike you, Senpai.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Geez, ｛Amachi＊＊｝!");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("D0206000_F01800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "It's cold here.\nLet's go to a warm place, Senpai.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Date_InData_Date(124, 4);
    Date_InData_Date(321, 1);
    Parameter_AddCh1Param(6, 61, 6);
    Parameter_AddCh1Param(6, 60, 3);
    Parameter_AddCh1Param(6, 62, #5);
    System_GlobalWork(5, 0, 1);
    }
