section "d02_m2_000"{
    Character_BlinkStart(2, 1, (#1), 1);
    Character_BlinkStart(2, 1, (#1), 2);
    Character_ChFace(0, 0, 0);
    Character_ChFace(1, 0, 0);
    Background_Bg_GS2("BG_SC302_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, right.\nI was going to go to the library\nroom!)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Hmm, there's still some time left\nin my break...\nAh, I'll just go!)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_SC311_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Let's see...\nThe history shelf, the history\nshelf...)");
    Voice_PlayVoice("", 2, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Environment_StopME(0, 40);
    Still_Event("EV_02_12", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_02_002_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝...\nWere you sleeping?");
    Voice_PlayVoice("D0202000_B00100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Yeah... What period is next?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Third period.");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0202000_B00200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Third period...? Ah...\nWhatever...");
    Still_Approach(2, 41, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "It's not good...\nClass is about to start!");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0202000_B00300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... You should stay here, too.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...?");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("D0202000_B00400", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "...\nEven if you don't say anything...\nYou're an interesting person.\nIt's the first time I've met someone\nlike you...");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D0202000_B00500", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... Like this...\nI can relax just knowing that you\nare at the same place I am...");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D0202000_B00600", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "That's why you should.........");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝...?");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_SC311_CO_0", #1, #1, 0);
    Character_Chara_GS2(2, "M2_01F", 0);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Screen_WipeIn(2);
    Voice_PlayVoice("D0202000_B00700", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... You should head back to class.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh...\nWhat about you,\n｛Shiba＊＊｝?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(2, 3, (#1), 1);
    Voice_PlayVoice("D0202000_B00800", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Hmm? ...\nLet me sleep a little while longer.\nI slept late last night.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Hmm.\nJust for today though, okay?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(2, 2, (#1), 1);
    Voice_PlayVoice("D0202000_B00900", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Thanks.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Now then, I'm going.");
    Character_ChFace(0, 0, 0);
    Character_BlinkStart(2, 0, (#1), 1);
    Voice_PlayVoice("", 2, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm?");
    Character_BlinkStart(2, 3, (#1), 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("D0202000_B01000", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "... It's nothing.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... You were just saying my name?");
    Voice_PlayVoice("D0202000_B01100", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Yeah.\nI think that I'll be able to have a\nnice dream.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Shiba＊＊｝...");
    SoundEffect_PlayStream(2, "SS_T_00_079_S00");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D0202000_B01200", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Hey.\nIf you don't hurry back, you'll be\nyelled at.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yeah. Now then...");
    Character_BlinkStart(2, 2, (#1), 1);
    Voice_PlayVoice("D0202000_B01300", #1, "");
    Message_Who(2);
    Message_MsgDisp("Shiba", "Goodnight.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Shiba＊＊｝...)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    SoundEffect_StopStream(2, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(2, 86, 1);
    Parameter_AddCh1Param(2, 61, 6);
    Parameter_AddCh1Param(2, 60, 3);
    Parameter_AddCh1Param(2, 62, #5);
    }
