section "d99_m5_000"{
    Background_Bg_GS2("BG_FP000_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh, it seems like\n｛Chris＊＊｝ hasn't come,\nyet.");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "I wonder what happened with\n｛Chris＊＊｝...?");
    Character_Chara_GS2(20, "N1_17F", 0);
    Voice_PlayVoice("NS_M2_050_00000", #1, "");
    Message_Who(20);
    Message_Who(20);
    Message_MsgDisp("Man", "Hi, Miss. What are you doing here?");
    Message_Who(0);
    Message_MsgDisp("主人公", "...");
    Voice_PlayVoice("NS_M2_050_00100", #1, "");
    Message_Who(20);
    Message_Who(20);
    Message_MsgDisp("Man", "Come on, don't ignore me～.\nWell, that gets me more excited,\nthough!\nCome on, let's go!");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, please let go of me!");
    Voice_PlayVoice("D9905000_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("？？？", "Here.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Character_Chara_GS2(20, "NON");
    Still_Event("EV_05_23", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_05_000_D00", 127, 40);
    Message_WindowPosition(0);
    Voice_PlayVoice("NS_M2_050_00200", #1, "");
    Message_Who(22);
    Message_Who(22);
    Message_MsgDisp("Man", "Wh... Who are you!");
    Message_WindowPosition(1);
    Voice_PlayVoice("D9905000_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I don't have a name for a person\nlike you.\nCan you just back off?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah... ｛Chris＊＊｝!");
    Voice_PlayVoice("D9905000_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Sorry I'm late. Are you alright?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Y-Yeah.");
    Still_Approach(5, 135, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Being this close to him makes my\nheart beat faster.\nUgh, I can't settle down...)");
    Still_ApproachEnd();
    Still_StillFace(0, 0, 1);
    Message_WindowPosition(1);
    Voice_PlayVoice("D9905000_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Lucky.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? What is?");
    Voice_PlayVoice("D9905000_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Being able to be so close to you....\nTo be in contact with you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "\"Contact\"... Ehh!?");
    Message_WindowPosition(0);
    Voice_PlayVoice("NS_M2_050_00300", #1, "");
    Message_Who(22);
    Message_Who(22);
    Message_MsgDisp("Man", "Don't go into your own world!\nI spoke to her first!");
    Still_StillFace(0, 0, 0);
    Message_WindowPosition(1);
    Voice_PlayVoice("D9905000_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "...\nIt's unfortunate, but I don't do\nthese kinds of conversations.");
    Message_WindowPosition(0);
    Voice_PlayVoice("NS_M2_050_00400", #1, "");
    Message_Who(22);
    Message_Who(22);
    Message_MsgDisp("Man", "W-What do you mean!");
    Message_WindowPosition(1);
    Voice_PlayVoice("D9905000_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Everything about this girl is mine.");
    Voice_PlayVoice("D9905000_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "So don't you touch her. Ever.");
    Message_WindowPosition(0);
    Voice_PlayVoice("NS_M2_050_00500", #1, "");
    Message_Who(22);
    Message_Who(22);
    Message_MsgDisp("Man", "Uh...");
    Message_WindowPosition(1);
    Voice_PlayVoice("D9905000_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "... Do you still have business here?\nNo one likes a guy who doesn't know\nwhen to back off.");
    Message_WindowPosition(0);
    Voice_PlayVoice("NS_M2_050_00600", #1, "");
    Message_Who(22);
    Message_Who(22);
    Message_MsgDisp("Man", "I-I'll back off for today...\nRemember this day!");
    Character_Chara_GS2(5, "M5_D?F", 0);
    Still_Event("");
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 2, 0);
    Voice_PlayVoice("D9905000_E00900", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Too bad.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh... why?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(5, 3, (#1));
    Voice_PlayVoice("D9905000_E01000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "If that guy was a little more\npersistent, I would've been able to\nhold you for longer.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Geez, ｛Chris＊＊｝!");
    Character_ChFace(0, 2, 0);
    Character_BlinkStart(5, 1, (#1));
    Character_BlinkStart(5, 0, (#1));
    Voice_PlayVoice("D9905000_E01100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Ahaha, I'm joking.");
    Character_ChFace(0, 0, 0);
    Voice_PlayVoice("D9905000_E01200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Now then, let's start again.\n-- Thanks for waiting.\nLet's go on a fun date.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah!");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 61, 6);
    Parameter_AddCh1Param(5, 60, 3);
    Parameter_AddCh1Param(5, 62, #5);
    }
