section "d99_m4_000"{
    Background_Bg_GS2("BG_NE000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's about time I went home....\nHmm?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(The fliers that are put up over\nthere are from\n｛Hariya＊＊｝'s band...)");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I was right, after all.\nHe was also handing them out here\nbefore.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(ReD: Cro'z LIVE...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah, it's today! ...\nMaybe I should go take a look.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_NE200_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(It's already started.\nWhat should I do...?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    SoundEffect_PlayStream(3, "SEQ_SE_EV_138");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Ah.)");
    SoundEffect_PlayStream(3, "GAYA_KANSEI_LOOP_02");
    Still_Event("EV_04_20", #1, 0, 60);
    Screen_WipeIn(2);
    Voice_PlayVoice("NS_F2_040_00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Girl A", "Harry is here! Ah, Ino is here, too!");
    Voice_PlayVoice("NS_F1_040_00000", #1, "");
    Message_Who(0);
    Message_MsgDisp("Girl B", "So cool～...");
    Still_Approach(4, 103, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hariya＊＊｝'s band is\npopular...)");
    Still_ApproachEnd();
    SoundEffect_StopStream(3, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(He was different to when I see him\nat school, ｛Hariya＊＊｝...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I kind of feel like he's becoming a\nstranger to me...\nWhy is that...?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 61, 6);
    Parameter_AddCh1Param(4, 60, 3);
    Parameter_AddCh1Param(4, 62, #5);
    }
