section "d99_m7_000"{
    Background_Bg_GS2("BG_SC420_SP_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(*Sigh...\nAll that's left is to tidy up.\nNext I have to return the key,\nreport to ｛Wakaouji＊＊｝,\nand--)");
    Voice_PlayVoice("", 7, "D9907000_G00000");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "｛主人公｝, over here!");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝?\nWhat do you mean by... Ah!\nWhat are you doing?");
    Voice_PlayVoice("D9907000_G00100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "I'm taking a little break.\nWhat about you?\nThe spot next to me is free.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Still_Event("EV_07_20", #1, 0, 60);
    Music_PlayBGM(0, "MN_C_07_001_D00", 127, 40);
    Still_StillFace(0, 0, 2);
    Screen_WipeIn(2);
    Voice_PlayVoice("D9907000_G00200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Ah, welcome.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes, sorry for interrupting you...");
    Still_StillFace(0, 0, 0);
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "......");
    Still_Approach(7, 192, 0, 0, 1, 1);
    Message_Who(0);
    Message_MsgDisp("主人公", "......");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 2);
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "......");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm...\nHow long are we going to do this?");
    Still_StillFace(0, 0, 2);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("D9907000_G00500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Hmm, yeah...\nUntil you nap and wake up.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? I'm not sleepy.");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D9907000_G00600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Is that so?\nThen try shutting your eyes.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay...");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "As expected, I don't really feel--");
    Still_StillFace(0, 6, 1);
    Still_Approach(7, 192, 0, 0, 1, 5);
    Voice_PlayVoice("D9907000_G00700", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Shh...");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "?");
    Voice_PlayVoice("D9907000_G00800", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Breathe slowly...\nBe as quiet as you can... Right...");
    Message_Who(0);
    Message_MsgDisp("主人公", "......");
    Message_CloseMsg();
    Screen_WipeOut(3);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Still_Event("EV_07_20", #1, 0, 60);
    Still_StillFace(0, 6, 0);
    Screen_WipeIn(3);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? When exactly did I...)");
    Voice_PlayVoice("D9907000_G00900", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Good morning.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Wakaouji＊＊｝...\nWas I sleeping?");
    Still_StillFace(0, 0, 2);
    Still_Approach(7, 192, 0, 0, 1, 9);
    Voice_PlayVoice("D9907000_G01000", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "For about 15 minutes.\nYou have quite an attractive\nsleeping face.");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "(!! How embarrassing...)");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("D9907000_G01100", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Stay like that and listen to me.");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 0);
    Still_Approach(7, 192, 0, 0, 1, 13);
    Voice_PlayVoice("D9907000_G01200", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "Doing your very best in everything\nis amazing, whether it be for the\nclub or anything else.");
    Still_ApproachEnd();
    Voice_PlayVoice("D9907000_G01300", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "But it's bad to overdo it like you\ndid today, or when it seems like\nyou're going to collapse.");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("D9907000_G01400", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "There are incidents that can happen\nwhere you can't undo things.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Okay.");
    Background_Bg_GS2("BG_SC420_SP_1", #1, #1, 0);
    Still_Event("");
    Character_ChFace(0, 0, 10);
    Character_Chara_GS2(7, "M7_08F", 0);
    Voice_PlayVoice("D9907000_G01500", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "*Sigh*... When I nap, I get hungry.\nWhat about you?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes, I am hungry, too.");
    Voice_PlayVoice("D9907000_G01600", #1, "");
    Message_Who(7);
    Message_MsgDisp("Wakaouji", "It's proof that you are healthy.\nI will do the rest, so you should\nhurry home.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Right, I was tired, so then\n｛Wakaouji＊＊｝...)");
    Music_StopBGM(0, 40);
    Parameter_AddPl1Param(22, #50);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(7, 61, 6);
    Parameter_AddCh1Param(7, 60, 3);
    Parameter_AddCh1Param(7, 62, #5);
    }
