section "g01_g1_020"{
    Character_Chara_GS2(10, "G1_01F", 0);
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(10, 2, (#1));
    Background_Bg_GS2("BG_SC410_?_0", 1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_10_001_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh, ｛Toudou＊＊｝.");
    Voice_PlayVoice("G0110020_J00000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Oh, it's you...");
    Message_Who(0);
    Message_MsgDisp("主人公", "What are you doing in a place like\nthis?");
    Character_BlinkStart(10, 3, (#1));
    Voice_PlayVoice("G0110020_J00100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "You know, ｛主人公｝...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm? What is it?");
    Character_BlinkStart(10, 0, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("G0110020_J00200", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Love is tiring.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah...");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(10, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("G0110020_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "*Giggles*...... Ahaha!");
    Message_Who(0);
    Message_MsgDisp("主人公", "What's so funny?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(10, 2, (#1));
    Voice_PlayVoice("G0110020_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "You don't get it...\nReally, it's best to make an end to\nthis.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?");
    Character_ChFace(0, 4, 0);
    Character_BlinkStart(10, 0, (#1));
    Voice_PlayVoice("G0110020_J00500", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I'm putting in some fighting spirit\nfor love, even if I have to\nchallenge you.\nAfter all, you're my friend.");
    Character_BlinkStart(10, 3, (#1));
    Voice_PlayVoice("G0110020_J00600", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "You always have time to smile...\nI am no match for you, at all.");
    Message_Who(0);
    Message_MsgDisp("主人公", "That's not true...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("G0110020_J00700", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I am defeated.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Toudou＊＊｝...!");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("G0110020_J00800", #1, "G0110020_J00801");
    Message_Who(10);
    Message_MsgDisp("Toudou", "It's okay, ｛主人公｝.\nHe's the one I fell in love with.\nFocus on catching him, okay?");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Okay.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("G0110020_J00900", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Be sure to be happy. Promise me?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Thank you... ｛Toudou＊＊｝.");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(10, 86, 1);
    }
