section "g01_g1_010"{
    Background_Bg_GS2("BG_SC100_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Character_Chara_GS2(10, "G1_01F", 0);
    Character_ChFace(0, 2, 1);
    Music_PlayBGM(0, "MN_C_10_001_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Toudou＊＊｝.");
    Voice_PlayVoice("G0110010_J00000", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I've been waiting for you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? For me?");
    Voice_PlayVoice("G0110010_J00100", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "We have to talk.\nIs now a good time...?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(10, "NON");
    Character_Chara_GS2(10, "G1_01F", 0);
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(10, 3, (#1));
    Background_Bg_GS2("BG_EX100_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("G0110010_J00200", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Since I don't like to keep things to\nmyself, I'll say this bluntly.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay.");
    Character_BlinkStart(10, 0, (#1));
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("G0110010_J00300", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "I have fallen for Shiba.");
    Message_Who(0);
    Message_MsgDisp("主人公", "H-H-Huh!?");
    Character_BlinkStart(10, 3, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("G0110010_J00400", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Hah... Laugh if you want.");
    Message_Who(0);
    Message_MsgDisp("主人公", "No... why would I?\nBut why are you telling me this?");
    Character_BlinkStart(10, 0, (#1));
    Character_ChFace(0, 2, 1);
    Voice_PlayVoice("G0110010_J00500", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "*Sigh* ... I wonder why.\nFor the time being, I'm cutting ties\nwith humanity.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("G0110010_J00600", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "It's a fair and square match,\n｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "But those are fighting words...");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("G0110010_J00700", #1, "");
    Message_Who(10);
    Message_MsgDisp("Toudou", "Win or lose, no hard feelings.\nSorry, but I'm serious about this,\nokay?");
    Message_MsgSel("I'm not playing this game.", "(｛Toudou＊＊｝ as a rival...)");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "I'm not playing this game.");
        Character_ChFace(0, 0, 8);
        Voice_PlayVoice("G0110010_J00800", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Are you running away?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I mean...\nThere's no reason to fight.");
        Character_ChFace(0, 0, 11);
        Voice_PlayVoice("G0110010_J00900", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Is that true?");
        Character_ChFace(0, 0, 10);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("G0110010_J01000", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I'm sorry. I got ahead of myself.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(10, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(It's my first seeing you like this,\n｛Toudou＊＊｝...)");
        Parameter_InCh1Param(10, 513, 0);
        break ;
        case 1:
        Character_ChFace(0, 0, 7);
        Voice_PlayVoice("G0110010_J01100", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Well then, my best regards.");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(10, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, wait... ｛Toudou＊＊｝!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Toudou＊＊｝ is falling\nfor ｛Shiba＊＊｝...)");
        break ;
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(10, 86, 1);
    }
