section "g01_g4_020"{
    Background_Bg_GS2("BG_SC202_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(*Sigh*... It's getting late...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? Isn't that...)");
    Character_Chara_GS2(13, "G4_01F", 0);
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Music_PlayBGM(0, "MN_C_13_001_D01", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Mizushima＊＊｝...");
    Voice_PlayVoice("G0113020_M00000", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Yes.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Were you waiting for me, by any\nchance?");
    Character_BlinkStart(13, 2, (#1));
    Voice_PlayVoice("G0113020_M00100", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "... Yes.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Can we go to the rooftop?");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(13, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_Chara_GS2(13, "G4_01F", 0);
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(13, 3, (#1));
    Background_Bg_GS2("BG_SC500_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Mizushima＊＊｝.....\nDid something happened?");
    Character_BlinkStart(13, 2, (#1));
    Voice_PlayVoice("G0113020_M00200", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "A talk... I want you to hear me out.\nI know that what I'm asking is\nselfish.");
    Message_Who(0);
    Message_MsgDisp("主人公", "No, it's fine.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("G0113020_M00300", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "You do know that Chris-kun is a\nfree-spirit, right?\n... A pervert, though.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.");
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("G0113020_M00400", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "However, when it's just the two of\nus, he seems to be very uptight.");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("G0113020_M00500", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "The two of us used to talk like this\nbefore, and then a lot of things\nchanged.");
    Character_BlinkStart(13, 2, (#1));
    Voice_PlayVoice("G0113020_M00600", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "I might have seen my ideal self\nwithin Chris, who is so liberal, or\nI may have just fallen in love with\nhim.");
    Character_ChFace(0, 0, 9);
    Voice_PlayVoice("G0113020_M00700", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Now I'm wondering why I treat you so\nharshly.");
    Character_BlinkStart(13, 2, (#1));
    Voice_PlayVoice("G0113020_M00800", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Even though I was so mean to you,\nyou never changed one bit...");
    Character_BlinkStart(13, 3, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("G0113020_M00900", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Always thinking about myself...\nBut, I wondered what kind of\nfeelings you had.");
    Character_BlinkStart(13, 2, (#1));
    Voice_PlayVoice("G0113020_M01000", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "It's hard...\nBut, I don't know what else to do.\nForgive me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Forgive you...\n｛Mizushima＊＊｝, it's really\nokay.");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(13, 2, (#1));
    Voice_PlayVoice("G0113020_M01100", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "Treasure Chris-kun, okay?\nAlways be carefree, like him.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes, I'll do my best.");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(13, 3, (#1));
    Voice_PlayVoice("G0113020_M01200", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "If you ever make Chris-kun cry, I'm\ngoing to take him away from you!");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay, I'll try my best...");
    Character_BlinkStart(13, 0, (#1));
    Voice_PlayVoice("G0113020_M01300", #1, "");
    Message_Who(13);
    Message_MsgDisp("Mizushima", "*giggles*, It's a joke.\nI'll cheer you on.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Finally, feelings were understood.)");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(13, "NON");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(13, 86, 1);
    }
