section "g01_g2_010"{
    Character_Chara_GS2(11, "G2_01F", 0);
    Character_ChFace(0, 0, 8);
    Background_Bg_GS2("BG_SC100_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_11_001_D00", 127, 40);
    Voice_PlayVoice("", #1, "G0111010_K00000");
    Message_Who(11);
    Message_MsgDisp("Onoda", "｛主人公｝.\nI have something to tell you, do you\nhave time?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh, ｛Onoda＊＊｝....\nHuh, that ribbon, what's wrong?");
    Character_BlinkStart(11, 3, (#1));
    Voice_PlayVoice("G0111010_K00100", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "This is to show my determination!\nMy feelings are just like this\nribbon, both are linked tightly!");
    Message_Who(0);
    Message_MsgDisp("主人公", "...\n*Sigh*");
    Character_BlinkStart(11, 2, (#1));
    Character_ChFace(0, 3, 2);
    Voice_PlayVoice("G0111010_K00200", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "It may be against the school rules.\nBut, I have to stay firm....\nI checked to make sure it was all\nright.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see. Good for you.");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(11, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("G0111010_K00300", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Good.... No, not that!\nWhat I am trying to say is...");
    Character_ChFace(0, 4, 0);
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(11, 3, (#1));
    Voice_PlayVoice("G0111010_K00400", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "I...I never knew these kind of\nfeelings were inside of me.");
    Character_BlinkStart(11, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("G0111010_K00500", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "I may have truly known.\nI never wanted to admit it.\nIn some respect, I thought about it.");
    Character_BlinkStart(11, 0, (#1));
    Voice_PlayVoice("G0111010_K00600", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "But I cannot　lie to myself.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm... ｛Onoda＊＊｝?");
    Character_ChFace(0, 0, 3);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("G0111010_K00700", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "I... like Hikami-kun.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh...?");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("G0111010_K00800", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "I am the only one who can understand\nHikami-kun's feelings, no one\nelse...\nNot even you.");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("G0111010_K00900", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "I will prove it....\nI swear on this ribbon!\nI will never lose against you!!");
    Message_Who(0);
    Message_MsgDisp("主人公", "W-Well...");
    Character_BlinkStart(11, 2, (#1));
    Voice_PlayVoice("G0111010_K01000", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "That's enough talking! ...\nExcuse me!");
    Message_MsgSel("Wait! You've got the wrong idea!", "(Ugh, I'm going to lose...)");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "Wait! You got the wrong idea!");
        Character_ChFace(0, 2, 4);
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("G0111010_K01100", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Huh... I do?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah.");
        Character_ChFace(0, 2, 2);
        Character_BlinkStart(11, 2, (#1));
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("G0111010_K01200", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Are you... I-I am sorry. I...");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(11, 2, (#1));
        Voice_PlayVoice("G0111010_K01300", #1, "");
        Message_Who(11);
        Message_MsgDisp("Onoda", "Let's be friends forever!");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(11, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(This is my first time seeing you\nlike this, ｛Onoda＊＊｝...)");
        Parameter_InCh1Param(11, 513, 0);
        break ;
        case 1:
        SoundEffect_PlayStream(2, "SS_T_00_029_M00");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(11, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(...\n｛Onoda＊＊｝ and\n｛Hikami＊＊｝...)");
        break ;
        }
    Message_CloseMsg();
    SoundEffect_StopStream(2, 40);
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(11, 86, 1);
    }
