section "g01_g3_010"{
    Character_Chara_GS2(12, "G3_01F", 0);
    Background_Bg_GS2("BG_SC100_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_C_12_001_D00", 127, 40);
    Voice_PlayVoice("G0112010_L00000", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Oh, ｛主人公｝!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh, ｛Nishimoto＊＊｝.\nWhat's up?");
    Character_ChFace(0, 0, 10);
    Character_BlinkStart(12, 3, (#1));
    Voice_PlayVoice("G0112010_L00100", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Good timing, heading home?\nHey, if you're free, could we go for\na cup of tea on our way home?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yeah, let's go!");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(12, "NON");
    Character_Chara_GS2(12, "G3_03F", 0);
    Background_Bg_GS2("BG_EX000_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("G0112010_L00200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "...\nAnd I'm going to nag you really hard\nwithout any second thoughts.\nAh, what am I saying!");
    Message_Who(0);
    Message_MsgDisp("主人公", "*Giggles* That seems like you,\n｛Nishimoto＊＊｝.");
    Character_ChFace(0, 0, 11);
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("G0112010_L00300", #1, "G0112010_L00301");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Huh? ｛主人公｝...\nYour lips are a bit cracked, you\nknow.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh, really?");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("G0112010_L00400", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I'll lend you my lip balm.\nYou can just get it.\nIt's inside my bag.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay, thank you.");
    Character_BlinkStart(12, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("G0112010_L00500", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Oh yeah, I need to call home to tell\nthem I'm going to be 　late.\nI'll be back!");
    Message_CloseMsg();
    Screen_WipeOut(8);
    SoundEffect_PlayStream(3, "SS_DSE_069_000");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Umm, I wonder where's the lip\nbalm...\nIt's inside this make-up pouch.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Oh... Something dropped.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? Is this...\n｛Hariya＊＊｝'s\npicture...!?)");
    Character_ChFace(0, 0, 11);
    Screen_WipeIn(2);
    Voice_PlayVoice("G0112010_L00600", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "......!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh... ｛Nishimoto＊＊｝!");
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("G0112010_L00700", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "......");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ummm...\nI accidentally saw the picture.\nI'm sorry... okay?");
    Character_ChFace(0, 0, 8);
    Character_BlinkStart(12, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("G0112010_L00800", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "... It's not what you think it is...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?");
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("G0112010_L00900", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "It's not like I like him!\nHonestly...!");
    Message_MsgSel("I think you guys would hit it off great...", "(Could she be my rival...?)");
    switch (Message_TextSelect()){
        case 0:
        Message_Who(0);
        Message_MsgDisp("主人公", "I think you guys would hit it off\ngreat...");
        Character_ChFace(0, 0, 11);
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("G0112010_L01000", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Huh...?");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Nishimoto＊＊｝ and\n｛Hariya＊＊｝.");
        Character_BlinkStart(12, 2, (#1));
        Voice_PlayVoice("G0112010_L01100", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "... You really think so...?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Y-Yeah.");
        Character_ChFace(0, 0, 10);
        Character_BlinkStart(12, 3, (#1));
        Character_ChFace(0, 4, 1);
        Voice_PlayVoice("G0112010_L01200", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "... I see. In that case, it's fine.");
        Character_BlinkStart(12, 0, (#1));
        Voice_PlayVoice("G0112010_L01300", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Ahaha, I'm sorry, okay?\nSuch a great misunderstanding...\nYeah.");
        Character_ChFace(0, 4, 0);
        Character_ChFace(0, 0, 3);
        Voice_PlayVoice("G0112010_L01400", #1, "");
        Message_Who(12);
        Message_MsgDisp("Nishimoto", "Now, let's go.");
        Music_StopBGM(0, 40);
        Message_Who(0);
        Message_MsgDisp("主人公", "(Might be my first time seeing\n｛Nishimoto＊＊｝ like that...)");
        Parameter_InCh1Param(12, 513, 0);
        break ;
        case 1:
        Music_StopBGM(0, 40);
        Message_CloseMsg();
        Screen_WipeOut(8);
        SoundEffect_PlayStream(3, "SS_DSE_060_000");
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh, ｛Nishimoto＊＊｝...!!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Might be my first time seeing\n｛Nishimoto＊＊｝ like that...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(So ｛Nishimoto＊＊｝ is really\ninto ｛Hariya＊＊｝...?)");
        break ;
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(12, 86, 1);
    }
