section "g02_g1_000"{
    Background_Bg_GS2("BG_SC100_?_1", 1, #1, 0);
    Screen_WipeIn(2);
    if (Parameter_GetPl1Param(25) == 1){
        Message_Who(0);
        Message_MsgDisp("主人公", "(Oh, it's...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Toudou＊＊｝!");
        Character_Chara_GS2(10, "G1_02F", 0);
        Music_PlayBGM(0, "MN_C_10_000_D00", 127, 40);
        Message_Who(10);
        Message_MsgDisp("Toudou", "... ｛主人公｝.");
        Character_Chara_GS2(10, "NON");
        Character_Chara_GS2(10, "G1_01F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "Are you heading home?\nOh, ｛Shiba＊＊｝'s here,\ntoo.");
        Character_Chara_GS2(2, "M2_02F", 0, 0, 1);
        Voice_PlayVoice("G0210000_B00100", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Yeah.");
        Message_Who(0);
        Message_MsgDisp("主人公", ".........");
        Message_Who(10);
        Message_MsgDisp("Toudou", ".........");
        Message_Who(2);
        Message_MsgDisp("Shiba", ".........");
        Message_Who(0);
        Message_MsgDisp("主人公", "...... Umm...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, if it's okay with you two, can\nI join you heading home?");
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 0);
        Voice_PlayVoice("G0210000_B00400", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Sorry.\nWe are going somewhere from here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Really?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("G0210000_J00500", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Sport shop.\nShiba needs to buy something for his\nclub.");
        Character_ChFace(1, 0, 3);
        Character_BlinkStart(10, 3, (#1));
        Voice_PlayVoice("G0210000_J00600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I'm a bag carrier.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Bag carrier? ｛Toudou＊＊｝?");
        Character_BlinkStart(10, 2, (#1));
        Voice_PlayVoice("G0210000_J00700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I'm interested in the things he\nuses.\nI'll buy some myself.");
        Character_BlinkStart(10, 3, (#1));
        Voice_PlayVoice("G0210000_B00800", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Toudou.\nWe have to get going or the shop\nwill be closed.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("G0210000_J00900", #1, "G0210000_J00901");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Yeah, I guess.\nWell, ｛主人公｝, see\nyou.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, okay...");
        Character_BlinkStart(10, 0, (#1));
        Message_Who(2);
        Message_MsgDisp("Shiba", "......");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(10, "NON");
        Character_Chara_GS2(2, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I never got the chance to join...)");
        }
    else {
        Message_Who(0);
        Message_MsgDisp("主人公", "(Oh, that's...)");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Toudou＊＊｝!");
        Character_Chara_GS2(10, "G1_02F", 0);
        Music_PlayBGM(0, "MN_C_10_000_D00", 127, 40);
        Message_Who(10);
        Message_MsgDisp("Toudou", "..... ｛主人公｝.");
        Character_Chara_GS2(10, "NON");
        Character_Chara_GS2(10, "G1_01F", 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "Heading home?\nAh, ｛Shiba＊＊｝'s here,\ntoo.");
        Character_Chara_GS2(2, "M2_02F", 0, 0, 1);
        Voice_PlayVoice("G0210000_B01200", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "..... Yeah.");
        Message_Who(0);
        Message_MsgDisp("主人公", ".........");
        Message_Who(10);
        Message_MsgDisp("Toudou", ".........");
        Message_Who(2);
        Message_MsgDisp("Shiba", ".........");
        Message_Who(0);
        Message_MsgDisp("主人公", "... Umm...");
        Message_Who(0);
        Message_MsgDisp("主人公", "Umm, if it's okay with you two, can\nI join you heading home?");
        Character_ChFace(1, 2, 2);
        Character_ChFace(1, 3, 0);
        Voice_PlayVoice("G0210000_B01500", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Sorry.\nWe are going somewhere from here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Really?");
        Character_ChFace(0, 2, 0);
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("G0210000_J01600", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Sports shop.\nShiba needs to buy something for his\ntraining session.");
        Character_ChFace(1, 0, 3);
        Character_BlinkStart(10, 3, (#1));
        Voice_PlayVoice("G0210000_J01700", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I'm the bag carrier.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Bag carrier? ｛Toudou＊＊｝?");
        Character_BlinkStart(10, 2, (#1));
        Voice_PlayVoice("G0210000_J01800", #1, "");
        Message_Who(10);
        Message_MsgDisp("Toudou", "I'm interested in the things he\nuses.\nI'll buy some myself.");
        Character_BlinkStart(10, 3, (#1));
        Voice_PlayVoice("G0210000_B01900", #1, "");
        Message_Who(2);
        Message_MsgDisp("Shiba", "... Toudou.\nWe need to get going or the shop\nwill be closed.");
        Character_ChFace(0, 0, 10);
        Voice_PlayVoice("G0210000_J02000", #1, "G0210000_J02001");
        Message_Who(10);
        Message_MsgDisp("Toudou", "Yeah, I guess.\nWell, ｛主人公｝, see\nyou.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Yeah, okay...");
        Character_BlinkStart(10, 0, (#1));
        Message_Who(2);
        Message_MsgDisp("Shiba", "......");
        Music_StopBGM(0, 40);
        Character_Chara_GS2(10, "NON");
        Character_Chara_GS2(2, "NON");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I never got the chance to join...)");
        }
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(10, 86, 1);
    Parameter_AddCh1Param(10, 86, 1);
    }
