section "g02_g2_000"{
    Background_Bg_GS2("BG_SC212_CO_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? It's...)");
    Voice_PlayVoice("G0211000_C00000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "... It leads to that interpretation.\nIt is desirable to include some\nimprovement at this point.");
    Voice_PlayVoice("G0211000_K00100", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Yes, that is true.\nNonetheless, the problem is\nparagraph eight.\nI think it causes misunderstandings.");
    Voice_PlayVoice("G0211000_C00200", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Yes, exactly!\nLet us discuss it right away.\nYou are easy to talk to.\nIt's a big help.");
    Character_Chara_GS2(11, "G2_01F", 0);
    Music_PlayBGM(0, "MN_C_11_000_D00", 127, 40);
    Voice_PlayVoice("G0211000_K00300", #1, "G0211000_K00301");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Oh.... ｛主人公｝.\nGood afternoon.");
    Character_Chara_GS2(3, "M3_01F", 0, 0, 1);
    Voice_PlayVoice("", 3, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, what's up? You're so serious.");
    Character_ChFace(1, 2, 1);
    Character_BlinkStart(11, 3, (#1));
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("G0211000_C00400", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "That's obvious.\nIt is important and required for a\npressing matter.");
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("G0211000_K00500", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "It's about reforming the school\nrules.\nHikami-kun and I are weighing it.\nThere are still a lot of problems.");
    Message_Who(0);
    Message_MsgDisp("主人公", "*Sigh* Is that so?");
    Character_BlinkStart(11, 1, (#1));
    Character_ChFace(1, 3, 0);
    Voice_PlayVoice("G0211000_C00600", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "The school rules also require quick\nresponses with the demands.\nWe must always raise a question.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm......\nIn brief, what you mean to say is...");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("G0211000_K00700", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Exactly.\nThis may seem futile, but\nregardless, you should continue to\nmake an effort!");
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("G0211000_C00800", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "Onoda-kun, you are right!\nThat road may be tough.\nHowever, someone has to be inclined\nto do so.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("G0211000_K00900", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Yes!\nI'll always follow you wherever you\ngo!");
    Character_ChFace(1, 2, 4);
    Character_BlinkStart(11, 2, (#1));
    Character_ChFace(1, 4, 1);
    Voice_PlayVoice("G0211000_C01000", #1, "");
    Message_Who(3);
    Message_MsgDisp("Hikami", "I-I see... Very well!\nLet us assemble a special meeting\nright away.\nCome, Onoda-kun!");
    Character_ChFace(0, 2, 1);
    Voice_PlayVoice("G0211000_K01100", #1, "");
    Message_Who(11);
    Message_MsgDisp("Onoda", "Yes!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(11, "NON");
    Character_Chara_GS2(3, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "... They're gone.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Those two look good together.\nI feel left out...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(11, 86, 1);
    Parameter_AddCh1Param(11, 86, 1);
    }
