section "g02_g3_000"{
    Background_Bg_GS2("BG_SC212_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh, I hear voices from the\nclassroom at this hour...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(12, "NON");
    Character_Chara_GS2(12, "G3_01F", 0);
    Character_Chara_GS2(4, "M4_01F", 0, 0, 1);
    Music_PlayBGM(0, "MN_C_12_000_D00", 127, 40);
    Background_Bg_GS2("BG_SC302_CO_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hariya＊＊｝ and\n｛Nishimoto＊＊｝?)");
    Character_ChFace(1, 0, 10);
    Voice_PlayVoice("G0212000_D02200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Well, let's go!");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("G0212000_L00000", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Sheesh, that's obvious!\nAre you okay in this state?");
    Character_ChFace(1, 2, 1);
    Character_ChFace(1, 3, 5);
    Voice_PlayVoice("G0212000_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "What are you saying?\nI'm the one who's gonna do it.\nIt's supposed to be alright!");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(12, 2, (#1));
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("G0212000_L00200", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "... Yeah, I guess.\nSince it's you, Harry, you're gonna\nbe fine.");
    Character_ChFace(1, 2, 4);
    Character_BlinkStart(12, 2, (#1));
    Character_ChFace(1, 3, 0);
    Voice_PlayVoice("G0212000_D00300", 4, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Oh, ｛主人公｝.");
    Character_ChFace(0, 4, 0);
    Character_BlinkStart(12, 0, (#1));
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("", #1, "G0212000_L00400");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "｛主人公｝...!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh... I'm sorry, I heard you guys.\nAre you guys going somewhere?");
    Character_ChFace(1, 0, 10);
    Voice_PlayVoice("G0212000_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah, we're holding a street live\nafter this.\nIt's her idea.");
    Character_ChFace(1, 2, 2);
    Character_ChFace(1, 3, 5);
    Character_ChFace(1, 4, 1);
    Voice_PlayVoice("G0212000_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Amazing...\nI feel like I'm getting nervous.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("G0212000_L00700", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Of course you are in that condition.");
    Character_ChFace(1, 0, 8);
    Character_ChFace(1, 4, 1);
    Voice_PlayVoice("G0212000_D00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Hey! Why you--!");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("G0212000_L00900", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "I'm kidding, I'm kidding, it's just\na joke!\nHey, we have to get going or the day\nwill change before we know it!");
    Character_ChFace(1, 4, 0);
    Character_ChFace(1, 3, 2);
    Voice_PlayVoice("G0212000_D01000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It won't change that fast!");
    Character_ChFace(1, 0, 9);
    Character_BlinkStart(12, 3, (#1));
    Voice_PlayVoice("G0212000_D01100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nThis annoying wannabe manager is a\nbit harsh.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Manager?");
    Character_BlinkStart(12, 0, (#1));
    Character_ChFace(1, 3, 5);
    Voice_PlayVoice("G0212000_D01200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "A wannabe, a wannabe.\nI wouldn't be waiting if you had\njust properly managed it.");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("G0212000_L01300", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "That's mean!");
    Character_ChFace(1, 2, 1);
    Character_ChFace(1, 3, 3);
    Voice_PlayVoice("G0212000_D01400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It's the truth anyway～.");
    Character_ChFace(1, 0, 10);
    Voice_PlayVoice("G0212000_D01500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I'd say, if you want to get praised,\nyou better manage well.\nLike major high-level management.");
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("G0212000_L01600", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "... My hopes are high!");
    Character_BlinkStart(12, 3, (#1));
    Voice_PlayVoice("G0212000_L01700", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Eventually, Harry will ask me～, with\na bow.");
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("G0212000_D01800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah, yeah.\nDon't hope for it, that'll have to\nwait.");
    Character_BlinkStart(12, 0, (#1));
    Character_ChFace(0, 2, 3);
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("G0212000_L01900", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Oh, we don't have much time left.\nLet's go! Hurry!");
    Character_ChFace(1, 0, 10);
    Voice_PlayVoice("G0212000_D02000", 4, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah.\nWell then, see ya,\n｛主人公｝.");
    Character_ChFace(0, 0, 3);
    Character_BlinkStart(12, 2, (#1));
    Voice_PlayVoice("G0212000_L02100", #1, "");
    Message_Who(12);
    Message_MsgDisp("Nishimoto", "Let's chat again sometime! Bye!");
    Music_StopBGM(0, 40);
    Character_Chara_GS2(12, "NON");
    Character_Chara_GS2(4, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Seems like those two share the same\nwavelength...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Screen_ClearScreen();
    Parameter_AddCh1Param(12, 86, 1);
    Parameter_AddCh1Param(12, 86, 1);
    }
