section "r08_m1_010"{
    if (Parameter_GetPl1Param(26) != 1){
        Background_Bg_GS2("BG_BK000_CO_0", #1, #1, 0);
        Screen_WipeIn(2);
        SoundEffect_PlayStream(2, "EV_SE_579");
        Message_Who(0);
        Message_MsgDisp("主人公", "Huh... My phone...?");
        SoundEffect_StopStream(2, 0);
        SoundEffect_PlaySE(20, 127);
        Voice_PlayVoice("R0801010_A00000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Hello? It's me.");
        Message_Who(0);
        Message_MsgDisp("主人公", "... ｛Saeki＊＊｝!?\nWhat's wrong?");
        Voice_PlayVoice("R0801010_A00100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Were you sleeping?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Of course I was! \nI mean, it's now...4 o'clock!?");
        Voice_PlayVoice("R0801010_A00200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Right. Well, whatever.\nOpen your window and go out to the\nbalcony.");
        Message_Who(0);
        Message_MsgDisp("主人公", "??? \nWhy?");
        Voice_PlayVoice("R0801010_A00300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Just do it. Hurry.");
        SoundEffect_PlaySE(20);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        SoundEffect_PlayStream(3, "SS_T_00_109_M00");
        Still_Event("EV_01_27", #1, 0, 60);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ugh～! It's freezing!\nSeriously, what is it...?");
        SoundEffect_PlayStream(2, "SEQ_SE_EV_002");
        System_Wait(10);
        Voice_PlayVoice("R0801010_A00400", #1, "");
        Message_Who(1);
        Message_MsgDisp("？？？", "Up... and over!");
        Message_Who(0);
        Message_MsgDisp("主人公", "...!?");
        Still_Event("EV_01_16", #1, 1, 60);
        Music_PlayBGM(0, "MN_X_00_R08_D00", 127, 40);
        Still_Approach(1, 14, 0, 0, 1, 1);
        Voice_PlayVoice("R0801010_A00500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Yo.");
        Still_ApproachEnd();
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝!\nWhat in the world!?\nI thought you were a thief!");
        Still_StillFace(0, 6, 2);
        Voice_PlayVoice("R0801010_A00600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It's Christmas, isn't it?\nObviously, I'm Santa.");
        Message_Who(0);
        Message_MsgDisp("主人公", ".........");
        Still_StillFace(0, 6, 3);
        Still_StillFace(0, 6, 0);
        Voice_PlayVoice("R0801010_A00700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "The main entrance was locked.\nBesides, I've always wanted to try \na movie-style entrance like this.\"");
        Message_Who(0);
        Message_MsgDisp("主人公", "Geez. Why does everything you do \nhave to be so extreme...?");
        Voice_PlayVoice("R0801010_A00800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Stop grumbling.\nI came all this way to bring you a present,\nyou know.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Oh... \nThank you.");
        Still_StillFace(0, 6, 2);
        Voice_PlayVoice("R0801010_A00900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Yeah... \nMerry Christmas.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Merry Christmas.\n...I'm sorry.\nI don't have a present for you.");
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("R0801010_A01000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It's fine.\nI got to see your face, so I'll let\nit slide.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...I don't know,｛Saeki＊＊｝.\nYou're being a lot nicer than usual today.");
        Still_StillFace(0, 6, 2);
        Voice_PlayVoice("R0801010_A01100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Is that so?");
        Message_Who(0);
        Message_MsgDisp("主人公", "And... you seem kind of down. \nDuring the day, you were so full of energy, \nsaying how busy the shop was.");
        Still_StillFace(0, 0, 1);
        Still_StillFace(0, 6, 2);
        Voice_PlayVoice("R0801010_A01200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Ah, the shop.\n...Yeah.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...?\nDid something happen at Sangosho?");
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("R0801010_A01300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "The shop closed down tonight.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Eh!?  But... so suddenly...?");
        Still_StillFace(0, 0, 0);
        Still_StillFace(0, 6, 3);
        Still_StillFace(0, 6, 0);
        Voice_PlayVoice("R0801010_A01400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Yeah....\nGrandpa said he decided on this \na long time ago.");
        Message_Who(0);
        Message_MsgDisp("主人公", "But still!\n｛Saeki＊＊｝, you've done so much for \nSangosho up until-");
        Still_StillFace(0, 0, 1);
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("R0801010_A01500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Keep your voice down. You'll wake everyone\nup. It's alright. \nI'm doing better than I thought.");
        Still_Approach(1, 14, 0, 0, 1, 5);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝...");
        Still_ApproachEnd();
        Still_StillFace(0, 0, 0);
        Still_StillFace(0, 6, 2);
        Voice_PlayVoice("R0801010_A01600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I should go. I have a taxi waiting.\n...Goodnight.");
        Still_Event("EV_01_27", #1, 0, 60);
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Saeki＊＊｝... \nThere's no way you're fine... )");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Music_StopBGM(0, 40);
        Screen_ClearScreen();
        Parameter_InCh1Param(1, 551, 56);
        }
    else {
        System_GlobalWork(3, 0, 1);
        Background_Bg_GS2("BG_SC820_WI_2", #1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(The party is quite lively!\n｛Saeki＊＊｝ should have come.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(I bet he's running all over the shop \nright about now...\n...I'll give him a quick call!)");
        SoundEffect_PlaySE(21, 127);
        System_Wait(#300);
        SoundEffect_StopSE(21, 0);
        Message_Who(0);
        Message_MsgDisp("主人公", "Hello? ｛Saeki＊＊｝?\nMerry Christmas!");
        Voice_PlayVoice("R0801010_A01700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Huh? \nAh, it's you.");
        Message_Who(0);
        Message_MsgDisp("主人公", "How is it?\nIs the shop super busy?");
        Voice_PlayVoice("R0801010_A01800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Eh? No, ah... Yeah....");
        Message_Who(0);
        Message_MsgDisp("主人公", "...Is something wrong?\nYou sound a little off.");
        Voice_PlayVoice("R0801010_A01900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "It's nothing.\nDon't worry about things over here.\nBye.");
        SoundEffect_PlaySE(330, 127);
        System_Wait(30);
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Saeki＊＊｝!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(Something might have happened.\n｛Saeki＊＊｝ always acts so tough...\nThe trains are still running right now...\nOkay!)");
        Message_Who(0);
        Message_MsgDisp("主人公", "Excuse me, Sensei!\nSomething urgent came up, so--");
        SoundEffect_PlayStream(2, "SS_T_00_004_M00");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Background_Bg_GS2("BG_BH110_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "(*Phew*... I made it in time!\nLooks like the shop is still open.)");
        Message_Who(0);
        Message_MsgDisp("主人公", "(... Huh? But, it's kind of quiet...)");
        Voice_PlayVoice("R0801010_A02000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "But, even you, Grandpa, you were working \nso hard! I can't just accept this!");
        Message_Who(0);
        Message_MsgDisp("主人公", "(｛Saeki＊＊｝!?)");
        Voice_PlayVoice("R0801010_P02100", #1, "");
        Message_Who(16);
        Message_MsgDisp("Master", "My mind is made up. The shop will close \nfor good tonight. \nGive it up.");
        Message_Who(0);
        Message_MsgDisp("主人公", "(The shop... No way...)");
        SoundEffect_PlayStream(3, "SS_T_00_210_M00");
        System_Wait(30);
        SoundEffect_PlayStream(2, "SS_T_00_129_M00");
        Character_ChFace(0, 0, 11);
        Character_Chara_GS2(1, "M1_13F", 0);
        Voice_PlayVoice("R0801010_A02200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "!!");
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 4, 1);
        System_Wait(30);
        Character_Chara_GS2(1, "NON");
        SoundEffect_PlayStream(3, "SS_T_00_068_M00");
        Message_Who(0);
        Message_MsgDisp("主人公", "Ah, ｛Saeki＊＊｝!!");
        Message_CloseMsg();
        Environment_StopME(1, 40);
        Screen_WipeOut(2);
        Character_Chara_GS2(1, "NON");
        Background_Bg_GS2("BG_AR101_CO_2", #1, #1, 0);
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Character_Chara_GS2(16, "S3_17F", 0);
        Screen_WipeIn(2);
        Voice_PlayVoice("R0801010_P02300", #1, "");
        Message_Who(16);
        Message_MsgDisp("Master", "Oh. What brings you here at this time \nof night...?");
        Message_Who(0);
        Message_MsgDisp("主人公", "I called ｛Saeki＊＊｝ and he sounded \na bit off, so...");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("R0801010_P02400", #1, "");
        Message_Who(16);
        Message_MsgDisp("Master", "Thank you.\nYou came because you were worried\nabout him, didn't you?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Are you really closing the shop?");
        Character_ChFace(0, 2, 0);
        Character_BlinkStart(1, 3, (#1));
        Character_ChFace(0, 3, 2);
        Voice_PlayVoice("R0801010_P02500", #1, "");
        Message_Who(16);
        Message_MsgDisp("Master", "Did you overhear that...?\n...Yes. \nTonight is the end for Sangosho.");
        Message_Who(0);
        Message_MsgDisp("主人公", "But why all of a sudden...");
        Character_BlinkStart(1, 0, (#1));
        Voice_PlayVoice("R0801010_P02600", #1, "");
        Message_Who(16);
        Message_MsgDisp("Master", "Just the whims of an old man...\nI know I'm letting you both down after\nhow much you've helped me here.\nI'm truly sorry.");
        Message_Who(0);
        Message_MsgDisp("主人公", "But... I don't think ｛Saeki＊＊｝ can \njust let it go...");
        Character_ChFace(0, 2, 2);
        Character_ChFace(0, 3, 0);
        Voice_PlayVoice("R0801010_P02700", #1, "");
        Message_Who(16);
        Message_MsgDisp("Master", "No, you're right...\nI have no right to ask this of you, but... \ncould you go after him?");
        Character_ChFace(0, 3, 3);
        Voice_PlayVoice("R0801010_P02800", #1, "");
        Message_Who(16);
        Message_MsgDisp("Master", "He's never learned how to lean on people.\nHe acts tough, but... he isn't as strong\nas he looks.\nI'll finish locking up here.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Okay.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Character_Chara_GS2(16, "NON");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Background_Bg_GS2("BG_BH111_CO_2", #1, #1, 0);
        Screen_WipeIn(2);
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝.");
        Character_BlinkStart(1, 3, (#1));
        Character_ChFace(0, 0, 9);
        Character_ChFace(0, 3, 1);
        Character_Chara_GS2(1, "M1_13F", 0);
        Message_Who(1);
        Message_MsgDisp("Saeki", "..........");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hey, ｛Saeki＊＊｝.");
        Character_ChFace(0, 7, 0);
        Character_ChFace(0, 0, 9);
        Character_BlinkStart(1, 2, (#1));
        Voice_PlayVoice("R0801010_A03000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "...What is it?");
        Message_Who(0);
        Message_MsgDisp("主人公", "Are you alright?\nIf there's anything I can do--");
        Character_BlinkStart(1, 3, (#1));
        Voice_PlayVoice("R0801010_A03100", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I'm fine, really.");
        Message_Who(0);
        Message_MsgDisp("主人公", "But... you don't exactly look fine...");
        Character_BlinkStart(1, 2, (#1));
        Voice_PlayVoice("R0801010_A03200", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Then... Your lap.");
        Message_Who(0);
        Message_MsgDisp("主人公", "My lap?");
        Character_BlinkStart(1, 3, (#1));
        Voice_PlayVoice("R0801010_A03300", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Let me use your lap.");
        Message_CloseMsg();
        Screen_WipeOut(2);
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Still_Event("EV_01_17", #1, 0, 0);
        Screen_WipeIn(2);
        Music_PlayBGM(0, "MN_Z_00_003_D00_B", 127, 40);
        Voice_PlayVoice("R0801010_A03400", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "This feels nice.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...Yeah? I'm glad.");
        Voice_PlayVoice("R0801010_A03500", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I knew, you know. \nI was just pretending not to notice.");
        Message_Who(0);
        Message_MsgDisp("主人公", "...?");
        Still_StillFace(0, 0, 1);
        Still_StillFace(0, 6, 2);
        Voice_PlayVoice("R0801010_A03600", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Grandpa never said it out loud,\nbut he saw how overwhelmed I was.\nHe couldn't stand to watch it anymore. \nThat's why...");
        Message_Who(0);
        Message_MsgDisp("主人公", "(So that's what happened...)");
        Still_StillFace(0, 0, 0);
        Still_StillFace(0, 6, 1);
        Voice_PlayVoice("R0801010_A03700", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Hey...\nDid I really do everything I could?");
        Message_Who(0);
        Message_MsgDisp("主人公", "｛Saeki＊＊｝, you did your\nbest.");
        Voice_PlayVoice("R0801010_A03800", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "I see.\n.....Just a little longer.");
        Message_Who(0);
        Message_MsgDisp("主人公", "Hmm?");
        Voice_PlayVoice("R0801010_A03900", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Just a little longer like this.\nI'm a little... tired.");
        Message_Who(0);
        Message_MsgDisp("主人公", "It's okay.\nJust rest for a while.");
        Still_StillFace(0, 0, 1);
        Still_StillFace(0, 6, 1);
        Still_Approach(1, 15, 0, 0, 1, 1);
        Voice_PlayVoice("R0801010_A04000", #1, "");
        Message_Who(1);
        Message_MsgDisp("Saeki", "Yeah... Merry Christmas.\nI'm glad you're here with me.");
        Still_ApproachEnd();
        Message_Who(0);
        Message_MsgDisp("主人公", "(Merry Christmas,\n｛Saeki＊＊｝...)");
        Message_Who(0);
        Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
        Message_CloseMsg();
        Screen_WipeOut(1);
        Music_StopBGM(0, 40);
        Screen_ClearScreen();
        Parameter_InCh1Param(1, 551, 57);
        }
    Parameter_AddCh1Param(1, 86, 1);
    Parameter_AddCh1Param(1, 61, 5);
    Parameter_AddCh1Param(1, 60, 3);
    Parameter_AddCh1Param(1, 62, #5);
    Parameter_InCh1Param(1, 544, 49);
    }
