section "r08_m4_000"{
    System_GlobalWork(3, 0, 4);
    Background_Bg_GS2("BG_SC820_WI_2", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh...?\nI haven't seen ｛Hariya＊＊｝\naround.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He said that he'd sing a Christmas\ncarol for everyone, too...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I wonder where he went...\nMaybe he's outside?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Background_Bg_GS2("BG_SC830_WI_2", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(He's not here... Then...\nmaybe he's in the lodge?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(He's not here, either...\nAh, stairs. Maybe he's... upstairs?)");
    Voice_PlayVoice("", 4, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh......");
    Environment_StopME(0, 40);
    Still_Event("EV_04_14", #1, 0, 60);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_X_00_R08_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝...!");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("R0804000_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Yo.\nWhat are you doing all the way up\nhere?");
    Message_Who(0);
    Message_MsgDisp("主人公", "I can ask the same about you,\n｛Hariya＊＊｝...\nYou'll catch a cold if you stay\nhere.");
    Still_StillFace(0, 0, 0);
    Voice_PlayVoice("R0804000_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... I've got a habit.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What?");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("R0804000_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "When I start to get nervous, I look\nfor a place where I can be alone.");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("R0804000_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "You've heard me many times, so you\nunderstand.");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("R0804000_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I'm really good at singing when I'm\nalone, right?\nSo--");
    Voice_PlayVoice("R0804000_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "I was convinced that things would go\nwell somehow if I were alone.");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("R0804000_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... But...");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("R0804000_D00700", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "It's actually the opposite.\nAll I did was corner myself.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝...");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("R0804000_D00800", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Having someone in the audience to\nsupport and encourage me...");
    Still_StillFace(0, 0, 1);
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("R0804000_D00900", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Looking at you, I've realized\nsomething.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh? Me?");
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("R0804000_D01000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah.");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("R0804000_D01100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Thanks to you, I'm unbelievably\nrelaxed....\nThat's a first.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝...");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("R0804000_D01200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Sorry for making you worry.\nIt's almost my turn to sing, right?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yes. I came here to get you.");
    Still_Approach(4, 102, 0, 0, 1, 1);
    Voice_PlayVoice("R0804000_D01300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Haha. Don't forget.");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 2);
    Voice_PlayVoice("R0804000_D01400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "...\nYou have to stand at the very front\nand watch me.");
    Still_StillFace(0, 6, 1);
    Voice_PlayVoice("R0804000_D01500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "My song is yours.\nSince it's Christmas, it'll be\nspecial.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Hariya＊＊｝...");
    Still_StillFace(0, 6, 0);
    Voice_PlayVoice("R0804000_D01600", 4, "R0804000_D01601");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Thanks, ｛主人公｝.\nMerry Christmas.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Merry Christmas,\n｛Hariya＊＊｝.");
    Message_CloseMsg();
    Screen_WipeOut(1);
    Still_Event("");
    Music_StopBGM(0, 40);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    Parameter_AddCh1Param(4, 61, 5);
    Parameter_AddCh1Param(4, 60, 3);
    Parameter_AddCh1Param(4, 62, #5);
    }
