section "r08_m6_000"{
    System_GlobalWork(3, 0, 6);
    Background_Bg_GS2("BG_SC820_WI_2", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh?\nIs that ｛Amachi＊＊｝...\nover there?)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Amachi＊＊｝!\nWhat are you doing here? Alone?");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(6, "M6_12F", 0);
    Voice_PlayVoice("R0806000_F00000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Watching the snow.");
    Message_Who(0);
    Message_MsgDisp("主人公", "The snow?");
    Environment_StopME(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("EV_06_13", #1, 0, 60, 1);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_X_00_R08_D00", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah, it's true...\nIt'll most likely be a White\nChristmas tomorrow.");
    Still_Approach(6, 161, 0, 0, 1, 1);
    Voice_PlayVoice("R0806000_F00100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Maybe.\nI like seeing snow, but I hate the\ncold.");
    Still_ApproachEnd();
    Still_StillFace(0, 6, 2, 1);
    Voice_PlayVoice("R0806000_F00200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I've been watching it fall for a\nlong time now.\nSince I was a child.");
    Still_StillFace(0, 6, 0, 1);
    Voice_PlayVoice("R0806000_F00300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "My sister is usually amazed that I\ncan watch without getting tired.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Teehee... Is that right?");
    Voice_PlayVoice("R0806000_F00400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Yeah.");
    Voice_PlayVoice("R0806000_F00500", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I love the beginning the most.\nWhen the snow isn't stepped on by\nanyone.");
    Still_StillFace(0, 6, 1, 1);
    Voice_PlayVoice("R0806000_F00600", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "It's so gentle and pure white...");
    Still_StillFace(0, 6, 0, 1);
    Voice_PlayVoice("R0806000_F00700", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "... Senpai is like the snow.");
    Message_Who(0);
    Message_MsgDisp("主人公", "What?");
    Voice_PlayVoice("R0806000_F00800", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "I meant me watching the snow without\ngetting tired.");
    Message_Who(0);
    Message_MsgDisp("主人公", "I see...");
    Still_Event("EV_06_18", #1, 1, 60, 1);
    Voice_PlayVoice("R0806000_F00900", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Ahaha. Senpai nods obediently.");
    Still_StillFace(0, 6, 2, 1);
    Voice_PlayVoice("R0806000_F01000", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "You don't understand that I was\nmaking fun of you.\nYou agree without thinking about it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh? You were making fun of me?");
    Still_StillFace(0, 6, 0, 1);
    Voice_PlayVoice("R0806000_F01100", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "In a way, I guess?\nHowever, isn't what I said about why\nI love the snow true?");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Amachi＊＊｝...");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Character_ChFace(0, 3, 3);
    Character_Chara_GS2(6, "M6_12F", 0);
    Background_Bg_GS2("BG_SC820_WI_2", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("R0806000_F01200", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Oh, the dessert came out.\nLet's go eat, Senpai.");
    Voice_PlayVoice("R0806000_F01300", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "It'll be gone if we don't hurry!");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's okay, you don't have to panic\nso much.");
    Character_ChFace(0, 2, 1);
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("R0806000_F01400", #1, "");
    Message_Who(6);
    Message_MsgDisp("Amachi", "Please don't say such a thing,\nSenpai!\nDon't be so responsible, just eat!");
    Message_Who(0);
    Message_MsgDisp("主人公", "*Giggles* Then let's hurry.");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(6, 86, 1);
    Parameter_AddCh1Param(6, 61, 5);
    Parameter_AddCh1Param(6, 60, 3);
    Parameter_AddCh1Param(6, 62, #5);
    }
