section "r08_m8_000"{
    Background_Bg_GS2("BG_NE100_LI_1", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Huh? That person running is...)");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Masaki＊＊｝!");
    Character_ChFace(0, 0, 11);
    Character_Chara_GS2(8, "M8_01F", 0);
    Voice_PlayVoice("R0808000_H00000", 8, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Oi! ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Are you making a delivery?");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(8, 2, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("R0808000_H00100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah...\nWe're getting many customers and\ncalls.\nI don't know if I can get a chance\nto eat...");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("R0808000_H00200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "You've got that thing, don't you?\nHanegasaki's famous ski camp.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes!");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(8, 2, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("R0808000_H00300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Sounds nice...\nYou get to have such a fun event\nduring the busy period...");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ugh... Sorry...");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("R0808000_H00400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I'm kidding, I'm kidding.");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(8, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("R0808000_H00500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "It's the one big event during high\nschool, so enjoy it!\nIt'll definitely become a good\nmemory for you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.");
    Character_ChFace(0, 2, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("R0808000_H00600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Oh～. Nice response.");
    Character_ChFace(0, 0, 6);
    Character_ChFace(0, 4, 0);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("R0808000_H00700", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Screwing around is okay, but make\nsure you don't get hurt.\nLater～.");
    Character_Chara_GS2(8, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(He left...\n｛Masaki＊＊｝ looks really\ntired.)");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Hmm... I'm a little worried.\nI'll go check out the store to see\nwhat things are like.)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_AR500_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "(Wow! It's really busy!)");
    Voice_PlayVoice("R0808000_Q00800", #1, "");
    Message_Who(17);
    Message_MsgDisp("Arisawa", "Welcome... Ah.");
    Message_Who(0);
    Message_MsgDisp("主人公", "You're working hard...\nT-This is amazing...");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(8, 2, (#1));
    Character_Chara_GS2(17, "G5_01F", 0);
    Voice_PlayVoice("R0808000_Q00900", #1, "");
    Message_Who(17);
    Message_MsgDisp("Arisawa", "Yes, we are busier than I had\nanticipated....\nAre you free right now?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, yes.");
    Voice_PlayVoice("R0808000_Q01000", #1, "");
    Message_Who(17);
    Message_MsgDisp("Arisawa", "I'd be glad if you could help out a\nlittle...\nWelcome!");
    Character_Chara_GS2(17, "NON");
    Message_Who(0);
    Message_MsgDisp("主人公", "(Help out, huh...\nI still have time, so it's alright\nfor me to help out a bit, right?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_Bg_GS2("BG_AR500_LI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Voice_PlayVoice("R0808000_H01100", #1, "");
    Message_Who(8);
    Message_MsgDisp("？？？", "I've returned～!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, ｛Masaki＊＊｝.\nWelcome back.");
    Character_BlinkStart(8, 2, (#1));
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Character_Chara_GS2(8, "M8_01F", 0);
    Voice_PlayVoice("R0808000_H01200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Thanks...");
    Character_ChFace(0, 2, 1);
    Character_BlinkStart(8, 0, (#1));
    Character_ChFace(0, 3, 4);
    Voice_PlayVoice("R0808000_H01300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... That's not right!\nWhat the hell are you doing here!?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Umm, the store seemed busy so I was\nhelping out...");
    Character_ChFace(0, 2, 2);
    Character_BlinkStart(8, 3, (#1));
    Character_ChFace(0, 3, 1);
    Voice_PlayVoice("R0808000_H01400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Helping out...\nWhy are you so careless...?\nYou're late!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah! You're right!\nIt's already getting late...");
    Character_ChFace(0, 0, 8);
    Voice_PlayVoice("R0808000_H01500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "*Sigh* ......... Arisawa!\nI'm gonna drive her to Mt. Habataki.\nAre things okay here?");
    Character_Chara_GS2(8, "NON");
    Character_ChFace(1, 0, 8);
    Character_Chara_GS2(8, "M8_01F", 0, 0, 1);
    Character_Chara_GS2(17, "G5_01F", 0);
    Voice_PlayVoice("R0808000_Q01600", #1, "");
    Message_Who(17);
    Message_MsgDisp("Arisawa", "Yes. The manager has returned, too.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("R0808000_Q01700", #1, "");
    Message_Who(17);
    Message_MsgDisp("Arisawa", "You've really helped out today.\nThank you.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah, don't mention it.");
    Voice_PlayVoice("R0808000_H01800", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Come on, let's go....\nAh, just leave the apron on. Hurry!");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay!\nExcuse me, but I'll be leaving now!");
    Music_StopBGM(0, 40);
    Message_CloseMsg();
    Screen_WipeOut(2);
    Character_Chara_GS2(8, "NON");
    Character_Chara_GS2(17, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_CarBGOpen2("BG_EX170_AU_1");
    Still_Event("EV_08_30", #1, 0, 60);
    Still_StillFace(0, 0, 1);
    Screen_WipeIn(2);
    Voice_PlayVoice("R0808000_H01900", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "............");
    Message_Who(0);
    Message_MsgDisp("主人公", "It doesn't look like the traffic\nwill move any time soon...");
    Still_StillFace(0, 0, 2);
    Still_StillFace(0, 3, 0);
    Voice_PlayVoice("R0808000_H02000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah...\nThis is what they call the Christmas\njam...\nAh, we're moving.");
    SoundEffect_PlayStream(2, "SS_DSE_004_000");
    Background_CarBGScroll(0);
    Background_CarBGScroll(#1);
    Background_CarBgSpeedChange(#4, 120);
    System_Wait(80);
    Still_StillFace(0, 0, 3);
    Voice_PlayVoice("R0808000_H02100", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Alright, we're almost out of the\njam....\nIt looks like you'll be a little\nlate, though.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I should apologize for that...)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Background_CarBGOpen2("BG_EX170_AU_2");
    Still_Event("EV_08_30", #1, 0, 5);
    Still_StillFace(0, 0, 2);
    Character_BlinkStart(8, 2, (#1));
    Background_CarBGScroll(0);
    Screen_WipeIn(2);
    Voice_PlayVoice("R0808000_H02200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "This road is closed, too...\nI don't think the snow's that bad...");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Sorry...");
    Still_StillFace(0, 2, 6);
    Still_StillFace(0, 3, 3);
    Voice_PlayVoice("R0808000_H02300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... You've got bad habits.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ugh......");
    Still_StillFace(0, 2, 2);
    Character_BlinkStart(8, 2, (#1));
    Still_StillFace(0, 3, 1);
    Voice_PlayVoice("R0808000_H02400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "......... The party's already over.");
    Message_Who(0);
    Message_MsgDisp("主人公", "... Yeah......");
    Still_StillFace(0, 0, 4);
    Voice_PlayVoice("R0808000_H02500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "... Alright.\nSince we're not gonna make it, let's\ntake the long way there.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    Voice_PlayVoice("R0808000_H02600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Relax, I'll take you all the way to\nthe ski lodge.\nAh, you'd better call your teacher.");
    Message_Who(0);
    Message_MsgDisp("主人公", "O-Okay.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(The long way? Where are we going?)");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Effect_CloseParticle();
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "(............ Huh? Uhh.........)");
    Background_CarBGOpen2("BG_EX170_AU_2");
    Background_CarBGScroll(0);
    Background_CarBGScroll(#1);
    Background_CarBgSpeedChange(#8, 8);
    Still_Event("EV_08_30", #1, 0, 5);
    Still_StillFace(0, 0, 3);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Ah! D...Did I fall asleep?");
    Voice_PlayVoice("R0808000_H02700", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah, for about 10 minutes.\nWell, it can't be helped.\nYou must be tired from work.");
    Still_StillFace(0, 2, 4);
    Character_BlinkStart(8, 2, (#1));
    Still_StillFace(0, 3, 3);
    Voice_PlayVoice("R0808000_H02800", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "But you've woken up at quite a good\ntime.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh?");
    SoundEffect_PlayStream(3, "SS_T_00_229_M00");
    Background_CarBgSpeedChange(0, 180);
    System_Wait(180);
    Still_StillFace(0, 0, 4);
    Voice_PlayVoice("R0808000_H02900", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "We're here. Let's go outside.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay......");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    SoundEffect_StopStream(3, 40);
    SoundEffect_PlayStream(3, "SS_T_00_227_M00");
    System_Wait(30);
    SoundEffect_PlayStream(3, "SS_T_00_242_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "Wah......!");
    Still_Event("EV_08_14", #1, 0, 60);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_X_00_R08_D00", 127, 40);
    Voice_PlayVoice("R0808000_H03000", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "How should I put it...\nYou don't need words to describe\nthis kinda view.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes......");
    Still_StillFace(0, 0, 1);
    Voice_PlayVoice("R0808000_H03100", 8, "R0808000_H03101");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Ah～.... ｛主人公｝.\nIt's a day early, but Merry\nChristmas.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Eh......?");
    Still_StillFace(0, 2, 0);
    Voice_PlayVoice("R0808000_H03200", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "I didn't think I'd be able to spend\nthe day with you, so I didn't get\nyou a present.\nSorry.");
    Voice_PlayVoice("R0808000_H03300", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "You'll have to make do with this\nview.");
    Message_Who(0);
    Message_MsgDisp("主人公", "This is a present enough......!");
    Voice_PlayVoice("R0808000_H03400", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Thanks for saying that.");
    Voice_PlayVoice("R0808000_H03500", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "You might be annoyed that you missed\nyour party and things ended up like\nthis...");
    Voice_PlayVoice("R0808000_H03600", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "...\nBut to me, this is the best\nChristmas Eve.\nI'm grateful to the Gods.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Masaki＊＊｝...");
    Still_StillFace(0, 0, 0);
    Still_StillFace(0, 7, 1);
    Still_StillFace(0, 7, 0);
    Still_Approach(8, 222, 0, 0, 1, 1);
    Voice_PlayVoice("R0808000_H03700", #1, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Your teachers will get worried if\nyou're late, so it's about time we\nleft.");
    Still_ApproachEnd();
    Message_Who(0);
    Message_MsgDisp("主人公", "Yes.");
    Message_CloseMsg();
    Screen_WipeOut(2);
    Still_Event("");
    Screen_ClearScreen();
    Music_StopBGM(0, 40);
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Character_BlinkStart(8, 2, (#1));
    Character_ChFace(0, 3, 3);
    Character_Chara_GS2(8, "M8_01F", 0);
    Background_Bg_GS2("BG_SC830_WI_2", #1, #1, 0);
    Screen_WipeIn(2);
    Message_Who(0);
    Message_MsgDisp("主人公", "Thank you very much for today,\n｛Masaki＊＊｝.");
    Voice_PlayVoice("R0808000_H03800", 8, "");
    Message_Who(8);
    Message_MsgDisp("Masaki", "Yeah, later....\nGoodnight, ｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Goodnight.");
    Character_Chara_GS2(8, "NON");
    SoundEffect_PlayStream(3, "SS_T_00_241_M00");
    System_Wait(30);
    SoundEffect_PlayStream(3, "SS_T_00_242_M00");
    System_Wait(120);
    SoundEffect_PlayStream(3, "SS_T_00_218_M00");
    Message_Who(0);
    Message_MsgDisp("主人公", "(This is how Christmas Eve ended...)");
    Message_CloseMsg();
    SoundEffect_StopStream(3, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(8, 86, 1);
    Parameter_AddCh1Param(8, 61, 5);
    Parameter_AddCh1Param(8, 60, 3);
    }
