section "r09_m4_000"{
    Character_ChFace(0, 3, 3);
    Character_Chara_GS2(4, "M4_10F", 0);
    Background_Bg_GS2("BG_TR120_WI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGD_028_000", 127, 40);
    Voice_PlayVoice("R0904000_D00000", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yo.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Yo, ｛Hariya＊＊｝.");
    Character_ChFace(0, 2, 4);
    Character_BlinkStart(4, 2, (#1));
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("R0904000_D00100", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Hey, wanna take the lift to the\nhighest possible spot?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?! The highest spot...");
    Character_ChFace(0, 2, 1);
    Voice_PlayVoice("R0904000_D00200", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Yeah!\nThat legendary spot where the best\nskier said they had trouble with it.");
    Message_Who(0);
    Message_MsgDisp("主人公", "It's impossible for us!");
    Character_ChFace(0, 0, 9);
    Character_BlinkStart(4, 3, (#1));
    Voice_PlayVoice("R0904000_D00300", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "So it's no good...\nI wanted to experience the best part\nof the snowy mountains, too.");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Hariya＊＊｝ really likes\nthe sound of \"the best\"...)");
    Character_BlinkStart(4, 0, (#1));
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 5);
    Voice_PlayVoice("R0904000_D00400", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "Then I'll drop it....\nIn return, you gotta ski with me.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Huh?");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 1);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("R0904000_D00500", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "... Because it's Christmas! I...\nwanna be with you. How about it?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay! Let's ski together!");
    Character_ChFace(0, 0, 10);
    Character_ChFace(0, 4, 1);
    Voice_PlayVoice("R0904000_D00600", #1, "");
    Message_Who(4);
    Message_MsgDisp("Hariya", "A...Alright! Let's go!");
    Character_Chara_GS2(4, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "(I had fun at the ski lodge with\n｛Hariya＊＊｝.)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(4, 86, 1);
    }
