section "r09_m5_000"{
    Background_Bg_GS2("BG_TR120_WI_0", #1, #1, 0);
    Screen_WipeIn(2);
    Music_PlayBGM(0, "MN_BGD_028_000", 127, 40);
    Message_Who(0);
    Message_MsgDisp("主人公", "(*Phew* Finally, I was able to bring\nmyself to the top...\nI'm exhausted.)");
    Character_ChFace(0, 0, 0);
    Character_Chara_GS2(5, "M5_10F", 0);
    Voice_PlayVoice("", 5, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "｛主人公｝.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Oh, ｛Chris＊＊｝.");
    Character_ChFace(0, 2, 2);
    Character_ChFace(0, 3, 3);
    Voice_PlayVoice("R0905000_E00000", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Looks like you were having a fight\nwith the snow.");
    Message_Who(0);
    Message_MsgDisp("主人公", "Ugh...\nwere you looking at me all this\ntime?");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(5, 3, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("R0905000_E00100", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Yeah.\nYou're too cute when you're upset on\nthe slippery ice, sorry.");
    Message_Who(0);
    Message_MsgDisp("主人公", "You're mean!");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("R0905000_E00200", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Haha, I said I'm sorry!");
    Character_ChFace(0, 0, 3);
    Voice_PlayVoice("R0905000_E00300", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "By the way, I've got this thing I\nwanted to do.\nWould you like to join me?");
    Message_Who(0);
    Message_MsgDisp("主人公", "Hmm? What is it?");
    Voice_PlayVoice("R0905000_E00400", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "I want to build a snowman.");
    Message_Who(0);
    Message_MsgDisp("主人公", "｛Chris＊＊｝ never made\none.");
    Character_ChFace(0, 2, 3);
    Character_BlinkStart(5, 2, (#1));
    Character_ChFace(0, 3, 0);
    Voice_PlayVoice("R0905000_E00500", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Indeed. And also you...\nYou must be tired from that struggle\na while ago, right?");
    Voice_PlayVoice("R0905000_E00600", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Now's the chance to take a break\nfrom it.\nSo, how about it?");
    Message_Who(0);
    Message_MsgDisp("主人公", "*Giggles* Let's do that.");
    Character_ChFace(0, 0, 10);
    Voice_PlayVoice("R0905000_E00700", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Great.\nAn addition to Chris's lovely\nmemories in his precious album.");
    Voice_PlayVoice("R0905000_E00800", #1, "");
    Message_Who(5);
    Message_MsgDisp("Chris", "Let's make a big one and brag about\nit to everyone!");
    Message_Who(0);
    Message_MsgDisp("主人公", "Okay!");
    Character_Chara_GS2(5, "NON");
    Message_Who(0);
    Message_MsgDisp("　　　", "　　　　　　・\n　　　　　　・\n　　　　　　・");
    Message_Who(0);
    Message_MsgDisp("主人公", "(｛Chris＊＊｝ and I made a\nhuge snowman.\nI had fun at the ski lodge.)");
    Message_CloseMsg();
    Music_StopBGM(0, 40);
    Screen_WipeOut(1);
    Screen_ClearScreen();
    Parameter_AddCh1Param(5, 86, 1);
    }
